### PR TITLE
invoice: avoid negative msat amounts

### LINKED ISSUE #636: Invoice with negative amount breaks LND
LND allows creating invoice with negative amount:
`lncli addinvoice --memo "broken" --value "-10"`

Which causes `lncli listinvoices` to fail with:
`"error": "2 UNKNOWN: unable to decode payment request: amount 18446744073709451616 pBTC not expressible in msat"`

Same goes with `lncli decodepayreq`:
```
$ lncli decodepayreq lnbc18446744073709451616p1pdxytcypp5tupcauu6qggpsad2n9s48ntkgewztp7vjylw7954933r27pslfmqdq2vfex76m9dccqzysh3m06h5ewty3a05f5ezn790um5fgzlf2qv0kqgrlkueth7yjhsdnam3rd9p5nexyz3qy7vtaadufdawahgx5eksjhl8200kggw74dtspmakq02
[lncli] rpc error: code = Unknown desc = amount 18446744073709451616 pBTC not expressible in msat
```

Solution: implement checking in `addinvoice` to prevent generating invoice with negative amount.

Broken LND can be fixed by removing malformed invoice from `channel.db` manually.

### PR DESCRIPTION
**Pull request by wilmerpaulino**
Fixes #636.

### CODE REVIEW

File: zpay32/invoice.go [hunk 1]
```diff
@@ -514,6 +514,11 @@ func validateInvoice(invoice *Invoice) error {
 		return fmt.Errorf("net params not set")
 	}
 
+	if invoice.MilliSat != nil && *invoice.MilliSat < 0 {
```
Comment (halseth) [inline zpay32/invoice.go]: Add short comment.

File: zpay32/amountunits.go [hunk 2]
```diff
@@ -127,6 +127,11 @@ func decodeAmount(amount string) (lnwire.MilliSatoshi, error) {
 // encodeAmount encodes the provided millisatoshi amount using as few characters
 // as possible.
 func encodeAmount(msat lnwire.MilliSatoshi) (string, error) {
+	if msat < 0 {
+		return "", fmt.Errorf("unable to encode negative amount: %v",
```
Comment (halseth) [inline zpay32/amountunits.go]: It should say that negative amounts are not allowed. Maybe "amount must be positive: %v"? :)

**Comment by wilmerpaulino** [comment]
Rebased to master and addressed comments.
