### PR TITLE
wtclient: replay pending and unacked updates

### LINKED ISSUE #7725: [Doc]: Wrong comment in handleStaleTower function coment
The comment in the handlesStaleTower function seems to be same as the one in the handleNewTower function

https://github.com/lightningnetwork/lnd/blob/c3a2368f46af05120defd1eccfef6f51c73d19da/watchtower/wtclient/client.go#L1248-L1251

### PR DESCRIPTION
**Pull request by ellemouton**
This PR demonstrates 2 main issues and then fixes them:

1. If `backupTasks` have been "bound" to a session's `pendingQueue` and then the associated Tower is removed, those pending updates are just quietly lost at the moment. This PR makes sure that these tasks are replayed onto the main task pipeline.
2. If a `CommittedUpdate` has been persisted but the session does not respond with an Ack and then the client requests to remove the tower, this will currently fail with "tower has unacked updates". This is fixed by also replaying these updates onto the main task pipeline.

With this PR, the tower client can shutdown as soon as it is requested to since any un-acked updates or pending updates will just be persisted. This is nice since there will no longer be a 10 second wait on shutdown :) 

Fixes https://github.com/lightningnetwork/lnd/issues/4420
Fixes #7725

### CODE REVIEW

**Comment by ellemouton** [comment]
@Bladez1753 , accidental comment?

**Comment by ellemouton** [comment]
note to myself to checkout this failure: https://github.com/lightningnetwork/lnd/actions/runs/5011209617/jobs/8981798576?pr=6895

File: watchtower/wtclient/client.go [hunk 1]
```diff
@@ -698,101 +680,44 @@ func (c *TowerClient) Stop() error {
...
-		// 1. Shutdown the backup queue, which will prevent any further
-		// updates from being accepted. In practice, the links should be
-		// shutdown before the client has been stopped, so all updates
-		// would have been added prior.
-		err := c.pipeline.Stop()
-		if err != nil {
-			c.log.Errorf("could not stop backup queue: %v", err)
+		// 3. Shutdown the backup queue, which will prevent any further
+		// updates from being accepted.
+		if err := c.pipeline.Stop(); err != nil {
```
Comment (guggero) [inline watchtower/wtclient/client.go:707]: I'm not sure if maybe this change in order could be the cause for the unit race failure?
I was able to reproduce it locally with `env CGO_ENABLED=1 GORACE="history_size=7 halt_on_errors=1" go test -tags="dev nolog lowscrypt" -test.timeout=3m -test.count=1 -race github.com/lightningnetwork/lnd/watchtower/wtclient` and saw that the clients are blocked on https://github.com/lightningnetwork/lnd/blob/450e3b1011e2f351531d2df25c40481823da83d9/watchtower/wtclient/session_queue.go#L260.
I don't have the full context of how the session/pipeline/client interact, so I could be totally wrong.

File: watchtower/wtclient/client_test.go [hunk 2]
```diff
@@ -1214,12 +1215,9 @@ var clientTests = []clientTest{
...
 
-			// Force quit the client to abort the state updates it
-			// has queued. The sleep ensures that the session queues
-			// have enough time to commit the state updates before
-			// the client is killed.
-			time.Sleep(time.Second)
-			h.client.ForceQuit()
+			// Stop the client to abort the state updates it has
+			// queued.
+			require.NoError(h.t, h.client.Stop())
```
Comment (guggero) [inline watchtower/wtclient/client_test.go:1220]: This is where things hang in the unit race in case that helps.

File: watchtower/wtclient/session_queue.go [hunk 3]
```diff
@@ -151,41 +152,74 @@ func newSessionQueue(cfg *sessionQueueConfig,
...
+			unAckedUpdates[update.BackupID] = true
+		}
 
-// ForceQuit idempotently aborts any clean shutdown in progress and returns to
-// he caller after all lingering goroutines have spun down.
-func (q *sessionQueue) ForceQuit() {
-	q.forced.Do(func() {
-		q.log.Infof("SessionQueue(%s) force quitting...", q.ID())
+		// of each session onto the task pipeline.
+		q.queueCond.L.Lock()
```
Comment (guggero) [inline watchtower/wtclient/session_queue.go:224]: Hmm, do we ever unlock this? Maybe this is the problem and you can ignore my previous comment.

Comment (guggero) [reply watchtower/wtclient/session_queue.go:224]: I added a `defer q.queueCond.L.Unlock()` here and ran the tests a couple of times. The race deadlock didn't happen anymore, but 1 out of 4 runs failed with:
```
--- FAIL: TestClient (0.00s)
    --- FAIL: TestClient/committed_update_restart (2.04s)
        client_test.go:1234: 
                Error Trace:    /home/guggero/projects/go/src/github.com/lightningnetwork/lnd/watchtower/wtclient/client_test.go:1011
                                                        /home/guggero/projects/go/src/github.com/lightningnetwork/lnd/watchtower/wtclient/client_test.go:1234
                                                        /home/guggero/projects/go/src/github.com/lightningnetwork/lnd/watchtower/wtclient/client_test.go:2456
                Error:          Should be true
                Test:           TestClient/committed_update_restart
                Messages:       breach hints not received, only got 2/3
    --- FAIL: TestClient/can_remove_tower_with_un-acked_updates_(with_restart) (6.23s)
        client_test.go:2441: Received 2/3
        client_test.go:2441: Received 2/3
        client_test.go:2441: Received 2/3
        client_test.go:2441: Received 2/3
        client_test.go:2441: 
                Error Trace:    /home/guggero/projects/go/src/github.com/lightningnetwork/lnd/watchtower/wtclient/client_test.go:1011
                                                        /home/guggero/projects/go/src/github.com/lightningnetwork/lnd/watchtower/wtclient/client_test.go:2441
                                                        /home/guggero/projects/go/src/github.com/lightningnetwork/lnd/watchtower/wtclient/client_test.go:2456
                Error:          Should be true
                Test:           TestClient/can_remove_tower_with_un-acked_updates_(with_restart)
                Messages:       breach hints not received, only got 2/3
FAIL
FAIL    github.com/lightningnetwork/lnd/watchtower/wtclient     19.992s
```

So something's flaky either way.

**Review by guggero — COMMENTED** [review]
Code looks good, very nice to have these two bugs fixed :100: 
Tried to look into the unit race failure but wasn't 100% successful. Maybe my couple of pointers help.

File: watchtower/wtclient/client.go (hunk 1 above)
Comment (ellemouton) [reply watchtower/wtclient/client.go]: replied to the other comment :)

**Review by ellemouton — COMMENTED** [review]
Thanks for the review @guggero! 🙏 

Found and fixed the flake :) basically: there was a chance that `AcceptTask` could be called which would add a task to the pending queue _after_ the queue had already been shutdown. 

Also realised that there was a chance that `prevTask` of the `Client` could be left unhandled. 

So the main changes are:
1. `prevTask` is re-added to the pipeline on Stop if it is non-nil
2. a new session queue status is added: `sessionQueueShuttingDown`
3. `AcceptTask` first checks if the session queue has started shutting down before doing anything. If it has, then `sessionQueueShuttingDown` is returned and the client will then handle this appropriately by assigning the left over task to `prevTask` (which is then handled in step 1 when the client is being shut down)

**Comment by saubyk** [comment]
Concept Ack

**Review by guggero — APPROVED** [review]
Great fixes, LGTM :tada:

**Review by bitromortac — APPROVED** [review]
LGTM :zap:, great to have a proper way to clean up watchtowers, nice work! Only minor nits left :rocket:.

**Comment by saubyk** [comment]
We got the approvals. Retagged it for 0.17.0
