### PR TITLE
graph/db: fix SetSourceNode no rows error

### LINKED ISSUE #10370: Unable to create server due to `sql: no rows in result set`
From this [build](https://github.com/lightningnetwork/lnd/actions/runs/19332527590/job/55298890408?pr=10364#logs), which used the following setup,
```
make itest-parallel tranches=8 backend=bitcoind dbbackend=sqlite nativesql=true tags=test_native_sql
```

The failed logs,
```
2025-11-13 13:27:59.526 [WRN] LTND config.go:879: open /tmp/itest-self_node_announcement_persistence-Alice-15-1763040476173382397/lnd.conf: no such file or directory
2025-11-13 13:27:59.527 [INF] LTND lnd.go:186: Version Info version=0.20.99-beta commit=v0.20.0-beta-37-g40d09a9b1 debuglevel=development logging=debug
2025-11-13 13:27:59.527 [INF] LTND lnd.go:213: Network Info active_chain=Bitcoin network=regtest
2025-11-13 13:27:59.528 [DBG] ARPC autopilot_server.go:140: Autopilot RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] NTFR chain_server.go:210: ChainNotifier RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] NTFR chain_server.go:214: ChainKit RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] NRPC neutrino_server.go:141: Neutrino RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] SGNR signer_server.go:216: Signer RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] VRPC server.go:66: Versioner RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] WLKT walletkit_server.go:344: WalletKit RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] DRPC dev_server.go:137: DEV RPC server successfully registered with root the gRPC server
2025-11-13 13:27:59.528 [DBG] IRPC invoices_server.go:190: Invoices RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] PRPC peers_server.go:119: Peers RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [DBG] RRPC router_server.go:301: Router RPC server successfully registered with root gRPC server
2025-11-13 13:27:59.528 [INF] RPCS lnd.go:923: RPC server listening on 127.0.0.1:10502
2025-11-13 13:27:59.530 [DBG] ARPC autopilot_server.go:163: Autopilot REST server successfully registered with root REST server
2025-11-13 13:27:59.530 [DBG] NTFR chain_server.go:237: ChainNotifier REST server successfully registered with root REST server
2025-11-13 13:27:59.530 [DBG] NTFR chain_server.go:248: ChainKit REST server successfully registered with root REST server
2025-11-13 13:27:59.533 [DBG] NRPC neutrino_server.go:164: Neutrino REST server successfully registered with root REST server
2025-11-13 13:27:59.534 [DBG] SGNR signer_server.go:239: Signer REST server successfully registered with root REST server
2025-11-13 13:27:59.534 [DBG] VRPC server.go:89: Versioner REST server successfully registered with root REST server
2025-11-13 13:27:59.535 [DBG] WLKT walletkit_server.go:367: WalletKit REST server successfully registered with root REST server
2025-11-13 13:27:59.540 [DBG] DRPC dev_server.go:160: DEV REST server successfully registered with the root REST server
2025-11-13 13:27:59.541 [DBG] IRPC invoices_server.go:213: Invoices REST server successfully registered with root REST server
2025-11-13 13:27:59.541 [DBG] PRPC peers_server.go:142: Peers REST server successfully registered with root REST server
2025-11-13 13:27:59.541 [DBG] RRPC router_server.go:324: Router REST server successfully registered with root REST server
2025-11-13 13:27:59.542 [INF] RPCS lnd.go:1044: gRPC proxy started at 127.0.0.1:10503
2025-11-13 13:27:59.542 [INF] LTND config_builder.go:993: Opening the main database, this might take a few minutes...
2025-11-13 13:27:59.549 [INF] LTND config_builder.go:1041: Creating local graph and channel state DB instances
2025-11-13 13:27:59.550 [INF] CHDB db.go:1686: Checking for schema update: latest_version=33, db_version=33
2025-11-13 13:27:59.550 [INF] CHDB db.go:1780: Applying 2 optional migrations
2025-11-13 13:27:59.551 [INF] CHDB db.go:1784: Checking for optional update: name=prune_revocation_log
2025-11-13 13:27:59.551 [DBG] CHDB db.go:1788: Skipping optional migration: name=prune_revocation_log as it is not specified in the config
2025-11-13 13:27:59.551 [INF] CHDB db.go:1784: Checking for optional update: name=gc_decayed_log
2025-11-13 13:27:59.551 [DBG] CHDB db.go:1798: Skipping optional migration: name=gc_decayed_log as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000001_invoices' (version 1) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000002_amp_invoices' (version 2) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000003_invoice_events' (version 3) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000004_invoice_expiry_fix' (version 4) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000005_migration_tracker' (version 5) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000006_invoice_migration' (version 6) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration 'kv_invoice_migration' (version 7) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000007_invoice_add_settled_index' (version 8) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration '000008_graph' (version 9) as it has already been applied
2025-11-13 13:27:59.551 [INF] SQLD migrations.go:432: Skipping migration 'kv_graph_migration' (version 10) as it has already been applied
2025-11-13 13:27:59.553 [INF] LTND config_builder.go:1325: Database(s) now open (time_to_open=11.310453ms)!
2025-11-13 13:27:59.557 [INF] RPCC infrastructure.go:1545: Established connection to RPC server 127.0.0.1:10057
2025-11-13 13:27:59.557 [INF] RPCC infrastructure.go:1545: Established connection to RPC server 127.0.0.1:10057
2025-11-13 13:27:59.560 [DBG] RPCC infrastructure.go:1678: Detected bitcoind version: /Satoshi:29.0.0/
2025-11-13 13:27:59.561 [INF] RPCC infrastructure.go:1545: Established connection to RPC server 127.0.0.1:10057
2025-11-13 13:27:59.562 [INF] BTWL bitcoind_zmq_events.go:246: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:10055
2025-11-13 13:27:59.562 [INF] BTWL bitcoind_zmq_events.go:343: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:10056
2025-11-13 13:27:59.563 [DBG] RPCC infrastructure.go:1678: Detected bitcoind version: /Satoshi:29.0.0/
2025-11-13 13:27:59.566 [INF] CHRE chainregistry.go:720: Using external fee estimator http://localhost:10007/fee-estimates.json: cached=false: min update timeout=5m0s, max update timeout=20m0s
2025-11-13 13:27:59.566 [INF] LNWL estimator.go:843: Starting Web API fee estimator...
2025-11-13 13:27:59.566 [DBG] LNWL estimator.go:1011: Received response from source: {"fee_by_block_target":{"1":50000},"min_relay_feerate":1012}
2025-11-13 13:27:59.570 [INF] BTWL wallet.go:4411: Opened wallet
2025-11-13 13:27:59.572 [INF] BTWL wallet.go:1430: The wallet has been unlocked without a time limit
2025-11-13 13:27:59.612 [INF] CHRE chainregistry.go:792: LightningWallet opened
2025-11-13 13:27:59.613 [DBG] BTWL chainntfns.go:521: Birthday block has already been verified: height=0, hash=0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
2025-11-13 13:27:59.617 [INF] HSWC circuit_map.go:280: Cleaning circuits from disk for closed channels
2025-11-13 13:27:59.617 [DBG] HSWC circuit_map.go:324: Found 0 closed channels
2025-11-13 13:27:59.617 [INF] HSWC circuit_map.go:328: Finished cleaning: no closed channels found, no actions taken.
2025-11-13 13:27:59.617 [INF] HSWC circuit_map.go:497: Restoring in-memory circuit state from disk
2025-11-13 13:27:59.618 [INF] HSWC circuit_map.go:602: Payment circuits loaded: num_pending=0, num_open=0
2025-11-13 13:27:59.619 [ERR] LTND lnd.go:169: Shutting down due to error in main method err="can't set self node: unable to upsert source node: upserting node(037e10ee34f414c80687ffa3dc0f68a9b6c88254f44d0b62d5018526627cd5e6cc): sql: no rows in result set"
2025-11-13 13:27:59.621 [INF] BTWL chainntfns.go:155: Stopped waiting for wallet sync due to error: wallet shutting down
2025-11-13 13:27:59.621 [INF] LNWL estimator.go:877: Stopping web API fee estimator
2025-11-13 13:27:59.621 [INF] SQLB db.go:299: Closing database towerserverdb
2025-11-13 13:27:59.621 [INF] SQLB db.go:299: Closing database walletdb
2025-11-13 13:27:59.621 [INF] SQLB db.go:299: Closing database channeldb
2025-11-13 13:27:59.621 [INF] SQLB db.go:299: Closing database macaroondb
2025-11-13 13:27:59.622 [INF] SQLB db.go:299: Closing database decayedlogdb
2025-11-13 13:27:59.622 [INF] SQLB db.go:299: Closing database towerclientdb
2025-11-13 13:27:59.624 [INF] LTND lnd.go:152: Shutdown complete
unable to create server: can't set self node: unable to upsert source node: upserting node(037e10ee34f414c80687ffa3dc0f68a9b6c88254f44d0b62d5018526627cd5e6cc): sql: no rows in result set
```

### PR DESCRIPTION
**Pull request by ellemouton**
# Fix SetSourceNode Race Condition with Lenient Upsert

## Problem

During itest execution, the following error occurred during server startup:

```
unable to create server: can't set self node: unable to upsert source node:
upserting node(037e10ee34f414c80687ffa3dc0f68a9b6c88254f44d0b62d5018526627cd5e6cc):
sql: no rows in result set
```

This error is caused by a **race condition** where multiple goroutines call `SetSourceNode` concurrently with the same timestamp, causing the SQL store to reject the second update.

### The Race Condition

Multiple code paths in `server.go` call `SetSourceNode` during startup:

1. **`setSelfNode()`** (line 5700) - Called during server initialization
2. **`createNewHiddenService()`** (line 3325) - Called during Tor setup AND by health check goroutines
3. **`updateAndBroadcastSelfNode()`** (line 3447) - RPC handler for node updates

These paths can execute concurrently, especially during server startup when Tor is enabled.

### Race Timeline

**Initial state:** Database has source node with timestamp `T`

**Concurrent execution:**

| Thread A (setSelfNode) | Thread B (createNewHiddenService) |
|------------------------|-----------------------------------|
| Reads DB: timestamp `T` | Reads in-memory: timestamp `T` |
| Increments to `T+1` | Increments to `T+1` |
| Calls `SetSourceNode(T+1)` first | |
| ✅ Success: `T+1 > T` | |
| DB now has timestamp `T+1` | Calls `SetSourceNode(T+1)` second |
| | ❌ Fails: `T+1` NOT `> T+1` |
| | Returns `sql.ErrNoRows` |

### Why the SQL Constraint Fails

The original `UpsertNode` query has a WHERE clause that requires strictly increasing timestamps:

```sql
ON CONFLICT (pub_key, version)
    DO UPDATE SET
        alias = EXCLUDED.alias,
        last_update = EXCLUDED.last_update,
        ...
WHERE graph_nodes.last_update IS NULL
    OR EXCLUDED.last_update > graph_nodes.last_update  -- Must be strictly greater!
RETURNING id;
```

When the WHERE clause fails, **no rows are updated**, and the `RETURNING id` clause returns nothing, resulting in `sql.ErrNoRows`.

### Why the Existing Mutex Doesn't Help

The `s.mu` mutex in `genNodeAnnouncement()` only protects the in-memory `currentNodeAnn` read/write. It does NOT protect:

- Database reads in `setSelfNode`
- The entire read-modify-write cycle across different call-sites
- The actual database write in `SetSourceNode`

This is a classic **Time-of-Check to Time-of-Use (TOCTOU)** race condition.

### Use Separate UpsertSourceNode Query

Added a new SQL query `UpsertSourceNode` (in `sqldb/sqlc/queries/graph.sql`) that removes the strict timestamp constraint:

```sql
-- name: UpsertSourceNode :one
INSERT INTO graph_nodes (
    version, pub_key, alias, last_update, color, signature
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (pub_key, version)
    DO UPDATE SET
        alias = EXCLUDED.alias,
        last_update = EXCLUDED.last_update,
        color = EXCLUDED.color,
        signature = EXCLUDED.signature
    -- No WHERE clause - always updates!
RETURNING id;
```

### Code Changes

Modified `graph/db/sql_store.go` with maximum reusability:

1. **`upsertNodeAncillaryData()`** - Extracted common logic for updating features, addresses, and extra fields (shared by both upsert functions)

2. **`populateNodeParams()`** - Extracted parameter building logic using callback pattern to support both `UpsertNodeParams` and `UpsertSourceNodeParams` types

3. **`buildNodeUpsertParams()`** - Builds params for strict `UpsertNode` query

4. **`buildSourceNodeUpsertParams()`** - Builds params for lenient `UpsertSourceNode` query

5. **`upsertSourceNode()`** - New function using `UpsertSourceNode` query, reuses ancillary data helpers

6. **`upsertNode()`** - Refactored to use helper functions, eliminating code duplication

7. **`SetSourceNode()`** - Updated to call `upsertSourceNode()` instead of `upsertNode()`

### Why This is Safe

**For source node (our own node):**
- We control all updates to our own node announcement
- Last-write-wins is acceptable because all concurrent updates are valid
- Parameter changes must persist even with timestamp collisions
- Matches bbolt KV store behavior (which already uses last-write-wins)

**For other nodes (network gossip):**
- Still use strict `UpsertNode` with timestamp checking
- Maintains Lightning Network gossip protocol guarantees
- Same timestamp = same content (enforced by cryptographic signatures)
- Prevents stale network updates and replay attacks

### Before

- Concurrent source node updates with same timestamp → ❌ Second update fails with `sql.ErrNoRows`
- Parameter changes lost if timestamp doesn't advance
- Server startup could fail during Tor initialization

### After

- Concurrent source node updates with same timestamp → ✅ Both succeed (last-write-wins)
- All parameter changes persist
- Server startup succeeds reliably

### Unit Test

Updated `TestSetSourceNodeSameTimestamp` in `graph/db/graph_test.go`:

- Creates source node with timestamp `T`
- Updates with same timestamp `T` but different parameters (alias, color)
- Verifies update succeeds (no error)
- Verifies parameter changes actually persisted to database

### Why This Can Happen in Production

The race is particularly likely during:

1. **Server startup with Tor enabled**
   - `setSelfNode()` runs during `newServer()`
   - `createNewHiddenService()` runs in `Start()`
   - Health check goroutines can trigger immediately
   - All happening within the same second

2. **Fast-running tests (itests)**
   - Tight timing between initialization steps
   - Multiple rapid node updates

3. **User-triggered updates**
   - RPC calls to update node info while Tor reconnects
   - Multiple parameter changes in quick succession

Fixes #10370

### CODE REVIEW

**Comment by litbot-9000** [comment]
@ellemouton, remember to re-request review from reviewers when ready

File: graph/db/graph_test.go [hunk 1]
```diff
@@ -396,6 +397,62 @@ func TestSourceNode(t *testing.T) {
 	compareNodes(t, testNode, sourceNode)
 }
 
+// TestSetSourceNodeSameTimestamp demonstrates that SetSourceNode can return an
+// error when called with the same last update timestamp. Calling SetSourceNode
+// with the same timestamp should be allowed (unlike AddNode), as it is
+// possible that our own node announcement may change quickly. This will be
+// fixed in an upcoming commit.
+func TestSetSourceNodeSameTimestamp(t *testing.T) {
```
Comment (yyforyongyu) [inline graph/db/graph_test.go:406]: always love that we start a fix with a demo unit test!

File: sqldb/sqlc/queries/graph.sql [hunk 2]
```diff
@@ -21,6 +21,25 @@ WHERE graph_nodes.last_update IS NULL
...
+)
+ON CONFLICT (pub_key, version)
+    -- Update the following fields if a conflict occurs on pub_key
+    -- and version.
+    DO UPDATE SET
+        alias = EXCLUDED.alias,
+        last_update = EXCLUDED.last_update,
+        color = EXCLUDED.color,
+        signature = EXCLUDED.signature
+RETURNING id;
```
Comment (yyforyongyu) [inline sqldb/sqlc/queries/graph.sql:43]: I think we should check the new update has a timestamp that is at least the same? sth like `EXCLUDED.last_update >= graph_nodes.last_update`, otherwise we risk inserting outdated updates.

File: graph/db/sql_store.go [hunk 3]
```diff
@@ -3599,77 +3607,181 @@ func getNodeFeatures(ctx context.Context, db SQLQueries,
...
 	if err != nil {
-		return 0, fmt.Errorf("unable to marshal extra opaque data: %w",
+		return 0, fmt.Errorf("upserting node(%x): %w", node.PubKeyBytes,
 			err)
 	}
 
-	// Update the node's extra signed fields.
-	err = upsertNodeExtraSignedFields(ctx, db, nodeID, extra)
+	// We can exit here if we don't have the announcement yet.
+	if !node.HaveAnnouncement() {
```
Comment (yyforyongyu) [inline graph/db/sql_store.go:3777]: looks like this change should be put in its own commit given that this is a new behavior change.

File: graph/db/sql_store.go [hunk 4]
```diff
@@ -521,7 +522,14 @@ func (s *SQLStore) SetSourceNode(ctx context.Context,
...
 
 	return s.db.ExecTx(ctx, sqldb.WriteTxOpt(), func(db SQLQueries) error {
-		id, err := upsertNode(ctx, db, node)
+		// For the source node, we use a less strict upsert that allows
+		// updates even when the timestamp hasn't changed. This handles
+		// the race condition where multiple goroutines (e.g.,
+		// setSelfNode, createNewHiddenService, RPC updates) read the
+		// same old timestamp, independently increment it, and try to
+		// write concurrently. We want all parameter changes to persist,
+		// even if timestamps collide.
```
Comment (yyforyongyu) [inline graph/db/sql_store.go:531]: What if we use `upsertNode` and ignore `sql.ErrNoRows` here?

Comment (ellemouton) [reply graph/db/sql_store.go:531]: cause `upsertNode` still uses the other query which has the strict timestamp rule. For our own node, we dont want to fail to persist our own update even if the timestamp is the same as the previous one. For our own node, it actually can be the case that we persist the same update _with different info_ which is the risk

File: graph/db/sql_store.go (hunk 3 above)
Comment (ellemouton) [reply graph/db/sql_store.go:3777]: i think this is not a behaviour change? previously we just had `upsertNode` which also called `if !node.HaveAnnouncement() {` before persisting any other data

**Review by yyforyongyu — COMMENTED** [review]
Needs a rebase!

**Comment by saubyk** [comment]
@ellemouton this change needs to be back ported to `v0.20.x-branch`. Thanks.
