### PR TITLE
multi: always fail pending htlcs on commitment confirmation

### LINKED ISSUE #2045: HTLC not getting failed upstream after they timeout downstream
### Background

I see quite a lot of htlcs timing out instead of failing on mainnet, which is quite annoying because that leads to channel closing. This could be normal if the counterparty was down, but in that particular case, I was pretty sure the peer was up and operational, so I tried to find out what happened.

### Your environment

* version of `lnd`: v0.5.0-beta

### Steps to reproduce

Scenario is a payment being relayed through `eclair` and then through `lnd`:

... -----> `eclair` ----- htlcA ----->	`lnd`	----- htlcB -----> ...

htlcA  lnd_channel_id=`544814:1271:1`  expiry=545073  htlc_id=7
htlcB  lnd_channel_id=`540823:2707:1`  expiry=545069  htlc_id=15

From the point of view of `eclair`, nothing happens until block #545073 gets mined, at which point htlcA has timed out, causing `eclair` to unilaterally close the channel.

I was able to get `lnd`'s logs ([log.zip](https://github.com/lightningnetwork/lnd/files/2474665/log.zip), thanks @AndrewSamokhvalov), here is what I think are the relevant parts:

```
"October 9th 2018, 16:39:57.044",DBG,PEER,"Received UpdateAddHTLC(chan_id=b0d69f3c998bfabfc32702e55fbe0ff3e2551d91ca234c692e0fc1b0a1a8745e, id=7, amt=135635112 mSAT, expiry=545073, hash=7202da369b8dae66cb9ac6b0dec53bfe7e254efe53ebfb0d3ef6b6f1ba90d4bc) from 34.239.230.56:9735"
...
"October 9th 2018, 16:39:58.660",DBG,PEER,"Sending UpdateAddHTLC(chan_id=8c8481ae7e2a76af1691599057f2e4bafa7cad382f68eb73a9a1650ee410344d, id=15, amt=135634976 mSAT, expiry=545069, hash=7202da369b8dae66cb9ac6b0dec53bfe7e254efe53ebfb0d3ef6b6f1ba90d4bc) to 47.184.129.94:43178"
...
"October 9th 2018, 16:39:59.664",TRC,HSWC,"ChannelLink(540823:2707:1) revocation window exhausted, unable to send: 1, dangling_opens=([]channeldb.CircuitKey) (len=1 cap=1) {
 (channeldb.CircuitKey) (Chan ID=544814:1271:1, HTLC ID=7)
}
, dangling_closes([]channeldb.CircuitKey) {
}
(the above line is repeated ~100k times)
...
"October 9th 2018, 18:25:28.665",DBG,HSWC,"ChannelLink(540823:2707:1) removing Add packet (Chan ID=544814:1271:1, HTLC ID=7) from mailbox"
```
I think what happened is that the next peer in the route got unresponsive or something, and htlcB never got signed. I'm actually not sure if `lnd` sent a `commit_sig` for htlcB or not. It seems like `lnd` was waiting for a `revoke_and_ack` that never arrived, and after a while `lnd` just removed htlcB (not sure what exactly triggered this). So `lnd` didn't watch htlcB's expiry and didn't fail htlcA between blocks 545069 and 545073, which caused htlcA to eventually timeout.

### Expected behaviour

- If `lnd` sent a `commit_sig` containing htlcB, it should have watched the blockchain, closed the downstream channel after block 545069 and failed htlcA.

- If `lnd` didn't send a `commit_sig`, then it should have fast-failed htlcA

In any case the issue being between `lnd` and the next node, it shouldn't have caused the closing of the upstream channel.

### Actual behaviour

`lnd` ignored htlcA, and htlcA eventually timed out.

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we address a TOOD, and end up fixing a lingering bug related to commitments on chain. Before this commit, it was possible that `lnd` would unnecessarily cause an incoming link to force close on chain if the outgoing link was in an indeterminate state. We fix this issue by always checking for HTLCs that we need to time out on the incoming link based on all valid commits. With this fix, we'll no longer go to chain unnecessarily which wastes chain fees and may also increase off-chain HTLC fail delays. 

Fixes #2045.

### CODE REVIEW

File: contractcourt/chain_watcher.go [hunk 1]
```diff
@@ -30,20 +30,78 @@ const (
...
+	RemotePendingCommit *channeldb.ChannelCommitment
+}
+
+// toActiveHTLCSets returns the set of all active HTLCs across all commitment
+// transactions.
+func (c *CommitSet) toActiveHTLCSets() map[HtlcSetKey]htlcSet {
+	htlcSets := make(map[HtlcSetKey]htlcSet)
+
+	htlcSets[HtlcSetKey{
+		IsRemote: false, IsPending: false,
```
Comment (cfromknecht) [inline contractcourt/chain_watcher.go]: would help readability to use the defined keys, e.g. `LocalHtlcSetKey`

File: contractcourt/chain_watcher.go [hunk 2]
```diff
@@ -373,6 +431,28 @@ func (c *chainWatcher) closeObserver(spendNtfn *chainntnfs.SpendEvent) {
 			return
 		}
 
+		// Fetch the current known commit height for the remote party,
+		// and their pending commitment chain tip if it exist.
+		remoteStateNum := remoteCommit.CommitHeight
+		remoteChainTip, err := c.cfg.chanState.RemoteCommitChainTip()
+		if err != nil && err != channeldb.ErrNoPendingCommit {
+			log.Errorf("unable to obtain chain tip for "+
```
Comment (cfromknecht) [inline contractcourt/chain_watcher.go]: nit: capitalize log message

File: contractcourt/chain_watcher.go [hunk 3]
```diff
@@ -373,6 +431,28 @@ func (c *chainWatcher) closeObserver(spendNtfn *chainntnfs.SpendEvent) {
...
+				"ChannelPoint(%v): %v",
+				c.cfg.chanState.FundingOutpoint, err)
+			return
+		}
+
+		// Now that we have all the possible valid commitments, we'll
+		// make the CommitSet s the ChannelArbitrator will need it in
```
Comment (cfromknecht) [inline contractcourt/chain_watcher.go]: stray "s"

File: contractcourt/channel_arbitrator.go [hunk 4]
```diff
@@ -191,6 +191,30 @@ func newHtlcSet(htlcs []channeldb.HTLC) htlcSet {
 	}
 }
 
+// HtlcSetKey is a two-tuple that uniquely identifies a set of HTLCs on a
+// commitment transaction.
+type HtlcSetKey struct {
+	// IsResolved denotes if the HTLCs are on the remote commitment
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: `IsResolved` -> `IsRemote`

File: contractcourt/channel_arbitrator.go [hunk 5]
```diff
@@ -191,6 +191,30 @@ func newHtlcSet(htlcs []channeldb.HTLC) htlcSet {
...
+	// transaction.
+	IsRemote bool
+
+	// IsDangling denotes if the commitment transaction that HTLCS are on
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: `IsDangling` -> `IsPending`

File: contractcourt/channel_arbitrator.go [hunk 6]
```diff
@@ -209,7 +233,7 @@ type ChannelArbitrator struct {
 
 	// activeHTLCs is the set of active incoming/outgoing HTLC's on the
 	// commitment transaction.
-	activeHTLCs htlcSet
+	activeHTLCs map[HtlcSetKey]htlcSet
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: godoc needs updating

File: contractcourt/channel_arbitrator.go [hunk 7]
```diff
@@ -802,7 +837,19 @@ func (c *ChannelArbitrator) stateStep(triggerHeight uint32,
...
+		// TODO(roasbeef): not needed since we must have a commitment
+		// output in order to make an outgoing HTLC?
+		noCommitHtlcs := true
+		if confCommitSet != nil {
+			localHTLCs := len(confCommitSet.LocalCommit.Htlcs) > 0
+			remoteHTLCs := len(confCommitSet.RemoteCommit.Htlcs) > 0
+			danglingHtlcs := (confCommitSet.RemotePendingCommit != nil &&
+				len(confCommitSet.RemotePendingCommit.Htlcs) > 0)
+
+			noCommitHtlcs = !localHTLCs && !remoteHTLCs && !danglingHtlcs
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: adding a helper method to compute this would be useful, e.g. `confCommitSet.IsEmpty()`

File: contractcourt/channel_arbitrator.go [hunk 8]
```diff
@@ -1269,15 +1321,171 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+	localCommitActions, err := c.checkCommitChainActions(
+		height, trigger, activeHTLCs[LocalHtlcSet],
+	)
+	if err != nil {
+		return nil, err
+	}
+
+	// Next, we'll examine the remote commitment (and maybe a dangling one)
+	// to see if the set difference of our HTLCs is non-empty. If so, then
+	// we may need to cnacel back some HTLCs if we decide go to chain.
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: cnacel -> cancel

File: contractcourt/channel_arbitrator.go [hunk 9]
```diff
@@ -1269,15 +1321,171 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+	for htlcSetKey, htlcs := range activeHTLCs {
+		if htlcSetKey.IsRemote {
+			continue
+		}
+
+		for _, htlc := range htlcs.outgoingHTLCs {
+			localHTLCs[htlc.HtlcIndex] = htlc
+		}
+	}
+	for htlcSetKey, htlcs := range activeHTLCs {
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: the local and remote htlcs can be computed in a single pass

File: contractcourt/channel_arbitrator.go [hunk 10]
```diff
@@ -1269,15 +1321,171 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+// that are close to timing out. If we find any, then we'll return a set of
+// chain actions for HTLCs that are on our commitment, but not theirs to cancel
+// immediately.
+func (c *ChannelArbitrator) checkRemoteDanglingActions(
+	height uint32, activeHTLCs map[HtlcSetKey]htlcSet,
+	commitsConfirmed bool) ChainActionMap {
+
+	var (
+		pendingRemoteHTLCs []channeldb.HTLC
+		localHTLCs         = make(map[uint64]channeldb.HTLC)
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: looks like this can be made a `map[uint64]struct{}`

File: contractcourt/channel_arbitrator.go [hunk 11]
```diff
@@ -1269,15 +1321,171 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+	// remote commitment transaction, but not on ours.
+	for htlcIndex, htlc := range remoteHTLCs {
+		if _, ok := localHTLCs[htlcIndex]; ok {
+			continue
+		}
+
+		pendingRemoteHTLCs = append(pendingRemoteHTLCs, htlc)
+	}
+
+	// Finally, we'll examine al the pending remote HTLCs for those that
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: al -> all

File: contractcourt/channel_arbitrator.go [hunk 12]
```diff
@@ -1269,15 +1321,171 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+	// are close to expiring. If we find any, then we'll recommend that
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: should this read "have expired" instead of "close to expiring", since our outgoing broadcast delta is now zero?

File: htlcswitch/link.go [hunk 13]
```diff
@@ -1720,8 +1720,11 @@ func (l *channelLink) handleUpstreamMsg(msg lnwire.Message) {
 		// Since we just revoked our commitment, we may have a new set
 		// of HTLC's on our commitment, so we'll send them over our
 		// HTLC update channel so any callers can be notified.
+		newHTLCS := map[contractcourt.HtlcSetKey][]channeldb.HTLC{
```
Comment (cfromknecht) [inline htlcswitch/link.go]: defining a new type, e.g. `contractcourt.HtlcSets` would help cut down on the verbosity here

File: lnwallet/channel.go [hunk 14]
```diff
@@ -3035,8 +3035,10 @@ func (lc *LightningChannel) createCommitDiff(
 // The first return parameter is the signature for the commitment transaction
 // itself, while the second parameter is a slice of all HTLC signatures (if
 // any). The HTLC signatures are sorted according to the BIP 69 order of the
-// HTLC's on the commitment transaction.
-func (lc *LightningChannel) SignNextCommitment() (lnwire.Sig, []lnwire.Sig, error) {
+// HTLC's on the commitment transaction. Finally, the new set of pending HTLCs
+// for the remote party's commitment are also returned.
+func (lc *LightningChannel) SignNextCommitment() (lnwire.Sig, []lnwire.Sig, []channeldb.HTLC, error) {
```
Comment (cfromknecht) [inline lnwallet/channel.go]: nit: long line

File: contractcourt/channel_arbitrator.go [hunk 15]
```diff
@@ -851,11 +899,14 @@ func (c *ChannelArbitrator) stateStep(triggerHeight uint32,
 
 		// With the commitment broadcast, we'll then send over all
 		// messages we can send immediately.
-		err = c.cfg.DeliverResolutionMsg(pktsToSend...)
-		if err != nil {
-			// TODO(roasbeef): make sure packet sends are idempotent
-			log.Errorf("unable to send pkts: %v", err)
-			return StateError, closeTx, err
+		if len(pktsToSend) != 0 {
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: `DeliverResolutionMsg` is already a NOP for zero-length slices. if this is only for satisfying the tests, perhaps we update the tests to ignore empty slices instead of vice versa?

Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: Yeah this was added just so the test could pass. Once could argue that that current check is an underlying detail of the default `DeliverResolutionMsg` closure, so it's simply a defensive check on the part of the channel arb.

File: contractcourt/chain_watcher.go (hunk 2 above)
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: This existed before this diff, the log messages are also inconsistent in this file as is.

File: contractcourt/chain_watcher.go (hunk 1 above)
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: Fixed, forgot to update this after I aded the definitions.

**Comment by Roasbeef** [comment]
Updated with a new commit structure to ensure each of them compile.

File: contractcourt/channel_arbitrator.go (hunk 15 above)
Comment (cfromknecht) [reply contractcourt/channel_arbitrator.go]: On the other hand, one could argue that we lose a valuable testing hook, that could otherwise be used to assert the internal state machine is progressing as expected ;)

File: contractcourt/chain_watcher.go [hunk 16]
```diff
@@ -373,6 +427,28 @@ func (c *chainWatcher) closeObserver(spendNtfn *chainntnfs.SpendEvent) {
...
+		// Now that we have all the possible valid commitments, we'll
+		// make the CommitSet the ChannelArbitrator will need it in
+		// order to carry out its duty.
+		commitSet := CommitSet{
+			LocalCommit:  *localCommit,
+			RemoteCommit: *remoteCommit,
+		}
+		if remoteChainTip != nil {
+			commitSet.RemotePendingCommit = &remoteChainTip.Commitment
+		}
```
Comment (joostjager) [inline contractcourt/chain_watcher.go]: Shouldn't c.cfg.chanState.LatestCommitments() return the remotePendingCommit too, instead of fetching it separately? Or expose it as a field on OpenChannel?

File: contractcourt/chain_watcher.go [hunk 17]
```diff
@@ -30,20 +30,74 @@ const (
...
+// the CommitSet at the time of channel closure.
+type RemoteUnilateralCloseInfo struct {
+	*lnwallet.UnilateralCloseSummary
+
+	// CommitSet is the set of known valid commitments at the time the
+	// remote party's commitemnt hit the chain.
+	CommitSet CommitSet
+}
+
+// CommitSet is a collection of the set of known validate commitments at a
```
Comment (joostjager) [inline contractcourt/chain_watcher.go]: s/validate/valid

File: contractcourt/channel_arbitrator.go [hunk 18]
```diff
@@ -191,6 +191,30 @@ func newHtlcSet(htlcs []channeldb.HTLC) htlcSet {
...
+	// LocalHtlcSet is the HtlcSetKey used for local commitments.
+	LocalHtlcSet = HtlcSetKey{IsRemote: false, IsPending: false}
+
+	// RemoteHtlcSet is the HtlcSetKey used for remote commitments.
+	RemoteHtlcSet = HtlcSetKey{IsRemote: true, IsPending: false}
+
+	// RemotePendingHtlcSet is the HtlcSetKey used for dangling remote
+	// commitment transactions.
+	RemotePendingHtlcSet = HtlcSetKey{IsRemote: true, IsPending: true}
+)
```
Comment (joostjager) [inline contractcourt/channel_arbitrator.go]: Isn't it clearer to just define this as an enum? There may be an extra `||` in some if statement, but it can be worth it.

File: contractcourt/channel_arbitrator.go [hunk 19]
```diff
@@ -600,8 +626,9 @@ func (t transitionTrigger) String() string {
 // the appropriate state transition if necessary. The next state we transition
 // to is returned, Additionally, if the next transition results in a commitment
 // broadcast, the commitment transaction itself is returned.
-func (c *ChannelArbitrator) stateStep(triggerHeight uint32,
-	trigger transitionTrigger) (ArbitratorState, *wire.MsgTx, error) {
+func (c *ChannelArbitrator) stateStep(
+	triggerHeight uint32, trigger transitionTrigger,
+	confCommitSet *CommitSet) (ArbitratorState, *wire.MsgTx, error) {
```
Comment (joostjager) [inline contractcourt/channel_arbitrator.go]: `confCommitSet` unused (in this commit).

File: contractcourt/channel_arbitrator.go (hunk 18 above)
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: Also these `HtlcSetKey` fields are not used in this commit.

File: contractcourt/chain_watcher.go [hunk 20]
```diff
@@ -30,20 +30,74 @@ const (
 	maxCommitPointPollTimeout = 10 * time.Minute
 )
 
-// LocalUnilateralCloseInfo encapsulates all the informnation we need to act
-// on a local force close that gets confirmed.
+// LocalUnilateralCloseInfo encapsulates all the informnation we need to act on
```
Comment (joostjager) [inline contractcourt/chain_watcher.go]: s/informnation/information

File: contractcourt/chain_watcher.go [hunk 21]
```diff
@@ -54,7 +54,7 @@ type RemoteUnilateralCloseInfo struct {
 	*lnwallet.UnilateralCloseSummary
 
 	// CommitSet is the set of known valid commitments at the time the
-	// remote party's commitemnt hit the chain.
+	// remote party's commitment hit the chain.
```
Comment (joostjager) [inline contractcourt/chain_watcher.go]: Typo fixed in wrong commit

File: contractcourt/chain_watcher.go [hunk 22]
```diff
@@ -74,7 +74,7 @@ type CommitSet struct {
 	// RemoteCommit is the latest valid commitment for the remote party.
 	RemoteCommit channeldb.ChannelCommitment
 
-	// RemotePendingCommit if non nil, is the pending commmitment for the
+	// RemotePendingCommit if non nil, is the pending commitment for the
```
Comment (joostjager) [inline contractcourt/chain_watcher.go]: Typo fixed in wrong commit

File: contractcourt/channel_arbitrator.go [hunk 23]
```diff
@@ -1298,6 +1307,118 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+		// been confirmed, then we can move on. Otherwise, if
+		// commitments have been confirmed, then we need to cancel back
+		// *all* of the pending remote HTLCS.
+		if !goToChain && !commitsConfirmed {
+			continue
+		}
+
+		log.Tracef("ChannelArbitrator(%v): immediately "+
+			"htlc=%x about to timeout on remote commitment",
+			c.cfg.ChanPoint, htlc.RHash[:])
```
Comment (joostjager) [inline contractcourt/channel_arbitrator.go]: Log text reads not as a sentence.

File: contractcourt/channel_arbitrator.go [hunk 24]
```diff
@@ -824,7 +824,7 @@ func (c *ChannelArbitrator) stateStep(
 	case StateContractClosed:
 		// First, we'll fetch our chain actions, and both sets of
 		// resolutions so we can process them.
-		chainActions, err := c.log.FetchChainActions()
+		_, err := c.log.FetchChainActions()
```
Comment (joostjager) [inline contractcourt/channel_arbitrator.go]: Commit message says we reconstruct chain actions, but here they are still fetched from the log.

File: contractcourt/channel_arbitrator.go (hunk 7 above)
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: `CommitSet.IsEmpty` is defined, but not called here?

File: contractcourt/channel_arbitrator.go [hunk 25]
```diff
@@ -424,18 +424,24 @@ func (c *ChannelArbitrator) relaunchResolvers() error {
...
 	// db migration.
 	htlcMap := make(map[wire.OutPoint]*channeldb.HTLC)
-	chainActions, err := c.log.FetchChainActions()
-	if err != nil {
-		log.Errorf("unable to fetch chain actions: %v", err)
-		return err
-	}
-	for _, htlcs := range chainActions {
-		for _, htlc := range htlcs {
+	for _, htlcs := range c.activeHTLCs {
```
Comment (joostjager) [inline contractcourt/channel_arbitrator.go]: Make this change in the same commit where we stop writing chain actions?

File: contractcourt/briefcase.go [hunk 26]
```diff
@@ -82,17 +81,6 @@ type ArbitratorLog interface {
...
-	// LogChainActions stores a set of chain actions which are derived from
-	// our set of active contracts, and the on-chain state. We'll write
-	// this et of cations when: we decide to go on-chain to resolve a
-	// contract, or we detect that the remote party has gone on-chain.
-	LogChainActions(ChainActionMap) error
-
-	// FetchChainActions attempts to fetch the set of previously stored
-	// chain actions. We'll use this upon restart to properly advance our
-	// state machine forward.
-	FetchChainActions() (ChainActionMap, error)
```
Comment (joostjager) [inline contractcourt/briefcase.go]: I would remove this in the same commit where we stop using them, to prevent having dead code in master.

File: contractcourt/chain_watcher.go [hunk 27]
```diff
@@ -30,20 +30,91 @@ const (
...
-// on a local force close that gets confirmed.
+// LocalUnilateralCloseInfo encapsulates all the informnation we need to act on
+// a local force close that gets confirmed.
 type LocalUnilateralCloseInfo struct {
 	*chainntnfs.SpendDetail
 	*lnwallet.LocalForceCloseSummary
 	*channeldb.ChannelCloseSummary
+
+	// CommitSet is the set of known valid commitments at the time the
+	// remote party's commitemnt hit the chain.
```
Comment (alexbosworth) [inline contractcourt/chain_watcher.go]:
```suggestion
	// remote party's commitment hit the chain.
```

File: contractcourt/chain_watcher.go [hunk 28]
```diff
@@ -30,20 +30,91 @@ const (
...
+	CommitSet CommitSet
 }
 
-// CooperativeCloseInfo encapsulates all the informnation we need to act
-// on a cooperative close that gets confirmed.
+// CooperativeCloseInfo encapsulates all the informnation we need to act on a
```
Comment (alexbosworth) [inline contractcourt/chain_watcher.go]:
```suggestion
// CooperativeCloseInfo encapsulates all the information we need to act on a
```

File: contractcourt/chain_watcher.go [hunk 29]
```diff
@@ -373,6 +444,28 @@ func (c *chainWatcher) closeObserver(spendNtfn *chainntnfs.SpendEvent) {
...
+		remoteChainTip, err := c.cfg.chanState.RemoteCommitChainTip()
+		if err != nil && err != channeldb.ErrNoPendingCommit {
+			log.Errorf("unable to obtain chain tip for "+
+				"ChannelPoint(%v): %v",
+				c.cfg.chanState.FundingOutpoint, err)
+			return
+		}
+
+		// Now that we have all the possible valid commitments, we'll
+		// make the CommitSet the ChannelArbitrator will need it in
```
Comment (alexbosworth) [inline contractcourt/chain_watcher.go]:
```suggestion
		// make the CommitSet the ChannelArbitrator will need in
```

File: contractcourt/chain_watcher.go [hunk 30]
```diff
@@ -30,20 +30,91 @@ const (
...
+	// LocalCommit is the latest valid commitment for the local party.
+	LocalCommit channeldb.ChannelCommitment
+
+	// RemoteCommit is the latest valid commitment for the remote party.
+	RemoteCommit channeldb.ChannelCommitment
+
+	// RemotePendingCommit if non nil, is the pending commitment for the
+	// remote party. This is a commitment that we've sent to them, but have
+	// not yet received a revocation for.
+	RemotePendingCommit *channeldb.ChannelCommitment
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: I think in the case of HTLCSets a map is more apt given the type of manipulation we do to interact with the items. We use pointers here to signal a field that may not always be populated. This struct also has the extra `ConfCommitKey` value as well.

File: contractcourt/chain_watcher.go [hunk 31]
```diff
@@ -411,8 +504,10 @@ func (c *chainWatcher) closeObserver(spendNtfn *chainntnfs.SpendEvent) {
 		// as we don't have any further processing we need to do (we
 		// can't cheat ourselves :p).
 		if isOurCommit {
+			commitSet.ConfCommitKey = &LocalHtlcSet
+
 			if err := c.dispatchLocalForceClose(
-				commitSpend, *localCommit,
+				commitSpend, commitSet,
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: Yes, it's possible that:
  * we go to force close a channel and have what we beielve to be an update to date HTLC set
  * we write that to disk (not done anymore, but provided for the sake of the scenario)]
  * we transition states in the channel arb
  * during that we revoke a commitment and block on sending it to the channel arb
  * channel arb force closes

At that point, if we use only the in-memory state, we may miss out on some context, or in the worse case if the entire set of HTLCs has changed, then we're using stale data.

File: contractcourt/channel_arbitrator.go [hunk 32]
```diff
@@ -1269,15 +1321,164 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+		htlcActions, err = c.checkLocalChainActions(
+			height, trigger, htlcSets, true,
+		)
+
+	// If the remote commitment confirmed, then we only need to examine the
+	// remote set for any HTLCs.
+	case RemoteHtlcSet:
+		htlcActions, err = c.checkCommitChainActions(
+			height, trigger, htlcSets[RemoteHtlcSet],
+		)
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: That would be the case if there's no incoming HTLC at all, so it's a direct payment. In that case we could go to chain (as written in order to fully resolve it). However since we have an outgoing broadcast delta of zero atm, we would've went to chain anyway in order to resolve it.

File: contractcourt/channel_arbitrator.go [hunk 33]
```diff
@@ -1856,7 +2053,7 @@ func (c *ChannelArbitrator) channelAttendant(bestHeight int32) {
 			// a terminal state.
 			_, _, err = c.advanceState(
 				uint32(uniClosure.SpendingHeight),
-				remoteCloseTrigger,
+				remoteCloseTrigger, &uniClosure.CommitSet,
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: We pass in all 3 as our in memory state and what actually confirmed in the chain may have diverged.

File: contractcourt/channel_arbitrator.go [hunk 34]
```diff
@@ -802,7 +837,19 @@ func (c *ChannelArbitrator) stateStep(triggerHeight uint32,
 		// If the resolution is empty, then we're done here. We don't
 		// need to launch any resolvers, and can go straight to our
 		// final state.
-		if contractResolutions.IsEmpty() {
+		//
+		// TODO(roasbeef): not needed since we must have a commitment
+		// output in order to make an outgoing HTLC?
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: Yes that if we've made an outgoing HTLC, then due to the reserve requirements, we _must_ also have an output since we need funds to make that HTLC. However, thinking about it more: it's possible that we do have enough funds and have met the reserve, but the output is now considered dust.

File: contractcourt/chain_watcher.go [hunk 35]
```diff
@@ -30,20 +30,91 @@ const (
...
 }
 
+// RemoteUnilateralCloseInfo wraps the normal UnilateralCloseSummary to couple
+// the CommitSet at the time of channel closure.
+type RemoteUnilateralCloseInfo struct {
+	*lnwallet.UnilateralCloseSummary
+
+	// CommitSet is the set of known valid commitments at the time the
+	// remote party's commitment hit the chain.
+	CommitSet CommitSet
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: Just the HTLCs atm, but I don't think there's any harm in passing the rest in. It's also nice since the channel arb now gains _full_ context on the valid commitment state at time of channel closure.

File: contractcourt/channel_arbitrator_test.go [hunk 36]
```diff
@@ -144,27 +134,33 @@ func (*mockChainIO) GetBlock(blockHash *chainhash.Hash) (*wire.MsgBlock, error)
 }
 
 func createTestChannelArbitrator(log ArbitratorLog) (*ChannelArbitrator,
-	chan struct{}, error) {
+	chan struct{}, chan []ResolutionMsg, chan *chainntnfs.BlockEpoch, error) {
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator_test.go]: It builds, but the tests don't run. I only went for building.

File: contractcourt/chain_watcher.go (hunk 16 above)
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: Possibly, they could very well be combined but I don't think we need to do that in this PR (this is just code that was moved around). It isn't a field since this needs to be read from disk and my not be present at all.

File: contractcourt/channel_arbitrator.go (hunk 18 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: I don't think there's a big win as an enum or a struct. The struct is attractive IMO as we can add additional fields and still have the map operations work properly. They're introduced since the concept of the `HtlcSet` is also introduced in this commit.

File: contractcourt/channel_arbitrator.go (hunk 19 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: Adding it in this commit made it easier to construct the commits that came after it. I don't think there's much to be gained by moving around this small portion of the diff.

File: contractcourt/chain_watcher.go (hunk 20 above)
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: This was already there, but fixed.

File: contractcourt/channel_arbitrator.go (hunk 23 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: I don't think we have such a hard requirement. If so many other log messages would need to be modified. This is an existing log message with a swap swapped in.

File: contractcourt/channel_arbitrator.go (hunk 24 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: They're still fetched, but we don't use them.

File: contractcourt/channel_arbitrator.go (hunk 7 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: Ah messed up in the rebase somehow, should be fixed in the latest diff.

File: contractcourt/channel_arbitrator.go (hunk 25 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: I think it stands on its own as: if we've already written chain actions for this channel, then the return parameter will be properly populated.

**Comment by Roasbeef** [comment]
PTAL @cfromknecht @joostjager!

File: contractcourt/chain_watcher.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/chain_watcher.go]: In this PR, almost in everywhere a specific set is explictly picked (local, remote, remotepending). It seems that only when something comes in through `htlcUpdates`, the manipulation is easier with a map. If combined with my other comment about just storing the htlcs in `channelArbitrator` rather than the full commit tx, I think the code would be simpler, easier to understand.

File: contractcourt/channel_arbitrator.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: I am thinking about the case where we've sent commitSig only for a forwarded htlc. That htlc is then in the remote pending commit tx only. Then the remote party force closes the channel with the remote commit (not including that htlc). What makes us cancel the incoming htlc in that case?

File: contractcourt/chain_watcher.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/chain_watcher.go]: In general, I think there is harm in passing in more info than needed. The extreme is making every variable global so all code can access everything.

My preference would be to pass in just what is needed and only change that when there is a real need for the channel arbitrator to know more.

File: contractcourt/channel_arbitrator_test.go (hunk 36 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator_test.go]: Ok. I saw some tests are updated in commits though. What is the reason for leaving this build error until the end of the commit set?

File: contractcourt/channel_arbitrator.go (hunk 23 above)
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: Ok, not always clear to see in the diff what was pre-existing.

File: contractcourt/channel_arbitrator.go (hunk 24 above)
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: To me that makes the commit not completely logical. Why would you fetch them if not used?

File: contractcourt/channel_arbitrator.go (hunk 25 above)
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: But doesn't that mean that the commit where you stopped writing chain actions broke this part of the code?

File: contractcourt/chain_watcher.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: Yeah we could grab it then as well. However we'd need to then store the commitment set in a private attribute in order to have it be available for the next call to `stateStep` so we can prep the contract resolvers. Functionally, it's the same path, but IMO having the chain watcher provide this state (as it's what tells the channel arb what confirmed on chain) is more natural within this context.

File: contractcourt/channel_arbitrator.go [hunk 37]
```diff
@@ -1794,7 +1986,7 @@ func (c *ChannelArbitrator) channelAttendant(bestHeight int32) {
 			// a terminal state.
 			_, _, err = c.advanceState(
 				uint32(closeInfo.SpendingHeight),
-				localCloseTrigger,
+				localCloseTrigger, &closeInfo.CommitSet,
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: The commit set is only obtained when the chain watcher sends us message that something has confirmed on chain. We only use the commit set when prepping contract resolutions (and check for nil-ness in other areas). We only prep resolutions once a commitment has confirmed. Therefore we'll only access this when it's non-nil and a commitment has confirmed.

File: contractcourt/channel_arbitrator.go (hunk 25 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: The diff is to be taken as a whole (all the commits), if a user cherry picks some commits, but not others, then behavior will be broken. As I said earlier, the commits are constructed so things compile, but if you run things like the itests at any commit but the end, they may fail.

File: contractcourt/channel_arbitrator.go (hunk 24 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: It makes the commit diffs smaller, of course I could just do everything in a single commit. If you follow the commits step by step, it shows that we start to reconstruct, then no longer write them all together.

File: contractcourt/channel_arbitrator_test.go (hunk 36 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator_test.go]: Simply preference (I went for just building), I don't think leaving it till the end invalidates the diff or makes things any harder to review.

File: contractcourt/chain_watcher.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: I don't think we're anywhere near that extreme. I don't consider this a blocking item, there're many other areas in the codebase where we use an entire struct for convenience when we only need a few fields. It's also the case that the chain watcher already passes in the entire commitment confirmed, we just modify it to also pass in all valid commitments at time of confirmation.

File: contractcourt/channel_arbitrator.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: Ahh I see what you're getting at! Updated the tests to cover: "remote commit conf, with remote pending htlc" (htlc expired and not).

File: contractcourt/chain_watcher.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/chain_watcher.go]: > In this PR, almost in everywhere a specific set is explictly picked (local, remote, remotepending).

There're also areas where pass all 3 and examine 2 of them. The two representations are isomorphic, as a result it's up to preference which of them are used.

**Comment by Roasbeef** [comment]
PTAL @joostjager @cfromknecht

File: contractcourt/channel_arbitrator.go (hunk 37 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: But if we crash at this point, will we get the commitment confirmed signal again after restart from chain watcher?

File: contractcourt/channel_arbitrator.go (hunk 25 above)
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: I do it differently and only create commits that have no broken behaviour. I also try to get the unit tests and itests running. If that seems to be work that is reverted again in later commits, it is an indication that my commit structure isn't right. But it is something up to preference too.

File: contractcourt/channel_arbitrator.go (hunk 24 above)
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: My preference (it is a preference) is to have one logical commit that makes the change, keeping behaviour in tact.

File: contractcourt/channel_arbitrator.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: And how about the other way around, remote pending confirms, with htlc still on the remote (htlc already failed on the remote pending)?

[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: If I'm following then then that's not possible. The only way the remote pending commit can have something that a remote commit doesn't is if it was manually failed back, and the only party that can fail back HTLCs is the one that received the HTLC.

[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: If the remote pending confirms, then we just play that as is. If the remote pending has the HTLC failed, then the remote party would've needed to send us a sig, then we revoke, meaning that we also don't have the HTLC locally on our commitment transaction.

File: contractcourt/channel_arbitrator.go (hunk 37 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: Hmm yeah at an initial glance, I thought it would continue to send this information until we mark the channel as closed, which is the case, but we do so before we start to advance our state. Atm, we do so only after we finish writing the contract resolutions here: https://github.com/lightningnetwork/lnd/blob/master/contractcourt/channel_arbitrator.go#L1837

It appears that we may also need to start to write this commitment transaction information, as this state isn't stored in the `ChannelCloseSummary` which is what's available to us once we mark a channel as closed.

[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: To make this backwards compatible for old nodes (that are for the case of this scenario, "frozen" in this limbo state), then if this new piece of information isn't present, we just only play the commitment at hand.

File: contractcourt/channel_arbitrator.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: Isn't it in that case that we only cancel back our incoming htlc once we receive the revoke from the remote party? So:
* Remote party sends us a sig over a commit tx that doesn't contain the htlc anymore
* We send the revoke the to remote party
* We remove htlc from our remote tx and send a sig (it is now removed from remote pending)
* The remote party publishes that remote pending tx without sending a revoke
* What mechanism now lets us now cancel back the incoming?

[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: The only tx where the htlc is still in is the remote tx, but we don't inspect that

File: contractcourt/channel_arbitrator.go (hunk 37 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: Can this then combined with that other comment about getting the final commit sets during force close?

[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: So not passing them in from chain watcher at all anymore

File: contractcourt/briefcase.go [hunk 38]
```diff
@@ -802,6 +781,59 @@ func (b *boltArbitratorLog) FetchChainActions() (ChainActionMap, error) {
...
+		if err != nil {
+			return err
+		}
+
+		var b bytes.Buffer
+		if err := encodeCommitSet(&b, commits); err != nil {
+			return err
+		}
+
+		return scopeBucket.Put(commitSetKey, b.Bytes())
```
Comment (joostjager) [inline contractcourt/briefcase.go]: It still feels like redundant data. The commit sets are already persisted by the channel and now here again. Couldn't storing just the type of commit (local, remote, remote pending) be enough?

File: contractcourt/channel_arbitrator.go (hunk 37 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: I implemented what I described above in this latest diff. I still prefer passing the information from the chain watcher as IMO it's easier to reason about the consistency of the commitment states at that point since the channel has been closed.

File: contractcourt/briefcase.go (hunk 38 above)
Comment (Roasbeef) [reply contractcourt/briefcase.go]: Once the channel has been marked as pending closed, we no longer have access to that data since the channel close summary doesn't store the full commitment information. Once this is written, you're correct that the data is redundant, but once we proceed to the next call to mark the channel as pending close, it's the only area in the database that we store this information. Looking back upon it, it was a mistake to remove all the channel state once we moved from open -> pending close. A few times now, we've had to supplement the pending close information in order to carry out tasks like what's implemented in this PR.

Comment (joostjager) [reply contractcourt/briefcase.go]: So shouldn't that data be kept a bit longer in the channel buckets then? To prevent serializing them there when the channel is open and storing it in the new store when it is pending close?

File: contractcourt/channel_arbitrator.go (hunk 37 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply contractcourt/channel_arbitrator.go]: Ok, I thought maybe this last change changed your view on this.

File: contractcourt/briefcase.go (hunk 38 above)
Comment (Roasbeef) [reply contractcourt/briefcase.go]: It's possible for us to head back in this direction, but it's a larger change over all. We'd either need to move all that state into the current channel close summary, or modify `CloseChannel` to hold onto all the state or "move" all the channel state into a different bucket since if it lingers there, then many other sub-systems/callers will think the channel is still open.

File: contractcourt/channel_arbitrator.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: Extended the tests to cover this case.

**Comment by Roasbeef** [comment]
PTAL @cfromknecht @joostjager

File: contractcourt/channel_arbitrator.go [hunk 39]
```diff
@@ -1269,15 +1340,254 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+		height, activeHTLCs, commitsConfirmed,
+	)
+
+	// Finally, we'll merge the two set of chain actions.
+	localCommitActions.Merge(remoteDanglingActions)
+
+	return localCommitActions, nil
+}
+
+// checkRemoteChainActions examines the set of remote commitments for any HTLCs
```
Comment (cfromknecht) [inline contractcourt/channel_arbitrator.go]: godoc/name mismatch

File: contractcourt/briefcase.go [hunk 40]
```diff
@@ -82,15 +82,22 @@ type ArbitratorLog interface {
...
+	// from the database.
+	FetchConfirmedCommitSet() (*CommitSet, error)
 
 	// FetchChainActions attempts to fetch the set of previously stored
 	// chain actions. We'll use this upon restart to properly advance our
 	// state machine forward.
+	//
+	// NOTE: This method only exists in order to be able to serve nodes had
+	// channels in the process of closing before the CommitSet struct was
+	// introduced.
```
Comment (joostjager) [inline contractcourt/briefcase.go]: What is the plan to remove this eventually? Or will we never able to?

File: contractcourt/briefcase.go [hunk 41]
```diff
@@ -802,6 +781,59 @@ func (b *boltArbitratorLog) FetchChainActions() (ChainActionMap, error) {
...
+		commitSet, err := decodeComitSet(bytes.NewReader(commitSetBytes))
+		if err != nil {
+			return err
+		}
+
+		c = commitSet
+		return nil
+	})
+	if err != nil {
+		return nil, nil
```
Comment (joostjager) [inline contractcourt/briefcase.go]: `return nil, err` ?

File: contractcourt/channel_arbitrator.go [hunk 42]
```diff
@@ -1269,15 +1340,254 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+	return remoteCommitActions, nil
+}
+
+// checkRemoteDiffActions checks the set difference of the HTLCs on the remote
+// confirmed commit and remote dangling commit for HTLCS that we need to cancel
+// back. If we find any HTLCs on the remote pending but not the remote, then
+// we'll mark them to be failed immediately.
+func (c *ChannelArbitrator) checkRemoteDiffActions(height uint32,
+	activeHTLCs map[HtlcSetKey]htlcSet,
+	pendingConf bool) ChainActionMap {
```
Comment (joostjager) [inline contractcourt/channel_arbitrator.go]: I think it would be clearer to pass in the two set keys instead of the boolean. Make it a more generic diff "htlcs in B but not in A". Then what A and B are can be specified in `checkRemoteChainActions`.

File: contractcourt/channel_arbitrator.go [hunk 43]
```diff
@@ -1269,15 +1340,254 @@ func (c *ChannelArbitrator) isPreimageAvailable(hash lntypes.Hash) (bool,
...
+	// the CommitSet was introduced. In this case, we'll just return the
+	// existing ChainActionMap they had on disk.
+	if confCommitSet == nil {
+		return c.log.FetchChainActions()
+	}
+
+	// Otherwise we have the full commitment set written to disk, and can
+	// proceed as normal.
+	htlcSets := confCommitSet.toActiveHTLCSets()
+	switch *confCommitSet.ConfCommitKey {
```
Comment (joostjager) [inline contractcourt/channel_arbitrator.go]: Make it is an idea to take out the call to `checkCommitChainActions` from `checkLocalChainActions` and `checkRemoteChainActions` and put it here. It is clear then that we always check the confirmed commit and use the switch only to merge the 'extra' actions.

File: contractcourt/briefcase.go (hunk 38 above)
Comment (joostjager) [reply contractcourt/briefcase.go]: If it touches many other sub-systems, I can imagine it is a bigger change. It seems to me that only persisting commit txes in the channel state (where they already are stored) is a cleaner solution, but probably to big of a refactoring for now.

File: contractcourt/briefcase.go (hunk 40 above)
Comment (Roasbeef) [reply contractcourt/briefcase.go]: Remove the method? All new channels don't need it, but prior channels do. Once those old channels have been fully resolved (only those in the process of being closed as this PR lands), then it's no longer needed. No current plan to remove it atm (we're able to do so), but we can discuss such a plan offline.

File: contractcourt/channel_arbitrator.go (hunk 43 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: It's just a matter of following the function to see that `checkCommitChainActions` is called first. It also states something along these lines in the `godoc` comments of each of the methods.

File: contractcourt/channel_arbitrator.go (hunk 42 above)
Comment (Roasbeef) [reply contractcourt/channel_arbitrator.go]: If we actually need to generalize it in the future, then it's a small diff away. Atm, we only care about pending or not.
