### PR TITLE
channeldb+lnwallet: store updates the peer should sign under new key

### LINKED ISSUE #4134: remote side force-closed the channel after err=rejected commitment
### Background

As stated, the channel is unexpectedly closed by remote side

### Your environment

* lnd 0.9.2
* Gentoo Linux, kernel 4.19.89-v7l+ , Raspberry Pi 4
* bitcoind 0.19.1.0
* the remote side also has lnd 0.9.2 

Note that there were 2 channels between those nodes:
* ChannelLink(621728:1134:1) - this is the closed one
* ChannelLink(621755:921:0) - this is another one, not closed

Issues #1727 and #1737 seem similar, but they are rather old, so not very interesting I guess.

### Steps to reproduce

Not sure how to reproduce, including relevant parts of lnd log. I checked twice that there are no relevant messages between 17:58 and 18:18, and between 18:18 and 18:43 (checked using regex `(621728:1134:1)|(02d22)|(621755:921:0)|(a1a3fe)`)
```
2020-03-31 17:36:38.077 [INF] PEER: Disconnecting 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b
8a88@[scrubbed], reason: Peer 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88@[scrubbed] no answer for 5m0s -- disconnecting
2020-03-31 17:36:38.078 [INF] PEER: unable to read message from 02d22df3b3013af15a2da1381bdd76266a9375040a5152b6
7999ad32a26e6b8a88@[scrubbed]: read tcp 192.168.1.213:9735->[scrubbed]: use of closed networ
k connection
...
2020-03-31 17:36:38.480 [INF] HSWC: Removing channel link with ChannelID(bd9e44810b9df031519542d85c9f08052cc9a07
9f7b0f805fcc8fab255fea3a0)
2020-03-31 17:36:38.480 [INF] HSWC: ChannelLink(621728:1134:1): stopping
2020-03-31 17:36:38.580 [INF] HSWC: ChannelLink(621728:1134:1): exited
2
...
2020-03-31 17:36:41.828 [INF] PEER: NodeKey(02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88) loading ChannelPoint(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1)
2020-03-31 17:36:41.840 [INF] HSWC: Removing channel link with ChannelID(bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0)
2020-03-31 17:36:41.840 [INF] HSWC: ChannelLink(621728:1134:1): starting
2020-03-31 17:36:41.841 [INF] HSWC: Trimming open circuits for chan_id=621728:1134:1, start_htlc_id=0
2020-03-31 17:36:41.841 [INF] HSWC: Adding live link chan_id=bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0, short_chan_id=621728:1134:1
2020-03-31 17:36:41.841 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1)
2020-03-31 17:36:41.841 [INF] HSWC: ChannelLink(621728:1134:1): HTLC manager started, bandwidth=975005500 mSAT
2020-03-31 17:36:41.843 [INF] HSWC: ChannelLink(621728:1134:1): attempting to re-resynchronize
2020-03-31 17:36:41.842 [INF] SRVR: Negotiated chan series queries with 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88
2020-03-31 17:36:41.845 [INF] DISC: Creating new GossipSyncer for peer=02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88
2020-03-31 17:36:42.708 [INF] HSWC: ChannelLink(621728:1134:1): received re-establishment message from remote side
...
2020-03-31 17:55:52.549 [INF] PEER: unable to read message from 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88@[scrubbed_ip_addr_2]: EOF
2020-03-31 17:55:52.549 [INF] PEER: Disconnecting 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88@[scrubbed_ip_addr_2], reason: read handler closed
2020-03-31 17:55:52.850 [INF] DISC: Removing GossipSyncer for peer=02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88
2020-03-31 17:55:52.953 [INF] HSWC: ChannelLink(621728:1134:1): stopping
2020-03-31 17:55:53.054 [INF] HSWC: ChannelLink(621728:1134:1): exited
...
2020-03-31 17:58:39.066 [INF] SRVR: Finalizing connection to 02d22df3b3013af15a2da1381bdd76266a9375040a5152b6799
9ad32a26e6b8a88@[scrubbed_ip_addr_2], inbound=true
2020-03-31 17:58:39.165 [INF] PEER: NodeKey(02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88) 
loading ChannelPoint(8385033801fde5026d82ebba018da612d0bee5837728f3fc01d8c300788780b0:0)
...
2020-03-31 17:58:39.475 [INF] PEER: NodeKey(02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88) loading ChannelPoint(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1)
2020-03-31 17:58:39.485 [INF] HSWC: Removing channel link with ChannelID(bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0)
2020-03-31 17:58:39.486 [INF] HSWC: ChannelLink(621728:1134:1): starting
2020-03-31 17:58:39.486 [INF] HSWC: Trimming open circuits for chan_id=621728:1134:1, start_htlc_id=0
2020-03-31 17:58:39.486 [INF] HSWC: Adding live link chan_id=bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0, short_chan_id=621728:1134:1
2020-03-31 17:58:39.487 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1)
2020-03-31 17:58:39.487 [INF] HSWC: ChannelLink(621728:1134:1): HTLC manager started, bandwidth=975005500 mSAT
2020-03-31 17:58:39.487 [INF] HSWC: ChannelLink(621728:1134:1): attempting to re-resynchronize
2020-03-31 17:58:39.489 [INF] SRVR: Negotiated chan series queries with 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88
2020-03-31 17:58:39.489 [INF] DISC: Creating new GossipSyncer for peer=02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88
2020-03-31 17:58:39.807 [INF] HSWC: ChannelLink(621755:921:0): received re-establishment message from remote side
2020-03-31 17:58:39.808 [INF] HSWC: ChannelLink(621728:1134:1): received re-establishment message from remote side
2020-03-31 17:58:40.530 [INF] HSWC: ChannelLink(621728:1134:1): sending 1 updates to synchronize the state
2020-03-31 17:58:41.625 [ERR] HSWC: ChannelLink(621728:1134:1): failing link: ChannelPoint(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1): received error from peer: chan_id=bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0, err=rejected commitment: commit_height=23, invalid_commit_sig=30440220426432dde354bf77b06aa588c23c7892d30a2c1e1214663f3cdf029ea6c7d4a402202f13960df26a50d2b0988b33851fbf61597b8c2de116b6d0307ebf9a34a0c264, commit_tx=0200000001bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a10100000000958844800245420f000000000016001440584ebd06390f2bf791b64e67636048c8badee423d2160000000000220020b4fc4194cdac1679f3c71ccad222a53371b0a6533dfa3d680e7554d5fb9b5ba0735ea320, sig_hash=9fd9944691915268e64100c3515a4efc000c9b9d9030de4b978f36866f472a56
2020-03-31 17:58:41.626 [ERR] HSWC: ChannelLink(621728:1134:1): link failed, exiting htlcManager
2020-03-31 17:58:41.626 [INF] HSWC: ChannelLink(621728:1134:1): exited
2020-03-31 17:58:41.626 [INF] HSWC: Removing channel link with ChannelID(bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0)
2020-03-31 17:58:41.626 [INF] HSWC: ChannelLink(621728:1134:1): stopping
2020-03-31 17:58:42.395 [INF] SRVR: New inbound connection from 127.0.0.1:57056
2020-03-31 17:58:42.395 [INF] PEER: Disconnecting 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b
8a88@[addr3], reason: server: disconnecting peer 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999
ad32a26e6b8a88@[addr3]
2020-03-31 17:58:42.396 [INF] PEER: unable to read message from 02d22df3b3013af15a2da1381bdd76266a9375040a5152b6
7999ad32a26e6b8a88@[addr3]: read tcp 192.168.1.213:9735->[addr3]: use of closed network co
nnection
2020-03-31 17:58:42.705 [INF] DISC: Removing GossipSyncer for peer=02d22df3b3013af15a2da1381bdd76266a9375040a515
2b67999ad32a26e6b8a88
2020-03-31 17:58:42.706 [INF] HSWC: Removing channel link with ChannelID(b080877800c3d801fcf3287783e5bed012a68d0
1baeb826d02e5fd0138038583)
2020-03-31 17:58:42.707 [INF] HSWC: ChannelLink(621755:921:0): stopping
2020-03-31 17:58:42.808 [INF] HSWC: ChannelLink(621755:921:0): exited
2020-03-31 17:58:42.808 [INF] SRVR: Finalizing connection to 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88@127.0.0.1:57056, inbound=true
2020-03-31 17:58:42.809 [INF] PEER: Disconnecting 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88@127.0.0.1:57056, reason: unable to start peer: unable to send init msg: write tcp 127.0.0.1:9735->127.0.0.1:57056: write: broken pipe
2020-03-31 17:58:45.821 [INF] DISC: Broadcasting 188 new announcements in 19 sub batches
2020-03-31 17:58:47.674 [INF] SRVR: New inbound connection from [addr3]
2020-03-31 17:58:47.676 [INF] SRVR: Finalizing connection to 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88@[addr3], inbound=true
2020-03-31 17:58:47.722 [INF] PEER: NodeKey(02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88) 
loading ChannelPoint(8385033801fde5026d82ebba018da612d0bee5837728f3fc01d8c300788780b0:0)
2020-03-31 17:58:48.339 [INF] HSWC: Removing channel link with ChannelID(b080877800c3d801fcf3287783e5bed012a68d0
1baeb826d02e5fd0138038583)
2020-03-31 17:58:48.340 [INF] HSWC: ChannelLink(621755:921:0): starting
2020-03-31 17:58:48.340 [INF] HSWC: Trimming open circuits for chan_id=621755:921:0, start_htlc_id=3
2020-03-31 17:58:48.340 [INF] HSWC: Adding live link chan_id=b080877800c3d801fcf3287783e5bed012a68d01baeb826d02e
5fd0138038583, short_chan_id=621755:921:0
2020-03-31 17:58:48.345 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(8385033801fde5026d82eb
ba018da612d0bee5837728f3fc01d8c300788780b0:0)
2020-03-31 17:58:48.345 [INF] HSWC: ChannelLink(621755:921:0): HTLC manager started, bandwidth=2477983000 mSAT
2020-03-31 17:58:48.346 [INF] HSWC: ChannelLink(621755:921:0): attempting to re-resynchronize
2020-03-31 17:58:48.402 [INF] PEER: NodeKey(02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88) 
loading ChannelPoint(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1)
2020-03-31 17:58:48.414 [INF] HSWC: Removing channel link with ChannelID(bd9e44810b9df031519542d85c9f08052cc9a07
9f7b0f805fcc8fab255fea3a0)
2020-03-31 17:58:48.415 [INF] HSWC: ChannelLink(621728:1134:1): starting
2020-03-31 17:58:48.415 [INF] HSWC: Trimming open circuits for chan_id=621728:1134:1, start_htlc_id=0
2020-03-31 17:58:48.415 [INF] HSWC: Adding live link chan_id=bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0, short_chan_id=621728:1134:1
2020-03-31 17:58:48.415 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1)
2020-03-31 17:58:48.416 [INF] HSWC: ChannelLink(621728:1134:1): HTLC manager started, bandwidth=975005500 mSAT
2020-03-31 17:58:48.416 [INF] HSWC: ChannelLink(621728:1134:1): attempting to re-resynchronize
2020-03-31 17:58:48.416 [INF] SRVR: Negotiated chan series queries with 02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88
2020-03-31 17:58:48.418 [INF] DISC: Creating new GossipSyncer for peer=02d22df3b3013af15a2da1381bdd76266a9375040a5152b67999ad32a26e6b8a88
2020-03-31 17:58:48.420 [INF] HSWC: ChannelLink(621755:921:0): received re-establishment message from remote side
2020-03-31 17:58:48.421 [INF] HSWC: ChannelLink(621728:1134:1): received re-establishment message from remote side
2020-03-31 17:58:49.775 [INF] HSWC: ChannelLink(621728:1134:1): sending 1 updates to synchronize the state
...
2020-03-31 18:18:14.180 [INF] NANN: Announcing channel(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b8
1449ebd:1) disabled [detected]
...
2020-03-31 18:18:49.726 [INF] NANN: Announcing channel(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b8
1449ebd:1) enabled
....
2020-03-31 18:43:39.609 [INF] UTXN: Attempting to graduate height=623780: num_kids=0, num_babies=0
2020-03-31 18:43:39.616 [WRN] HSWC: ChannelLink(621728:1134:1): remote peer has closed on-chain
2020-03-31 18:43:39.616 [INF] CNCT: ChannelArbitrator(a1a3fe55b2fac8fc05f8b0f779a0c92c05089f5cd842955131f09d0b81449ebd:1): remote party has closed channel out on-chain
2020-03-31 18:43:39.617 [INF] HSWC: ChannelLink(621728:1134:1): exited
2020-03-31 18:43:39.617 [INF] HSWC: Removing channel link with ChannelID(bd9e44810b9df031519542d85c9f08052cc9a079f7b0f805fcc8fab255fea3a0)
2020-03-31 18:43:39.618 [INF] HSWC: ChannelLink(621728:1134:1): stopping


```

### Expected behaviour

The channel should not be closed.

### Actual behaviour

The channel is force-closed.

### LINKED ISSUE #4137: Unexpected error during itests: attempted to restore an unsigned remote update
Saw the following error during flakehunting MPP itests at commit https://github.com/lightningnetwork/lnd/pull/3970/commits/163bdea9eeca422563f1761cc5fed034d6169927

```
--- FAIL: TestLightningNetworkDaemon (50.68s)
    lnd_test.go:15022: Running 58 integration tests
    --- FAIL: TestLightningNetworkDaemon/sendtoroute_multi_path_payment (26.62s)
        lnd_test.go:105: Failed: (sendtoroute multi path payment): exited with error:
            *errors.errorString unable to close channel: rpc error: code = Unknown desc = attempted to restore an unsigned remote update: log_index=1
            /Users/johan/golang/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:296 (0x19cf5b7)
            	closeChannelAndAssertType: t.Fatalf("unable to close channel: %v", err)
            /Users/johan/golang/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:271 (0x1a23b72)
            	testSendToRouteMultiPath.func1.1: return closeChannelAndAssertType(ctx, t, net, node, fundingChanPoint, false, force)
            /Users/johan/golang/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:271 (0x1a23b35)
            	closeChannelAndAssert: return closeChannelAndAssertType(ctx, t, net, node, fundingChanPoint, false, force)
            /Users/johan/golang/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_mpp_test.go:369 (0x19c20c7)
            	testSendToRouteMultiPath: }
            /Users/johan/golang/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:128 (0x19ce77a)
            	(*harnessTest).RunTestCase: testCase.test(h.lndHarness, h)
            /Users/johan/golang/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:15043 (0x1a3dfbc)
            	TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase)
            /usr/local/Cellar/go@1.13/1.13.9/libexec/src/testing/testing.go:909 (0x1107eb9)
            	tRunner: fn(t)
            /usr/local/Cellar/go@1.13/1.13.9/libexec/src/runtime/asm_amd64.s:1357 (0x10612e1)
            	goexit: BYTE	$0x90	// NOP
FAIL
FAIL	github.com/lightningnetwork/lnd/lntest/itest	51.003s
FAIL
make: *** [flakehunter] Error 1
```

Attaching logs from the run
[logs.zip](https://github.com/lightningnetwork/lnd/files/4415430/logs.zip)

### LINKED ISSUE #4246: Channels often become inactive
### Background

After upgrade to 0.10 channels quickly become inactive, for an unknown reason.
I have a simple script to kick inactive channels every couple of hours, e.g.
`lncli disconnect 030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f ; sleep 5; lncli connect 030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f@52.50.244.44:9735 # bitrefill 2`
but that doesn't seem right, and channels tend to close in couple of days after that.
Cant verify if its 0.10 fault as I don't have older node running, or the problem is somewhere else.
Dont know how to debug this as well.

### Your environment

* version of `lnd`  
v0.10.0-beta
* which operating system (`uname -a` on *Nix) 
`Linux lnd2 4.15.0-66-generic` `Ubuntu 18.04.4 LTS`  
* version of `btcd`, `bitcoind`, or other backend 
`neutrino`
* any other relevant environment details

### Steps to reproduce

Just run 0.10 for a while

### Expected behaviour

channels always stay active and don't close randomly

### Actual behaviour

channels become inactive and randomly close

### LINKED ISSUE #4263: 0.10 LND force closing channels with older nodes
### Background

Describe your issue here.
0.10 node force closing channels with: 020-05-07 18:18:11.517 [ERR] HSWC: ChannelLink(612081:1755:1): failing link: ChannelPoint(b99fc7d8823c324e940ff8997c7689110c63a475798fe7a1cb338ba1e1961552:1): unable to accept new commitment: not enough HTLC signatures. with error: invalid commitment
### Your environment

* version of `lnd`
I have two nodes, one on 0.09 (with wumbo enabled) and one on 0.10 (no patches).

* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

Not sure but I created a wumbo invoice on the 0.10 node and attempted paying it with a 0.09 wumbo enabled node. There were errors paying even with a direct channel and plenty of inbound capacity.

I cleanly restarted and the 0.10 node force closed.

The logs for 0.10 node force closing the channel are at the end of this snippet: 

https://paste.ubuntu.com/p/Snww6ZdGpZ/

### LINKED ISSUE #4435: My node force-closed channel with bfx-lnd1, not sure why
### Background

My node foce-closed channel with bfx-lnd0 so I opened a new one with bfx-lnd1 and my node also closed this channel.
I did not do anything to foce-close the channel.

Here are  some of the logs:
```

2020-06-13 13:35:54.946 [INF] NTFN: New spend subscription: spend_id=43, outpoint=97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0, script=0 036081b2f5cd128d16f2b3d8a2b84c88d6d4a0cd8da6f210a70fe42f15704578, height_hint=634553
2020-06-13 13:35:54.947 [INF] NTFN: Dispatching historical spend rescan for outpoint=97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0, script=0 036081b2f5cd128d16f2b3d8a2b84c88d6d4a0cd8da6f210a70fe42f15704578, start=634553, end=634557
2020-06-13 13:35:59.113 [INF] CNCT: Close observer for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) active
2020-06-13 13:36:02.915 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=634558
2020-06-13 13:39:25.380 [INF] PEER: NodeKey(03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6) loading ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-13 13:39:25.591 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-15 00:58:45.513 [INF] NANN: Announcing channel(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) disabled [detected]
2020-06-15 01:05:41.320 [INF] PEER: NodeKey(03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6) loading ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-15 01:05:41.371 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-15 01:24:42.805 [INF] NANN: Announcing channel(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) enabled
2020-06-15 06:22:10.190 [INF] PEER: NodeKey(03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6) loading ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-15 06:22:10.359 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-15 06:47:39.087 [INF] NTFN: New spend subscription: spend_id=33, outpoint=97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0, script=0 036081b2f5cd128d16f2b3d8a2b84c88d6d4a0cd8da6f210a70fe42f15704578, height_hint=634826
2020-06-15 06:47:39.088 [INF] NTFN: Dispatching historical spend rescan for outpoint=97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0, script=0 036081b2f5cd128d16f2b3d8a2b84c88d6d4a0cd8da6f210a70fe42f15704578, start=634826, end=634830
2020-06-15 06:47:40.140 [INF] CNCT: Close observer for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) active
2020-06-15 06:47:46.584 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=634830
2020-06-15 06:49:23.447 [INF] PEER: NodeKey(03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6) loading ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-15 06:49:23.453 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-15 07:08:30.179 [INF] NANN: Announcing channel(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) disabled [detected]
2020-06-15 07:08:38.753 [INF] NANN: Announcing channel(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) enabled
2020-06-18 05:02:24.279 [INF] PEER: NodeKey(03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6) loading ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-18 05:02:24.287 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-18 07:37:34.851 [INF] PEER: NodeKey(03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6) loading ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-18 07:37:34.940 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0)
2020-06-18 08:26:58.994 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): force closing chan
2020-06-18 08:27:00.393 [INF] CNCT: Broadcasting force close transaction 8c50b676a62297640067a6bab7b12ef4c3a198610e13f00e29b6a92ec00837a6, ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): (*wire.MsgTx)(0x40031b7280)({
   PreviousOutPoint: (wire.OutPoint) 97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0,
2020-06-18 08:27:02.114 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): trigger chainTrigger moving from state StateCommitmentBroadcasted to StateCommitmentBroadcasted
2020-06-18 08:36:02.981 [INF] NTFN: Dispatching confirmed spend notification for outpoint=97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0, script=0 036081b2f5cd128d16f2b3d8a2b84c88d6d4a0cd8da6f210a70fe42f15704578 at current height=635268: 8c50b676a62297640067a6bab7b12ef4c3a198610e13f00e29b6a92ec00837a6[0] spending 97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0 at height=635268
2020-06-18 08:36:03.001 [INF] CNCT: Local unilateral close of ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) detected
2020-06-18 08:36:03.102 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): local on-chain channel close
2020-06-18 08:36:05.414 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): trigger localCloseTrigger moving from state StateCommitmentBroadcasted to StateContractClosed
2020-06-18 08:36:05.687 [INF] UTXN: Incubating Channel(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) num-htlcs=1
2020-06-18 08:36:05.845 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): still awaiting contract resolution
2020-06-19 11:47:39.724 [INF] CNCT: *contractcourt.commitSweepResolver(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): Sweeping with witness type: CommitmentTimeLock
2020-06-19 11:47:39.726 [INF] CNCT: *contractcourt.commitSweepResolver(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): sweeping commit output
2020-06-19 14:31:00.335 [INF] CNCT: *contractcourt.commitSweepResolver(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): commit tx fully resolved by sweep tx: b6b0ec3eb12eee7f0f43f89f1d43d63724bae9cf69cff91a37854473a130b4f4
2020-06-19 14:31:00.597 [INF] UTXN: Removed channel 97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0 from nursery store
2020-06-19 14:31:00.664 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): a contract has been fully resolved!
2020-06-19 14:31:00.664 [INF] CNCT: ChannelArbitrator(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0): still awaiting contract resolution
2020-06-19 14:31:00.730 [INF] CNCT: ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) has been fully resolved on-chain at height=635422
2020-06-19 14:31:00.730 [INF] CNCT: Marking ChannelPoint(97face4492e046ac5734ddb92dcc41fcc6e82d89f59f8c9fa4d4d47f5ec8d49b:0) fully resolved
```
### Your environment

0.10.1
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux
bitcoind

Thanks

### PR DESCRIPTION
**Pull request by Crypt-iQ**
This PR fixes a long-standing force close bug. Currently, when we send a revoke for our current commitment, we store all of the remote log updates that we need to sign for. Similarly, this PR stores the local log updates that the remote needs to sign for once we receive a revocation.

Fixes #4263 
Fixes #4435 
Fixes #4134
Fixes #4137
Fixes #4134 
Fixes #4246

### CODE REVIEW

File: channeldb/channel.go [hunk 1]
```diff
@@ -72,6 +72,11 @@ var (
 	// for in one of our remote commits.
 	unsignedAckedUpdatesKey = []byte("unsigned-acked-updates-key")
 
+	// peerUnsignedAckedUpdatesKey is an entry in the channel bucket that
```
Comment (Roasbeef) [inline channeldb/channel.go:75]: To avoid ambiguity with the above key, how about: `remoteUnsignedLocalUpdates`?

File: channeldb/channel.go [hunk 2]
```diff
@@ -1440,6 +1445,38 @@ func (c *OpenChannel) UpdateCommitment(newCommitment *ChannelCommitment,
...
 
+		// Persist the peer unsigned acked updates that are not included
+		// in our new commitment.
+		updateBytes := chanBucket.Get(peerUnsignedAckedUpdatesKey)
+		if updateBytes == nil {
+			return nil
+		}
+
+		r := bytes.NewReader(updateBytes)
+		updates, err := deserializeLogUpdates(r)
```
Comment (Roasbeef) [inline channeldb/channel.go:1456]: Error ignored.

File: channeldb/channel.go [hunk 3]
```diff
@@ -1440,6 +1445,38 @@ func (c *OpenChannel) UpdateCommitment(newCommitment *ChannelCommitment,
...
+
+		var validUpdates []LogUpdate
+
+		for _, upd := range updates {
+			lIdx := upd.LogIndex
+
+			// Check if it's not on our local commitment
+			if lIdx >= newCommitment.LocalLogIndex {
```
Comment (Roasbeef) [inline channeldb/channel.go:1467]: No need for the intermediate variable here? (assuming if fits within the char limit)

File: channeldb/channel.go [hunk 4]
```diff
@@ -2065,6 +2102,38 @@ func (c *OpenChannel) UnsignedAckedUpdates() ([]LogUpdate, error) {
 	return updates, nil
 }
 
+// PeerUnsignedAckedUpdates retrieves the persisted, unsigned acked local log
+// updates that the peer still needs to sign for.
+func (c *OpenChannel) PeerUnsignedAckedUpdates() ([]LogUpdate, error) {
```
Comment (Roasbeef) [inline channeldb/channel.go:2110]: Comment about key name above applies here too.

File: lnwallet/channel.go [hunk 5]
```diff
@@ -1904,6 +2014,43 @@ func (lc *LightningChannel) restorePendingRemoteUpdates(
...
+		logUpdate := logUpdate
+
+		payDesc, err := lc.localLogUpdateToPayDesc(
+			&logUpdate, lc.remoteUpdateLog, remoteCommitmentHeight,
+		)
+		if err != nil {
+			return err
+		}
+
+		if payDesc.EntryType == Add {
```
Comment (Roasbeef) [inline lnwallet/channel.go:2035]: The comment in `localLogUpdateToPayDesc` claims an add will never be returned.

File: lnwallet/channel.go [hunk 6]
```diff
@@ -1904,6 +2014,43 @@ func (lc *LightningChannel) restorePendingRemoteUpdates(
...
+			continue
+		}
+
+		// We don't save Adds so we don't need to handle them here.
+		switch payDesc.EntryType {
+		case FeeUpdate:
+			lc.localUpdateLog.restoreUpdate(payDesc)
+
+		default:
+			// settle/fail/malformed fail
```
Comment (Roasbeef) [inline lnwallet/channel.go:2045]: Comment should be a complete sentence.

File: lnwallet/channel.go [hunk 7]
```diff
@@ -1904,6 +2014,43 @@ func (lc *LightningChannel) restorePendingRemoteUpdates(
...
+			lc.localUpdateLog.restoreUpdate(payDesc)
```
Comment (Roasbeef) [inline lnwallet/channel.go:2046]: Alternative way to express this logic: 
```go
lc.localUpdateLog.restoreUpdate(payDesc)

if payDesc.EntryType != FeeUpdate {
    lc.remoteUpdateLog.markHtlcModified(payDesc.ParentIndex)
}
```

File: lnwallet/channel.go [hunk 8]
```diff
@@ -4573,6 +4720,60 @@ func (lc *LightningChannel) ReceiveRevocation(revMsg *lnwire.RevokeAndAck) (
 		}
 	}
 
+	var localPeerUpdates []channeldb.LogUpdate
```
Comment (Roasbeef) [inline lnwallet/channel.go:4723]: Should move this into its own function as this method is already pretty long.

File: lnwallet/channel.go [hunk 9]
```diff
@@ -4573,6 +4720,60 @@ func (lc *LightningChannel) ReceiveRevocation(revMsg *lnwire.RevokeAndAck) (
...
+
+		if pd.LogIndex < remoteMessageIndex && pd.LogIndex >= localMessageIndex {
+			// This is a settle/fail that is on the remote commitment, but
+			// not on the local commitment. We expect this update to be
+			// covered in the next commitment signature the remote sends.
+			logUpdate := channeldb.LogUpdate{
+				LogIndex: pd.LogIndex,
+			}
+
+			// don't save adds
```
Comment (Roasbeef) [inline lnwallet/channel.go:4741]: Comment should be a complete sentence.

File: lnwallet/channel.go [hunk 10]
```diff
@@ -4573,6 +4720,60 @@ func (lc *LightningChannel) ReceiveRevocation(revMsg *lnwire.RevokeAndAck) (
...
+	// We use the remote commitment chain's tip as it will soon become the tail
+	// once advanceTail is called.
+	remoteMessageIndex := lc.remoteCommitChain.tip().ourMessageIndex
+	localMessageIndex := lc.localCommitChain.tail().ourMessageIndex
+
+	for e := lc.localUpdateLog.Front(); e != nil; e = e.Next() {
+		pd := e.Value.(*PaymentDescriptor)
+
+		if pd.LogIndex < remoteMessageIndex && pd.LogIndex >= localMessageIndex {
+			// This is a settle/fail that is on the remote commitment, but
```
Comment (Roasbeef) [inline lnwallet/channel.go:4734]: Style nit: move the comment to reside _above_ the if statement?

File: lnwallet/channel.go [hunk 11]
```diff
@@ -4573,6 +4720,60 @@ func (lc *LightningChannel) ReceiveRevocation(revMsg *lnwire.RevokeAndAck) (
...
+			// not on the local commitment. We expect this update to be
+			// covered in the next commitment signature the remote sends.
+			logUpdate := channeldb.LogUpdate{
+				LogIndex: pd.LogIndex,
+			}
+
+			// don't save adds
+			if pd.EntryType == Add {
```
Comment (Roasbeef) [inline lnwallet/channel.go:4742]: This can be moved to reside outside the if statement so we can skip them early.

Comment (Crypt-iQ) [reply lnwallet/channel.go]: done

File: lnwallet/channel.go (hunk 10 above)
Comment (Crypt-iQ) [reply lnwallet/channel.go]: Should this always be the case? What if there's an `else`?

File: lnwallet/channel.go (hunk 9 above)
Comment (Crypt-iQ) [reply lnwallet/channel.go]: Mb, fixed.

File: lnwallet/channel.go (hunk 7 above)
Comment (Crypt-iQ) [reply lnwallet/channel.go]: Done

**Comment by Roasbeef** [comment]
New sporadic itests log error failure (looks to be unrelated to this PR): 
> <time> [ERR] HSWC: ChannelLink(<chan>): outgoing htlc(<hex>) has insufficient fee: expected 612500, got 1112

File: channeldb/channel.go [hunk 12]
```diff
@@ -79,6 +79,11 @@ var (
 	// for in one of our remote commits.
 	unsignedAckedUpdatesKey = []byte("unsigned-acked-updates-key")
 
+	// remoteUnsignedLocalUpdatesKey is an entry in the channel bucket that
+	// contains the local updates that the remote party has acked, but
+	// has not yet signed for in onr of their local commits.
+	remoteUnsignedLocalUpdatesKey = []byte("remote-unsigned-local-updates-key")
```
Comment (Roasbeef) [inline channeldb/channel.go:85]: 👍

File: channeldb/channel.go [hunk 13]
```diff
@@ -2073,6 +2112,38 @@ func (c *OpenChannel) UnsignedAckedUpdates() ([]LogUpdate, error) {
...
+// RemoteUnsignedLocalUpdates retrieves the persisted, unsigned local log
+// updates that the remote still needs to sign for.
+func (c *OpenChannel) RemoteUnsignedLocalUpdates() ([]LogUpdate, error) {
+	var updates []LogUpdate
+	err := kvdb.View(c.Db, func(tx kvdb.RTx) error {
+		chanBucket, err := fetchChanBucket(
+			tx, c.IdentityPub, &c.FundingOutpoint, c.ChainHash,
+		)
+		switch err {
+		case nil:
```
Comment (Roasbeef) [inline channeldb/channel.go:2124]: Could make this slightly more explicit by adding a `break` statement below this case. Otherwise, at a glance, it looks like it can fall through to the lower case statement, causing it to return `nil` when the bucket is actually found.

File: lnwallet/channel.go [hunk 14]
```diff
@@ -1904,6 +2014,34 @@ func (lc *LightningChannel) restorePendingRemoteUpdates(
...
+		payDesc, err := lc.localLogUpdateToPayDesc(
+			&logUpdate, lc.remoteUpdateLog, remoteCommitmentHeight,
+		)
+		if err != nil {
+			return err
+		}
+
+		lc.localUpdateLog.restoreUpdate(payDesc)
+
+		if payDesc.EntryType != FeeUpdate {
```
Comment (Roasbeef) [inline lnwallet/channel.go:2037]: Could add a comment here that only adds are stored under this key, so we only need this special case for fee updates.

File: channeldb/db_test.go [hunk 15]
```diff
@@ -398,7 +398,7 @@ func TestRestoreChannelShells(t *testing.T) {
 	if err != ErrNoRestoredChannelMutation {
 		t.Fatalf("able to mutate restored channel")
 	}
-	err = channel.AdvanceCommitChainTail(nil)
+	err = channel.AdvanceCommitChainTail(nil, nil)
```
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply channeldb/db_test.go:401]: Yes we should

**Comment by Roasbeef** [comment]
The failing race condition test look unrelated: 
```
--- FAIL: TestFundingManagerMaxPendingChannels (5.93s)
    fundingmanager_test.go:2845: peer did not send FundingLocked message
```

File: lnwallet/channel.go [hunk 16]
```diff
@@ -1527,6 +1527,100 @@ func (lc *LightningChannel) logUpdateToPayDesc(logUpdate *channeldb.LogUpdate,
...
+// re-insert the original entries back into the update log so we'll be expecting
+// the peer to sign them. The height of the remote commitment is expected to be
+// provided and we restore all log update entries with this height, even though
+// the real height may be lower. In the way these fields are used elsewhere, this
+// doesn't change anything.
+func (lc *LightningChannel) localLogUpdateToPayDesc(logUpdate *channeldb.LogUpdate,
+	remoteUpdateLog *updateLog, commitHeight uint64) (*PaymentDescriptor,
+	error) {
+
+	// The logUpdate here won't ever be an Add.
```
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply lnwallet/channel.go]: PTAL at comment

File: lnwallet/channel.go [hunk 17]
```diff
@@ -1527,6 +1527,100 @@ func (lc *LightningChannel) logUpdateToPayDesc(logUpdate *channeldb.LogUpdate,
...
+			Amount: lnwire.NewMSatFromSatoshis(
+				btcutil.Amount(wireMsg.FeePerKw),
+			),
+			EntryType:                FeeUpdate,
+			addCommitHeightRemote:    commitHeight,
+			removeCommitHeightRemote: commitHeight,
+		}, nil
+
+	default:
+		return nil, errors.New("unknown message type")
```
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply lnwallet/channel.go]: Done

File: lnwallet/channel.go (hunk 14 above)
Comment (Crypt-iQ) [reply lnwallet/channel.go:2090]: PTAL at comment

File: channeldb/db_test.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply channeldb/db_test.go:401]: Not entirely sure how this would look.

**Comment by Crypt-iQ** [comment]
> The failing race condition test look unrelated:
> 
> ```
> --- FAIL: TestFundingManagerMaxPendingChannels (5.93s)
>     fundingmanager_test.go:2845: peer did not send FundingLocked message
> ```

Yes race condition is unrelated. Addressed all comments but Conner's about including tests for `AdvanceCommitChainTail`.

File: channeldb/channel.go [hunk 18]
```diff
@@ -2102,7 +2173,9 @@ func (c *OpenChannel) InsertNextRevocation(revKey *btcec.PublicKey) error {
 // rectify the situation. This method will add the current commitment for the
 // remote party to the revocation log, and promote the current pending
 // commitment to the current remote commitment.
-func (c *OpenChannel) AdvanceCommitChainTail(fwdPkg *FwdPkg) error {
+func (c *OpenChannel) AdvanceCommitChainTail(fwdPkg *FwdPkg,
```
Comment (halseth) [inline channeldb/channel.go:2176]: nit: godoc should be updated to explain the new argument

File: lnwallet/channel.go [hunk 19]
```diff
@@ -1527,6 +1527,101 @@ func (lc *LightningChannel) logUpdateToPayDesc(logUpdate *channeldb.LogUpdate,
...
+	// never be an Add.
+	switch wireMsg := logUpdate.UpdateMsg.(type) {
+
+	// For HTLCs that we settled, we'll fetch the original offered HTLC from
+	// the remote update log so we can retrieve the same PaymentDescriptor that
+	// ReceiveHTLCSettle would produce.
+	case *lnwire.UpdateFulfillHTLC:
+		ogHTLC := remoteUpdateLog.lookupHtlc(wireMsg.ID)
+
+		if ogHTLC.addCommitHeightRemote == 0 {
```
Comment (halseth) [inline lnwallet/channel.go:1553]: is this necessary? Didn't we fix that in the previous PR?

File: lnwallet/channel.go [hunk 20]
```diff
@@ -1873,7 +1975,12 @@ func (lc *LightningChannel) restoreStateLogs(
 		return err
 	}
 
-	return nil
+	// Restore unsigned acked local log updates so we expect the peer to
+	// sign for them.
+	err = lc.restorePeerLocalUpdates(
```
Comment (Roasbeef) [inline lnwallet/channel.go:1980]: Style nit: can just return the method directly here since it only has a single return value.

File: lnwallet/channel.go (hunk 19 above)
Comment (Crypt-iQ) [reply lnwallet/channel.go]: This is the opposite side, I moved it to where the other side lives in `restoreStateLogs`

File: channeldb/channel.go (hunk 18 above)
Comment (Crypt-iQ) [reply channeldb/channel.go:2178]: PTAL @ comment
