### PR TITLE
cmd: Add passphrase confirmation when creating wallet from existing seed

### LINKED ISSUE #1507: lncli should ask to repeat passphrase
### Background

`lncli` should ask to repeat passphrase for improved user experience/security

### Your environment

`lnd version 0.4.2-beta commit=a0b2fadea35fa4642daf4e9f56e6ecfe31d22ce1`

### Steps to reproduce

`lncli create`

Use existing seed. Add passphrase.

### Expected behaviour

Should ask to repeat passphrase

### Actual behaviour

Only asks once.

### PR DESCRIPTION
**Pull request by carlaKC**
Require that users confirm their passphrase when providing their own seed with a passphrase.
Currently implemented as an infinite loop until passwords match, can be limited to a set number of retries if that's the UX wanted. 

Fixes #1507

### CODE REVIEW

**Comment by carlaKC** [comment]
Okay got it, I wasn't super clear on what needed to be done from the original issue, will update :)

While I'm at it, I'm wondering if it's worth adding similar password retry to creating the wallet password? Not sure if endless password loops everywhere are ideal, but adding it there would make the whole flow consistent?

**Comment by cfromknecht** [comment]
@carlaKC sure that sounds great! should be able to reuse a good amount of code between the two :)

File: cmd/lncli/commands.go [hunk 1]
```diff
@@ -1650,6 +1612,50 @@ mnemonicCheck:
 	return nil
 }
 
+func capturePassword(instruction, noun string, optional bool,
```
Comment (halseth) [inline cmd/lncli/commands.go]: should have a godoc

File: cmd/lncli/commands.go [hunk 2]
```diff
@@ -1539,47 +1517,31 @@ mnemonicCheck:
...
 		// command.
 		fmt.Println("Your cipher seed can optionally be encrypted.")
-		fmt.Printf("Input your passphrase if you wish to encrypt it " +
+
+		instruction := "Input your passphrase if you wish to encrypt it " +
 			"(or press enter to proceed without a cipher seed " +
-			"passphrase): ")
-		aezeedPass1, err := terminal.ReadPassword(int(syscall.Stdin))
+			"passphrase): "
+		aezeedPass, err = capturePassword(instruction, "azseed",
```
Comment (halseth) [inline cmd/lncli/commands.go]: s/azseed/aezeed

File: cmd/lncli/commands.go [hunk 3]
```diff
@@ -1650,6 +1612,50 @@ mnemonicCheck:
...
+
+		// If the password provided is not valid, restart
+		// password capture process from the beginning.
+		if err := validate(password); err != nil {
+			fmt.Println(err.Error())
+			fmt.Println()
+			continue
+		}
+
+		fmt.Printf("Confirm %v password: ", noun)
```
Comment (halseth) [inline cmd/lncli/commands.go]: I think the noun is unnecessary here.

File: cmd/lncli/commands.go [hunk 4]
```diff
@@ -1650,6 +1612,50 @@ mnemonicCheck:
...
+			return nil, err
+		}
+		fmt.Println()
+
+		if bytes.Equal(password, passwordConfirmed) {
+			return password, nil
+		}
+
+		fmt.Printf("%v passwords don't match, "+
+			"please try again", noun)
```
Comment (halseth) [inline cmd/lncli/commands.go]: Same, don't need to take the noun.

File: cmd/lncli/commands.go [hunk 5]
```diff
@@ -1398,33 +1398,11 @@ func create(ctx *cli.Context) error {
...
-	fmt.Printf("Input wallet password: ")
-	pw1, err := terminal.ReadPassword(int(syscall.Stdin))
-	if err != nil {
-		return err
-	}
-	fmt.Println()
-
-	fmt.Printf("Confirm wallet password: ")
-	pw2, err := terminal.ReadPassword(int(syscall.Stdin))
+	walletPassword, err := capturePassword("Input wallet password: ",
```
Comment (cfromknecht) [inline cmd/lncli/commands.go]: nit: suggested wrapping
```golang
walletPassword, err := capturePassword(
        "Input wallet password: ", false, walletunlocker.ValidatePassword,
)
```
as a general rule if function calls can't fit on one line the preferred wrapping is:
```
function(
        arg1, arg2, arg3,
)
```

File: cmd/lncli/commands.go [hunk 6]
```diff
@@ -1539,47 +1517,31 @@ mnemonicCheck:
...
 		// command.
 		fmt.Println("Your cipher seed can optionally be encrypted.")
-		fmt.Printf("Input your passphrase if you wish to encrypt it " +
+
+		instruction := "Input your passphrase if you wish to encrypt it " +
 			"(or press enter to proceed without a cipher seed " +
-			"passphrase): ")
-		aezeedPass1, err := terminal.ReadPassword(int(syscall.Stdin))
+			"passphrase): "
+		aezeedPass, err = capturePassword(instruction, true,
```
Comment (cfromknecht) [inline cmd/lncli/commands.go]: similar wrapping comment:
```golang
aezeedPass, err = capturePassword(
        instruction, true, func(password []byte) error {
	        return nil
	},
)
```
also since we don't use the password argument, we can replace `password` with `_` if space is tight :)

File: cmd/lncli/commands.go [hunk 7]
```diff
@@ -1650,6 +1612,56 @@ mnemonicCheck:
 	return nil
 }
 
+// capturePassword returns a password value that has been
```
Comment (cfromknecht) [inline cmd/lncli/commands.go]: Excellent description! The line wrapping on the godoc looks like it breaks before 80 chars, but not a blocker

Comment (carlaKC) [reply cmd/lncli/commands.go]: Thanks!
I was wrapping at 72 because I remembered seeing it somewhere in the contributions guide. but that was for commit messages 🤦‍♀

File: cmd/lncli/commands.go [hunk 8]
```diff
@@ -1650,6 +1612,55 @@ mnemonicCheck:
...
+
+		// Do not require users to repeat password if
+		// it is optional and they are not using one.
+		if len(password) == 0 && optional {
+			return nil, nil
+		}
+
+		// If the password provided is not valid, restart
+		// password capture process from the beginning.
+		if err := validate(password); err != nil {
```
Comment (halseth) [inline cmd/lncli/commands.go]: Good call to do validation before asking to repeat! 😀
