### PR TITLE
lnwallet/btcwallet: remove invalid transactions from the wallet when broadcast fails

### LINKED ISSUE #2657: Not valid transaction (dust) to be used as input for new channels...
### Background

If node has a 1.5 BTC in wallet for example after a some open few channels API calls i have walletbalance as **0** and some pending channels has double spent outputs.

### Your environment

* version of `lnd` **v0.5.2-beta**
* which operating system (`uname -a` on *Nix) **CentOS 6.\***
* version of `btcd`, `bitcoind`, or other backend **0.17.1**

Hello!

I have fresh version of LND but i regulary have problems with open channels through API. Can you research this problem details? For example today i openned few channels. Before i had 1.5 BTC but after few calls i had in walletbalance zero. I open channels by same API (Node.JS):

    let res = await myNode.client.openChannelSync({
        //node_pubkey: Buffer.from(pubKey, 'hex'),
        node_pubkey_string: pubKey,
        local_funding_amount: amnt,
        push_sat: 0,
        sat_per_byte: 2,
        private: false,
        min_htlc_msat: 1,
        min_confs: 0,
        spend_unconfirmed: true
    })

Today before openning i stopped and restarted the LND. I need to do it regulary because i regulary have stuck channels. Ok, i did it: stopped and started again the LND. After some minutes i called to open channels. After few calls i had zero walletbalance. After researchind i found some channels with not-croadcasted funding transactions. For example:

    {
        "channel": {
            "remote_node_pub": "03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268",
            "channel_point": "624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0",
            "capacity": "4994574",
            "local_balance": "4990923",
            "remote_balance": "0"
        },
        "confirmation_height": 0,
        "commit_fee": "3651",
        "commit_weight": "600",
        "fee_per_kw": "5044"
    },

And what i see in logs again:

    $ grep 624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b ~/.lnd/mainnet-lnd-run.log 
    2019-02-19 11:15:52.365 [INF] FNDG: Generated ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0) for pendingID(15352eb09082da640ad68e019dc45a445063be8eb5681bbfd84d289fae99b778)
    2019-02-19 11:15:52.484 [INF] FNDG: Broadcasting funding tx for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0): (*wire.MsgTx)(0xc0be76bdc0)({
    2019-02-19 11:15:52.486 [INF] LNWL: Inserting unconfirmed transaction 624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b
    2019-02-19 11:15:52.507 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0): Transaction rejected: output already spent
    2019-02-19 11:15:52.507 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0)
    2019-02-19 11:15:52.507 [INF] CNCT: ChannelArbitrator(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0): starting state=StateDefault
    2019-02-19 11:15:52.509 [INF] NTFN: New spend subscription: spend_id=357, outpoint=624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0, height_hint=563745
    2019-02-19 11:15:52.518 [INF] FNDG: Finalizing pendingID(15352eb09082da640ad68e019dc45a445063be8eb5681bbfd84d289fae99b778) over ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0), waiting for channel open on-chain
    2019-02-19 11:15:52.518 [INF] CNCT: Close observer for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0) active
    2019-02-19 11:15:52.518 [INF] NTFN: New confirmation subscription: txid=624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b, numconfs=3
    2019-02-19 11:15:52.519 [INF] FNDG: Waiting for funding tx (624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b) to reach 3 confirmations
    2019-02-19 11:15:52.731 [ERR] NTFN: Rescan to determine the spend details of 624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0 failed: transaction not found within range

I found the fund transaction in logs:

    2019-02-19 11:15:52.484 [INF] FNDG: Broadcasting funding tx for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0): (*wire.MsgTx)(0xc0be76bdc0)({
     Version: (int32) 1,
     TxIn: ([]*wire.TxIn) (len=4 cap=15) {
      (*wire.TxIn)(0xc0054fb6e0)({
       PreviousOutPoint: (wire.OutPoint) 27a635424bf0d124a2ec4b3e39d4650001c1d88f2feeed60544b3a228c3753c4:0,
       SignatureScript: ([]uint8) <nil>,
       Witness: (wire.TxWitness) (len=2 cap=2) {
        ([]uint8) (len=72 cap=144) {
         00000000  30 45 02 21 00 d0 a4 4e  10 ba 9f b2 a3 53 e6 4c  |0E.!...N.....S.L|
         00000010  a6 41 06 78 35 4f d5 c1  86 6c e0 1c eb ea 03 55  |.A.x5O...l.....U|
         00000020  e1 ae 42 18 9c 02 20 23  7c 2a fe 20 4a 17 b2 34  |..B... #|*. J..4|
         00000030  0c e5 76 aa d8 89 c6 cd  e1 ec 3e 25 b0 ac 68 6f  |..v.......>%..ho|
         00000040  53 2b 54 eb 16 34 ab 01                           |S+T..4..|
        },
        ([]uint8) (len=33 cap=33) {
         00000000  02 7a 71 96 d9 f2 92 d8  97 cf d6 ef 82 6e e4 02  |.zq..........n..|
         00000010  ca 6a a9 66 33 c6 27 82  d4 c6 50 88 8a 78 d5 70  |.j.f3.'...P..x.p|
         00000020  6c                                                |l|
        }
       },
       Sequence: (uint32) 4294967295
      }),
      (*wire.TxIn)(0xc0054fb680)({
       PreviousOutPoint: (wire.OutPoint) 44936ac77ca64509b782f1022c5661ec5436afa3b4e1cae3b6c1704125ab2f7b:0,
       SignatureScript: ([]uint8) <nil>,
       Witness: (wire.TxWitness) (len=2 cap=2) {
        ([]uint8) (len=71 cap=144) {
         00000000  30 44 02 20 2f 38 9e 8d  f1 a6 62 a6 ed 05 38 6a  |0D. /8....b...8j|
         00000010  11 f3 3d bb a9 a4 5d 85  9b 70 c2 b0 56 27 95 62  |..=...]..p..V'.b|
         00000020  bb b9 f1 37 02 20 03 13  0c 40 63 b4 ba 2b 31 1e  |...7. ...@c..+1.|
         00000030  22 5a 90 94 84 4f d3 40  e7 d6 3b 0c a9 fa 19 d9  |"Z...O.@..;.....|
         00000040  f9 97 7e a0 ac c3 01                              |..~....|
        },
        ([]uint8) (len=33 cap=33) {
         00000000  02 08 21 3f 07 8a 3b 42  da df 43 89 ee 17 dd e9  |..!?..;B..C.....|
         00000010  66 b4 c2 31 fc 68 b2 3f  33 fe 91 e1 f7 c5 28 1e  |f..1.h.?3.....(.|
         00000020  f2                                                |.|
        }
       },
       Sequence: (uint32) 4294967295
      }),
      (*wire.TxIn)(0xc0054fb740)({
       PreviousOutPoint: (wire.OutPoint) 80a4a4e49a16e145967ce2c8edbe746da3d6509ea37d74fbd9a9b9cc6dffe814:1,
       SignatureScript: ([]uint8) <nil>,
       Witness: (wire.TxWitness) (len=2 cap=2) {
        ([]uint8) (len=71 cap=144) {
         00000000  30 44 02 20 36 fa 2d b7  c9 e1 6c 5a 80 96 b3 86  |0D. 6.-...lZ....|
         00000010  60 8f af 49 51 56 82 1c  3e 3d 15 b6 e6 3f ad 55  |`..IQV..>=...?.U|
         00000020  7c 40 80 11 02 20 7d 65  fd ff 8b a4 a5 09 7a 5e  ||@... }e......z^|
         00000030  d2 2f 82 a2 7e 33 9b 26  d7 81 2d 1d 72 a4 e8 55  |./..~3.&..-.r..U|
         00000040  f7 68 65 02 af b5 01                              |.he....|
        },
        ([]uint8) (len=33 cap=33) {
         00000000  03 b8 98 31 54 08 78 c8  c7 16 60 5f e6 4a 99 1a  |...1T.x...`_.J..|
         00000010  cc 8c 81 ea a2 33 c3 79  00 2b 03 fc be 45 55 c3  |.....3.y.+...EU.|
         00000020  b6                                                |.|
        }
       },
       Sequence: (uint32) 4294967295
      }),
      (*wire.TxIn)(0xc0054fb7a0)({
       PreviousOutPoint: (wire.OutPoint) d282aba762494f535bab325c8316906b8137be764001508e2d595135c1aaf791:1,
       SignatureScript: ([]uint8) <nil>,
       Witness: (wire.TxWitness) (len=2 cap=2) {
        ([]uint8) (len=71 cap=144) {
         00000000  30 44 02 20 1d 18 a7 84  95 5c 54 dc ba eb 7f fa  |0D. .....\T.....|
         00000010  39 bc 42 0a 46 f5 34 e4  22 6b f0 23 1b 4c a4 05  |9.B.F.4."k.#.L..|
         00000020  14 d2 37 2b 02 20 56 35  1e ef df 46 b1 86 eb a2  |..7+. V5...F....|
         00000030  f0 f0 ef c1 3a 80 3a 7b  76 a0 57 9a 1f 92 00 9c  |....:.:{v.W.....|
         00000040  50 f6 dc f2 cb cf 01                              |P......|
        },
        ([]uint8) (len=33 cap=33) {
         00000000  02 f7 17 85 0a 2d 52 9e  f7 0e 3a d2 52 fe 06 41  |.....-R...:.R..A|
         00000010  2b bf 87 3a 12 f5 f4 c8  01 2b f2 b9 13 cd 6e 20  |+..:.....+....n |
         00000020  f5                                                |.|
        }
       },
       Sequence: (uint32) 4294967295
      })
     },
     TxOut: ([]*wire.TxOut) (len=2 cap=15) {
      (*wire.TxOut)(0xc03c2102e0)({
       Value: (int64) 4994574,
       PkScript: ([]uint8) (len=34 cap=500) {
        00000000  00 20 ea c3 ae 19 cc 07  2b eb 3e e3 71 b1 f6 cf  |. ......+.>.q...|
        00000010  b1 7a 72 57 4c 79 38 62  3a 03 7c 97 4b 5f 4e f3  |.zrWLy8b:.|.K_N.|
        00000020  b1 c4                                             |..|
       }
      }),
      (*wire.TxOut)(0xc063bbcee0)({
       Value: (int64) 43285291,
       PkScript: ([]uint8) (len=22 cap=500) {
        00000000  00 14 f4 c9 b4 81 64 9f  82 f9 21 e8 31 9f f9 bb  |......d...!.1...|
        00000010  94 84 39 34 f2 b7                                 |..94..|
       }
      })
     },
     LockTime: (uint32) 0
    })

There are 4 inputs. Some input(s) was used before. Why the LND uses spent outputs?
Ok, if it's error why the LND sees the error "Transaction rejected: output already spent" and after this: 

    2019-02-19 11:15:52.507 [ERR] FNDG: Unable to broadcast funding tx for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0): Transaction rejected: output already spent
    2019-02-19 11:15:52.507 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0)
    2019-02-19 11:15:52.507 [INF] CNCT: ChannelArbitrator(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0): starting state=StateDefault
    2019-02-19 11:15:52.509 [INF] NTFN: New spend subscription: spend_id=357, outpoint=624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0, height_hint=563745
    2019-02-19 11:15:52.518 [INF] FNDG: Finalizing pendingID(15352eb09082da640ad68e019dc45a445063be8eb5681bbfd84d289fae99b778) over ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0), waiting for channel open on-chain
    2019-02-19 11:15:52.518 [INF] CNCT: Close observer for ChannelPoint(624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0) active
    2019-02-19 11:15:52.518 [INF] NTFN: New confirmation subscription: txid=624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b, numconfs=3
    2019-02-19 11:15:52.519 [INF] FNDG: Waiting for funding tx (624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b) to reach 3 confirmations
    2019-02-19 11:15:52.731 [ERR] NTFN: Rescan to determine the spend details of 624296d9ac5ba5f8469187cee9e2be87331d5b6bc86477f75287681a6b1d201b:0 failed: transaction not found within range

It's stupid behaviuor. It should delete this not-finished channel. But it does everything as the channel is normal. After this i have stuck channels and cannot open channels but i have there ~ 1 BTC :(

### PR DESCRIPTION
**Pull request by wpaulino**
In this PR, we update our btcwallet dependency to the latest version, which includes some minor improvements to our error handling when broadcasting transactions.

Along the way, we also address a lingering issue within some subsystems that are responsible for broadcasting transactions. Previously, ErrDoubleSpend indicated that a transaction was already included in the mempool/chain. This error was then modified to actually be returned for conflicting transactions, but its callers were not modified accordingly. This would lead to conflicting transactions to be interpreted as valid, when they shouldn't be.

Depends on https://github.com/btcsuite/btcwallet/pull/597.
Fixes #2657.

### CODE REVIEW

**Comment by wpaulino** [comment]
There are two cases left which I cannot determine if they should also be ignoring `ErrDoubleSpend`:

https://github.com/lightningnetwork/lnd/blob/8a0d0ec98fd659fdc325279a36442c990192541b/sweep/sweeper.go#L195
https://github.com/lightningnetwork/lnd/blob/8a0d0ec98fd659fdc325279a36442c990192541b/sweep/sweeper.go#L650

cc @joostjager

**Comment by joostjager** [comment]
Yes, they should be ignoring. The mechanism in sweeper is that it often tries to publish and if it is a double spend, it keeps retrying with exponential randomized back-off. This is to avoid making all kinds of mempool assumptions in the sweeper why a tx might be a double spend.

**Comment by joostjager** [comment]
Even though the first case that you refer to is rebroadcasting an exact tx of ours, it may still be that it fails because there is a conflict.

**Comment by Roasbeef** [comment]
Needs a rebase now that the dependent PR is in.

File: contractcourt/htlc_success_resolver.go [hunk 1]
```diff
@@ -200,7 +199,7 @@ func (h *htlcSuccessResolver) Resolve() (ContractResolver, error) {
 	//
 	// TODO(roasbeef): after changing sighashes send to tx bundler
 	err := h.PublishTx(h.htlcResolution.SignedSuccessTx)
-	if err != nil && err != lnwallet.ErrDoubleSpend {
+	if err != nil {
```
Comment (Roasbeef) [inline contractcourt/htlc_success_resolver.go]: So with this change, do we even still need `lnwallet.ErrDoubleSpend` at all?

Comment (wpaulino) [reply contractcourt/htlc_success_resolver.go]: The error is still needed with its current purpose, as pointed out by @joostjager. Its former purpose of detecting whether the transaction is in the mempool or has already confirmed is no longer needed as we won't return an error in those cases.

**Comment by wpaulino** [comment]
Will rebase this after we've caught up lnd with btcwallet and neutrino.

**Comment by Roasbeef** [comment]
Needs rebase now that the dep PR has been merged.

**Comment by wpaulino** [comment]
Rebased.
