### PR TITLE
lnwallet+rpcserver: fix weight calculation for taproot channels

### LINKED ISSUE #8036: [bug]: 0-conf Simple Taproot channel becomes inactive after payment is made
### Background

After opening up a 0-conf Simple Taproot channel and then completing a payment, the channel becomes inactive, erroring while trying to update the commitment.

`
01:09:32.357 [ERR] HSWC: ChannelLink(85a8547f268528e5473b58883561e30134756d4ab2aadccd8338508346917ec2:0): failing link: unable to update commitment: height=2, for ChannelPoint(85a8547f268528e5473b58883561e30134756d4ab2aadccd8338508346917ec2:0) attempts to create commitment with feerate 218 sat/kw: (*lnwallet.unsignedCommitmentTx)(0x400150a700)({
`

After talking with roasbeef, it sounds like this feerate is set incorrectly and should be set to min of 253 sat/kw everywhere.

The same error was hit opening up a channel, both via RPC and CLI.

Also attempted to open a non 0-conf chan afterwards and hit the following error:

`[lncli] rpc error: code = Unknown desc = non-zero-conf channel has min depth zero`

Can provide more logs upon request.

### Your environment

Initiator
* `lnd` v0.17.0-beta.rc5 (also occurred back with rc1 + rc2)
* Ubuntu Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-156-generic x86_64)
* `bitcoind` v24.01

Acceptor
* Mobile
* `lnd` v0.17.0-beta.rc5 (also occurred back with rc1 + rc2)
* Android 9 + 12
* `bitcoind` v24.01

### Steps to reproduce

Open up a 0-conf Simple Taproot channel to a mobile LND node, and then complete a payment across the channel.

### Expected behaviour

The channel should remain active.

### Actual behaviour

The channel becomes inactive after failing to update the commitment.

### PR DESCRIPTION
**Pull request by yyforyongyu**
Fix the weight calculation found in multiple places.

Fix #8036

### CODE REVIEW

File: lnwallet/channel.go [hunk 1]
```diff
@@ -3027,11 +3027,17 @@ func (lc *LightningChannel) fetchCommitmentView(remoteChain bool,
 	}
 	fee := lc.channelState.Capacity - totalOut
 
+	var witnessWeight int64
+	if lc.channelState.ChanType.IsTaproot() {
+		witnessWeight = input.TaprootKeyPathWitnessSize
```
Comment (guggero) [inline lnwallet/channel.go:3032]: I'm confused. If the weight of a taproot key spend is smaller than the v0 multisig spend, wouldn't we have **over**estimated the fee instead?
Or is this when we check the proposed fee rate of the other party (which calculated it correctly), we reject it because we think it's too low?

File: rpcserver.go [hunk 2]
```diff
@@ -3476,10 +3476,17 @@ func (r *rpcServer) fetchPendingOpenChannels() (pendingOpenChannels, error) {
 		// broadcast.
 		// TODO(roasbeef): query for funding tx from wallet, display
 		// that also?
+		var witnessWeight int64
```
Comment (guggero) [inline rpcserver.go:3479]: Since we didn't catch any of these three code paths in the integration tests, do you think it would be easy to add such a test (or tests)?

**Review by guggero — COMMENTED** [review]
Thanks for the quick fix!

File: lnwallet/channel.go (hunk 1 above)
Comment (Roasbeef) [reply lnwallet/channel.go:3032]: Hmm also swore I had this updated in one of the side branches, may have been dropped in a rebase conflict. Open question though is: why wasn't this caught by any of the itests or the unit tests?

Comment (Roasbeef) [reply lnwallet/channel.go:3032]: Dug a bit deeper, and it was missing in all the branches. We have unit tests to assert proper weight/fee calculation, but that's in another area when we construct the commitment transaction to then compare against the weight estimates.

Comment (Roasbeef) [reply lnwallet/channel.go:3032]: Re @guggero's questions above: iiuc, yes we would instead over estimate. This is called both when we go to propose a state, and also when we go to accept a state from the remote party. 

This seems independent of zero conf all together (since that was mentioned in the initial issue). One other relevant tidbit was: using mainnet fee estimation (neutrino) for a testnet node.

File: rpcserver.go (hunk 2 above)
Comment (yyforyongyu) [reply rpcserver.go:3479]: Added an itest

File: lnwallet/channel.go (hunk 1 above)
Comment (yyforyongyu) [reply lnwallet/channel.go:3032]: I think the issue is, we use a much higher fee rate in itests, so this edge case was never caught. Added a new test case to check this edge case.

File: itest/lnd_payment_test.go [hunk 3]
```diff
@@ -16,6 +17,124 @@ import (
...
+		// TODO(yy): remove the sleep once the following bug is fixed.
+		// When the invoice is reported settled, the commitment dance
+		// is not yet finished, which can cause an error when closing
+		// the channel, saying there's active HTLCs. We need to
+		// investigate this issue and reverse the order to, first
+		// finish the commitment dance, then report the invoice as
+		// settled.
+		time.Sleep(2 * time.Second)
+
+		// Close the channel.
```
Comment (guggero) [inline itest/lnd_payment_test.go:102]: Should we note here that this implicitly makes sure the channel is active (as coop-close is only possible when the channel is fully operational and online).

**Review by guggero — APPROVED** [review]
Very nice! Can confirm the itest catches the issue that is fixed in the PR. LGTM :tada:

File: itest/lnd_payment_test.go (hunk 3 above)
Comment (yyforyongyu) [reply itest/lnd_payment_test.go:102]: Done!

**Comment by Roasbeef** [comment]
To answer the question above re why this results in a lower fee rate in the sanity check instead of a higher one:
  * We use the correct weight values everywhere else up to this point, so we estimate against a "fully loaded" commitment tx (witness, etc). 
  * When we get down to this check, we actually over estimate the weight since we use the segwit v0 witness value. For the musig2 channels, the witness is ~4x smaller, so by using the old constant we over estimate the weight for the sanity check, which leads to a lower fee rate.

**Review by Roasbeef — APPROVED** [review]
LGTM 👙
