### PR TITLE
fix: clarify available commitment balance log message

### LINKED ISSUE #8152: [bug]:  Probably an incorrect message ?
### Background

Just saw in my lnd logs:
2023-11-06 17:20:26.341 [INF] LNWL: ChannelPoint(7550ec24e9fddd9a46c081222ed0e6ecab62df829492f0c4a4aee67fbe339d4e:0): Reducing local balance (from 3008100571 mSAT to 1679999 mSAT): remote side does not have enough funds (1947100 mSAT < 2136000 mSAT) to pay for non-dust HTLC in case of unilateral close.
2023-11-06 17:20:26.341 [INF] LNWL: ChannelPoint(7550ec24e9fddd9a46c081222ed0e6ecab62df829492f0c4a4aee67fbe339d4e:0): Reducing local balance (from 3008100571 mSAT to 1951999 mSAT): remote side does not have enough funds (1947100 mSAT < 2136000 mSAT) to pay for non-dust HTLC in case of unilateral close.

### Your environment

lnd 0.17.0

The message is saying my local balance went from 3M? to 1600 sat??
After this, local balance is still 3M, and remote is 31k sats in RTL

The remote party initiated the channel. I can understand that it would lower its local balance if network fees become high to be sure it has enough sats available to pay for a transaction to get its part of the channel back. 

_So i guess there is a mixup in the message between the initiator's local balance and my local balance?_

### PR DESCRIPTION
**Pull request by mohamedawnallah**
## Change Description
This commit addresses clarification in the `availableCommitmentBalance` function in `lnwallet/channel.go` by adjusting the log message to better reflect the context of balance reduction.

Closes #8152 

## Steps to Test
N/A

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

File: lnwallet/channel.go [hunk 1]
```diff
@@ -8366,11 +8366,12 @@ func (lc *LightningChannel) availableCommitmentBalance(view *htlcView,
 	if theirBalance < commitFeeWithHtlc && ourBalance >= nonDustHtlcAmt {
 		// see https://github.com/lightning/bolts/issues/728
 		ourReportedBalance := nonDustHtlcAmt - 1
-		lc.log.Infof("Reducing local balance (from %v to %v): "+
-			"remote side does not have enough funds (%v < %v) to "+
-			"pay for non-dust HTLC in case of unilateral close.",
-			ourBalance, ourReportedBalance, theirBalance,
-			commitFeeWithHtlc)
+		lc.log.Infof("Reducing local (reported) balance "+
```
Comment (guggero) [inline lnwallet/channel.go:8369]: nit: if you configure your editor correctly (add a ruler at 80 characters, use tab size of 8), you see that this message can be slightly more compact by fitting a couple of more words on each line.

**Review by guggero — APPROVED** [review]
LGTM :tada:

File: lnwallet/channel.go (hunk 1 above)
Comment (mohamedawnallah) [reply lnwallet/channel.go:8369]: Thanks! Updated.

**Review by yyforyongyu — APPROVED** [review]
LGTM🦾
