### PR TITLE
addinvoice: refactor hint hop selection algorithm

### LINKED ISSUE #6898: addinvoice --private flag causes delay on v15.1
### Background

LND v15.1 has a big delay when generating an invoice using the `--private` flag

### Your environment

lnd version: `0.15.1-beta commit=v0.15.1-beta`
os: `Linux ip-172-1-1-8 5.13.0-1021-aws #23~20.04.2-Ubuntu SMP Thu Mar 31 11:36:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
bitcoind: `Bitcoin Core version v0.21.1`

### Steps to reproduce

```
lncli addinvoice 1000 --private
```

### Expected behaviour

This should "immediately" create the invoice

### Actual behaviour

It is taking around 12 seconds to generate an invoice with the private flag. Without the private flag things seems normal. Another smaller node of ours is also having the same problem after running v15.1, but the delay is shorter for this smaller node.

### PR DESCRIPTION
**Pull request by positiveblue**
In order to reduce the number of calls to the db we try to process as
 few channels as we can + try to not do extra work for each of them.
    
- First fetch all the channels. Then, filter all the public ones and
  sort the potential candidates by remote balance.

- Filter out each potential candidate as soon as possible.

- Only check the alias if the channel supports scid aliases.

- Because we sort the channels by remote balance, we will hit the
  target amount, if possible, as soon as we can.

We do not want to leak extra information about our remote balances, so we
shuffle the hop hints (the forced ones go always first) so the invoice
receiver does not know which channels have more balance than others.

## Steps to Test
```
cd lnrpc/invoicesrpc
go test ./...
```

Fixes #6898

### CODE REVIEW

**Comment by Roasbeef** [comment]
Related ish: https://github.com/lightningnetwork/lnd/pull/4679

File: lnrpc/invoicesrpc/addinvoice.go [hunk 1]
```diff
@@ -366,93 +372,35 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
-					}
-				}
-
-				chanID := lnwire.NewChanIDFromOutPoint(
-					&c.FundingOutpoint,
-				)
-
-				// Check whether the the peer's alias was
-				// provided in forcedHints.
-				peerAlias, _ := cfg.GetAlias(chanID)
```
Comment (Roasbeef) [inline lnrpc/invoicesrpc/addinvoice.go:409]: IIUC, this is what causes the slown down. Given we know all the channels here ahead of time, what if we just did a batch request to get all the _potential_ aliases for each of the channels?

Alternatively, we can add a write-thru cache to the Alias Manager, so then `GetPeerAlias` would would just read things in memory. Might be an over all smaller change.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: lnrpc/invoicesrpc/addinvoice.go (hunk 1 above)
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:409]: Write-thru cache [added](https://github.com/lightningnetwork/lnd/pull/6914/commits/e078f683930e9b0bd6c7c86f86d89a8af7d1452a) :+1:

File: lnrpc/invoicesrpc/addinvoice.go [hunk 2]
```diff
@@ -678,169 +618,229 @@ type SelectHopHintsCfg struct {
...
+	edgePolicy, canBeHopHint := chanCanBeHopHint(hopHintInfo, cfg)
+	if edgePolicy == nil || !canBeHopHint {
+		return zpay32.HopHint{}, 0, false
+	}
+
+	if hopHintInfo.ScidAliasFeature {
+		alias, err := cfg.GetAlias(chanID)
+		_, included := alreadyIncluded[alias.ToUint64()]
+		switch {
+		case err != nil:
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:748]: my personal preference would be to have the error check for `GetAlias` directly after the call. Cause here you are accessing `alias.ToUint64()` before checking if the call even succeeded. This is fine at the moment since `GetAlias` does not return a pointer but if it was to change to a pointer then this would panic. 
Just a thought

File: lnrpc/invoicesrpc/addinvoice.go [hunk 3]
```diff
@@ -678,169 +618,229 @@ type SelectHopHintsCfg struct {
...
-		// was negotiated and the alias is not yet assigned, we cannot
-		// issue an invoice. Doing so might expose the confirmed SCID
-		// of a private channel.
-		if channel.ScidAliasFeature {
-			var defaultScid lnwire.ShortChannelID
-			if alias == defaultScid {
-				continue
-			}
-		}
+// SelectHopHints will select up to cfg.MaxHophints from the current open
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:809]: nit s/SelectHopHints/PopulateHopHints

**Review by ellemouton — COMMENTED** [review]
Awesome stuff @positiveblue! Left some comments

File: lnrpc/invoicesrpc/addinvoice.go [hunk 4]
```diff
@@ -678,169 +618,229 @@ type SelectHopHintsCfg struct {
...
-			}
+	// TODO(positiveblue): get the channels slice already filtered by
+	// private == true and sorted by RemoteBalance?
+	openChannels, err := cfg.FetchAllChannels()
+	if err != nil {
+		return nil, err
+	}
+
+	privateChannels := make([]*channeldb.OpenChannel, 0, len(openChannels))
+	for _, oc := range openChannels {
```
[the remark this answers is not in the document]
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:704]: yes, but then it gets harder to tests all the paths. The logic behind this split is:
- `getPotentialHints` all the channels that could potentially be a hint at some point
- `shouldIncludeChannel`: works on channels, filters channels by potential hop hints in a given payment at a given point (channel is active, is already included, etc)
- `chanCanBeHopHint: already works on hopHInts (not channels)

File: lnrpc/invoicesrpc/addinvoice.go (hunk 2 above)
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:748]: I like this a lot :+1:

File: aliasmgr/aliasmgr.go [hunk 5]
```diff
@@ -176,6 +206,14 @@ func (m *Manager) populateMaps() error {
 		m.aliasToBase[aliasSCID] = baseSCID
 	}
 
+	// Populate the peer alias cache.
+	m.peerAlias = make(
```
[the remark this answers is not in the document]
Comment (positiveblue) [reply aliasmgr/aliasmgr.go:210]: well, here we are giving it the right size (now that we know it)

File: aliasmgr/aliasmgr.go [hunk 6]
```diff
@@ -320,36 +360,32 @@ func (m *Manager) PutPeerAlias(chanID lnwire.ChannelID,
...
+	if err != nil {
+		return err
+	}
+
+	// Now that the database state has been updated, we can update it in
+	// our cache.
+	m.Lock()
+	m.peerAlias[chanID] = alias
+	m.Unlock()
+
```
[the remark this answers is not in the document]
Comment (positiveblue) [reply aliasmgr/aliasmgr.go:372]: :dart:

File: aliasmgr/aliasmgr.go [hunk 7]
```diff
@@ -115,6 +119,10 @@ func (m *Manager) populateMaps() error {
 	// populate the Manager's actual maps.
 	aliasMap := make(map[lnwire.ShortChannelID]lnwire.ShortChannelID)
 
+	// This map caches the ChannelID/alias SCIDs stored in the database and
+	// is used to populate the Manager's cache.
+	peerAliasMap := make(map[lnwire.ChannelID]lnwire.ShortChannelID)
+
 	err := kvdb.Update(m.backend, func(tx kvdb.RwTx) error {
```
[the remark this answers is not in the document]
Comment (positiveblue) [reply aliasmgr/aliasmgr.go:126]: No idea, I think we can update it :eyes:

File: lnrpc/invoicesrpc/addinvoice.go [hunk 8]
```diff
@@ -678,169 +619,233 @@ type SelectHopHintsCfg struct {
...
+	targetAmount lnwire.MilliSatoshi) bool {
 
-	if numHints >= maxHints {
-		log.Debug("Reached maximum number of hop hints")
+	if nHintsLeft <= 0 {
+		log.Debugf("Reached targeted number of hop hints")
 		return true
 	}
 
-	requiredAmount := amount * lnwire.MilliSatoshi(scalingFactor)
```
Comment (Roasbeef) [inline lnrpc/invoicesrpc/addinvoice.go:694]: What happened to the scaling factor here?

File: lnrpc/invoicesrpc/addinvoice.go [hunk 9]
```diff
@@ -678,169 +619,233 @@ type SelectHopHintsCfg struct {
...
-	hopHints := make([][]zpay32.HopHint, 0, numMaxHophints)
-	for _, channel := range openChannels {
-		enoughHopHints := sufficientHints(
-			len(hopHints), numMaxHophints, hopHintFactor, amtMSat,
-			totalHintBandwidth,
-		)
-		if enoughHopHints {
-			log.Debugf("First pass of hop selection has " +
-				"sufficient hints")
+// populateForcedHints check that the provided hint paths are valid and returns
```
Comment (Roasbeef) [inline lnrpc/invoicesrpc/addinvoice.go:674]: check -> checks

File: lnrpc/invoicesrpc/addinvoice.go [hunk 10]
```diff
@@ -678,169 +619,233 @@ type SelectHopHintsCfg struct {
...
+// an array of hop hints.
+func populateForcedHints(forcedHints [][]zpay32.HopHint) ([][]zpay32.HopHint,
+	error) {
 
-			return hopHints
+	hopHints := make([][]zpay32.HopHint, 0, maxHopHints)
+	for _, hint := range forcedHints {
+		if len(hint) == 0 {
```
Comment (Roasbeef) [inline lnrpc/invoicesrpc/addinvoice.go:681]: I wonder if this check can't just be enforced at a higher level (potentially during RPC parsing)? Why would a forced hint (provided by the user) ever have zero length?

File: lnrpc/invoicesrpc/addinvoice_test.go [hunk 11]
```diff
@@ -0,0 +1,840 @@
...
+				require.ErrorContains(t, err, tc.expectedErr)
+				return
+			}
+			require.NoError(t, err)
+			require.Equal(t, tc.expectedHints, hopHints)
+		})
+	}
+}
+
+var shouldIncludeChannelTestCases = []struct {
```
Comment (Roasbeef) [inline lnrpc/invoicesrpc/addinvoice_test.go:143]: The fact that the old tests are deleted (unclear why) and then re-added here makes this difficult to review (also all the test case names are changed as well so that can't be used to spot check), namely at a glance it isn't clear if all the prior tests are replicated here.

Comment (Roasbeef) [reply lnrpc/invoicesrpc/addinvoice_test.go:143]: Will look at the test coverage diff manually on a local env

File: lnrpc/invoicesrpc/addinvoice_test.go [hunk 12]
```diff
@@ -0,0 +1,840 @@
...
+
+	edgeInfo := args.Get(0).(*channeldb.ChannelEdgeInfo)
+	policy1 := args.Get(1).(*channeldb.ChannelEdgePolicy)
+	policy2 := args.Get(2).(*channeldb.ChannelEdgePolicy)
+
+	return edgeInfo, policy1, policy2, err
+}
+
+// getTestPubKey returns a valid parsed pub key to be used in our tests.
+func getTestPubKey() *secp256k1.PublicKey {
```
Comment (Roasbeef) [inline lnrpc/invoicesrpc/addinvoice_test.go:76]: This should be `btcec`.

File: aliasmgr/aliasmgr.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply aliasmgr/aliasmgr.go:126]: I think since we don't create the top level bucket anywhere else, so then it wants to do that here. We can potentially revisit this in another PR.

File: aliasmgr/aliasmgr.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply aliasmgr/aliasmgr.go:210]: Why do we need to populate the map here (copy everything over), if we made it above w/ the exact same type signature? 

AFAICT, we can just assign it here instead.

File: aliasmgr/aliasmgr.go [hunk 13]
```diff
@@ -310,7 +350,10 @@ func (m *Manager) DeleteSixConfs(baseScid lnwire.ShortChannelID) error {
 func (m *Manager) PutPeerAlias(chanID lnwire.ChannelID,
 	alias lnwire.ShortChannelID) error {
 
-	return kvdb.Update(m.backend, func(tx kvdb.RwTx) error {
+	m.Lock()
+	m.Unlock()
```
Comment (Roasbeef) [inline aliasmgr/aliasmgr.go:354]: This doesn't do anything, missing a `defer` here.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: lnrpc/invoicesrpc/addinvoice.go [hunk 14]
```diff
@@ -3,10 +3,11 @@ package invoicesrpc
 import (
 	"bytes"
 	"context"
-	"crypto/rand"
 	"errors"
 	"fmt"
 	"math"
+	"math/rand"
```
[the remark this answers is not in the document]
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:10]: @ellemouton pointed it out. All the `crypto/rand` calls have been substituted by the `cryptoRand` named import and rand is used only for the `Shuffle`.

To ensure that we do not slide any erorrs in the future I will leave `rand.XXX` for `crypto/rand` and `mathRand` for `math/rand` :ok_hand:

File: lnrpc/invoicesrpc/addinvoice.go [hunk 15]
```diff
@@ -366,93 +372,35 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
-	if invoice.Private {
-		openChannels, err := cfg.ChanDB.FetchAllChannels()
-		if err != nil {
-			return nil, nil, fmt.Errorf("could not fetch all " +
-				"channels")
+	// Include route hints if needed.
+	if len(invoice.RouteHints) > 0 || invoice.Private {
+		totalHopHints := len(invoice.RouteHints)
+		if invoice.Private {
+			totalHopHints = maxHopHints
```
[the remark this answers is not in the document]
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:385]: No, `totalHopHints` is the max number of hopHints that we can add.

If the user provided `RouteHints` those are the minimum that we will add. If the user adds the flag `invoice.Private` we will add up to maxHopHints, including the RouteHints that the user provided.

PopulateHopHints will take care to stop whenever we reached a stop state.

File: lnrpc/invoicesrpc/addinvoice.go (hunk 8 above)
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:694]: `PopulateHopHints` has it for calculating `targetBandwidth := amtMSat * hopHintFactor
`

File: lnrpc/invoicesrpc/addinvoice.go (hunk 10 above)
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:681]: we can check at a higher level :+1:

File: lnrpc/invoicesrpc/addinvoice.go [hunk 16]
```diff
@@ -678,169 +627,213 @@ type SelectHopHintsCfg struct {
...
-		// TODO(roasbeef): have a cut off based on min bandwidth?
-		totalHintBandwidth += channel.RemoteBalance
+	// If we already have enough hints we don't need to add any more.
+	nHintsLeft := cfg.MaxHopHints - len(hopHints)
+	if nHintsLeft <= 0 {
+		return hopHints, nil
 	}
 
-	return hopHints
+	alreadyIncluded := make(map[uint64]struct{})
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:821]: How about instead using `map[uint64]bool` for `alreadyIncluded` instead? 

That makes the logic later easier to read cause you can do 
```
if alreadyIncluded[xxx] {
```
instead of 
```
_, ok := alreadyIncluded[xxx]
if ok {
```

File: lnrpc/invoicesrpc/addinvoice.go [hunk 17]
```diff
@@ -678,169 +627,213 @@ type SelectHopHintsCfg struct {
...
+		if err != nil {
+			return zpay32.HopHint{}, 0, false
 		}
 
-		// Now that we now this channel use usable, add it as a hop
-		// hint and the indexes we'll use later.
-		addHopHint(&hopHints, channel, edgePolicy, alias)
+		_, included := alreadyIncluded[alias.ToUint64()]
+		switch {
+		case alias.IsDefault():
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:744]: I think we can remove the switch statement entirely. The first case is not at all dependent on if the alias is already included or not. 
So I would suggest:
```
if alias.IsDefault() || alreadyIncluded[alias.ToUint64()] {
    return zpay32.HopHint{}, 0, false
}

hopHintInfo.ShortChannelID = alias.ToUint64()
```

File: lnrpc/invoicesrpc/addinvoice.go [hunk 18]
```diff
@@ -678,169 +627,213 @@ type SelectHopHintsCfg struct {
...
+	alreadyIncluded map[uint64]struct{},
+	cfg *SelectHopHintsCfg) [][]zpay32.HopHint {
+
+	currentBandwidth := lnwire.MilliSatoshi(0)
+	hopHints := make([][]zpay32.HopHint, 0, nHintsLeft)
+	for _, channel := range potentialHints {
 		enoughHopHints := sufficientHints(
-			len(hopHints), numMaxHophints, hopHintFactor, amtMSat,
-			totalHintBandwidth,
+			nHintsLeft, currentBandwidth, targetBandwidth,
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:775]: can just

```
if sufficientHints(...) {
       return hopHints
}
```

File: lnrpc/invoicesrpc/addinvoice.go [hunk 19]
```diff
@@ -678,169 +627,213 @@ type SelectHopHintsCfg struct {
...
-			if alias == defaultScid {
-				continue
-			}
-		}
+// PopulateHopHints will select up to cfg.MaxHophints from the current open
+// channels. The set of hop hints will be returned as a slice of functional
+// options that'll append the route hint to the set of all route hints.
+//
+// TODO(roasbeef): do proper sub-set sum max hints usually << numChans.
+func PopulateHopHints(amtMSat lnwire.MilliSatoshi, cfg *SelectHopHintsCfg,
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:810]: nit: usually nice if the `cfg` variable is first (no blocking though)

File: lnrpc/invoicesrpc/addinvoice.go [hunk 20]
```diff
@@ -678,169 +627,213 @@ type SelectHopHintsCfg struct {
...
+
+// selectHopHints iterates a list of potential hints selecting the valid hop
+// hints until we have enough hints or run out of channels.
+//
+// NOTE: selectHopHints expects potentialHints to be already sorted in
+// descending priority.
+func selectHopHints(nHintsLeft int, targetBandwidth lnwire.MilliSatoshi,
+	potentialHints []*channeldb.OpenChannel,
+	alreadyIncluded map[uint64]struct{},
+	cfg *SelectHopHintsCfg) [][]zpay32.HopHint {
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:769]: same here with the `cfg` variable :)

File: lnrpc/invoicesrpc/addinvoice_test.go [hunk 21]
```diff
@@ -0,0 +1,786 @@
+package invoicesrpc
+
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice_test.go:2]: nit: commit message name: s/uint/unit

File: lnrpc/invoicesrpc/addinvoice.go (hunk 18 above)
Comment (positiveblue) [reply lnrpc/invoicesrpc/addinvoice.go:775]: it does not fit in 80 characters, so it would look like

```
if sufficientHints(
    nHintsLeft, currentBandwidth, targetBandwidth,
) {
    return hopHints
}

**Review by Roasbeef — APPROVED** [review]
LGTM 🥑

File: lnrpc/invoicesrpc/addinvoice.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ellemouton) [reply lnrpc/invoicesrpc/addinvoice.go:695]: alrighty-roo 🦘 makes sense!

File: lnrpc/invoicesrpc/addinvoice.go [hunk 22]
```diff
@@ -677,169 +626,208 @@ type SelectHopHintsCfg struct {
...
+		hopHintInfo.ShortChannelID = alias.ToUint64()
 	}
 
-	// In this second pass we'll add channels, and we'll either stop when
-	// we have 20 hop hints, we've run through all the available channels,
-	// or if the sum of available bandwidth in the routing hints exceeds 2x
-	// the payment amount. We do 2x here to account for a margin of error
-	// if some of the selected channels no longer become operable.
-	for i := 0; i < len(openChannels); i++ {
+	// Now that we now this channel use usable, add it as a hop hint and
```
Comment (ellemouton) [inline lnrpc/invoicesrpc/addinvoice.go:749]: nit: s/now/know

File: lnrpc/invoicesrpc/addinvoice.go (hunk 16 above)
Comment (ellemouton) [reply lnrpc/invoicesrpc/addinvoice.go]: ah! TIL - awesome, good to know!

**Review by ellemouton — COMMENTED** [review]
LGTM 🔥  just one small type to fixed and then g2g!

**Review by ellemouton — APPROVED** [review]
