### PR TITLE
lnd: fix #1990 LND can't read .cookie file in Bitcoin datadir (Windows 10)

### LINKED ISSUE #1990: [Testnet] LND can't read .cookie file in Bitcoin datadir (Windows 10)
Both of my Bitcoin and LND nodes are installed in their default datadir location:
C:\Users\username\AppData\Local\Bitcoin 
C:\Users\username\AppData\Local\Bitcoin

Version of bitcoin: v0.16.3
Version of lnd: "0.5.0-beta commit=b341dea3733cb721d6aecefa54123b5b1ac7b126"
Operating System:  Windows 10

Problem: At startup LND is supposed to read the .cookie file in Bitcoin\testnet\.cookie but it does not, so starting LND fails with this error message: 

`>lnd
Attempting automatic RPC configuration to bitcoind
unable to load RPC credentials for bitcoind: unable to extract RPC credentials: unable to find rpcuser in config, cannot start w/o RPC connection`

After putting  `rpcuser` and `rpcpassword` in bitcoin.conf then LND can start successfully, (and oddly that these credentials are only required to be applied to bitcoin.conf, not lnd.conf. This doesn't happen the same with Ubuntu because with Ubuntu LND and Bitcoind can function without rpcuser and rpcpass when they're installed in default locations.

### PR DESCRIPTION
**Pull request by GameXG**
Path package only supports the unix path format, not the windows path format.

``` go

// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package path implements utility routines for manipulating slash-separated
// paths.
//
// The path package should only be used for paths separated by forward
// slashes, such as the paths in URLs. This package does not deal with
// Windows paths with drive letters or backslashes; to manipulate
// operating system paths, use the path/filepath package.
package path

```

### CODE REVIEW

**Comment by GameXG** [comment]
main.go

``` go
package main

import (
	"fmt"
	"path"
	"path/filepath"
)

func main() {
	p := "c:\\aa\\bb\\cc"

	fmt.Println("path.dir:", path.Dir(p))
	fmt.Println("filepath.dir:", filepath.Dir(p))
}
```


``` cmd

>go run main.go
path.dir: .
filepath.dir: c:\aa\bb


```

File: config.go [hunk 1]
```diff
@@ -1608,17 +1607,17 @@ func extractBitcoindRPCParams(networkName string,
 		dataDir = string(dataDirSubmatches[1])
 	}
 
-	chainDir := "/"
+	chainDir := ""
```
Comment (guggero) [inline config.go:1610]: Can set this to `chainDir` directly and only set to empty on `case "mainnet"`?

**Review by guggero — COMMENTED** [review]
Nice, fix, thank you!
Just one comment about the switch statement, otherwise looks good to me :tada:

File: config.go (hunk 1 above)
Comment (GameXG) [reply config.go:1610]:
``` go

	chainDir := ""
	switch networkName {
	case "mainnet":
		chainDir = ""
	case "testnet3":
		chainDir = "testnet3"
	case "testnet4":
		chainDir = "testnet4"
	case "regtest":
		chainDir = "regtest"
	default:
		return "", "", "", "", fmt.Errorf("unexpected networkname %v", networkName)
	}

```

hello,
I'm not sure if there are other networks, have they met expectations?

**Review by guggero — COMMENTED** [review]
Code looks good, thank you!

Could you please squash the commits and update the commit message [according to the contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure)? Thanks.

**Review by bhandras — APPROVED** [review]
LGTM

**Review by guggero — APPROVED** [review]
