### PR TITLE
itest: fix restore backup file test flake for bitcoind backend

### LINKED ISSUE #5634: Restorechanbackup: panic: runtime error: invalid memory address or nil pointer dereference
Unfortunately, I overwritten the working .lnd/data folder with my old 2019 backup (.lnd/data) and lost all information about channels.

When I start my LND node and try to recover channel from actual channel.backup
`lncli restorechanbackup --multi_file=channel.backup`

 lnd crashes with error:

 `2021-08-17 01:37:20.910 [INF] LTND: SCB Recovery: created channel shell for ChannelPoint(acccdb3db58bd707b82e6cb3746e0bffa24bf1b620dc05df91459d38f7c27b1c:0), chan_type=2
2021-08-17 01:37:20.910 [INF] LTND: Inserting 1 SCB channel shells into DB
2021-08-17 01:37:20.913 [INF] LTND: Informing chain watchers of new restored channels
2021-08-17 01:37:20.914 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(acccdb3db58bd707b82e6cb3746e0bffa24bf1b620dc05df91459d38f7c27b1c:0)
2021-08-17 01:37:20.916 [INF] CNCT: ChannelArbitrator(acccdb3db58bd707b82e6cb3746e0bffa24bf1b620dc05df91459d38f7c27b1c:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=696129
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xaff441]`

[recover.txt](https://github.com/lightningnetwork/lnd/files/6995935/recover.txt)

Environment
version": "0.13.99-beta commit=v0.13.0-beta-150-gedd41526
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-34-generic x86_64)

### PR DESCRIPTION
**Pull request by yyforyongyu**
This PR fixes the flake found in the [build](https://app.travis-ci.com/github/lightningnetwork/lnd/jobs/530874124)
```go
--- FAIL: TestLightningNetworkDaemon/tranche02/56-of-82/bitcoind/channel_backup_restore/restore_force_closed_from_backup_file_anchors
    assertions.go:1182: 
            Error Trace:    assertions.go:1182
                                        lnd_channel_backup_test.go:1095
                                        lnd_channel_backup_test.go:437
            Error:          Received unexpected error:
                            wanted 3, found 2 txs in mempool: [e08034649e8d9abae17673133d911fff152f7c6620fd7ab89c1bdf638f2d579a 5937d42f77f78afc6ca75438a975164c31f99f2a2a7affa82b392303861fce6a]
            Test:           TestLightningNetworkDaemon/tranche02/56-of-82/bitcoind/channel_backup_restore/restore_force_closed_from_backup_file_anchors
            Messages:       unable to find Carol's sweep tx in mempool
```

In short, what happened was the sweeper was not aware of the UTXOs because the rescanning addresses in recovery mode was not finished, thus no sweep tx was created. This can be fixed by ensuring that the wallet is synced before the test(which turns out to be an [older fix](https://github.com/lightningnetwork/lnd/pull/4685) btw). I think we need the fix. If the "2 hour not active" became a problem, we could fix it in the itest.

By removing the special branch for itest, a nil pointer dereference error was caught. It was caused by making RPC call before the server was fully started. This issue is fixed by checking the server status in the RPC call.

A side question, do we still use the profile generated from itest? Was thinking maybe `h.lndHarness.SaveProfilesPages` could be removed?

The nil deference error,
```go
=== CONT  TestLightningNetworkDaemon
    test_harness.go:119: lnd finished with error (stderr):
        exit status 2
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1731881]
        
        goroutine 173 [running]:
        github.com/lightningnetwork/lnd/chainntnfs.(*TxNotifier).RegisterSpend(0x0, 0xc000599524, 0xc00177f000, 0x22, 0x1f4, 0xc0000001cd, 0x0, 0x0, 0x0)
            .../lnd/chainntnfs/txnotifier.go:991 +0x61
        github.com/lightningnetwork/lnd/chainntnfs/btcdnotify.(*BtcdNotifier).RegisterSpendNtfn(0xc000172000, 0xc000599524, 0xc00177f000, 0x22, 0x1f4, 0x1cd, 0x0, 0x0, 0x1f4)
            .../lnd/chainntnfs/btcdnotify/btcd.go:701 +0x86
        github.com/lightningnetwork/lnd/contractcourt.(*chainWatcher).Start(0xc0013e4300, 0xc00154a8e0, 0x0)
            .../lnd/contractcourt/chain_watcher.go:267 +0x264
        github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).WatchNewChannel(0xc0004ee6e0, 0xc000599500, 0x0, 0x0)
            .../lnd/contractcourt/chain_arbitrator.go:1138 +0x48f
        github.com/lightningnetwork/lnd.(*chanDBRestorer).RestoreChansFromSingles(0xc00143c2c0, 0xc000457980, 0x1, 0x1, 0x1, 0x1)
            .../lnd/chanrestore.go:272 +0x2fd
        github.com/lightningnetwork/lnd/chanbackup.Recover(0xc000457800, 0x1, 0x1, 0x2462a80, 0xc00143c2c0, 0x2462ae0, 0xc00003a500, 0x2482f00, 0xb2c8380)
            .../lnd/chanbackup/recover.go:50 +0x20c
        github.com/lightningnetwork/lnd/chanbackup.UnpackAndRecoverMulti(0xc00142c1c0, 0x1a7, 0x1c0, 0xb2c8380, 0xc0004be6c0, 0x2462a80, 0xc00143c2c0, 0x2462ae0, 0xc00003a500, 0xc001440000, ...)
            .../lnd/chanbackup/recover.go:122 +0xc9
        github.com/lightningnetwork/lnd.(*rpcServer).RestoreChannelBackups(0xc0004e6750, 0x2482f80, 0xc000a4a000, 0xc0005c4700, 0xc0004e6750, 0x2176820, 0xb29e1e0)
            .../lnd/rpcserver.go:6485 +0x4d0
        github.com/lightningnetwork/lnd/lnrpc._Lightning_RestoreChannelBackups_Handler.func1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0x26, 0x0, 0x0, 0x0)
            .../lnd/lnrpc/lightning_grpc.pb.go:2735 +0x8b
        github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).MacaroonUnaryServerInterceptor.func1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0xc00143c0a0, 0xc0005d0120, 0xc0005c4700, 0xc00142c000, 0x1aa, 0x1aa)
            .../lnd/rpcperms/interceptor.go:488 +0xc2
        github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0x0, 0x1aa, 0x0, 0x0)
            .../go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63
        github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).rpcStateUnaryServerInterceptor.func1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0xc00143c0a0, 0xc00143c0c0, 0x203000, 0x0, 0xc001433a18, 0x1a73e4e)
            .../lnd/rpcperms/interceptor.go:579 +0xad
        github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0x20, 0x2067160, 0x1c, 0xc001433a60)
            .../go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63
        github.com/lightningnetwork/lnd/rpcperms.errorLogUnaryServerInterceptor.func1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0xc00143c0a0, 0xc00143c0e0, 0x1c79a7a, 0x2067160, 0xc00143c100, 0xc00143c0a0)
            .../lnd/rpcperms/interceptor.go:404 +0x82
        github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0xc00005e480, 0x0, 0xc001433b30, 0x100e158)
            .../go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63
        github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x2482f80, 0xc000a4a000, 0x2090080, 0xc0005c4700, 0xc00143c0a0, 0xc0005d0120, 0xc001429ba0, 0x11b1646, 0x20a3e80, 0xc000a4a000)
            .../go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xd7
        github.com/lightningnetwork/lnd/lnrpc._Lightning_RestoreChannelBackups_Handler(0x2176820, 0xc0004e6750, 0x2482f80, 0xc000a4a000, 0xc0004aa000, 0xc0004ea510, 0x2482f80, 0xc000a4a000, 0xc00142c000, 0x1aa)
            .../lnd/lnrpc/lightning_grpc.pb.go:2737 +0x150
        google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ec1c0, 0x2491eb8, 0xc0003c4d80, 0xc0002ae6c0, 0xc0004ea7e0, 0x2d22a28, 0x0, 0x0, 0x0)
            .../go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
        google.golang.org/grpc.(*Server).handleStream(0xc0004ec1c0, 0x2491eb8, 0xc0003c4d80, 0xc0002ae6c0, 0x0)
            .../go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
        google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00053e080, 0xc0004ec1c0, 0x2491eb8, 0xc0003c4d80, 0xc0002ae6c0)
            .../go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0xab
        created by google.golang.org/grpc.(*Server).serveStreams.func1
            .../go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
        
=== CONT  TestLightningNetworkDaemon/tranche00/56-of-82/btcd/channel_backup_restore/restore_from_RPC_backup
    test_harness.go:94: Error outside of test: *errors.errorString unable to restore node: unable to restore backups: rpc error: code = Unavailable desc = error reading from server: EOF
        .../lnd/lntest/itest/lnd_channel_backup_test.go:1055 (0x1b3916d)
            testChanRestoreScenario: t.Fatalf("unable to restore node: %v", err)
        .../lnd/lntest/itest/lnd_channel_backup_test.go:437 (0x1bb5d7b)
            testChannelBackupRestore.func11: testChanRestoreScenario(h, net, &testCase, password)
        /usr/local/Cellar/go/1.16/libexec/src/testing/testing.go:1194 (0x111980f)
            tRunner: fn(t)
        /usr/local/Cellar/go/1.16/libexec/src/runtime/asm_amd64.s:1371 (0x10717e1)
            goexit: BYTE    $0x90   // NOP
write log got err: write .logs-tranche0/4-channel_backup_restore-dave-tmp__.log: file already closed--- FAIL: TestLightningNetworkDaemon (14.84s)
    --- FAIL: TestLightningNetworkDaemon/tranche00/56-of-82/btcd/channel_backup_restore (13.70s)
        --- FAIL: TestLightningNetworkDaemon/tranche00/56-of-82/btcd/channel_backup_restore/restore_from_RPC_backup (9.15s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1aff4f7]
```

Fixes #5634

### CODE REVIEW

File: lnd.go [hunk 1]
```diff
@@ -893,56 +893,52 @@ func Main(cfg *Config, lisCfg ListenerCfg, interceptor signal.Interceptor) error
...
-				err := fmt.Errorf("unable to determine if "+
-					"wallet is synced: %v", err)
-				ltndLog.Error(err)
-				return err
-			}
+	// We'll wait until we're fully synced to continue the start up of the
+	// remainder of the daemon. This ensures that we don't accept any
+	// possibly invalid state transitions, or accept channels with spent
+	// funds.
+	_, bestHeight, err := activeChainControl.ChainIO.GetBestBlock()
```
Comment (guggero) [inline lnd.go:900]: While I think it's correct to always wait to be synced, I'm still a bit worried about breaking too many people's test setups/assumptions with this. Alternatively we could just add an override flag here that we only set for our itests? Either as a config flag or a build tag specific variable.

**Review by guggero — COMMENTED** [review]
Great fix, thanks! This possibly also solves cases like https://github.com/lightningnetwork/lnd/issues/5634.

My main concern is breaking other people's test setup. But maybe we should just do it and see what happens...

File: lnd.go (hunk 1 above)
Comment (yyforyongyu) [reply lnd.go:900]: tbh I'm also concerned that this simple change might cause lots of unknown problems...however the build results look promising tho. I think if our setups/assumptions are based on an unsynced chain or wallet, I'm keen to fix those issues. Making a special case for `itest` imo decreases the efficacy of the tests. I'll be closely watching out for related effects from this change. WDYT?

Comment (guggero) [reply lnd.go:900]: Yeah, you're right, adding another special case to the itests is probably not a good idea. I'm in favor of removing the condition and waiting for sync on all networks. @Roasbeef what's your opinion?

We will need to highlight this a bit more in the release notes, so an item somewhere in the `# Wallet` section that explains the change in a bit more detail.

**Review by guggero — APPROVED** [review]

File: lnd.go (hunk 1 above)
Comment (yyforyongyu) [reply lnd.go:900]: Updated!
Also do you think the `bitcoind`'s 2-hour-not-synced rule is configurable? Meaning can we change it to longer hours?

Comment (guggero) [reply lnd.go:900]: Hmm, I don't think that's something that can be configured. It might be hard coded in and the two hours are actually the same time span that a block is allowed to be out of a node's time range to still be accepted?

I found this instead: https://github.com/lightningnetwork/lnd/issues/3336
@carlaKC do you remember why you opened that issue originally? Where did you encounter problems with a stale chain?

Comment (carlaKC) [reply lnd.go:900]: I just ran into it occasionally in local dev when I was testing off-chain stuff and didn't mine a block in 2 hours. Seemed logical to add the exception for regtest since simnet was already there.

Comment (Roasbeef) [reply lnd.go:922]: In practice what I think will happen is that those running in regtest/simnet/signet, etc will need to _mine_a new block before `lnd` fully starts up. 

As is, it'll insta start up, but then users will need to mine a new block in order to have things flip to "synced to chain". 

Alternatively, couldn't we just apply this logic, but at the `lntest.NewNode` level? So that ends up blocking (using a similar loop as below) to ensure that all nodes are fully ready to go before being used within tests? So rather than making a special case within the itests, we instead just ensure that no node is actually usable (the initialization method will _block_) until the node is fully synced to the chain. 

Otherwise, I can see this change messing up things like Polar when users may have longer lived simnet chains with several nodes connected to them.

File: lnrpc/lightning.proto [hunk 2]
```diff
@@ -1678,6 +1678,9 @@ message GetInfoResponse {
     announcements and invoices.
     */
     map<uint32, Feature> features = 19;
+
+    // Whether the lnd server has been fully started.
+    bool started = 21;
```
Comment (Roasbeef) [inline lnrpc/lightning.proto:1683]: Why do we need this if we have the main status endpoint? 

It's also the case that there exists rpc methods that _can't_ be called before the server is fully started up. The work to ensure we send out specific error codes could help here as well.

File: rpcserver.go [hunk 3]
```diff
@@ -6566,6 +6566,12 @@ func (r *rpcServer) ExportAllChannelBackups(ctx context.Context,
 func (r *rpcServer) RestoreChannelBackups(ctx context.Context,
 	in *lnrpc.RestoreChanBackupRequest) (*lnrpc.RestoreBackupResponse, error) {
 
+	// The server hasn't yet started, so it won't be able to service any of
+	// our requests, so we'll bail early here.
+	if !r.server.Started() {
+		return nil, ErrServerNotActive
```
Comment (Roasbeef) [inline rpcserver.go:6572]: Similar to this issue https://github.com/lightningnetwork/lnd/issues/5586 -- if we return an actual error code here, we can do a normal type/value check from the PoV of any caller. 

It's a sort of a tangent, but we could also expand this to just live at the `rpcperms` level, and deny all calls (with the same error, other than a set few like GetInfo) that shouldn't be called before the server is fully started up.

File: lntest/node.go [hunk 4]
```diff
@@ -984,6 +985,11 @@ func (hn *HarnessNode) FetchNodeInfo() error {
 		return err
 	}
 
+	// Check that the node is fully started.
+	if !info.Started {
```
Comment (Roasbeef) [inline lntest/node.go:989]: See prior comment re just having the node creation pause until it's fully started up. 

Also same comment here re just using the exiting status endpoint (which was intended for this type of synchronization).

File: lntest/itest/lnd_channel_backup_test.go [hunk 5]
```diff
@@ -1048,6 +1040,13 @@ func testChanRestoreScenario(t *harnessTest, net *lntest.NetworkHarness,
 		t.Fatalf("unable to restore node: %v", err)
 	}
 
+	// Wait for the node to finish starting.
+	ctxt, cancel := context.WithTimeout(ctxb, defaultTimeout)
+	defer cancel()
+
+	err = dave.WaitForBlockchainSync(ctxt)
```
Comment (Roasbeef) [inline lntest/itest/lnd_channel_backup_test.go:1047]: Can be done _within_ the `restroedNodeFunc` so the `Restart()` method itself? May also help tighten up other issues we're seeing in the itests as well.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: lnrpc/lightning.proto (hunk 2 above)
Comment (yyforyongyu) [reply lnrpc/lightning.proto:1683]: Which main status endpoint? The `InterceptorChain.GetState`?
Initially I did think about putting the state there, only to found out later the `GetState` seemed to be referring to wallet state, not the lnd server state. On the other hand, the rpc server is started before the main server, and we only `SetRPCActive()` right after the rpc server is started.

I think what we could do instead is to add a new state to `InterceptorChain`, and a new method `SetServerActive()` to mark the server is fully started.

File: rpcserver.go (hunk 3 above)
Comment (yyforyongyu) [reply rpcserver.go:6572]: Cool stuff. Was reading [this](https://jbrandhorst.com/post/grpc-errors/) the other day, and I think it's def better if we could start using the `status`. Speaking of which, since the error codes are global values(from the user's PoV), maybe we should define an error code system if we want to use it in all RPC servers?

File: lnd.go (hunk 1 above)
Comment (yyforyongyu) [reply lnd.go:922]: A bit confused here...are you suggesting we keep the special case for regtest/simnet or remove it?

The problem with waiting in `lntest.NewNode` is that, in this case, it's not the itest that relies on it being synced, rather, it's the subserver that requires the wallet to be synced within `lnd`. The test failed because the sweeper started before the wallet was synced, thus the rescanning part was not finished and the sweeper was not aware of the UTXOs. This, however, wouldn't happen if it's on mainnet/testnet because we always require the wallet to finish syncing before moving forward, hence starting the server.

I think what's more important is that we want to have our itest best emulating the actual onchain conditions, yet we seem to have broken that promise by splitting another branch and build tests against it. They differ slightly and may have unintentional consequences, but I have the feeling the seeming nuance will bite us...

File: rpcserver.go (hunk 3 above)
Comment (yyforyongyu) [reply rpcserver.go:6572]: ha nvm I found this [proposal](https://github.com/lightningnetwork/lnd/pull/5436#issuecomment-909307926).

File: lnd.go (hunk 1 above)
Comment (yyforyongyu) [reply lnd.go:922]: A bit confused here...are you suggesting we keep the special case for regtest/simnet or remove it?

The problem with waiting in `lntest.NewNode` is that, in this case, it's not the itest that relies on it being synced, rather, it's the subserver that requires the wallet to be synced within `lnd`. The test failed because the sweeper started before the wallet was synced, thus the rescanning part was not finished and the sweeper was not aware of the UTXOs. This, however, wouldn't happen if it's on mainnet/testnet because we always require the wallet to finish syncing before moving forward, hence starting the server.

I think what's more important is that we want to have our itest best emulating the actual onchain conditions, yet we seem to have broken that promise by splitting another branch and build tests against it. They differ slightly and may have unintentional consequences, but I have the feeling the seeming nuance will bite us...

File: lntest/itest/lnd_channel_backup_test.go (hunk 5 above)
Comment (yyforyongyu) [reply lntest/itest/lnd_channel_backup_test.go]: This commit was removed as we now require the node to be started when calling `HarnessNode.start()`.

File: lnrpc/lightning.proto (hunk 2 above)
Comment (Roasbeef) [reply lnrpc/lightning.proto:1683]: Yeah I mean either `GetState` or `SubscribeState`. I see what you mean in taht we only have RPC active, and not a state that triggers right after the server is fully active. I think going with the option of adding this new state is the way to go, we can then call this right after we do the final initialization to start up the server.

Comment (yyforyongyu) [reply lnrpc/lightning.proto]: Cool, changed to be using the interceptor chain, PTAL.

**Review by Roasbeef — APPROVED** [review]
LGTM 🏸

**Comment by Roasbeef** [comment]
Just needs a rebase now!

**Comment by yyforyongyu** [comment]
> Just needs a rebase now!

Done!
