### PR TITLE
config: misconfigured bitcoind zmq

### LINKED ISSUE #4636: Health check does not pick up misconfigured bitcoind ZMQ arguments
### Background

I started LND with switched `bitcoind.zmqpubrawtx` and `bitcoind.zmqpubrawblock` ports. I didn't notice for several weeks because I could both send and receive lightning payments. One day I couldn't send payments anymore because `ExpiryTooFar`.
I also had a bunch of these logs in lnd:
```
2020-09-20 20:04:25.475 [INF] DISC: Update announcement for short_chan_id(713051982387740673), is premature: advertises height 648517, only height 647146 is known
```

I ended up in a potentially dangerous situation because LND wasn't notified of new transactions or blocks. Therefore my LND has not been able to sweep force closes between block 647146 and 648517.

### Your environment

* version of `lnd`
v0.9.2
* which operating system (`uname -a` on *Nix)
`Linux #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
`bitcoind v0.19.1`
* any other relevant environment details

### Steps to reproduce

1. Start bitcoind with these flags:
```
 $ bitcoind
-zmqpubrawtx=tcp://0.0.0.0:12397
-zmqpubrawblock=tcp://0.0.0.0:12398
```
2. Start lnd with these flags:
```
 $ lnd
--bitcoind.zmqpubrawtx=tcp://bitcoind:12398
--bitcoind.zmqpubrawblock=tcp://bitcoind:12397
```
Notice that the rawtx and rawblock ports are not equal. So lnd can't actually receive any events from the ZM Queue.

My node was running for a while with this config, leading to lots of logs like:
```
2020-09-20 20:04:25.475 [INF] DISC: Update announcement for short_chan_id(713051982387740673), is premature: advertises height 648517, only height 647146 is known
```

### Expected behaviour
The new health checks in v0.11.1 should not pass, because lnd is misconfigured.

### Actual behaviour
LND starts and chugs along happily (for a while).

### PR DESCRIPTION
**Pull request by ErikEk**
Fixes #4636
This PR makes sure lnd listens to the correct zmq notifications.
Right now, a potentially dangerous situation can occur if the ports of `zmqpubrawtx`/`zmqpubrawblock` (bitcoind) and `bitcoind.zmqpubrawtx`/`bitcoind.zmqpubrawblock` (lnd) gets mixed up (as described in #4636). This would result in lnd not being notified of new transactions and/or blocks.
Another potential risk right now stems from users, by misstake, using `zmqpubhashtx` instead of `zmqpubrawtx` and `zmqpubhashblock` instead of `zmqpubrawblock` when configuring bitcoind (as described in https://github.com/lightningnetwork/lnd/issues/4636#issuecomment-884892299). This would cause the same issue.

### CODE REVIEW

**Comment by carlaKC** [comment]
> In this commit, I'm utilizing the health check mechanism - would it be better to check the setup once instead of continuously?

If we're protecting against misconfiguration I think that it makes more sense to have a once-off check on startup?

**Review by carlaKC — COMMENTED** [review]
> If we're protecting against misconfiguration I think that it makes more sense to have a once-off check on startup?

Thoughts on this @ErikEk?

**Comment by ErikEk** [comment]
@carlaKC you are probably right. It should be enough. Let me see if I can make it work.

**Comment by ErikEk** [comment]
Not ready for review.

**Review by carlaKC — COMMENTED** [review]
Tested this out with incorrect ports (switched the two around), and it seems that bitcoind might just be echoing back our incorrect ports?

From [0.17 docs](https://bitcoincore.org/en/doc/0.17.0/rpc/zmq/getzmqnotifications/) "returns information about the active ZeroMQ notifications" isn't totally clear, but I can see that it might just be returning our values?

I might have tested this out incorrectly, so please double check me on this!

**Review by carlaKC — APPROVED** [review]
Not even a nit, thanks for this one! I think it's going to be very helpful for people getting mixed up about ports (like me 😅 ).

**Comment by carlaKC** [comment]
Release notes entry just needs to be updated to 0.15!

**Comment by ErikEk** [comment]
@carlaKC Thank for the review. Pr is now updated with notes for 0.15.

File: chainreg/chainregistry.go [hunk 1]
```diff
@@ -485,11 +486,93 @@ func NewPartialChainControl(cfg *Config) (*PartialChainControl, func(), error) {
...
 		if err != nil {
 			return nil, nil, err
 		}
 
+		// If the getzmqnotifications api is available (was added in
+		// version 0.17.0) we make sure lnd subscribes to the correct
+		// zmq events. We do this to avoid a situation in which we are
+		// not notified of new transactions or blocks.
+		if ver >= 170000 {
+
```
Comment (bhandras) [inline chainreg/chainregistry.go:499]: nit: extra nl

**Review by bhandras — APPROVED** [review]
LGTM, great work @ErikEk :1st_place_medal:

File: chainreg/chainregistry.go (hunk 1 above)
Comment (ErikEk) [reply chainreg/chainregistry.go]: @bhandras Thank you for your review. Nit fixed.
