### PR TITLE
Litecoin fixes

### LINKED ISSUE #936: Different zmqpath ports in install dokumentations
As new user I would like to follow the default configuration. Bitcoin.conf and lnd.conf contain different zmqpath ports. Which one is the recommended default port?

Port 28332: https://github.com/lightningnetwork/lnd/blob/47329c9267f03887a2f1596a99f23446dc7d4176/docs/INSTALL.md#L215
Port 18501 https://github.com/lightningnetwork/lnd/blob/0c1b619e53ac88ad53f3a88e5d1129c25ddeaf13/sample-lnd.conf#L190

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Minor fixes for litecoin related stuff.

Was trying to get LND running on litecoin testnet, noticed some problems in the sample config file. This also fixes [bug reported by justin on slack](https://lightningcommunity.slack.com/archives/C6BFMETDL/p1521496526000030).

Closes #936 and #914

### CODE REVIEW

**Comment by bretton** [comment]
zmqpath conflicts with recently committed changes in https://github.com/lightningnetwork/lnd/commit/47329c9267f03887a2f1596a99f23446dc7d4176

To retain consistency change
```
litecoind.zmqpath=tcp://127.0.0.1:18501
```

to 
```
litecoind.zmqpath=tcp://127.0.0.1:28332
```

**Comment by nalinbhardwaj** [comment]
@bretton : Heh, sample config still seems to be using [`bitcoind.zmqpath=tcp://127.0.0.1:18501`](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L190). I'll fix that as well.

File: config.go [hunk 1]
```diff
@@ -407,18 +407,20 @@ func loadConfig() (*config, error) {
...
 		var ltcParams litecoinNetParams
 		if cfg.Litecoin.MainNet {
 			numNets++
 			ltcParams = litecoinMainNetParams
+			activeNetParams = bitcoinMainNetParams
 		}
 		if cfg.Litecoin.TestNet3 {
 			numNets++
 			ltcParams = litecoinTestNetParams
+			activeNetParams = bitcoinTestNetParams
```
Comment (Roasbeef) [inline config.go]: If you look below, we apply the Litecoin params to activeNetParams below.

**Comment by Roasbeef** [comment]
I don't see why these fixes are necessary. As in, out of the box, Litecoin mode works fine for me. Is this an attempt to fix `getinfo` showing `testnet` as true for Litecoin?

**Comment by nalinbhardwaj** [comment]
@roasbeef : yeah.

An alternate might be to detect it inline in getinfo RPC, but I don’t think chain related logic should leak too much outside of chainparams.go?

File: config.go (hunk 1 above)
Comment (nalinbhardwaj) [reply config.go]: Have I misunderstood something? This line is just to prevent equality [here](https://github.com/lightningnetwork/lnd/blob/237ed4fc6ec3f34a67a65e1e79cb43302b0cb634/rpcserver.go#L1200). I am unable to actually test it on main-net, but flipping this setting(faking mainnet for the part) shows testnet: false, as expected...

**Comment by cfromknecht** [comment]
The strongest way of doing this inspecting the `activeNetParams.Params.Net` field. btcd uses `wire.TestNet3`, while ltcd uses `wire.TestNet4`. Note that the two wire packages are distinct. Something like:
```golang
func isTestnet() bool {
    switch activeNetParams.Params.Net {
    case bwire.TestNet3, lwire.TestNet4:
        return true
    default:
        return false
    }
}

// Set inline in response as you suggestted
```

**Comment by nalinbhardwaj** [comment]
@cfromknecht : Fixed.

File: sample-lnd.conf [hunk 2]
```diff
@@ -207,18 +207,20 @@ bitcoin.node=btcd
 ; active.
 ; litecoin.active=1
 
-; Use Bitcoin's test network.
+; Use Litecoin's test network.
 ; litecoin.testnet=1
 ; 
-; Use Bitcoin's simulation test network
+; Use Litecoin's simulation test network
```
Comment (cfromknecht) [inline sample-lnd.conf]: We might consider removing these, as we currently don't have an ltc simnet.

File: sample-lnd.conf [hunk 3]
```diff
@@ -207,18 +207,20 @@ bitcoin.node=btcd
...
 litecoin.simnet=1
 
-; Use Bitcoin's regression test network
+; Use Litecoin's regression test network
```
Comment (cfromknecht) [inline sample-lnd.conf]: we also don't support ltc regnet :P

File: sample-lnd.conf (hunk 2 above)
Comment (nalinbhardwaj) [reply sample-lnd.conf]: Fixed.
