### PR TITLE
REST: Enable support for bi-directional streaming RPCs over REST, fix ping/pong support

### LINKED ISSUE #4120: Channel Acceptor Available on REST API
### Background

It would be great to be able to use the channel acceptor RPC from the REST API.

### Expected behaviour

I would like to have an application which uses thread to monitor the channel acceptor streaming API.

### Actual behaviour

You are only able to configure this through the gRPC interface, not through command line or REST.

### LINKED ISSUE #4497: REST Websocket proxy doesnt respond ping with pong
### Background

When using the rest websocket proxy, some websocket clients send periodic pings, and expect to receive pongs, or else it will close the connection. It doesn't appear as if LND is responding to those pings, so additional flags need to be used to prevent accidental closes of the websocket.

I am trying to use the REST '/v2/router/htlcevents' endpoint stream.

### Your environment

* version of `lnd`
    "version": "0.10.1-beta commit=clock/v1.0.0-250-ga39c91fbcb9b002c93cae3432771b295ea4a942c-dirty",
    "commit_hash": "a39c91fbcb9b002c93cae3432771b295ea4a942c",
* which operating system (`uname -a` on *Nix)
ubuntu
* version of `btcd`, `bitcoind`, or other backend
bitcoind
* any other relevant environment details
python3.8 using the websocket package

### Steps to produce
This is the stack overflow page that described the result of my issue: https://github.com/miguelgrinberg/python-socketio/issues/310

Code example:
```
import websockets
import asyncio
import ssl
import logging
logger = logging.getLogger('websockets')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

macaroon = codecs.encode(open(f'{LND_DIR}/data/chain/bitcoin/{CHAIN}/admin.macaroon', 'rb').read(), 'hex').decode()

headers = {'Grpc-Metadata-macaroon': macaroon}

ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
ssl_context.load_verify_locations('/home/sako09038/.lnd/tls.cert')

async def htlcevents2():
	ws = await websockets.connect("wss://10.0.0.111:8080/v2/router/htlcevents?method=GET", ping_timeout=None,ping_interval=1, ssl=ssl_context, extra_headers=headers, max_size=1000000000)
	# future = asyncio.run_coroutine_threadsafe(pinger(ws), loop)
	print('waiting')
	await asyncio.sleep(1)
	print('priming')
	await ws.send(json.dumps({}).encode('UTF-8'))
	async for message in ws:
		print('receiving')
		try:
			hi = await asyncio.wait_for(ws.recv(), timeout=5)
			hi = json.loads(hi)
			hi = hi['result']
			await ws.ping()
			pprint(hi)
		except asyncio.TimeoutError:
			print('timeout!')
		except asyncio.CancelledError:
			print("cancelled?")


async def main():
	loop = asyncio.get_event_loop()
	await htlcevents2()

asyncio.run(main())
```

When I opened my websocket as such I received a "no pong received error":
```ws = await websockets.connect("wss://10.0.0.111:8080/v2/router/htlcevents?method=GET", ping_interval=1, ssl=ssl_context, extra_headers=headers, max_size=1000000000)
client > Frame(fin=True, opcode=2, data=b'{}', rsv1=False, rsv2=False, rsv3=False)
client > Frame(fin=True, opcode=9, data=b'j\xd1\xcb\xd8', rsv1=False, rsv2=False, rsv3=False)
client ! timed out waiting for pong
client ! failing OPEN WebSocket connection with code 1011
client - state = CLOSING
client > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
client ! timed out waiting for TCP close
client x closing TCP connection
client ! timed out waiting for TCP close
client x aborting TCP connection
client - event = connection_lost(None)
client - state = CLOSED
```

However, opening up the socket as so, telling it to ignore missing pongs, I am able to keep the socket alive long term:

```
ws = await websockets.connect("wss://10.0.0.111:8080/v2/router/htlcevents?method=GET", ping_timeout=None,ping_interval=1, ssl=ssl_context, extra_headers=headers, max_size=1000000000)
```

What do you think? Is it bad that its not responding the pings with pongs? According to the linked stackoverflow the issue is non-compliance with: https://tools.ietf.org/html/rfc6455#section-5.5.3

### PR DESCRIPTION
**Pull request by guggero**
Fixes #4120
Fixes #4497

This PR fixes the WebSocket support for client-streaming (request-streaming) RPCs.
At the moment this is the `lnrpc.Lightning.ChannelAcceptor`, `lnrpc.Lightning.SendPayment` and `routerrpc.HtlcInterceptor`.

At the same time we also fix the keep-alive issue where the WebSocket server wouldn't respond to ping messages correctly.

### CODE REVIEW

File: lnrpc/websocket_proxy.go [hunk 1]
```diff
@@ -129,6 +134,11 @@ func (p *WebsocketProxy) upgradeToWebSocketProxy(w http.ResponseWriter,
 		request.Method = m
 	}
 
+	// Is this a call to a client-streaming RPC method?
+	streamParam := r.URL.Query().Get(ClientStreamingParam)
```
Comment (halseth) [inline lnrpc/websocket_proxy.go:162]: is there really no way of extracting what RPC is being called? Then we could've easily mapped that to whether it was client streaming or not.

File: lnrpc/websocket_proxy.go [hunk 2]
```diff
@@ -71,6 +78,14 @@ func NewWebSocketProxy(h http.Handler, logger btclog.Logger) http.Handler {
 			},
 		},
 	}
+
+	// If a ping interval is specified, we wait an additional 5 seconds for
+	// a pong answer.
+	if pingInterval > 0 {
+		p.pingInterval = pingInterval
+		p.pongWait = pingInterval + (5 * time.Second)
```
Comment (halseth) [inline lnrpc/websocket_proxy.go:86]: nit: brackets not needed

**Review by halseth — CHANGES_REQUESTED** [review]

File: lnrpc/websocket_proxy.go (hunk 1 above)
Comment (guggero) [reply lnrpc/websocket_proxy.go:162]: Unfortunately not, as far as I can tell. I even tried to use some black reflection magic but that also got me nowhere. I even checked if upgrading to the latest version of `grpc-gateway` somehow exposed more meta information that we could use for the lookup but that doesn't seem to be the case either. We could fork the `grpc-gateway` library but that seems excessive for (currently) just two request-streaming RPCs.

Comment (halseth) [reply lnrpc/websocket_proxy.go:162]: So what is set in the `r.URL` path? Is it blank?

Comment (guggero) [reply lnrpc/websocket_proxy.go:162]: It is set to the full URL (for example `/v1/channels/acceptor`). But we don't have any reverse mapping to the RPC method that's being called for it (except in `lnrpc/rest-annotations.yaml` which is not compiled into the binary). There's only the generated code in the `*.pb.gw.go` files and there's no mapping metadata there either (each HTTP method is generated individually instead of using a generic mapping).
We could of course keep an extra hard coded list of client-streaming RPCs somewhere and match against that. But then we'd very likely forget to add new URLs once we add new RPCs.

Comment (guggero) [reply lnrpc/websocket_proxy.go]: Discussed this offline and decided to go with a hard coded list maintained in `lnrpc` instead of putting the burden of the additional request parameter onto the client.

**Review by wpaulino — COMMENTED** [review]
Looks like some protos weren't generated? From Travis:
```
Protos not properly formatted or not compiled with v3.4.0
HEAD detached at FETCH_HEAD
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   lnrpc/rpc.pb.gw.go
	modified:   lnrpc/rpc.swagger.json
```

File: docs/rest/websockets.md [hunk 3]
```diff
@@ -97,3 +97,55 @@ ws.on('message', function(body) {
 //      "height": <int64>, 
 //  }
 ```
+
+## Request-streaming RPCs
+
+Starting with `lnd v0.13.0-bata` all RPCs can be used through REST, even those
```
[the remark this answers is not in the document]
Comment (guggero) [reply docs/rest/websockets.md:103]: :joy: oops. fixed

File: lnrpc/websocket_proxy.go [hunk 4]
```diff
@@ -200,6 +225,43 @@ func (p *WebsocketProxy) upgradeToWebSocketProxy(w http.ResponseWriter,
 		}
 	}()
 
+	// Ping write loop: Send a ping message regularly if ping/pong is
+	// enabled.
+	if p.pingPongEnabled() {
+		// Whenever a pong message comes in, we extend the deadline
+		// until the next read is expected by the pong wait time.
+		conn.SetPongHandler(func(appData string) error {
+			_ = conn.SetReadDeadline(time.Now().Add(p.pongWait))
```
[the remark this answers is not in the document]
Comment (guggero) [reply lnrpc/websocket_proxy.go]: When we send the ping, we want an answer back in 5 seconds. But once the pong comes in, we're okay with not receiving any message for `interval + pongWait`. With the updated logic this should be more clear now I hope.

File: lnrpc/websocket_proxy.go [hunk 5]
```diff
@@ -200,6 +225,43 @@ func (p *WebsocketProxy) upgradeToWebSocketProxy(w http.ResponseWriter,
...
+
+			for {
+				select {
+				case <-ctx.Done():
+					p.logger.Debug("ping loop done")
+					return
+
+				case <-ticker.C:
+					deadline := time.Now().Add(p.pongWait)
+					_ = conn.SetReadDeadline(deadline)
```
[the remark this answers is not in the document]
Comment (guggero) [reply lnrpc/websocket_proxy.go]: Good point. I changed the logic a bit to be more restrictive on the pong deadline.

File: lnrpc/websocket_proxy.go [hunk 6]
```diff
@@ -129,6 +142,14 @@ func (p *WebsocketProxy) upgradeToWebSocketProxy(w http.ResponseWriter,
 		request.Method = m
 	}
 
+	// Is this a call to a client-streaming RPC method?
+	clientStreaming := false
+	for _, pattern := range p.clientStreamingURIs {
```
Comment (halseth) [inline lnrpc/websocket_proxy.go:174]: 👍

File: lnrpc/websocket_proxy.go [hunk 7]
```diff
@@ -50,15 +51,26 @@ var (
...
 		"Grpc-Metadata-Macaroon": true,
 	}
+
+	// DefaultPingInterval is the default number of seconds to wait between
+	// sending ping requests.
+	DefaultPingInterval = time.Second * 30
+
+	// DefaultPongWait is the maximum duration we wait for a pong response
+	// to a ping we sent before we assume the connection died.
+	DefaultPongWait = time.Second * 5
```
Comment (halseth) [inline lnrpc/websocket_proxy.go:61]: could we be less aggressive here? Is there any downside to increasing this? (im thinking 5s could be too little for slow connections, tor etc)

**Review by halseth — APPROVED** [review]
LGTM, only q is whether we should be more lenient on the pong timeout. ✅

File: lnrpc/websocket_proxy.go (hunk 7 above)
Comment (guggero) [reply lnrpc/websocket_proxy.go:61]: I think this should be fine for most situations, as even with Tor 5 seconds is quite a long time. But I went ahead and made both numbers configurable, just in case.

File: lnrpc/websocket_proxy.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (wpaulino) [reply lnrpc/websocket_proxy.go]: We'd send another ping after 30 seconds though, which would enforce a new pong deadline, so seems the pong handler isn't necessary?

**Review by wpaulino — APPROVED** [review]
LGTM, just left a comment inline wondering if the pong handler is still necessary.

**Comment by guggero** [comment]
Ah, I see your point. I guess I got something confused in the initial implementation between `SetWriteDeadline` and `SetReadDeadline`. I've now implemented it according to the "official" example: https://github.com/gorilla/websocket/blob/master/examples/filewatch/main.go#L63

File: lnrpc/websocket_proxy.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (guggero) [reply lnrpc/websocket_proxy.go]: You're right, there was one unnecessary call. The one that was originally just before sending the ping should've been a `SetWriteDeadline` in the first place.

File: lnrpc/websocket_proxy.go [hunk 8]
```diff
@@ -230,6 +230,12 @@ func (p *WebsocketProxy) upgradeToWebSocketProxy(w http.ResponseWriter,
 	// Ping write loop: Send a ping message regularly if ping/pong is
 	// enabled.
 	if p.pingPongEnabled() {
+		// We'll send out our first ping in pingInterval. So the initial
+		// deadline is that interval plus the time we allow for a
+		// response to be sent.
+		initialDeadline := time.Now().Add(p.pingInterval + p.pongWait)
```
Comment (wpaulino) [inline lnrpc/websocket_proxy.go:236]: Nit: looks like these changes should've been squashed on commit https://github.com/lightningnetwork/lnd/pull/5237/commits/de175da7bd17ac3ba9e5cc8d8251039499d7dc82 instead?

**Review by wpaulino — APPROVED** [review]

File: lnrpc/websocket_proxy.go (hunk 8 above)
Comment (guggero) [reply lnrpc/websocket_proxy.go:236]: Oops, yes definitely. Fixed.
