### PR TITLE
multi: use bitcoind uptime api for healthcheck

### LINKED ISSUE #4669: Health check: chain backend failed after 3 calls. How to avoid the shutdown?
### Background

My LND node keeps shutting down. Seems like it's triggered by a short network failure preventing the node from reaching `bitcoind` 

### Your environment

* lnd version 0.11.99-beta commit=v0.11.0-beta-255-g10a84f2c75c9de958c9dd07de830f0546a43d05a
* which operating system: Debian GNU/Linux 10 4.19.0-8-amd64
* version of `bitcoind`: Bitcoin Core version v0.20.1
* `lnd` and `bitocoind` are on different servers

### Steps to reproduce

Restart LND. Repros every 1 to 2 days.

### Expected behaviour

Just keep running.

### Actual behaviour

```
2020-10-03 02:18:26.258 [INF] NTFN: New block: height=651006, sha=000000000000000000059e4ba6945311b11cf30cea4389ca932ebd0c89f5186c
2020-10-03 02:18:26.258 [INF] UTXN: Attempting to graduate height=651006: num_kids=0, num_babies=0
2020-10-03 02:18:58.221 [INF] CRTR: Processed channels=0 updates=554 nodes=1 in last 59.999815896s

2020-10-03 02:19:24.910 [CRT] SRVR: Health check: chain backend failed after 3 calls  <------------

2020-10-03 02:19:24.910 [INF] SRVR: Sending request for shutdown
```

#### Question

 How to avoid the shutdown?

### PR DESCRIPTION
**Pull request by carlaKC**
Previously we were using `GetBestBlock` for all of our healthchecks. This was running into some issues with `bitcoind`, because the `GetBestBlock` rpc call uses the csmain lock, which is widely used, and would block for extended periods of time (5 minutes sometimes!). `btcd` has more granular locking, so it does not face these issues. 

This PR updates our chain backend health check to use the `uptime` api because it has no locking. Another option would be to use something like `estimatesmartfee` which uses a less common lock in `bitcoind` and does not need us to make an ad-hoc `rpcclient`. Decided against this because `estimatesmartfee` could crunch through mempool data unnecessarily. 

Fixes #4669.

### CODE REVIEW

File: chainreg/chainregistry.go [hunk 1]
```diff
@@ -431,6 +442,20 @@ func NewChainControl(cfg *Config) (*ChainControl, error) {
...
+		// Bitcoind uses a widely-used lock for its GetBestBlock
+		// endpoint which makes it unsuitable for use as a health
+		// check because it can block for a long time. Instead, we use
+		// a call to the uptime endpoint as our health check function.
+		chainConn, err := rpcclient.New(rpcConfig, nil)
+		if err != nil {
+			return nil, err
+		}
+		cc.HealthCheck = func() error {
+			_, err := chainConn.RawRequest("uptime", nil)
```
Comment (Roasbeef) [inline chainreg/chainregistry.go:455]: Which version of `bitcoind` was this call added with? Perhaps we should do a version check on start up to warn the user about the feature, possibly falling back to the older way of doing things?

Comment (carlaKC) [reply chainreg/chainregistry.go:455]: First added in [0.15](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.0.md), will add a version check 👍

Comment (carlaKC) [reply chainreg/chainregistry.go:455]: Discussed online, Segwit added in [0.16](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.16.0.md) so you can't run lnd with a version that doesn't have the `uptime` endpoint, version check not required.

**Comment by carlaKC** [comment]
Updated this to have a version check to be safe, I don't think it costs us much. It's difficult to tell where the line is for segwit enabled because 0.13 has all the code, but then activation was more complex. All the 0.14 versions are also vulnerable to [inflation bug](https://bitcoincore.org/en/2018/09/20/notice/), so I think most people _should_ be running on 0.15 and above.

**Review by wpaulino — APPROVED** [review]

**Review by Roasbeef — APPROVED** [review]
LGTM 🍬

**Comment by C-Otto** [comment]
Thanks, that was quick :+1:
