### PR TITLE
peer: do not require static remote for peers with legacy channels

### LINKED ISSUE #4800: Maintain connection to nodes with existing legacy channels
After we flipped the `static_remote_key` feature to required (https://github.com/lightningnetwork/lnd/pull/4751) lnd will fail to connect to _existing channel peers_ without this feature. See https://github.com/ACINQ/eclair-mobile/issues/256

We should probably don't require this feature for nodes we have existing legacy channels with.

### PR DESCRIPTION
**Pull request by carlaKC**
This PR updates the peer package to downgrade the static remote key feature bit from required to optional in the case where we have legacy channels with the peer. Without this change, `lnd` will not connect to peers that do not recognize the feature bit, and any legacy channels with these peers will be unusable. 

The last commit in this PR adds a workflow which tests the upgrade path, since we do not have a way to test different versions in our itests. Rather than spin up an eclair mobile node (which does not recognize the feature bit), test test uses lnd `0.7.0-beta`, which does not recognize the feature bit, to test the upgrade path. **To be removed before merge.**

Fixes #4800

### CODE REVIEW

File: peer/brontide.go [hunk 1]
```diff
@@ -2752,12 +2766,19 @@ func (p *Brontide) RemoteFeatures() *lnwire.FeatureVector {
...
 
-// sendInitMsg sends the Init message to the remote peer. This message contains our
-// currently supported local and global features.
-func (p *Brontide) sendInitMsg() error {
+// sendInitMsg sends the Init message to the remote peer. This message contains
+// our currently supported local and global features.
+func (p *Brontide) sendInitMsg(legacyChan bool) error {
+	features := p.cfg.Features
+
+	if legacyChan && features.RequiresFeature(lnwire.StaticRemoteKeyRequired) {
```
Comment (halseth) [inline peer/brontide.go:2774]: Add a comment here.

File: peer/brontide_test.go [hunk 2]
```diff
@@ -862,6 +860,114 @@ func TestCustomShutdownScript(t *testing.T) {
...
+// bit to optional if we have legacy channels with a peer. This ensures that
+// we can stay connected to peers that don't support the feature bit that we
+// have channels with.
+func TestStaticRemoteDowngrade(t *testing.T) {
+	t.Parallel()
+
+	var (
+		// We set the same legacy feature bits for all tests, since these are
+		// not relevant to our test scenario
+		rawLegacy = lnwire.NewRawFeatureVector(lnwire.AnchorsOptional)
```
Comment (halseth) [inline peer/brontide_test.go:873]: Not sur if really matters for this test, but could use the `SingleFunderBit` here instead, since in realuty `AnchorsOptional` implies `StaticRemoteKeyOptional`.

File: peer/brontide_test.go [hunk 3]
```diff
@@ -862,6 +860,114 @@ func TestCustomShutdownScript(t *testing.T) {
...
+				},
+			}
+
+			var b bytes.Buffer
+			_, err := lnwire.WriteMessage(&b, test.expectedInit, 0)
+			require.NoError(t, err)
+
+			// Send our init message, assert that we write our expected message
+			// and shutdown our write pool.
+			require.NoError(t, p.sendInitMsg(test.legacy))
```
Comment (halseth) [inline peer/brontide_test.go:964]: Great test! 😮  🤩

File: scripts/static_remote.sh [hunk 4]
```diff
@@ -0,0 +1,73 @@
+#!/bin/bash
+
+set -ev
+
+./scripts/run_bitcoin.sh
+./scripts/run_lnd.sh carlakirkcohen/lnd:v0.11.1-beta 0
+./scripts/run_lnd.sh carlakirkcohen/lnd:v0.7.0-beta 1
```
Comment (halseth) [inline scripts/static_remote.sh:7]: did you test without the patch, checking whether v0.7 would disconnect from `master` when a legacy channel existed? AFAIK eclair is even stricter than LND in how it handles unknown required bits.

File: scripts/static_remote.sh [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+$BTC_CLI generatetoaddress 6 "$ADDR"
+
+waitnoerror chanCheck "$txid"
+
+echo Opened channel "$txid"
+
+echo Upgrading lnd to static remote required
+
+# Now we want to upgrade our node that understands static remote to require it.
+# Use a docker container which has our patch included in it.
```
Comment (halseth) [inline scripts/static_remote.sh:53]: add a step that updates to master, check that the  disconnect happens?

**Review by halseth — COMMENTED** [review]
Great work on the docker reproduction 👍  I think we shouldn't merge it, but great to see the scenario in action.

One question about if we ensure that lnd master actually would disconnect the legacy node, other than that it looks very good 💯

File: scripts/static_remote.sh (hunk 4 above)
Comment (carlaKC) [reply scripts/static_remote.sh:7]: 0.7 disconnect because on the unknown feature bit and 0.11 will keep trying to connect because we have a channel open. Tested this out manually on master 👍

**Comment by carlaKC** [comment]
> I think we shouldn't merge it

Agreed, also the bash has begun to sprawl so happy to axe the last commit 😅

File: peer/brontide.go [hunk 6]
```diff
@@ -2752,12 +2766,28 @@ func (p *Brontide) RemoteFeatures() *lnwire.FeatureVector {
...
+func (p *Brontide) sendInitMsg(legacyChan bool) error {
+	features := p.cfg.Features
+
+	// If we have a legacy channel open with a peer, we downgrade static
+	// remote required to optional in case the peer does not understand the
+	// required feature bit. If we do not do this, the peer will reject our
+	// connection because it does not understand a required feature bit, and
+	// our channel will be unusable.
+	if legacyChan && features.RequiresFeature(lnwire.StaticRemoteKeyRequired) {
+		peerLog.Infof("legacy channel open with peer: %x, "+
```
Comment (halseth) [inline peer/brontide.go:2780]: nit: capital first letter for logs

File: peer/brontide.go [hunk 7]
```diff
@@ -2752,12 +2766,28 @@ func (p *Brontide) RemoteFeatures() *lnwire.FeatureVector {
...
+			"downgrading static remote required feature bit to "+
+			"optional", p.PubKey())
+
+		features.Unset(lnwire.StaticRemoteKeyRequired)
```
Comment (halseth) [inline peer/brontide.go:2784]: I think I checked this, but just to make sure: Is `features` a local copy at this point, or do we risk unsetting the bit for our features for future handshakes? Could be worth calling `features.Clone()` here just to be sure :)

**Review by halseth — APPROVED** [review]
One question regarding checking we don't alter the feature bits for a pointer to our features, otherwise this LGTM 👍 

(also great work on the docker test, sad that it has to go but that's life 😿 )

File: peer/brontide.go [hunk 8]
```diff
@@ -446,9 +446,36 @@ func (p *Brontide) Start() error {
 
 	peerLog.Tracef("Peer %v starting", p)
 
+	// Fetch and then load all the active channels we have with this remote
+	// peer from the database.
+	activeChans, err := p.cfg.ChannelDB.FetchOpenChannels(
+		p.cfg.Addr.IdentityKey,
+	)
+	if err != nil {
+		peerLog.Errorf("unable to fetch active chans "+
```
Comment (bhandras) [inline peer/brontide.go:455]: nit: this could be capitalizaed

File: peer/brontide.go (hunk 7 above)
Comment (bhandras) [reply peer/brontide.go:2784]: It's a pointer, we need to clone.

File: peer/test_utils.go [hunk 9]
```diff
@@ -443,3 +449,55 @@ func createTestPeer(notifier chainntnfs.ChainNotifier,
...
+}
+
+// assertWrite asserts that our mock as had WriteMessage called with the byte
+// slice we expect.
+func (m *mockMessageConn) assertWrite(expected []byte) {
+	select {
+	case actual := <-m.writtenMessages:
+		require.Equal(m.t, expected, actual)
+
+	case <-time.After(timeout):
```
Comment (bhandras) [inline peer/test_utils.go:501]: do we want to fail here?

File: scripts/run_bitcoin.sh [hunk 10]
```diff
@@ -0,0 +1,30 @@
+#!/bin/bash
+
+set -ev
+
+BITCOIND_VERSION=${BITCOIN_VERSION:-0.18.1}
```
Comment (bhandras) [inline scripts/run_bitcoin.sh:5]: q: Are we using an old version intentionally?

**Review by bhandras — APPROVED** [review]
Looks good, a few nits remain.

File: scripts/run_bitcoin.sh (hunk 10 above)
Comment (carlaKC) [reply scripts/run_bitcoin.sh:5]: Yeah, bitcoind made a breaking change in the `GetBlockchainInfo` API, so we can't run 0.7 with the newer versions of core.

File: peer/brontide.go (hunk 7 above)
Comment (carlaKC) [reply peer/brontide.go:2784]: done!

**Comment by carlaKC** [comment]
> sad that it has to go but that's life 😿 

Valar Morghulis ⚔️ 

Bash test in [personal fork](https://github.com/carlaKC/lnd/tree/4800-withbashrepro) if it's still needed.

File: peer/brontide.go (hunk 7 above)
Comment (cfromknecht) [reply peer/brontide.go:2784]: FWIW `cfg.Features` is already a local copy, we clone a fresh feature vector for each connection from the static feature definitions 
https://github.com/lightningnetwork/lnd/blob/304a25691f14db448a55a6db55953c3864b7d80b/server.go#L3054
https://github.com/lightningnetwork/lnd/blob/304a25691f14db448a55a6db55953c3864b7d80b/feature/manager.go#L121
https://github.com/lightningnetwork/lnd/blob/304a25691f14db448a55a6db55953c3864b7d80b/feature/manager.go#L113

**Review by halseth — APPROVED** [review]
Valar dohaeris 🐲
