### PR TITLE
log: structured logging

### LINKED ISSUE #6163: Logging timestamps should be optional
lnd always prints timestamps in log messages.
This is redundant in systemd services (where log messages are automatically timestamped) and should be made optional.
This [SO post](https://stackoverflow.com/a/48630122/3806468) shows how this can be achieved

### LINKED ISSUE #6828: add a command line option to disable stdout and stderr
lnd has a log file that is written to that contains mostly the same (duplicate) information that is written to standard output and standard error. When running lnd as a systemd service, the systemd journal gets all of this information too from stdout and stderr. It would be nice to have a command line option that does not have the outputs written to standard output/error, only the lnd log file, this would avoid polluting the systemd journal with duplicate information. I'm aware that the log level can be changed, but I'd still like to capture more detailed information, I just don't necessarily want it going to the systemd journal too. When running on the command line, we can already redirect to /dev/null, but that's not as clean of an approach, especially when using systemd.

In bitcoind we have the -daemon option that does this silencing of standard output and standard error (since bitcoind also has its own dedicate log file) and also forks the process and puts it in the background. I'm not totally sure why bitcoind forks the process and sends it to the background, so I'm not sure if lnd wants to do this too. I don't see a particular advantage of it because then when running as a systemd service, lnd would need to communicate the pid to systemd so that it can keep track of whether it's actually running.

### LINKED ISSUE #8713: [bug]: Regression: Missing newline in "Shutdown complete" log message
See https://github.com/lightningnetwork/lnd/issues/3801. This bug resurfaced with `v0.17.3-beta` or before:

This is the output (in `lnd.log`) with `lncli stop` (v0.17.3-beta) and then re-starting lnd (v0.18.0-beta.rc1).
```
2024-04-30 15:21:12.886 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2024-04-30 15:21:12.899 [INF] LTND: Shutdown complete2024-04-30 15:21:19.087 [INF] LTND: REST API is disabled!
2024-04-30 15:21:19.089 [WRN] LTND: Config 'bitcoin.active' is deprecated, please remove it
```

### PR DESCRIPTION
**Pull request by ellemouton**
Update LND logger(s) to make use of structured logging (the `Logger` interface now has structured logging messages (`DebugS`, `InfoS` etc)) 

See btclog update here: https://github.com/btcsuite/btclog/pull/17

### Tracing

The big bonus of this update is that you only need to add your identifier(s) once to the context when the request comes in and then as long as you pass that context through & use it when you log, you dont need to remember to specify the identifiers again.  This can take the form of a `request_id=??` for incoming user requests or `channel_id=xyz` for anything channel related. 

### Searchable logs

With the tracing above, each log will have a `request_id=abcd` in it and each log will use this same structure. So log searches will now become way easier. 

The other thing is that the way we generally write logs today is using formatted strings like: 

❌  **Out with the old**
```
log.Infof("Finalizing pending_id(%x) over ChannelPoint(%v), "+
		"waiting for channel open on-chain", pendingChanID[:],
		fundingPoint)
```
Which appears in the logs as:
```
[INF] FNDG: Finalizing pending_id(xyz) over ChannelPoint(abc), waiting for channel open on-chain"
```

This is not ideal for a few reasons:
1) This log line is called from the funding manager but if a user initiated 2 fundings at the same time, then how do you know which one this log is referring to? The log author would need to remember to add some request identifier and then would need to remember to add that to each and every log within the funding manager so that it always shows up.
2) When actually writing the log, you always need to go line up which param goes to which directive which makes it hard & bug-prone.  
3) If we want to go search through our logs (via grepping the log file or w/e) for how many times this exact log line occurred, it is actually really difficult because each directive (`%d``%v`) makes the log unique... And you cant necessarily just grep on `Finalizing pending_id` because what if there is another log line somewhere that starts the same way?
4) Similarly to 3, if we want to go find where in the code base a log is being emitted from, this can be tricky if there are many directives to work around. 

Enter structured logging:

✅  **In with the new**

The above log line could now be converted into something like this:
```
log.InfoS(ctx, "Finalizing channel ID. Waiting for channel open on-chain",
		btclog.Hex("pending_id", pendingChanID[:]),
		"channel_point", fundingPoint.String())
```
Which will result in the following log line:
```
[INF] FNDG: Finalizing channel ID. Waiting for channel open on-chain request_id=123 pending_id=xyz channel_point=abc
```

A few things to note: 
- it takes a context from which it may extract other key-value pairs (such as `request_id`) at log time.
- The log message is a constant. This makes it easy to search both the logs and the code base for this log line.
- All variables with in the log are now key value pairs. This makes constructing the log line easy to do. 
- You as the dev dont need to remember to go add the `request_id` each time you add a new log line! It will just automagically appear 🪄 

## Details

- This new implementation is flexible enough to allow callers to pass in their own `slog.Handlers` (which underneath could be a json formatter, a logfmt formatter or any anything else like a [charm Handler](https://github.com/charmbracelet/log) 

## Usage

The idea is that the `msg` passed to an `S` method should be a constant. The `attr...` params are then used for key-value pairs. 

```
log.InfoS(ctx, "User performed a request",
			"user_id", id,
			"request_uri: ", uri)
```

Each new method also takes a `context.Context`.  The `WithCtx` helper can be used to attach any key-value pairs to a 
context and then when the logger is called, the pairs will be extracted from the context and added as attributes in the log. 

For example:

```
ctx := WithCtx(context.Background(), "user_id", id)

// This log will include both the `user_id` and `request_uri` attributes.
log.InfoS(ctx, "User performed a request", "request_uri", uri)
```

# Other additions:

### Config options

- This also introduces a new `--logging.console.disable` option to disable logs being written 
to stdout and a new `--logging.file.disable` option to disable writing logs to the standard log file.

- It also has `--logging.console.no-timestamps` & `--logging.file.no-timestamps` to omit timestamps from the logs

- It also adds new `--logging.console.call-site` and `--logging.console.call-site` options which can be used to include log line source call-site in the log lines. The options are "off", "short" (source file name and line number) and "long" (full path to source file and line number)

- finally, there is a new `--logging.console.style` option which can be set to use color formatting - this is only available if the `dev` build flag is set. 

## TODO: 
- update docs with guidelines for using structured logging methods

Fixes #8713
Fixes #6828
Fixes #6163

### CODE REVIEW

File: build/handlers.go [hunk 1]
```diff
@@ -0,0 +1,257 @@
...
+func NewLogFileHandler(w io.Writer, opts ...HandlerOptions) Handler {
+	options := defaultLogFileOptions()
+	for _, o := range opts {
+		o(options)
+	}
+
+	return options.buildHandler(w)
+}
+
+// charmHandler holds a charm.Logger handler and adds some methods that can
```
Comment (guggero) [inline build/handlers.go:134]: nit: incomplete sentence?

File: go.mod [hunk 2]
```diff
@@ -64,13 +67,16 @@ require (
 	gopkg.in/macaroon.v2 v2.0.0
 )
 
+require github.com/charmbracelet/x/ansi v0.1.4 // indirect
```
Comment (guggero) [inline go.mod:70]: Hmm, why is this its own `require` block? Shouldn't this be sorted in with the rest in the upcoming block for the indirect dependencies?

File: go.mod [hunk 3]
```diff
@@ -64,13 +67,16 @@ require (
...
+
 require (
 	github.com/Azure/go-ansiterm v0.0.0-20230124172434-306776ec8161 // indirect
 	github.com/Microsoft/go-winio v0.6.1 // indirect
 	github.com/NebulousLabs/fastrand v0.0.0-20181203155948-6fb6489aac4e // indirect
 	github.com/Nvveen/Gotty v0.0.0-20120604004816-cd527374f1e5 // indirect
 	github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da // indirect
 	github.com/aead/siphash v1.0.1 // indirect
+	github.com/aymanbagabas/go-osc52/v2 v2.0.1 // indirect
```
Comment (guggero) [inline go.mod:79]: Hmm, that's quite a few new dependencies being pulled in just for the coloring... Maybe we should for now leave the `lipgloss` part out and just do everything else? The structured log with attributes and context-based tracing-values plus all the console/file handling already gives us a ton, wouldn't want to see this PR being blocked by safety concerns. What do you think?
Or maybe we can put the coloring stuff behind a not-yet enabled build tag, so at least at build time these dependencies aren't pulled in (yet), until we can take a closer look at them?

File: build/logrotator.go [hunk 4]
```diff
@@ -14,7 +14,8 @@ import (
 // RotatingLogWriter is a wrapper around the LogWriter that supports log file
 // rotation.
 type RotatingLogWriter struct {
-	logWriter *LogWriter
+	// pipe is the write-end pipe for writing to the log rotator
```
Comment (guggero) [inline build/logrotator.go:17]: nit: missing full stop.

File: build/sub_logger.go [hunk 5]
```diff
@@ -30,10 +29,12 @@ type SubLoggerManager struct {
...
 
 // NewSubLoggerManager constructs a new SubLoggerManager.
-func NewSubLoggerManager(w io.Writer) *SubLoggerManager {
+func NewSubLoggerManager(handlers ...Handler) *SubLoggerManager {
 	return &SubLoggerManager{
-		loggers:   SubLoggers{},
-		genLogger: btclog.NewBackend(w),
+		loggers: SubLoggers{},
+		genLogger: newSubLogGenerator(
+			newHandlerSet(btclog.LevelInfo, handlers...),
```
Comment (guggero) [inline build/sub_logger.go:36]: We have the global variable `LogLevel` that's being set with build tags for testing/development. I assume that still works? Or do we need to use that level here to set the correct default/initial level?

File: sample-lnd.conf [hunk 6]
```diff
@@ -963,6 +963,37 @@
 ; Instructs lnd to encrypt the private key using the wallet's seed.
 ; tor.encryptkey=false
 
+[logging]
+
+; Disable logging to stdout and stderror.
+; Default:
+;   logging.console.disable=false
+; Example:
+;   logging.console.disable=true
```
Comment (guggero) [inline sample-lnd.conf:972]: nit: Do we really need an example for boolean values? I think the more compact form with just the default value is probably enough.

File: sample-lnd.conf [hunk 7]
```diff
@@ -963,6 +963,37 @@
...
+
+; Don't add timestamps to logs written to stdout and stderr.
+; Default:
+;   logging.console.no-timestamps=false
+; Example:
+;   logging.console.no-timestamps=true
+
+; Set color theme for to stdout and stderror logger.
```
Comment (guggero) [inline sample-lnd.conf:980]: Should we list all possible values here? Since the `choice` is only rendered on the console when printing the help text.

**Review by guggero — COMMENTED** [review]
Awesome PR, really excited about this new feature!

File: build/prefix_log.go [hunk 8]
```diff
@@ -22,10 +30,16 @@ func (p *PrefixLog) addFormatPrefix(s string) string {
...
 // addArgsPrefix prepends the prefix to a list of arguments.
-func (p *PrefixLog) addArgsPrefix(args []interface{}) []interface{} {
+func (p *PrefixLog) addArgsPrefix(args []any) []any {
 	return append([]interface{}{p.prefix}, args...)
 }
 
+// mergeAttr merges the given set of attributes with any attributes that the
+// logger was initialised with.
+func (p *PrefixLog) mergeAttr(attrs []any) []any {
+	return append(attrs, p.attr...)
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply build/prefix_log.go]: updated!

File: build/handlers.go [hunk 9]
```diff
@@ -0,0 +1,257 @@
...
+	}
+}
+
+// WithColor is a functional option that can be used to change the default log
+// output colour profile.
+func WithColor(color Color) HandlerOptions {
+	return func(opts *handlerOptions) {
+		opts.color = color
+	}
+}
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply build/handlers.go]: (removed this commit now)

File: build/handlers.go (hunk 1 above)
Comment (ellemouton) [reply build/handlers.go]: (removed commit)

File: go.mod (hunk 2 above)
Comment (ellemouton) [reply go.mod]: (removed commit)

File: go.mod (hunk 3 above)
Comment (ellemouton) [reply go.mod]: (removed commit)

File: build/sub_logger.go (hunk 5 above)
Comment (ellemouton) [reply build/sub_logger.go:36]: that will still work. The previous "NewBackend" also used to set Info level as default. So SetLevel is used later to set these :)

File: sample-lnd.conf (hunk 7 above)
Comment (ellemouton) [reply sample-lnd.conf:980]: converted this to a bool now

File: sample-lnd.conf (hunk 6 above)
Comment (ellemouton) [reply sample-lnd.conf:972]: ah - missed this comment. Will address tomorrow

Comment (ellemouton) [reply sample-lnd.conf]: fixed

**Comment by ellemouton** [comment]
Note to reviewers: this is ready along with the parent PR in btclog. Went with the v2 module strategy. cc @guggero & @ziggie1984

File: build/config.go [hunk 10]
```diff
@@ -16,10 +16,19 @@ type LoggerConfig struct {
 	NoTimestamps bool `long:"no-timestamps" description:"Omit timestamps from log lines."`
 }
 
+// consoleLoggerCfg extends the LoggerConfig struct by adding a Color option
+// which is only available for a console logger.
+//
+//nolint:lll
+type consoleLoggerCfg struct {
+	LoggerConfig
+	Style bool `long:"style" description:"If set, the output will be styled with color and fonts"`
```
Comment (ellemouton) [inline build/config.go:25]: seeing if i can put the style stuff behind the dev build flag only...

Comment (ellemouton) [reply build/config.go]: done

**Comment by ellemouton** [comment]
added a bonus commit which adds call-site to the log lines (if user wants) :) 

Screenshot 2024-10-15 at 18 29 14

File: build/prefix_log.go [hunk 11]
```diff
@@ -98,13 +111,55 @@ func (p *PrefixLog) Critical(v ...interface{}) {
 	p.log.Critical(p.addArgsPrefix(v)...)
 }
 
+// TraceS writes a structured log with the given message and key-value pair
+// attributes with LevelTrace to the log.
+func (p *PrefixLog) TraceS(ctx context.Context, msg string, attrs ...any) {
```
Comment (yyforyongyu) [inline build/prefix_log.go:116]: Can we create the context inside this method so the caller doesn't need to create it? Think this way we won't need more code lines when creating logs

Comment (ellemouton) [reply build/prefix_log.go:116]: Passing in a context is part of what's cool about this feature cause we can add kv pair attributes to a context and that will get logged without us needing to remember to include it in the log every time

File: build/config_dev.go [hunk 12]
```diff
@@ -0,0 +1,137 @@
...
+// HandlerOptions returns the set of btclog.HandlerOptions that the state of the
+// config struct translates to.
+func (cfg *consoleLoggerCfg) HandlerOptions() []btclog.HandlerOption {
+	opts := cfg.LoggerConfig.HandlerOptions()
+
+	if !cfg.Style {
+		return opts
+	}
+
+	return append(opts,
```
Comment (guggero) [inline build/config_dev.go:96]: nit: move `opts` to next line?

File: build/log_shutdown.go [hunk 13]
```diff
@@ -41,3 +43,15 @@ func (s *ShutdownLogger) Critical(v ...interface{}) {
 	s.Logger.Info("Sending request for shutdown")
 	s.shutdown()
 }
+
+// CriticalS writes a structured log with the given message and key-value pair
+// attributes with LevelCritical to the log.
```
Comment (guggero) [inline build/log_shutdown.go:48]: nit: add "It will then call the shutdown logger's shutdown function to prompt safe shutdown."

File: build/config.go [hunk 14]
```diff
@@ -16,26 +22,40 @@ type LogConfig struct {
...
 
 // LoggerConfig holds options for a particular logger.
 //
 //nolint:lll
 type LoggerConfig struct {
-	Disable      bool `long:"disable" description:"Disable this logger."`
-	NoTimestamps bool `long:"no-timestamps" description:"Omit timestamps from log lines."`
+	Disable      bool   `long:"disable" description:"Disable this logger."`
+	NoTimestamps bool   `long:"no-timestamps" description:"Omit timestamps from log lines."`
+	CallSite     string `long:"call-site" description:"Include the call-site of each log line." choice:"off" choice:"short" choice:"long"`
```
Comment (guggero) [inline build/config.go:40]: This is sooo useful! :100:

**Review by guggero — APPROVED** [review]
tACK, LGTM :tada: 

This is sooo nice :star_struck:

File: build/logrotator.go [hunk 15]
```diff
@@ -80,11 +81,20 @@ func (r *RotatingLogWriter) InitLogRotator(logFile, logCompressor string,
 		}
 	}()
 
-	r.logWriter.RotatorPipe = pw
+	r.pipe = pw
 
 	return nil
 }
 
+// Write writes the byte slice to both stdout and the log rotator, if present.
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply build/logrotator.go:89]: indeed :)

File: build/config_dev.go [hunk 16]
```diff
@@ -0,0 +1,158 @@
...
+	Console *consoleLoggerCfg `group:"console" namespace:"console" description:"The logger writing to stdout and stderr."`
+	File    *LoggerConfig     `group:"file" namespace:"file" description:"The logger writing to LND's standard log file."`
+}
+
+// DefaultLogConfig returns the default logging config options.
+func DefaultLogConfig() *LogConfig {
+	return &LogConfig{
+		Console: &consoleLoggerCfg{
+			LoggerConfig: LoggerConfig{
+				CallSite: callSiteOff,
```
Comment (yyforyongyu) [inline build/config_dev.go:39]: can we set the default to `callSiteShort` for `dev` cfg? think this will make debugging itest much easier!

Comment (ellemouton) [reply build/config_dev.go:39]: yeah def! good idea

Comment (ellemouton) [reply build/config_dev.go]: done :)

File: sample-lnd.conf [hunk 17]
```diff
@@ -963,6 +963,19 @@
...
+; logging.console.disable=false
+
+; Don't add timestamps to logs written to stdout and stderr.
+; logging.console.no-timestamps=false
+
+; Disable logging to the standard LND log file.
+; logging.file.disable=false
+
+; Don't add timestamps to logs written to the standard LND log file.
+; logging.file.no-timestamps=false
```
Comment (ziggie1984) [inline sample-lnd.conf:985]: Missing `call-site`

File: build/config_dev.go [hunk 18]
```diff
@@ -0,0 +1,137 @@
...
+import (
+	"fmt"
+	"strings"
+
+	btclogv1 "github.com/btcsuite/btclog"
+	"github.com/btcsuite/btclog/v2"
+)
+
+const (
+	resetSeq = "0"
```
Comment (ziggie1984) [inline build/config_dev.go:15]: Could you explain why we are only adding style option to the dev env, because of some attack vectors mentioned in the btclog PR ?

File: build/config_dev.go [hunk 19]
```diff
@@ -0,0 +1,137 @@
...
+	Console *consoleLoggerCfg `group:"console" namespace:"console" description:"The logger writing to stdout and stderr."`
+	File    *LoggerConfig     `group:"file" namespace:"file" description:"The logger writing to LND's standard log file."`
+}
+
+// LoggerConfig holds options for a particular logger.
+//
+//nolint:lll
+type LoggerConfig struct {
+	Disable      bool `long:"disable" description:"Disable this logger."`
+	NoTimestamps bool `long:"no-timestamps" description:"Omit timestamps from log lines."`
```
Comment (ziggie1984) [inline build/config_dev.go]: why no callsite here ?

**Review by ziggie1984 — COMMENTED** [review]
Great PR 👏, a bit complex to grasp because of all the interface but makes it really flexible as well. Can't wait until we actually use the new power of SLogs.

File: build/handler_sets.go [hunk 20]
```diff
@@ -0,0 +1,173 @@
...
+	for _, handler := range h.set {
+		handler.SetLevel(level)
+	}
+	h.level = level
+}
+
+// Level returns the current logging level of the Handler.
+//
+// NOTE: this is part of the btclog.Handler interface.
+func (h *handlerSet) Level() btclogv1.Level {
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply build/handler_sets.go:107]: there is no v2 level type

File: log.go [hunk 21]
```diff
@@ -206,13 +209,39 @@ func AddSubLogger(root *build.RotatingLogWriter, subsystem string,
...
+	SetV1SubLogger(root, subsystem, logger, useLoggers...)
+}
+
+// SetV1SubLogger is a helper method to conveniently register the logger of a
+// sub system.
+func SetV1SubLogger(root *build.SubLoggerManager, subsystem string,
+	logger btclog.Logger, useLoggers ...func(btclogv1.Logger)) {
+
+	root.RegisterSubLogger(subsystem, logger)
+	for _, useLogger := range useLoggers {
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply log.go:246]: added a comment

File: build/config_dev.go (hunk 18 above)
Comment (ellemouton) [reply build/config_dev.go:15]: we can always change this later I think. Just feels good to be safe for now in this initial PR

File: build/handlers.go [hunk 22]
```diff
@@ -0,0 +1,23 @@
+package build
+
+import (
+	"os"
+
+	"github.com/btcsuite/btclog/v2"
+)
+
+// NewDefaultLoggers returns the standard console logger and rotating log
```
[the remark this answers is not in the document]
Comment (ziggie1984) [reply build/handlers.go]: Upps, you are right sorry

File: build/config.go [hunk 23]
```diff
@@ -0,0 +1,61 @@
...
+}
+
+// HandlerOptions returns the set of btclog.HandlerOptions that the state of the
+// config struct translates to.
+func (cfg *LoggerConfig) HandlerOptions() []btclog.HandlerOption {
+	opts := []btclog.HandlerOption{
+		btclog.WithCallSiteSkipDepth(7),
```
Comment (ziggie1984) [inline build/config.go:47]: could you add a comment where this magic number comes from.

File: build/config_dev.go [hunk 24]
```diff
@@ -0,0 +1,158 @@
...
+	Disable      bool   `long:"disable" description:"Disable this logger."`
+	NoTimestamps bool   `long:"no-timestamps" description:"Omit timestamps from log lines."`
+	CallSite     string `long:"call-site" description:"Include the call-site of each log line." choice:"off" choice:"short" choice:"long"`
+}
+
+// HandlerOptions returns the set of btclog.HandlerOptions that the state of the
+// config struct translates to.
+func (cfg *LoggerConfig) HandlerOptions() []btclog.HandlerOption {
+	opts := []btclog.HandlerOption{
+		btclog.WithCallSiteSkipDepth(7),
```
Comment (ziggie1984) [inline build/config_dev.go:61]: same here.

**Review by ziggie1984 — APPROVED** [review]
Thanks for the quick reply, LGTM

File: build/config.go (hunk 23 above)
Comment (ellemouton) [reply build/config.go:51]: good idea! done :)

File: build/config_dev.go (hunk 24 above)
Comment (ellemouton) [reply build/config_dev.go:65]: done :)
