### PR TITLE
multi: Inbound fees are retained when not provided

### LINKED ISSUE #8614: [bug]: InboundFees are overwritten if they were not explicitly specified in lncli
### Background

I run the current master on testnet and tested the setting of inbound fees with `lncli updatechanpolicy`. But the inbound fees are not preserved if I run the command without the command line flags

### Your environment

* testnet
* version of `lnd`
fn/v1.0.5-129-gb1175514f

### Steps to reproduce

1. set inbound fees with
`lncli updatechanpolicy --base_fee_msat 0 --fee_rate_ppm 200 --time_lock_delta 144 --inbound_fee_rate_ppm -100 --inbound_base_fee_msat -1 --chan_point 9952586a20fecd4d99c3f400c44f10e17c674f1050f773656a42acbf7b80901c:0`

2. check the inbound fees
```
lncli getchaninfo 2579374014416486400
{
    "channel_id":  "2579374014416486400",
    "chan_point":  "9952586a20fecd4d99c3f400c44f10e17c674f1050f773656a42acbf7b80901c:0",
    "last_update":  1712092954,
    "node1_pub":  "024e97ccd1382cb736f86694e0d1312cb53fdcbffb93f13f2626702c3d74cabf99",
    "node2_pub":  "038214ce28b285a6233300fc114184c1e1da7bab146d705679339c304e118330a1",
    "capacity":  "20000",
    "node1_policy":  {
        "time_lock_delta":  144,
        "min_htlc":  "2100000",
        "fee_base_msat":  "0",
        "fee_rate_milli_msat":  "200",
        "disabled":  false,
        "max_htlc_msat":  "19800000",
        "last_update":  1712092954,
        "custom_records":  {
            "55555":  "ffffffffffffff9c"
        },
        "inbound_fee_base_msat":  -1,
        "inbound_fee_rate_milli_msat":  -100
    },
    "node2_policy":  {
        "time_lock_delta":  144,
        "min_htlc":  "2100000",
        "fee_base_msat":  "0",
        "fee_rate_milli_msat":  "250",
        "disabled":  false,
        "max_htlc_msat":  "7858400",
        "last_update":  1712092021,
        "custom_records":  {},
        "inbound_fee_base_msat":  0,
        "inbound_fee_rate_milli_msat":  0
    },
    "custom_records":  {}
}
```

3. Set the policy again without inbound fees
`lncli updatechanpolicy --base_fee_msat 0 --fee_rate_ppm 300 --time_lock_delta 144 --chan_point 9952586a20fecd4d99c3f400c44f10e17c674f1050f773656a42acbf7b80901c:0`

4. Check the inbound fees again
```
lncli getchaninfo 2579374014416486400
{
    "channel_id":  "2579374014416486400",
    "chan_point":  "9952586a20fecd4d99c3f400c44f10e17c674f1050f773656a42acbf7b80901c:0",
    "last_update":  1712093293,
    "node1_pub":  "024e97ccd1382cb736f86694e0d1312cb53fdcbffb93f13f2626702c3d74cabf99",
    "node2_pub":  "038214ce28b285a6233300fc114184c1e1da7bab146d705679339c304e118330a1",
    "capacity":  "20000",
    "node1_policy":  {
        "time_lock_delta":  144,
        "min_htlc":  "2100000",
        "fee_base_msat":  "0",
        "fee_rate_milli_msat":  "300",
        "disabled":  false,
        "max_htlc_msat":  "19800000",
        "last_update":  1712093293,
        "custom_records":  {
            "55555":  "0000000000000000"
        },
        "inbound_fee_base_msat":  0,
        "inbound_fee_rate_milli_msat":  0
    },
    "node2_policy":  {
        "time_lock_delta":  144,
        "min_htlc":  "2100000",
        "fee_base_msat":  "0",
        "fee_rate_milli_msat":  "250",
        "disabled":  false,
        "max_htlc_msat":  "7858400",
        "last_update":  1712092021,
        "custom_records":  {},
        "inbound_fee_base_msat":  0,
        "inbound_fee_rate_milli_msat":  0
    },
    "custom_records":  {}
}

```

### Expected behaviour

Inbound Fees have to be preserved.

### PR DESCRIPTION
**Pull request by feelancer21**
Fixes the problem that inbound base fee and fee rate are overwritten with 0 if they are not specified in PolicyUpdateRequest. This ensures backward compatibility with older rpc clients that do not yet support the inbound feature.

## Change Description
Fixes #8614

I had initially considered working with a boolean. However, as the base fee and fee rate are two values that are updated and not just one, I found it more elegant to outsource them to an extra message, which can also be nil. Both implementation variants mean that rpc clients that already implement the inbound fees in the current variant have to update their protos again.

The idea with the fn package comes from @ziggie1984  . Thanks for that .

## Steps to Test
Tested with `lncli` as described in #8614.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

File: cmd/lncli/commands.go [hunk 1]
```diff
@@ -2387,12 +2387,26 @@ func updateChannelPolicy(ctx *cli.Context) error {
 		return errors.New("inbound_fee_rate_ppm out of range")
 	}
 
+	// Inbound fees are optional. However, if an update is required,
+	// both the base fee and the fee rate must be provided.
+	var inboundFee *lnrpc.InboundFee
+	switch {
```
Comment (yyforyongyu) [inline cmd/lncli/commands.go:2393]: I'd remove the switch case and do the following instead, easier to understand,
```go
	if ctx.IsSet("inbound_base_fee_msat") !=
		ctx.IsSet("inbound_fee_rate_ppm") {

		return errors.New("both parameters must be provided: " +
			"inbound_base_fee_msat and inbound_fee_rate_ppm")
	}

	inboundFee := &lnrpc.InboundFee{
		BaseFeeMsat: int32(inboundBaseFeeMsat),
		FeeRatePpm:  int32(inboundFeeRatePpm),
	}
```

File: lnrpc/lightning.proto [hunk 2]
```diff
@@ -4402,8 +4412,9 @@ message PolicyUpdateRequest {
     // If true, min_htlc_msat is applied.
     bool min_htlc_msat_specified = 8;
 
-    int32 inbound_base_fee_msat = 10;
-    int32 inbound_fee_rate_ppm = 11;
+    // Optional inbound fee. If unset, the previously set value will be
+    // retained [EXPERIMENTAL].
```
Comment (yyforyongyu) [inline lnrpc/lightning.proto:4416]: A bit confused about this flag `EXPERIMENTAL`, when will this stop being experimental?

File: routing/localchans/manager.go [hunk 3]
```diff
@@ -182,9 +192,14 @@ func (r *Manager) updateEdge(tx kvdb.RTx, chanPoint wire.OutPoint,
 		newSchema.FeeRate,
 	)
 
-	inboundFee := newSchema.InboundFee.ToWire()
-	if err := edge.ExtraOpaqueData.PackRecords(&inboundFee); err != nil {
-		return err
+	if !newSchema.InboundFee.IsNone() {
```
Comment (yyforyongyu) [inline routing/localchans/manager.go:195]: Should use `WhenSome` instead

File: routing/localchans/manager.go [hunk 4]
```diff
@@ -112,7 +122,7 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
 			TimeLockDelta: uint32(edge.TimeLockDelta),
 			MinHTLCOut:    edge.MinHTLC,
 			MaxHTLC:       edge.MaxHTLC,
-			InboundFee:    newSchema.InboundFee,
+			InboundFee:    models.NewInboundFeeFromWire(inboundFee),
```
Comment (yyforyongyu) [inline routing/localchans/manager.go:125]: Think we can just do `newSchema.InboundFee.UnwrapOr(models.InboundFee{})` here to avoid the `ExtractRecords` above?

File: routing/localchans/manager.go [hunk 5]
```diff
@@ -182,9 +192,14 @@ func (r *Manager) updateEdge(tx kvdb.RTx, chanPoint wire.OutPoint,
 		newSchema.FeeRate,
 	)
 
-	inboundFee := newSchema.InboundFee.ToWire()
-	if err := edge.ExtraOpaqueData.PackRecords(&inboundFee); err != nil {
```
Comment (yyforyongyu) [inline routing/localchans/manager.go:186]: Do we know what else has been saved in this `ExtraOpaqueData` field? I think `PackRecords` will overwrite it - if we have other fields they will be lost.

Comment (yyforyongyu) [reply routing/localchans/manager.go:186]: There probably should be an `UpdateRecords` method on `ExtraOpaqueData`, it first reads the existing records, then updates the specified records.

File: rpcserver.go [hunk 6]
```diff
@@ -7195,34 +7196,40 @@ func (r *rpcServer) UpdateChannelPolicy(ctx context.Context,
...
+		if req.InboundFee.FeeRatePpm > 0 {
 			return nil, fmt.Errorf("positive values for inbound "+
 				"fee rate ppm are not supported: %v",
-				req.InboundFeeRatePpm)
+				req.InboundFee.FeeRatePpm)
 		}
 	}
 
+	// In case inbound fees are not specified no inbound fees will be
+	// applied but the previous value will be retained.
```
Comment (yyforyongyu) [inline rpcserver.go:7213]: How is the previous value being retained?

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
Thanks for the PR! Left a few comments, and could you test the new behavior in `itest/lnd_channel_policy_test.go`?

File: cmd/lncli/commands.go (hunk 1 above)
Comment (feelancer21) [reply cmd/lncli/commands.go:2393]: Thank you very much for your comments. I'll take a detailed look tomorrow. 
At this point I don't quite understand what you mean. We need to catch the case where both lncli are not set and then pass nil to the rpc. Or am I missing something?

File: lnrpc/lightning.proto (hunk 2 above)
Comment (feelancer21) [reply lnrpc/lightning.proto:4416]: I added this because the whole inbound fee implentation is mentioned as experimental in the release notes. For other new features I have also seen the flag in the proto files.
But I can remove it  if it is rather confusing.

Comment (Roasbeef) [reply lnrpc/lightning.proto:4416]: I think fine to retain the flag. Indicates that the API may change in the near future.

File: cmd/lncli/commands.go [hunk 7]
```diff
@@ -2387,12 +2387,26 @@ func updateChannelPolicy(ctx *cli.Context) error {
...
+	case ctx.IsSet("inbound_base_fee_msat") !=
+		ctx.IsSet("inbound_fee_rate_ppm"):
+		return errors.New("both parameters must be provided: " +
+			"inbound_base_fee_msat and inbound_fee_rate_ppm")
+
+	case ctx.IsSet("inbound_fee_rate_ppm"):
+		inboundFee = &lnrpc.InboundFee{
+			BaseFeeMsat: int32(inboundBaseFeeMsat),
+			FeeRatePpm:  int32(inboundFeeRatePpm)}
```
Comment (Roasbeef) [inline cmd/lncli/commands.go:2402]: Close bracket should be on a new line.

File: itest/lnd_multi-hop-payments_test.go [hunk 8]
```diff
@@ -257,9 +257,10 @@ func updateChannelPolicy(ht *lntest.HarnessTest, hn *node.HarnessNode,
 		Scope: &lnrpc.PolicyUpdateRequest_ChanPoint{
 			ChanPoint: chanPoint,
 		},
-		MaxHtlcMsat:        maxHtlc,
-		InboundBaseFeeMsat: inboundBaseFee,
-		InboundFeeRatePpm:  inboundFeeRate,
+		MaxHtlcMsat: maxHtlc,
+		InboundFee: &lnrpc.InboundFee{
+			BaseFeeMsat: inboundBaseFee,
+			FeeRatePpm:  inboundFeeRate},
```
Comment (Roasbeef) [inline itest/lnd_multi-hop-payments_test.go:263]: Close bracket should be on a new line.

File: lnrpc/lightning.proto [hunk 9]
```diff
@@ -4402,8 +4412,9 @@ message PolicyUpdateRequest {
...
+    InboundFee inbound_fee = 10;
```
Comment (Roasbeef) [inline lnrpc/lightning.proto:4417]: Good move to make it into a sub-proto, this way we can check for `nil`-ness 👍

File: cmd/lncli/commands.go (hunk 7 above)
Comment (Roasbeef) [reply cmd/lncli/commands.go:2402]: I see how using the sub-proto here helps us check for nil-ness. But don't we need to use the approach for the individual fields? Otherwise if the the base fee value is set, but the ppm value isn't, then the msat value will get reset to zero.

File: routing/localchans/manager.go [hunk 10]
```diff
@@ -99,6 +99,16 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
 			return nil
 		}
 
+		// Extract the inbound fees from the edge we just updated.
+		// We only handle chan policies of ourselves which works with
+		// or without specified inbound fees. So having a decoding error
+		// reveils another problem.
+		var inboundFee lnwire.Fee
+		_, err = edge.ExtraOpaqueData.ExtractRecords(&inboundFee)
```
Comment (Roasbeef) [inline routing/localchans/manager.go:107]: Why's parsing it again require here, whereas it wasn't before this diff?

File: routing/router.go [hunk 11]
```diff
@@ -310,7 +311,7 @@ type ChannelPolicy struct {
 
 	// MinHTLC is the minimum HTLC size including fees we are allowed to
 	// forward over this channel.
-	MinHTLC *lnwire.MilliSatoshi
+	MinHTLC fn.Option[lnwire.MilliSatoshi]
```
Comment (Roasbeef) [inline routing/router.go:314]: Seems like a distinct change.

File: routing/localchans/manager.go (hunk 5 above)
Comment (Roasbeef) [reply routing/localchans/manager.go:186]: I think we should just lift the field directly into the struct, rather than making a callers aways encode it and decode it. Not sure the rational of implementing it like this in the first place... 

If we just set the field, then we also ensure that nothing else gets clobbered.

File: routing/localchans/manager.go (hunk 3 above)
Comment (Roasbeef) [reply routing/localchans/manager.go:195]: Yeah we want to remove `UnsafeFromSome`. 

You can also write it like this (to catch that error):
```
errr := fn.MapOptionZ(newSchema.InboundFee, func(f models.InboundFee) error {
      return edge.ExtraOpaqueData.PackRecords(&inboundWireFee)
})
```

But see my other comment, I think we should just have the new fields be a direct part of the struct instead of encoding into the extra data. Though I can understand if you leave to wish it like this, as your main goal was resolving the bug re default values.

File: rpcserver.go (hunk 6 above)
Comment (Roasbeef) [reply rpcserver.go:7213]: `updateEdge` has been modified to check the option value, only setting the value if `Some`.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: cmd/lncli/commands.go (hunk 7 above)
Comment (bitromortac) [reply cmd/lncli/commands.go:2402]: In the future we could deprecate the other fields and use this method for them as well, as it seems to lead to a non-intuitive way to update values where one has to echo the non-updated values.

File: cmd/lncli/commands.go (hunk 1 above)
Comment (yyforyongyu) [reply cmd/lncli/commands.go:2393]: nvm, it seems this PR requires the user to set both `inbound_fee_rate_ppm` and `inbound_base_fee_msat` at the same time, but I think we want to allow updating a single field, so either `inbound_base_fee_msat` or  `inbound_fee_rate_ppm`?

File: cmd/lncli/commands.go (hunk 7 above)
Comment (yyforyongyu) [reply cmd/lncli/commands.go:2402]: We could make `BaseFeeMsat` and `FeeRatePpm` using the `optional` flag in proto3 and check their nil-ness - we need to update `falafel` first tho, as last time I tried to use it, `make rpc` would fail with,
```
walletkit.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-custom hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--custom_out:
```

Comment (feelancer21) [reply cmd/lncli/commands.go:2402]: My primary goal was to ensure backwards compatibility with older RPC clients, so that a PolicyUpdate from clients that do not recognize inbound fees does not overwrite the InboundFees with 0. Many noderunners use several clients. However, clients that use InboundFees must set both fields.  

But I would also prefer an optional flag. Then you could also do without the submessage, which is more of a workaround. 

Who can customize Falafel, if optionality is desired?

File: routing/localchans/manager.go (hunk 5 above)
Comment (feelancer21) [reply routing/localchans/manager.go:186]: I can add the fields to the edge.

**Comment by saubyk** [comment]
Hi @feelancer21 we'd like to get this pr merged into the next rc asap.
Please let us know, if you can turn this around quickly. If not, we can take this over. Thanks

**Comment by feelancer21** [comment]
Hello guys,

have made an update. Here are a few comments:

1. My primary goal was to ensure backwards compatibility with older RPC clients, so that a PolicyUpdate from clients that do not recognize inbound fees does not overwrite the InboundFees with 0. Many noderunners use several clients. However, clients that use InboundFees must set both fields. Optionality at field level should be addressed separately in the future. Maybe we need an extra rpc call then.

2 I have now included the inbound fees in the edge. However, I did not split up the individual fields because they would have been merged again in UpdatePolicy anyway. But I can still change this if desired.

3. extract and pack the `ExtraOpaqueData` I have not outsourced to a separate method. Since policies have no other ExtraOpaqueData, this should not lead to problems.

4. I had to integrate itests for the inbound fees into the `lnd_channel_policy_test.go`. As part of this, I had to fix another issue with the assert of the policies. The nil case is also tested.

Regards

File: lntest/node/watcher.go [hunk 12]
```diff
@@ -681,6 +681,18 @@ func CheckChannelPolicy(policy, expectedPolicy *lnrpc.RoutingPolicy) error {
...
 	}
+	if policy.InboundFeeBaseMsat != expectedPolicy.InboundFeeBaseMsat {
+		return fmt.Errorf("expected max htlc %v, got %v",
+			expectedPolicy.InboundFeeBaseMsat,
+			policy.InboundFeeBaseMsat)
+	}
+	if policy.InboundFeeRateMilliMsat !=
+		expectedPolicy.InboundFeeRateMilliMsat {
+
+		return fmt.Errorf("expected max htlc %v, got %v",
```
Comment (bitromortac) [inline lntest/node/watcher.go:692]: nit: error message should refer to inbound fees

File: channeldb/models/channel_edge_policy.go [hunk 13]
```diff
@@ -60,6 +60,9 @@ type ChannelEdgePolicy struct {
 	// HTLCs for each millionth of a satoshi forwarded.
 	FeeProportionalMillionths lnwire.MilliSatoshi
 
+	// InboundFee that will be charged for incoming HTLCs.
+	InboundFee
```
[the remark this answers is not in the document]
Comment (feelancer21) [reply channeldb/models/channel_edge_policy.go:64]: I had that thought too. An alternative I had in mind was to define an InboundFee in UpdatePolicy and pass a pointer to it to UpdateEdge. This would be quickly adjusted. I would just need to know in which direction we want to go.

File: routing/localchans/manager.go [hunk 14]
```diff
@@ -182,9 +183,28 @@ func (r *Manager) updateEdge(tx kvdb.RTx, chanPoint wire.OutPoint,
...
+				edge.InboundFee = f
+				inboundWireFee := f.ToWire()
+				return edge.ExtraOpaqueData.PackRecords(
+					&inboundWireFee,
+				)
+			})
+		if err != nil {
+			return err
+		}
+	} else {
```
[the remark this answers is not in the document]
Comment (feelancer21) [reply routing/localchans/manager.go:201]: `newSchema` only contains an `InboundFee` if it is to be updated. Otherwise we have to use and determine the existing InboundFee. Therefore, there must be a case somewhere.

File: channeldb/models/channel_edge_policy.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (feelancer21) [reply channeldb/models/channel_edge_policy.go:64]: Have created an alternative. Preview can be found here: https://github.com/feelancer21/lnd/compare/e080792451184cf0810831230cf8ef8609a4cc51..9b17806

[the remark this answers is not in the document]
Comment (bitromortac) [reply channeldb/models/channel_edge_policy.go:64]: I'd probably have it this way (I think you had a similar version before): https://github.com/lightningnetwork/lnd/commit/b8b2a05605af4dc9587392a56e9dd9e1182347b4, but not sure about the other reviewer's opinions. We could deal with adding the inbound fees field in a later PR. I think technically `htlc_maximum_msat` was also part of the extra data, because it was optional, but got then promoted to `models.UpdateEdgePolicy` and `lnwire.ChannelUpdate`. We could do a similar transition by removing inbound fees from the extra data to promote it to `models.UpdateEdgePolicy`. We could then leave any non-interpreted extra data untouched, which is useful to display in `describegraph`.

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
I think this is very close! As mentioned by @bitromortac, there's this mapping from a `ChannelUpdate` to a `ChannelEdgePolicy`, in which we also map `ChannelUpdate.ExtraOpaqueData` to `ChannelEdgePolicy.ExtraOpaqueData`. Ideally we'll want to deserialize the bytes in `ChannelUpdate.ExtraOpaqueData`, and extract the inbound fee info into a new field `ChannelEdgePolicy.InboundFee` since we cannot be sure in the future whether there would be more data being saved in `ChannelUpdate.ExtraOpaqueData` and transferred over the wire. This means we need to also change the existing mapping, which means more work.

The second approach is to stick to the `ChannelEdgePolicy.ExtraOpaqueData` as suggested by @bitromortac - we certainly don't wanna two places to hold the same data as it'd soon become a question about who holds the truth.

I'd prefer the second approach as it's almost already done here and we want the release soon.

**Comment by saubyk** [comment]
Hi @feelancer21 would you be able to address the feedback comments today?

**Comment by feelancer21** [comment]
> Hi @feelancer21 would you be able to address the feedback comments today?

that's the plan

File: channeldb/models/channel_edge_policy.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (feelancer21) [reply channeldb/models/channel_edge_policy.go]: Ok. Have integrated the version of @bitromortac.

File: lntest/node/watcher.go (hunk 12 above)
Comment (feelancer21) [reply lntest/node/watcher.go]: should be fixed now

File: itest/lnd_multi-hop-payments_test.go [hunk 15]
```diff
@@ -85,9 +85,19 @@ func testMultiHopPayments(ht *lntest.HarnessTest) {
 		aliceInboundFeeRate     = -50000 // 5%
 	)
 
+	// We update the channel twice. The first time we set the inbound fee,
```
Comment (yyforyongyu) [inline itest/lnd_multi-hop-payments_test.go:88]: I think this behavior is already tested in `req.InboundFee = nil`, plus this is an MPP-related test and should not test policy updates.

**Review by yyforyongyu — APPROVED** [review]
Thanks for the fix 🙏

File: channeldb/models/channel_edge_policy.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (bitromortac) [reply channeldb/models/channel_edge_policy.go]: One problem I wanted to note here (not an issue with this PR) with extracting the inbound fees (or other data later) from the extra data may be that the order of TLVs could change if we re-serialize to `lnwire.ChannelUpdate`, maybe leading to signature invalidation, when we try to relay the message.
