### PR TITLE
multi: set zero bandwidth hint for channels that do not have any available slots

### LINKED ISSUE #4656: Endless loop when max htlcs is reached
### Background

Payment gets into an endless loop when all channel slots are full.

### Your environment

* lnd 0.11.1-beta.rc4

### Steps to reproduce

* Set up nodes Alice and Bob
* Start Bob with `--default-remote-max-htlcs=5 --accept-keysend --keysend-hold-time=1h`
* Open a channel between Alice and Bob
* Send 5 keysend payments from Alice to Bob. They are held as expected.
* Send one more keysend payment.

### Expected behaviour

Payment should fail.

### Actual behaviour

`lnd` goes into an endless retry loop, where the following log fragment is repeated:

```
2020-09-28 12:03:02.579 [DBG] CRTR: PaymentSession(c2ffe2db144499b6c6281aef61544f18fea5b47e5179203e5001291f036198de): pathfinding for amt=1000 mSAT
2020-09-28 12:03:02.580 [DBG] CRTR: Found route: probability=0.95, hops=1, fee=0 mSAT
2020-09-28 12:03:02.580 [DBG] CRTR: Pathfinding perf metrics: nodes=1, edges=1, time=478.514µs
2020-09-28 12:03:02.608 [WRN] HSWC: ChannelLink(35775:1:0): Unable to handle downstream add HTLC: commitment transaction exceed max htlc number
2020-09-28 12:03:02.608 [ERR] CRTR: Failed sending attempt 30 for payment c2ffe2db144499b6c6281aef61544f18fea5b47e5179203e5001291f036198de to switch: could not add downstream htlc
2020-09-28 12:03:02.608 [WRN] CRTR: Attempt 30 for payment c2ffe2db144499b6c6281aef61544f18fea5b47e5179203e5001291f036198de failed: could not add downstream htlc
2020-09-28 12:03:02.625 [WRN] CRTR: Failed to launch shard 30 for payment c2ffe2db144499b6c6281aef61544f18fea5b47e5179203e5001291f036198de: could not add downstream htlc
2020-09-28 12:03:02.625 [ERR] CRTR: Channel update of ourselves received
2020-09-28 12:03:02.627 [WRN] CRTR: Routing failure for local channel 39335028483751936 occurred
2020-09-28 12:03:02.630 [DBG] CRTR: Payment c2ffe2db144499b6c6281aef61544f18fea5b47e5179203e5001291f036198de in state terminate=false, active_shards=0, rem_value=1000 mSAT, fee_limit=1000 mSAT
```

### LINKED ISSUE #5297: lnd becoming unusable after htlcs in a channel > default-remote-max-htlcs
### Background

Since the last 24 hours, lnd is behaving weirdly. 

One thing I have seen is that there is 30 htlc in one channel, despite having `default-remote-max-htlcs=10` option set

Disk storage went from ~1Gb to 6Gb in 2 days. and the node is overly slow. 

The log seems to show a log of error failure related to the channel that has more than 10 htlc.

```
2021-05-14 17:21:22.831 CEST
2021-05-14 15:21:22.829 [WRN] CRTR: Attempt 774716 for payment 6770f241f9288c4bf28698cd************************* failed: could not add downstream htlc
Info
2021-05-14 17:21:22.831 CEST
2021-05-14 15:21:22.829 [ERR] CRTR: Failed sending attempt 774716 for payment 6770f241f9288c4bf28698cd7********************* to switch: could not add downstream htlc
Info
2021-05-14 17:21:22.831 CEST
2021-05-14 15:21:22.829 [WRN] HSWC: ChannelLink(652799:1128:1): Unable to handle downstream add HTLC: commitment transaction exceed max htlc number
Info
2021-05-14 17:21:22.831 CEST
2021-05-14 15:21:22.829 [WRN] CRTR: Attempt 774717 for payment 92633c7aeb012d19da653********************* failed: could not add downstream htlc
Info
2021-05-14 17:21:22.831 CEST
2021-05-14 15:21:22.829 [ERR] CRTR: Failed sending attempt 774717 for payment 92633c7aeb012d19da653********************* to switch: could not add downstream htlc
Info
2021-05-14 17:21:22.831 CEST
2021-05-14 15:21:22.829 [WRN] HSWC: ChannelLink(652799:1128:1): Unable to handle downstream add HTLC: commitment transaction exceed max htlc number
Info
2021-05-14 17:21:22.822 CEST
2021-05-14 15:21:22.822 [WRN] CRTR: Routing failure for local channel 7177600************** occurred
Info
2021-05-14 17:21:22.821 CEST
2021-05-14 15:21:22.818 [ERR] CRTR: Channel update of ourselves received
Info
2021-05-14 17:21:22.821 CEST
2021-05-14 15:21:22.818 [WRN] CRTR: Routing failure for local channel 7177600************** occurred
Info
2021-05-14 17:21:22.816 CEST
2021-05-14 15:21:22.813 [ERR] CRTR: Channel update of ourselves received
Info
2021-05-14 17:21:22.803 CEST
2021-05-14 15:21:22.800 [WRN] CRTR: Attempt 774714 for payment 22354d6931ff4d4197a0c828e9282c4d4635a4a3b2533c45bc5802e44f385b7b failed: could not add downstream htlc
Info
```

### Your environment

* version of `lnd`: 0.12.1
* which operating system (`uname -a` on *Nix): Linux lnd-0 4.19.167+ #1 SMP Tue Feb 2 07:59:55 PST 2021 x86_64 Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoin 0.21
* any other relevant environment details

### Steps to reproduce

Do not know how the node ends up in this situation

### Actual behaviour

image

image

image

### PR DESCRIPTION
**Pull request by carlaKC**
This PR updates our bandwidth hints to report a zero balance when we're not allowed to add any more htlcs to the remote party's commitment. This prevents pathfinding from using the channel at all; previously it would endlessly try to send shard on the channel. 

The first commit just demonstrates the endless cycle of htlcs by logging (couldn't think of a better way), and should be squashed with the second commit to include a test that asserts that we don't use full channels. Open to other testing options besides an itest, but it's difficult to do because this is a combination of multiple elements - pathfinding + payment lifecycle + link - so mocking this didn't feel like it would meaningfully add much (would be testing the mock rather than the code itself).

Fixes #5297
Fixes #4656

### CODE REVIEW

File: lnwallet/channel.go [hunk 1]
```diff
@@ -6496,6 +6496,19 @@ func (lc *LightningChannel) AvailableBalance() lnwire.MilliSatoshi {
...
 
+// RemoteHtlcSlots returns the number of slots remaining on the remote party's
+// commitment. This count only includes htlcs that are active on *both*
+// commitment transactions.
+func (lc *LightningChannel) RemoteHtlcSlots() int {
+	lc.RLock()
+	defer lc.RUnlock()
+
+	slots := lc.channelState.LocalChanCfg.MaxAcceptedHtlcs
+	htlcs := len(lc.channelState.ActiveHtlcs())
```
Comment (Crypt-iQ) [inline lnwallet/channel.go:6507]: `LocalChanCfg.MaxAcceptedHtlcs` is the maximum htlcs we'll accept on our commit tx.
`ActiveHtlcs` only counts htlcs that are active on *both* commit tx's, so it wouldn't count an htlc on the remote's pending commit tx.

Comment (Crypt-iQ) [reply lnwallet/channel.go:6507]: Related: https://github.com/lightningnetwork/lightning-rfc/issues/745

Comment (carlaKC) [reply lnwallet/channel.go]: > LocalChanCfg.MaxAcceptedHtlcs is the maximum htlcs we'll accept on our commit tx. 

this got me for a good 5 minutes, "local" is a bit of an ambiguous term here

> ActiveHtlcs only counts htlcs that are active on both commit tx's, so it wouldn't count an htlc on the remote's pending commit tx.

Thanks for pointing this out! Updated to be more accurate and only count outgoing htlcs that we've added to their commitment. I think this approach covers the remote pending commit, but not sure (a bit unfamiliar with this part of the codebase).

Comment (Crypt-iQ) [reply lnwallet/channel.go]: Just double-checked with a unit test, and `RemoteCommitment` doesn't store pending htlc's.  Those get applied after receiving a revocation from the counterparty.  With [option_dusty_htlcs_uncounted](https://github.com/lightningnetwork/lightning-rfc/issues/873) the way we count htlc's towards max_accepted_htlcs will change, and `RemoteCommitment` also stores dust htlcs.  I think it may be better to avoid duplicating the logic that's already performed in `lnwallet/channel.go` here (especially if it may change in the future):

https://github.com/lightningnetwork/lnd/blob/42099ef5e1e0f927290531fe2bff18406141567b/lnwallet/channel.go#L4938-L4946

I think the lines above can be extracted into a new function that is used to test the max_accepted_htlcs limit, which accounts for the remote pending commitment.

Comment (carlaKC) [reply lnwallet/channel.go]: Updated to go with the approach suggested here, thanks!

I'm not wild about passing in a "fake" htlc, but don't really see another way around it if we want to use `validateCommitmentSanity`, which makes sense to me.

**Comment by carlaKC** [comment]
> Think the first commit should be dropped like you said, o/w this patch looks good!

WDYT about keeping the itest? Was planning on updating to just add the itest in the last commit.

**Comment by Crypt-iQ** [comment]
> > Think the first commit should be dropped like you said, o/w this patch looks good!
> 
> WDYT about keeping the itest? Was planning on updating to just add the itest in the last commit.

Yeah I think the itest is good as it exercises previously uncovered behavior

File: lnwallet/channel.go [hunk 2]
```diff
@@ -4934,6 +4934,30 @@ func (lc *LightningChannel) AddHTLC(htlc *lnwire.UpdateAddHTLC,
...
+// want to test that we have slots for a potential htlc so we use a "mock"
+// htlc to validate a potential commitment state with one more outgoing htlc.
+func (lc *LightningChannel) MayAddOutgoingHtlc() error {
+	lc.Lock()
+	defer lc.Unlock()
+
+	// Create a "mock" outgoing htlc
+	pd := lc.htlcAddDescriptor(
+		&lnwire.UpdateAddHTLC{
+			Amount: lc.channelState.LocalChanCfg.MinHTLC,
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply lnwallet/channel.go:4948]: Wouldn't `validateCommitmentSanity` take that into account for us? Used `MinHtlc` here so that any failure due to balance restrictions would fail for any htlc (since size >= `MinHtlc`). If we move to not counting dust htlcs, I would expect `validateCommitmentSanity` to account for that?

**Comment by carlaKC** [comment]
> Yeah I think the itest is good as it exercises previously uncovered behavior

sgtm, squashed all itest changes to last commit where we add the fix.

File: lnwallet/channel.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply lnwallet/channel.go:4951]: I'm not sure I follow, let me know if my thinking isn't correct:
- We move to not count dust HTLCs towards the maximum number of HTLC's in flight
- We predict adding this `MinHTLC` (which may be dust) to the remote commitment transaction
- `validateCommitmentSanity` does not count this HTLC towards max in flight, when it should because the *actual* HTLC we are adding is greater than dust.

But also, this isn't relevant to this PR, just thought I'd point it out.

[the remark this answers is not in the document]
Comment (carlaKC) [reply lnwallet/channel.go:4951]: Ah right of course. Good thing to remember when we add `option_dusty_htlcs`, will have to update this check a bit. I think it's good enough in the meantime, since it addresses a pretty gnarley bug?

**Comment by carlaKC** [comment]
@Roasbeef is this something we could consider for 0.13? When this condition hits it really hammers the db with payment attempts, with 60 second timeout locally I saw 200-300 unnecessary attempts.

File: lnwallet/channel.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply lnwallet/channel.go:4951]: Yup I agree, and there's not consensus yet on `option_dusty_htlcs`, so this is a great stop-gap measure.  (And we'll still have this issue *with* `option_dusty_htlcs`)

File: lntest/itest/lnd_max_htlcs_test.go [hunk 3]
```diff
@@ -0,0 +1,215 @@
...
+	update, err = payment.Recv()
+	require.NoError(t.t, err, "no payment failed update")
+	require.Equal(t.t, lnrpc.Payment_FAILED, update.Status)
+	require.Len(t.t, update.Htlcs, 0, "expected no htlcs dispatched")
+
+	// Now that we're done, we cancel all our pending htlcs so that we
+	// can cleanup the channel with a coop close.
+	ctxt, _ = context.WithTimeout(ctxb, defaultTimeout)
+	for _, sub := range subscriptions {
+		sub.cancel(ctxt, t.t)
```
Comment (Crypt-iQ) [inline lntest/itest/lnd_max_htlcs_test.go:107]: nit: think this could use distinct `ctxt` so that all these `cancel` calls aren't under the same `defaultTimeout`?

File: lntest/itest/lnd_max_htlcs_test.go [hunk 4]
```diff
@@ -0,0 +1,215 @@
...
+	invUpdate, err := h.invSubscription.Recv()
+	require.NoError(t, err, "cancel invoice subscribe failed")
+	require.Equal(t, lnrpc.Invoice_CANCELED, invUpdate.State,
+		"expected invoice canceled")
+
+	// We expect one in flight update when our htlc is canceled back, and
+	// another when we fail the payment as a whole.
+	payUpdate, err := h.paymentSubscription.Recv()
+	require.NoError(t, err, "cancel payment subscribe failed")
+	require.Len(t, payUpdate.Htlcs, 1)
```
Comment (Crypt-iQ) [inline lntest/itest/lnd_max_htlcs_test.go:144]: nit: could assert `payUpdate` state?

File: lntest/itest/lnd_max_htlcs_test.go [hunk 5]
```diff
@@ -0,0 +1,215 @@
...
+	require.NoError(t.t, err, "bob does not have open channel")
+
+	// Alice and bob should have one channel open with each other now.
+	assertNodeNumChannels(t, net.Alice, 1)
+	assertNodeNumChannels(t, net.Bob, 1)
+
+	// Send our maximum number of htlcs from Bob -> Alice so that we get
+	// to a point where Alice won't accept any more htlcs on the channel.
+	subscriptions := make([]*holdSubscription, maxHtlcs)
+	subCtx, cancel := context.WithTimeout(ctxb, defaultTimeout)
```
Comment (Crypt-iQ) [inline lntest/itest/lnd_max_htlcs_test.go:53]: nit: could use different contexts so not all `acceptHoldInvoice` use the same `defaultTimeout`?

**Review by Crypt-iQ — APPROVED** [review]
LGTM 🏭 , just nits

**Comment by carlaKC** [comment]
[Rebased](https://github.com/lightningnetwork/lnd/compare/15fb00e9bf14f15efc0e2dfe8328a113af2e797c..abd249779642c6ad7455e7ed07b04d24005c3ffc) + [addressed](https://github.com/lightningnetwork/lnd/compare/abd249779642c6ad7455e7ed07b04d24005c3ffc..6aa37066b2339732da75da977d3860fcf90ff1b6) itest comments. Thanks for the review @Crypt-iQ !

**Review by Crypt-iQ — APPROVED** [review]

File: htlcswitch/interfaces.go [hunk 6]
```diff
@@ -145,6 +145,10 @@ type ChannelLink interface {
 	// will use this function in forwarding decisions accordingly.
 	EligibleToForward() bool
 
+	// MayAddOutgoingHtlc returns an error if we may not add an outgoing
```
Comment (Roasbeef) [inline htlcswitch/interfaces.go:148]: Why do we need this if we already have `CheckHtlcTransit` which calls `canSendHTLC` that eventually calls `Bandwidth` to ensure that the channel has enough idle bandwidth to carry the HTLC? In this case, one could say that if a channel has no free HTLC slots, then it effectively has zero bandwidth.

File: lntest/itest/lnd_max_htlcs_test.go [hunk 7]
```diff
@@ -0,0 +1,229 @@
...
+	err = assertNumActiveHtlcs([]*lntest.HarnessNode{
+		net.Alice, net.Bob,
+	}, 0)
+	require.NoError(t.t, err, "expected all htlcs canceled")
+
+	ctxt, _ = context.WithTimeout(ctxb, channelCloseTimeout)
+	closeChannelAndAssert(ctxt, t, net, net.Alice, chanPoint, false)
+}
+
+type holdSubscription struct {
```
Comment (Roasbeef) [inline lntest/itest/lnd_max_htlcs_test.go:133]: 👍

File: htlcswitch/interfaces.go (hunk 6 above)
Comment (Roasbeef) [reply htlcswitch/interfaces.go:148]: Thinking about this a bit more, I think as is this addresses the case of backing off when _we're_ the sender, but not the case where an outgoing link is fully saturated (in terms of idle HTLCs), and a new forward come across destined to that link. With the current control flow, we'll go all the way through and call `AddHTLC` on the link with that eventually failing and returning back a temp chan failure. However if we add this check to `CheckHtlcForward`, then we skip sending a message (with channel overhead, etc) to the link and can fail things back earlier at the forwarding site within the switch itself. 

If we like this alternative direction, then "mock validation" via the new `validateAddHtlc` can be used _within_ the link implementation (we don't need to extend the main interface) to apply this extra step of validation _before_ the multi-hop related checks (fee and timelocks, etc). 

One tradeoff with this alternative direction is that we'll allow an HTLC to proceed to the switch (it'll fail at the call to `getLocalLink`) vs it failing earlier at the router level (it'll get a nil policy as the bandwidth will show up as being zero). FWIW if it gets all the way here, then we'll emit a link failure event for the subscription RPC which might be useful for alerts to keep an eye on persistently full HTLC slots. 

Thoughts?

Comment (carlaKC) [reply htlcswitch/interfaces.go:148]: I like the idea of moving this check into `CheckHtlcForward` to get the `LinkFailure` event, but it doesn't solve the issue of pathfinding becoming aware of the link failure and excluding the link as a possible route (which is what's making us spin out at present).

This endless storm of htlcs happens in the following case:
* Payment tries to [launchShard](https://github.com/lightningnetwork/lnd/blob/master/routing/payment_lifecycle.go#L257) on a channel that is saturated 
* Our [sendPaymentAttempt](https://github.com/lightningnetwork/lnd/blob/master/routing/payment_lifecycle.go#L408) fails to [SendHtlc](https://github.com/lightningnetwork/lnd/blob/29d0b6491e7d824b66f387a5d20ba35525f1df3c/routing/payment_lifecycle.go#L705) because the link is full
* We [fail the htlc attempt](https://github.com/lightningnetwork/lnd/blob/29d0b6491e7d824b66f387a5d20ba35525f1df3c/routing/payment_lifecycle.go#L765) on disk and cancel the shard
* We loop back around in our payment logic and try to [launch another shard](https://github.com/lightningnetwork/lnd/blob/29d0b6491e7d824b66f387a5d20ba35525f1df3c/routing/payment_lifecycle.go#L212) using the same channel because pathfinding has no awareness that this channel has just failed us

The `queryBandwidth` check felt like the best way to communicate this unavailability to `RequestRoute`? The alternative would be to update [handleSendError](https://github.com/lightningnetwork/lnd/blob/master/routing/payment_lifecycle.go#L725)'s [error processing](https://github.com/lightningnetwork/lnd/blob/master/routing/router.go#L2279) to specifically understand this type of switch error and report it to mission control differently, since right now [we're just logging it](https://github.com/lightningnetwork/lnd/blob/master/routing/result_interpretation.go#L156). This is more involved (previously discussed and decided against it iirc), but it does seem like the less hacky way to go.

Comment (Crypt-iQ) [reply htlcswitch/interfaces.go:148]: Also would just like to point out that `Bandwidth()` is only concerned with bandwidth, and doesn't take into account space on the commitment. So the commitment could be full, but not all of its bandwidth consumed, which would be misleading if we relied on `canSendHtlc`.

Comment (Roasbeef) [reply htlcswitch/interfaces.go:148]: > This endless storm of htlcs happens in the following case:

Ah yeh this makes more sense, thanks for the breakdown. 

>  The alternative would be to update handleSendError's error processing to specifically understand this type of switch error and report it to mission control differently, since right now we're just logging i

Don't think this is the correct route either as we'd end up "penalizing" our local channels using our existing observation system when we we're actually able to have an up-to-date view of the state since it's a local channel. 

The thing that made be to a double take was the fact that we're extending a fundamental interface in the switch with a method that was effectively only put in place to solve a one-off issue. However looking at this addition from another angle, it forces callers that handle a link to be aware of that fact that we actually have two constraints w.r.t being able to forward HTLCs: the set of available bandwidth, and the current flow control constraints. 

With that said, how about renaming the newly added method from `MayAddOutgoingHtlc` to something like `func PaymentSlotAvailable(amt) bool` (just a suggestion)? This reflects that the method is a best-effort attempt at claiming an available payment slots (which encapsulates things like the future dust limits, max htlc, max in flight, etc). It's best-effort as no strong guarantees are made as it's possible that a forwarded HTLC instead claims the slots, and the caller would need to be aware of that. With this interface change, we'd also start to thread through the _amount_ as then we ensure we're able to factor in all the other flow control constraints. Actually without this, I think other infinite loops exist where adding an HTLC violates another constraint (aside from max HTLCs). 

Doesn't look like we have the amount available here when we go to query for bandwidth hints, but with a small tweak we could have the [`bandwidthHintsMap`](https://github.com/lightningnetwork/lnd/blob/master/routing/unified_policies.go#L178) map to a function closure (or interface) to allow it to accept an amount (and possibly later other parmaters). Looking at this section of the codebase with fresh eyes, it doesn't look like we attempt to adhere to the _link level constraints_ enforced by the remote party w.r.t what type of HTLCs they'll accept (like the link level min HTLC param). Taking this final step to make the bandwidth hints (from the PoV of the router) aware (via direction) of these link level constraints _should_ address this gap and any other lingering ones.

Comment (carlaKC) [reply htlcswitch/interfaces.go:148]: > The thing that made be to a double take was the fact that we're extending a fundamental interface in the switch with a method that was effectively only put in place to solve a one-off issue.

yeah def, also didn't love this approach
 
> Doesn't look like we have the amount available here when we go to query for bandwidth hints, but with a small tweak we could have the bandwidthHintsMap map to a function closure (or interface) to allow it to accept an amount (and possibly later other parmaters).

Took a look at this approach today and it looks like a good direction to go in - there's a working branch [here](https://github.com/carlaKC/lnd/commits/4656-amountawarehint), although I haven't fully tested it. 

One thing I ran into is that there are two cases where we use our hints: 
- [Local policy](https://github.com/lightningnetwork/lnd/blob/master/routing/unified_policies.go#L178): here we want to include htlc amount
- [Outgoing balance](https://github.com/lightningnetwork/lnd/blob/master/routing/pathfind.go#L378): iiuc, we don't actually want to check flow constraints here? Since it's just a total balance check


Ended up using `*lnwire.Millisatoshi` to infer whether we want to check flow as well, could possibly be a different method in the `bandwidthHints` interface.

Comment (Roasbeef) [reply htlcswitch/interfaces.go:148]: > Outgoing balance: iiuc, we don't actually want to check flow constraints here? Since it's just a total balance check

Yeah in that case, I'd expect that the map look up is `!ok` (we don't define a function for that edge) so we instead fall through to using the existing balance.

**Comment by Roasbeef** [comment]
Thought about this a bit more, and I think it's important we patch this issue in the short-term as it's affecting users in the wild. As I outlined above, we can generalize things a bit and also address other possible vectors for a tight HTLC loop like violating constraints like the max amount allowed in flight. So I'm thinking we move forward with what we have here, package it in 0.13.1, and shoot for the more fundamental fix so we can land it in 0.14.

**Review by Roasbeef — APPROVED** [review]
LGTM 🥜
