### PR TITLE
routing: Fix possible infinite loop on first hop unknown next peer

### LINKED ISSUE #6169: Bad route hint sends sender node into infinite payment loop
### Your environment

* lnd master 2682ca3e22ded37aa75ba40b5dd826bcd5cdd20a
* linux
* bitcoind

### Steps to reproduce

* Nodes A and B with a channel between them
* Patch node B to generate invoices that include a hop hint from A via a non-existent channel id
* Create invoice on B
* Pay invoice from A

### Expected behaviour

Payment fails immediately.

### Actual behaviour

Node A goes into an infinite payment loop where each iteration the outcome is the same `UNKNOWN_NEXT_PEER @ 0`.

### PR DESCRIPTION
**Pull request by lsunsi**
## Change Description

Add ignore condition to additional edges that connect to self. These
edges are already known and avoiding these hints protect the payment
from malformed channel ids which could lead to infinite loop.

Fixes #6169.

## Steps to Test
The #6169 issue explains the steps to reproduce the issue.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

File: routing/result_interpretation.go [hunk 1]
```diff
@@ -148,6 +148,12 @@ func (i *interpretedResult) processPaymentOutcomeSelf(
 			i.finalFailureReason = &reasonError
 		}
 
+	// If the first hop in the route wasn't known or offline. We probably
+	// received a malformed invoice with a invalid channel id in
+	// the first hop. So we fail to avoid retrying the same route.
+	case *lnwire.FailUnknownNextPeer:
+		i.failNode(rt, 1)
```
Comment (joostjager) [inline routing/result_interpretation.go:155]: To what extent does this allow an attacker to craft an invoice with bad route hints that leads us to penalize an arbitrary peer of ours?

Comment (lsunsi) [reply routing/result_interpretation.go:155]: @joostjager If it's possible for a payment between A and C to include a bad hop hint between A and B, then it's possible this change would penalize B without B even participating in this transaction. Is there a better way to fail the payment in this case? Maybe `failPair` like the `processPaymentOutcomeIntermediate` does in a similar situation?

Comment (joostjager) [reply routing/result_interpretation.go:155]: I don't think that penalization is the right solution for this problem. Would expect a check at an earlier stage.

**Comment by Crypt-iQ** [comment]
I would like to note that this is an "infinite" loop for three minutes

**Comment by lsunsi** [comment]
> I would like to note that this is an "infinite" loop for three minutes
Infinite until timeout, fair enough!

**Comment by lsunsi** [comment]
@lightninglabs-deploy Definitely! Will do

File: routing/result_interpretation.go (hunk 1 above)
Comment (lsunsi) [reply routing/result_interpretation.go]: @joostjager Makes sense, the penalization could be used for attacks. We looked for a way to fail the payment in an earlier step, but we didn't find a place the channel ID could be verified locally. Then we found that just failing the payment, without failing a node or a pair, works to avoid the infinite loop and is not exploitable in the way you mentioned. We updated the PR to reflect that, would you mind taking a second look?

Comment (lsunsi) [reply routing/result_interpretation.go]: @joostjager Got it, makes sense! We'll look more into this approach, and let you know! Thanks for the hint and second review

Comment (joostjager) [reply routing/result_interpretation.go]: Probably just have to filter out all the route hints from the self node in pathfinding, because we already know which public and private channels we have.

Comment (lsunsi) [reply routing/result_interpretation.go]: @joostjager I'll look into it today and ping you back! You've been really helpful, thanks a lot!

Comment (joostjager) [reply routing/result_interpretation.go]: @lsunsi are you still working on this?

Comment (lsunsi) [reply routing/result_interpretation.go]: @joostjager Definitely, we just updated the PR to reflect our latest attempt. Can you take a new look at it? This approach feels more correct than the previous ones definitely, so thanks for the guidance. It cleanly avoid the infinite loop and even makes the payment work in our tests (instead of just failing fast).

File: routing/pathfind.go [hunk 2]
```diff
@@ -542,14 +542,19 @@ func findPath(g *graphParams, r *RestrictParams, cfg *PathFindingConfig,
 		// search is taken place from target to source.
 		for _, outgoingEdgePolicy := range outgoingEdgePolicies {
 			toVertex := outgoingEdgePolicy.ToNodePubKey()
```
Comment (joostjager) [inline routing/pathfind.go:544]: This only needs to be executed if `vertex != self`

File: routing/pathfind_test.go [hunk 3]
```diff
@@ -1290,6 +1293,54 @@ func runPathFindingWithAdditionalEdges(t *testing.T, useCache bool) {
 	assertExpectedPath(t, graph.aliasMap, path, "songoku", "doge")
 }
 
+// runPathFindingWithRedundantAdditionalEdges asserts that we are able to
+// find paths to nodes ignoring additional edges that are already known by
+// self node.
+func runPathFindingWithRedundantAdditionalEdges(t *testing.T, useCache bool) {
+	graph, err := parseTestGraph(t, useCache, basicGraphFilePath)
```
Comment (joostjager) [inline routing/pathfind_test.go:1300]: This test graph is mainly used in the older tests. At some point it was considered impractical because it ties all tests together.

Newer tests are based on `newPathFindingTestContext` that takes a set of channels directly. You could consider using that.

File: routing/pathfind_test.go [hunk 4]
```diff
@@ -1290,6 +1293,54 @@ func runPathFindingWithAdditionalEdges(t *testing.T, useCache bool) {
...
+
+	require.NoError(t, err, "unable to find path to songoku")
+
+	// The path should represent the following hop roasbeef -> songoku
+	assertExpectedPath(t, graph.aliasMap, path, "songoku")
+
+	if path[0].ChannelID == hintChannelId {
+		t.Fatal("additional edge for known edge wasn't ignored")
+	}
+}
```
Comment (joostjager) [inline routing/pathfind_test.go:1342]: Would it be worth to add a test on a higher level that asserts that the infinite loop is no longer occuring?

Comment (lsunsi) [reply routing/pathfind_test.go:1342]: Definitely would, do you have a suggestion for where? We'll get right on it

File: routing/pathfind.go [hunk 5]
```diff
@@ -542,14 +542,19 @@ func findPath(g *graphParams, r *RestrictParams, cfg *PathFindingConfig,
...
-				sourceNode: vertex,
-				edge:       outgoingEdgePolicy,
-			}
 
-			additionalEdgesWithSrc[toVertex] =
-				append(additionalEdgesWithSrc[toVertex],
-					incomingEdgePolicy)
+			// Additional edges that connect to self can be safely ignored
+			// since they are already known.
+			if vertex != self {
```
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind.go:548]: That makes sense, we'll change it

File: routing/pathfind_test.go (hunk 4 above)
Comment (joostjager) [reply routing/pathfind_test.go:1342]: Perhaps `integrated_routing_test.go` is suitable for this. Not as heavy as an integration test, but it does cover the various interacting components for the bug that is fixed in this PR.

File: routing/pathfind.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind.go]: [6c94e09](https://github.com/lightningnetwork/lnd/pull/6766/commits/6c94e09a6f2b183dda4bd0d6ffe63fdf6a8ae618)

File: routing/pathfind.go (hunk 2 above)
Comment (lsunsi) [reply routing/pathfind.go:548]: [6c94e09](https://github.com/lightningnetwork/lnd/pull/6766/commits/6c94e09a6f2b183dda4bd0d6ffe63fdf6a8ae618)

File: routing/pathfind_test.go (hunk 3 above)
Comment (lsunsi) [reply routing/pathfind_test.go]: This one was a breeze to add and looks way better. [a2079ec](https://github.com/lightningnetwork/lnd/pull/6766/commits/a2079ec9649152b86a637fb95f353634801382da)

File: routing/pathfind_test.go (hunk 4 above)
Comment (lsunsi) [reply routing/pathfind_test.go:1345]: [92c372a](https://github.com/lightningnetwork/lnd/pull/6766/commits/92c372aad2b0919655d62bf0f9041776823936a1)

We gave it a go and ran into some difficulties. The bigger one was that when hop hints are passed the target public key is actually parsed, which means it cannot be an invalid set of bytes. We made it work improving the way the test creates the Vertex by actually turning the input byte into a valid public key, as you'll see from the commit.

Without the change we did, the test we coded fails due to unknown next peer, but it doesn't go into a loop. The loop probably happens on the lifecycle or some level above, but with our change what would be the unknown next peer actually turns into a successful payment (as tested), which is even better for this case.

What do you think? Should we test on some other level or are the already submitted tests enough?

Comment (joostjager) [reply routing/pathfind_test.go:1345]: The test does look good, but I am surprised that without the fix the infinite loop isn't reproduced. It does use payment session and mission control, so would expect that `RequestRoute` to return the same result each time. Maybe the bad route hint should be bad in a different way?

A definitive answer to this question would be great to have, so that there is certainty on what is covered exactly. I don't think it will be needed to write a test on yet another level.

Comment (lsunsi) [reply routing/pathfind_test.go:1345]: @joostjager Makes sense, me and @andreihod will investigate further and try to understand this behavior. We were able to reproduce the loop locally and verify that this fix works, so we'll try to explain why the test case is different from our testing.

Comment (lsunsi) [reply routing/pathfind_test.go:1345]: @joostjager Upon more investigation, we came to the conclusion that the loop is not reproduced in the test added to `integrated_routing_test` because it has it's own lifecycle loop (https://github.com/lightningnetwork/lnd/blob/master/routing/integrated_routing_context_test.go#L211) instead of using the real one (https://github.com/lightningnetwork/lnd/blob/master/routing/payment_lifecycle.go#L156), which causes the loop because the unknown next peer on first hop leads to a retry. We thought of adding one more test to `router_test` that triggers the loop exactly, but we weren't sure it was needed from what you mentioned before. How would you recommend we proceed?

Comment (lsunsi) [reply routing/pathfind_test.go:1345]: @joostjager [32db8f3](https://github.com/lightningnetwork/lnd/pull/6766/commits/32db8f36eadd1d4dd714dc42616ad0b1a0709487) Me and @andreihod ended up adding the missing test that exactly reproduces the infinite loop without the fix. We think we have all that we need, can you think of anything left?

Comment (joostjager) [reply routing/pathfind_test.go:1345]: Nice investigation. Is https://github.com/lightningnetwork/lnd/blob/202fcd6672a004881925710e6dc9e336af8945aa/routing/mock_graph_test.go#L68 the difference that causes the different behavior in the test - not returning a real unknown next peer error?

The `router_test.go` addition looks good. Probably better than using the integrated routing test, because it has more fake components.

Now that you have both tests, you could leave them to see what a Lightning Labs reviewer prefers?

**Review by joostjager — APPROVED** [review]

**Comment by andreihod** [comment]
Added a release note description of the bug (https://github.com/lightningnetwork/lnd/pull/6766/commits/851be3cc667aa017b648828ea506f29403d74f3f) and fixed a lint error (https://github.com/lightningnetwork/lnd/pull/6766/commits/b6c383416432b26a4157da72600436ae4c51bc59)

**Comment by lsunsi** [comment]
@joostjager With the latest commit, @andreihod fixed the linting and documentation issues. We were thinking how to move forward with this, do you have any suggestions? Should we ping someone to review or just wait?

**Comment by joostjager** [comment]
@lsunsi I would squash all commits into a single one. For further review, I've added @bitromortac.

**Comment by lsunsi** [comment]
@joostjager @andreihod just squashed all the fixups into one. We also updated the PR description to better fit the current solution and move the release notes to the correct version. We'll keep an eye on this PR if further changes are required.

**Comment by andreihod** [comment]
Fixed the last CI errors. It should pass now :)

**Review by bitromortac — COMMENTED** [review]
Good catch and a simple fix, I especially like the thorough testing :+1:! Left a few code-style nits (to fulfill [code formatting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_formatting_rules.md)).

Effectively, we prevent sending to ourselves with a hop hint here. Are we sure we want to prevent that? Some people may have applications for fake channel ids in combination with hosting users on the same node, where pathfinding is done (a bit far-fetched because for hosted channel setups, pathfinding would be done client-side and for the noncustodial case bookkeeping would be done on a per-payment hash basis).

**Review by carlaKC — APPROVED** [review]
Nice fix, and great tests! 

These bugs can be particularly gnarley to fix, so I created an itest demonstrating the loop and rebased it on your fix to demonstrate that it is indeed fixed: 
* Itest demonstrating bug [here](https://github.com/carlaKC/lnd/tree/6766-itest-demonstratebug) (scremz in logging)
* Itest rebased on this PR + updated to assert loop is fixed [here](https://github.com/carlaKC/lnd/tree/6766-itest-bugresolved)

Confident that goods are as advertized! I would like a comment on the `vertex == self` check explainig why we skip over hop hints sourced from our own node (for the sake of our future selves when we one day forget why we added it), but LGTM otherwise!

**Comment by bitromortac** [comment]
> Well, it's impossible to do this right now (as we enter an infinite loop till timeout then fail the payment), so I don't think there's concern that this is cutting out any use cases?
> 
> Besides, most of the funky fun hop hint things make the hint _from yourself_ to a fake channel ID so that the receiving node needs to handle the "fake" channel ID, not the sender. IMO this is how it should be.

Yes, my example was too constructed, just wanted to motivate a second thought on that.

File: routing/pathfind_test.go [hunk 6]
```diff
@@ -1290,6 +1293,57 @@ func runPathFindingWithAdditionalEdges(t *testing.T, useCache bool) {
 	assertExpectedPath(t, graph.aliasMap, path, "songoku", "doge")
 }
 
+// runPathFindingWithRedundantAdditionalEdges asserts that we are able to
+// find paths to nodes ignoring additional edges that are already known by
+// self node.
```
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind_test.go]: Fixed on [c621f8e](https://github.com/lightningnetwork/lnd/pull/6766/commits/c621f8e834ad8a0cf33e18780b005065250f2b91).

File: routing/pathfind_test.go [hunk 7]
```diff
@@ -1290,6 +1293,57 @@ func runPathFindingWithAdditionalEdges(t *testing.T, useCache bool) {
...
+	}
+
+	additionalEdges := map[route.Vertex][]*channeldb.CachedEdgePolicy{
+		ctx.source: {aliceToBob},
+	}
+
+	path, err := dbFindPath(
+		ctx.graph, additionalEdges, ctx.bandwidthHints, &ctx.restrictParams,
+		&ctx.pathFindingConfig, ctx.source, target, paymentAmt, ctx.timePref, 0,
+	)
```
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind_test.go]: Fixed on [c621f8e](https://github.com/lightningnetwork/lnd/pull/6766/commits/c621f8e834ad8a0cf33e18780b005065250f2b91).

File: routing/pathfind_test.go [hunk 8]
```diff
@@ -1290,6 +1293,57 @@ func runPathFindingWithAdditionalEdges(t *testing.T, useCache bool) {
...
+
+	require.NoError(t, err, "unable to find path to bob")
+	require.Len(t, path, 1)
+
+	if path[0].ChannelID != realChannelID {
+		t.Fatal("additional edge for known edge wasn't ignored")
+	}
```
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind_test.go]: Fixed on [c621f8e](https://github.com/lightningnetwork/lnd/pull/6766/commits/c621f8e834ad8a0cf33e18780b005065250f2b91).

File: routing/router_test.go [hunk 9]
```diff
@@ -361,6 +361,70 @@ func TestSendPaymentRouteFailureFallback(t *testing.T) {
...
+				FeeBaseMSat:     uint32(50),
+				CLTVExpiryDelta: uint16(200),
+			},
+		}},
+	}
+
+	var preImage [32]byte
+	copy(preImage[:], bytes.Repeat([]byte{9}, 32))
+
+	ctx.router.cfg.Payer.(*mockPaymentAttemptDispatcherOld).setPaymentResult(
```
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/router_test.go:404]: Added on [c621f8e](https://github.com/lightningnetwork/lnd/pull/6766/commits/c621f8e834ad8a0cf33e18780b005065250f2b91).

File: routing/pathfind.go [hunk 10]
```diff
@@ -540,8 +540,13 @@ func findPath(g *graphParams, r *RestrictParams, cfg *PathFindingConfig,
 	for vertex, outgoingEdgePolicies := range g.additionalEdges {
 		// Build reverse lookup to find incoming edges. Needed because
 		// search is taken place from target to source.
+		if vertex == self {
```
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind.go:543]: Added on [794494b](https://github.com/lightningnetwork/lnd/pull/6766/commits/794494b111e9940a3c199849340d9a73e4a7b11e)!

File: routing/mock_graph_test.go [hunk 11]
```diff
@@ -13,7 +14,12 @@ import (
 
 // createPubkey return a new test pubkey.
 func createPubkey(id byte) route.Vertex {
-	pubkey := route.Vertex{id}
+	_, secpPub := btcec.PrivKeyFromBytes([]byte{id})
```
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/mock_graph_test.go:17]: We needed to change this because the test required the private key to be a real one. Just mocking with fixed values would give us an error parsing the key. This change makes it so the parsing works because we use real generated values. Do you think this makes sense?

**Comment by lsunsi** [comment]
@carlaKC @bitromortac We just made all the suggested changes and answered all comments. We're available for further changes or discussions.

@carlaKC We checked out the test you wrote making sure the fix is working, do you need us to add your test to your branch or something like that?

File: routing/pathfind_test.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (bitromortac) [reply routing/pathfind_test.go]: The linter (`make lint`) is complaining about not complying with `go fmt`, could you please run `go fmt` on that file?

File: routing/router_test.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (bitromortac) [reply routing/router_test.go:404]: Looks good, thank you! Could you also break the comment `// Returns a FailUnknownNextPeer if it's trying to pay an invalid channel.` to fulfill the 80-char wrapping? Will then need a rebase concerning the release notes. Would be great if you could then squash the fixup commits too :rocket: (submitting fixup commits for further changes is not necessary).

**Comment by lsunsi** [comment]
@bitromortac Just squased and rebased. All good!

File: routing/pathfind.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply routing/pathfind.go:543]: An additional reason for skipping these is that our own channels are always in the graph already, so no need to add them here.

[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind.go:544]: @joostjager Definitely, we changed the comment a little bit to reflect what you mentioned more precisely.

File: routing/router_test.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/router_test.go]: @bitromortac Absolutely, we just edited the code a big to pass the 80-char limit in all places the linter was complaining.

File: routing/pathfind_test.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (lsunsi) [reply routing/pathfind_test.go]: @bitromortac Just did it! I think it's all compliant now

**Comment by lsunsi** [comment]
@carlaKC Oh, got it! We solved all the conflicts now I think.

**Comment by lsunsi** [comment]
@bitromortac Asking for re-review since the bot asked me so nicely! haha

**Comment by guggero** [comment]
Looks like the one reliable itest we have (`CI / run itests (btcd, backend=btcd)`) is currently broken on master and therefore also in your PR. We're going to fix that asap and then I'll ask you to rebase again to make sure this PR doesn't introduce a new failure. But this PR is first in the merge queue after we fix the btcd itest.

**Comment by lsunsi** [comment]
@guggero @bitromortac @joostjager @carlaKC Just rebased the PR to include newly merge master fixes. Let us know if anything!
