### PR TITLE
lnrpc/routerrrpc+routing: fix send to route error propagation

### LINKED ISSUE #5477: Payment failures are no longer populated as structured errors, payment failure details not returned
### Background

When making a payment using a send to a route directly, a payment failure normally would return a structured failure message with the failure code

This return value has changed to no longer return a structured failure, it now populates an unstructured error that is missing failure details.

Ideally the behavior for payment failures such as paying to an unknown payment hash remains consistent, and the full set of failure data is returned to the sender

The removal of structured failure data seems to have happened in https://github.com/lightningnetwork/lnd/pull/5332 with commit `cf2b5744a155c02b34ccb0e1d062f5e70e6fa7b4`

### Your environment

* lnd 0.13.1-beta rc1

### Steps to reproduce

- send from node a to node b, using a random payment hash

### Expected behavior

- a detailed failure response should be returned, and no error

### Actual behavior

- a terse error is returned with a string and no structured failure data

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we fix a regression introduced by a recent bug fix in
this area. Before this change, we'd inspect the error returned by
`processSendError`, and then fail the payment from the PoV of mission
control using the returned error.

A recent refactoring removed `processSendError` and combined the logic
with `tryApplyChannelUpdate` in order to introduce a new
`handleSendError` method that consolidates the logic within the
`shardHandler`. Along the way, the behavior of the prior check was
replicated in the form of a new internal `failPayment` closure. However,
the new function closure ends up returning a `channeldb.FailureReason`
instance, which is actually an `error`.

In the wild, when `SendToRoute` fails due to an error at the
destination, then this new logic caused the `handleSendErorr` method to
fail with an error, returning an unstructured error back to the caller,
instead of the usual payment failure details.

We fix this by no longer checking the `handleSendErorr` for an error as
normal. The `handleSendErorr` function as is will always return an error
of type `*channeldb.FailureReason`, therefore we don't need to treat it
as a normal error. Instead, we check for the type of error returned, and
update the control tower state accordingly.

With this commit, the test added in the prior commit now passes.

Fixes #5477.

### CODE REVIEW

File: routing/payment_lifecycle.go [hunk 1]
```diff
@@ -782,10 +782,13 @@ func (p *shardHandler) handleSendError(attempt *channeldb.HTLCAttemptInfo,
 		if err := p.router.cfg.Control.Fail(
 			p.identifier, *reason); err != nil {
 
-			return err
+			log.Errorf("unable to report failure to control "+
+				"tower: %v", err)
+
+			return &internalErrorReason
```
Comment (Roasbeef) [inline routing/payment_lifecycle.go:788]: Similar to ReportPaymentFail below, we just count this as an internal failure reason. This lets the method always return *channeldb.FailureReason.

The downside is that we lose this error context from the PoV, of the caller.

File: routing/router.go [hunk 2]
```diff
@@ -2163,15 +2164,29 @@ func (r *ChannelRouter) SendToRoute(htlcHash lntypes.Hash, rt *route.Route) (
 	// mark the payment failed with the control tower immediately. Process
 	// the error to check if it maps into a terminal error code, if not use
 	// a generic NO_ROUTE error.
-	if err := sh.handleSendError(attempt, shardError); err != nil {
-		return nil, err
-	}
+	var failureReason *channeldb.FailureReason
+	err = sh.handleSendError(attempt, shardError)
```
Comment (Roasbeef) [inline routing/router.go:2168]: I think the method should maybe just return `*channeldb.FailureReason` directly so it's clear that it can't return a "real" generic error.

File: routing/router_test.go [hunk 3]
```diff
@@ -2922,16 +2922,16 @@ func TestSendToRouteStructuredError(t *testing.T) {
 	}
 
 	// We'll modify the SendToSwitch method so that it simulates a failed
-	// payment with an error originating from the first hop of the route.
-	// The unsigned channel update is attached to the failure message.
+	// payment with an error originating from the final hop in the route.
+	finalHopIndex := len(hops)
```
Comment (Roasbeef) [inline routing/router_test.go:2926]: I think there's some value here, in just adding this as a new test case instead.

File: routing/router_test.go [hunk 4]
```diff
@@ -2922,16 +2922,16 @@ func TestSendToRouteStructuredError(t *testing.T) {
 	}
```
Comment (yyforyongyu) [inline routing/router_test.go:2922]: nit: there's a typo in the commit message, 

As is, this test will fail as a recent refactoring causes us to return a
`channeldb.FailureReason` error, since the newly added `handleSendError`
code path in the `SendToRoute` method will return the raw error, ~~ratehr~~ rather
than the `shardError`, which is of the expected type.

File: routing/router_test.go [hunk 5]
```diff
@@ -2944,11 +2944,11 @@ func TestSendToRouteStructuredError(t *testing.T) {
 
 	fErr, ok := err.(*htlcswitch.ForwardingError)
 	if !ok {
-		t.Fatalf("expected forwarding error")
+		t.Fatalf("expected forwarding error, got: %T", err)
```
Comment (yyforyongyu) [inline routing/router_test.go:2947]: nit: could use `require` instead. Same below.

File: routing/router.go [hunk 6]
```diff
@@ -2,6 +2,7 @@ package routing
 
 import (
 	"bytes"
+	goErrors "errors"
```
Comment (yyforyongyu) [inline routing/router.go:5]: wow didn't realize we were using `github.com/go-errors/errors`.

File: channeldb/payment_control.go [hunk 7]
```diff
@@ -503,7 +503,7 @@ func (p *PaymentControl) Fail(paymentHash lntypes.Hash,
 			return err
 		}
 
-		// We mark the payent as failed as long as it is known. This
+		// We mark the payment as failed as long as it is known. This
```
Comment (yyforyongyu) [inline channeldb/payment_control.go:506]: 👍

File: routing/router.go [hunk 8]
```diff
@@ -2163,15 +2164,29 @@ func (r *ChannelRouter) SendToRoute(htlcHash lntypes.Hash, rt *route.Route) (
...
-		return nil, err
+	switch {
+	// If we weren't able to extract a proper failure reason (which can
+	// happen if the second chance logic is triggered), then we'll use the
+	// normal no route error.
+	case err == nil:
+		err = r.cfg.Control.Fail(
+			paymentIdentifier, channeldb.FailureReasonNoRoute,
+		)
+		if err != nil {
```
Comment (yyforyongyu) [inline routing/router.go:2178]: The error check could be moved out of the switch statements, saving us a few lines.

File: routing/payment_lifecycle.go (hunk 1 above)
Comment (yyforyongyu) [reply routing/payment_lifecycle.go:788]: I'd prefer the `internalErrorReason`. To me errors come from other packages/services do seem to be "internal" when we are viewing it as the user of the `routing`. It's probably better (haven't thought through it) though we could wrap the error inside the internal error and returns it back to the caller.

**Review by yyforyongyu — APPROVED** [review]
Thanks for the fix! LGTM, just a few nits.

I haven't dug into the details about how errors are handled here, just a thought. It's probably better if we could make  package-specific error types so that the raw error is never returned. Maybe a `errors.go` under every package, and when returning an error inside the package, it must use the defined types and no more `if err != nil { return err}`. This would have the effect of forcing us to look into the errors returned and assign the appropriate type, so error-type-aware...

File: routing/router.go (hunk 6 above)
Comment (Roasbeef) [reply routing/router.go:5]: Yeah I had forgot about ti, till I hit a weird compiler error. I think w/ the latest version of the std lib Go error package, we don't really gain anything by using  `github.com/go-errors/errors` any longer. So we may want to do a sweep to remove it.

**Comment by Roasbeef** [comment]
>  It's probably better if we could make package-specific error types so that the raw error is never returned. 

Yeah generally we have this, like the set of errors in `routing/errors.go`. The issue here however, was the ambiguity w.r.t if an error was actual a fatal error, or an "internal error" to eventually be passed up and/or ignored.
