### PR TITLE
Bugfix/htlc flush shutdown

### LINKED ISSUE #6039: Can't mutual close with pending HTLC
### Background

When trying to close a channel with a lnd node, the node returned the error `cannot co-op close channel w/ active htlcs`

### Steps to reproduce

Open a channel to a lnd node, add a HTLC , send a shutdown message.

### Expected behaviour

The node should wait for the HTLC to be resolved, not add any new HTLC, and then reply with a shutdown message.
[BOLT 2: Channel Close](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#channel-close)

### Actual behaviour

The lnd node returns an error: `cannot co-op close channel w/ active htlcs`

### PR DESCRIPTION
**Pull request by ProofOfKeags**
## Change Description
This change fixes a bug where we would fail channels if our peer sent a shutdown message while there were still live HTLCs on the channel. Fixes #6039 

## Steps to Test
Steps for reviewers to follow to test the change.

### Testing
- [x] Your PR passes all CI checks.
- [x] Tests covering the positive and negative (error paths) are included.
- [x] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

## Summary by CodeRabbit

- **New Features**
  - Introduced a cooperative close of channels with active HTLCs.
  - Added a non-blocking option to the CloseChannel RPC call for faster operations when the closing transaction ID is not required.

- **Bug Fixes**
  - Resolved issues related to channel closure and payment settlement, removing the need for artificial delays in integration tests.

- **Documentation**
  - Updated the release notes to reflect compliance with BOLT2 shutdown procedures during in-flight HTLCs.

- **Tests**
  - Added new integration tests to ensure proper channel closure behavior with active HTLCs.
  - Enhanced existing tests to adapt to the new channel closing logic and HTLC management.

- **Refactor**
  - Refined channel state management and shutdown logic for improved clarity and control.
  - Restructured the channel closer logic into more focused methods for better lifecycle handling.

### CODE REVIEW

File: fn/mvar.go [hunk 1]
```diff
@@ -0,0 +1,205 @@
+package fn
+
+import (
+	"sync"
+	"sync/atomic"
+)
+
+// MVar[A any] is a structure that is designed to store a single value in an API
```
Comment (Roasbeef) [inline fn/mvar.go:8]: I think could use some more detail in the commit body re the rationale/usage for such a variable. Eg: does the `M` prefix have any intended semantic meaning?

File: fn/mvar.go [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+//
+// Take : MVar[A] -> A.
+func (m *MVar[A]) Take() A {
+	var val *A
+
+	// Here we use a Cond pattern and try to Swap nil into value. If we get
+	// a non-nil out it means we can actually finish the Take.
+	m.mutex.Lock()
+	for val = m.value.Swap(nil); val == nil; val = m.value.Swap(nil) {
+		m.tCond.Wait()
```
Comment (Roasbeef) [inline fn/mvar.go:80]: Do we need to thread through a `context.Context` here to allow any blocked callers to automatically exit if a shutdown is initiated?

File: fn/mvar.go [hunk 3]
```diff
@@ -0,0 +1,205 @@
...
+
+// Put will wait for a value to be made empty and will immediately replace it
+// with the argument.
+//
+// Put : (MVar[A], A) -> ().
+func (m *MVar[A]) Put(a A) {
+	// Here we use a Cond pattern and try to CompareAndSwap expecting value
+	// to be nil. If we successfully swap, it means we can actually finish
+	// the Put.
+	m.mutex.Lock()
```
Comment (Roasbeef) [inline fn/mvar.go:117]: Need to double check, but I think API wise the lock _within_ the condition variable should be the one that's obtained.

File: fn/mvar.go [hunk 4]
```diff
@@ -0,0 +1,205 @@
...
+// be woken up before callers of Take.
+//
+// Read : MVar[A] -> A.
+func (m *MVar[A]) Read() A {
+	var val *A
+
+	// While the Read is going we need to increment the WaitGroup so that
+	// a waiting Put operation knows when it can actually wake any waiting
+	// Takes
+	m.reads.Add(1)
```
Comment (Roasbeef) [inline fn/mvar.go:168]: Still getting through the diff, but: is this wait group ever reset? We'll need to take care to ensure that the wait group can't have a `Add` call follow a `Wait`, otherwise we'll run into a panic.

File: htlcswitch/interfaces.go [hunk 5]
```diff
@@ -138,6 +138,20 @@ type ChannelUpdateHandler interface {
 	// clean. This can be used with dynamic commitment negotiation or coop
 	// close negotiation which require a clean channel state.
 	ShutdownIfChannelClean() error
+
+	// Flush is a method that disables htlc adds to the channel until it has
+	// reached an empty state. When we reach zero HTLCs, the supplied
+	// function will be called.
+	Flush(func()) error
```
Comment (Roasbeef) [inline htlcswitch/interfaces.go:145]: Will this error out if a caller tries to flush while one is already outstanding? Or does it get added to a queue to permit multiple callers?

File: htlcswitch/interfaces.go [hunk 6]
```diff
@@ -138,6 +138,20 @@ type ChannelUpdateHandler interface {
 	// clean. This can be used with dynamic commitment negotiation or coop
 	// close negotiation which require a clean channel state.
 	ShutdownIfChannelClean() error
+
+	// Flush is a method that disables htlc adds to the channel until it has
```
Comment (Roasbeef) [inline htlcswitch/interfaces.go:142]: If we have `Flush`, then do we still need the `ShutdownIfChannelClean` above?

File: htlcswitch/link.go [hunk 7]
```diff
@@ -364,6 +365,10 @@ type channelLink struct {
 	// resolving those htlcs when we receive a message on hodlQueue.
 	hodlMap map[models.CircuitKey]hodlHtlc
 
+	// flushCont is a function that is called when the channel finishes
+	// flushing.
+	flushCont fn.MVar[func()]
```
Comment (Roasbeef) [inline htlcswitch/link.go:363]: Still getting through the diff, but: if this is always managed in the main event loop of the channel, then do we need this new concurrent-safe swappable condition variable? Otherwise I'm imagining something a bit simper (and a pattern we've used elsewhere), where we store the set of subscribers to notify after some condition/state has been met. 

Still trying to piece together the final control flow here....

File: htlcswitch/link.go [hunk 8]
```diff
@@ -528,6 +534,28 @@ func (l *channelLink) Stop() {
 	}
 }
 
+func (l *channelLink) Flush(onFlushed func()) error {
+	if !l.flushCont.TryPut(onFlushed) {
```
Comment (Roasbeef) [inline htlcswitch/link.go:531]: Oh I see now it'll restrict to only a single caller.

File: htlcswitch/link.go [hunk 9]
```diff
@@ -528,6 +534,28 @@ func (l *channelLink) Stop() {
...
+		return errors.New(
+			"can't flush because flush already in progress",
+		)
+	}
+
+	return nil
+}
+
+func (l *channelLink) CancelFlush() error {
+	if l.flushCont.TryTake().IsNone() {
```
Comment (Roasbeef) [inline htlcswitch/link.go:541]: Does this later on add the mechanics to _resume_ normal channel execution? If not, then what's gained by allowing a flush to. be cancelled?

File: htlcswitch/link.go [hunk 10]
```diff
@@ -570,7 +570,8 @@ func (l *channelLink) WaitForShutdown() {
 func (l *channelLink) EligibleToForward() bool {
 	return l.channel.RemoteNextRevocation() != nil &&
 		l.ShortChanID() != hop.Source &&
-		l.isReestablished()
+		l.isReestablished() &&
+		!l.IsFlushing()
```
Comment (Roasbeef) [inline htlcswitch/link.go:567]: 👍 

This'll prevent the router from trying to send an HTLC over the link, and also the switch from trying to forward over the link.

File: htlcswitch/link.go [hunk 11]
```diff
@@ -1306,6 +1307,20 @@ func (l *channelLink) htlcManager() {
 		case <-l.quit:
 			return
 		}
+
+		// After we are finished processing the event, if the link is
```
Comment (Roasbeef) [inline htlcswitch/link.go:1289]: So this won't always be reached, certain cases above can cause us to `continue` to the next evaluation of the loop. Eg: fee update ticks, but nothing actually needed. 

I think in practice though, this'll eventually be reached as anytime we process an actual update, we'll drop down there.

File: htlcswitch/link.go [hunk 12]
```diff
@@ -1306,6 +1307,20 @@ func (l *channelLink) htlcManager() {
...
+		// flushing, we check if the channel is clean and invoke the
+		// post-flush hook if it is.
+		if l.IsFlushing() && l.channel.IsChannelClean() {
+			// This will not block since flushCont must be full.
+			// We Read instead of Take to ensure a new flush
+			// operation can't be initiated until the continuation
+			// for the current flush has completed.
```
Comment (Roasbeef) [inline htlcswitch/link.go:1296]: Ahh ok, I think this completes my mental model of the control flow here.

File: htlcswitch/link.go [hunk 13]
```diff
@@ -1306,6 +1307,20 @@ func (l *channelLink) htlcManager() {
...
+			l.flushCont.Read()()
+
+			// Reset the flushCont MVar. This will also not block.
+			l.flushCont.Take()
```
Comment (Roasbeef) [inline htlcswitch/link.go:1300]: Ah I see here now that the state can basically be fully re-used. Eg: dyn commitments when we want to do a series of independent updates w/o actually tearing down the link.

File: htlcswitch/link.go [hunk 14]
```diff
@@ -3085,6 +3099,25 @@ func (l *channelLink) processRemoteAdds(fwdPkg *channeldb.FwdPkg,
 
 		fwdInfo := pld.ForwardingInfo()
 
+		// If we are in a flush state we need to cancel back all of the
+		// net new HTLCs rather than forwarding them. This is the first
+		// opportunity we have to bounce invalid HTLC adds without
+		// doing a force-close.
+		if l.IsFlushing() {
```
Comment (Roasbeef) [inline htlcswitch/link.go:3072]: 👍

File: htlcswitch/interfaces.go [hunk 15]
```diff
@@ -137,7 +137,7 @@ type ChannelUpdateHandler interface {
 	// ShutdownIfChannelClean shuts the link down if the channel state is
 	// clean. This can be used with dynamic commitment negotiation or coop
 	// close negotiation which require a clean channel state.
-	ShutdownIfChannelClean() error
+	ShutdownHtlcManager()
```
Comment (Roasbeef) [inline htlcswitch/interfaces.go:140]: `godoc` comment not updated.

Comment (Roasbeef) [reply htlcswitch/interfaces.go:140]: But if we have the new flush call, then in situations where's a flush to shut down, can't we just add that context to an arg in `Flush`. This way the caller doesn't need to reach down as much into the implementation details of how the link works. Instead if the extra arg is set, then the link starts to down itself down when it's safe to do so. 

Technically, the link should still be "up" (but in the fully flushed state) until shutdown is sent and recv'd by other parties. As there's a provision that lets either side send a new `update_fee` to adjust the current fee level.

File: htlcswitch/link.go [hunk 16]
```diff
@@ -2796,26 +2774,14 @@ func (l *channelLink) HandleChannelUpdate(message lnwire.Message) {
...
-	case l.shutdownRequest <- &shutdownReq{
-		err: errChan,
-	}:
+	case l.shutdownRequest <- struct{}{}:
 	case <-l.quit:
-		return ErrLinkShuttingDown
-	}
-
-	select {
-	case err := <-errChan:
```
Comment (Roasbeef) [inline htlcswitch/link.go:2773]: See comments above (I think we can remove this method all together), but in the past this was sync, and now it's async.

File: peer/brontide.go [hunk 17]
```diff
@@ -3133,19 +3133,18 @@ func (p *Brontide) tryLinkShutdown(cid lnwire.ChannelID) error {
...
-	// link's goroutines and remove it from the switch's internal maps. We
-	// don't call WipeChannel as the channel must still be in the
-	// activeChannels map to process coop close messages.
-	p.cfg.Switch.RemoveLink(cid)
-
-	return nil
+	return chanLink.Flush(func() {
+		// Else, the link exists, so attempt to trigger shutdown. If
+		// this fails, we'll send an error message to the remote peer.
+		chanLink.ShutdownHtlcManager()
```
Comment (Roasbeef) [inline peer/brontide.go:3139]: I think we can hide this information from the caller, by executing this logic in the link if a new arg is set.

File: peer/brontide.go [hunk 18]
```diff
@@ -3133,19 +3133,18 @@ func (p *Brontide) tryLinkShutdown(cid lnwire.ChannelID) error {
...
+
+		// Next, we remove the link from the switch to shut down all of
+		// the link's goroutines and remove it from the switch's
+		// internal maps. We don't call WipeChannel as the channel must
+		// still be in the activeChannels map to process coop close
+		// messages.
+		p.cfg.Switch.RemoveLink(cid)
```
Comment (Roasbeef) [inline peer/brontide.go:3146]: IIUC, we need to insert the continuation signal here. In other words, in the case where we're trying to shutdown to do co-op close, the control flow (when we receive the request from our remote peer) needs to block _after_ sending `shutdown` (it shouldn't send `closing_signed` until the shutdown is finished). For the RPC flow, IMO we still want to just hard exit here as default behavior. We can add a new sync flow with a new API or arg to the existing API.

File: peer/brontide.go (hunk 17 above)
Comment (Roasbeef) [reply peer/brontide.go:3139]: Also `RemoveLink` will end up shutting down the main loop here: https://github.com/lightningnetwork/lnd/blob/5e369a02bb789140d286391edb7a86d78337dd25/htlcswitch/switch.go#L2580-L2581

So with that, I don't think we need `ShutdownHtlcManager` at all.

**Review by Roasbeef — CHANGES_REQUESTED** [review]
Great PR! `MVar` certainly seems very powerful, but I have to confess that I still need to study the implementation more closely to make sure there aren't any obvious pitfalls. In the past, we've realized that `sync.Cond` can take a bit of care to ensure it's used properly. 

Left some comments in line re another area we need to cancel back (`mailbox.FailAdd` when handling down stream requests). Also I think we need to add a new _continuation_ flow from the link to the chan closer. After shutdown is sent+recv'd, and only _after_ the flush has fully completed should the state machine in the `ChanCloser` be allowed to progress. I think we can do this by adding the continuation logic to the closure we send as a callback to `Flush`.

File: fn/mvar.go [hunk 19]
```diff
@@ -0,0 +1,205 @@
...
+// It supports two operations: take and put.
+//
+// The state transition rules are as follows:
+//  1. put while full blocks.
+//  2. put while empty sets.
+//  3. take while full resets.
+//  4. take while empty blocks.
+//  5. read while full nops.
+//  6. read while empty blocks.
+type MVar[A any] struct {
```
Comment (yyforyongyu) [inline fn/mvar.go:22]: Why do we need this when we already have [`atomic`](https://pkg.go.dev/sync/atomic) and [`sync`](https://pkg.go.dev/sync)? Or what are the use cases?

Comment (ProofOfKeags) [reply fn/mvar.go:22]: The use case is not having to think about synchronization as a separate thing from state management. If you need shared state across threads you can use one of these instead of rolling your own every time. It's not quite as good as STM but I don't have the skill/knowledge to quickly implement a nice STM API at the moment.

In my case here I made this because when I was designing the rest of this change I reached for [this API](https://hackage.haskell.org/package/base-4.19.0.0/docs/Control-Concurrent-MVar.html) that is part of the standard library in Haskell 

I personally don't think anyone should be using the usual sync primitives directly in application code. It's error prone and there are better abstractions to use out there such as this one. I certainly don't want to think about sync primitives when I'm writing domain specific logic.

File: fn/mvar.go (hunk 1 above)
Comment (ProofOfKeags) [reply fn/mvar.go:8]: Would you rather have it in the commit body or just in the godoc itself?

File: fn/mvar.go (hunk 2 above)
Comment (ProofOfKeags) [reply fn/mvar.go:80]: Probably a good idea. We can make it optional and if they don't provide one then we just block til the heat death of the universe.

File: fn/mvar.go (hunk 3 above)
Comment (ProofOfKeags) [reply fn/mvar.go:117]: In this case they are the same.

File: fn/mvar.go (hunk 4 above)
Comment (ProofOfKeags) [reply fn/mvar.go:168]: The only call to wait is in Put, and it is just to ensure that all blocked readers are satisfied before control is handed to a blocked Take operation.

Comment (ProofOfKeags) [reply fn/mvar.go:178]: Turns out that an interleaving stress test revealed this was an issue. It has been fixed now

File: fn/mvar.go (hunk 3 above)
Comment (ProofOfKeags) [reply fn/mvar.go]: I have modified this to make it explicit so as not to spook anyone who is used to the pattern in the docs

File: htlcswitch/link.go (hunk 9 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:541]: There may be a discussion to have here. In this case since all channel link impairment is implicit on the state of this MVar the cancel will implicitly resume normal channel function. The only "irrevocable" action is the shutdown of the htlc manager which happens in the continuation inserted here. So it can be cancelled until the flushCont begins executing. We can remove this API though, as it was only added for completeness. I can't think of a reason en-protocol that we want this.

File: htlcswitch/interfaces.go (hunk 6 above)
Comment (ProofOfKeags) [reply htlcswitch/interfaces.go:142]: I'm leaning towards no. It's somewhat of an "Unsafe" method and doesn't seem necessary. It's only purpose is to interrupt the htlcManager goroutine.

File: htlcswitch/interfaces.go (hunk 5 above)
Comment (ProofOfKeags) [reply htlcswitch/interfaces.go:145]: It error's out right now and I'm reticent to handle it differently. If we wanted to permit multiple callers it would make more sense to have a list of continuations that are invoked in sequence once we hit HTLC-0 but I'm inclined to let a use case where we actually want that pop up first.

File: htlcswitch/link.go (hunk 7 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:363]: Because Flush is on the link interface we can't guarantee that we won't have callsites in different threads.

**Comment by ProofOfKeags** [comment]
Replaces #8145

File: htlcswitch/link.go (hunk 16 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:2773]: It appears so

File: fn/mvar.go (hunk 2 above)
Comment (ProofOfKeags) [reply fn/mvar.go:81]: Upon second look, even if we accept a context here it raises the question of whether we want to have an error value that can be returned from this function. It would impair the interface unless it was acceptable to panic, which I suspect it wouldn't be. Otherwise we now have an error type we need to add to the interface which would have to be checked all the time. If you think it's worth it to have it be cancellable like that but less ergonomic, then we can.

File: htlcswitch/link.go (hunk 14 above)
Comment (Crypt-iQ) [reply htlcswitch/link.go:3055]: We should only do this cancel back logic if the state of `fwdPkg` is `FwdStateLockedIn`. If the state is `FwdStateProcessed`, the htlc may already have been sent to the outgoing link in a prior invocation of `processRemoteAdds` and canceling back would be unsafe

File: fn/mvar.go (hunk 2 above)
Comment (Crypt-iQ) [reply fn/mvar.go:81]: Wouldn't we get a deadlock if there's no way to stop waiting?

Comment (ProofOfKeags) [reply fn/mvar.go:81]: Isn't that true of a number of other synchronization tools too, including go channels? It is true that a misuse of this API will absolutely result in a deadlock. Suppose we do want to make these waits cancellable, though, are we willing to panic the thread, or do we really want to check for async cancellation everywhere? I see an argument for both.

File: htlcswitch/interfaces.go [hunk 20]
```diff
@@ -138,8 +138,73 @@ type ChannelUpdateHandler interface {
...
+
+	// IsDraining returns true when UpdateAddHtlc's are disabled in the
+	// direction of the argument.
+	IsDraining(direction LinkDirection) bool
+
+	// OnFlushedOnce is a method that adds a hook to be called the next time
+	// the channel state reaches zero htlcs. This hook will only ever be
+	// called once. This function returns a FlushId that can be used to
+	// preemptively remove this hook.
+	OnFlushedOnce(func()) FlushHookID
```
Comment (yyforyongyu) [inline htlcswitch/interfaces.go:160]: I think we are exposing too much implementation details of `link`, instead we should seek designs that can deepen the interface methods.

**Comment by ProofOfKeags** [comment]
@yyforyongyu

> Trying to learn more about MVar and got a bit confused - how is this different from go channel? I guess it has a Read method - but other than that IMO go channel can do a better job?

Channels do a better job up until the point where you try to read the front of the channel without changing state. In fact my initial implementation looks exactly like the implementation you wrote out. 

> I guess a more fundamental question is, why should we use this MVar which is built for Haskell to control concurrency, while go insists we should [share memory by communicating](https://go.dev/doc/effective_go#concurrency). Meanwhile I find this guy's answer interesting as [Haskell also does CSP](https://stackoverflow.com/a/4522407).

The current version of this PR doesn't actually use MVar anymore and if I get to the end of this task and find I don't need it I'll cherry pick the commit and put it in a different draft PR and drop it from this PR. I put it in originally because an earlier implementation (which had fundamental design issues) made use of it and I chose to use it there because it was the first tool I reached for. In particular, I wanted the Read/TryRead functionality, something go channels do not provide.

> Aside from that, ideally I think links should be managed by switch and brontide would only need to interact with switch. When the channel is shutting down, brontide just calls an inteface method switch.CloseLink(linkID), which returns a channel that brontide will listen to, and it will be closed when link is fully cleaned.

Maybe, but I don't currently intend to do that in this PR. Happy to discuss this architectural change as I do believe that ownership and message flow are not ideal at the moment. I think the fact that the link is both driven by the brontide and the switch is manageable but I agree that there may be opportunities to simplify things and fix a lot of latent bugs by mediating all link access through the switch.

File: fn/mutguard.go [hunk 21]
```diff
@@ -0,0 +1,30 @@
+package fn
+
+import "sync"
+
+type MutGuard[A any] struct {
```
Comment (ProofOfKeags) [inline fn/mutguard.go:5]: Current revision of this PR doesn't make use of this API. I'm leaving it here until this PR is finalized and if it doesn't make the final cut, I can drop the commit entirely or I can PR separately if we think it is useful.

File: fn/mvar.go [hunk 22]
```diff
@@ -0,0 +1,212 @@
...
```
Comment (ProofOfKeags) [inline fn/mvar.go:22]: Current revision of this PR doesn't make use of this API. I'm leaving it here until this PR is finalized and if it doesn't make the final cut, I can drop the commit entirely or I can PR separately if we think it is useful.

File: fn/rwguard.go [hunk 23]
```diff
@@ -0,0 +1,25 @@
+package fn
+
+import "sync"
+
+type RwGuard[A any] struct {
```
Comment (ProofOfKeags) [inline fn/rwguard.go:5]: Current revision of this PR doesn't make use of this API. I'm leaving it here until this PR is finalized and if it doesn't make the final cut, I can drop the commit entirely or I can PR separately if we think it is useful.

File: peer/brontide.go [hunk 24]
```diff
@@ -3617,6 +3617,22 @@ func (p *Brontide) StartTime() time.Time {
 // message is received from the remote peer. We'll use this message to advance
 // the chan closer state machine.
 func (p *Brontide) handleCloseMsg(msg *closeMsg) {
+	link := p.fetchLinkFromKeyAndCid(msg.cid)
+	if link == nil {
+		// TODO(proofofkeags): is this ever a valid situation?
```
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply peer/brontide.go:3590]: I don't follow, can you elaborate? Currently in the code as written, link can be nil here and we'd still need to process the closing_signed. I think we just need to process the closing_signed even if the link is down

[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply peer/brontide.go:3590]: I currently am fetching the link because later in this function I need to add link lifecycle hooks (introduced in an earlier commit in this PR). It seems like if the link has already been removed then we wouldn't need to insert those hooks. I will update the PR to reflect this understanding and maybe the code will be clearer than my explanation.

File: htlcswitch/link.go [hunk 25]
```diff
@@ -384,6 +396,66 @@ type channelLink struct {
 	quit chan struct{}
 }
 
+// hookMap is a data structure that is used to track the hooks that need to be
+// called in various parts of the channelLink's lifecycle.
+//
+// WARNING: NOT thread-safe.
+type hookMap struct {
+	transient  map[uint64]func()
```
Comment (bhandras) [inline htlcswitch/link.go:400]: Given that keys are random and map iteration order is also not guaranteed, could a more deterministic design, such as using a simple slice to store the hooks work better? Or do explicitly want the randomness? If so perhaps worth noting that in the godoc of the type.

Alternatively a priority queue could be considered too if adding hooks is non-deterministic but we still want to ensure order.

Comment (ProofOfKeags) [reply htlcswitch/link.go:400]: I'm on the fence. I have arguments for both ways but I'm leaning towards agreeing that a linear design will have fewer surprises for the the caller and I don't have a good enough reason to no promise it. Right now we call the hooks from the control context of the link's main event loop and I think that's a good idea. If we want parallel execution we would just put the logic in its own goroutine and wait on a channel send from the hook. Also while using a slice will cause fragmentation if we continually add and remove persistent hooks there are ways to correct that by tracking the "freed" slots and reallocating them to future adds.

So yeah. Let's promise either queue or stack order on the interface. Do you have a preference?

File: htlcswitch/link.go [hunk 26]
```diff
@@ -367,10 +363,102 @@ type channelLink struct {
...
+func (m *hookMap) alloc(hook func(), persistent bool) uint64 {
+	var relevant map[uint64]func()
+	if persistent {
+		relevant = m.persistent
+	} else {
+		relevant = m.transient
+	}
+
+	for {
+		//nolint:gosec
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:423]: Do you think that the randomness we need for hook id allocation requires cryptographic assurance?

File: htlcswitch/link.go [hunk 27]
```diff
@@ -2411,6 +2564,12 @@ func (l *channelLink) updateCommitTx() error {
 	}
 	l.cfg.Peer.SendMessage(false, commitSig)
 
+	// Now that we have sent out a new CommitSig, we invoke the outgoing set
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:2544]: I don't think it matters. But knowing what we promise does matter. We can do before or after queueing but we probably ought to specify exactly which one it is in the interface.

File: htlcswitch/interfaces.go (hunk 20 above)
Comment (ProofOfKeags) [reply htlcswitch/interfaces.go:155]: I think we should have a conversation about what subsystems "own" each other. The way I've conceptualized everything right now is that we have:

Brontide <-> ChannelLink <-> Switch <-> ChannelLink <-> Brontide

and that each of these subsystems has a "peer" relationship with one another. That said, I can imagine and can endorse a design where the Switch "owns" the ChannelLinks. This makes sense to a degree because we already rely on the Switch to be able to look up the ChannelLink from the ChanID so there are already sketches of this relationship in the codebase today.

I don't think we should remove the API I put in here since I think it accurately describes what the role of the link is, but making the Brontide responsible for coordinating the lifecycle continuations is probably neither necessary nor ideal.

Does this match what you are thinking?

File: htlcswitch/link.go [hunk 28]
```diff
@@ -367,10 +363,102 @@ type channelLink struct {
...
 	quit chan struct{}
 }
 
+// hookMap is a data structure that is used to track the hooks that need to be
+// called in various parts of the channelLink's lifecycle.
+//
+// WARNING: NOT thread-safe.
+type hookMap struct {
+	transient  map[uint64]func()
+	persistent map[uint64]func()
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:401]: Persistent hooks don't need to be GC'ed, transient hooks are cleared when `invoke` is called. That said, if we want the link's `Stop` method to put it in a clean state, that would be the time to GC them.

File: htlcswitch/link.go [hunk 29]
```diff
@@ -367,10 +363,102 @@ type channelLink struct {
...
+	var relevant map[uint64]func()
+	if persistent {
+		relevant = m.persistent
+	} else {
+		relevant = m.transient
+	}
+
+	for {
+		//nolint:gosec
+		hookID := prand.Uint64()
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:424]: I'm struggling to understand what that fixes.

File: htlcswitch/link.go [hunk 30]
```diff
@@ -1729,6 +1927,19 @@ func (l *channelLink) handleUpstreamMsg(msg lnwire.Message) {
 			return
 		}
 
+		l.RWMutex.Lock()
+		if l.IsDraining(Incoming) {
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:1931]: I don't think it matters. We want to accept the add either way and cancel it back if it came in while we were draining the inbound.

File: peer/brontide.go [hunk 31]
```diff
@@ -3009,7 +2992,26 @@ func (p *Brontide) handleLocalCloseReq(req *htlcswitch.ChanClose) {
 			return
 		}
 
-		p.queueMsg(shutdownMsg, nil)
+		link := p.fetchLinkFromKeyAndCid(chanID)
+		if link != nil {
```
Comment (Crypt-iQ) [inline peer/brontide.go:2996]: `if link == nil`

File: peer/brontide.go [hunk 32]
```diff
@@ -3656,10 +3643,41 @@ func (p *Brontide) handleCloseMsg(msg *closeMsg) {
...
+				})
+			},
+		)
+		oClosingSigned.WhenSome(
+			// If we have a ClosingSigned to send, let's defer it
+			// until the channel has no remaining HTLCs.
+			func(msg lnwire.ClosingSigned) {
+				link.OnFlushedOnce(func() {
+					p.cfg.Switch.RemoveLink(msg.ChannelID)
+					p.queueMsg(&msg, nil)
```
Comment (Crypt-iQ) [inline peer/brontide.go:3677]: I think there are some subtle issues here because the counter-party is allowed to interact w/ our `ChanCloser` state machine by sending `closing_signed` even though we're "not ready" for it:

- If the counter-party repeatedly sends us `closing_signed` that we don't agree with, we'll respond with our own `closing_signed`. Here, respond means we add another flush hook to the link and keep our `closing_signed` response in memory. When we are finally ready to flush, we could end up sending hundreds of thousands of messages assuming the node hasn't OOM'd first.
- If the counter-party instead sends us a message that agrees with our `closing_signed` or is close enough to ours that we agree with them, we'll end up broadcasting the cooperative close transaction even though the link is still up. Due to the way balance is calculated in coop close, if we've offered an HTLC to the counter-party, that HTLC will effectively be deleted from our balance and be used as fees. This could be used as a griefing vector

File: lnwallet/chancloser/chancloser.go [hunk 33]
```diff
@@ -534,16 +545,18 @@ func (c *ChanCloser) ProcessCloseMsg(msg lnwire.Message) ([]lnwire.Message,
 		// wire.
 		localShutdown, err := c.initChanShutdown()
```
Comment (Crypt-iQ) [inline lnwallet/chancloser/chancloser.go:546]: `initChanShutdown` calls `MarkCoopBroadcasted` which will update the channel's status at the database level. This will make it so that further commitment updates in the link won't work. `MarkCoopBroadcasted` should instead be called when we've flushed and are ready to send `closing_signed`.

File: peer/brontide.go (hunk 31 above)
Comment (ProofOfKeags) [reply peer/brontide.go:2996]: we can't register a flush hook on a nil channel link though..

File: peer/brontide.go (hunk 32 above)
Comment (ProofOfKeags) [reply peer/brontide.go:3677]: The protocol adherence of the shutdown procedure should be enforced by the ChanCloser, no?

I do agree here that if there are many rounds of closing_signed negotiation, we need to ensure that the link is only given a single flush hook to tear itself down. If the link is already torn down it means that we are firmly in closing negotiation and we can synchronously send the message back.

Nice catch.

File: peer/brontide.go [hunk 34]
```diff
@@ -3617,6 +3590,20 @@ func (p *Brontide) StartTime() time.Time {
 // message is received from the remote peer. We'll use this message to advance
 // the chan closer state machine.
 func (p *Brontide) handleCloseMsg(msg *closeMsg) {
+	link := p.fetchLinkFromKeyAndCid(msg.cid)
+
+	if link != nil {
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply peer/brontide.go:3595]: No because the ChanCloser state machine needs to be driven. The Link's lifecycle terminates when shutdown has been both sent and received, but there are still messages that must be exchanged in the coop close negotiation after that.

File: peer/brontide.go [hunk 35]
```diff
@@ -3653,18 +3648,50 @@ func (p *Brontide) handleCloseMsg(msg *closeMsg) {
...
-		return
 	}
 
-	// Queue any messages to the remote peer that need to be sent as a part of
-	// this latest round of negotiations.
-	for _, msg := range msgs {
-		p.queueMsg(msg, nil)
+	// Next, we'll process the next message using the target state machine.
+	// We'll either continue negotiation, or halt.
+	switch typed := msg.msg.(type) {
```
Comment (Roasbeef) [inline peer/brontide.go:3642]: Drive by review (was just sent this commit in isolation), but I think that we should move this back into something _like_ `ProcessCloseMsg`. Then this way the peer doesn't need to be aware of the messages it needs to route to the chan closer _and_ which methods to call in order to execute them. 

Then in then in the future when we add the new simple co-op close state machine, this call site stays mostly the same (we break out a new interface to abstract away from the protocol being executed). 

If we want to keep the state machine mostly pure, we can have it emit an event (similar to above), and there's a certain event type that says: "send this message to the peer". Otherwise, the chan closer can gain a slim `Peer` interface, that's just used to flush out new messages. Unit tests can have this send to a channel, while the actual system passes in the peer directly (implicit interface).

File: htlcswitch/interfaces.go (hunk 20 above)
Comment (yyforyongyu) [reply htlcswitch/interfaces.go]: Yep, I don't think we need to remove the API either, either on interface level or implementation level. But because `making the Brontide responsible for coordinating the lifecycle continuations is probably neither necessary nor ideal`, I'd say not expose `link` in `brontide`. Sharing some notes I've taken previously,
```
- When we init the shutdown:
	- request shutdown via `rpcServer.CloseChannel`
		- link is closed via `switch.CloseLink`, which creates a `htlcswitch.ChanClose` message that has a channel `Updates` that's used by the `chanCloser` to notify the channel is closed, then,
			- `switch` calls `s.cfg.LocalChannelClose`, mounted to `brontide.HandleLocalCloseChanReqs`
				- brontide calls `handleLocalCloseReq`:
					- 1. brontide creates a channel closer via `p.createChanCloser` and stores it in `p.activeChanCloses`, `htlcswitch.ChanClose` message is passed to this closer.
					- 2. brontide calls `chanCloser.ShutdownChan()`, in which,
						- `chanCloser` calls `initChanShutdown`, in which,
							- calls `c.cfg.DisableChannel`, that mounts to `ChanStatusMgr.RequestDisable`, in which,
								- `ChanStatusManager` calls `processDisableRequest`, in which,
									- it creates a channel update and calls `m.cfg.ApplyChannelUpdate`, mounts to `s.applyChannelUpdate` that sends a `ChannelUpdate` via the `authGossiper`
							- TODO calls it broadcasted with `nil` closing tx via `MarkCoopBroadcasted`, reason being to keep the `listchannels` rpc stay consistent <- need revisit
						- `chanCloser` sets its state to `closeShutdownInitiated`
					- 3. `brontide` calls `link.DisableAdds` which disables the outgoing link, which forbids us sending out htlcs to the peer.
					- 4. `brontide` sends the `shutdown` message to the peer
			- rpcserver now listens to `htlcswitch.ChanClose.Updates` which sends signals when the channel closing process has updates.
```

This is just the first part where we send out the `shutdown` message, notice how we jump from `switch` to `brontide` to `link`, not to mention the following handling on peer's `shutdown` message and `closing_signed` messages...

File: htlcswitch/link.go [hunk 36]
```diff
@@ -364,13 +365,40 @@ type channelLink struct {
...
+}
+
+// flushHooksMap is a newtype wrapper around a map from FlushId's to hooks. It
+// is for implementation ergonomics only.
+type flushHookMap map[FlushHookID]func()
+
+// addGateState is a piece of channelLink state that tracks whether
+// we are allowed to add htlc's on either side of the link.
+type addGateState struct {
+	outgoingAddsEnabled atomic.Bool
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply htlcswitch/link.go]: Didn't have an opinion when I asked, purely out of curiosity.

File: htlcswitch/link.go (hunk 26 above)
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply htlcswitch/link.go:417]: yeah - but performance wise, I'd say use `atomic.Unit64` which is faster.

File: htlcswitch/link.go [hunk 37]
```diff
@@ -542,7 +632,122 @@ func (l *channelLink) WaitForShutdown() {
 func (l *channelLink) EligibleToForward() bool {
 	return l.channel.RemoteNextRevocation() != nil &&
 		l.ShortChanID() != hop.Source &&
-		l.isReestablished()
+		l.isReestablished() &&
+		!l.IsDraining(Outgoing)
+}
+
+func (l *channelLink) EnableAdds(linkDirection LinkDirection) error {
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply htlcswitch/link.go:633]: hmm don't think it helps tho. If I just jump into any struct, do I need to figure out if there's an interface for that struct and check the docs there? Plus what if there are multiple implementations of the same interface? I think it's ok to duplicate docs here, to save us time. Tho ideally the docs here should mention the implementation details.

File: htlcswitch/link.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:424]: Ah I think you're saying just do a bump allocator?

File: peer/brontide.go (hunk 35 above)
Comment (ProofOfKeags) [reply peer/brontide.go:3642]: After trying to rebundle the ChanCloser APIs I decided it was better to leave them separate for the time being.

Comment (Crypt-iQ) [reply peer/brontide.go:3642]: > I also generally oppose the philosophy of only implementing infrastructure when there's overwhelming demand for it

I'm a bit hesitant to this approach because we can end up with code that's generalized, but is only used by one caller.

> Wouldn't this defy the goals of "not putting shutdown logic in the link"?

I think this would be a lot slimmer than what I wrote in #6760, especially since the link isn't receiving/sending out `Shutdown` in the link code and instead uses a callback. It would have some shutdown logic (atomic booleans), but I think it would be minimal. It would also let us do away with the `switch` case in the peer code. Thoughts @Roasbeef ?

Comment (ProofOfKeags) [reply peer/brontide.go:3642]: > I'm a bit hesitant to this approach because we can end up with code that's generalized, but is only used by one caller.

That is the failure mode, yes. I guess I just don't see that as an issue in practice. In fact, generalization has benefits beyond de-duplicating code. The more general the API, the more restrictive the implementation and the more restrictive the implementation, the fewer opportunities there are for implementing it incorrectly. It simplifies the properties of the system. I'll admit that the drawback is that it often takes longer to come up with good generalizations and that effort may not be worth what you get in the short term.

Comment (ProofOfKeags) [reply peer/brontide.go:3642]: > I think this would be a lot slimmer than what I wrote in https://github.com/lightningnetwork/lnd/pull/6760, especially since the link isn't receiving/sending out Shutdown in the link code and instead uses a callback. It would have some shutdown logic (atomic booleans), but I think it would be minimal. It would also let us do away with the switch case in the peer code. Thoughts @Roasbeef ?

After reviewing [option_simple_close](https://github.com/lightning/bolts/pull/1096/files) it is clear to me that `shutdown` is fundamentally a link operation. Conceptually this seems obvious to me now, as any coop-close flow relies on clean channel state and regardless of what protocol you use for coming to agreement on a coop-close transaction, that state machine doesn't really kick off until the link shuts down. We can confirm this hypothesis by reviewing `option_simple_close` and see that it begins the same way:

1. exchange shutdown messages
2. wait for htlcs to drain
3. begin negotiation
4. ?????
5. profit

So if we want to ditch the lifecycle hook work in this PR I am OK with that so long as we acknowledge that `shutdown` truly is part of the Link's lifecycle. The more I think about it, the more I think this is the right thing to do irrespective of our opinion on lifecycle hooks and premature generalization. You could imagine a world with multiple choices for closing negotiation protocols and that you might select which one you want to use *in the shutdown message*. It wouldn't make sense to do so before the `shutdown` unless it was pre-negotiated up front.

`shutdown` is the happy-path end of the link's lifecycle, NOT the beginning of the closing protocol.

Thank you for comming to my TED Talk. 🤪

Comment (ProofOfKeags) [reply peer/brontide.go:3639]: 4 days later my conviction in the above has only grown. I think that we should make `shutdown` a message that the link processes, and pull it out of the `ChanCloser`

File: htlcswitch/link_test.go [hunk 38]
```diff
@@ -6894,3 +6895,216 @@ func TestChannelLinkShortFailureRelay(t *testing.T) {
...
+		close(hookCalled)
+	})
+
+	select {
+	case <-hookCalled:
+		t.Fatal("hook called prematurely")
+	case <-time.NewTimer(time.Second).C:
+	}
+
+	batchTicker <- time.Now()
```
Comment (Roasbeef) [inline htlcswitch/link_test.go:6908]: Send another ticket to confirm that things don't actually panic? (hook only called once)

File: htlcswitch/link_test.go [hunk 39]
```diff
@@ -6894,3 +6895,216 @@ func TestChannelLinkShortFailureRelay(t *testing.T) {
...
+	}
+
+	if err = start(); err != nil {
+		t.Fatal("could not start link")
+	}
+
+	hookCalled := make(chan struct{})
+	hid := aliceLink.OnCommitOnce(Outgoing, func() {
+		close(hookCalled)
+	}).UnsafeFromSome()
```
Comment (Roasbeef) [inline htlcswitch/link_test.go:6951]: Ah ok I see the usage here now, so far relegated to just test code.

Comment (Roasbeef) [reply htlcswitch/link_test.go:6951]: Or it could fail the test early if `None` at that point?

File: htlcswitch/link_test.go [hunk 40]
```diff
@@ -6894,3 +6895,216 @@ func TestChannelLinkShortFailureRelay(t *testing.T) {
 	default:
 	}
 }
+
+func TestLinkDrainApiDirectionIsolation(t *testing.T) {
```
Comment (Roasbeef) [inline htlcswitch/link_test.go:6811]: FWIW, we usually only add tests in commits where they pass, can make CI happier with cherry-picks n such.

File: lnwallet/chancloser/chancloser.go [hunk 41]
```diff
@@ -70,6 +71,11 @@ const (
 	// phase.
 	closeShutdownInitiated
 
+	// closeAwaitingFlush is the state that's transitioned to once both
```
Comment (Roasbeef) [inline lnwallet/chancloser/chancloser.go:74]: Could use some more detail in the commit body message, message says break up, but afaict this is new implementations of process close?

As mentioned before imo can just retain process close (accept `lnwire.Message`, or `lnwire.ChanCloser` (new interface similar to `LinkUpdater`)), which reduces the awareness of the peer dispatch code until we get some sort of message router sub-system going.

File: lnwallet/chancloser/chancloser.go (hunk 33 above)
Comment (Roasbeef) [reply lnwallet/chancloser/chancloser.go:529]: I think this can be addressed with a new intermediate state, like `chanFlushing`, we go to that after we recv or send shutdown, then afterwards, we continue execution from here. Either way correct that for the new flow, we need to split out some of the logic from `initChanShutdown`.

File: lnwallet/chancloser/chancloser.go [hunk 42]
```diff
@@ -470,6 +476,373 @@ func validateShutdownScript(disconnect func() error, upfrontScript,
...
+		return noShutdown, nil
+
+	default:
+		// Otherwise we are not in a state where we can accept this
+		// message.
+		return noShutdown, ErrInvalidState
+	}
+}
+
+func (c *ChanCloser) BeginNegotiation() (
```
Comment (Roasbeef) [inline lnwallet/chancloser/chancloser.go:610]: Missing `godoc` comments for these. Generally I think we can have the best of worlds if: all fo these new methods are made private, they're called from the existing `ProcessCloseMsg` dispatch func.

Comment (Roasbeef) [reply lnwallet/chancloser/chancloser.go:610]: Commit wise, I think if each commit takes a chunk from `ProcessCloseMsg` and refactors it into one of these new messages (vs adding the new func that may or may not contain new logic), then it'll be easier to review.

File: peer/brontide.go (hunk 35 above)
Comment (Roasbeef) [reply peer/brontide.go:3639]: >  I think that we should make shutdown a message that the link processes, and pull it out of the ChanCloser

FWIW with the new co-op close flow, `shutdown` can be sent again to reset state to RBF a new co-op close offer. In this state, the link no longer exists as it isn't loaded into the switch on connection establishment (channel state is now borked).

Comment (Roasbeef) [reply peer/brontide.go:3639]: I generally agree tho, that we can just literally move this into what used to be `ProcessCloseMsg` just hiding some of the internal message routing details from the peer itself, and this are mostly the same. 

Then this way it also doesn't need to understand the new dispatch routing for the new co-op close state machine (there're two new messages added).

File: lnwallet/chancloser/chancloser_test.go [hunk 43]
```diff
@@ -535,66 +528,81 @@ func TestTaprootFastClose(t *testing.T) {
...
 
 	// We'll now restore the original offer before passing it on to Alice.
-	bobOffer.FeeSatoshis = ogOffer
+	bobClosingSigned.FeeSatoshis = ogOffer
 
 	// If we use the original offer, then Alice should accept this message,
 	// and finalize the shutdown process. We expect a message here as Alice
 	// will echo back the final message.
-	aliceMsgs, closeFinished, err = aliceCloser.ProcessCloseMsg(bobMsgs[0])
+	oClosingSigned, err = aliceCloser.ReceiveClosingSigned(bobClosingSigned)
```
Comment (Roasbeef) [inline lnwallet/chancloser/chancloser_test.go:590]: Other info leakage here now is that the tests are made _slightly_ more white box. Could imagine that if `ProcessCloseMsg` is kept _mostly_ in place, then the new co-op close state machine can re-use the overall tests flow, even if the message dispatch is slightly diff. 

Ultimately, I think we're all heading closer to the idea of extracting the routing/dispatch logic from the peer, into something else with an additional layer of indirection. Right now the peer ends up knowing a lot about the channel life cycle (new channels, pending channels, etc, etc), when really all it needs to do is read off the wire, and figure out who/what to pass the message to then go back to the top.

Feels like we're sort of reaching diminishing returns with this part of the review conversation, and in the near-ish future, we can erect the more abstract message router/dispatcher which will once again hide more of the information from the peer.

File: htlcswitch/link.go [hunk 44]
```diff
@@ -545,7 +545,8 @@ func (l *channelLink) WaitForShutdown() {
 func (l *channelLink) EligibleToForward() bool {
 	return l.channel.RemoteNextRevocation() != nil &&
 		l.ShortChanID() != hop.Source &&
-		l.isReestablished()
+		l.isReestablished() &&
+		!l.IsDraining(Outgoing)
```
Comment (Roasbeef) [inline htlcswitch/link.go:637]: Has `IsDraining` been added at this point?

File: peer/brontide.go (hunk 34 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply peer/brontide.go:3590]: Makes sense, since after we mark the channel as borked, it won't ever be loaded into the link, so we can sorta fast forward past the flush state (or just accelerate by moving it to insta flushed).

File: peer/brontide.go [hunk 45]
```diff
@@ -3658,17 +3672,32 @@ func (p *Brontide) handleCloseMsg(msg *closeMsg) {
 		}
 
 		oShutdown.WhenSome(func(msg lnwire.Shutdown) {
-			p.queueMsg(&msg, nil)
+			// When we have a Shutdown to send, we defer it til the
+			// next time we send a CommitSig to remain spec
+			// compliant.
+			link.OnCommitOnce(htlcswitch.Outgoing, func() {
```
Comment (Roasbeef) [inline peer/brontide.go:3651]: IIUC, if the coast is already clear, then we can just send asap?

File: peer/brontide.go [hunk 46]
```diff
@@ -2967,17 +2967,6 @@ func (p *Brontide) handleLocalCloseReq(req *htlcswitch.ChanClose) {
 			}
 		}
 
-		// Optimistically try a link shutdown, erroring out if it
-		// failed.
```
Comment (Roasbeef) [inline peer/brontide.go:2971]: Commit body could use more detail here.

File: htlcswitch/link.go [hunk 47]
```diff
@@ -609,47 +701,107 @@ func (l *channelLink) IsDraining(linkDirection LinkDirection) bool {
...
-	// TODO(proofofkeags): Implement
-	return fn.None[CommitHookID]()
+	// If we want to run the hook once on the next fully committed state,
+	// and we don't currently need/owe a commitment, it means we don't have
+	// any pending updates and we can run the hook synchronously. If we call
+	// it syncrhonously we will not add it to the map at all.
+	runSync := direction == Outgoing && !l.channel.OweCommitment() ||
+		direction == Incoming && !l.channel.NeedCommitment()
+	if runSync {
+		hook()
```
Comment (Roasbeef) [inline htlcswitch/link.go:743]: Ah ok I think this answers by question about calling the hook early (eg: to send shutdown as the coast is clear). I think would be useful to mention in the `godoc` comment for the method/interface, namely that if we're in a state where we don't actually need to send a commit, the hook will be called early (denoted by `None` hook ID).

File: htlcswitch/link.go [hunk 48]
```diff
@@ -609,47 +701,107 @@ func (l *channelLink) IsDraining(linkDirection LinkDirection) bool {
...
-	// TODO(proofofkeags): Implement
-	return CommitHookID(0)
+func (l *channelLink) OnCommitMany(
+	direction LinkDirection, hook func(),
+) CommitHookID {
+
+	l.RWMutex.Lock()
+	defer l.RWMutex.Unlock()
+
+	var hm *hookMap
```
Comment (Roasbeef) [inline htlcswitch/link.go:769]: Doesn't actually need to be a pointer?

**Review by Roasbeef — CHANGES_REQUESTED** [review]
Excited to finally get this (and the related `stfu` logic) across the hump!

I think the only thing this is missing _functionality_ wise, is allow callers to _opt into_ this new behavior on the RPC interface. IMO, most wallets/apps already have the expectation that the call will either return nearly asap, or error out (link not clear). To avoid breaking applications, I think we should have an option that lets the caller opt into this new "close whenever possible mode" (which is something many routing nodes have wanted, and also how things are originally laid out in the spec). 

On the RPC/CLI layer, this would take the form of a new bool or enum callers can set, `LazyClose` or something like that perhaps. 

We can either add this in a new PR, or in this one. Slightly favor new PR just to not expand the scope of this one. Then in the new PR, we can also add itests that exercise the new options, eg:
  * Send an HTLC, hodl mode
  * Do lazy co-op close 
  * Settle the HTLC 
  * ??
  * Co-op close txn broadcast

File: htlcswitch/link_test.go (hunk 40 above)
Comment (ProofOfKeags) [reply htlcswitch/link_test.go:6811]: No TDD?

File: peer/brontide.go (hunk 45 above)
Comment (ProofOfKeags) [reply peer/brontide.go:3651]: OnCommitOnce will send synchronously if no commit_sig is owed.

File: lnwallet/chancloser/chancloser.go (hunk 33 above)
Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser.go:529]: This is how it is in this PR, no?

File: fn/option.go [hunk 49]
```diff
@@ -147,3 +147,12 @@ func (o Option[A]) Alt(o2 Option[A]) Option[A] {
 
 	return o2
 }
+
+// UnsafeFromSome can be used to extract the internal value. This will panic
+// if the value is None() though.
+func (o Option[A]) UnsafeFromSome() A {
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply fn/option.go:153]: You can recover this functionality a number of ways but I did this to make testing ergonomics a bit better

File: htlcswitch/interfaces.go [hunk 50]
```diff
@@ -138,8 +138,73 @@ type ChannelUpdateHandler interface {
...
+	EnableAdds(direction LinkDirection) error
+
+	// DiableAdds sets the ChannelUpdateHandler state to allow
+	// UpdateAddHtlc's in the specified direction. It returns an error if
+	// the state already disallowed those adds.
+	DisableAdds(direction LinkDirection) error
+
+	// IsDraining returns true when UpdateAddHtlc's are disabled in the
+	// direction of the argument.
+	IsDraining(direction LinkDirection) bool
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/interfaces.go:150]: I'll rename to flushing for consistency. Idk why I used two different terms lol

File: htlcswitch/link.go (hunk 48 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:769]: It does because we choose the value that goes in here off of the following block and the `alloc` method takes a pointer receiver. We don't want to call by value for `alloc` either.

File: fn/option.go [hunk 51]
```diff
@@ -147,3 +147,12 @@ func (o Option[A]) Alt(o2 Option[A]) Option[A] {
 
 	return o2
 }
+
+// UnsafeFromSome can be used to extract the internal value. This will panic
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply fn/option.go:151]: Ah that explains so much

File: lnwallet/chancloser/chancloser.go (hunk 41 above)
Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser.go:74]: It's not a new implementation, really. However, I did change the return type substantially to more tightly circumscribe what comes out of each stage.

We can rebundle ReceiveShutdown and ReceiveClosingSigned if we want and I did try that but there's two downsides:

First, there's no way to escape needing to call `BeginNegotiation` when the channel finishes flushing. We used to be able to do this synchronously between the stages because we could assume a clean channel state since we made that a precondition of kicking off this process. We can't anymore.

Second, if we rebundle them, it means that we can't quite as tightly bound the return type as we do here. We instead would need to return a pair of `Option[Shutdown]` and `Option[ClosingSigned]`. If we were to go as far as we did before and inject those types into the larger `[]lnwire.Message` type, then we would need to scrutinize those values in order to insert them into their proper lifecycle hooks (in the case of `Shutdown` it needs to be queued `OnCommitOnce(Outgoing)`).

I did actually write this code out but I removed it because it doesn't actually fix your concern around making this process opaque to the Brontide, and it additionally costs us precision on the actual state machine traversal functions. If you want I can add a commit to the end of this PR demoing what I tried for this and you can take a look at it. If you still prefer it I can pull that work into the main body of this PR in the relevant places, however, I doubt once you see it you'll want to go that route.

File: lnwallet/chancloser/chancloser.go (hunk 33 above)
Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser.go:529]: JK It's not. I'll address.

File: lnwallet/chancloser/chancloser.go (hunk 42 above)
Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser.go:610]: > all fo these new methods are made private, they're called from the existing ProcessCloseMsg dispatch func.

Which CloseMsg corresponds to `BeginNegotiation`?

File: htlcswitch/link.go (hunk 27 above)
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:2608]: Actually in this use case it matters that we do it after. It is a protocol violation to send `Shutdown` while we owe a `CommitSig`, so if we move this to be before the CommitSig is sent than using it how we are right now won't work.

File: lnwallet/chancloser/chancloser.go (hunk 41 above)
Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser.go:74]: Ok theres one final problem with rebundling that I believe is fatal. We can't escape inspecting the close message type because we need to decide whether or not to register the flush hook only if the message type is a shutdown. If we receive a valid `closing_signed` then we are already flushed, and shouldn't be flushing again.

File: peer/brontide.go (hunk 35 above)
Comment (ProofOfKeags) [reply peer/brontide.go:3637]: Ok theres one final problem with rebundling that I believe is fatal. We can't escape inspecting the close message type because we need to decide whether or not to register the flush hook only if the message type is a shutdown. If we receive a valid closing_signed then we are already flushed, and shouldn't be flushing again.

File: lnwallet/chancloser/chancloser.go (hunk 41 above)
Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser.go:74]: Ok theres one final problem with rebundling that I believe is fatal. We can't escape inspecting the close message type because we need to decide whether or not to register the flush hook only if the message type is a shutdown. If we receive a valid closing_signed then we are already flushed, and shouldn't be flushing again.

Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser.go:74]: See [this](https://github.com/lightningnetwork/lnd/pull/8167/files#r1427456093) for why I think we definitively cannot rebundle.

File: htlcswitch/link_test.go (hunk 39 above)
Comment (ProofOfKeags) [reply htlcswitch/link_test.go:6955]: The ergonomics were worse that way.

File: htlcswitch/link.go [hunk 52]
```diff
@@ -1812,6 +1812,33 @@ func (l *channelLink) handleUpstreamMsg(msg lnwire.Message) {
...
+			// already sent a CommitSig we haven't received yet,
+			// channel state will be re-synchronized with a
+			// ChannelReestablish message upon reconnection and the
+			// protocol state that caused us to flush the link will
+			// be rolled back. In the event that there was some
+			// non-deterministic behavior in the remote that caused
+			// them to violate the protocol, we have a decent shot
+			// at correcting it this way, since reconnecting will
+			// put us in the cleanest possible state to try again.
+			l.fail(
```
Comment (Crypt-iQ) [inline htlcswitch/link.go:1984]: This may be hit erroneously for lnd nodes due to a race:

- counterparty sends `update_add_htlc`, `commit_sig`, `shutdown` in that order
- `update_add_htlc` & `commit_sig` added to link's mailbox
- `shutdown` is processed in `handleCloseMsg` and calls `link.DisableAdds(htlcswitch.Incoming)`
- If `link.DisableAdds` is run before the link can pull from the mailbox, the htlc will cause this section to be hit

The issue here boils down to enforcing the same message ordering that was received over the wire.

File: htlcswitch/link.go [hunk 53]
```diff
@@ -638,24 +748,66 @@ func (l *channelLink) RemoveFlushHook(FlushHookID) error {
...
-	// TODO(proofofkeags): Implement
-	return fn.None[CommitHookID]()
+	// If we want to run the hook once on the next fully committed state,
+	// and we don't currently need/owe a commitment, it means we don't have
+	// any pending updates and we can run the hook synchronously. If we call
+	// it syncrhonously we will not add it to the map at all.
+	runSync := direction == Outgoing && !l.channel.OweCommitment() ||
+		direction == Incoming && !l.channel.NeedCommitment()
+	if runSync {
+		hook()
```
Comment (Crypt-iQ) [inline htlcswitch/link.go:749]: I don't think this can be run synchronously because the callback is not invoked from the `htlcManager` goroutine.  If the link sends an htlc after the value of `runSync` is set but before `hook()` is run, we'll end up violating the protocol

File: htlcswitch/link.go [hunk 54]
```diff
@@ -545,7 +545,8 @@ func (l *channelLink) WaitForShutdown() {
 func (l *channelLink) EligibleToForward() bool {
 	return l.channel.RemoteNextRevocation() != nil &&
 		l.ShortChanID() != hop.Source &&
-		l.isReestablished()
+		l.isReestablished() &&
+		!l.IsFlushing(Outgoing)
```
Comment (Crypt-iQ) [inline htlcswitch/link.go:637]: This will prevent the link from sending `update_fee` after we've sent `shutdown` since `updateChannelFee` calls `EligibleToForward`.  Sending `update_fee` during the coop close process was brought up in prior spec meetings since you may want to adjust the commitment feerate in case you need to force close

File: lnwallet/chancloser/chancloser.go [hunk 55]
```diff
@@ -822,24 +837,20 @@ func (c *ChanCloser) ProcessCloseMsg(msg lnwire.Message) ([]lnwire.Message,
...
 
-		// There's no more to do as both sides should have already broadcast
-		// the closing transaction at this state.
-		return nil, true, nil
+		// There's no more to do as both sides should have already
+		// broadcast the closing transaction at this state.
+		return noClosing, nil
 
-	// Otherwise, we're in an unknown state, and can't proceed.
 	default:
```
Comment (Crypt-iQ) [inline lnwallet/chancloser/chancloser.go:852]: I think we need to cache the peer's `closing_signed` because if they send us a `revoke_and_ack` followed by `closing_signed`, we might call `ProcessClosingSigned` before the link calls `BeginNegotiation`. Then we'd hit this default case and error out

File: peer/brontide.go [hunk 56]
```diff
@@ -3658,17 +3670,32 @@ func (p *Brontide) handleCloseMsg(msg *closeMsg) {
...
-		oClosingSigned, err := chanCloser.BeginNegotiation()
-		if err != nil {
-			handleErr(err)
-			return
-		}
+		// Now we register a flush hook to advance the ChanCloser and
+		// possibly send out a ClosingSigned when the link finishes
+		// draining.
+		link.OnFlushedOnce(func() {
+			p.cfg.Switch.RemoveLink(msg.cid)
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply peer/brontide.go:3662]: Maybe this is dumb, but like, couldn't we also just launch a goroutine to call the `RemoveLink`?

File: htlcswitch/link.go (hunk 54 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:637]: Seems like `update_fee` shouldn't be gated on "EligibleToForward"... I'll take a look at how we use it in that way and develop a different measurement for update_fee

File: htlcswitch/link.go (hunk 53 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:749]: What if we `RLock` the link here?

**Review by yyforyongyu — COMMENTED** [review]
Saw discussions about the architecture and I'd like to share some of my notes.

```
┌─────────────────┐┌──────────────┐┌────────────────┐┌──────────┐
│ funding manager ││ channel link ││ channel closer ││ gossiper │
└─────────────────┘└──────────────┘└────────────────┘└──────────┘
│                           peer conn                           │
└───────────────────────────────────────────────────────────────┘
│                          noise conn                           │
└───────────────────────────────────────────────────────────────┘
```

At the bottom layer, noise conn is managed by `PeerConnManager` and is still [WIP](https://github.com/lightningnetwork/lnd/pull/7283). Its responsibility is to create, maintain, or destroy the noise connection.

One layer up is the peer conn which is managed by `Brontide`, it handles all the wire messages, and uses the following messages to update its state:
- `init`
- `error` and `warning`
- `ping` and `pong`

The rest of the messages are then forwarded to other subsystems:
- channel open related messages are handled by `FundingManager`
- channel update related messages are handled by `Switch` via `chanStream`
- channel close related messages are handled by `ChanCloser`
- channel reestablishment is handled by `Switch`, which IMO should be handled by a dedicated subservice
- gossip related messages are handled by `AuthGossiper` via `discStream`

That's roughly the current architecture. The subsystems are not completely independent from each other - there's a similar issue before, as described in #7401, there was a friction between funding manager and channel link, which was resolved by tracking pending channels in `Brontide`. In other words, we use `Brontide` as the coordinator to remove the frictions among subsystems.

After reading the comments I got the impression that we want to have this architecture,

```
┌─────────────────────────────────────────────────────┐
│┌─────────────────┐┌──────────────┐┌────────────────┐│
││ funding manager ││ channel link ││ channel closer ││
│└─────────────────┘└──────────────┘└────────────────┘│
│                                                     │┌──────────┐
│                 link lifecycle manager              ││ gossiper │
└─────────────────────────────────────────────────────┘└──────────┘
│                            peer conn                            │
└─────────────────────────────────────────────────────────────────┘
│                           noise conn                            │
└─────────────────────────────────────────────────────────────────┘
```

Though I'd propose to change the specs so we gossip over paid connections to mitigate spamming or DoS and eventually have an architecture as such,

```
┌────────────────────────────────────────────────────┐
│                  gossip over link                  │
└────────────────────────────────────────────────────┘
│┌─────────────────┐┌─────────────┐┌────────────────┐│
││ funding manager ││ htlc switch ││ channel closer ││
││   create link   ││ update link ││   delete link  ││
│└─────────────────┘└─────────────┘└────────────────┘│
│                       link conn                    │
└────────────────────────────────────────────────────┘
│                       peer conn                    │
└────────────────────────────────────────────────────┘
│                      noise conn                    │
└────────────────────────────────────────────────────┘
```

Either way, if we decide the let link handle the shutdown, we should also let it handle the creation. We should either move everything to a conceptual link lifecycle, or keep using `Brontide` as a coordinator to remove the frictions, **but not a mix of both approaches**. In addition, my instinct is that the frictions are better handled by using a link lifecycle - future PRs tho.

Back to this PR, my main question is whether we need to differentiate the direction of the link as it causes us to expose the details of link lifecycle. If not, things can be much easier as we can just send a teardown signal to link and let channel link handles finishing its last commit dance, something like,
1. `Brontide` receives a `shutdown` message or user calls `closechannel`, which `Brontide` sends a teardown request to `ChannelLink`, and wait for response.
2. `ChannelLink` finishes its commit dance and respond to `Brontide`'s request.
3. `Brontide` advises `ChanCloser` to continue its process.

Also we should remove this check to fix #6039
https://github.com/lightningnetwork/lnd/blob/4d8fa349ca405a42548717c17cc689e6612ff37a/rpcserver.go#L2634

File: peer/brontide.go (hunk 56 above)
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply peer/brontide.go]: I think launching a goroutine here should also work

File: htlcswitch/link.go [hunk 57]
```diff
@@ -538,15 +627,186 @@ func (l *channelLink) WaitForShutdown() {
...
+	return l.isIncomingAddBlocked.Load()
+}
+
+// OnFlushedOnce is a method that adds a hook to be called the next time the
+// channel state reaches zero htlcs. This hook will only ever be called once.
+// This function returns a FlushHookID that can be used to preemptively remove
+// this hook. If the channel state is already flushed -- no HTLCs and no
+// commitments owed by either party -- then we will call this hook synchronously
+// and will not return a FlushHookID.
+func (l *channelLink) OnFlushedOnce(hook func()) fn.Option[FlushHookID] {
```
Comment (Crypt-iQ) [inline htlcswitch/link.go:702]: It's possible that the `hook` function here is never called:

- goroutine 1: `OnFlushedOnce` called and `IsChannelClean` returns false
- goroutine 2: The link receives the final `commit_sig` / `revoke_and_ack` that makes the channel clean in `handleUpstreamMsg`
- goroutine 2: `flushHooks.invoke()` is called, but there are no hooks yet
- goroutine 1: `flushHooks.alloc` is called, but no goroutine will call `flushHooks.invoke()` anymore since if the peer is following the spec, they won't send any more messages

File: htlcswitch/link.go [hunk 58]
```diff
@@ -538,15 +627,186 @@ func (l *channelLink) WaitForShutdown() {
...
+	return errors.New("could not remove flush hook: not found")
+}
+
+// OnCommitOnce adds a hook that will be called the next time a CommitSig
+// message is sent in the argument's LinkDirection. This hook will only ever be
+// called once. This function returns a CommitHookID that can be used to
+// preemptively remove this hook. If no CommitSig is owed in the argument's
+// LinkDirection, then we will call this hook synchronously and will not return
+// a CommitHookID.
+func (l *channelLink) OnCommitOnce(
```
Comment (Crypt-iQ) [inline htlcswitch/link.go:746]: Similar to `OnCommitOnce`, the `hook` function may never get called:

- goroutine 1: `OnCommitOnce` called, `OweCommitment` is true so `runSync` is false
- goroutine 2: we send `commit_sig` covering their updates on their commitment tx and come to a clean state, but there are no `outgoingCommitHooks` so the `invoke` call is a no-op
- goroutine 1: `outgoingCommitHooks.alloc` is called
- goroutine 1: `OnFlushedOnce` called and since the channel is clean, `hook` is run

In this case, `closing_signed` is sent without us sending a `shutdown`

File: htlcswitch/interfaces.go [hunk 59]
```diff
@@ -138,8 +139,80 @@ type ChannelUpdateHandler interface {
...
+// one of these by hand, nor should you try.
+type FlushHookID uint64
+
+// LinkDirection is used to query and change any link state on a per-direction
+// basis.
+type LinkDirection bool
+
+const (
+	// Incoming is the direction from the remote peer to our node.
+	Incoming LinkDirection = false
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/interfaces.go:205]: I'd prefer we didn't. We have an 80col limit on code which makes things pretty tight compared to any other ecosystem I've worked in. Secondly the type is named LinkDirection and you can see that info on hover in any IDE/LSP.

File: htlcswitch/interfaces.go [hunk 60]
```diff
@@ -138,8 +139,80 @@ type ChannelUpdateHandler interface {
...
+type CommitHookID uint64
+
+// FlushHookID is a value that is used to uniquely identify hooks in the
+// ChannelUpdateHandler's flush lifecycle. You should never need to construct
+// one of these by hand, nor should you try.
+type FlushHookID uint64
+
+// LinkDirection is used to query and change any link state on a per-direction
+// basis.
+type LinkDirection bool
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/interfaces.go:201]: We can use anything we want. The representation is supposed to be opaque. It's the smallest type that would work which is the heuristic I usually use. Further, there fundamentally isn't a good concept of a "third" direction and `bool` is the canonical 2-point type.

File: htlcswitch/link.go (hunk 57 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:702]: Indeed. I'll move the Lock call to the beginning

File: htlcswitch/link_test.go [hunk 61]
```diff
@@ -6894,3 +6895,220 @@ func TestChannelLinkShortFailureRelay(t *testing.T) {
...
 }
+
+func TestLinkFlushApiDirectionIsolation(t *testing.T) {
+	aliceLink, _, _, _, _, _ :=
+		newSingleLinkTestHarness(
+			t, 5*btcutil.SatoshiPerBitcoin,
+			1*btcutil.SatoshiPerBitcoin,
+		)
+
+	for i := 0; i < 10; i++ {
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link_test.go:6818]: Yep. It was a poor-mans property test since all I needed was a coin flip

File: htlcswitch/link_test.go [hunk 62]
```diff
@@ -6894,3 +6895,220 @@ func TestChannelLinkShortFailureRelay(t *testing.T) {
...
+			//nolint:errcheck
+			aliceLink.EnableAdds(Outgoing)
+		} else {
+			//nolint:errcheck
+			aliceLink.DisableAdds(Outgoing)
+		}
+		require.False(t, aliceLink.IsFlushing(Incoming))
+	}
+
+	//nolint:errcheck
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link_test.go:6829]: No because if it errors we still want to keep going. The "error" case here is just the system telling us that there was a noop state change. Sometimes we care about that, sometimes we don't. Here we don't.

File: htlcswitch/link_test.go (hunk 39 above)
Comment (ProofOfKeags) [reply htlcswitch/link_test.go:6955]: It's not just about the assertion. It's about getting our hands on the value inside Some as well if it's not None so we can continue with the rest of the test.

File: peer/brontide.go [hunk 63]
```diff
@@ -3648,18 +3643,52 @@ func (p *Brontide) handleCloseMsg(msg *closeMsg) {
...
+			handleErr(err)
+			return
+		}
+
+		oClosingSigned.WhenSome(func(msg lnwire.ClosingSigned) {
+			p.queueMsg(&msg, nil)
+		})
+
+	default:
+		panic("impossible closeMsg type")
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply peer/brontide.go:3687]: I did this to make it very clear if we implement a "closeMsg" type that we don't handle in this switch case. I actually think the aggressiveness of this blowup will reduce production vulnerabilities not increase them. Things that should be **structurally** impossible should have aggressive blowups so we catch them immediately. Crashes are the most obvious failures and the ones least likely to slip by our testing. If we do something other than panic, then the "impossibility" (read: core assumption we make about the system) silently breaks down and causes other bugs. Every bug has the potential to be a security issue and so doing something less aggressive doesn't actually improve the situation. It makes it worse because it makes it harder to notice.

Ordinarily I'd solve this by having a proper message sum-type hierarchy so we can rule out any broken assumptions at compile time but since go doesn't really support sum types we don't have that option. Additionally the switch statement in go isn't capable of informing us of exhaustion, which would be a dramatic improvement over this approach.

File: htlcswitch/link.go (hunk 52 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:1997]: Where we landed on this is that since we just disconnect, the cost of this race condition being hit is not disastrous. Unless we are prepared to synchronize all message orderings across state machines in this PR, which, while a good idea, is likely beyond the scope of what we want to do here, I think we can leave this as is

File: htlcswitch/link.go (hunk 53 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:760]: We currently Lock link state for this so I think we're OK.

File: htlcswitch/link_test.go [hunk 64]
```diff
@@ -6894,3 +6895,220 @@ func TestChannelLinkShortFailureRelay(t *testing.T) {
...
+	ctx.sendHtlcBobToAlice(htlc)
+
+	// A <- sig -- B
+	ctx.sendCommitSigBobToAlice(1)
+
+	// A -- rev -> B
+	ctx.receiveRevAndAckAliceToBob()
+
+	// Register flush hook
+	aliceLink.OnFlushedOnce(func() {
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link_test.go:7177]: Then it will run synchronously.

**Comment by ProofOfKeags** [comment]
> In other words, we use Brontide as the coordinator to remove the frictions among subsystems.

This confirms my observation and assessment.

> After reading the comments I got the impression that we want to have this architecture,

This is exactly what I am suggesting.

> Though I'd propose to change the specs so we gossip over paid connections to mitigate spamming or DoS and eventually have an architecture as such,

How do new nodes bootstrap network state if gossip requires a channel relationship?

> Either way, if we decide the let link handle the shutdown, we should also let it handle the creation. 

Absolutely. The symmetry here makes sense to me.

> We should either move everything to a conceptual link lifecycle, or keep using Brontide as a coordinator to remove the frictions, but not a mix of both approaches. In addition, my instinct is that the frictions are better handled by using a link lifecycle - future PRs tho.

Yes yes yes.

> Back to this PR, my main question is whether we need to differentiate the direction of the link as it causes us to expose the details of link lifecycle. If not, things can be much easier as we can just send a teardown signal to link and let channel link handles finishing its last commit dance, something like,

If we go this route we have to be careful not to block the Brontide's control flow while it waits. Further, just because we have sent out the commitment transaction and can safely send shutdown doesn't mean that the link has been torn down. For instance, if we are the initiators then we can rather quickly get to a point where we can send shutdown but will have to wait a while longer before we can receive it. Maybe this is OK, but I think that allowing for hooks is the cleanest way to zip multiple subsystems together when we do have certain synchronization requirements between them. We can pack all these things behind the Lifecycle interface so as not to leak it more broadly, but as long as there is required coordination between subsystems, I don't think there is a way around leaking some of the internals, hooks or otherwise.

Further, this only solves the question with regards to syncing `Shutdown` with `CommitSig`. We still also have to sync `ClosingSigned` with an empty HTLC state.

I understand the desire to "not leak implementation details" but part of the external view of the channel is this notion of the fact that it is a duplex channel. At some level that state will need to be exposed. I agree that exposing it all the way to the Brontide seems sus, but the state machine has isolated requirements for either direction depending on link state, so whatever coordinates that state with the messages that need to be sent is going to need to know about it.

**Comment by Roasbeef** [comment]
Catch up with this PR a bit now, feels like we're starting to reach diminishing returns re review, wherein the main converations now are related to broader philosophy re responsibility and architecture design including, but beyond the scope of the `chancloser`. I don't think we'll resolve all of that here, nor do we need to. I think the discussion has been fruitful so far, as we're starting to zoom in on a shared ideal of the "right" architecture here. We also shouldn't lose sight w.r.t the concrete improvement of finally giving users a proper async way to close out channels, whereas rn they need to have a script that polls in the background to close until it succeeds.

With that said, I propose the following:
  * Commit to not expanding the scope of this PR further, to address the remaining concrete implementation or functionality issues that may or may not remain.  
  * Make a new PR to handle the RPC level changes. Today we'll still auto bail out if there're active HTLCs on the commitment transaction: https://github.com/lightningnetwork/lnd/blob/9afe1b72dcc845b275af8d22036f2fa4c484eeea/rpcserver.go#L2646-L2653. My rough proposal here is add a new `--async` flag which conditionally skips the above check. The default would be false, which doesn't change the behavior for users _initiating_ a co-op close, but will still do the "right thing" when the remote party initiates a co-op close. 
  * Re the race condition discussed (note that this is second hand knowledge on my part), I think we can make a new issue to track this. IIUC, we may be able to solve this by adding a check when we read off the mailbox to see if we sent a shutdown or not, and if so, then we cancel back in the mailbox to avoid violating the spec by sending a commit sig.

**Comment by ProofOfKeags** [comment]
> My rough proposal here is add a new --async flag which conditionally skips the above check. The default would be false, which doesn't change the behavior for users initiating a co-op close, but will still do the "right thing" when the remote party initiates a co-op close.

I have already added a `--no_wait` flag (easier to understand as a user imo), and removed the active htlc check in [fd2b7d2](https://github.com/lightningnetwork/lnd/pull/8167/commits/fd2b7d204427fb82c34ecc4aff7c6fab1f967ead). If this is not supplied we will block until htlcs have flushed and completed the negotiation process.

**Review by yyforyongyu — COMMENTED** [review]
Very close! My major comment is since now that the bug is fixed, we can finally remove the hacks in our itests:
https://github.com/lightningnetwork/lnd/blob/a2986f96daab5cade34a6902e2fd94b7f2396d15/lntest/harness.go#L1222

There are quite a few of them, could you do a search of "`link failed to shutdown` if we close the channel" and remove all the `time.Sleep` to see if the tests still pass?

File: lnwallet/chancloser/chancloser_test.go [hunk 65]
```diff
@@ -535,66 +528,81 @@ func TestTaprootFastClose(t *testing.T) {
 
 	// Bob will then process this message. As he's the responder, he should
 	// only send the shutdown message back to Alice.
-	bobMsgs, closeFinished, err := bobCloser.ProcessCloseMsg(msg)
+	oShutdown, err := bobCloser.ReceiveShutdown(*msg)
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply lnwallet/chancloser/chancloser_test.go:531]: Option, to indicate we aren't sure of its presence at this point.

File: htlcswitch/link_test.go [hunk 66]
```diff
@@ -6894,3 +6895,220 @@ func TestChannelLinkShortFailureRelay(t *testing.T) {
...
+	}
+}
+
+func TestLinkOutgoingCommitHooksCalled(t *testing.T) {
+	aliceLink, _, batchTicker, start, _, err :=
+		newSingleLinkTestHarness(
+			t, 5*btcutil.SatoshiPerBitcoin,
+			btcutil.SatoshiPerBitcoin,
+		)
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link_test.go:7033]: Oops. 😅

File: itest/lnd_coop_close_with_htlcs_test.go [hunk 67]
```diff
@@ -0,0 +1,91 @@
...
+
+	ht.AssertInvoiceState(invoiceStream, lnrpc.Invoice_OPEN)
+
+	req := &routerrpc.SendPaymentRequest{
+		PaymentRequest: resp.PaymentRequest,
+		TimeoutSeconds: 60,
+		FeeLimitSat:    1000000,
+	}
+	ht.SendPaymentAndAssertStatus(bob, req, lnrpc.Payment_IN_FLIGHT)
+	err := wait.NoError(func() error {
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply itest/lnd_coop_close_with_htlcs_test.go:47]: ht.AssertNumActiveHtlcs will *wait* for that state to occur?

File: peer/brontide.go [hunk 68]
```diff
@@ -3648,18 +3628,83 @@ func (p *Brontide) handleCloseMsg(msg *closeMsg) {
...
+
+		oShutdown.WhenSome(func(msg lnwire.Shutdown) {
+			// if the link is nil it means we can immediately queue
+			// the Shutdown message since we don't have to wait for
+			// commitment transaction synchronization
+			if link == nil {
+				p.queueMsg(typed, nil)
+				return
+			}
+			// When we have a Shutdown to send, we defer it til the
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply peer/brontide.go:3653]: Huh... [TIL](https://www.merriam-webster.com/dictionary/%27til) that "till" is a legitimate synonym to "until" and that "til" is far newer abbreviated form of "until"

File: peer/brontide.go (hunk 63 above)
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply peer/brontide.go:3702]: I'm happy to do this if we can make our test harnesses fail on Critical logs.

**Comment by ProofOfKeags** [comment]
> @yyforyongyu There are quite a few of them, could you do a search of "link failed to shutdown if we close the channel" and remove all the time.Sleep to see if the tests still pass?

7f454383e3d748501dfe88d08bf73e469364d668 removes them all. Locally testing the specific test case ones reveals they all work now (yay further confirmation that this does what it's supposed to). We'll see if the harness wide one works in the CI pipeline.

**Review by Crypt-iQ — COMMENTED** [review]
Almost there! A follow up PR should handle the reestablish case. It should get into 0.18.0 especially because of the disconnect issue in this PR. Otherwise, users will have to force close the channel

File: htlcswitch/link.go (hunk 53 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:760]: We need it though. If we are already in a clean commitment state, and we remove this, it will result in having to wait for our *next* commitment to get sent out. This can result in protocol violations. If you find that the mutex won't suffice we can change this to a different sync model wherein we accept the hooks over channels and then they either get immediately executed in the htlcManager thread or they get added to the map for deferred execution.

File: htlcswitch/link.go (hunk 52 above)
Comment (ProofOfKeags) [reply htlcswitch/link.go:1997]: I'll add an issue and ref it in a comment.

**Comment by ProofOfKeags** [comment]
> Almost there! A follow up PR should handle the reestablish case. It should get into 0.18.0 especially because of the disconnect issue in this PR. Otherwise, users will have to force close the channel

What needs to be done here? I am not sure I see the force-closure requirement or what needs to be done in a reestablish that would fix it.

File: htlcswitch/link.go [hunk 69]
```diff
@@ -376,10 +376,99 @@ type channelLink struct {
 	// UpdateAddHTLC.
 	isIncomingAddBlocked atomic.Bool
 
+	// flushHooks is a hookMap that is triggered when we reach a channel
+	// state with no live HTLCs.
+	flushHooks hookMap
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply htlcswitch/link.go:370]: I don't mind doing that, but it does make me wonder why we have the link mutex at all. I figured it would be to handle these exact cases where we wanted to modify rows on this structure. However, you mentioned it isn't locked during changes to the underlying LightningChannel either.

File: rpcserver.go [hunk 70]
```diff
@@ -2690,6 +2682,12 @@ func (r *rpcServer) CloseChannel(in *lnrpc.CloseChannelRequest,
 			maxFee, deliveryScript,
 		)
 	}
+
+	// If the user doesn't want to wait for the txid to come back then we
+	// will exit early.
+	if in.NoWait {
+		return nil
```
[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply rpcserver.go:2689]: The idea is to NOT send updates on the closing client if they specify no_wait. Can you clarify what you mean here?

[the remark this answers is not in the document]
Comment (yyforyongyu) [reply rpcserver.go:2689]: yeah i don't think that's a good idea tho - I think the callers would want to know the closing status of a given channel, which is already async as they just listen to the updates sent from the closing client. If not, they can just bail out. Then this `no_wait` flag enhances the experience of closing channels, after user calls `closechannel`, it  returns immediately. 
```go
// By using the flag, it can now return immediately.
closeClient := alice.RPC.CloseChannel(...)

// User can then still wait for the closing result.
ht.ReceiveCloseChannelUpdate(closeClient)

// Or decide to not wait and continue.
...
```

[the remark this answers is not in the document]
Comment (ProofOfKeags) [reply rpcserver.go]: I've adjusted this to send an empty update instantly to allow the CLI and REST interfaces to fast return.

File: rpcserver.go [hunk 71]
```diff
@@ -2690,6 +2682,19 @@ func (r *rpcServer) CloseChannel(in *lnrpc.CloseChannelRequest,
 			maxFee, deliveryScript,
 		)
 	}
+
+	// If the user doesn't want to wait for the txid to come back then we
+	// will exit early.
+	if in.NoWait {
```
Comment (yyforyongyu) [inline rpcserver.go:2688]: What I meant [here](https://github.com/lightningnetwork/lnd/pull/8167#discussion_r1458569283) was to put the below `out` loop into a goroutine and then we can just exit here - I don't think sending an empty update is gonna help, the user still wants the results being sent, just in an async manner.

Comment (ProofOfKeags) [reply rpcserver.go:2688]: I think this works because it makes it such that the initial instantaneous response causes the cli and json clients to detach.

Comment (yyforyongyu) [reply rpcserver.go:2688]: but then how can a user get updates about the channel closure in that close client?

File: htlcswitch/link.go [hunk 72]
```diff
@@ -538,15 +599,91 @@ func (l *channelLink) WaitForShutdown() {
...
+	}
+
+	return l.isIncomingAddBlocked.Load()
+}
+
+// OnFlushedOnce adds a hook that will be called the next time the channel
+// state reaches zero htlcs. This hook will only ever be called once. If the
+// channel state already has zero htlcs, then this will be called immediately.
+func (l *channelLink) OnFlushedOnce(hook func()) {
+	l.flushHooks.newTransients <- hook
```
Comment (Crypt-iQ) [inline htlcswitch/link.go:672]: Needs to `select` and have a case for the link quitting

File: htlcswitch/link.go [hunk 73]
```diff
@@ -538,15 +599,91 @@ func (l *channelLink) WaitForShutdown() {
...
+}
+
+// OnCommitOnce adds a hook that will be called the next time a CommitSig
+// message is sent in the argument's LinkDirection. This hook will only ever be
+// called once. If no CommitSig is owed in the argument's LinkDirection, then
+// we will call this hook be run immediately.
+func (l *channelLink) OnCommitOnce(direction LinkDirection, hook func()) {
```
Comment (Crypt-iQ) [inline htlcswitch/link.go:679]: Also needs to `select` and have a case for the link quit

File: rpcserver.go (hunk 71 above)
Comment (Crypt-iQ) [reply rpcserver.go:2688]: Won't the stream exit if we return here though?

File: rpcserver.go [hunk 74]
```diff
@@ -2643,14 +2643,6 @@ func (r *rpcServer) CloseChannel(in *lnrpc.CloseChannelRequest,
 		rpcsLog.Debugf("Target sat/kw for closing transaction: %v",
 			int64(feeRate))
 
-		// Before we attempt the cooperative channel closure, we'll
-		// examine the channel to ensure that it doesn't have a
-		// lingering HTLC.
-		if len(channel.ActiveHtlcs()) != 0 {
```
Comment (Crypt-iQ) [inline rpcserver.go:2649]: Per [this comment](https://github.com/lightningnetwork/lnd/pull/8167#pullrequestreview-1780701979) it seems like the code should instead optionally check `len(ActiveHtlcs()) == 0`. That was at least my interpretation of what the `NoWait` flag should be

**Review by Crypt-iQ — COMMENTED** [review]
Will approve once the rpcserver discussion is resolved

File: rpcserver.go (hunk 71 above)
Comment (yyforyongyu) [reply rpcserver.go:2688]: was thinking something like this,
```diff
diff --git a/rpcserver.go b/rpcserver.go
index 08e7e1876..1806a5a41 100644
--- a/rpcserver.go
+++ b/rpcserver.go
@@ -2683,56 +2683,62 @@ func (r *rpcServer) CloseChannel(in *lnrpc.CloseChannelRequest,
 		)
 	}
 
-	// If the user doesn't want to wait for the txid to come back then we
-	// will exit early.
-	if in.NoWait {
-		rpcsLog.Tracef("[closechannel] sending instant update")
-		if err := updateStream.Send(
-			&lnrpc.CloseStatusUpdate{
-				Update: &lnrpc.CloseStatusUpdate_CloseInstant{},
-			},
-		); err != nil {
-			return err
-		}
-	}
-out:
-	for {
-		select {
-		case err := <-errChan:
-			rpcsLog.Errorf("[closechannel] unable to close "+
-				"ChannelPoint(%v): %v", chanPoint, err)
-			return err
-		case closingUpdate := <-updateChan:
-			rpcClosingUpdate, err := createRPCCloseUpdate(
-				closingUpdate,
-			)
-			if err != nil {
+	// sendUpdate is a helper closure...
+	sendUpdate := func() error {
+		for {
+			select {
+			case err := <-errChan:
+				rpcsLog.Errorf("[closechannel] unable to "+
+					"close ChannelPoint(%v): %v", chanPoint,
+					err)
+
 				return err
-			}
 
-			rpcsLog.Tracef("[closechannel] sending update: %v",
-				rpcClosingUpdate)
+			case closingUpdate := <-updateChan:
+				rpcClosingUpdate, err := createRPCCloseUpdate(
+					closingUpdate,
+				)
+				if err != nil {
+					return err
+				}
 
-			if err := updateStream.Send(rpcClosingUpdate); err != nil {
-				return err
-			}
+				rpcsLog.Tracef("[closechannel] sending "+
+					"update: %v", rpcClosingUpdate)
 
-			// If a final channel closing updates is being sent,
-			// then we can break out of our dispatch loop as we no
-			// longer need to process any further updates.
-			switch closeUpdate := closingUpdate.(type) {
-			case *peer.ChannelCloseUpdate:
-				h, _ := chainhash.NewHash(closeUpdate.ClosingTxid)
-				rpcsLog.Infof("[closechannel] close completed: "+
-					"txid(%v)", h)
-				break out
+				err = updateStream.Send(rpcClosingUpdate)
+				if err != nil {
+					return err
+				}
+
+				// If a final channel closing updates is being
+				// sent, then we can break out of our dispatch
+				// loop as we no longer need to process any
+				// further updates.
+				switch closeUpdate := closingUpdate.(type) {
+				case *peer.ChannelCloseUpdate:
+					h, _ := chainhash.NewHash(
+						closeUpdate.ClosingTxid,
+					)
+					rpcsLog.Infof("[closechannel] close "+
+						"completed: txid(%v)", h)
+
+					return nil
+				}
+
+			case <-r.quit:
+				return nil
 			}
-		case <-r.quit:
-			return nil
 		}
 	}
 
-	return nil
+	// If the user doesn't want to wait for the txid to come back then we
+	// will exit early.
+	if in.NoWait {
+		go sendUpdate()
+		return nil
+	}
+
+	return sendUpdate()
```

And we need to test the `NoWait` behavior in itest.

Comment (ProofOfKeags) [reply rpcserver.go:2688]: I'd really like to get on the same page about what this is for. @Roasbeef said in the presence of active htlcs that clients will block until they get an update and that it may be undesirable for that wait to occur. However, we need to  We want to provide an option that allows them to return immediately without waiting for that update. In the case of the CLI and REST interfaces there is no follow up. We want to leave the gRPC client to continue to do what it does with the close client so we don't want to change the rpc server.

I'm having a hard time understanding what detaching the goroutine does for these scenarios as nothing about the streams changes on the client side.

File: rpcserver.go (hunk 74 above)
Comment (ProofOfKeags) [reply rpcserver.go:2649]: Yeah this has been added so as not to break backwards compat.

File: rpcserver.go (hunk 71 above)
Comment (ProofOfKeags) [reply rpcserver.go:2696]: After discussing with @Roasbeef the angle is that we don't want to change existing behavior and break clients. The new behavior should be that it returns instantly and if you hold onto the closeClient you'll get updates about it. I believe the existing code satisfies this.

Comment (Roasbeef) [reply rpcserver.go:2696]: IIUC, the handler can't just return there as in the background gRPC will detect the response as being complete, so the stream itself will exit. We want to leave the gRPC handler running, as that's what will keep the stream established. 

Re behavior, need to get through the latest in the PR, but the intent is:
   * Today, users of both the CLI+RPC will get an instant error if they try to co-op close with HTLCs active. 
   * If co-op close is possible (no HTLCs active), then they'll get a _single_ update response once the co-op close transaction has been broadcast. 
   * With this PR, we can now implement the full async co-op close flow, which may mean blocking for minutes/hours while we're waiting for the channel to be flushed. 
   * We don't want to break behavior for all the existing wallets and UIs that use this API. Therefore, we want to guard all new behavior behind a new optional flag. Users can specify this optional flag to permit the full async co-op close process, which one day will become the default. 
   * For the full async co-op close process, we can add in _new_ update messages we send back to the client. These updates can give information w.r.t the various state transitions, eg: shutdown pending, channel flushed, tx brodcast, etc. Due to the above, we can't send any new updates for the legacy clients as they currently assume only one update is sent, and that update has the closing txid. 

At the RPC level, we want the default behavior to be virtually identical to the behavior today. In addition to the check for `ActiveHTLCs`, we also want to make a check right before we signal the link to start to enter a flushing mode. If we can't flush right then and there, we want to return an error. For the new `async` mode, assuming the peer is online, we'll always take the requests and carry out the co-op close now matter how long it takes.

On the CLI level, for the default behavior, no UX changes. For the new async behavior, we have a few options. If we want to match the existing UX (only returns if not possible, or with the co-op close txid), then we can just block until the txid is available once again (can defer other changes to later, so we can conclude the scope of this PR). Otherwise, we can stream the responses back to the CLi. Main thing to be mindful of is that if we just block w/o any updates, users might think it's stuck, and try to issue the command again, so the new logic should reject as we already have a pending close active. Eventually we might also want to add a new state here we show for the channel re closing pending, channel flushign, etc. Again I think we can defer that to limit to the scope of this PR.

**Comment by yyforyongyu** [comment]
@coderabbitai review

File: itest/lnd_coop_close_with_htlcs_test.go [hunk 75]
```diff
@@ -0,0 +1,103 @@
...
+	ht.SendPaymentAndAssertStatus(bob, req, lnrpc.Payment_IN_FLIGHT)
+	ht.AssertNumActiveHtlcs(bob, 1)
+
+	// Assert at this point that the HTLC is open but not yet settled.
+	ht.AssertInvoiceState(invoiceStream, lnrpc.Invoice_ACCEPTED)
+
+	// Have alice attempt to close the channel.
+	closeClient := alice.RPC.CloseChannel(&lnrpc.CloseChannelRequest{
+		ChannelPoint: chanPoint,
+		NoWait:       true,
```
Comment (yyforyongyu) [inline itest/lnd_coop_close_with_htlcs_test.go:67]: Nice!

File: lntest/harness.go [hunk 76]
```diff
@@ -1218,28 +1218,12 @@ func (h *HarnessTest) CloseChannelAssertPending(hn *node.HarnessNode,
...
-		}
-
-		return err
-	}, wait.ChannelCloseTimeout)
+	stream = hn.RPC.CloseChannel(closeReq)
+	event, err = h.ReceiveCloseChannelUpdate(stream)
+	if err != nil {
+		h.Logf("Test: %s, close channel got error: %v",
+			h.manager.currentTestCase, err)
+	}
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply lntest/harness.go:1226]: We do wanna halt the test and stop in this case inside the `lntest` package, as there's no need to handle this error but stopping the test and fix this test case.

File: rpcserver.go [hunk 77]
```diff
@@ -2690,6 +2690,19 @@ func (r *rpcServer) CloseChannel(in *lnrpc.CloseChannelRequest,
 			maxFee, deliveryScript,
 		)
 	}
+
+	// If the user doesn't want to wait for the txid to come back then we
+	// will exit early.
+	if in.NoWait {
+		rpcsLog.Tracef("[closechannel] sending instant update")
```
Comment (yyforyongyu) [inline rpcserver.go:2697]: `Tracef -> Trace`

**Review by yyforyongyu — COMMENTED** [review]
itests are failing, aside from that, I think it's good to go once the rpc level behavior is settled. My suggestion is to defer the `NoWait` changes and itests to a new PR, and merge the rest to limit the scope. There we can then handle this case properly,
> Main thing to be mindful of is that if we just block w/o any updates, users might think it's stuck, and try to issue the command again, so the new logic should reject as we already have a pending close active. Eventually we might also want to add a new state here we show for the channel re closing pending, channel flushign, etc. Again I think we can defer that to limit to the scope of this PR.

File: peer/brontide.go [hunk 78]
```diff
@@ -3602,6 +3577,8 @@
 // message is received from the remote peer. We'll use this message to advance
 // the chan closer state machine.
 func (p *Brontide) handleCloseMsg(msg *closeMsg) {
+	link := p.fetchLinkFromKeyAndCid(msg.cid)
+
```
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply peer/brontide.go:3581]: Mr Rabbit I think you are wrong

File: rpcserver.go (hunk 71 above)
Comment (Crypt-iQ) [reply rpcserver.go:2696]: > In addition to the check for ActiveHTLCs, we also want to make a check right before we signal the link to start to enter a flushing mode. If we can't flush right then and there, we want to return an error.

I don't think this check is possible in practice. Since flushing only happens when both sides have sent `shutdown`, we would have to send `shutdown` to enter this state. If we send `shutdown`, that means that we've started the coop close process when the intent AFAICT is to _not start_ the process unless we're sure the `closing_signed` portion can start immediately (keeping the old behavior). But we can't know ahead of time (i.e. before sending `shutdown`) whether it can immediately start as the counterparty is allowed to add HTLCs even if we've sent `shutdown`.

Comment (Crypt-iQ) [reply rpcserver.go:2696]: Since the goal is to keep RPC users of the old form of coop close compatible, I think we can make some minimally invasive changes here.  Currently, users are expecting a `ChannelCloseUpdate` that is sent once the closing transaction has been detected on-chain.  They may also expect coop close to fail if there are active HTLCs, but that shouldn't matter anymore since coop close can now always complete; removing the `ActiveHTLCs` check shouldn't break any clients.  If we want to update the user on progress with states like `shutdown_sent`, `shutdown_received`, `flushing`, then we can add an RPC flag that opts into additional updates.  As long as we send a `ChannelCloseUpdate` at the end, we won't break clients that didn't opt into this. 

From what I can tell, the one concrete change is that users will have to wait longer to get their `ChannelCloseUpdate` since the flushing process could take some time.  However, they were already waiting for one confirmation of the coop close transaction so the API in current `master` is not quick.  If the goal is to instead give users an option to quickly get through the negotiation part of coop close, I don't see how we can do that and I also don't see what the benefit is to the user who has to wait 1 confirmation anyways, but I could be missing something.

**Comment by Roasbeef** [comment]
> My suggestion is to defer the NoWait changes and itests to a new PR, and merge the rest to limit the scope. 

I think that `NoWait` flag, even if it's temp here is useful, as it's what enables the itest in the first place. The test should stay structurally the same later, but we'd use a diff flag to opt into the new async behavior.

File: itest/lnd_mpp_test.go [hunk 79]
```diff
@@ -309,15 +309,6 @@ func (m *mppTestScenario) closeChannels() {
...
 	}
 
-	// TODO(yy): remove the sleep once the following bug is fixed. When the
-	// payment is reported as settled by Alice, it's expected the
-	// commitment dance is finished and all subsequent states have been
-	// updated. Yet we'd receive the error `cannot co-op close channel with
-	// active htlcs` or `link failed to shutdown` if we close the channel.
-	// We need to investigate the order of settling the payments and
-	// updating commitments to understand and fix .
-	time.Sleep(5 * time.Second)
```
Comment (Roasbeef) [inline itest/lnd_mpp_test.go:319]: 👍

**Review by Roasbeef — APPROVED** [review]
LGTM 🦎
