### PR TITLE
lnwallet/channel: set add heights based on the locked in commits

### LINKED ISSUE #1261: [ERR] SRVR: unable to start server bad-txns-in-belowout
### Background

lnd crashes at startup with error 

### Your environment
0.4.1-beta commit=6a2a049df13103918546a3fc83d65862b68d9708
Linux 4.13.0-1015-gcp  x86_64 GNU/Linux
bitcoind 0.16

out
https://pastebin.com/raw/K7KzHKix

and lnd.log
https://pastebin.com/raw/pBN1gqr1

### LINKED ISSUE #1267: LND crashes on startup: -22: TX rejected: total value of all transaction inputs for transaction ... is 16777216 which is less than the amount spent of 17776996
### Background

Running LND on Testnet on my Laptop. After it went to sleep and woke up, it tried to sync up and quit giving the following error:

```
2018-05-21 17:18:29.682 [INF] LNWL: Inserting unconfirmed transaction d7855d82a1a438668431127441c3bd4ab886dbd0eb240b04527b45c067d539a6
2018-05-21 17:18:29.689 [ERR] CNCT: ChannelArbitrator(195244dcc0a5dcfc2638e8ae791d1a4d90a408effeafe5c5222bdd4fe0ea686b:0): unable to broadcast close tx: -22: TX rejected: total value of all transaction inputs for transaction d7855d82a1a438668431127441c3bd4ab886dbd0eb240b04527b45c067d539a6 is 16777216 which is less than the amount spent of 17776996
2018-05-21 17:18:29.689 [ERR] CNCT: unable to advance state: -22: TX rejected: total value of all transaction inputs for transaction d7855d82a1a438668431127441c3bd4ab886dbd0eb240b04527b45c067d539a6 is 16777216 which is less than the amount spent of 17776996
2018-05-21 17:18:29.689 [ERR] SRVR: unable to start server: -22: TX rejected: total value of all transaction inputs for transaction d7855d82a1a438668431127441c3bd4ab886dbd0eb240b04527b45c067d539a6 is 16777216 which is less than the amount spent of 17776996

-22: TX rejected: total value of all transaction inputs for transaction d7855d82a1a438668431127441c3bd4ab886dbd0eb240b04527b45c067d539a6 is 16777216 which is less than the amount spent of 17776996
```

Everything is running in a docker. I committed one of the containers to an image. Running: `docker start alice` tries to sync up with btcd, and then throws the above error.
My BTCD is all synced up with Testnet.

### Your environment

* version of `lnd` 0.4.1 (Initially started docker from commit 097fd507)
* which operating system (`uname -a` on *Nix): MacOSX but running in Docker
* version of `btcd`, `bitcoind`, or other backend: BTCD: Version 0.12.0-beta
* any other relevant environment details

### Steps to reproduce

Stack trace above

### Expected behaviour

Start up normally

### Actual behaviour

Crashes with above error

### LINKED ISSUE #1292: lnd crash after 30 seconds.
just upgraded to version 524291dadaf39bfbd99efb6654beb6030b3e285e
since then lnd crashes shortly after start

with bitcoind:
```2018-05-28 15:10:05.798 [INF] LNWL: Inserting unconfirmed transaction 37c39e8dcf1f7b4e31a266c27e8bf4914ac228203db0a97ded691b87eeba3cfe
2018-05-28 15:10:05.946 [ERR] CNCT: ChannelArbitrator(15ced24c5eeb2167765a20958470bb18cc062bc96e13a5e62d7bbee7d5979398:1): unable to broadcast close tx: -26: bad-txns-in-belowout, value in (0.002) < value out (0.00202286) (code 16)
2018-05-28 15:10:05.946 [ERR] CNCT: unable to advance state: -26: bad-txns-in-belowout, value in (0.002) < value out (0.00202286) (code 16)
2018-05-28 15:10:05.946 [ERR] SRVR: unable to start server: -26: bad-txns-in-belowout, value in (0.002) < value out (0.00202286) (code 16)

-26: bad-txns-in-belowout, value in (0.002) < value out (0.00202286) (code 16)
```

with btcd:
```2018-05-28 15:11:28.263 [INF] LNWL: Inserting unconfirmed transaction 37c39e8dcf1f7b4e31a266c27e8bf4914ac228203db0a97ded691b87eeba3cfe
2018-05-28 15:11:28.267 [ERR] CNCT: ChannelArbitrator(15ced24c5eeb2167765a20958470bb18cc062bc96e13a5e62d7bbee7d5979398:1): unable to broadcast close tx: -22: TX rejected: total value of all transaction inputs for transaction 37c39e8dcf1f7b4e31a266c27e8bf4914ac228203db0a97ded691b87eeba3cfe is 200000 which is less than the amount spent of 202286
2018-05-28 15:11:28.267 [ERR] CNCT: unable to advance state: -22: TX rejected: total value of all transaction inputs for transaction 37c39e8dcf1f7b4e31a266c27e8bf4914ac228203db0a97ded691b87eeba3cfe is 200000 which is less than the amount spent of 202286
2018-05-28 15:11:28.267 [ERR] SRVR: unable to start server: -22: TX rejected: total value of all transaction inputs for transaction 37c39e8dcf1f7b4e31a266c27e8bf4914ac228203db0a97ded691b87eeba3cfe is 200000 which is less than the amount spent of 202286

-22: TX rejected: total value of all transaction inputs for transaction 37c39e8dcf1f7b4e31a266c27e8bf4914ac228203db0a97ded691b87eeba3cfe is 200000 which is less than the amount spent of 202286
```

some other things in the log that looks bad but doesn't crash:

```
2018-05-28 11:35:04.080 [DBG] LNWL: Could not resend transaction 76552c1183731ce514d4908934ed1a07e449ee3f13e41000f6f396f059112db7: -22: TX rejected: transaction output has negative value of -643
2018-05-28 11:35:04.081 [DBG] LNWL: Could not resend transaction fc09569edc501ef75f6ce61d5116ee6319ba8096adeb6d7d6884cb6902c51c39: -22: TX rejected: transaction output has negative value of -4633
2018-05-28 11:35:04.082 [DBG] LNWL: Could not resend transaction 6a6b136b5bfeae3fe06014e74628e38a30b981cd0f139caefc12b315f5fbdc31: -22: TX rejected: transaction 6a6b136b5bfeae3fe06014e74628e38a30b981cd0f139caefc12b315f5fbdc31 is not standard: transaction output 0: payment of 50 is dust
2018-05-28 11:35:04.083 [DBG] LNWL: Could not resend transaction da182019d8853332ebb4d43999df961d0b661631d220043145393c8e7a85f7aa: -22: TX rejected: transaction output has negative value of -45
2018-05-28 11:35:04.084 [DBG] LNWL: Could not resend transaction 3ee78d447769774ab6de8b7eb73af8322646eb747ca3f743285233faf53a19e4: -22: TX rejected: transaction already exists   2018-05-28 11:35:04.085 [DBG] LNWL: Could not resend transaction 032dd4db8bb8aef899bbf36af8b1fecf8af9a77084daf973b93c4f0d03dfd7aa: -22: TX rejected: transaction output has negative value of -1850
2018-05-28 11:35:04.086 [DBG] LNWL: Could not resend transaction 52ffee32a8f2d7a4f9f7fc640f1abd23efd35977f092189a4c017637582122e1: -22: TX rejected: transaction output has negative value of -453
2018-05-28 11:35:04.086 [DBG] LNWL: Could not resend transaction 3e534322a3f85e7283f0962f6543940849acc6a28fb45b8f86690f676be7aa5d: -22: TX rejected: transaction output has negative value of -330
2018-05-28 11:35:04.087 [DBG] LNWL: Could not resend transaction ddf46c985005f6913a06439cdd497b9e74d1bc309da5bf3da219acb6e26e5e88: -22: TX rejected: transaction output has negative value of -45
2018-05-28 11:35:04.088 [DBG] LNWL: Could not resend transaction c6b5d91543cdeabe528247ba7b1584d4df6c4bb1627714a506012cd3358285c0: -22: TX rejected: transaction output has negative value of -668
2018-05-28 11:35:04.089 [DBG] LNWL: Could not resend transaction 80d93e5a0437457c85d4434c6dc3e84162f889aaba9ff88ad79812ed05762a6f: -22: TX rejected: transaction output has negative value of -709
2018-05-28 11:35:04.092 [DBG] LNWL: Could not resend transaction d3882957348fd0cdce3882503f030a58472e1fc5b95473777824a35868d308a4: -22: TX rejected: transaction already exists
2018-05-28 11:35:04.095 [DBG] LNWL: Could not resend transaction fd28e78fe75c7c2f06590ec4c163f0c97ba9fb3ea5822accdb4473f9080a93c1: -22: TX rejected: transaction already exists
2018-05-28 11:35:04.099 [DBG] LNWL: Could not resend transaction f7b15e4977c1178fcbbdb32693e56ade7776bb08229233a5374264cc9ebe1b87: -22: TX rejected: transaction already exists
2018-05-28 11:35:04.100 [DBG] LNWL: Could not resend transaction cd93f5c587f582ba1b2fbecdd908c9e07bda0a823c3e1caa2c0c79737c19d248: -22: TX rejected: transaction output has negative value of -519
2018-05-28 11:35:04.101 [DBG] LNWL: Could not resend transaction 972a11ff5eacadb1132e47b7cf7eaa1393091b2a36067d84af30ee912c8c4a17: -22: TX rejected: transaction output has negative value of -710
2018-05-28 11:35:04.102 [DBG] LNWL: Could not resend transaction 0febf306b42f38f9a3e0fa8a369acc61ba2c36b3fef95831ab35b239908c31a8: -22: TX rejected: transaction 0febf306b42f38f9a3e0fa8a369acc61ba2c36b3fef95831ab35b239908c31a8 is not standard: transaction output 0: payment of 50 is dust
2018-05-28 11:35:04.103 [DBG] LNWL: Could not resend transaction 58f366d4778ae08e34658e9da0d594ffa61bdf567aef513db4d83220b4e7c840: -22: TX rejected: transaction 58f366d4778ae08e34658e9da0d594ffa61bdf567aef513db4d83220b4e7c840 is not standard: transaction output 0: payment of 51 is dust
2018-05-28 11:35:04.104 [DBG] LNWL: Could not resend transaction 1ccb470413dd7ac109e0fd1af4f24610dfca764188bdd5455cb59ee9c87a67ca: -22: TX rejected: transaction 1ccb470413dd7ac109e0fd1af4f24610dfca764188bdd5455cb59ee9c87a67ca is not standard: transaction output 0: payment of 282 is dust
2018-05-28 11:35:04.105 [DBG] LNWL: Could not resend transaction 3ee905b1a247777462096878a806e31e5fc32623124333e4bdbb51eb7bcc39fe: -22: TX rejected: transaction output has negative value of -1023
2018-05-28 11:35:04.107 [DBG] LNWL: Could not resend transaction dd1b4c533cc1e4fd6e6933c3c5702cf29a54eeed3d75dca9ae002941fd81ca9b: -22: TX rejected: transaction already exists
2018-05-28 11:35:04.108 [DBG] LNWL: Could not resend transaction 95a79b0f59ed2845d0e92d0307baaa2653d1163620c0a019f82196dcf309c76d: -22: TX rejected: transaction output has negative value of -98
2018-05-28 11:35:04.109 [DBG] LNWL: Could not resend transaction e285e1078e2b14cf93a791c25d6d26a02285d436cff86249b072b735b33fff7e: -22: TX rejected: transaction output has negative value of -1279
2018-05-28 11:35:04.110 [DBG] LNWL: Could not resend transaction 9ad578b3744c6cecd7d47031178e34c50e1028a3983b52dfbfc756aadec4e5c6: -22: TX rejected: transaction output has negative value of -2800
2018-05-28 11:35:04.110 [DBG] LNWL: Could not resend transaction 64040bacfd7bee3cee98ddd166a0e114ab28ee037f796374a5a89ac9c9e58e8d: -22: TX rejected: transaction 64040bacfd7bee3cee98ddd166a0e114ab28ee037f796374a5a89ac9c9e58e8d is not standard: transaction output 0: payment of 117 is dust
2018-05-28 11:35:04.111 [DBG] LNWL: Could not resend transaction b5f6d716508aaebab69cc2fd63ffd43cac12658de415cab067a0efb6d9ca08e8: -22: TX rejected: transaction output has negative value of -1213                                                                                                                                                                 2018-05-28 11:35:04.112 [DBG] LNWL: Could not resend transaction faace583c679a3614936cf82d47a08a9e3b3381fbde75e571e4219aea2661aac: -22: TX rejected: transaction faace583c679a3614936cf82d47a08a9e3b3381fbde75e571e4219aea2661aac is not standard: transaction output 0: payment of 50 is dust```

### PR DESCRIPTION
**Pull request by halseth**
This commit fixes a bug which would cause the add heights of the HTLCs
in the update log to be set wrongly. At times, an add height could be
incorrecly set, leading to the HTLCs not being accounted for correctly
during evaluating the HTLC views. This was caused by the assumption that
if the HTLC was not on the pending remote commit, then it was locked in
on both the local and the remote commit, which is not always true.

Instead of making this assumption, we instead now inspect the three
commits: the local, remote and pending remote; and set the add heights
accordingly. This should ensure that HTLCs are subtracted from the
balances only when they are first added.

Fixes #1293. 
Fixes #1267. 
Fixes #1261. 
Fixes #1292.

### CODE REVIEW

File: lnwallet/channel.go [hunk 1]
```diff
@@ -1671,14 +1657,15 @@ func (lc *LightningChannel) restoreCommitState(
...
-			false, true, &pendingRemoteCommitDiff.Commitment,
+			false, &pendingRemoteCommitDiff.Commitment,
 			nil, pendingCommitPoint,
 		)
 		if err != nil {
 			return err
 		}
 		lc.remoteCommitChain.addCommitment(pendingRemoteCommit)
 
+		// TODO: add htlcs
```
Comment (Roasbeef) [inline lnwallet/channel.go]: They're already logged in the contract court FWIW.

File: lnwallet/channel.go [hunk 2]
```diff
@@ -1716,19 +1703,67 @@ func (lc *LightningChannel) restoreStateLogs(
...
+		for _, r := range pendingRemoteCommit.incomingHTLCs {
+			incomingRemoteAddHeights[r.HtlcIndex] =
+				pendingRemoteCommit.height
+		}
+	}
+
+	// Now set the remote commit height of all incoming HTLCs found on the
+	// remote commitment.
+	for _, r := range remoteCommitment.incomingHTLCs {
+		incomingRemoteAddHeights[r.HtlcIndex] = remoteCommitment.height
```
Comment (cfromknecht) [inline lnwallet/channel.go]: What if the htlcs were locked in before the latest remote commitment?

We could walk backwards along the remote commitment until finding the earliest occurrence of each htlc, not sure that's the best way to approach it though

File: lnwallet/channel.go [hunk 3]
```diff
@@ -1716,19 +1703,67 @@ func (lc *LightningChannel) restoreStateLogs(
...
+	}
+
+	// And finally we can do the same for the outgoing HTLCs.
+	for _, l := range localCommitment.outgoingHTLCs {
+		outgoingLocalAddHeights[l.HtlcIndex] = localCommitment.height
```
Comment (cfromknecht) [inline lnwallet/channel.go]: Same question here wrt. HTLCs being locked in by a prior commitment? This might be more difficult to restore than the remote case since we discard our old local states

File: lnwallet/channel_test.go [hunk 4]
```diff
@@ -5505,3 +5505,194 @@ func TestDuplicateSettleRejection(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("unable to sign commitment: %v", err)
+	}
+
+	// The signing of a new commitment for Alice should have given the new
+	// HTLC an add height.
+	bobChannel = restoreAndAssertCommitHeights(t, bobChannel, true, 0, 2, 1)
+	bobChannel = restoreAndAssertCommitHeights(t, bobChannel, true, 1, 2, 2)
+
+	aliceChannel.Stop()
```
Comment (cfromknecht) [inline lnwallet/channel_test.go]: Maybe `defer aliceChannel.Stop()` after each restore?

File: lnwallet/channel.go (hunk 2 above)
Comment (Roasbeef) [reply lnwallet/channel.go]: There's no material diff if they were say locked in at height 3 (waay before), but then we restore at height 20, as long as it's done symmetrically on both commitments (which it is atm).

Comment (cfromknecht) [reply lnwallet/channel.go]: Makes sense, thanks!

File: lnwallet/channel.go (hunk 1 above)
Comment (halseth) [reply lnwallet/channel.go]: woops, stray TODO. Removed.

File: lnwallet/channel_test.go (hunk 4 above)
Comment (halseth) [reply lnwallet/channel_test.go]: Chose to stop the channel inside `restoreAndAssertCommitHeights` to not clutter the test flow too much :)

Comment (cfromknecht) [reply lnwallet/channel_test.go]: Hadn't noticed that :) won't catch in cases where we fail, but probably okay
