### PR TITLE
funding: fix race in itest for zero-conf funding

### LINKED ISSUE #9912: [bug]: failed to send payments in `zero_conf-channel_policy_update_public_zero_conf`
Found from this [build](https://github.com/lightningnetwork/lnd/actions/runs/15445236160/job/43472922533?pr=9880),
```
--- FAIL: TestLightningNetworkDaemon/tranche01/48-of-301/bitcoind/zero_conf-channel_policy_update_public_zero_conf (151.80s)
        harness_node.go:403: Starting node (name=Eve) with PID=18006
        harness_node.go:403: Starting node (name=Carol) with PID=18306
        harness_node.go:403: Starting node (name=Dave) with PID=18496
        harness_assertion.go:1087: 
            	Error Trace:	/home/runner/work/lnd/lnd/lntest/harness_assertion.go:1087
            	            				/home/runner/work/lnd/lnd/lntest/harness_assertion.go:1040
            	            				/home/runner/work/lnd/lnd/lntest/harness.go:1588
            	            				/home/runner/work/lnd/lnd/lntest/harness.go:1601
            	            				/home/runner/work/lnd/lnd/itest/lnd_zero_conf_test.go:673
            	            				/home/runner/work/lnd/lnd/itest/lnd_zero_conf_test.go:65
            	            				/home/runner/work/lnd/lnd/lntest/harness.go:303
            	            				/home/runner/work/lnd/lnd/itest/lnd_test.go:130
            	Error:      	Received unexpected error:
            	            	received error from payment stream: EOF
            	Test:       	TestLightningNetworkDaemon/tranche01/48-of-301/bitcoind/zero_conf-channel_policy_update_public_zero_conf
            	Messages:   	timeout while waiting payment
        harness.go:381: finished test: zero_conf-channel_policy_update_public_zero_conf, start height=574, end height=588, mined blocks=14
        harness.go:340: test failed, skipped cleanup
    lnd_test.go:138: Failure time: 2025-06-04 15:32:32.374
```

Eve tried to send a payment to Dave via Carol, but Carol cannot find the channel between her and Dave, causing the payment to fail,
```
2025-06-04 15:31:01.819 [DBG] HSWC link.go:4115: ChannelLink([ChanPoint: Eve=>Carol]): forwarding 1 packets to switch: replay=false
2025-06-04 15:31:01.822 [DBG] HSWC switch.go:2253: Querying outgoing link using chanID=583:1:0, aliasID=false
2025-06-04 15:31:01.822 [DBG] HSWC switch.go:2869: unable to find link with destination 583:1:0
2025-06-04 15:31:01.822 [ERR] HSWC switch.go:1238: UnknownNextPeer
2025-06-04 15:31:01.822 [ERR] HSWC switch.go:840: Unhandled error while reforwarding htlc settle/fail over htlcswitch: UnknownNextPeer
2025-06-04 15:31:01.822 [DBG] HSWC link.go:1926: ChannelLink([ChanPoint: Eve=>Carol]): queueing removal of FAIL closed circuit: (Chan ID=577:1:0, HTLC ID=0)->(Chan ID=583:1:0, HTLC ID=0)
```

It's like a bug in zeroconf or channel policy update, causing the channel to not be found here,
https://github.com/lightningnetwork/lnd/blob/4a7cd0095e37c2caf080d39d2f7290a5d38d831e/htlcswitch/switch.go#L2285-L2306

### PR DESCRIPTION
**Pull request by ziggie1984**
Fix a race condition where forwarding through a public zero-conf channel
could fail with UnknownNextPeer when using the confirmed SCID. The issue
occurred because ReportShortChanID (which updates the switch's baseIndex
to handle the confirmed SCID) was called AFTER addToGraph (which announces
the confirmed SCID to the network).

With slow backends like postgres, addToGraph takes significant time,
creating a window where other nodes learn about the confirmed SCID from
gossip and attempt to route through it, but the receiving node's switch
hasn't been updated yet to handle forwards using the confirmed SCID.

The fix reorders operations to call ReportShortChanID before addToGraph,
ensuring the switch is ready to handle the confirmed SCID before it's
announced to the network. Forwards using either the alias or confirmed
SCID will work since getLinkByMapping uses baseIndex to map both to the
same link in forwardingIndex.

Fixes flaky test: zero_conf-channel_policy_update_public_zero_conf

Fix #9912

### CODE REVIEW

File: funding/manager.go [hunk 1]
```diff
@@ -3957,6 +3957,22 @@ func (f *Manager) waitForZeroConfChannel(c *channeldb.OpenChannel) error {
...
+	// it. This is especially important for integration tests.
+	err = f.cfg.ReportShortChanID(c.FundingOutpoint)
+	if err != nil {
+		// This should only fail if the link is not found in the
+		// Switch's linkIndex map. If this is the case, then the peer
+		// has gone offline and the next time the link is loaded, it
+		// will have a refreshed state. Just log an error here.
+		log.Errorf("unable to report scid for zero-conf channel "+
+			"channel: %v", err)
+	}
```
Comment (starius) [inline funding/manager.go:3974]: If `ReportShortChanID` fails, we still call `addToGraph`, so we might gossip the confirmed SCID while the switch mapping is missing. If the link is offline, forwarding cannot work anyway and the mapping will be repopulated on reconnect. But if the failure is transient (e.g. DB briefly down) while the link is up, do we reintroduce the race until the link reloads? Should we treat `ReportShortChanID` as required (return/retry before gossip), or is the current flow acceptable?

File: funding/manager_test.go [hunk 2]
```diff
@@ -4746,6 +4741,13 @@ func testZeroConf(t *testing.T, chanType *lnwire.ChannelType) {
 		t.Fatalf("did not call ReportShortChanID in time")
 	}
 
+	// For taproot channels, we don't expect them to be announced atm.
+	if !isTaprootChanType(chanType) {
+		assertChannelAnnouncements(
+			t, alice, bob, fundingAmt, nil, nil, nil, nil,
+		)
+	}
+
```
Comment (starius) [inline funding/manager_test.go:4750]: Nice! :+1: 

The unit test captures the bug: the test fails if `manager.go` is reverted to the previous (incorrect) version.

**Review by starius — APPROVED** [review]
**LGTM!** 🏆

Thanks for fixing this! The test is wonderful - it serves as a regression test.

Just one comment: if `ReportShortChanID` fails because of a transient DB error, does it make sense to call `addToGraph`?

File: funding/manager.go (hunk 1 above)
Comment (ziggie1984) [reply funding/manager.go:3974]: so this is just a race in the itests, normally we should never see the link being online this update failing, but I think even if we would see that, it is totally fine to continue publishing the channel.
