### PR TITLE
multi: export channel status field in migration25

### LINKED ISSUE #6558: Unable to apply migration #27 / LTND: unable to open graph DB
### Background

NOTE: TIL the difference between updating to master and tagged release "latest." :)

- Updated to 164a9c6 (v0.15.0-beta.rc2) from ??? (I assume 14.3)
- Received the error below when starting LND (see complete logs at bottom of report):
```
CHDB: Unable to apply migration #27
LTND: unable to open graph DB
```
- Reverted back to b31640e (lnd v0.15.0-beta.rc1)
- Started LND successfully

I see there are database updates so I didn't go all the way back to v14.3 for fear of corrupting something. I am not a coder/developer in the least--just been following all the great docs all these years. :) I hope this report helps.

### Your environment

* Version of `lnd`: v.15.0-beta-rc1 and rc2)
* Which operating system: Ubuntu 22.04 LTS
* Version of `btcd`, `bitcoind`, or other backend: Bitcoin Core version v22.0.0
* Any other relevant environment details: None but let me know, in detail, what you need added to help
* "Cyclopes" on testnet (updated to v15.0-beta.rc2 without issue)
* "Steropes" on mainnet (having the issue described in this report)

### Steps to reproduce

- Update to v15.0-beta-rc2
- Start LND

### Expected behaviour

Upgrade completes and LND updates DB as needed and runs successfully.

### Actual behaviour

DB error per logs below:
```
2022-05-21 20:29:25.497 [INF] LTND: Version: 0.15.0-beta.rc2 commit=v0.15.0-beta.rc2, build=production, logging=default, debuglevel=info
2022-05-21 20:29:25.497 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2022-05-21 20:29:25.506 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2022-05-21 20:29:25.507 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2022-05-21 20:29:25.507 [INF] LTND: Opening the main database, this might take a few minutes...
2022-05-21 20:29:25.507 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
2022-05-21 20:29:25.507 [I> 2022-05-21 20:29:25.497 [INF] LTND: Version: 0.15.0-beta.rc2 commit=v0.15.0-beta.rc2, build=production, logging=default, debuglevel=info
2022-05-21 20:29:25.497 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2022-05-21 20:29:25.506 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2022-05-21 20:29:25.507 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2022-05-21 20:29:25.507 [INF] LTND: Opening the main database, this might take a few minutes...
2022-05-21 20:29:25.507 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
2022-05-21 20:29:25.507 [INF] CHDB: Compacting database file at /[***edited**]/.lnd/data/graph/mainnet/channel.db
2022-05-21 20:29:35.300 [INF] CHDB: DB compaction of /[***edited**]/.lnd/data/graph/mainnet/channel.db successful, 513925120 -> 513900544 bytes (gain=1.00x)
2022-05-21 20:29:35.300 [INF] CHDB: Swapping old DB file from /[***edited**]/.lnd/data/graph/mainnet/temp-dont-use.db to /[***edited**]/.lnd/data/graph/mainnet/channel.db
2022-05-21 20:29:35.375 [INF] CHDB: Compacting database file at /[***edited**]/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2022-05-21 20:29:35.378 [INF] CHDB: DB compaction of /[***edited**]/.lnd/data/chain/bitcoin/mainnet/macaroons.db successful, 32768 -> 32768 bytes (gain=1.00x)
2022-05-21 20:29:35.378 [INF] CHDB: Swapping old DB file from /[***edited**]/.lnd/data/chain/bitcoin/mainnet/temp-dont-use.db to /[***edited**]/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2022-05-21 20:29:35.379 [INF] CHDB: Compacting database file at /[***edited**]/.lnd/data/graph/mainnet/sphinxreplay.db
2022-05-21 20:29:36.357 [INF] CHDB: DB compaction of /[***edited**]/.lnd/data/graph/mainnet/sphinxreplay.db successful, 25214976 -> 25214976 bytes (gain=1.00x)
2022-05-21 20:29:36.357 [INF] CHDB: Swapping old DB file from /[***edited**]/.lnd/data/graph/mainnet/temp-dont-use.db to /[***edited**]/.lnd/data/graph/mainnet/sphinxreplay.db
2022-05-21 20:29:36.360 [INF] LTND: Creating local graph and channel state DB instances
2022-05-21 20:29:37.753 [INF] CHDB: Checking for schema update: latest_version=27, db_version=25
2022-05-21 20:29:37.753 [INF] CHDB: Performing database schema migration
2022-05-21 20:29:37.754 [INF] CHDB: Applying migration #26
2022-05-21 20:29:37.766 [INF] CHDB: Applying migration #27
2022-05-21 20:29:37.766 [INF] CHDB: Unable to apply migration #27
2022-05-21 20:29:37.772 [ERR] LTND: unable to open graph DB: bb913c5edf3950a4acfde74f76416083a4f4056ba3049a2a2111cfe262254801:0: fetch chan info got: MsgTx.BtcDecode: witness tx but flag byte is 00
2022-05-21 20:29:37.773 [ERR] LTND: Shutting down because error in main method: unable to open databases: unable to open graph DB: bb913c5edf3950a4acfde74f76416083a4f4056ba3049a2a2111cfe262254801:0: fetch chan info got: MsgTx.BtcDecode: witness tx but flag byte is 00
2022-05-21 20:29:37.773 [INF] LTND: Shutdown completeNF] CHDB: Compacting database file at /[***edited**]/.lnd/data/graph/mainnet/channel.db
2022-05-21 20:29:35.300 [INF] CHDB: DB compaction of /[***edited**]/.lnd/data/graph/mainnet/channel.db successful, 513925120 -> 513900544 bytes (gain=1.00x)
2022-05-21 20:29:35.300 [INF] CHDB: Swapping old DB file from /[***edited**]/.lnd/data/graph/mainnet/temp-dont-use.db to /[***edited**]/.lnd/data/graph/mainnet/channel.db
2022-05-21 20:29:35.375 [INF] CHDB: Compacting database file at /[***edited**]/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2022-05-21 20:29:35.378 [INF] CHDB: DB compaction of /[***edited**]/.lnd/data/chain/bitcoin/mainnet/macaroons.db successful, 32768 -> 32768 bytes (gain=1.00x)
2022-05-21 20:29:35.378 [INF] CHDB: Swapping old DB file from /[***edited**]/.lnd/data/chain/bitcoin/mainnet/temp-dont-use.db to /[***edited**]/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2022-05-21 20:29:35.379 [INF] CHDB: Compacting database file at /[***edited**]/.lnd/data/graph/mainnet/sphinxreplay.db
2022-05-21 20:29:36.357 [INF] CHDB: DB compaction of /[***edited**]/.lnd/data/graph/mainnet/sphinxreplay.db successful, 25214976 -> 25214976 bytes (gain=1.00x)
2022-05-21 20:29:36.357 [INF] CHDB: Swapping old DB file from /[***edited**]/.lnd/data/graph/mainnet/temp-dont-use.db to /[***edited**]/.lnd/data/graph/mainnet/sphinxreplay.db
2022-05-21 20:29:36.360 [INF] LTND: Creating local graph and channel state DB instances
2022-05-21 20:29:37.753 [INF] CHDB: Checking for schema update: latest_version=27, db_version=25
2022-05-21 20:29:37.753 [INF] CHDB: Performing database schema migration
2022-05-21 20:29:37.754 [INF] CHDB: Applying migration #26
2022-05-21 20:29:37.766 [INF] CHDB: Applying migration #27
2022-05-21 20:29:37.766 [INF] CHDB: Unable to apply migration #27
2022-05-21 20:29:37.772 [ERR] LTND: unable to open graph DB: bb913c5edf3950a4acfde74f76416083a4f4056ba3049a2a2111cfe262254801:0: fetch chan info got: MsgTx.BtcDecode: witness tx but flag byte is 00
2022-05-21 20:29:37.773 [ERR] LTND: Shutting down because error in main method: unable to open databases: unable to open graph DB: bb913c5edf3950a4acfde74f76416083a4f4056ba3049a2a2111cfe262254801:0: fetch chan info got: MsgTx.BtcDecode: witness tx but flag byte is 00
2022-05-21 20:29:37.773 [INF] LTND: Shutdown complete
```

Again, I hope this helps and I didn't miss a migration step for the DB changes. Thank you!

### PR DESCRIPTION
**Pull request by yyforyongyu**
Fixes #6558.

Previously, in `migration25.OpenChannel`, there was a private field `chanStatus` used to keep track of the channel status. The following migrations, `migration26` and `migration27` also have their own `OpenChannel` defined, with `migration26` inherited from `migration25`, and `migration27` inherited from `migration26`. The private field `chanStatus`, however, is NOT inherited and each of the migrations uses its own. This is fine for reading and writing as, under the hood, the `chanStatus` is just a `uint8` value. Because each migration has its own fetcher and putter, it can safely access its private field to read and write it correctly.

The issue pops up when we use the method `migration25.FundingTxPresent()`. Because it's evaluating its channel status using its own private field `chanStatus`, this field would always be the default value(`ChanStatusDefault`), leading the statement `!c.hasChanStatus(ChanStatusRestored)` to always be true. Thus a restored channel will be mistakenly considered to have funding tx present, causing failures in reading the channel info in the following migrations.

We fix this by exporting the `ChanStatus` field so its value can be set by following migrations.

### Affected migrations

Migration 26 and 27 will fail at decoding the funding tx step if we are the channel funder and the channel is restored. If they succeed, it means either,

1. we are not the channel funder, or,
2. the channel is funded externally, or,
3. the channel is not restored

And the data has been migrated correctly. Otherwise, the migrations will halt and `lnd` will quit with an error.

### CODE REVIEW

**Comment by yyforyongyu** [comment]
Got one confirmation from @ziggie1984 that this pr fixed the issue. Thanks again for reporting the issue and sharing the testnet channel db file!

**Review by Crypt-iQ — APPROVED** [review]

File: channeldb/migration27/migration_test.go [hunk 1]
```diff
@@ -54,42 +54,80 @@ var (
...
-		false,
-	)
+	testCases := []struct {
+		name               string
+		isAfterMigration25 bool
+		isRestored         bool
+	}{
+		{
+			// Test that when the restored historical channel
+			// doesn't have the two new fields.
```
Comment (Roasbeef) [inline channeldb/migration27/migration_test.go:72]: 👍

**Review by Roasbeef — APPROVED** [review]
LGTM 🐊
