### PR TITLE
chainntnfs: handle historical confs and spends asynchronously

### LINKED ISSUE #1569: No outbound peer connections when restarting & Sluggish startup
### Background

Describe your issue here.

### Your environment

* version of `lnd` 0.4.2-beta commit=6dff599d213be4182a70c8eab4cac8a36d3c15e4 but was also running into something similar on pervious commmits
* which operating system (`uname -a` on *Nix)
Ubuntu  x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend
btcd version 0.12.0-beta
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

Outbound connections

### Actual behaviour

Tell us what happens instead

Here's what profiling shows: 
https://paste.ubuntu.com/p/JxjrqWzrdw/
https://paste.ubuntu.com/p/QJ5k3rjGzn/

In previous commits LND would usually take 20ish minutes to startup and it would eventually. This time it refuses to connect outbound and I left it running overnight.

Seems after another restart I was able to connect to some peers but doesn't auto connect to any others.

2018-07-17 08:27:55.520 is where I restart, and any connections made following that I made manually.
LND logs
https://paste.ubuntu.com/p/4MgWjJqRB4/
Another profiler view from this point http://paste.ubuntu.com/p/tNXp4PX7jC/

### LINKED ISSUE #1616: lnd does not finish starting all watchers in  ChainArbitrator
[lnd.log](https://github.com/lightningnetwork/lnd/files/2225725/lnd.log)
### Background

I decided to force close some old channels with peers I hadn't seen for a month or more. I force-closed 5 channels in total. About the same time, I noticed someone creating dust channel of 20k satoshi with me, so after having force-closed, but before anything was confirmed I guess, I restarted node to set a minchansize parameter.

Describe your issue here.

After starting up lnd and unlocking wallet, it gets to ChainArbitrator, and begins starting close observers. After a variable number of successful close observer goroutines is started, it seems to get stuck and LND does not continue its work. It still answers to lncli commands, though.
### Your environment

* version of `lnd`

LND version 0.4.2-beta commit=e0baa4969035fc555b185d21acaa0b09aecdef6f
* which operating system (`uname -a` on *Nix)

Linux thundroid 4.14.24-113 #1 SMP PREEMPT Mon Mar 5 12:21:35 UTC 2018 armv7l armv7l armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

Bitcoin Core Daemon version v0.16.0
Copyright (C) 2009-2018 The Bitcoin Core developers

* any other relevant environment details

### Steps to reproduce

Not sure if the above steps will reproduce or not....

### Expected behaviour

All chain watchers should start, and LND should continue startup.

### Actual behaviour

Tell us what happens instead

LND hangs in ChainArbitrator startup.

### LINKED ISSUE #1648: lnd take ages to start up
### Background

lnd needs around 10-15 minutes after startup to actually connecting to peers. There's no unexpected activity (network or high CPU load). Then it always start talking to peer, but it looks like it is stuck on some timeouts (maybe waiting to timeouts to unreachable peers, serially?)

After this time, node normally start up with 300+ peers.

I started to notice this kind of behavior after it started maintaining high amount of peers, but it might be a coincidence.

### Your environment
```
{
    "identity_pubkey": "02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469",
    "alias": "tady je slushovo",
    "num_pending_channels": 4,
    "num_active_channels": 292,
    "num_peers": 285,
    "block_height": 534252,
    "block_hash": "00000000000000000015b1681f2db980643fcfe6c36bc330c56e20731bed7010",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469@109.239.79.181:9735"
    ],
    "best_header_timestamp": "1532860554",
    "version": "0.4.2-beta commit=92b0b10dc75de87be3a9f895c8dfc5a84a2aec7a"
}
```

```Linux server01 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux```

* bitcoind 0.16.1

### Steps to reproduce

Any restart of lnd.

### Expected behaviour

After lnd restart, lnd should open connections to peers and start communicating.

### Actual behaviour

Log is filling with lines like this, but no other activity can be seen.

```
2018-07-29 10:41:01.408 [INF] NTFN: New spend subscription: utxo=5f2274c650d5838f06c3dd213b0fb366462e31accdc82e8f0d7fd4cb91c603ec:0
2018-07-29 10:41:01.408 [INF] CNCT: Close observer for ChannelPoint(58374cb32884e7b03c643540c49217a28415bdd2523d4548b940d07a49214a56:0) active
2018-07-29 10:41:01.536 [INF] NTFN: New spend subscription: utxo=26d7408e94ab5f75d470fdde3790544f3510d7b126e94d223e983e963bd980ee:0
2018-07-29 10:41:01.536 [INF] CNCT: Close observer for ChannelPoint(5f2274c650d5838f06c3dd213b0fb366462e31accdc82e8f0d7fd4cb91c603ec:0) active
2018-07-29 10:41:01.610 [INF] NTFN: New spend subscription: utxo=a813a909de85fb573a8bb9c747114eb3c5f98903b1994235ee086a2edc24629a:1
2018-07-29 10:41:01.610 [INF] CNCT: Close observer for ChannelPoint(26d7408e94ab5f75d470fdde3790544f3510d7b126e94d223e983e963bd980ee:0) active
2018-07-29 10:41:01.710 [INF] NTFN: New spend subscription: utxo=6af2f741ba31a9e6e5ab1073e795f7145e8cda3dd5628b11ee5dc1192c8506b0:0
2018-07-29 10:41:01.710 [INF] CNCT: Close observer for ChannelPoint(a813a909de85fb573a8bb9c747114eb3c5f98903b1994235ee086a2edc24629a:1) active
2018-07-29 10:41:01.811 [INF] NTFN: New spend subscription: utxo=e2911f11feef0653be37c4ec1be4b799ca4cfdd302b6927d2776eb4f550e5d56:0
2018-07-29 10:41:01.811 [INF] CNCT: Close observer for ChannelPoint(6af2f741ba31a9e6e5ab1073e795f7145e8cda3dd5628b11ee5dc1192c8506b0:0) active
```

getinfo:

```
$ lncli getinfo
{
    "identity_pubkey": "02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469",
    "alias": "tady je slushovo",
    "num_pending_channels": 4,
    "num_active_channels": 0,
    "num_peers": 0,
    "block_height": 534252,
    "block_hash": "00000000000000000015b1681f2db980643fcfe6c36bc330c56e20731bed7010",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469@109.239.79.181:9735"
    ],
    "best_header_timestamp": "1532860554",
    "version": "0.4.2-beta commit=92b0b10dc75de87be3a9f895c8dfc5a84a2aec7a"
}
```

### PR DESCRIPTION
**Pull request by wpaulino**
In this PR, we modify our `bitcoind` and `btcd` chain notifiers to handle historical confirmations and spends asynchronously. This was motivated by users experiencing slow startups due to blocking during long rescans.

Fixes #1569.
Fixes #1616.
Fixes #1648.

### CODE REVIEW

**Comment by Roasbeef** [comment]
Looks to have PR-specific failures on the itests rn.

File: chainntnfs/neutrinonotify/neutrino.go [hunk 1]
```diff
@@ -306,15 +306,16 @@ func (n *NeutrinoNotifier) notificationDispatcher() {
 				currentHeight := n.bestHeight
 				n.heightMtx.RUnlock()
 
-				// Lookup whether the transaction is already included in the
-				// active chain.
-				txConf, err := n.historicalConfDetails(msg.TxID, currentHeight,
-					msg.heightHint)
+				// Look up whether the transaction is already
+				// included in the active chain.
+				confDetails, err := n.historicalConfDetails(
```
Comment (halseth) [inline chainntnfs/neutrinonotify/neutrino.go]: why not async?

File: chainntnfs/txconfnotifier.go [hunk 2]
```diff
@@ -98,78 +101,116 @@ func NewTxConfNotifier(startHeight uint32, reorgSafetyLimit uint32) *TxConfNotif
...
-// confirmation details must be given as the txConf argument, otherwise it
-// should be nil. If the transaction already has the sufficient number of
-// confirmations, this dispatches the notification immediately.
-func (tcn *TxConfNotifier) Register(ntfn *ConfNtfn, txConf *TxConfirmation) error {
+//
+// NOTE: If the transaction has already been included in a block on the chain,
+// the confirmation details must be provided with the UpdateConfDetails method,
+// otherwise we will wait for the transaction to confirm even though it already
+// has.
+func (tcn *TxConfNotifier) Register(ntfn *ConfNtfn) error {
```
Comment (halseth) [inline chainntnfs/txconfnotifier.go]: Commit message says "registrations for unconfirmed transactions only", but seems like this will also be called fro already confirmed transactions?

File: chainntnfs/bitcoindnotify/bitcoind.go [hunk 3]
```diff
@@ -245,24 +245,37 @@ out:
 				_, currentHeight, err := b.chainConn.GetBestBlock()
```
Comment (halseth) [inline chainntnfs/bitcoindnotify/bitcoind.go]: seems like this could be moved inside the go routine

File: chainntnfs/txconfnotifier.go [hunk 4]
```diff
@@ -98,78 +101,116 @@ func NewTxConfNotifier(startHeight uint32, reorgSafetyLimit uint32) *TxConfNotif
...
+		confHeight := details.BlockHeight + ntfn.NumConfirmations - 1
+		if confHeight <= tcn.currentHeight {
+			Log.Infof("Dispatching %v conf notification for %v",
+				ntfn.NumConfirmations, ntfn.TxID)
+
+			// We'll send a 0 value to the Updates channel,
+			// indicating that the transaction has already been
+			// confirmed.
+			select {
+			case ntfn.Event.Updates <- 0:
```
Comment (halseth) [inline chainntnfs/txconfnotifier.go]: Can we risk the channel having a buffer one element to small in this case? (since it is created with `numconfs` capacity)

File: chainntnfs/txconfnotifier.go [hunk 5]
```diff
@@ -98,78 +101,116 @@ func NewTxConfNotifier(startHeight uint32, reorgSafetyLimit uint32) *TxConfNotif
...
+
+			// We'll also send an update to the client of how many
+			// confirmations are left for the transaction to be
+			// confirmed. We'll only do this if the transaction has
+			// been found in the chain before our current height to
+			// avoid sending duplicate updates.
+			if details.BlockHeight <= tcn.currentHeight {
+				numConfsLeft := confHeight - tcn.currentHeight
+				select {
+				case ntfn.Event.Updates <- numConfsLeft:
```
Comment (halseth) [inline chainntnfs/txconfnotifier.go]: Seems like there might be an issue here if multiple callers register for confirmation of the same txid. Each time `UpdateConfDetails` is called as a result of this, all clients will be sent updates? This will lead to each client receiving the updates multiple times, and the channel might even get full.

From what I can gather, we shouldn't need to iterate the ntfn clients in this method, but pass in the one client that requested the historical dispatch, and only notify that one.

File: chainntnfs/bitcoindnotify/bitcoind.go [hunk 6]
```diff
@@ -714,6 +691,65 @@ func (b *BitcoindNotifier) RegisterSpendNtfn(outpoint *wire.OutPoint,
...
+				case <-b.quit:
+					return ErrChainNotifierShuttingDown
+				}
+
+				return nil
+			}
+		}
+	}
+
+	return fmt.Errorf("spending transaction not found within block range "+
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/bitcoindnotify/bitcoind.go]: Fixed.

File: chainntnfs/neutrinonotify/neutrino.go (hunk 1 above)
Comment (wpaulino) [reply chainntnfs/neutrinonotify/neutrino.go]: Fixed.

File: chainntnfs/txconfnotifier.go (hunk 2 above)
Comment (wpaulino) [reply chainntnfs/txconfnotifier.go]: Clarified things a bit, let me know what you think.

File: chainntnfs/txconfnotifier.go (hunk 5 above)
Comment (wpaulino) [reply chainntnfs/txconfnotifier.go]: Yeah, I spent quite some time debugging this. Ended up adding an `id` so that we can uniquely track each notification. This is something that will be needed anyway once we support canceling confirmation notifications.

File: chainntnfs/txconfnotifier.go (hunk 4 above)
Comment (wpaulino) [reply chainntnfs/txconfnotifier.go]: It's safe to do so as we don't send an update indicating the required number of confirmations. Now that I think about this though, it should do that in place of sending an update indicating there aren't any confirmations left as that's already handled by the `Confirmed` channel. Will address it in a follow-up PR.

File: chainntnfs/btcdnotify/btcd.go [hunk 7]
```diff
@@ -299,24 +299,39 @@ out:
...
+					"subscription: txid=%v, id=%v, numconfs=%v",
+					msg.TxID, msg.ID, msg.NumConfirmations)
+
+				bestHeight := uint32(currentHeight)
+
+				// Look up whether the transaction is already
+				// included in the active chain. We'll do this
+				// in a goroutine to prevent blocking
+				// potentially long rescans.
+				go func() {
```
[the remark this answers is not in the document]
Comment (halseth) [reply chainntnfs/btcdnotify/btcd.go]: I was probably wrong, looks like the `tcn.Lock` acquired in `UpdateConfDetails` makes sure that no new block gets processed before we are done with the notifying, so we should be good 👍

File: chainntnfs/neutrinonotify/neutrino.go [hunk 8]
```diff
@@ -696,18 +711,23 @@ func (n *NeutrinoNotifier) RegisterConfirmationsNtfn(txid *chainhash.Hash,
...
 		ConfNtfn: chainntnfs.ConfNtfn{
+			ID:               atomic.AddUint64(&n.confClientCounter, 1),
 			TxID:             txid,
 			NumConfirmations: numConfs,
 			Event:            chainntnfs.NewConfirmationEvent(numConfs),
 		},
 		heightHint: heightHint,
 	}
 
+	if err := n.txConfNotifier.Register(&ntfn.ConfNtfn); err != nil {
```
Comment (halseth) [inline chainntnfs/neutrinonotify/neutrino.go]: Can we just move this call to where we are handling the `confirmationsNotification`, before we start the historical dispatch?

File: chainntnfs/neutrinonotify/neutrino.go [hunk 9]
```diff
@@ -307,31 +307,45 @@ func (n *NeutrinoNotifier) notificationDispatcher() {
...
+						msg.TxID, currentHeight,
+						msg.heightHint,
+					)
+					if err != nil {
+						chainntnfs.Log.Error(err)
+					}
+
+					if confDetails != nil {
+						err := n.txConfNotifier.UpdateConfDetails(
+							*msg.TxID, msg.ID,
```
Comment (halseth) [inline chainntnfs/neutrinonotify/neutrino.go]: Not sure if we actually need the new `ID` if we can just pass the `ConfNtfn` in here instead.

File: chainntnfs/btcdnotify/btcd.go [hunk 10]
```diff
@@ -800,6 +801,7 @@ func (b *BtcdNotifier) RegisterConfirmationsNtfn(txid *chainhash.Hash,
 
 	ntfn := &confirmationNotification{
 		ConfNtfn: chainntnfs.ConfNtfn{
+			ID:               atomic.AddUint64(&b.confClientCounter, 1),
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/btcdnotify/btcd.go]: Fixed.

File: chainntnfs/txconfnotifier.go [hunk 11]
```diff
@@ -108,49 +111,100 @@ func NewTxConfNotifier(startHeight uint32, reorgSafetyLimit uint32) *TxConfNotif
...
+		ntfns = make(map[uint64]*ConfNtfn)
+		tcn.confNotifications[*ntfn.TxID] = ntfns
+	}
+
+	ntfns[ntfn.ID] = ntfn
+
+	return nil
+}
+
+// UpdateConfDetails attempts to mark an existing unconfirmed transaction as
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/txconfnotifier.go]: Forgot to update it. Fixed.

File: chainntnfs/bitcoindnotify/bitcoind.go [hunk 12]
```diff
@@ -243,27 +243,37 @@ out:
...
-				if err != nil {
-					chainntnfs.Log.Error(err)
-				}
+				currentHeight := uint32(bestHeight)
+
+				// Look up whether the transaction is already
+				// included in the active chain. We'll do this
+				// in a goroutine to prevent blocking
+				// potentially long rescans.
+				go func() {
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/bitcoindnotify/bitcoind.go]: Not sure if it's really needed here 🤔

File: chainntnfs/bitcoindnotify/bitcoind.go [hunk 13]
```diff
@@ -243,27 +243,37 @@ out:
...
-				// active chain.
-				txConf, err := b.historicalConfDetails(
-					msg.TxID, msg.heightHint, uint32(currentHeight),
-				)
-				if err != nil {
-					chainntnfs.Log.Error(err)
-				}
+					if confDetails != nil {
+						err := b.txConfNotifier.UpdateConfDetails(
+							*msg.TxID, msg.ID,
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/bitcoindnotify/bitcoind.go]: I think it's better to keep it as is to make sure the notification has been registered with the notifier first.

File: chainntnfs/neutrinonotify/neutrino.go (hunk 8 above)
Comment (wpaulino) [reply chainntnfs/neutrinonotify/neutrino.go]: We can, but I figured it made more sense having it here like we do with `NotifySpent` with `RegisterSpendNtfn`.

File: chainntnfs/neutrinonotify/neutrino.go (hunk 9 above)
Comment (wpaulino) [reply chainntnfs/neutrinonotify/neutrino.go]: Same comment as above w.r.t. ensuring the notification has been registered first.

File: chainntnfs/txconfnotifier.go [hunk 14]
```diff
@@ -108,49 +111,105 @@ func NewTxConfNotifier(startHeight uint32, reorgSafetyLimit uint32) *TxConfNotif
...
+		return fmt.Errorf("no notification found with ID %v", clientID)
+	}
+
+	// If the notification has already recognized that the transaction
+	// confirmed, there's nothing left for us to do.
+	if ntfn.details != nil {
+		return nil
+	}
+
+	// The notifier has yet to reach the height at which the transaction was
```
Comment (Roasbeef) [inline chainntnfs/txconfnotifier.go]: This is a bit confusing, how would we _ever_ know in advance if the conf intent is already satisfied? Seems like it should read `DispatchBlockHeight` here instead of just a block height.

Comment (Roasbeef) [reply chainntnfs/txconfnotifier.go]: If it's the block height that the transaction was _initially_ confirmed at, why can we determine this independent of the notifier itself advancing? Do we have a test to exercise this case?

File: chainntnfs/bitcoindnotify/bitcoind.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply chainntnfs/bitcoindnotify/bitcoind.go]: Yeah I don't think it's needed here. Otherwise a very distant rescan can cause the shutdown process to be held up.

File: chainntnfs/neutrinonotify/neutrino.go [hunk 15]
```diff
@@ -307,31 +307,45 @@ func (n *NeutrinoNotifier) notificationDispatcher() {
...
+					// confirmation, then we'll update our
+					// filter so we can be notified of its
+					// future initial confirmation.
 					rescanUpdate := []neutrino.UpdateOption{
 						neutrino.AddTxIDs(*msg.TxID),
 						neutrino.Rewind(currentHeight),
 					}
-					if err := n.chainView.Update(rescanUpdate...); err != nil {
-						chainntnfs.Log.Errorf("unable to update rescan: %v", err)
+					err = n.chainView.Update(rescanUpdate...)
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply chainntnfs/neutrinonotify/neutrino.go]: What do you mean by this @halseth ?

File: chainntnfs/bitcoindnotify/bitcoind.go [hunk 16]
```diff
@@ -237,7 +241,7 @@ out:
 					b.spendNotifications[op] = make(map[uint64]*spendNotification)
 				}
 				b.spendNotifications[op][msg.spendID] = msg
-				b.chainConn.NotifySpent([]*wire.OutPoint{&op})
```
Comment (Roasbeef) [inline chainntnfs/bitcoindnotify/bitcoind.go]: Looks like this was a duplicate call even? We already do this at notification registration site.

File: chainntnfs/txconfnotifier.go (hunk 14 above)
Comment (wpaulino) [reply chainntnfs/txconfnotifier.go]: The reason behind the check is due to the lag between the `TxConfNotifier` and the backend. For example, let's say that the notifier starts at height 100 and the the transaction confirms at 102. The backend moves up to 102, but the `TxConfNotifier` is still processing height 101. In the event that `UpdateConfDetails` is called before `ConnectTip(..., 102, ...)`, the notifier isn't yet aware of this height, so we defer until handling the notification dispatch until then.

Not sure what you mean by `DispatchBlockHeight`. Are you referring to renaming the method `UpdateConfDetails` to that?

File: chainntnfs/txconfnotifier.go [hunk 17]
```diff
@@ -98,49 +111,105 @@ func NewTxConfNotifier(startHeight uint32, reorgSafetyLimit uint32) *TxConfNotif
...
 		return nil
 	}
 
-	// If the transaction already has the required confirmations, we'll
-	// dispatch the notification immediately.
-	confHeight := txConf.BlockHeight + ntfn.NumConfirmations - 1
+	// The notifier has yet to reach the height at which the transaction was
+	// included in a block, so we should defer until handling it then within
+	// ConnectTip.
+	if details.BlockHeight > tcn.currentHeight {
```
Comment (cfromknecht) [inline chainntnfs/txconfnotifier.go]: this line will panic if `details` is nil, which is possible as written. Might want to add a test for this

File: chainntnfs/txconfnotifier.go [hunk 18]
```diff
@@ -3,15 +3,26 @@ package chainntnfs
...
+	"sync"
 
 	"github.com/btcsuite/btcd/chaincfg/chainhash"
 	"github.com/btcsuite/btcutil"
 )
 
+var (
+	// ErrTxConfNotifierExiting is an error returned when attempting to
+	// interact with the TxConfNotifier but it been shut down.
+	ErrTxConfNotifierExiting = errors.New("TxConfNotifier is exiting")
```
Comment (cfromknecht) [inline chainntnfs/txconfnotifier.go]: 👍

File: chainntnfs/bitcoindnotify/bitcoind.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (cfromknecht) [reply chainntnfs/bitcoindnotify/bitcoind.go]: we could thread a quit chan down to the rescan if we want. thinking it might be a good idea actually, to prevent the rescan from causing an accidental panic after the chain conns are deinitialized

File: chainntnfs/neutrinonotify/neutrino.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (halseth) [reply chainntnfs/neutrinonotify/neutrino.go]: We are passing in `currentHeight`, which might be outdated at this point (because of potential long-running `historicalConfDetails`). I think this should be okay, but just meant that we should check that it indeed is.

File: chainntnfs/neutrinonotify/neutrino.go (hunk 8 above)
Comment (halseth) [reply chainntnfs/neutrinonotify/neutrino.go]: For readability I think it would make sense to move it there, as they always need to be called in that order, right after one another, right?

File: chainntnfs/bitcoindnotify/bitcoind.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (halseth) [reply chainntnfs/bitcoindnotify/bitcoind.go]: I think it's a nice pattern to follow, as also test failures tend to be harder to trace if there are stray go routines remaining.

File: chainntnfs/bitcoindnotify/bitcoind.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (halseth) [reply chainntnfs/bitcoindnotify/bitcoind.go]: if moving the `Register` call right before, that would make those call more tightly coupled, and i think even the whole `ConfID` can be removed?

**Comment by halseth** [comment]
Mostly LGTM now (after addressing Conner's comments). I still think the `Register` should be moved though, as that will entail a smaller structural change from the existing code, and aids readability IMO. It also makes it possible to simplify a bit by removing the `ConfIDs`.

File: chainntnfs/neutrinonotify/neutrino.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (cfromknecht) [reply chainntnfs/neutrinonotify/neutrino.go]: Good point, it's likely we'd rescan all of the manual dispatch done before? Since current height is behind a mutex, should be safe to read again?

File: chainntnfs/bitcoindnotify/bitcoind.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/bitcoindnotify/bitcoind.go]: Fixed.

File: chainntnfs/bitcoindnotify/bitcoind.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/bitcoindnotify/bitcoind.go]: Sure, but then it's expected for the caller to know this, rather than just providing an interface that ensures the notification has been registered first. Having an ID will also come in handy when adding support for cancelling existing notifications (there's an existing TODO for this).

File: chainntnfs/neutrinonotify/neutrino.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/neutrinonotify/neutrino.go]: `currentHeight` is a copy so it should remain unchanged even if the actual height changes.

File: chainntnfs/neutrinonotify/neutrino.go (hunk 8 above)
Comment (wpaulino) [reply chainntnfs/neutrinonotify/neutrino.go]: `Register` must now be called first. Since it's possible that it fails, we should return the error to the caller rather than just logging it, as otherwise the caller will be expecting to receive the confirmation details for a failed registration. At the moment, it's unlikely for it to return an error other than when shutting down, but it could prevent an obscure bug later down the road.

File: chainntnfs/bitcoindnotify/bitcoind.go [hunk 19]
```diff
@@ -54,12 +58,13 @@ type chainUpdate struct {
 // chain client. Multiple concurrent clients are supported. All notifications
 // are achieved via non-blocking sends on client channels.
 type BitcoindNotifier struct {
-	spendClientCounter uint64 // To be used atomically.
-	epochClientCounter uint64 // To be used atomically.
-
 	started int32 // To be used atomically.
 	stopped int32 // To be used atomically.
 
+	confClientCounter  uint64 // To be used atomically.
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/bitcoindnotify/bitcoind.go]: Fixed.

File: chainntnfs/btcdnotify/btcd.go [hunk 20]
```diff
@@ -61,12 +61,13 @@ type txUpdate struct {
 // notifications. Multiple concurrent clients are supported. All notifications
 // are achieved via non-blocking sends on client channels.
 type BtcdNotifier struct {
-	spendClientCounter uint64 // To be used atomically.
-	epochClientCounter uint64 // To be used atomically.
-
 	started int32 // To be used atomically.
 	stopped int32 // To be used atomically.
 
+	confClientCounter  uint64 // To be used aotmically.
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/btcdnotify/btcd.go]: Fixed.

File: chainntnfs/txconfnotifier.go (hunk 17 above)
Comment (wpaulino) [reply chainntnfs/txconfnotifier.go]: Fixed.

File: chainntnfs/txconfnotifier.go [hunk 21]
```diff
@@ -108,49 +111,105 @@ func NewTxConfNotifier(startHeight uint32, reorgSafetyLimit uint32) *TxConfNotif
...
+		ntfns = make(map[uint64]*ConfNtfn)
+		tcn.confNotifications[*ntfn.TxID] = ntfns
+	}
+
+	ntfns[ntfn.ConfID] = ntfn
+
+	return nil
+}
+
+// UpdateConfDetails attempts to update the confirmation details for the an
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply chainntnfs/txconfnotifier.go]: Fixed.
