### PR TITLE
Ability to spend unconfirmed coins when making onchain transactions

### LINKED ISSUE #4644: Ability to spend unconfirmed utxos with sendcoins RPC
### Background

Add ability to spend unconfirmed outputs when making onchain transactions.

When opening channels it is possible to spend unconfirmed outputs by passing `spend_unconfirmed` as part of the openChannel call.

Suggest adding the same `spend_unconfirmed` flag for `sendcoins` RPC.

### Your environment

* version of `lnd`: 0.11
* which operating system (`uname -a` on *Nix) : mac
* version of `btcd`, `bitcoind`, or other backend: bitcoind

### Steps to reproduce

Deposit coins onto a fresh node, then try to make a couple of onchain payments. They can fail when change outputs are unconfirmed.

### Expected behaviour

I should be able to spend the coins from my wallet.

### Actual behaviour

I can't spend them because some are unconfirmed.

### PR DESCRIPTION
**Pull request by mrfelton**
Initial stab at adding support for spending unconfirmed outputs when making onchain transactions. Affects the following RPCs:

- `Lightning.SendCoins`
- `Lightning.SendMany`
- `WalletKit.SendOutputs`

Adds two new parameters for these methods, following the same format as used for `Lightning.OpenChannel` RPC:

- `min_confs` (default=1)
- ` spend_unconfirmed` (default=false)

Needs some code cleanup and consolidation but wanted to drop it here to get thoughts on the approach before I take it any further.

Fix #4644

### CODE REVIEW

File: lnrpc/walletrpc/walletkit_server.go [hunk 1]
```diff
@@ -473,6 +473,13 @@ func (w *WalletKit) SendOutputs(ctx context.Context,
 		})
 	}
 
+	// Then, we'll extract the minimum number of confirmations that each
+	// output we use to fund the transaction should satisfy.
+	minConfs, err := extractSendOutputsMinConfs(req)
```
Comment (halseth) [inline lnrpc/walletrpc/walletkit_server.go:478]: We should share this method between all RPCs having the same `spend_unconfirmed/min_confs` params (including `OpenChannel`).

File: lnwallet/btcwallet/btcwallet.go [hunk 2]
```diff
@@ -309,7 +309,7 @@ func (b *BtcWallet) SendOutputs(outputs []*wire.TxOut,
 	}
 
 	return b.wallet.SendOutputs(
-		outputs, defaultAccount, 1, feeSatPerKB, label,
+		outputs, defaultAccount, minconf, feeSatPerKB, label,
```
Comment (halseth) [inline lnwallet/btcwallet/btcwallet.go:312]: sanity check `minConfs` above?

File: rpcserver.go [hunk 3]
```diff
@@ -1623,6 +1639,78 @@ func extractOpenChannelMinConfs(in *lnrpc.OpenChannelRequest) (int32, error) {
 	}
 }
 
+// extractSendCoinsMinConfs extracts the minimum number of confirmations from
+// the SendCoinsRequest that each output used to fund the transaction should
+// satisfy.
+func extractSendCoinsMinConfs(in *lnrpc.SendCoinsRequest) (int32, error) {
```
Comment (halseth) [inline rpcserver.go:1645]: we can share this logic by passing in `MinConfs and `SpendUnconfirmed` instead of the RPC specific request.

**Review by halseth — CHANGES_REQUESTED** [review]
Thanks, looks good! Main comment is about sharing the extraction logic between all callers. 

A test for the new behavior would also be nice :)

File: rpcserver.go (hunk 3 above)
Comment (mrfelton) [reply rpcserver.go:1645]: Yeah, this is what I meant by "needs consolidation" :)... Can you suggest where this more general utility method should live in the codebase?

File: lnrpc/walletrpc/walletkit_server.go (hunk 1 above)
Comment (mrfelton) [reply lnrpc/walletrpc/walletkit_server.go]: update

File: lnwallet/btcwallet/btcwallet.go (hunk 2 above)
Comment (mrfelton) [reply lnwallet/btcwallet/btcwallet.go:317]: Added sanity check

File: rpcserver.go (hunk 3 above)
Comment (mrfelton) [reply rpcserver.go]: Extracted to more generalised `lnrpc.ExtractMinConfs` utility method.

**Comment by Roasbeef** [comment]
TBH, I'm a bit weary of this, mainly because I'm not confident that we've patched all the known/under-investigation issues w.r.t spending zero conf inputs within `btcwallet` itself. In the end though, it's something we've been wanting to refocus on to fumigate any existing bugs we may be aware of in that area. The worst case scenario with the class of bugs I'm referring to us that the UTXO set of the wallet gets out of sync, and a wallet rescan is required (`droptxtmgr`). Related to that is that imo we should also expose that as an easy RPC call so people don't need to mess around w/ manually running a command on their DB file.

File: rpcserver.go [hunk 4]
```diff
@@ -1180,8 +1181,16 @@ func (r *rpcServer) SendCoins(ctx context.Context,
...
-	rpcsLog.Infof("[sendcoins] addr=%v, amt=%v, sat/kw=%v, sweep_all=%v",
-		in.Addr, btcutil.Amount(in.Amount), int64(feePerKw),
+	// Then, we'll extract the minimum number of confirmations that each
+	// output we use to fund the transaction should satisfy.
+	minConfs, err := extractSendCoinsMinConfs(in)
+	if err != nil {
+		return nil, err
+	}
+
+	rpcsLog.Infof("[sendcoins] addr=%v, amt=%v, sat/kw=%v, minConfs=%v, "+
```
Comment (wpaulino) [inline rpcserver.go:1191]:
```suggestion
	rpcsLog.Infof("[sendcoins] addr=%v, amt=%v, sat/kw=%v, min_confs=%v, "+
```

**Review by wpaulino — COMMENTED** [review]
@mrfelton could you squash the commits resulting from review feedback into the main commit?

**Comment by wpaulino** [comment]
> TBH, I'm a bit weary of this, mainly because I'm not confident that we've patched all the known/under-investigation issues w.r.t spending zero conf inputs within btcwallet itself.

I agree, as far as I'm aware though, the latest instance of this bug was with the change to only scan default scopes, which has been reverted now. If anything, adding this feature will only help expose any remaining unknown bugs, with the potential drawback of many users having to perform a wallet rescan (having a RPC to do so would certainly help).

File: rpcserver.go (hunk 4 above)
Comment (mrfelton) [reply rpcserver.go]: updated

**Comment by mrfelton** [comment]
> @mrfelton could you squash the commits resulting from review feedback into the main commit?

squashed and rebased

**Comment by mrfelton** [comment]
> TBH, I'm a bit weary of this, mainly because I'm not confident that we've patched all the known/under-investigation issues w.r.t spending zero conf inputs within btcwallet itself.

I can't really talk to this since I'm not so familiar, but from my perspective I don't see that this PR is adding anything new to that. We already allow users to spend unconfirmed outputs when opening channels. So I'd tend to agree with @wpaulino that making this more accessible would be a good thing if it helps to expose unidentified bugs with the underlaying wallet functionality.

**Comment by mrfelton** [comment]
> A test for the new behavior would also be nice :)

I've added a new test case that verifies spending unconfirmed outputs works.

File: lnwallet/interface_test.go [hunk 5]
```diff
@@ -2376,6 +2372,79 @@ func testChangeOutputSpendConfirmation(r *rpctest.Harness,
...
+	output := &wire.TxOut{
+		Value:    int64(bobBalance - txFee),
+		PkScript: alicePkScript,
+	}
+	tx := sendCoins(t, miner, bob, alice, output, txFeeRate, true, 1)
+	txHash := tx.TxHash()
+	assertTxInWallet(t, alice, txHash, true)
+	assertTxInWallet(t, bob, txHash, true)
+
+	// Next we will send a transaction to bob but leave it in an
```
Comment (halseth) [inline lnwallet/interface_test.go:2397]: before sending Bob the coins here, check that Bob fails to send coins because he has no balance. That way we can be sure the later transaction he sends is funded by the unconfirmed output.

File: lnwallet/interface_test.go [hunk 6]
```diff
@@ -2376,6 +2372,79 @@ func testChangeOutputSpendConfirmation(r *rpctest.Harness,
...
+	assertTxInWallet(t, alice, txHash, false)
+	assertTxInWallet(t, bob, txHash, false)
+
+	// Now, try to spend some of the unconfirmed funds from bob's wallet.
+	alicePkScript = newPkScript(t, alice, lnwallet.WitnessPubKey)
+	output = &wire.TxOut{
+		Value:    btcutil.SatoshiPerBitcoin * 0.5,
+		PkScript: alicePkScript,
+	}
+	tx = sendCoins(t, miner, bob, alice, output, txFeeRate, false, 0)
```
Comment (halseth) [inline lnwallet/interface_test.go:2415]: similarly, before calling this, attempt to send coins using minconfs=1 and make sure that fails.

**Review by halseth — CHANGES_REQUESTED** [review]
Great change! Two suggestions for additions to the test, otherwise this looks good 👍

File: lnwallet/interface_test.go (hunk 5 above)
Comment (mrfelton) [reply lnwallet/interface_test.go:2397]: Good idea. Updated.

File: lnwallet/interface_test.go (hunk 6 above)
Comment (mrfelton) [reply lnwallet/interface_test.go:2415]: Updated

**Review by wpaulino — APPROVED** [review]

**Comment by wpaulino** [comment]
The linter is failing at the proto verification step, looks like you need to run `make rpc` and commit those changes.
https://travis-ci.org/github/lightningnetwork/lnd/jobs/731267269

**Comment by mrfelton** [comment]
Regenerated protos

File: lnwallet/interface_test.go (hunk 5 above)
Comment (halseth) [reply lnwallet/interface_test.go:2397]: I don't see the change?

File: lnwallet/interface_test.go (hunk 6 above)
Comment (halseth) [reply lnwallet/interface_test.go:2415]: Same here, no change?

**Review by halseth — CHANGES_REQUESTED** [review]
Did you forget to push the test additions?

File: lnwallet/interface_test.go (hunk 5 above)
Comment (mrfelton) [reply lnwallet/interface_test.go:2411]: Ahh, bad rebase. Should be back now

File: lnwallet/interface_test.go [hunk 7]
```diff
@@ -2376,6 +2372,101 @@ func testChangeOutputSpendConfirmation(r *rpctest.Harness,
...
+	// Verify that bob doesn't have enough balance to send coins.
+	output = &wire.TxOut{
+		Value:    btcutil.SatoshiPerBitcoin * 0.5,
+		PkScript: alicePkScript,
+	}
+	tx, err = bob.SendOutputs(
+		[]*wire.TxOut{output}, txFeeRate, 0, labels.External,
+	)
+	if err == nil {
+		t.Fatalf("should have not been able to pay due to insufficient balance: %v", err)
```
Comment (halseth) [inline lnwallet/interface_test.go:2408]: nit: error is nil so no need to print it

File: lnwallet/interface_test.go (hunk 5 above)
Comment (halseth) [reply lnwallet/interface_test.go:2411]: Yep! 👍

**Review by halseth — APPROVED** [review]
Thanks, LGTM ✅

**Comment by halseth** [comment]
Linter is failing.

**Comment by mrfelton** [comment]
> Linter is failing.

doh! 😞  . Ok, that's fixed now!
