### PR TITLE
graph: fix inefficient query for IsPublicNode

### LINKED ISSUE #10337: [bug]: Graph SQL implementation results in some performance issues
### Pre-Submission Checklist

- [x] I have searched the existing issues and believe this is a new bug.
- [x] I am not asking a question about how to use lnd, but reporting a bug (otherwise open a discussion).

### LND Version

0.20 rc3

### LND Configuration

native sql storage active.

### Backend Version

neutrino

### Backend Configuration

-

### OS/Distribution

-

### Bug Details & Steps to Reproduce

# IsPublicNode Performance Bottleneck Analysis

## Executive Summary

CPU profiling reveals that `IsPublicNode` queries consume **62.36% of total CPU time** (21.77s out of 34.91s) during gossip message processing. This represents a critical performance bottleneck in LND's gossip subsystem that significantly impacts node synchronization and network message processing throughput.

## Problem Description

The `IsPublicNode` function is called for every node announcement received from the Lightning Network gossip protocol. During the profiling period of 10.10 seconds, this function was sampled 2,177 times, indicating extremely high call frequency.

### Call Stack
```
discovery.(*AuthenticatedGossiper).handleNodeAnnouncement (62.50% CPU)
  ↓
graph.(*Builder).IsPublicNode (62.36% CPU)
  ↓
graph/db.(*SQLStore).IsPublicNode (62.36% CPU)
  ↓
SQLite query execution (IsPublicV1Node)
```

### Profile Evidence
```
Duration: 10.10s, Total samples = 34.91s (345.47%)
      flat  flat%   sum%        cum   cum%
         0     0%     0%     21.86s 62.62%  discovery.(*AuthenticatedGossiper).processNetworkAnnouncement
         0     0%     0%     21.82s 62.50%  discovery.(*AuthenticatedGossiper).handleNodeAnnouncement
         0     0%     0%     21.77s 62.36%  graph.(*Builder).IsPublicNode
         0     0%     0%     21.77s 62.36%  graph/db.(*SQLStore).IsPublicNode
```

### 1. Inefficient SQL Query Structure

**Location:** `sqldb/sqlc/queries/graph.sql:55-71`

```sql
-- name: IsPublicV1Node :one
SELECT EXISTS (
    SELECT 1
    FROM graph_channels c
    JOIN graph_nodes n ON n.id = c.node_id_1 OR n.id = c.node_id_2
    WHERE c.version = 1
      AND c.bitcoin_1_signature IS NOT NULL
      AND n.pub_key = $1
);
```

**Problem:** The `OR` condition in the JOIN clause (`n.id = c.node_id_1 OR n.id = c.node_id_2`) prevents SQLite from efficiently utilizing indexes. This forces a full or near-full table scan of `graph_channels` for each query.

**Existing Indexes:**
- `graph_channels_node_id_1_idx` on `node_id_1`
- `graph_channels_node_id_2_idx` on `node_id_2`
- `graph_nodes_unique` on `(pub_key, version)`

Despite these indexes, the OR condition in the JOIN prevents their effective use.

### 2. High Call Frequency

**Location:** `discovery/gossiper.go:2519`

```go
func (d *AuthenticatedGossiper) handleNodeAnnouncement(...) {
    // ... node already added to database at line 2499
    if err := d.addNode(ctx, nodeAnn, ops...); err != nil {
        // error handling
    }

    // IsPublicNode called AFTER node is added
    isPublic, err := d.cfg.Graph.IsPublicNode(nodeAnn.NodeID)
    if err != nil {
        // error handling
    }

    // Only used to decide whether to broadcast
    if isPublic {
        announcements = append(announcements, networkMsg{...})
    }
}
```

This function is called for **every node announcement** received, including:
- Initial gossip sync (thousands of announcements)
- Real-time gossip updates
- Re-announcements from peers

### 3. Redundant Database Operations

The query is executed **after** the node has already been added to the database. The check is only used to determine if the announcement should be rebroadcast to peers, but it requires scanning the entire channel graph each time.

### 4. Lock Contention

Secondary performance impact from database locking:
```
12.81s (36.69%) - syscall.syscall6
 8.75s (25.06%) - pthread_cond_wait
 5.67s (16.24%) - pthread_cond_signal
 5.34s (15.30%) - SQLite mutex operations
```

Multiple goroutines competing for database access during high-frequency queries exacerbates the problem.

### Quantitative Analysis
- **62.36% of CPU time** spent in a single query type
- **2,177 calls** in 10 seconds = ~217 calls/second
- **~10ms average per call** under load
- During initial sync with thousands of node announcements, this becomes a significant synchronization bottleneck

### User Impact
- Slower initial blockchain/graph synchronization
- Reduced gossip message processing throughput
- Increased CPU usage during normal operation
- Potential for gossip message queue backlog

### Solution 1: Query Rewrite with UNION (Immediate Fix)

**Complexity:** Low
**Impact:** High
**Risk:** Low

Rewrite the query to use UNION instead of OR, allowing index usage:

```sql
-- name: IsPublicV1Node :one
SELECT EXISTS (
    SELECT 1 FROM (
        SELECT c.id
        FROM graph_channels c
        JOIN graph_nodes n ON n.id = c.node_id_1
        WHERE c.version = 1
          AND c.bitcoin_1_signature IS NOT NULL
          AND n.pub_key = $1
        UNION
        SELECT c.id
        FROM graph_channels c
        JOIN graph_nodes n ON n.id = c.node_id_2
        WHERE c.version = 1
          AND c.bitcoin_1_signature IS NOT NULL
          AND n.pub_key = $1
    )
);
```

**Benefits:**
- Allows SQLite to use `graph_channels_node_id_1_idx` and `graph_channels_node_id_2_idx`
- No code changes required, only SQL modification
- Backward compatible

**Estimated Impact:** 10-50x performance improvement

### Solution 2: In-Memory Cache (Medium-term)

**Complexity:** Medium
**Impact:** Very High
**Risk:** Medium

Implement an LRU cache for `IsPublicNode` results:

```go
type PublicNodeCache struct {
    cache *lru.Cache
    mu    sync.RWMutex
}

func (s *SQLStore) IsPublicNode(pubKey [33]byte) (bool, error) {
    // Check cache first
    if cached, ok := s.publicNodeCache.Get(pubKey); ok {
        return cached.(bool), nil
    }

    // Query database
    isPublic, err := s.isPublicNodeQuery(pubKey)
    if err != nil {
        return false, err
    }

    // Cache result
    s.publicNodeCache.Add(pubKey, isPublic)
    return isPublic, nil
}
```

**Cache Invalidation Strategy:**
- Invalidate on channel addition/removal for affected nodes
- TTL of 5-10 minutes as safety mechanism
- Size limit of 10,000-50,000 entries (manageable memory footprint)

**Benefits:**
- Near-zero latency for repeated lookups
- Dramatically reduces database load
- Node public status rarely changes

**Challenges:**
- Cache invalidation complexity
- Memory overhead (acceptable: ~1-2MB for 50K entries)

**Estimated Impact:** 100-1000x improvement for cache hits

### Solution 3: Denormalize Public Status (Long-term)

**Complexity:** High
**Impact:** Very High
**Risk:** Medium-High

Add `is_public` boolean column to `graph_nodes` table:

```sql
ALTER TABLE graph_nodes ADD COLUMN is_public BOOLEAN DEFAULT FALSE;
CREATE INDEX graph_nodes_is_public_idx ON graph_nodes(is_public, pub_key);
```

Update logic:
- Compute `is_public` when channels are added/removed
- Simple `SELECT is_public FROM graph_nodes WHERE pub_key = $1` query
- No JOIN required

**Benefits:**
- O(1) lookup via primary key
- Eliminates JOIN entirely
- Most efficient long-term solution

**Challenges:**
- Schema migration required
- Complex update logic when channels change
- Need to backfill existing data
- Increased write complexity

**Estimated Impact:** 1000x+ improvement

### Solution 4: Batch Processing

**Complexity:** Medium
**Impact:** Medium
**Risk:** Low

Accumulate node announcements and check public status in batches:

```go
func (d *AuthenticatedGossiper) batchCheckPublicNodes(nodes [][33]byte) (map[[33]byte]bool, error) {
    // Single query with WHERE pub_key IN (?, ?, ...)
    return d.cfg.Graph.IsPublicNodeBatch(nodes)
}
```

**Benefits:**
- Reduces query count
- Better database query planner utilization
- Lower transaction overhead

**Challenges:**
- Increases latency for individual announcements
- Requires refactoring of gossip processing pipeline

**Estimated Impact:** 5-10x improvement

## Recommended Approach

**Phase 1 (Immediate):** Implement Solution 1 (Query Rewrite)
- Low risk, high reward
- Can be deployed immediately
- No architectural changes

**Phase 2 (Short-term):** Implement Solution 2 (LRU Cache)
- Combines with Phase 1 for maximum impact
- Cache hit rate likely >90% during normal operation
- Proven pattern already used in LND codebase

**Phase 3 (Long-term):** Consider Solution 3 (Denormalization)
- Evaluate based on Phase 1 & 2 results
- If performance is still inadequate, pursue denormalization
- Coordinate with graph database refactoring efforts

## Testing Recommendations

1. **Benchmark Testing:**
   - Create benchmark comparing current vs. optimized query
   - Test with realistic graph sizes (80K+ channels)
   - Measure under concurrent load

2. **Integration Testing:**
   - Test during initial sync
   - Test with high gossip message rate
   - Verify cache invalidation correctness (if implemented)

3. **Performance Validation:**
   - CPU profiling before/after
   - Gossip throughput measurement
   - Sync time comparison

## References

- CPU Profile: `cpu.prof` (Duration: 10.10s, Total samples: 34.91s)
- Code Locations:
  - Query: `sqldb/sqlc/queries/graph.sql:55-71`
  - Caller: `discovery/gossiper.go:2519`
  - DB Schema: `sqldb/sqlc/migrations/000008_graph.up.sql`

### Option A: Separate Lookups
```sql
SELECT EXISTS (
    SELECT 1 FROM graph_channels c
    WHERE c.version = 1
      AND c.bitcoin_1_signature IS NOT NULL
      AND (c.node_id_1 = (SELECT id FROM graph_nodes WHERE pub_key = $1)
           OR c.node_id_2 = (SELECT id FROM graph_nodes WHERE pub_key = $1))
);
```
**Status:** Still uses OR, similar performance

### Option B: IN clause
```sql
SELECT EXISTS (
    SELECT 1 FROM graph_channels c
    WHERE c.version = 1
      AND c.bitcoin_1_signature IS NOT NULL
      AND (SELECT id FROM graph_nodes WHERE pub_key = $1) IN (c.node_id_1, c.node_id_2)
);
```
**Status:** Better than OR, worse than UNION

### Expected Behavior

-

### Debug Information

_No response_

### Environment

_No response_

### PR DESCRIPTION
**Pull request by Abdulkbk**
fixes #10337 (partially)

## Change Description
In this PR, we rewrite the query for `IsPublicV1Node`, which returns a boolean based on if a node has a public or private channel. This particularly fixes an issue `sqlite` backend as it struggles to efficiently use multiple indexes across seperate columns in one query.

## Step to test
```bash
cd graph/db

go test -tags test_db_sqlite  -run TestNodeIsPublic -v # ensure we still correctly distinguish between pub & priv
```

### CODE REVIEW

**Comment by ziggie1984** [comment]
can you create some stress tests to see whether union is actually better ?

**Comment by Abdulkbk** [comment]
> can you create some stress tests to see whether union is actually better ?

I added a benchmark as the first commit, the following is what I found after running:
```bash
go test -tags=test_db_sqlite -bench=BenchmarkIsPublicNode  > sqlite_or.txt

# then

go test -tags=test_db_sqlite -bench=BenchmarkIsPublicNode  > sqlite_union.txt

# finally
benchstat sqlite_or.txt sqlite_union.txt 
```
| Query Type | Iterations (`b.N`) | Time per op (`ns/op`) |
|-------------|--------------------|-------------------|
| **UNION ALL** | 388 | 3,009,488 ns/op (~3ms) |
| **OR** | 289 | 4,063,903 ns/op (~4ms)|

The fact that this benchmark is run with approximately 8k nodes means that, if the number of nodes is increased to around ~80k, the difference will become more noticeable.

File: graph/db/graph_test.go [hunk 1]
```diff
@@ -3995,6 +3997,25 @@ func TestNodeIsPublic(t *testing.T) {
 	)
 }
 
+// BenchmarkIsPublicNode measures the performance of IsPublicNode when checking
+// a large number of nodes.
+func BenchmarkIsPublicNode(b *testing.B) {
+	graph := MakeTestGraph(b)
+
+	// Create a graph with a reasonable number of nodes and channels.
+	numNodes := 8000
```
Comment (MPins) [inline graph/db/graph_test.go]: After changing the number of nodes to 16000 I got: 

*** SELECT WITH UNION ***

`go test -tags=test_db_sqlite -bench=BenchmarkIsPublicNode`

```
goos: linux
goarch: amd64
pkg: github.com/lightningnetwork/lnd/graph/db
cpu: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     
BenchmarkIsPublicNode-16    	      93	  11939604 ns/op
--- BENCH: BenchmarkIsPublicNode-16
    test_sqlite.go:49: Creating new SQLite DB for testing
PASS
ok  	github.com/lightningnetwork/lnd/graph/db	212.488s
```

Then changed the go.mod line 216:

from `replace github.com/lightningnetwork/lnd/sqldb => ./sqldb`
to `//replace github.com/lightningnetwork/lnd/sqldb => ./sqldb`

*** SELECT USING OR ***
And ran it again :

```
goos: linux
goarch: amd64
pkg: github.com/lightningnetwork/lnd/graph/db
cpu: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     
BenchmarkIsPublicNode-16    	      48	  24982592 ns/op
--- BENCH: BenchmarkIsPublicNode-16
    test_sqlite.go:49: Creating new SQLite DB for testing
PASS
ok  	github.com/lightningnetwork/lnd/graph/db	228.831s
```

The `BenchmarkIsPublicNode` using `SELECT WITH UNION` took 11.9ms and using `SELECT WITH OR` 24.9ms.

File: graph/db/graph_test.go [hunk 2]
```diff
@@ -3995,6 +3997,25 @@ func TestNodeIsPublic(t *testing.T) {
...
+	numChans := 4
+	_, nodes := fillTestGraph(b, graph, numNodes, numChans)
+
+	// Pick a random node to test.
```
Comment (MPins) [inline graph/db/graph_test.go]: As it is not a random number, I would change the comment to reflect and explain your choice.

File: graph/db/graph_test.go [hunk 3]
```diff
@@ -3995,6 +3997,25 @@ func TestNodeIsPublic(t *testing.T) {
...
+	nodePub := nodes[len(nodes)/2].PubKeyBytes
+
```
Comment (MPins) [inline graph/db/graph_test.go:4059]: You could add the `b.ResetTimer()` if you want to clean the results from the setup overhead.

I did it and there is not a big impact to the numbers, but I thing it is better to use the clean numbers:

`SELECT USING UNION`
8k nodes without reset `9719683 ns/op`, after reset `9644365 ns/op`
16k nodes without reset `20125172 ns/op`, after reset `191052752 ns/op`

`SELECT USING OR`
8k nodes without reset `11786240 ns/op`, after reset `11426299 ns/op`
16k nodes without reset `24982592 ns/op`, after reset `24353715 ns/op`

**Review by MPins — COMMENTED** [review]
Hello @Abdulkbk,  I ran the benchmark as is and got the following numbers.

`go test -tags=test_db_sqlite -bench=BenchmarkIsPublicNode`

*** SELECT WITH UNION ***
```
goos: linux
goarch: amd64
pkg: github.com/lightningnetwork/lnd/graph/db
cpu: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     
BenchmarkIsPublicNode-16    	     122	   9719683 ns/op
--- BENCH: BenchmarkIsPublicNode-16
    test_sqlite.go:49: Creating new SQLite DB for testing
PASS
ok  	github.com/lightningnetwork/lnd/graph/db	119.003s

```

Then changed the go.mod line 216:

from `replace github.com/lightningnetwork/lnd/sqldb => ./sqldb`
to `//replace github.com/lightningnetwork/lnd/sqldb => ./sqldb`

And ran it again :

*** SELECT USING OR ***
```
goos: linux
goarch: amd64
pkg: github.com/lightningnetwork/lnd/graph/db
cpu: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     
BenchmarkIsPublicNode-16    	      93	  11786240 ns/op
--- BENCH: BenchmarkIsPublicNode-16
    test_sqlite.go:49: Creating new SQLite DB for testing
PASS
ok  	github.com/lightningnetwork/lnd/graph/db	120.685s
```

The `BenchmarkIsPublicNode` using `SELECT WITH UNION` took 9.7ms and using `SELECT WITH OR` 11.7ms.

**Comment by Abdulkbk** [comment]
Thanks @MPins, for taking a look. I've addressed the feedback.

**Comment by Abdulkbk** [comment]
Thanks for taking a look @GustavoStingelin. From the output, we can see that indeed the `union_all` performs better, took less time to plan and execute.

**Review by MPins — APPROVED** [review]
LGTM :rocket:

**Comment by ziggie1984** [comment]
yeah I think having a union call makes sense, can land after the cache PR if we still see major bottlenecks, however I think the cache will already solve our problems. The speed gain with a union is probably around ~20-30% given that node ids will be equally queried meaning that in the UnionCall we will likely also have to scan the table 2 times for 50% the node announcements we receive. I think planning plans are cached in PG so the planning time is not really super critical in a query.

**Comment by ziggie1984** [comment]
Given @yyforyongyu comment and another analysis I run on a bigger channel graph, it seems these queries compare O(n) vs O(log n) so might might prioritize this one first before the cache.

```
   graph_sql_test.go:330:
        ======================================================================
    graph_sql_test.go:331: QUERY 1: Original with OR in JOIN
    graph_sql_test.go:332: ======================================================================
    graph_sql_test.go:353: Result  (cost=75.68..75.69 rows=1 width=1) (actual time=0.074..0.074 rows=1 loops=1)
    graph_sql_test.go:353:   Output: $0
    graph_sql_test.go:353:   Buffers: shared hit=41
    graph_sql_test.go:353:   InitPlan 1 (returns $0)
    graph_sql_test.go:353:     ->  Nested Loop  (cost=8.74..75.68 rows=1 width=0) (actual time=0.073..0.074 rows=1 loops=1)
    graph_sql_test.go:353:           Join Filter: ((n.id = c.node_id_1) OR (n.id = c.node_id_2))
    graph_sql_test.go:353:           Rows Removed by Join Filter: 100
    graph_sql_test.go:353:           Buffers: shared hit=41
    graph_sql_test.go:353:           ->  Bitmap Heap Scan on public.graph_channels c  (cost=4.40..51.43 rows=16 width=16) (actual time=0.041..0.054 rows=101 loops=1)
    graph_sql_test.go:353:                 Output: c.id, c.version, c.scid, c.node_id_1, c.node_id_2, c.outpoint, c.capacity, c.bitcoin_key_1, c.bitcoin_key_2, c.node_1_signature, c.node_2_signature, c.bitcoin_1_signature, c.bitcoin_2_signature
    graph_sql_test.go:353:                 Recheck Cond: (c.version = 1)
    graph_sql_test.go:353:                 Filter: (c.bitcoin_1_signature IS NOT NULL)
    graph_sql_test.go:353:                 Heap Blocks: exact=7
    graph_sql_test.go:353:                 Buffers: shared hit=38
    graph_sql_test.go:353:                 ->  Bitmap Index Scan on graph_channels_version_outpoint_idx  (cost=0.00..4.40 rows=16 width=0) (actual time=0.034..0.034 rows=2000 loops=1)
    graph_sql_test.go:353:                       Index Cond: (c.version = 1)
    graph_sql_test.go:353:                       Buffers: shared hit=31
    graph_sql_test.go:353:           ->  Materialize  (cost=4.33..22.31 rows=7 width=8) (actual time=0.000..0.000 rows=1 loops=101)
    graph_sql_test.go:353:                 Output: n.id
    graph_sql_test.go:353:                 Buffers: shared hit=3
    graph_sql_test.go:353:                 ->  Bitmap Heap Scan on public.graph_nodes n  (cost=4.33..22.28 rows=7 width=8) (actual time=0.002..0.002 rows=1 loops=1)
    graph_sql_test.go:353:                       Output: n.id
    graph_sql_test.go:353:                       Recheck Cond: (n.pub_key = '\x034704866e705c6b45fab5b7adc6f8ac431a6ca6b38d9f9038ca83bf1d801a3357'::bytea)
    graph_sql_test.go:353:                       Heap Blocks: exact=1
    graph_sql_test.go:353:                       Buffers: shared hit=3
    graph_sql_test.go:353:                       ->  Bitmap Index Scan on graph_nodes_unique  (cost=0.00..4.33 rows=7 width=0) (actual time=0.001..0.001 rows=1 loops=1)
    graph_sql_test.go:353:                             Index Cond: (n.pub_key = '\x034704866e705c6b45fab5b7adc6f8ac431a6ca6b38d9f9038ca83bf1d801a3357'::bytea)
    graph_sql_test.go:353:                             Buffers: shared hit=2
    graph_sql_test.go:353: Planning Time: 0.099 ms
    graph_sql_test.go:353: Execution Time: 0.092 ms
    graph_sql_test.go:357:
        ======================================================================
    graph_sql_test.go:358: QUERY 2: UNION ALL approach
    graph_sql_test.go:359: ======================================================================
    graph_sql_test.go:380: Result  (cost=87.23..87.24 rows=1 width=1) (actual time=0.049..0.050 rows=1 loops=1)
    graph_sql_test.go:380:   Output: $0
    graph_sql_test.go:380:   Buffers: shared hit=38
    graph_sql_test.go:380:   InitPlan 1 (returns $0)
    graph_sql_test.go:380:     ->  Append  (cost=26.77..147.70 rows=2 width=4) (actual time=0.049..0.050 rows=1 loops=1)
    graph_sql_test.go:380:           Buffers: shared hit=38
    graph_sql_test.go:380:           ->  Hash Join  (cost=26.77..73.84 rows=1 width=4) (actual time=0.049..0.049 rows=1 loops=1)
    graph_sql_test.go:380:                 Output: 1
    graph_sql_test.go:380:                 Inner Unique: true
    graph_sql_test.go:380:                 Hash Cond: (c.node_id_1 = n.id)
    graph_sql_test.go:380:                 Buffers: shared hit=38
    graph_sql_test.go:380:                 ->  Bitmap Heap Scan on public.graph_channels c  (cost=4.40..51.43 rows=16 width=8) (actual time=0.033..0.040 rows=101 loops=1)
    graph_sql_test.go:380:                       Output: c.id, c.version, c.scid, c.node_id_1, c.node_id_2, c.outpoint, c.capacity, c.bitcoin_key_1, c.bitcoin_key_2, c.node_1_signature, c.node_2_signature, c.bitcoin_1_signature, c.bitcoin_2_signature
    graph_sql_test.go:380:                       Recheck Cond: (c.version = 1)
    graph_sql_test.go:380:                       Filter: (c.bitcoin_1_signature IS NOT NULL)
    graph_sql_test.go:380:                       Heap Blocks: exact=7
    graph_sql_test.go:380:                       Buffers: shared hit=35
    graph_sql_test.go:380:                       ->  Bitmap Index Scan on graph_channels_version_outpoint_idx  (cost=0.00..4.40 rows=16 width=0) (actual time=0.028..0.028 rows=2000 loops=1)
    graph_sql_test.go:380:                             Index Cond: (c.version = 1)
    graph_sql_test.go:380:                             Buffers: shared hit=28
    graph_sql_test.go:380:                 ->  Hash  (cost=22.28..22.28 rows=7 width=8) (actual time=0.003..0.003 rows=1 loops=1)
    graph_sql_test.go:380:                       Output: n.id
    graph_sql_test.go:380:                       Buckets: 1024  Batches: 1  Memory Usage: 9kB
    graph_sql_test.go:380:                       Buffers: shared hit=3
    graph_sql_test.go:380:                       ->  Bitmap Heap Scan on public.graph_nodes n  (cost=4.33..22.28 rows=7 width=8) (actual time=0.002..0.002 rows=1 loops=1)
    graph_sql_test.go:380:                             Output: n.id
    graph_sql_test.go:380:                             Recheck Cond: (n.pub_key = '\x034704866e705c6b45fab5b7adc6f8ac431a6ca6b38d9f9038ca83bf1d801a3357'::bytea)
    graph_sql_test.go:380:                             Heap Blocks: exact=1
    graph_sql_test.go:380:                             Buffers: shared hit=3
    graph_sql_test.go:380:                             ->  Bitmap Index Scan on graph_nodes_unique  (cost=0.00..4.33 rows=7 width=0) (actual time=0.001..0.001 rows=1 loops=1)
    graph_sql_test.go:380:                                   Index Cond: (n.pub_key = '\x034704866e705c6b45fab5b7adc6f8ac431a6ca6b38d9f9038ca83bf1d801a3357'::bytea)
    graph_sql_test.go:380:                                   Buffers: shared hit=2
    graph_sql_test.go:380:           ->  Hash Join  (cost=26.77..73.84 rows=1 width=4) (never executed)
    graph_sql_test.go:380:                 Output: 1
    graph_sql_test.go:380:                 Inner Unique: true
    graph_sql_test.go:380:                 Hash Cond: (c_1.node_id_2 = n_1.id)
    graph_sql_test.go:380:                 ->  Bitmap Heap Scan on public.graph_channels c_1  (cost=4.40..51.43 rows=16 width=8) (never executed)
    graph_sql_test.go:380:                       Output: c_1.id, c_1.version, c_1.scid, c_1.node_id_1, c_1.node_id_2, c_1.outpoint, c_1.capacity, c_1.bitcoin_key_1, c_1.bitcoin_key_2, c_1.node_1_signature, c_1.node_2_signature, c_1.bitcoin_1_signature, c_1.bitcoin_2_signature
    graph_sql_test.go:380:                       Recheck Cond: (c_1.version = 1)
    graph_sql_test.go:380:                       Filter: (c_1.bitcoin_1_signature IS NOT NULL)
    graph_sql_test.go:380:                       ->  Bitmap Index Scan on graph_channels_version_outpoint_idx  (cost=0.00..4.40 rows=16 width=0) (never executed)
    graph_sql_test.go:380:                             Index Cond: (c_1.version = 1)
    graph_sql_test.go:380:                 ->  Hash  (cost=22.28..22.28 rows=7 width=8) (never executed)
    graph_sql_test.go:380:                       Output: n_1.id
    graph_sql_test.go:380:                       ->  Bitmap Heap Scan on public.graph_nodes n_1  (cost=4.33..22.28 rows=7 width=8) (never executed)
    graph_sql_test.go:380:                             Output: n_1.id
    graph_sql_test.go:380:                             Recheck Cond: (n_1.pub_key = '\x034704866e705c6b45fab5b7adc6f8ac431a6ca6b38d9f9038ca83bf1d801a3357'::bytea)
    graph_sql_test.go:380:                             ->  Bitmap Index Scan on graph_nodes_unique  (cost=0.00..4.33 rows=7 width=0) (never executed)
    graph_sql_test.go:380:                                   Index Cond: (n_1.pub_key = '\x034704866e705c6b45fab5b7adc6f8ac431a6ca6b38d9f9038ca83bf1d801a3357'::bytea)
    graph_sql_test.go:380: Planning Time: 0.098 ms
    graph_sql_test.go:380: Execution Time: 0.071 ms
```


here the OR query could not effectively use a bitmap and had to scan through the whole channel table.

File: graph/db/graph_test.go (hunk 1 above)
Comment (ziggie1984) [reply graph/db/graph_test.go]: this underlines the O(n) vs O(log(n)) relationship

**Comment by ziggie1984** [comment]
can you fix the linter and add 20.1 release notes here @Abdulkbk

File: graph/db/graph_test.go [hunk 4]
```diff
@@ -4042,6 +4044,29 @@ func TestNodeIsPublic(t *testing.T) {
 	)
 }
 
+// BenchmarkIsPublicNode measures the performance of IsPublicNode when checking
+// a large number of nodes.
+func BenchmarkIsPublicNode(b *testing.B) {
```
Comment (ziggie1984) [inline graph/db/graph_test.go:4049]: I think the benchmark an be improved we always query the same node which let's sql probably allow caching results diluting the actual benchmark tests:

```
 func BenchmarkIsPublicNode(b *testing.B) {
        graph := MakeTestGraph(b)

@@ -4054,14 +4059,14 @@ func BenchmarkIsPublicNode(b *testing.B) {
        numChans := 4
        _, nodes := fillTestGraph(b, graph, numNodes, numChans)

-       // Pick any node to test with.
-       nodePub := nodes[len(nodes)/2].PubKeyBytes
-
-       // Reset the timer to exclude setup time especially since
-       // `fillTestGraph` can take a while.
-       b.ResetTimer()
+       // Use deterministic random number generator for reproducible results.
+       rng := prand.New(prand.NewSource(42))

+       // b.Loop() automatically resets the timer, excluding setup time.
        for b.Loop() {
+               // Query random nodes to avoid query caching and better
+               // represent real-world query patterns.
+               nodePub := nodes[rng.Intn(len(nodes))].PubKeyBytes
                _, err := graph.IsPublicNode(nodePub)
                require.NoError(b, err)
        }
```


moreover timer clearance before the loop is not need since 1.24:

https://go.dev/blog/testing-b-loop

Comment (ziggie1984) [reply graph/db/graph_test.go:4049]: also less decrease the value of the nodes to something like 100, we don't want to clog the test times, because this benchmark without the comparision to the other call is not really worth much so user will have to tinker with the numbers anyway if they wanna find out the performance results.

**Comment by ziggie1984** [comment]
@Abdulkbk could you analyze why the itest on windows failed ? It is not related to the PR but we should make sure we at least document flakes.

**Comment by litbot-9000** [comment]
@abdulkbk, remember to re-request review from reviewers when ready
