### PR TITLE
tor: socks and control can not use the same host:port

### LINKED ISSUE #4154: lnd hangs without logs when tor socks port is set to tor control port
### Background

This tripped me up longer than I want to admit. I accidentally set my `tor.socks` port to the same port as `tor.control`. When this happens, `lnd` simply hangs with no log messages at all, even with `--debuglevel=trace`. When trying to kill the process with `Control+C` you get a shutdown message but the process doesn't actually exit. You must do `kill -9` to get exit the process.

### Your environment

- lnd version 0.9.1-beta commit=v0.9.1-beta
- Ubuntu Xenial Docker Image (Linux a6deda9059c1 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
- btcd backend (btcd version 0.20.1-beta)

### Steps to reproduce

Create a `lnd.conf` file with the follow Tor config:

```
[tor]
tor.active=true
tor.socks=9051
tor.control=9051
```

Try to run lnd with `lnd --configfile=/path/to/conf`.

Alternatively, you can exclusively use cli flags:

`lnd --tor.active --tor.socks=9051 --tor.control=9051 ...`

### Expected behaviour

I think it would be good at the very least to log something and handle a SIGTERM. Any indication or pointer to the problem would be very helpful instead of nothing. Not sure if there's a network level check you can do for this error. Perhaps just seeing if `tor.socks` and `tor.control` are the same port is sufficient to error out. However, this still happens if you only specify `tor.socks` and not set `tor.control` at all.

### Actual behaviour

lnd hangs with no output and doesn't respect SIGTERM.

### PR DESCRIPTION
**Pull request by ErikEk**
This PR resolves the issue where the instance hangs if tor.socks and tor.control use the same host:port. This addition simply returns an error message if they are equal.

Fixes #4154

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -663,6 +663,12 @@ func loadConfig() (*config, error) {
 	}
 	cfg.Tor.Control = control.String()
 
+	if cfg.Tor.SOCKS == cfg.Tor.Control {
```
Comment (guggero) [inline config.go:666]: Would be nice to add a commend _why_ we need to check this. Mention that wrong configuration can lead to `lnd` not starting up properly.

Comment (ErikEk) [reply config.go:668]: Done. Thanks for the review.
