### PR TITLE
fundingmanager: send messages directly to peers

### LINKED ISSUE #1495: lncli openchannel does not return w/ chan reserve too low error
### Background
Lncli hangs without an error message when I try to open a channel and the channel reserve is too low. 

### Your environment

* version of `lnd`: 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
* which operating system: Linux 4.14.18-sunxi #24 SMP Fri Feb 9 16:24:32 CET 2018 armv7l GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: Bitcoin Core Daemon version v0.16.1

### Steps to reproduce
lncli openchannel --node_key 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf --connect 13.92.254.226:9735 --local_amt 51000

in the log I found the following:
`
2018-07-02 14:08:27.451 [INF] FNDG: Target commit tx sat/kw for pendingID(0fa9f74e1e6e7585905b2829a5d9eedc0f60f5bcf8e6d32fa9a4a67890096e54): 500
2018-07-02 14:08:27.456 [INF] FNDG: Starting funding workflow with 13.92.254.226:9735 for pendingID(0fa9f74e1e6e7585905b2829a5d9eedc0f60f5bcf8e6d32fa9a4a67890096e54)
2018-07-02 14:08:27.466 [INF] SRVR: Attempting to send msgs 1 to: 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf
2018-07-02 14:08:29.741 [INF] FNDG: Recv'd fundingResponse for pendingID(0fa9f74e1e6e7585905b2829a5d9eedc0f60f5bcf8e6d32fa9a4a67890096e54)
2018-07-02 14:08:29.743 [WRN] FNDG: Unacceptable channel constraints: channel reserve of 510 sat is too small, min is 573 sat
2018-07-02 14:08:29.745 [ERR] FNDG: Failing funding flow: channel reserve of 510 sat is too small, min is 573 sat ((*lnwire.Error)(0x131ba6c0)({
 ChanID: (lnwire.ChannelID) (len=32 cap=32) 0fa9f74e1e6e7585905b2829a5d9eedc0f60f5bcf8e6d32fa9a4a67890096e54,
 Data: (lnwire.ErrorData) (len=55 cap=64) {
  00000000  63 68 61 6e 6e 65 6c 20  72 65 73 65 72 76 65 20  |channel reserve |
  00000010  6f 66 20 35 31 30 20 73  61 74 20 69 73 20 74 6f  |of 510 sat is to|
  00000020  6f 20 73 6d 61 6c 6c 2c  20 6d 69 6e 20 69 73 20  |o small, min is |
  00000030  35 37 33 20 73 61 74                              |573 sat|
 }
})
)
2018-07-02 14:08:29.753 [INF] FNDG: Cancelling funding reservation for node_key=03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf, chan_id=0fa9f74e1e6e7585905b2829a5d9eedc0f60f5bcf8e6d32fa9a4a67890096e54
2018-07-02 14:08:29.773 [INF] SRVR: Attempting to send msgs 1 to: 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf
`

### Expected behaviour
I would expect to get en error message instead of a non-returning cli (and for usability reasons it would be nice to get some information/hints what to do, because it is not obvious for beginners)

### Actual behaviour
lncli does not return

### PR DESCRIPTION
**Pull request by wpaulino**
In this PR, we introduce a similar optimization to the one done in #1345. Currently, each call to `server.SendToPeer` acquires the server's mutex to obtain the active peer. We work around this by passing the `peer` struct itself within the internal `fundingManager` messages.

Fixes #1495.

### CODE REVIEW

File: discovery/gossiper.go [hunk 1]
```diff
@@ -2399,11 +2399,11 @@ func (d *AuthenticatedGossiper) sendAnnSigReliably(
 				"to peer(%x): %v. Will retry when online.",
 				remotePeer.SerializeCompressed(), err)
 
-			connected := make(chan struct{})
-			d.cfg.NotifyWhenOnline(remotePeer, connected)
+			peerChan := make(chan lnpeer.Peer)
```
Comment (cfromknecht) [inline discovery/gossiper.go]: buffer this as well?

File: fundingmanager_test.go [hunk 2]
```diff
@@ -323,22 +355,32 @@ func createTestFundingManager(t *testing.T, privKey *btcec.PrivateKey,
...
 		testDir:         tempTestDir,
 		shutdownChannel: shutdownChan,
-	}, nil
+		addr:            addr,
+	}
+
+	f.cfg.NotifyWhenOnline = func(peer *btcec.PublicKey,
+		connectedChan chan<- lnpeer.Peer) {
+
+		go func() {
```
Comment (cfromknecht) [inline fundingmanager_test.go]: will these tests pass w/o the goroutine now that we're buffering?

File: peer.go [hunk 3]
```diff
@@ -1999,6 +2006,43 @@ func (p *peer) IdentityKey() *btcec.PublicKey {
...
 }
 
+// Address returns the network address of the remote peer.
+func (p *peer) Address() net.Addr {
+	return p.addr.Address
+}
+
+// AddNewChannel adds a new channel to the peer. The channel should fail to be
+// added if the fundingQuit channel is closed.
+func (p *peer) AddNewChannel(channel *lnwallet.LightningChannel,
```
Comment (cfromknecht) [inline peer.go]: 👍

File: discovery/gossiper.go [hunk 4]
```diff
@@ -107,7 +107,7 @@ type Config struct {
 	// NotifyWhenOnline is a function that allows the gossiper to be
 	// notified when a certain peer comes online, allowing it to
 	// retry sending a peer message.
-	NotifyWhenOnline func(peer *btcec.PublicKey, connectedChan chan<- struct{})
+	NotifyWhenOnline func(peer *btcec.PublicKey, peerChan chan<- lnpeer.Peer)
```
Comment (cfromknecht) [inline discovery/gossiper.go]: Perhaps make a note in the godoc that `peerChan` MUST be buffered

File: discovery/gossiper.go (hunk 1 above)
Comment (wpaulino) [reply discovery/gossiper.go]: Fixed.

File: fundingmanager_test.go (hunk 2 above)
Comment (wpaulino) [reply fundingmanager_test.go]: Yep! Fixed.

File: discovery/gossiper.go (hunk 4 above)
Comment (wpaulino) [reply discovery/gossiper.go]: Fixed.

File: peer.go [hunk 5]
```diff
@@ -951,8 +951,12 @@ out:
 			// If the channel ID for the error message corresponds
 			// to a pending channel, then the funding manager will
 			// handle the error.
-			case p.server.fundingMgr.IsPendingChannel(msg.ChanID, p.addr):
-				p.server.fundingMgr.processFundingError(msg, p.addr)
+			case p.server.fundingMgr.IsPendingChannel(
+				msg.ChanID, p.addr.IdentityKey,
+			):
```
Comment (halseth) [inline peer.go]: hm, weird format? Maybe just do `key := addr.IdentityKey` to keep on one line.

File: fundingmanager.go [hunk 6]
```diff
@@ -93,6 +93,16 @@ var (
 		"down")
 )
 
+// FundingPeer represents a Lightning Network peer capable of handling funding
+// requests/messages.
+type FundingPeer interface {
+	lnpeer.Peer
+
+	// AddNewChannel adds a new channel to the peer. The channel should fail
+	// to be added if the fundingQuit channel is closed.
```
Comment (halseth) [inline fundingmanager.go]: I think `cancel` would be a better name for the chan.

File: peer.go [hunk 7]
```diff
@@ -223,6 +223,9 @@ func newPeer(conn net.Conn, connReq *connmgr.ConnReq, server *server,
 	return p, nil
 }
 
+// A compile-time check to ensure that peer satisfies the FundingPeer interface.
+var _ FundingPeer = (*peer)(nil)
```
Comment (halseth) [inline peer.go]: Hm, this has the unfortunate effect of keeping the dependency cycle `peer<->fundingmanager`. Why not make `AddNewChannel` part of the regular `Peer` interface?

File: fundingmanager.go [hunk 8]
```diff
@@ -630,7 +633,9 @@ func (f *fundingManager) Start() error {
 			go func(dbChan *channeldb.OpenChannel) {
 				defer f.wg.Done()
 
-				err := f.handleFundingConfirmation(dbChan, shortChanID)
+				err := f.handleFundingConfirmation(
+					nil, dbChan, shortChanID,
```
Comment (halseth) [inline fundingmanager.go]: not sure if passing `nil` here is the best option, can make it easy to make errors down the line. Instead, can you fetch the peer (`NotifyWhenOnline `) right before it is used, or make sure that it will never be passed in as `nil`?

File: fundingmanager.go [hunk 9]
```diff
@@ -337,7 +337,7 @@ type fundingConfig struct {
 	// the channel to the ChainArbitrator so it can watch for any on-chain
 	// events related to the channel. We also provide the address of the
 	// node we're establishing a channel with for reconnection purposes.
-	WatchNewChannel func(*channeldb.OpenChannel, *lnwire.NetAddress) error
+	WatchNewChannel func(*channeldb.OpenChannel, *btcec.PublicKey) error
```
Comment (halseth) [inline fundingmanager.go]: nit: update comment

File: discovery/gossiper.go [hunk 10]
```diff
@@ -9,7 +9,7 @@ import (
 	"sync/atomic"
 	"time"
 
-	"github.com/coreos/bbolt"
+	bolt "github.com/coreos/bbolt"
```
Comment (halseth) [inline discovery/gossiper.go]: why this change?

File: fundingmanager.go [hunk 11]
```diff
@@ -1933,37 +1928,32 @@ func (f *fundingManager) sendFundingLocked(peer lnpeer.Peer,
...
-		if peer == nil {
-			peer, err = f.cfg.FindPeer(completeChan.IdentityPub)
+		if peer != nil {
+			err = peer.SendMessage(false, fundingLockedMsg)
 			if err != nil {
-				continue
+				fndgLog.Warnf("Unable to send fundingLocked "+
+					"to peer %x: %v",
+					peerKey.SerializeCompressed(), err)
+			} else {
```
Comment (halseth) [inline fundingmanager.go]: Can `peer` be `nil` here? If not, this can be written
```go
err = sendMessage(..)
if err == nil {
    break
}
print(err)
... go on ...
```

EDIT: see other comment about `nil` peer

File: peer.go (hunk 5 above)
Comment (wpaulino) [reply peer.go]: Fixed.

File: fundingmanager.go (hunk 6 above)
Comment (wpaulino) [reply fundingmanager.go]: Fixed.

File: peer.go (hunk 7 above)
Comment (wpaulino) [reply peer.go]: Fixed.

File: fundingmanager.go (hunk 8 above)
Comment (wpaulino) [reply fundingmanager.go]: Changed it so that we fetch the peer before `handleFundingConfirmation`.

File: fundingmanager.go (hunk 9 above)
Comment (wpaulino) [reply fundingmanager.go]: Fixed.

File: discovery/gossiper.go (hunk 10 above)
Comment (wpaulino) [reply discovery/gossiper.go]: Had to add it because it wouldn't compile otherwise. Although it no longer seems to be a problem...

File: peer.go [hunk 12]
```diff
@@ -1999,6 +2003,43 @@ func (p *peer) IdentityKey() *btcec.PublicKey {
...
+		return errors.New("canceled adding new channel")
+	case <-p.quit:
+		return ErrPeerExiting
+	}
+
+	// We pause here to wait for the peer to recognize the new channel
+	// before we close the channel barrier corresponding to the channel.
+	select {
+	case <-newChanDone:
+	case <-cancel:
```
Comment (halseth) [inline peer.go]: Not sure if cancelling at this point will actually stop the channel from being added to the peer?

File: peer.go [hunk 13]
```diff
@@ -949,11 +950,11 @@ out:
 					p.failedChannels[chanID] = struct{}{}
 				}
 
-			// If the channel ID for the error message corresponds
-			// to a pending channel, then the funding manager will
-			// handle the error.
-			case p.server.fundingMgr.IsPendingChannel(msg.ChanID, p.addr):
-				p.server.fundingMgr.processFundingError(msg, p.addr)
+				// If the channel ID for the error message corresponds
```
Comment (halseth) [inline peer.go]: formatting

File: fundingmanager.go [hunk 14]
```diff
@@ -553,16 +554,29 @@ func (f *fundingManager) Start() error {
...
-					fndgLog.Errorf("failed to handle funding"+
-						"confirmation: %v", err)
+				// The funding transaction has confirmed, so
+				// we'll attempt to retrieve the remote peer
+				// to complete the rest of the funding flow.
+				peerChan := make(chan lnpeer.Peer, 1)
+				f.cfg.NotifyWhenOnline(ch.IdentityPub, peerChan)
+
+				select {
+				case peer := <-peerChan:
```
Comment (halseth) [inline fundingmanager.go]: Can do
```go
var peer lnpeer.Peer
select {
case peer = <-peerChan:
case <-f.quit:
    return
}
err := f.handleFundingConfirmation ....
```

File: fundingmanager.go [hunk 15]
```diff
@@ -620,10 +634,21 @@ func (f *fundingManager) Start() error {
...
 
-				err := f.handleFundingConfirmation(dbChan, shortChanID)
-				if err != nil {
-					fndgLog.Errorf("failed to handle funding"+
-						"confirmation: %v", err)
+				peerChan := make(chan lnpeer.Peer, 1)
+				f.cfg.NotifyWhenOnline(dbChan.IdentityPub, peerChan)
+
+				select {
+				case peer := <-peerChan:
```
Comment (halseth) [inline fundingmanager.go]: same as above

File: fundingmanager.go [hunk 16]
```diff
@@ -2276,33 +2264,7 @@ func (f *fundingManager) handleFundingLocked(fmsg *fundingLockedMsg) {
...
-	}
-
-	// We pause here to wait for the peer to recognize the new channel
-	// before we close the channel barrier corresponding to the channel.
-	select {
-	case <-f.quit:
-		return
-	case <-newChanDone: // Fallthrough if we're not quitting.
-	}
+	fmsg.peer.AddNewChannel(channel, f.quit)
```
Comment (halseth) [inline fundingmanager.go]: Does it make sense to let this return an error that we can log here?

File: fundingmanager_test.go [hunk 17]
```diff
@@ -434,11 +468,37 @@ func setupFundingManagers(t *testing.T) (*testNode, *testNode) {
...
 		t.Fatalf("failed creating fundingManager: %v", err)
 	}
 
+	// With the funding manager's created, we'll now attempt to mimic a
+	// connection pipe between them. In order to intercept the messages
+	// within it, we'll redirect all messages back to the msgChan of the
+	// sender. Since the fundingManager now has a reference to peers itself,
+	// alice.sendMessage will be triggered when Bob's funding manager
+	// attempts to send a message to Alice and vice versa.
+	alice.remotePeer = bob
```
Comment (halseth) [inline fundingmanager_test.go]: 👍

File: peer.go (hunk 12 above)
Comment (wpaulino) [reply peer.go]: Yeah, not much we can do after the request has already been sent. Just ended up removing this instead as this wasn't being handled previously anyway.

File: peer.go (hunk 13 above)
Comment (wpaulino) [reply peer.go]: Fixed.

File: fundingmanager.go (hunk 14 above)
Comment (wpaulino) [reply fundingmanager.go]: Fixed.

File: fundingmanager.go (hunk 15 above)
Comment (wpaulino) [reply fundingmanager.go]: Fixed.

File: fundingmanager.go (hunk 16 above)
Comment (wpaulino) [reply fundingmanager.go]: Fixed.

**Comment by cfromknecht** [comment]
needs rebase

**Comment by wpaulino** [comment]
Rebased.
