### PR TITLE
channeldb: change balance fields to tlv records and migrate historical bucket

### LINKED ISSUE #6549: regression with 0.15.0-rc1 : unable to fetch chan info: invalid public key: unsupported format: 72
### Background

Upgraded lnd from 0.14.3 to 0.15.0-beta.rc1

### Your environment

* version of `lnd`

0.15.0-beta.rc1

* which operating system (`uname -a` on *Nix)

Linux xxx 5.17.6-200.fc35.x86_64 #1 SMP PREEMPT Mon May 9 14:22:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend

bitcoind 22.0

### Steps to reproduce

start lnd

I have a channel that was force closed a couple of years ago and some funds still pending.

### Actual behaviour

lnd starts but during startup it quit with the following errors:

```
2022-05-17 22:26:13.267 [INF] CNCT: ChannelArbitrator(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:0): starting state=StateWaitingFullResolution, trigger=chainTrigger, triggerHeight=xxxxxx
2022-05-17 22:26:13.267 [INF] CNCT: ChannelArbitrator(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:0): still awaiting contract resolution
2022-05-17 22:26:13.268 [INF] CNCT: ChainArbitrator shutting down
2022-05-17 22:26:13.269 [INF] HSWC: HTLC Switch shutting down
2022-05-17 22:26:13.269 [INF] NTFN: Cancelling epoch notification, epoch_id=3
2022-05-17 22:26:13.269 [INF] FNDG: Funding manager shutting down
2022-05-17 22:26:13.269 [INF] BRAR: Breach arbiter shutting down
2022-05-17 22:26:13.269 [INF] UTXN: UTXO nursery shutting down
2022-05-17 22:26:13.269 [INF] NTFN: Cancelling epoch notification, epoch_id=2
2022-05-17 22:26:13.269 [INF] SWPR: Sweeper shutting down
2022-05-17 22:26:13.270 [INF] NTFN: Cancelling epoch notification, epoch_id=1
2022-05-17 22:26:13.270 [INF] HSWC: HtlcNotifier shutting down
2022-05-17 22:26:13.270 [INF] PRNF: PeerNotifier shutting down
2022-05-17 22:26:13.270 [INF] CHNF: ChannelNotifier shutting down
2022-05-17 22:26:13.270 [INF] NTFN: bitcoind notifier shutting down
2022-05-17 22:26:13.270 [INF] HLCK: Health monitor shutting down
2022-05-17 22:26:13.270 [ERR] LTND: Shutting down because error in main method: unable to start server: unable to fetch chan info: invalid public key: unsupported format: 72
2022-05-17 22:26:13.270 [INF] RPCS: Stopping RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping PeersRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping NeutrinoKitRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping VersionRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping WatchtowerRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
2022-05-17 22:26:13.271 [INF] RPCS: Stopping AutopilotRPC Sub-RPC Server
2022-05-17 22:26:13.272 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
2022-05-17 22:26:13.272 [INF] TORC: Stopping tor controller
2022-05-17 22:26:13.272 [ERR] TORC: DEL_ONION got error: invalid arguments: unexpected code
2022-05-17 22:26:13.272 [ERR] LTND: error stopping tor controller: invalid arguments: unexpected code
2022-05-17 22:26:13.361 [INF] LTND: Shutdown complete

unable to start server: unable to fetch chan info: invalid public key: unsupported format: 72
```

### PR DESCRIPTION
**Pull request by yyforyongyu**
This PR makes two changes,
1. use tlv to store the two balance fields.
2. patch empty balance values to historical channels. Since the revocation logs are removed when the channel is closed, it's not possible to find the balance info again. To avoid serialization/deserialization errors, we patch them with empty values. For historical channels after the revocation log PR, those fields should have the values again.

Fixes #6549 #6548

### CODE REVIEW

File: channeldb/migration27/migration.go [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+	// historically stored channels.
+	rootBucket := tx.ReadWriteBucket(historicalChannelBucket)
+
+	// If no bucket is found, we can exit early.
+	if rootBucket == nil {
+		return nil
+	}
+
+	// Read a list of historical channels.
+	channels, err := findHistoricalChannels(rootBucket)
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply channeldb/migration27/migration.go:38]: IIRC the bucket has been around for 1.5 years or so, but _does_ include every channel ever opened by the node. So it can be large, but likely doesn't have _millions_ of entries.

[the remark this answers is not in the document]
Comment (yyforyongyu) [reply channeldb/migration27/migration.go:38]: Ok cool. Each `ChannelInfo` is below 1KB (roughly 913 bytes if funding tx is 250 bytes), a 1 GB ram should fit 1 million records. As long as we don't have millions of channels here we'd be fine.

File: channeldb/migration27/migration.go [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+// with empty values.
+func migrateBalances(rootBucket kvdb.RwBucket, c *OpenChannel) error {
+	var chanPointBuf bytes.Buffer
+	err := mig.WriteOutpoint(&chanPointBuf, &c.FundingOutpoint)
+	if err != nil {
+		return err
+	}
+
+	// Get the channel bucket.
+	chanBucket, err := rootBucket.CreateBucketIfNotExists(
```
Comment (Roasbeef) [inline channeldb/migration27/migration.go:104]: Why `CreateBucketIfNotExists` vs just grabbing the bucket and exiting if it doesn't exist? AFAICT at this point we already know that this channel point is _definitely_ in the bucket as well?

File: channeldb/migration25/channel.go [hunk 3]
```diff
@@ -720,3 +720,39 @@ func fetchChannelLogEntry(log kvdb.RBucket,
 	commitReader := bytes.NewReader(commitBytes)
 	return mig.DeserializeChanCommit(commitReader)
 }
+
```
Comment (Roasbeef) [inline channeldb/migration25/channel.go:723]: Typo in commit message: severl -> several

File: channeldb/migration27/migration_test.go [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+	dummyPrivKey, _ = btcec.NewPrivateKey()
+	dummyPubKey     = dummyPrivKey.PubKey()
+	dummyOp         = wire.OutPoint{
+		Hash:  chainhash.Hash{},
+		Index: 9,
+	}
+
+	// testChannel is used to test the balance fields are correctly set.
+	testChannel = &OpenChannel{
+		OpenChannel: mig26.OpenChannel{
```
Comment (Roasbeef) [inline channeldb/migration27/migration_test.go:30]: Yo dawg, I herd you like `OpenChannels` 😆

**Review by Roasbeef — COMMENTED** [review]
Confirmed that this fixes the issue! Upgraded two nodes that were unable to do `lncli closedchannels`, saved the output before upgrading, then did a diff after the upgrade and found them to be identical.

File: channeldb/migration25/channel.go (hunk 3 above)
Comment (yyforyongyu) [reply channeldb/migration25/channel.go:723]: fixed!

File: channeldb/migration27/migration.go (hunk 2 above)
Comment (yyforyongyu) [reply channeldb/migration27/migration.go:104]: Yeah exactly, fixed!

File: channeldb/migration27/migration_test.go (hunk 4 above)
Comment (yyforyongyu) [reply channeldb/migration27/migration_test.go:30]: lol, image doing this for migration 100...

**Review by Roasbeef — APPROVED** [review]
LGTM 🦆

Looking forward to the day where we never need to do migrations of this nature again!

**Comment by C-Otto** [comment]
On my testnet node:
```
2022-05-19 12:30:47.404 [INF] CHDB: Performing database schema migration
2022-05-19 12:30:47.404 [INF] CHDB: Applying migration #26
2022-05-19 12:30:47.405 [INF] CHDB: Applying migration #27
2022-05-19 12:30:47.405 [INF] CHDB: Unable to apply migration #27
2022-05-19 12:30:47.405 [ERR] LTND: unable to open graph DB: unable to fetch chan info: unexpected EOF
2022-05-19 12:30:47.405 [ERR] LTND: Shutting down because error in main method: unable to open databases: unable to open graph DB: unable to fetch chan info: unexpected EOF
```

**Comment by yyforyongyu** [comment]
> On one of my testnet nodes (the other didn't have this issue):
> 
> ```
> 2022-05-19 12:30:47.404 [INF] CHDB: Performing database schema migration
> 2022-05-19 12:30:47.404 [INF] CHDB: Applying migration #26
> 2022-05-19 12:30:47.405 [INF] CHDB: Applying migration #27
> 2022-05-19 12:30:47.405 [INF] CHDB: Unable to apply migration #27
> 2022-05-19 12:30:47.405 [ERR] LTND: unable to open graph DB: unable to fetch chan info: unexpected EOF
> 2022-05-19 12:30:47.405 [ERR] LTND: Shutting down because error in main method: unable to open databases: unable to open graph DB: unable to fetch chan info: unexpected EOF
> ```

Thanks for reporting! Could you patch this PR and start it again? I've added more verbose error messages to hopefully debug what's going on there.

**Comment by C-Otto** [comment]
`2022-05-19 13:11:28.397 [ERR] LTND: unable to open graph DB: unable to fetch chan info: read FundingTxn got: unexpected EOF`

**Comment by C-Otto** [comment]
I added a bunch of debug statements in there and this one is triggered:
```
case **wire.MsgTx:
		tx := wire.NewMsgTx(2)
		if err := tx.Deserialize(r); err != nil {
			return fmt.Errorf("q %v", err)
		}

		*e = tx
```

**Comment by yyforyongyu** [comment]
> `2022-05-19 13:11:28.397 [ERR] LTND: unable to open graph DB: unable to fetch chan info: read FundingTxn got: unexpected EOF`

The funding tx looks weird. I added more verbose error messages to fetch the channel point, could you run it again?

**Comment by C-Otto** [comment]
```
2022-05-19 13:28:58.062 [INF] CHDB: Performing database schema migration
2022-05-19 13:28:58.062 [INF] CHDB: Applying migration #26
2022-05-19 13:28:58.063 [INF] CHDB: Applying migration #27
2022-05-19 13:28:58.075 [INF] LTND: Database(s) now open (time_to_open=5.028657158s)!
```

**Comment by C-Otto** [comment]
I published my old state, maybe that helps figuring out what went wrong?
https://c-otto.de/lnd.tar.bz2

File: channeldb/migration27/migration.go [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+
+		chanPointBuf := bytes.NewBuffer(cp)
+		err := mig.ReadOutpoint(chanPointBuf, &c.FundingOutpoint)
+		if err != nil {
+			return fmt.Errorf("read funding outpoint got: %v", err)
+		}
+
+		// Read the sub-bucket.
+		chanBucket := rootBucket.NestedReadBucket(cp)
+		if chanBucket != nil {
```
Comment (C-Otto) [inline channeldb/migration27/migration.go:72]: `!=`?

Comment (C-Otto) [reply channeldb/migration27/migration.go:72]: Ah, `chanBucket` contains the error, usually called `err`?

Comment (yyforyongyu) [reply channeldb/migration27/migration.go]: nope that was a mistake, I was testing the error logs and forgot to put it back. `chanBucket` is the bucket returned.

**Comment by C-Otto** [comment]
`2022-05-19 13:36:46.668 [ERR] LTND: unable to open graph DB: 32fc40c53d1116bc91782626f243058a51efafc209ac9d75825dfac42413db28:0: fetch chan info got: read FundingTxn got: unexpected EOF`

**Comment by yyforyongyu** [comment]
> `2022-05-19 13:36:46.668 [ERR] LTND: unable to open graph DB: 32fc40c53d1116bc91782626f243058a51efafc209ac9d75825dfac42413db28:0: fetch chan info got: read FundingTxn got: unexpected EOF`

Messaged you on slack.

**Comment by yyforyongyu** [comment]
> On one of my testnet nodes (the other didn't have this issue):
> 
> ```
> 2022-05-19 12:30:47.404 [INF] CHDB: Performing database schema migration
> 2022-05-19 12:30:47.404 [INF] CHDB: Applying migration #26
> 2022-05-19 12:30:47.405 [INF] CHDB: Applying migration #27
> 2022-05-19 12:30:47.405 [INF] CHDB: Unable to apply migration #27
> 2022-05-19 12:30:47.405 [ERR] LTND: unable to open graph DB: unable to fetch chan info: unexpected EOF
> 2022-05-19 12:30:47.405 [ERR] LTND: Shutting down because error in main method: unable to open databases: unable to open graph DB: unable to fetch chan info: unexpected EOF
> ```

Ok I think I found the issue. It turns out the historical channel was created after `migration25` was applied. So the info would have the fields `InitialLocalBalance` and `InitialRemoteBalance` presented. The latest update should fix this case too.

File: channeldb/migration26/channel.go [hunk 6]
```diff
@@ -0,0 +1,299 @@
...
+// OpenChannel embeds a mig25.OpenChannel with the extra update-to-date
+// serialization and deserialization methods.
+//
+// NOTE: doesn't have the Packager field as it's not used in current migration.
+type OpenChannel struct {
+	mig25.OpenChannel
+
+	// chanStatus is the current status of this channel. If it is not in
+	// the state Default, it should not be used for forwarding payments.
+	chanStatus mig25.ChannelStatus
```
Comment (Crypt-iQ) [inline channeldb/migration26/channel.go:76]: Doesn't mig25.OpenChannel already embed this?

Comment (Crypt-iQ) [reply channeldb/migration26/channel.go:76]: Oh I see, unexported.

**Comment by Roasbeef** [comment]
Nice addition with that last update: confirmed locally it hits that fall back path which exercises the migration for those that have closed channels after migration25, but before this one.

**Review by Crypt-iQ — APPROVED** [review]
