### PR TITLE
watchtower: Add retry logic for fetching blocks

### LINKED ISSUE #8205: [bug]: Watchtower gives up to fetch block in case of timeout
### Background

Describe your issue here.

If lnd watchtower fails to fetch a block, it looks like it never tries it again and thus it might not do its job. This would be especially an issue when using neutrino backend. It seems to be related to this comment in the code: https://github.com/lightningnetwork/lnd/blob/d9b88fba67a91583227d1d986deaa05177585bb1/watchtower/lookout/lookout.go#L125

Failing because of some timeout (no clue yet what is the exact reason behind that):

2023-11-18 18:37:29.084 [DBG] WTWR: Fetching block for (height=817357, hash=000000000000000000017421e65bd66c9432edd46c5e8b70cd4c12b542610e93)
2023-11-18 18:37:35.087 [ERR] WTWR: Unable to fetch block for (height=c78cd, hash=000000000000000000017421e65bd66c9432edd46c5e8b70cd4c12b542610e93): did not get response before timeout

Success after lnd restart:

2023-11-18 18:53:17.040 [DBG] WTWR: Fetching block for (height=817357, hash=000000000000000000017421e65bd66c9432edd46c5e8b70cd4c12b542610e93)
2023-11-18 18:53:23.034 [DBG] WTWR: Scanning 4350 transaction in block (height=817357, hash=000000000000000000017421e65bd66c9432edd46c5e8b70cd4c12b542610e93) for breaches
2023-11-18 18:53:23.133 [DBG] WTWR: No breaches found in (height=817357, hash=000000000000000000017421e65bd66c9432edd46c5e8b70cd4c12b542610e93)

### Your environment

* version of `lnd`: 0.17.0-beta
* which operating system: Linux 6.1.53-230601, x86_64
* version of `btcd`, `bitcoind`, or other backend: bitcoind v23.1.0 (pruned, blockfilterindex=1, peerblockfilters=1)
* running in docker cluster

### Steps to reproduce

No idea how to easily reproduce this exact case at the moment. It would be about searching for situation when the lnd with watchtower starts, connects to the (probably neutrino) backend and than the backend is disconnected.

### Expected behaviour

The watchtower retries to fetch the missing block or somehow loudly explicitly says that it gives up.

### Actual behaviour

It fails to obtain the wanted block due to timeout. It is not clear if it is just a temporary or permanent status. It is difficult to do any other diagnostics.

### PR DESCRIPTION
**Pull request by anibilthare**
## Change Description
Fixes #8205 , This change sets the total retry attempt count for fetching blocks to 4 (1 original attempt + 3 Retries).

## Steps to Test
I'm uncertain about how reviewers might naturally replicate a scenario in which the backend fails to deliver blocks to lnd. For testing purposes, I introduced a probabilistic failure in the GetBlock function (by returning a non-nil error). Below is the code snippet I used to implement this probabilistic error injection. For the purposes of testing, I have used bitcoind as backend.
```
type MyCustomError struct {
	Msg string
}

func (e MyCustomError) Error() string {
	return fmt.Sprintf("Error: %s", e.Msg)
}

func (b *BtcWallet) GetBlock(blockHash *chainhash.Hash) (*wire.MsgBlock, error) {
	rand.Seed(time.Now().UnixNano())
	randomNumber := rand.Intn(100) + 1
	_, ok := b.chain.(*chain.NeutrinoClient)
	if !ok {
		k, v := b.blockCache.GetBlock(blockHash, b.chain.GetBlock)
		if randomNumber < 20 {
			return k, v
		}
		return k, MyCustomError{Msg: "Animesh: Pseudo Error"}
	}

	// For the neutrino implementation of lnwallet.BlockChainIO the neutrino
	// GetBlock function can be called directly since it uses the same block
	// cache. However, it does not lock the block cache mutex for the given
	// block hash and so that is done here.
	b.blockCache.HashMutex.Lock(lntypes.Hash(*blockHash))
	defer b.blockCache.HashMutex.Unlock(lntypes.Hash(*blockHash))

	return b.chain.GetBlock(blockHash)
}
```
### Testing

image

This represents a scenario when block is finally fetched after all the attempts have been exhausted.

image

This represents a scenario when block is fetched after 2 attempts (1 original + 1 retry) have been exhausted.

image

This represents a scenario when block fetching fails.

I've been contemplating the practicality of implementing a unit test for this function. Given that we'll be mocking the `GetBlock` function to return either a nil or a non-nil error, I'm curious about the overall usefulness of such a test. Could someone help clarify if there's a significant benefit to this approach? I'm open to insights or suggestions on how we might enhance the testing strategy for this part of the code.

### CODE REVIEW

File: watchtower/lookout/lookout.go [hunk 1]
```diff
@@ -102,6 +103,52 @@ func (l *Lookout) Stop() error {
...
+// up to maxRetries times.
+//
+// Returns:
+// *wire.MsgBlock - A pointer to the fetched block, or nil if the block could
+// not be fetched after maxRetries attempts.
+// error - An error object indicating the failure reason in case the function
+// is unable to fetch the block; nil if the fetch is successful.
+//
+// Note: The function logs a message before each retry attempt after the first
+// failure.
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:133]: I think you can remove all of this :) the first few lines explain it pretty well :)

File: watchtower/lookout/lookout.go [hunk 2]
```diff
@@ -102,6 +103,52 @@ func (l *Lookout) Stop() error {
...
+func fetchBlockWithRetries(fetcher BlockFetcher, hash *chainhash.Hash,
+	maxRetries int) (*wire.MsgBlock, error) {
+	var block *wire.MsgBlock
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:136]: nit: add new line

File: watchtower/lookout/lookout.go [hunk 3]
```diff
@@ -118,9 +165,18 @@ func (l *Lookout) watchBlocks(epochs *chainntnfs.BlockEpochEvent) {
...
+			// arriving epoch from the backend.
+			// This is done using the fetchBlockWithRetries
+			// function, which attempts to fetch the block
+			// multiple times in case of temporary failures.
+			// This operation is crucial for keeping the local
+			// representation of the blockchain up-to-date with
+			// the newly arriving epoch, ensuring the system remains
+			// in sync with the backend.
+			block, err := fetchBlockWithRetries(l.cfg.BlockFetcher,
+				epoch.Hash, 3)
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:178]: nit: formatting 

block, err := fetchBlockWithRetries(
    l.cfg.BlockFetcher, epoch.Hash, 3, 
)

File: watchtower/lookout/lookout.go [hunk 4]
```diff
@@ -118,9 +165,18 @@ func (l *Lookout) watchBlocks(epochs *chainntnfs.BlockEpochEvent) {
...
-			block, err := l.cfg.BlockFetcher.GetBlock(epoch.Hash)
+			// Fetch the full block corresponding to the newly
+			// arriving epoch from the backend.
+			// This is done using the fetchBlockWithRetries
+			// function, which attempts to fetch the block
+			// multiple times in case of temporary failures.
+			// This operation is crucial for keeping the local
+			// representation of the blockchain up-to-date with
+			// the newly arriving epoch, ensuring the system remains
+			// in sync with the backend.
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:176]: i think the name of the function is self explanatory. So can leave this comment out or shorten it quite a bit I think

File: watchtower/lookout/lookout.go [hunk 5]
```diff
@@ -102,6 +103,52 @@ func (l *Lookout) Stop() error {
...
+// is unable to fetch the block; nil if the fetch is successful.
+//
+// Note: The function logs a message before each retry attempt after the first
+// failure.
+func fetchBlockWithRetries(fetcher BlockFetcher, hash *chainhash.Hash,
+	maxRetries int) (*wire.MsgBlock, error) {
+	var block *wire.MsgBlock
+	var err error
+
+	for attempt := 0; attempt <= maxRetries; attempt++ {
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:139]: what do you think about instead retrying indefinitely with an exponential back-off between retries?

File: watchtower/lookout/lookout.go [hunk 6]
```diff
@@ -118,9 +165,18 @@ func (l *Lookout) watchBlocks(epochs *chainntnfs.BlockEpochEvent) {
...
+			// multiple times in case of temporary failures.
+			// This operation is crucial for keeping the local
+			// representation of the blockchain up-to-date with
+			// the newly arriving epoch, ensuring the system remains
+			// in sync with the backend.
+			block, err := fetchBlockWithRetries(l.cfg.BlockFetcher,
+				epoch.Hash, 3)
+
 			if err != nil {
 				// TODO(conner): add retry logic?
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:181]: should remove this todo in this pr

File: watchtower/lookout/lookout.go (hunk 3 above)
Comment (ellemouton) [reply watchtower/lookout/lookout.go:178]: also - you could probably make `fetchBlockWithRetries` a method instead since then there is no need to pass the block fetcher. 

Then you can also more easily listen on the quit channel between retries

**Review by ellemouton — COMMENTED** [review]
Thanks for the PR @anibilthare! Left some comments

File: watchtower/lookout/lookout.go [hunk 7]
```diff
@@ -102,6 +103,52 @@ func (l *Lookout) Stop() error {
...
+	var block *wire.MsgBlock
+	var err error
+
+	for attempt := 0; attempt <= maxRetries; attempt++ {
+		if attempt > 0 {
+			log.Infof("Block fetch failed... Retrying attempt %d",
+				attempt)
+		}
+		block, err = fetcher.GetBlock(hash)
+		if err == nil {
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:145]: i think we still want to log the retry errors.

File: watchtower/lookout/lookout.go (hunk 3 above)
Comment (anibilthare) [reply watchtower/lookout/lookout.go:178]: > also - you could probably make `fetchBlockWithRetries` a method instead since then there is no need to pass the block fetcher.
> 
> Then you can also more easily listen on the quit channel between retries

Could you help me understand a bit more about your approach? How exactly are we planning to keep an eye on the quit channel? It kind of sounds like you're suggesting that every channel needs constant monitoring for breaches. Maybe I'm missing something here. Can you break it down a bit more for me? Thanks!

File: watchtower/lookout/lookout.go (hunk 5 above)
Comment (anibilthare) [reply watchtower/lookout/lookout.go:139]:
```
    const baseDelay = 1 // base delay in seconds
    const maxDelay = 60 // maximum delay in seconds

    for attempt := 0; ; attempt++ {
        block, err = fetcher.GetBlock(hash)
        if err == nil {
            return block, nil
        }

        // Calculate delay with exponential back-off
        delay := time.Duration(math.Min(math.Pow(2, float64(attempt)) * float64(baseDelay), float64(maxDelay))) * time.Second

        if attempt > 0 {
            log.Infof("Block fetch failed, retrying attempt %d after %v", attempt, delay)
        }

        // Wait for the calculated delay before the next attempt
        time.Sleep(delay)
    }
```

Does something like this makes sense? In case this project has some preferences about how delays are handled please let me know, for example, is calling `sleep` okay?

**Review by anibilthare — COMMENTED** [review]
Thanks for the review @ellemouton ! I'll address nits later once main logic has been finalised.

File: watchtower/lookout/lookout.go (hunk 3 above)
Comment (ellemouton) [reply watchtower/lookout/lookout.go:178]: ah - so the channel im referring to here is a golang channel, not a lightning channel.  So I mean the `Lookout`'s `quit chan struct` member. It will signal on that channel when it is exiting.

File: watchtower/lookout/lookout.go (hunk 5 above)
Comment (ellemouton) [reply watchtower/lookout/lookout.go:139]: yeah something like this but with a few tweaks:

1. I think you can just do something simple like this for the back off (copied this from the session negotiator) 
```
updateBackoff := func() {
		if backoff == 0 {
			backoff = n.cfg.MinBackoff
		} else {
			backoff *= 2
			if backoff > n.cfg.MaxBackoff {
				backoff = n.cfg.MaxBackoff
			}
		}
	}
```

2. We should not use `time.Sleep` in the code base since we cant listen on a quit channel while sleeping. so I suggest something like this at the end of your for-loop instead:

```
                 select {
		case <-time.After(backoff):
		case <-l.quit:
			return
		}
```

**Comment by anibilthare** [comment]
@ellemouton  I have implemented the change you suggested, I have further added a bool in the list of returned values, the purpose of the that is early exit so that we don't run into something weird (we might not, but I've placed it there for safety).

**Comment by anibilthare** [comment]
> Thanks @anibilthare :) Here is my suggested patch to your diff (i havent tested it yet so please do so): [towerRetry.patch](https://github.com/lightningnetwork/lnd/files/13948766/towerRetry.patch)
> 
> I've re-added the max-retries as well since we probably dont want a failure in 1 block to prevent us from fetching more blocks forever (my bad - I should have thought of this before 🙈 )
> 
> So this improves what we have today (which tries once and then moves on) _but_ eventually (in a different PR) we should be able to handle the case where one block fetch continues to fail: we should not let that prevent us from moving on but should also not just never get back to that block. So we should either handle retries of past blocks explicitly _or_ we should just do a hard error out (ie, LND will be forced to restart) if we cannot fetch the block after x number of retries since then clearly something is wrong.

Thanks for the patch @ellemouton  I have pushed the changes according to your suggestions. PTAL.

File: watchtower/lookout/lookout.go [hunk 8]
```diff
@@ -102,6 +122,50 @@ func (l *Lookout) Stop() error {
...
+		}
+	}
+
+	var attempt int
+	for {
+		attempt++
+
+		block, err := l.cfg.BlockFetcher.GetBlock(hash)
+		if err == nil {
+			log.Infof("ANIMESH: SUCCESSFULLY FETCHED!!")
```
Comment (ellemouton) [inline watchtower/lookout/lookout.go:146]: left over debug log 😉

Comment (anibilthare) [reply watchtower/lookout/lookout.go]: Fixed. Thanks!

File: docs/release-notes/release-notes-0.18.0.md [hunk 9]
```diff
@@ -129,6 +129,9 @@
 * [Added](https://github.com/lightningnetwork/lnd/pull/8142) full validation 
   for blinded path payloads to allow fuzzing before LND fully supports 
   blinded payment relay.
+* [Add retry logic for block fetching](https://github.com/lightningnetwork/lnd/pull/8381)
+  block fetching to retry indefinitely with an exponential back-off between
+  retries.
```
Comment (ellemouton) [inline docs/release-notes/release-notes-0.18.0.md:134]: I think you should mention that this is for a watchtower server

**Review by ellemouton — COMMENTED** [review]
Code looks good! 
Just need to rebase & add something to the release notes entry to show that this is a watchtower server change.

Also, in future - just click the re-request review button otherwise it doesnt show up in my review queue 🙏

**Comment by ellemouton** [comment]
closing as it seems the author has disappeared

**Comment by anibilthare** [comment]
@ellemouton  can I continue on this ? will it be possible for you to reopen this ?

**Comment by ellemouton** [comment]
@anibilthare  - re-opened 👍

**Comment by anibilthare** [comment]
@ellemouton  I have rebased my changes and updates release notes as well.

Can you please let me know if I need to move my release notes to some other file ? 

Apart from this can how please also tell me how do we decide where to put these release notes

**Comment by anibilthare** [comment]
@ellemouton  are these test locally runnable ?

**Review by ellemouton — COMMENTED** [review]
nice! I think this is good to go. 

Last thing is to move the release notes entry to the 19 doc 🙏  (can re-request from me once this is done)

Re you question about running the tests locally: yes you can run them locally but all of these here look like flakes & not related to this diff

**Comment by anibilthare** [comment]
@ellemouton  I have updated the docs. Thanks for the review

**Review by ellemouton — APPROVED** [review]
lgtm, thanks! 🚀 

cc @saubyk  for second reviewer here 🙏

**Comment by anibilthare** [comment]
@saubyk pls take a look

File: watchtower/lookout/lookout.go [hunk 10]
```diff
@@ -102,6 +122,49 @@ func (l *Lookout) Stop() error {
...
+	var attempt int
+	for {
+		attempt++
+
+		block, err := l.cfg.BlockFetcher.GetBlock(hash)
+		if err == nil {
+			return block, nil
+		}
+
+		if attempt >= l.cfg.MaxNumRetries {
```
Comment (bitromortac) [inline watchtower/lookout/lookout.go:149]: nit: technically `MaxNumRetries` is rather a `MaxNumTries` right now, so having `>` instead of `>=` would be more accurate

File: docs/release-notes/release-notes-0.19.0.md [hunk 11]
```diff
@@ -45,6 +46,12 @@
 ## Breaking Changes
 ## Performance Improvements
 
+## Misc
+
+* [Add retry logic for block fetching](https://github.com/lightningnetwork/lnd/pull/8381)
```
Comment (bitromortac) [inline docs/release-notes/release-notes-0.19.0.md:51]: please squash this commit with your main commit and remove the merge commit to have a clean commit history (you can just reset to master and then cherry pick your commit), ideally you'd end up with a single commit that contains all your changes

**Review by bitromortac — CHANGES_REQUESTED** [review]
Code LGTM, a single nit is left :tada:. Thanks for the PR! Could you rebase as described in the comment to have a clean commit history?

File: watchtower/lookout/lookout.go (hunk 10 above)
Comment (anibilthare) [reply watchtower/lookout/lookout.go]: Done, thanks!

File: docs/release-notes/release-notes-0.19.0.md (hunk 11 above)
Comment (anibilthare) [reply docs/release-notes/release-notes-0.19.0.md:54]: Done

File: docs/release-notes/release-notes-0.19.0.md [hunk 12]
```diff
@@ -48,6 +49,11 @@
 ## Performance Improvements
 
 * Log rotation can now use ZSTD 
+## Misc
+
+* [Add retry logic for block fetching](https://github.com/lightningnetwork/lnd/pull/8381)
+  block fetching to retry indefinitely with an exponential back-off between
```
Comment (bitromortac) [inline docs/release-notes/release-notes-0.19.0.md:55]: Thanks for the update, a final nit: 
`block fetching` is repeated here, and `indefinitely` is outdated, maybe you can change it to 

```
* [Add retry logic](https://github.com/lightningnetwork/lnd/pull/8381) for
  watchtower block fetching with a max number of attempts and exponential
  back-off.
```
If you're at it, we sort the list of contributors alphabetically. Also, the commit message is outdated, it mentions three times, but I think we retry five times.

**Review by ellemouton — CHANGES_REQUESTED** [review]
@anibilthare  - this still contains a merge commit

**Review by ellemouton — APPROVED** [review]
Cool - looks good. I think we can put the release notes entry under `Code Health` though.

File: docs/release-notes/release-notes-0.19.0.md [hunk 13]
```diff
@@ -75,6 +76,11 @@
 ## Performance Improvements
 
 * Log rotation can now use ZSTD 
+## Misc
```
Comment (ellemouton) [inline docs/release-notes/release-notes-0.19.0.md:79]: nit: missing new line above. 

But also can just put the entry under `Code Health` I'd say.

Comment (anibilthare) [reply docs/release-notes/release-notes-0.19.0.md]: Done.

**Review by bitromortac — APPROVED** [review]
LGTM :tokyo_tower:, thank you!

**Comment by ellemouton** [comment]
cc @guggero for override merge 🙏  (failing required check is unrelated)
