### PR TITLE
discovery: flatten future msg cache and increase its size

### LINKED ISSUE #7396: [bug]: Adding future message got error: can't insert entry of size XXX into cache with capacity 100
Versions:

lnd v0.15.5-beta-8-gb09afd4dd
bitcoind v23.0

A few days (I noticed it late), only one of the nodes [lnd-10] (apparently a very rare bug - I couldn't find anything about it) lost synchronization with the blockchain:

```
lncli getinfo|grep sync
    "synced_to_chain": false,
    "synced_to_graph": true,
```

But the problem was an error about which I could not find anything anywhere (this is already pure `grep`):

```
2023-02-06 14:03:01.403 [ERR] DISC: Adding future message got error: can't insert entry of size 101 into cache with capacity 100
2023-02-06 14:03:01.646 [ERR] DISC: Adding future message got error: can't insert entry of size 102 into cache with capacity 100
2023-02-06 14:03:03.430 [ERR] DISC: Adding future message got error: can't insert entry of size 103 into cache with capacity 100
2023-02-06 14:03:03.431 [ERR] DISC: Adding future message got error: can't insert entry of size 104 into cache with capacity 100
2023-02-06 14:03:06.571 [ERR] DISC: Adding future message got error: can't insert entry of size 105 into cache with capacity 100
2023-02-06 14:03:10.018 [ERR] DISC: Adding future message got error: can't insert entry of size 106 into cache with capacity 100
2023-02-06 14:03:10.019 [ERR] DISC: Adding future message got error: can't insert entry of size 107 into cache with capacity 100
2023-02-06 14:03:10.324 [ERR] DISC: Adding future message got error: can't insert entry of size 108 into cache with capacity 100
2023-02-06 14:03:11.307 [ERR] DISC: Adding future message got error: can't insert entry of size 109 into cache with capacity 100
2023-02-06 14:03:11.767 [ERR] DISC: Adding future message got error: can't insert entry of size 110 into cache with capacity 100
2023-02-06 14:03:11.767 [ERR] DISC: Adding future message got error: can't insert entry of size 111 into cache with capacity 100
2023-02-06 14:03:11.818 [ERR] DISC: Adding future message got error: can't insert entry of size 112 into cache with capacity 100
2023-02-06 14:03:12.913 [ERR] DISC: Adding future message got error: can't insert entry of size 113 into cache with capacity 100
...
2023-02-10 12:50:46.563 [ERR] DISC: Adding future message got error: can't insert entry of size 634 into cache with capacity 100
2023-02-10 12:50:48.818 [ERR] DISC: Adding future message got error: can't insert entry of size 635 into cache with capacity 100
2023-02-10 12:50:51.144 [ERR] DISC: Adding future message got error: can't insert entry of size 298 into cache with capacity 100
2023-02-10 12:51:06.149 [ERR] DISC: Adding future message got error: can't insert entry of size 281 into cache with capacity 100
2023-02-10 12:51:06.526 [ERR] DISC: Adding future message got error: can't insert entry of size 282 into cache with capacity 100
2023-02-10 12:51:16.850 [ERR] DISC: Adding future message got error: can't insert entry of size 115 into cache with capacity 100
2023-02-10 12:51:26.156 [ERR] DISC: Adding future message got error: can't insert entry of size 188 into cache with capacity 100
2023-02-10 12:51:33.202 [ERR] DISC: Adding future message got error: can't insert entry of size 116 into cache with capacity 100
2023-02-10 12:52:06.089 [ERR] DISC: Adding future message got error: can't insert entry of size 636 into cache with capacity 100
2023-02-10 12:53:28.213 [ERR] DISC: Adding future message got error: can't insert entry of size 399 into cache with capacity 100
2023-02-10 12:54:38.969 [ERR] DISC: Adding future message got error: can't insert entry of size 152 into cache with capacity 100
2023-02-10 12:54:47.504 [ERR] DISC: Adding future message got error: can't insert entry of size 400 into cache with capacity 100
```

before the error occurred , there were such lines:

```
2023-02-06 14:01:15.435 [INF] CRTR: Processed channels=0 updates=108 nodes=5 in last 59.999988483s
2023-02-06 14:01:28.614 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:31.658 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:36.460 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:40.325 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:41.639 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:41.817 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:43.798 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:45.481 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:45.665 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:45.936 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:47.943 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:48.983 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:49.315 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:51.776 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:53.474 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:57.735 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:57.904 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:01:59.622 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
..
2023-02-06 14:02:56.615 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:02:57.792 [WRN] DISC: Announcement for chan_id=(852433773024116737), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:02:57.792 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:02:58.605 [WRN] DISC: Announcement for chan_id=(852433773024116737), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:02:59.017 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:03:00.190 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:03:00.190 [WRN] DISC: Announcement for chan_id=(852433773024116737), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:03:01.402 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:03:01.403 [ERR] DISC: Adding future message got error: can't insert entry of size 101 into cache with capacity 100
2023-02-06 14:03:01.403 [WRN] DISC: Announcement for chan_id=(852433773024116737), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:03:01.646 [ERR] DISC: Adding future message got error: can't insert entry of size 102 into cache with capacity 100
2023-02-06 14:03:01.646 [WRN] DISC: Announcement for chan_id=(852433773024116737), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:03:03.430 [ERR] DISC: Adding future message got error: can't insert entry of size 103 into cache with capacity 100
2023-02-06 14:03:03.430 [WRN] DISC: Announcement for chan_id=(852433773024116737), is premature: advertises height 775284, only height 775282 is known
2023-02-06 14:03:03.431 [ERR] DISC: Adding future message got error: can't insert entry of size 104 into cache with capacity 100
2023-02-06 14:03:03.431 [WRN] DISC: Announcement for chan_id=(852433773016449025), is premature: advertises height 775284, only height 775282 is known
```

I found that the error is generated here `discovery/gossiper.go:1806` and to be related with `github.com/lightninglabs/neutrino/cache/lru`

### PR DESCRIPTION
**Pull request by yyforyongyu**
Fixes #7396. This PR flattens the slice used in future message cache and increases the cache size.

Depends on https://github.com/lightninglabs/neutrino/pull/268

### CODE REVIEW

File: discovery/gossiper.go [hunk 1]
```diff
@@ -423,8 +424,9 @@ type AuthenticatedGossiper struct {
 	// height specified in the future. We will save them and resend it to
 	// the chan networkMsgs once the block height has reached. The cached
 	// map format is,
-	//   {blockHeight: [msg1, msg2, ...], ...}
-	futureMsgs *lru.Cache[uint32, *cachedNetworkMsg]
+	//   {msgID1: msg1, msgID2: msg2, ...}
+	futureMsgs  *lru.Cache[uint64, *cachedFutureMsg]
```
Comment (Roasbeef) [inline discovery/gossiper.go:428]: Do we also need to do this to the premature message cache?

File: discovery/gossiper.go [hunk 2]
```diff
@@ -631,33 +633,62 @@ func (d *AuthenticatedGossiper) syncBlockHeight() {
...
+
 // resendFutureMessages takes a block height, resends all the future messages
-// found at that height and deletes those messages found in the gossiper's
-// futureMsgs.
+// found below and equal to that height and deletes those messages found in the
+// gossiper's futureMsgs.
 func (d *AuthenticatedGossiper) resendFutureMessages(height uint32) {
-	result, err := d.futureMsgs.Get(height)
+	// msgs are the target messages.
+	msgs := make([]*networkMsg, 0)
```
Comment (Roasbeef) [inline discovery/gossiper.go:656]: Can use `var` declaration if not pre-sizing any of the elements below.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: discovery/gossiper.go (hunk 2 above)
Comment (yyforyongyu) [reply discovery/gossiper.go]: Done.

File: discovery/gossiper.go (hunk 1 above)
Comment (yyforyongyu) [reply discovery/gossiper.go:433]: Good question. For premature messages, it's a bit different as we only expect premature `ChannelUpdate`s from the remote peer iff we are a participant of the channel, which means this `cache` could not grow that big? Anyway, have a local PR to enforce the logic "only allow premature `ChannelUpdate` iff we are a participant", and with another PR that fixes the validation barrier, this `cache` should then not be an issue.

**Review by Crypt-iQ — APPROVED** [review]
tACK 57851a40024413ccddfe5574c82351e64ad8efef

**Comment by Roasbeef** [comment]
Can be rebased now with the neutrino PR merged!

**Review by Roasbeef — CHANGES_REQUESTED** [review]
I think the final thing this needs is a basic test (could pull out the `futureMsgs` into a basic struct) to show that we no longer have the issue re adding more elements in the cache than the capacity. The cache should now reduce itself accordingly as each message is added.

File: discovery/gossiper.go [hunk 3]
```diff
@@ -632,33 +635,89 @@ func (d *AuthenticatedGossiper) syncBlockHeight() {
 	}
 }
 
+// futureMsgCache embeds a `lru.Cache` with a message counter that's served as
+// the unique ID when saving the message.
+type futureMsgCache struct {
```
Comment (Roasbeef) [inline discovery/gossiper.go:640]: 👍

**Review by Roasbeef — APPROVED** [review]
LGTM 🐺
