### PR TITLE
lncfg: add isIPv6Host helper to force v6 addrs through system resolver

### LINKED ISSUE #2541: unable to restlisten IPv6 address when tor=active
### Background

When tor.active=1, unable to restlisten to any IPv6 address

### Your environment

* version of `lnd` 0.5.1
* which operating system (`uname -a` on *Nix) 
Debian based

* version of `btcd`, `bitcoind`, or other backend
bitcoind 0.17.x

* any other relevant environment details

### Steps to reproduce

Create lnd.conf with the following contents:

[Application Options]
restlisten=[::]:8080

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.zmqpubrawblock=tcp://127.0.0.1:8301
bitcoind.zmqpubrawtx=tcp://127.0.0.1:8302

[Autopilot]
autopilot.active=0

[tor]
tor.active=1
tor.socks=127.0.0.1:9050

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

Run lnd with above lnd.conf.

### Expected behaviour

Should listen on [::]:8080 for REST connections and operate normally (ask for wallet passphrase etc).
If it's not going to support listening on REST port while Tor is active, that should be printed in the error message along with explanation and links to documentation.

### Actual behaviour

lnd aborts immediately printing only:

tor general error

Which is unexpected when the only thing added when going from a working configuration, to a non-working, is to add a restlisten line.

If you comment out either the tor.active line OR the restlisten line, it works as expected, but both together cause this error. 

with tor.active=1,
restlisten=[::1]:8080 - fails
restlisten=127.0.0.1:8080 - works
restlisten=0.0.0.0:8080 - works
restlisten=x.y.z.w:8080 (where x.y.z.w is an IP on the machine) - works
restlisten=[a:b:c:d:e:f:0:1]:8080 - where a:b:c:d:e:f:0:1 is an IPv6 address on the machine - fails

One clue is,
restlisten=hostname:8080 - fails with a different error
tor host is unreachable

So my GUESS is it's trying to use Tor to resolve a DNS entry for the host, which is incorrect, it should not resolve DNS for literal IPv6 addresses, whether Tor or not.

### PR DESCRIPTION
**Pull request by Crypt-iQ**
With this commit, if `--tor.active` is specified, then IPv6 addresses will no longer go through the `connmgr.TorLookupIP` function from btcd.  This function does not have proper IPv6 support and would fail with the error "tor general error".  Instead, use the system resolver.

Fixes #2541

### CODE REVIEW

File: lncfg/address.go [hunk 1]
```diff
@@ -121,6 +121,12 @@ func IsLoopback(addr string) bool {
 	return false
 }
 
+// isIPv6Host returns true if the host is IPV6 and false otherwise.
+func isIPv6Host(host string) bool {
+	// An IPv4 host without the port shouldn't have a colon.
+	return strings.Contains(host, ":")
```
Comment (guggero) [inline lncfg/address.go:127]: Wouldn't it need to also contain a `[` and `]` at this point to be valid? At least the `net.SplitHostPort()` function expects it that way. Perhaps we should add that to the check?

File: lncfg/address.go [hunk 2]
```diff
@@ -217,9 +223,10 @@ func ParseAddressString(strAddress string, defaultPort string,
 		}
 
 		// Otherwise, we'll attempt the resolve the host. The Tor
-		// resolver is unable to resolve local addresses, so we'll use
-		// the system resolver instead.
-		if rawHost == "" || IsLoopback(rawHost) {
+		// resolver is unable to resolve local or IPv6 addresses, so
+		// we'll use the system resolver instead.
+		if rawHost == "" || IsLoopback(rawHost) ||
+			isIPv6Host(rawHost) {
```
Comment (guggero) [inline lncfg/address.go:229]: nit: add extra newline after multiline `if` statement.

**Review by guggero — COMMENTED** [review]
Nice fix, thanks!
We should make the IPv6 check a bit more specific but apart from that LGTM :tada:

File: lncfg/address.go (hunk 1 above)
Comment (bhandras) [reply lncfg/address.go:127]: I believe a more correct method would be to `net.ParseIP` to parse and if not `nil` then check for `:`

**Review by bhandras — APPROVED** [review]
LGTM

File: lncfg/address.go (hunk 1 above)
Comment (Crypt-iQ) [reply lncfg/address.go:127]: I believe `net.SplitHostPort` removes the brackets and then it's just the raw host. IPv4 would not have a colon in the raw host.

File: lncfg/address.go [hunk 3]
```diff
@@ -121,6 +121,12 @@ func IsLoopback(addr string) bool {
 	return false
 }
 
+// isIPv6Host returns true if the host is IPV6 and false otherwise.
+func isIPv6Host(host string) bool {
```
Comment (Roasbeef) [inline lncfg/address.go:125]: This should use [`ParseIP`](https://golang.org/pkg/net/#ParseIP) so it can properly handle identifying the `IPv6` format. This is less error prone as if the string isn't actually an IPv6 address we'll be able to handle the error gracefully.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

**Comment by Roasbeef** [comment]
I think there's another related bug here: hosts which may actually be local aliases used for service discovery may fail when attempted to be resolved via Tor but succeed locally.

**Comment by Roasbeef** [comment]
I can reproduce the error above by adding an entry to say `localhost` in my `/etc/hosts`, then use that as `--restlisten` with `--tor.active`.
