### PR TITLE
Server-Peer Synchronization

### LINKED ISSUE #212: Test failure on fast machine. number of pending channels for alice incorrect. expected 0, got 1
When launching tests 
`go test -v`
following error occurs

=== RUN   TestLightningNetworkDaemon
--- FAIL: TestLightningNetworkDaemon (36.42s)
	lnd_test.go:3027: Running 18 integration tests
	lnd_test.go:85: Passed: (basic funding flow)
	lnd_test.go:85: Passed: (disconnecting target peer)
	lnd_test.go:85: Passed: (graph topology notifications)
	lnd_test.go:62: Failed: (funding flow persistence): exited with error: 
		*errors.errorString number of pending channels for alice incorrect. expected 0, got 1
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:256 (0xa2750b)
			assertNumOpenChannelsPending: "expected %v, got %v", expected, aliceNumChans)
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:577 (0xa296a5)
			testChannelFundingPersistence: assertNumOpenChannelsPending(ctxt, t, net.Alice, net.Bob, 0)
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:84 (0xa25f13)
			(*harnessTest).RunTestCase: testCase.test(net, h)
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:3029 (0xa3b5b3)
			TestLightningNetworkDaemon: ht.RunTestCase(testCase, lndHarness)
		/usr/local/go/src/testing/testing.go:657 (0x4ee786)
			tRunner: fn(t)
		/usr/local/go/src/runtime/asm_amd64.s:2197 (0x45b6b1)
			goexit: BYTE	$0x90	// NOP
=== RUN   TestAddSerializedKidsToList
--- PASS: TestAddSerializedKidsToList (0.00s)
=== RUN   TestSerializeKidOutput
--- PASS: TestSerializeKidOutput (0.00s)
FAIL
exit status 1
FAIL	github.com/lightningnetwork/lnd	36.451s

OR

=== RUN   TestLightningNetworkDaemon
--- FAIL: TestLightningNetworkDaemon (35.51s)
	lnd_test.go:3027: Running 18 integration tests
	lnd_test.go:85: Passed: (basic funding flow)
	lnd_test.go:85: Passed: (disconnecting target peer)
	lnd_test.go:85: Passed: (graph topology notifications)
	lnd_test.go:62: Failed: (funding flow persistence): exited with error: 
		*errors.errorString number of pending channels for bob incorrect. expected 0, got 1
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:261 (0xa2741f)
			assertNumOpenChannelsPending: expected, bobNumChans)
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:577 (0xa296a5)
			testChannelFundingPersistence: assertNumOpenChannelsPending(ctxt, t, net.Alice, net.Bob, 0)
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:84 (0xa25f13)
			(*harnessTest).RunTestCase: testCase.test(net, h)
		/go/src/github.com/lightningnetwork/lnd/lnd_test.go:3029 (0xa3b5b3)
			TestLightningNetworkDaemon: ht.RunTestCase(testCase, lndHarness)
		/usr/local/go/src/testing/testing.go:657 (0x4ee786)
			tRunner: fn(t)
		/usr/local/go/src/runtime/asm_amd64.s:2197 (0x45b6b1)
			goexit: BYTE	$0x90	// NOP
=== RUN   TestAddSerializedKidsToList
--- PASS: TestAddSerializedKidsToList (0.00s)
=== RUN   TestSerializeKidOutput
--- PASS: TestSerializeKidOutput (0.00s)
FAIL
exit status 1
FAIL	github.com/lightningnetwork/lnd	35.545s

It appears only on a relatively fast machine (like 128GB memory, 6 cores CPU). On my laptop, it never occurs. 
git commit: 74897dc328dbdeb59acd2b35d0288cdc03ec0f4c
go version: go1.8.1 linux/amd64
os: Linux 4.11.0-041100-generic 
repeatability: always.

### LINKED ISSUE #242: Unable to connect to remote node.
### Description
By one of our testers `mably` and others have been reported that `lnd` might getting into the state where other nodes are unable to establish the connection to it.

### Observation
* If we connect to the stuck machine over `ssh` and try to connect to other nodes it will lead to resolving the problem.
* If we connect to the stuck machine over `ssh` and check the `lsof` we will see that we have couple of `established` connections, but none of it is reflects in the `lncli listpeers`. Manually closing the `tcp` connection leads to the resolving the problem.
```
root@33554:~# lncli listpeers
{

}
root@33554:~# lsof -i:5656
COMMAND   PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
lnd     20678  lnd   10u  IPv6  314852455      0t0  TCP *:5656 (LISTEN)
lnd     20678  lnd   18u  IPv6  448638327      0t0  TCP 33554.s.time4vps.cloud:5656->202.28.248.231:57580 (ESTABLISHED)
lnd     20678  lnd   20u  IPv4 1370634882      0t0  TCP 33554.s.time4vps.cloud:37446->33346.s.time4vps.cloud:5656 (ESTABLISHED)
root@33554:~#
```
* Using the `delve` golang debugger I was unable to catch the program flow by setting the breakpoint in `connmanager.go:342 -> listenHandler`, which makes me feel that either the `listenHandler` exited, or it stuck on accepting the connection.

### Steps to reproduce
I have been able to reproduce it only once by writing the script which infinitely `connects` and than `disconnects` from the remote node. Running this script from two local nodes resulted in remote node stuck, but again, I was able to it only once.

### Assumptions
@Roasbeef wrote: Guess is a bug in state accounting, thinks it has a conn, but doesn't, or other way around.

### PR DESCRIPTION
**Pull request by cfromknecht**
This commit alters the synchronization patterns used in the server such that the internal state is protected by a single mutex.  Overall, this simplifies the ability to reason about the behavior and manipulation of the internal state, which has resolved a few flakes related to race conditions that were observed beforehand.

This PR originated as a fix for synchronizing the message broadcast, but has expanded into a full refactor of the server's synchronization.  A significant portion of this refactor was spent properly synchronizing disconnections from peers.  We observed a some flakes related to the timing of disconnections, particularly during restarts.  We also modified the implementation of `assertNumConnections` to poll for 3 seconds to ensure that the remote peer has acknowledged a disconnecting local peer, and has had time to gracefully exit.

To the best of my knowledge, this resolves #212 and resolves #242.  The former is improved by adding synchronization to message broadcasts, while the latter involved fixing a case where the server's lock was not released properly after attempting an outbound connection.

### CODE REVIEW

File: peer.go [hunk 1]
```diff
@@ -213,8 +208,8 @@ func (p *peer) Start() error {
 	// Before we launch any of the helper goroutines off the peer struct,
 	// we'll first ensure proper adherence to the p2p protocol. The init
 	// message MUST be sent before any other message.
-	readErr := make(chan error, 1)
-	msgChan := make(chan lnwire.Message, 1)
```
Comment (AndrewSamokhvalov) [inline peer.go]: What if read message return an error? In this case it probably might lead to goroutine waiting to write in `msgChan`, but nobody will read from it, because we exited from start.

File: htlcswitch/switch.go [hunk 2]
```diff
@@ -559,8 +559,6 @@ func (s *Switch) CloseLink(chanPoint *wire.OutPoint,
 		return updateChan, errChan
 
 	case <-s.quit:
-		errChan <- errors.New("unable close channel link, htlc " +
```
Comment (AndrewSamokhvalov) [inline htlcswitch/switch.go]: Could you please elaborate why you removed this line?

Comment (cfromknecht) [inline htlcswitch/switch.go]: This will likely not be in the final version of the PR, I was trying to test using unbuffered channels on travis and didn't want the code to hang if it exited for whatever reason.  I will remove this after rebasing.

File: server.go [hunk 3]
```diff
@@ -383,35 +366,38 @@ func (s *server) Stop() error {
...
-	if newStamp <= s.currentNodeAnn.Timestamp {
-		newStamp = s.currentNodeAnn.Timestamp + 1
-	}
-
-	s.currentNodeAnn.Timestamp = newStamp
-	s.currentNodeAnn.Signature, err = discovery.SignAnnouncement(
-		s.nodeSigner, s.identityPriv.PubKey(), s.currentNodeAnn,
+	s.currentNodeAnn.Timestamp = uint32(time.Now().Unix())
+	s.currentNodeAnn.Signature, err = discovery.SignAnnouncement(s.nodeSigner,
+		s.identityPriv.PubKey(), s.currentNodeAnn,
```
Comment (Roasbeef) [inline server.go]: The prior diff here is correct. Looks like a slight mistake introduced during a rebase.

File: server.go [hunk 4]
```diff
@@ -601,41 +606,86 @@ type nodeAddresses struct {
...
+
+func (s *server) sendToPeer(target *btcec.PublicKey, msgs []lnwire.Message) error {
+	// Compute the target peer's identifier.
+	targetPubBytes := target.SerializeCompressed()
+
+	srvrLog.Infof("Attempting to send msgs %v to: %x",
+		len(msgs), targetPubBytes)
+
+	// Lookup intended target in peersByPub, returning an error to the caller if
+	// the peer is unknown.  Access to peersByPub is synchronized here to ensure
```
Comment (Roasbeef) [inline server.go]: This line and a few others are over the 80-character limit observed uniformly throughout the codebase. I think you might need modify how your editor interprets tabs?

File: server.go [hunk 5]
```diff
@@ -601,41 +606,86 @@ type nodeAddresses struct {
...
-	case err := <-errChan:
-		return err
-	case <-s.quit:
-		return errors.New("server shutting down")
+	for _, msg := range msgs {
+		done := make(chan struct{})
+		select {
+		case targetPeer.outgoingQueue <- outgoinMsg{msg, done}:
+			select {
+			case <-done:
```
Comment (Roasbeef) [inline server.go]: I don't think the process of sending messages to a peer should be fully asynchronous. Currently, this API is by:
  * The `AuthenticatedGossiper` when broadcasting new node announcements
  * The `ChannelRouter` when syncing up a newly connected peer to our graph state
  * The `fundingManager` when processing the workflow of an active funding reservation 

In my mind, none of these cases require synchronous sends.

File: server.go (hunk 4 above)
Comment (cfromknecht) [inline server.go]: Thanks for catching this, I've update my .vimrc :)

File: server.go [hunk 6]
```diff
@@ -172,17 +153,17 @@ func newServer(listenAddrs []string, chanDB *channeldb.DB, cc *chainControl,
...
-			s.peersMtx.RLock()
-			peer, ok := s.peersByPub[string(pubKey)]
-			s.peersMtx.RUnlock()
-
-			if !ok {
+			peer, err := s.FindPeerByID(string(pubKey))
+			if err != nil {
 				srvrLog.Error("unable to close channel, peer"+
-					" with %v id can't be found", pubKey)
+					" with %v id can't be found: %v", pubKey, err)
```
Comment (halseth) [inline server.go]: line a bit long

File: server.go [hunk 7]
```diff
@@ -383,20 +366,38 @@ func (s *server) Stop() error {
...
 
-	// Signal all the lingering goroutines to quit.
-	close(s.quit)
+	// Wait for all lingering goroutines to quit.
 	s.wg.Wait()
 
 	return nil
 }
 
+// Stopped returns true if the server has been instructed to shutdown..
```
Comment (halseth) [inline server.go]: extra period

File: server.go [hunk 8]
```diff
@@ -383,20 +366,38 @@ func (s *server) Stop() error {
...
+// NOTE: This function is safe for concurrent access.
+func (s *server) Stopped() bool {
+	return atomic.LoadInt32(&s.shutdown) != 0
+}
+
+// WaitForShutdown blocks all goroutines have been stopped.
```
Comment (halseth) [inline server.go]: ...until all..?

File: server.go [hunk 9]
```diff
@@ -543,102 +542,147 @@ func (s *server) establishPersistentConnections() error {
...
+// NOTE: This method MUST provide a non-nil `wg` if it is spawned as a go
+// routine, otherwise `wg` should be nil.
+func (s *server) sendPeerMessages(
+	targetPeer *peer,
+	msgs []lnwire.Message,
+	wg *sync.WaitGroup) {
+
+	if wg != nil {
+		defer wg.Done()
+		defer s.wg.Done()
```
Comment (halseth) [inline server.go]: Not entirely clear from the godoc that the `s.wg` must be incremented if `wg` is non-nil.

File: server.go [hunk 10]
```diff
@@ -776,17 +813,20 @@ func shouldDropLocalConnection(local, remote *btcec.PublicKey) bool {
...
+// NOTE: This function is safe for concurrent access.
+func (s *server) InboundPeerConnected(conn net.Conn) {
+	nodePub := conn.(*brontide.Conn).RemotePub()
+	pubStr := string(nodePub.SerializeCompressed())
 
 	// If we already have an inbound connection to this peer, then ignore
 	// this new connection.
-	nodePub := conn.(*brontide.Conn).RemotePub()
-	pubStr := string(nodePub.SerializeCompressed())
+	s.mu.Lock()
```
Comment (halseth) [inline server.go]: Can you add a short comment why `defer Unlock()` is not used here? 😄

File: server.go (hunk 6 above)
Comment (cfromknecht) [inline server.go]: With 4-space tabs I only see this as 66 characters, are we doing our counts using 8-space tabs?

File: server.go (hunk 10 above)
Comment (cfromknecht) [inline server.go]: Originally this was done to keep consistency with the OutboundPeerConnected, but I think it makes sense now to do as you suggest, which is overall simpler and easier to understand :)

File: server.go (hunk 9 above)
Comment (cfromknecht) [inline server.go]: You're right that can be confusing, I think we can actually do without the need for a broadcast-specific wait group and just require that this method be run as a go routine and always signals `s.wg.Done()`

**Comment by cfromknecht** [comment]
I've added two new commits that resolve issues brought up by @halseth in `server.go` and `lnd_test.go`.  I reformatted the majority of `server.go` using 8-space tabs and made the requested typo fixes.  `InboundPeerConnected` and `OutboundPeerConnected` have been altered to employ the Lock/defer Unlock pattern.  `sendPeerMessages` has been updated to reflect the fact that it should always be called as a go routine, and removes broadcast-specific synchronization of message delivery.  `assertNumConnections` has also been changed so that it will exit early, instead of spinning for the full 3 seconds :)

File: server.go (hunk 9 above)
Comment (cfromknecht) [inline server.go]: I was mistaken, there were some flakes that were caused by not having synchronous broadcast (was the original intent of the PR after all 😂). I've updated the docs to hopefully alleviate the ambiguity

File: server.go [hunk 11]
```diff
@@ -648,21 +721,18 @@ func (s *server) findPeer(peerKey *btcec.PublicKey) (*peer, error) {
 // cleans up all resources allocated to the peer, notifies relevant sub-systems
 // of its demise, and finally handles re-connecting to the peer if it's
 // persistent.
-//
 // NOTE: This MUST be launched as a goroutine.
 func (s *server) peerTerminationWatcher(p *peer) {
+	defer p.wg.Done()
```
Comment (halseth) [inline server.go]: Since its is a bit confusing that this is tracked by the peer's waitgroup, could you add to the godoc the comment explaining that this is the case?

File: server.go [hunk 12]
```diff
@@ -1016,211 +1068,116 @@ type openChanReq struct {
...
+// NOTE: This function is safe for concurrent access.
+func (s *server) ConnectToPeer(addr *lnwire.NetAddress, perm bool) error {
 
-	targetPub := string(msg.addr.IdentityKey.SerializeCompressed())
+	targetPub := string(addr.IdentityKey.SerializeCompressed())
 
 	// Ensure we're not already connected to this
 	// peer.
-	s.peersMtx.RLock()
+	s.mu.Lock()
```
Comment (halseth) [inline server.go]: In this case _I think_ you cannot use the `defer Unlock()` pattern because you must unlock before calling `s.OutboundPeerConnected(nil, conn)`? Would be nice to have a small comment explaining this 😄

File: peer.go [hunk 13]
```diff
@@ -441,6 +440,7 @@ func newChanMsgStream(f *fundingManager, h *htlcswitch.Switch, p *peer,
 
 // Start starts the chanMsgStream.
 func (c *chanMsgStream) Start() {
+	c.wg.Add(1)
```
Comment (cfromknecht) [inline peer.go]: IMO, the preferred pattern, specifically for private go routines, is:
```
thing.wg.Add(1)
go thing.doSomething()
```
and that this should _imply_ that `thing` will (or at least should) always defer or signal Done to the wait group when that function exits.  Overall I think this improves readability, since we don't incur the extra lines from anonymous functions, and having a consistent pattern makes it easy for others to figure out which wait group is watching, and where it will be released.  It also helps ensure that each class is fully responsible for the go routines it spawns, as they are a resource that must be managed, just like any other.  Then, if you see a go routine spawned without incrementing a wait group, the mental alarms should go off.  Fortunately then, we can all apply this simple pattern to resolve such cases---unless there is a _very_ good reason to not do be watching a particular go routine.  I think it would make more sense to use the first pattern in the event that `msgConsumer` was designed for both synchronous and asynchronous invocation, and did not necessarily signal Done on its own. But in this case, we only use it as a go routine :)

File: peer.go [hunk 14]
```diff
@@ -1455,8 +1458,11 @@ func (p *peer) handleResponseClosingSigned(msg *lnwire.ClosingSigned,
 	// confirmation of the closing transaction, and mark the channel as
 	// such within the database (once it's confirmed").
 	notifier := p.server.cc.chainNotifier
+	p.wg.Add(1)
 	go waitForChanToClose(uint32(bestHeight), notifier, nil, chanPoint,
 		&closeTxid, func() {
+			defer p.wg.Done()
```
Comment (cfromknecht) [inline peer.go]: @halseth thanks for bringing this up, hadn't realized that the callback may not be executed

File: server.go [hunk 15]
```diff
@@ -172,17 +153,19 @@ func newServer(listenAddrs []string, chanDB *channeldb.DB, cc *chainControl,
...
+				srvrLog.Errorf("unable to close channel, peer"+
+					" with %v id can't be found: %v",
+					pubKey, err,
+				)
 				return
 			}
 
-			peer.localCloseChanReqs <- request
+			select {
+			case peer.localCloseChanReqs <- request:
```
Comment (cfromknecht) [inline server.go]: wish granted 🎩

File: server.go [hunk 16]
```diff
@@ -886,20 +916,18 @@ func (s *server) OutboundPeerConnected(connReq *connmgr.ConnReq, conn net.Conn)
 	nodePub := conn.(*brontide.Conn).RemotePub()
 	pubStr := string(nodePub.SerializeCompressed())
 
+	s.mu.Lock()
+	defer s.mu.Unlock()
```
Comment (cfromknecht) [inline server.go]: Originally that was the intention, but alas, readability hath prevailed :)

File: lnd_test.go [hunk 17]
```diff
@@ -267,25 +267,43 @@ func assertNumOpenChannelsPending(ctxt context.Context, t *harnessTest,
...
+				t.Fatalf("number of peers connected to alice is incorrect: "+
+					"expected %v, got %v", expected, len(aNumPeers.Peers))
+			}
+			if len(bNumPeers.Peers) != expected {
+				if i > 0 {
+					continue
+				}
+				t.Fatalf("number of peers connected to bob is incorrect: "+
+					"expected %v, got %v", expected, len(bNumPeers.Peers))
+			}
```
Comment (cfromknecht) [inline lnd_test.go]: Fixed now 🤓

File: peer.go (hunk 13 above)
Comment (halseth) [inline peer.go]: Yeah, if we stick to that pattern always goroutines should be fairly easy to track :)

Comment (cfromknecht) [inline peer.go]: Hopefully! Having a pattern is the important part 🙂

Forgot to mention! The approach above also allows you to mindlessly avoid accidentally capturing variables in scope that mutate, e.g. when iterating over a slice, since it forces you to pass in the parameters as arguments.

In some cases it may be useful to capture local variables and not have a tiny function with 8 arguments. There's never a one size fits all solution, but just some things to keep in mind if you have options :)
