### PR TITLE
Rebase bugfix PRs, prepare for minor release

### LINKED ISSUE #5890: possible issue with explicit chan type negotiation compatibility with eclair nodes
In commit 235efc04e4c9ad769516012ba8c2b5388d0f6664, `lightning.proto` defines:

```
enum CommitmentType {
    /*
    A channel using the legacy commitment format having tweaked to_remote
    keys.
    */
    LEGACY = 0;

    /*
    A channel that uses the modern commitment format where the key in the
    output of the remote party does not change each state. This makes back
    up and recovery easier as when the channel is closed, the funds go
    directly to that key.
    */
    STATIC_REMOTE_KEY = 1;

    /*
    A channel that uses a commitment format that has anchor outputs on the
    commitments, allowing fee bumping after a force close transaction has
    been broadcast.
    */
    ANCHORS = 2;

    /*
    Returned when the commitment type isn't known or unavailable.
    */
    UNKNOWN_COMMITMENT_TYPE = 999;
}
```

But in master cac8da819ff96769326b4d9b7648bf59a1049f74 this changed to:

```
enum CommitmentType {
    /*
    Returned when the commitment type isn't known or unavailable.
    */
    UNKNOWN_COMMITMENT_TYPE = 0;

    /*
    A channel using the legacy commitment format having tweaked to_remote
    keys.
    */
    LEGACY = 1;

    /*
    A channel that uses the modern commitment format where the key in the
    output of the remote party does not change each state. This makes back
    up and recovery easier as when the channel is closed, the funds go
    directly to that key.
    */
    STATIC_REMOTE_KEY = 2;

    /*
    A channel that uses a commitment format that has anchor outputs on the
    commitments, allowing fee bumping after a force close transaction has
    been broadcast.
    */
    ANCHORS = 3;

    /*
    A channel that uses a commitment type that builds upon the anchors
    commitment format, but in addition requires a CLTV clause to spend outputs
    paying to the channel initiator. This is intended for use on leased channels
    to guarantee that the channel initiator has no incentives to close a leased
    channel before its maturity date.
    */
    SCRIPT_ENFORCED_LEASE = 4;
}
```

### LINKED ISSUE #6001: "channel not found" causing shutdown after upgrade to 0.14
### Background

Subsequent to upgrading to 0.14, lnd is shutting down after wallet unlock.

### Your environment

* version of `lnd` "v0.14.0-beta"
* which operating system (`uname -a` on *Nix)  Linux 801bde55ca5b 5.4.0-89-generic Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 Linux
* version of `btcd`, `bitcoind`, or other backend bitcoind 0.21
* any other relevant environment details

### Steps to reproduce

The txid is very old, it has ~ 140,000 confirmations

```
....
2021-11-18 19:30:47.981 [DBG] CNCT: Starting ChannelArbitrator(<txid>:0), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>, state=StateWaitingFullResolution
2021-11-18 19:30:47.982 [INF] CNCT: ChannelArbitrator(<txid>:0): starting state=StateWaitingFullResolution, trigger=chainTrigger, triggerHeight=569380
2021-11-18 19:30:47.982 [DBG] CNCT: ChannelArbitrator(<txid>:0): attempting state step with trigger=chainTrigger from state=StateWaitingFullResolution
2021-11-18 19:30:47.982 [INF] CNCT: ChannelArbitrator(<txid>:0): still awaiting contract resolution
2021-11-18 19:30:47.982 [TRC] CNCT: ChannelArbitrator(<txid>:0): next_state=StateWaitingFullResolution
2021-11-18 19:30:47.982 [DBG] CNCT: ChannelArbitrator(<txid>:0): terminating at state=StateWaitingFullResolution
2021-11-18 19:30:47.982 [INF] CNCT: ChainArbitrator shutting down
....
2021-11-18 19:30:48.729 [ERR] LTND: Shutting down because error in main method: unable to start server: channel not found
....
```

### LINKED ISSUE #6002: "missing feature dependency: 23" after upgrade to 0.14.0-beta
### Background

lnd would not start after upgrading to 0.14.0-beta.
The last part of the output of `journalctl -u lnd`:
```
lnd[21138]: 2021-11-18 21:05:12.001 [INF] CHRE: LightningWallet opened                                          
lnd[21138]: 2021-11-18 21:05:12.006 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=true)! NOTE: Ensure the backend node is proxying over Tor as well
lnd[21138]: 2021-11-18 21:05:12.007 [INF] TORC: Starting tor controller                                         
lnd[21138]: 2021-11-18 21:05:12.009 [ERR] LTND: Shutting down because error in main method: unable to create server: invalid feature set SetInit: missing feature dependency: 23
lnd[21138]: 2021-11-18 21:05:12.009 [INF] TORC: Stopping tor controller                                         
lnd[21138]: 2021-11-18 21:05:12.010 [ERR] TORC: DEL_ONION got error: invalid arguments: unexpected code         
lnd[21138]: 2021-11-18 21:05:12.010 [ERR] LTND: error stopping tor controller: invalid arguments: unexpected code
lnd[21138]: 2021-11-18 21:05:12.027 [INF] LTND: Shutdown complete                                               
lnd[21138]: unable to create server: invalid feature set SetInit: missing feature dependency: 23                
```

### Your environment

* version of `lnd`: 0.14.0-beta
* Linux 5.10.63-v7l+ armv7l GNU/Linux
* bitcoind v22.0
* go1.16.7
* Tor version 0.3.5.15

### Steps to reproduce
* checkout v0.14.0-beta
* make install tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc routerrpc watchtowerrpc monitoring"
* **have `protocol.no-anchors=true` in lnd.conf**

(note: after disabling the `protocol.no-anchors=true`-line in my lnd.conf, lnd did start-up)

### Expected behaviour
lnd should start

### Actual behaviour
lnd not starting up with log lines as pasted above

### PR DESCRIPTION
**Pull request by guggero**
Replaces #6007.
Replaces #6003.

Fixes #6001.
Fixes #6002.
Fixes #5890.

Addresses an issue with explicit channel type negotiation that caused incompatibilities when opening channels with the latest versions of c-lightning and eclair (#5890).

### CODE REVIEW

**Review by bhandras — APPROVED** [review]
nit: I think the PR description needs an update to link to this PR https://github.com/lightningnetwork/lnd/pull/6003

LGTM :+1:

**Review by ellemouton — APPROVED** [review]
latest lgtm 🚀

File: funding/commitment_type_negotiation.go [hunk 1]
```diff
@@ -29,12 +29,32 @@ func negotiateCommitmentType(channelType *lnwire.ChannelType,
...
+		channelFeatures := lnwire.RawFeatureVector(*channelType)
+		staticRemoteKeyOnly := channelFeatures.OnlyContains(
+			lnwire.StaticRemoteKeyRequired,
+		)
+		anchorOnly := channelFeatures.OnlyContains(
+			lnwire.AnchorsZeroFeeHtlcTxRequired,
 		)
+
+		// It's one of the default types.
+		if staticRemoteKeyOnly || anchorOnly {
```
Comment (yyforyongyu) [inline funding/commitment_type_negotiation.go:52]: what if `staticRemoteKeyOnly` and `anchorOnly` are both true? can they?

Comment (guggero) [reply funding/commitment_type_negotiation.go:52]: That's not possible because of `OnlyContains`. That only returns true if that's the only flag that is set.

**Review by yyforyongyu — APPROVED** [review]

File: funding/manager.go [hunk 2]
```diff
@@ -1587,9 +1587,34 @@ func (f *Manager) handleFundingAccept(peer lnpeer.Peer,
...
 		}
 	} else if msg.ChannelType != nil {
-		err := errors.New("received unexpected channel type")
-		f.failFundingFlow(peer, msg.PendingChannelID, err)
-		return
+		// The spec isn't too clear about whether it's okay to set the
+		// channel type in the accept_channel response if we didn't
+		// explicitly set it in the open_channel message. For now, let's
+		// just log the problem instead of failing the funding flow.
+		log.Warnf("Peer sent explicit channel type even though we " +
```
Comment (Roasbeef) [inline funding/manager.go:1594]: In order to retain backwards compatibility before the feature bit for explicit chan type was added, this is actually ok (so we ca remove the log warning). 

The main thing we need to do is ensure the chan types match up at the end as we do below.

File: funding/commitment_type_negotiation.go [hunk 3]
```diff
@@ -29,12 +29,32 @@ func negotiateCommitmentType(channelType *lnwire.ChannelType,
...
+		// default types.
+		channelFeatures := lnwire.RawFeatureVector(*channelType)
+		staticRemoteKeyOnly := channelFeatures.OnlyContains(
+			lnwire.StaticRemoteKeyRequired,
+		)
+		anchorOnly := channelFeatures.OnlyContains(
+			lnwire.AnchorsZeroFeeHtlcTxRequired,
 		)
+
+		// It's one of the default types.
```
Comment (Roasbeef) [inline funding/commitment_type_negotiation.go:51]: The spec says "use the smallest bitmap possible", but leaves that somewhat open. For example, for anchors we'll set _both_ the bits above. 

This check here should be removed, causing us to fall back to implicit negotiation here has normal. Eventually, we'll require this bit and only accept an explicit channel type.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

**Comment by Roasbeef** [comment]
Patch to resolve the comment I made above: 
```diff
diff --git a/funding/commitment_type_negotiation.go b/funding/commitment_type_negotiation.go
index e2a9095a7..eb201e5b1 100644
--- a/funding/commitment_type_negotiation.go
+++ b/funding/commitment_type_negotiation.go
@@ -36,25 +36,6 @@ func negotiateCommitmentType(channelType *lnwire.ChannelType,
 				*channelType, local, remote,
 			)
 		}
-
-		// If they don't know explicit negotiation, let's fall back to
-		// implicit negotiation if they just signal one of the known
-		// default types.
-		channelFeatures := lnwire.RawFeatureVector(*channelType)
-		staticRemoteKeyOnly := channelFeatures.OnlyContains(
-			lnwire.StaticRemoteKeyRequired,
-		)
-		anchorOnly := channelFeatures.OnlyContains(
-			lnwire.AnchorsZeroFeeHtlcTxRequired,
-		)
-
-		// It's one of the default types.
-		if staticRemoteKeyOnly || anchorOnly {
-			return implicitNegotiateCommitmentType(local, remote), nil
-		}
-
-		// Something's weird, let's not accept this channel.
-		return 0, errUnsupportedExplicitNegotiation
 	}
 
 	return implicitNegotiateCommitmentType(local, remote), nil
diff --git a/funding/commitment_type_negotiation_test.go b/funding/commitment_type_negotiation_test.go
index c9ac25a7a..4da88f2a9 100644
--- a/funding/commitment_type_negotiation_test.go
+++ b/funding/commitment_type_negotiation_test.go
@@ -36,7 +36,8 @@ func TestCommitmentTypeNegotiation(t *testing.T) {
 				lnwire.StaticRemoteKeyOptional,
 				lnwire.AnchorsZeroFeeHtlcTxOptional,
 			),
-			expectsErr: errUnsupportedExplicitNegotiation,
+			expectsRes: lnwallet.CommitmentTypeAnchorsZeroFeeHtlcTx,
+			expectsErr: nil,
 		},
 		{
 			name: "explicit missing remote commitment feature",
@@ -181,8 +182,8 @@ func TestCommitmentTypeNegotiation(t *testing.T) {
 				return
 			}
 
-			require.Equal(t, testCase.expectsRes, localType)
-			require.Equal(t, testCase.expectsRes, remoteType)
+			require.Equal(t, testCase.expectsRes, localType, testCase.name)
+			require.Equal(t, testCase.expectsRes, remoteType, testCase.name)
 		})
 		if !ok {
 			return
```

**Comment by guggero** [comment]
Thanks! Applied the patch, going to test again vs. `c-lightning 0.10.2` locally.

**Review by Crypt-iQ — APPROVED** [review]
