### PR TITLE
routing: fix fee limit condition

### LINKED ISSUE #8940: [bug]: SendPaymentV2 does not respect fee limit setting in relation to inbound discounts
### Background

When paying to a payment request the caller can specify a fee limit for the maximum allowable fees to pay, with the assumption that if there is a route that has a fee within that constraint it will be used for the payment.

With the introduction of inbound discounts for routing fees, the fee limit does not respect these discounts and therefore will return no route found even when there is in fact a route that would fulfill the fee limit constraint after inbound discounts are applied.

This is problematic for probe-first payment flows that use the routing fee found in the probe as an input to the fee limit argument of SendPaymentV2

Describe your issue here.

### Your environment

- lnd 0.18.2

### Steps to reproduce

- Create A B C nodes, default routing fees to 1 sat
- Have B set an inbound discount on AB to allow traffic to be zero-fee when coming from A
- Probe or attempt paying A->C without a fee limit to confirm that the route from A to C would be zero fee
- Create an invoice on C and attempt to pay from A to C, with a fee limit of zero

### Expected behavior

- The fee limit should recognize the inbound discount and allow payment

### Actual behavior

- Payment fails with a no route error

### PR DESCRIPTION
**Pull request by bitromortac**
## Change Description
When iterating edges, pathfinding checks early whether using an edge would violate the requested total fee limit for a route. This check is done on the net amount (an amount the inbound fee is calculated with). However, a possible next hop's fee discount leads to a reduction in fees and as such using the net amount leads to assuming a higher cumulative fee than the route really has, excluding the path erroneously. With this PR, we perform the fee limit check on the amount to send, which includes both inbound and outbound fees, to fix #8940.

Todo:
- remove itest, add more lightweight test?

### CODE REVIEW

File: routing/pathfind.go [hunk 1]
```diff
@@ -722,6 +722,13 @@ func findPath(g *graphParams, r *RestrictParams, cfg *PathFindingConfig,
 		amountToSend := toNodeDist.netAmountReceived +
 			lnwire.MilliSatoshi(inboundFee)
 
+		// Check if accumulated fees would exceed fee limit when this
+		// node would be added to the path.
+		totalFee := int64(amountToSend) - int64(amt)
```
Comment (yyforyongyu) [inline routing/pathfind.go:727]: I find this log helpful when checking the behavior from the itest,
```go
log.Tracef("Checking toNode(%v) with minInboundFee=%v, inboundFee=%v, amountToSend=%v, amt=%v, totalFee=%v", toNodeDist.node, minInboundFee, inboundFee, amountToSend, amt, totalFee)
```

**Review by yyforyongyu — COMMENTED** [review]
Thanks for the quick fix! Just a few nits, otherwise LGTM.

> remove itest, add more lightweight test?

We do test inbound fees in `testMultiHopPayments`, but the `FeeLimitMsat` behavior was never tested there. We then have `testRouteFeeCutoff` which I think it's a bit difficult to add this test as it complicates things. So I'd prefer we keep the newly added test as it's straightforward.

A unit test can also be helpful, tho I'd say it's better to refactor the extremely long method `findPath` first.

Given this is a fairly small change and a bug fix, I think we can still make it into 0.18.3? cc @saubyk

File: routing/pathfind.go (hunk 1 above)
Comment (bhandras) [reply routing/pathfind.go:727]: +1 for the trace log, would be helpful when debugging inbound fees.

**Review by bhandras — APPROVED** [review]
Thanks for the super quick fix, LGTM, peding @yyforyongyu's comments 🎉

File: routing/pathfind.go [hunk 2]
```diff
@@ -722,6 +722,13 @@ func findPath(g *graphParams, r *RestrictParams, cfg *PathFindingConfig,
...
+		if totalFee > 0 && lnwire.MilliSatoshi(totalFee) > r.FeeLimit {
+			return
+		}
+
 		// Request the success probability for this edge.
 		edgeProbability := r.ProbabilitySource(
 			fromVertex, toNodeDist.node, amountToSend,
```
Comment (bitromortac) [inline routing/pathfind.go:734]: I think we should also correct `weight := edgeWeight(netAmountToReceive, fee, timeLockDelta)`  to `weight := edgeWeight(amountToSend, fee, timeLockDelta)`

Comment (yyforyongyu) [reply routing/pathfind.go:734]: in that case it should be `weight := edgeWeight(amountToSend, outboundFee, timeLockDelta)`?

Comment (bitromortac) [reply routing/pathfind.go:744]: the fee is just passed in there to be converted to `int64`, but isn't really related to the time lock weight, which is a bit strange and can be addressed in a refactor, so I think `weight := edgeWeight(amountToSend, fee, timeLockDelta)` is correct

**Comment by bitromortac** [comment]
Thanks for the quick reviews! I added some logging and a fix for the time lock weight.

Strange this doesn't compile with `Error: routing/pathfind.go:729:13: undefined: newLogClosure`, locally it works

File: routing/pathfind.go [hunk 3]
```diff
@@ -722,6 +721,24 @@ func findPath(g *graphParams, r *RestrictParams, cfg *PathFindingConfig,
 		amountToSend := toNodeDist.netAmountReceived +
 			lnwire.MilliSatoshi(inboundFee)
 
+		// Check if accumulated fees would exceed fee limit when this
+		// node would be added to the path.
+		totalFee := int64(amountToSend) - int64(amt)
+
+		log.Trace(newLogClosure(func() string {
```
Comment (yyforyongyu) [inline routing/pathfind.go:728]: This is now `lnutils.NewLogClosure`

**Review by yyforyongyu — COMMENTED** [review]
Needs a rebase to use the new log closure, otherwise LGTM.

File: routing/pathfind.go (hunk 3 above)
Comment (bitromortac) [reply routing/pathfind.go]: that was very strange, I could build the same commit on two different machines, maybe a github caching thing

**Review by yyforyongyu — APPROVED** [review]
LGTM🎉
