### PR TITLE
discovery: prevent endBlock overflow in replyChanRangeQuery

### LINKED ISSUE #4393: discovery: replyChannelRange overflow causes zero result reply
### Background

When processing query_channel_range, the incoming query includes a first_blocknum and num_block, both are uint32 values. According to BOLT7 there is no limitation on num_blocks in relation to the first_blocknum. This creates a situation where first_blocknum + num_blocks can overflow uint32 if not correctly handled by the receiving node.

In `syncer.replyChanRangeQuery`, when the end block is calculated, it does not account for the overflow. Go's implementation of integer overflows treats the addition as a modular addition resulting in an end block that is below the start block.
 
The final result is that zero records are returned.

### Your environment

* lnd version 0.10.99-beta commit=clock/v1.0.0-49-g9b8d51231c9cc5505380e911a45378f78d306190
* macOS: 10.15.5 

### Steps to reproduce

This was found testing a project that was sending custom gossip messages to various nodes.  The short of it is to construct a message with first_blocknum > 0 and num_blocks = uint32_max.

### Expected behaviour

It should returns results matching the range supplied, treating an overflow as wanting the maximum number of blocks. 

Below is a query that is constructed so that it does not trigger an overflow on an LND Node:  first_block + num_blocks = uint32_max.  The reply includes SCID results.

Query:
```
010743497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000001b0210ffe4fdef

0107 - type 263 (query_channel_range)
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 - chain_hash
001b0210 - first_blocknum (1770000)
ffe4fdef - num_blocks (4293197295)
```

Reply:
```
0108 - type 264 (reply_channel_range)
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 - chain_hash
001b0210 - first_blocknum (1770000)
ffe4fdef - num_blocks (4293197295)
01 - full_information (true)
00a9 - len (169)
00 - encoding type (uncompressed)
1b02480000140000 - scid
1b024c0000160001 - scid
1b024f00000d0000 - scid
1b024f00000d0001 - scid
1b02ae0000100000 - scid
1b02ae0000110000 - scid
1b02cb0000150000 - scid
1b02df0000090000 - scid
1b03340000120001 - scid
1b03ce0000050001 - scid
1b03ce0000060000 - scid
1b03ce0000070001 - scid
1b03ce0000080000 - scid
1b03cf00000e0000 - scid
1b03d000000d0000 - scid
1b03d000000e0001 - scid
1b04000000230000 - scid
1b04000000240001 - scid
1b04010000050001 - scid
1b04010000060000 - scid
1b04730000020000 - scid
```

### Actual behaviour

No results are returned when a message is constructed that triggers an overflow.  For example:  first_blocknum > 0, num_blocks= uint32_max. 

Query:
```
0107 - type 263 (query_channel_range)
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 - chain_hash
001b0210 - first_blocknum( 1770000)
ffffffff - num_blocks(4294967295)
```

Reply
```
0108 - type 264 (reply_channel_range) 
43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000
001b0210 - first_blocknum (1770000)
ffffffff - num_blocks (4294967295)
01 - full_information (true)
0001 - len (1)
00 - encoding type (uncompressed)
```

### PR DESCRIPTION
**Pull request by bmancini55**
One line change to `syncer.replyChanRangeQuery` to ensure endBlock calculation doesn't overflow.  Adds a test that performs multiple queries to ensure the correct start / end block values are supplied to the channel graph filter.

Fixes #4393

### CODE REVIEW

File: discovery/syncer_test.go [hunk 1]
```diff
@@ -915,6 +915,118 @@ func TestGossipSyncerReplyChanRangeQuery(t *testing.T) {
...
+			}
+		}
+	}()
+
+	// Wait for the results to be collected and validate that the
+	// collected results match the expected results, the timeout to
+	// expire, or an error to occur
+	select {
+	case capFilterReq := <-resultsCh:
+		if !reflect.DeepEqual(expFilterReqs, capFilterReq) {
```
Comment (wpaulino) [inline discovery/syncer_test.go:1017]: Nit: could use `require.Equal` here for better failure output.
