### PR TITLE
cmd/lncli/walletrpc_active.go: avoid nested getContext

### LINKED ISSUE #7161: [bug]: lncli wallet bumpclosefee => intercept already started
### Background

When running lncli wallet bumpclosefee on a standard lnd/lncli build, I get 'intercept already started' as an error message
### Your environment

* `lnd`: current master 478b01267289fa913d1be1e1357b2c4f582de7d3
* which operating system (`uname -a` on *Nix): `Linux murphy 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: bitcoind 23.0

### Steps to reproduce

Run lncli wallet bumpclosefee with superficially valid arguments (channel point should be parseable but doesn't need to belong to a channel waiting close)

### Expected behaviour

Fee bump or an error message like "channel not found"

### Actual behaviour

`intercept already started`

### Thoughts

Both `bumpCloseFee` and its callee `getWaitingCloseCommitments` do getContext(), which seems to set up an interceptor and complain if it's done twice. I've tried a change that passes bumpCloseFee's getContext() result into `getWaitingCloseCommitments`, and got expected behavior from lncli instead of "interceptor already started".

### PR DESCRIPTION
**Pull request by akovalenko**
Pass down a context from bumpCloseFee to getWaitingCloseCommitments, to avoid another call to getContext that used to fail with "intercept already active"

## Change Description
Fixes #7161
 
## Steps to Test
Run `lncli wallet bumpclosefee` with valid arguments. Before this patch, you get "intercept already started" even before checking for channel existence

### CODE REVIEW

File: cmd/lncli/walletrpc_active.go [hunk 1]
```diff
@@ -379,12 +381,11 @@ func bumpCloseFee(ctx *cli.Context) error {
 	return nil
 }
 
-func getWaitingCloseCommitments(client lnrpc.LightningClient,
+func getWaitingCloseCommitments(ctxc context.Context,
```
Comment (sputn1ck) [inline cmd/lncli/walletrpc_active.go:384]: nit:  i think the formatting could be improved, maybe
```
func getWaitingCloseCommitments(ctxc context.Context,
	client lnrpc.LightningClient, channelPoint string) (
	*lnrpc.PendingChannelsResponse_Commitments, error) {
```

**Review by sputn1ck — COMMENTED** [review]
Tested the changes locally and works now as expected.

Just a minor formatting nit

File: cmd/lncli/walletrpc_active.go [hunk 2]
```diff
@@ -320,7 +321,8 @@ func bumpCloseFee(ctx *cli.Context) error {
 	defer cleanUp()
 
 	// Fetch waiting close channel commitments.
-	commitments, err := getWaitingCloseCommitments(client, channelPoint)
+	commitments, err := getWaitingCloseCommitments(ctxc,
```
Comment (guggero) [inline cmd/lncli/walletrpc_active.go:324]: nit: please format this according to [our formatting rules](https://github.com/lightningnetwork/lnd/blob/master/docs/code_formatting_rules.md#wrapping-long-function-calls).

**Review by guggero — APPROVED** [review]
Nice catch! LGTM, just one additional nit.

And can you please squash your commits and either add the PR and yourself to the release notes or add the `[skip ci]` suffix to the commit title.

**Review by sputn1ck — APPROVED** [review]
