### PR TITLE
multi: refresh peer IP during reconnect

### LINKED ISSUE #5377: Peers are unable to reconnect and stuck in a deadlock after IP address change
As described by @t-bast in https://gitter.im/ACINQ/eclair LND and eclair (possibly c-lightning) peers are unable to reconnect after a IP address change due to not trusting `node_announcement`:

> if you change your IP address, your peers won't reconnect to you. They'll wait for you to connect to them and then will store your new IP address for future reconnections (ie they don't trust the new IP address from `node_announcement` alone)

This leads to a situation where even some clearnet peers have to be manually reconnected which can be quite time consuming and TOR peers are stuck in a deadlock that can only manually be resolved by the node operator of each and every TOR peer. They would have to look up the new IP address of their offline peer on one of the lightning explorer websites and manually feed it to their node. This is unlikely to happen quickly, if at all.

I changed the IP of my node more than 2 days ago and still have 65 disconnected TOR peers. Most, if not all of them seem to be running LND.

I'd suggest to use the IP from `node_announcement` if a connection to the last known IP fails. Can still be alternated with last known IP until success.

Also reported to eclair: https://github.com/ACINQ/eclair/issues/1842

### PR DESCRIPTION
**Pull request by ellemouton**
Fixes #5377 

With this PR, we ensure that when a persistent outbound peer changes its IP address we can reconnect to it. This is done by periodically fetching the peer's latest advertised IP address from the DB and updating the connection request to the peer accordingly.

A new itest, `reconnect_after_ip_change` demonstrates that the original bug and shows how this PR fixes the bug

### CODE REVIEW

File: routing/router.go [hunk 1]
```diff
@@ -1327,6 +1334,19 @@ func (r *ChannelRouter) processUpdate(msg interface{},
...
+		pk, err := msg.PubKey()
+		if err != nil {
+			return err
+		}
+
+		// If we currently have any connection requests pending for this
+		// node then update the requests if the node address has changed.
+		if err = r.cfg.UpdateConnRequests(pk, msg.Addresses); err != nil {
+			return errors.Errorf("unable to update "+
+				"connection requests for node%v: %v",
```
Comment (bhandras) [inline routing/router.go:1346]: nit: missing space before first `%v`

File: server.go [hunk 2]
```diff
@@ -3726,6 +3727,51 @@ func (s *server) connectToPeer(addr *lnwire.NetAddress,
 	s.OutboundPeerConnected(nil, conn)
 }
 
+// updateConnRequests checks to see if there are any existing connection requests
+// active for the given pubKey and if there are then it checks that there are
+// connection requests active for all the given addresses. If any are missing
+// then new connection requests are created.
+func (s *server) updateConnRequests(pubKey *btcec.PublicKey, addrs []net.Addr) error {
```
Comment (bhandras) [inline server.go:3734]: nit: we never return with error?

File: routing/router.go [hunk 3]
```diff
@@ -335,6 +336,12 @@ type Config struct {
 	// returned.
 	QueryBandwidth func(edge *channeldb.ChannelEdgeInfo) lnwire.MilliSatoshi
 
+	// UpdateConnRequests checks if there are currently any connection
+	// requests to a node with the given pubKey. If there are and if the
+	// nodes net addresses have changed then the old connection requests
```
Comment (bhandras) [inline routing/router.go:341]: Something I miss here is that the comment says that the old connection request are cancelled, but the implementation doesn't do that?

File: server.go [hunk 4]
```diff
@@ -3726,6 +3727,51 @@ func (s *server) connectToPeer(addr *lnwire.NetAddress,
...
+	s.mu.Lock()
+	defer s.mu.Unlock()
+
+	// Check if there are currently any connection requests for this node.
```
Comment (bhandras) [inline server.go:3738]: Something I don't fully understand is that isn't this inherently a race? As in if the address changes we only ever connect to that new address if we are right in the middle of connecting to the node anyway?

Comment (ellemouton) [reply server.go:3738]: Ah ok yeah is your question basically 'what happens if we somehow get the node announcement before we run `peerTerminationWatcher`? 

For some reason im having hard time recreating this situation in the itest (cant seem to force the NodeAnnouncement to be received before peerTerminationWatcher has run no matter where i add delays 🤔 )

To address this though, what do you think about:
1) removing the `if p.Inbound()` [here](https://github.com/lightningnetwork/lnd/blob/master/server.go#L3500) so that latest addresses are fetched from node announcement no matter if peer was inbound or outbound
2) also then fetching latest advertised addresses again after the backoff [here](https://github.com/lightningnetwork/lnd/blob/master/server.go#L3564)

we would still need to keep the UpdateConnReqs though for the case where NodeAnnouncement is received after peerTerminationWatcher has run

**Review by ellemouton — COMMENTED** [review]
Thanks for the review @bhandras :) I have fixed the nits and added a question to your one comment

File: lntest/itest/lnd_misc_test.go [hunk 5]
```diff
@@ -177,6 +177,80 @@ func testDisconnectingTargetPeer(net *lntest.NetworkHarness, t *harnessTest) {
...
+	// Change Bob's listening port and restart.
+	net.Bob.Cfg.P2PPort = lntest.NextAvailablePort()
+	if err := net.RestartNode(net.Bob, nil); err != nil {
+		t.Fatalf("unable to restart bob's node: %v", err)
+	}
+
+	// Check that Charlie and Bob did not reconnect once Bob restarted.
+	// This is the bug that will be fixed in a following commit.
+	assertConnected(t, net.Bob, charlie, false)
+
```
Comment (yyforyongyu) [inline lntest/itest/lnd_misc_test.go:245]: We should also check other functions such as `SendPayment` can also work after the reconnection.

File: routing/router.go [hunk 6]
```diff
@@ -1327,6 +1335,16 @@ func (r *ChannelRouter) processUpdate(msg interface{},
...
 
+		pk, err := msg.PubKey()
+		if err != nil {
+			return err
+		}
+
+		// If we currently have any connection requests pending for
+		// this node then update the requests if the node addresses
+		// have changed.
+		r.cfg.UpdateConnRequests(pk, msg.Addresses)
```
Comment (yyforyongyu) [inline routing/router.go:1346]: Not sure if `router` should be handling this as it's already saving the node info to db. Some other service could just read the info from db and apply the necessary changes there.

File: server.go (hunk 4 above)
Comment (yyforyongyu) [reply server.go:3738]: > removing the if p.Inbound() here so that latest addresses are fetched from node announcement no matter if peer was inbound or outbound
also then fetching latest advertised addresses again after the backoff here

Sounds good to me.

> we would still need to keep the UpdateConnReqs though for the case where NodeAnnouncement is received after peerTerminationWatcher has run

Not sure that I follow. What is the problem if `NodeAnnouncement` is received after `peerTerminationWatcher`?

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
I think modifying `peerTerminationWatcher` to fetch the latest net addr is good enough. In essence, a peer changing its IP is equivalent to a peer going offline then online. We need to properly handle the case where we need to clean old states (like disconnect peer, remove the links, etc), then attempt to reconnect using the new IP (also means updating states like the address in brontide's config). `peerTerminationWatcher` has almost done everything already, except fetching the updated net addr.

File: lntest/itest/lnd_misc_test.go [hunk 7]
```diff
@@ -177,6 +177,80 @@ func testDisconnectingTargetPeer(net *lntest.NetworkHarness, t *harnessTest) {
...
+		lntest.OpenChannelParams{
+			Amt: 1000000,
+		},
+	)
+
+	// Sleep for a second so that the timestamp of the NodeAnnouncement
+	// that Bob will send below after changing his listening port will be
+	// younger than the timestamp Bob's NodeAnnouncement sent after the
+	// channel open above.
+	time.Sleep(time.Second)
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply lntest/itest/lnd_misc_test.go:232]: Seems that if the 2 NodeAnnouncements about the same node are received in the same second then the second one is ignored as the node thinks it has received it already

File: server.go (hunk 4 above)
Comment (ellemouton) [reply server.go:3738]: peerTerminationWatcher creates the connection requests that will be used to reconnect to the peer and uses the currently stored addresses for that node. If the peer changes their address, but we only get their NodeAnnouncement that includes the new addresses after we have run peerTerminationWatcher, then the connection requests that we created will have the incorrect addresses

File: lntest/itest/lnd_misc_test.go [hunk 8]
```diff
@@ -87,7 +87,7 @@ func testDisconnectingTargetPeer(net *lntest.NetworkHarness, t *harnessTest) {
 	time.Sleep(time.Millisecond * 300)
 
 	// Assert that the connection was torn down.
-	assertNumConnections(t, alice, bob, 0)
+	assertConnected(t, alice, bob, false)
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply lntest/itest/lnd_misc_test.go:90]: cool, will add another func 👍

File: server.go (hunk 4 above)
Comment (yyforyongyu) [reply server.go:3738]: I see. Then I think we need to fetch the node info from db again to get the latest address.

File: lntest/itest/lnd_misc_test.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (ellemouton) [reply lntest/itest/lnd_misc_test.go:232]: ie: i think the timestamp resolution of the NodeAnnouncement is 1 second. but will double check 👍

File: lntest/itest/lnd_misc_test.go (hunk 5 above)
Comment (ellemouton) [reply lntest/itest/lnd_misc_test.go:245]: cool, will add in the commit where the assertion changes from not connected to connected 👍

Comment (ellemouton) [reply lntest/itest/lnd_misc_test.go:245]: oh hmmmm actually im not sure if that would make sense? cause they dont have a channel between them. This test is purely testing reconnection of persistant peers that dont have channels between them. If they did have a channel between them then they would defs reconnect after IP change

File: server.go (hunk 4 above)
Comment (ellemouton) [reply server.go:3738]: well yes, but those latest addresses could still be old. We could get a NodeAnnouncement after we have done that. That is why I added the: `r.cfg.UpdateConnRequests(pk, msg.Addresses)` above so that if we do get a NodeAnnouncement after we have already fetched from the db and created connReqs, then things can be updated. I will also add refresh from db in peerTerminationWatcher, but i dont think I can remove the `UpdateConnRequests`. Thoughts?

File: routing/router.go (hunk 6 above)
Comment (ellemouton) [reply routing/router.go:1346]: See my comment below

Comment (ellemouton) [reply routing/router.go:1346]: related to my comment below, yes sure another service could read from the DB but the issue is that the other service would not know _when_ to refresh from the db

Comment (yyforyongyu) [reply routing/router.go:1346]: Though we haven't strictly defined the overall architecture, `routing` package should not be worrying about `net.Addr`. Its main purpose is to route HTLCs over the link layer. If other services don't know when to refresh the db, we could apply a publish-subscribe pattern, or, in this case, might just periodically refresh the db.

File: server.go (hunk 4 above)
Comment (yyforyongyu) [reply server.go:3738]: > I will also add refresh from db in peerTerminationWatcher

Yeah I think this would be good enough. As suggested in [this comment](https://github.com/lightningnetwork/lnd/issues/5377#issuecomment-861857325), we should handle persistent connections on their own dedicated scope. Down the bottom,`connmgr` handles the retries, but it does not refresh the address. Since `peerTerminationWatcher` is a wrapper above `connmgr`, maybe we could put some logic there to retrieve the updated address?

Unrelated to this PR, I think we need to someday extract all the connection management into its own package, saving us from the long `server.go` file, put up some nice unit tests, etc.

**Comment by ellemouton** [comment]
Thanks for the review @yyforyongyu  and @bhandras :) I have updated the PR and have written a much more detailed PR description. Please let me know what you guys think :)

File: routing/router.go (hunk 6 above)
Comment (ellemouton) [reply routing/router.go]: cool I have moved this to the gossiper package.

File: server.go (hunk 4 above)
Comment (ellemouton) [reply server.go:3747]: I have updated the PR and the PR description to explain why i think it is not enough to just refresh from the db in peerTerminationWatcher (the itest also fails if we only do this). Let me know what you think.

File: server.go [hunk 9]
```diff
@@ -3728,6 +3736,49 @@ func (s *server) connectToPeer(addr *lnwire.NetAddress,
...
+	pubStr := string(pubKey.SerializeCompressed())
+	reqs, ok := s.persistentConnReqs[pubStr]
+	if !ok {
+		return
+	}
+
+	connSet := make(map[string]bool)
```
Comment (yyforyongyu) [inline server.go:3754]: nit: add some docs to explain what is this for.

File: server.go [hunk 10]
```diff
@@ -3728,6 +3736,49 @@ func (s *server) connectToPeer(addr *lnwire.NetAddress,
...
+		if connSet[lnAddr.String()] {
+			continue
+		}
+
+		connReq := &connmgr.ConnReq{
+			Addr:      lnAddr,
+			Permanent: true,
+		}
+
+		s.persistentConnReqs[pubStr] = append(
```
Comment (yyforyongyu) [inline server.go:3774]: What about `s.persistentPeersBackoff` and `s.persistentRetryCancels`, do we need to update them too?

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
> Thanks for the review @yyforyongyu and @bhandras :) I have updated the PR and have written a much more detailed PR description. Please let me know what you guys think :)

Cool, thanks for the update! Left some comments, and thinking maybe it's easier to just put a loop and retry the connection inside `peerTerminationWatcher` to avoid potential race, no need to worry about when the `NodeAnnouncement` arrives, etc.

File: server.go (hunk 10 above)
Comment (ellemouton) [reply server.go]: latest change does update `s.persistentPeersBackoff` but i dont htink that  `s.persistentRetryCancels` needs to be updated

**Review by ellemouton — COMMENTED** [review]
Thanks for the idea @yyforyongyu :) I have updated :+1:

File: server.go [hunk 11]
```diff
@@ -17,6 +17,13 @@ import (
...
 	"time"
 
+	"github.com/lightningnetwork/lnd/cert"
+	"github.com/lightningnetwork/lnd/clock"
+	"github.com/lightningnetwork/lnd/healthcheck"
+	"github.com/lightningnetwork/lnd/kvdb"
+	"github.com/lightningnetwork/lnd/queue"
+	"github.com/lightningnetwork/lnd/ticker"
+
 	"github.com/btcsuite/btcd/btcec"
```
Comment (ellemouton) [inline server.go:27]: oops. fixing

File: lntest/harness.go [hunk 12]
```diff
@@ -671,7 +671,7 @@ func (n *NetworkHarness) EnsureConnected(ctx context.Context,
 // NOTE: This function may block for up to 15-seconds as it will not return
 // until the new connection is detected as being known to both nodes.
 func (n *NetworkHarness) ConnectNodes(ctx context.Context, t *testing.T,
-	a, b *HarnessNode) {
+	a, b *HarnessNode, perm bool) {
```
Comment (bhandras) [inline lntest/harness.go:674]: nit: (no need to change) alternatively we could have `ConnectNodes(...)` and `ConnectNodesPerm(...)` both calling to `connectNodes(..., perm bool)`.

File: lntest/itest/lnd_network_test.go [hunk 13]
```diff
@@ -60,6 +60,79 @@ func testNetworkConnectionTimeout(net *lntest.NetworkHarness, t *harnessTest) {
...
+	// is then able to pass Bob's NodeAnnouncement to Charlie.
+	ctxt, _ = context.WithTimeout(ctxb, channelOpenTimeout)
+	chanPoint := openChannelAndAssert(
+		ctxt, t, net, net.Alice, net.Bob,
+		lntest.OpenChannelParams{
+			Amt: 1000000,
+		},
+	)
+	defer func() {
+		ctxt, _ = context.WithTimeout(ctxb, channelCloseTimeout)
```
Comment (bhandras) [inline lntest/itest/lnd_network_test.go:113]: nit: do you need this context?

File: lntest/itest/lnd_network_test.go [hunk 14]
```diff
@@ -60,6 +60,79 @@ func testNetworkConnectionTimeout(net *lntest.NetworkHarness, t *harnessTest) {
...
+		closeChannelAndAssert(t, net, net.Alice, chanPoint, false)
+	}()
+
+	// Sleep for a second so that the timestamp of the NodeAnnouncement
+	// that Bob will send below after changing his listening port will be
+	// younger than the timestamp Bob's NodeAnnouncement sent after the
+	// channel open above.
+	time.Sleep(time.Second)
```
Comment (bhandras) [inline lntest/itest/lnd_network_test.go:121]: nit: maybe move this sleep right above where we restart the node?

**Review by bhandras — APPROVED** [review]
Changes LGTM, much cleaner in the latest iteration. Great work @ellemouton! :tada:  (Left a few optional nits to consider.)

I think the PR is ready to get merged but could you please check those itest flakes if any of them are related?

File: lntest/itest/assertions.go [hunk 15]
```diff
@@ -547,46 +547,114 @@ func assertNumOpenChannelsPending(ctxt context.Context, t *harnessTest,
...
-				"number of peers connected to %s is "+
-					"incorrect: expected %v, got %v",
-				alice.Name(), expected, len(aNumPeers.Peers),
+				"error listing %s's node (%v) peers: %v",
+				alice.Name(), alice.NodeID, err,
 			)
 		}
-		if len(bNumPeers.Peers) != expected {
+
+		for _, peer := range peers.Peers {
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply lntest/itest/assertions.go]: good idea, updated 👍

**Review by ellemouton — COMMENTED** [review]
Thanks for the review @bhandras 🚀 addressed most of the nits

File: server.go [hunk 16]
```diff
@@ -3575,6 +3575,81 @@ func (s *server) peerTerminationWatcher(p *peer.Brontide, ready chan struct{}) {
...
+
+				s.persistentConnReqs[pubStr] = append(
+					s.persistentConnReqs[pubStr], connReq,
+				)
+
+				return true
+			}
+
+			for !connected {
+				select {
```
Comment (yyforyongyu) [inline server.go:3634]: I think the `select` statement from L3566 to L3577 can be removed? It seems you already have a nice retry func here, no need to do that select above.

**Review by yyforyongyu — COMMENTED** [review]
Cool! This version is much better, only got a question, otherwise this is good to go.

File: server.go (hunk 16 above)
Comment (ellemouton) [reply server.go:3634]: the reason i left that select  in is that the logic is different depending on if it is the first time `s.connMgr.Connect(connReq)` that vs subsequent times. For the first time, we definitely want to call `s.connMgr.Connect(connReq)`. The subsequent times, we only call that if connReq address has changed

Comment (ellemouton) [reply server.go:3634]: but could also add a `firstReconnect` bool if you think that would be better?

**Comment by ellemouton** [comment]
> could you please check those itest flakes if any of them are related

im not entirely sure that they are not related. i seem to consistently get errors for certain configs ex bitcoind with etcd... and then non for others. I guess it must then be related to this pr... so i need to investigate further

File: server.go (hunk 16 above)
Comment (yyforyongyu) [reply server.go:3634]: Was thinking something like this, easier to show in code,

```go
        // First, cleanup any remaining state the server has regarding the peer
	// in question.
	s.removePeer(p)

	// Next, check to see if this is a persistent peer or not.
	_, ok := s.persistentPeers[pubStr]
	if !ok {
		return
	}

	// We'll only need to re-launch a connection request if one
	// isn't already currently pending.
	if _, ok := s.persistentConnReqs[pubStr]; ok {
		return
	}

	go func() {
		for {
			// We'll ensure that we locate an advertised address to use
			// within the peer's address for reconnection purposes.
			//
			// TODO(roasbeef): use them all?
			advertisedAddr, err := s.fetchNodeAdvertisedAddr(pubKey)
			switch {
			// We found an advertised address, so use it.
			case err == nil:
				p.SetAddress(advertisedAddr)

			// The peer doesn't have an advertised address.
			case err == errNoAdvertisedAddr:
				// Fall back to the existing peer address if
				// we're not accepting connections over Tor.
				if s.torController == nil {
					break
				}

				// If we are, the peer's address won't be known
				// to us (we'll see a private address, which is
				// the address used by our onion service to dial
				// to lnd), so we don't have enough information
				// to attempt a reconnect.
				srvrLog.Debugf("Ignoring reconnection attempt "+
					"to inbound peer %v without "+
					"advertised address", p)
				return

			// We came across an error retrieving an advertised
			// address, log it, and fall back to the existing peer
			// address.
			default:
				srvrLog.Errorf("Unable to retrieve advertised "+
					"address for node %x: %v", p.PubKey(),
					err)
			}

			// Otherwise, we'll launch a new connection request in order to
			// attempt to maintain a persistent connection with this peer.
			connReq := &connmgr.ConnReq{
				Addr:      p.NetAddress(),
				Permanent: true,
			}
			s.persistentConnReqs[pubStr] = append(
				s.persistentConnReqs[pubStr], connReq)

			// Record the computed backoff in the backoff map.
			backoff := s.nextPeerBackoff(pubStr, p.StartTime())
			s.persistentPeersBackoff[pubStr] = backoff

			// Initialize a retry canceller for this peer if one does not
			// exist.
			cancelChan, ok := s.persistentRetryCancels[pubStr]
			if !ok {
				cancelChan = make(chan struct{})
				s.persistentRetryCancels[pubStr] = cancelChan
			}

			// We choose not to wait group this go routine since the Connect
			// call can stall for arbitrarily long if we shutdown while an
			// outbound connection attempt is being made.
			srvrLog.Debugf("Scheduling connection re-establishment to "+
				"persistent peer %v in %s", p, backoff)

			select {
			case <-time.After(backoff):
			// If connected, the cancelChan will be closed.
			case <-cancelChan:
				return
			case <-s.quit:
				return
			}

			srvrLog.Debugf("Attempting to re-establish persistent "+
				"connection to peer %v", p)

			s.connMgr.Connect(connReq)
		}
	}()
}
```

Comment (yyforyongyu) [reply server.go:3634]: Further looked into the mechanism, things I'm not sure,
- when connected,  we will close the `cancelChan`? Thus we could rely on that instead of a `connected` bool.
- I noticed there's a lock used in `updateConnReq`. This part I'm not sure either, as there's a lock used above at L3453. Will this create a deadlock?

**Review by yyforyongyu — COMMENTED** [review]
> im not entirely sure that they are not related. i seem to consistently get errors for certain configs ex bitcoind with etcd... and then non for others. I guess it must then be related to this pr... so i need to investigate further

Yeah the `itest` part can be painful...I just triggered a re-run to see if we could get the same set of failures. If so it's probably caused by this PR.

For reference, previous failures,

bitcoind with etcd
```go
    --- FAIL: TestLightningNetworkDaemon/tranche02/43-of-83/bitcoind/switch_offline_delivery_outgoing_offline (159.34s)
    assertions.go:236: 
            Error Trace:    assertions.go:236
                                        assertions.go:201
                                        lnd_switch_test.go:1179
                                        test_harness.go:115
                                        lnd_test.go:247
            Error:          Received unexpected error:
                            unable to recv() from close stream: rpc error: code = DeadlineExceeded desc = context deadline exceeded
            Test:           TestLightningNetworkDaemon/tranche02/43-of-83/bitcoind/switch_offline_delivery_outgoing_offline
            Messages:       unable to close channel
```

This one is weird as I remembered sending a PR to fix the context issue, did you rebase on the master yet @ellemouton ?

bitcoind with txindex disabled
```go
    lnd_multi-hop_test.go:227: 
            Error Trace:    assertions.go:55
                                        assertions.go:71
                                        lnd_multi-hop_test.go:227
                                        lnd_multi-hop_htlc_aggregation_test.go:32
                                        lnd_multi-hop_test.go:111
            Error:          Received unexpected error:
                            rpc error: code = Unknown desc = peer 02ecae0ea15ec6369a169c5b5bad5df895b283eadf501d8ef0d173afcddce7b16a is not online
            Test:           TestLightningNetworkDaemon/tranche00/01-of-83/bitcoind/test_multi-hop_htlc/committype=anchors/local_htlc_aggregation
            Messages:       unable to open channel
```

btcd with ARM
```go
=== RUN   TestLightningNetworkDaemon/tranche00/01-of-83/btcd/test_multi-hop_htlc/committype=anchors/local_htlc_aggregation
    harness.go:660: 
            Error Trace:    harness.go:660
                                        lnd_multi-hop_test.go:212
                                        lnd_multi-hop_htlc_aggregation_test.go:32
                                        lnd_multi-hop_test.go:111
            Error:          Received unexpected error:
                            predicate not satisfied after time out
            Test:           TestLightningNetworkDaemon/tranche00/01-of-83/btcd/test_multi-hop_htlc/committype=anchors/local_htlc_aggregation
            Messages:       unable to connect Alice to Bob, got error: peers not connected within 30s seconds
```

btcd
```go
--- FAIL: TestLightningNetworkDaemon/tranche02/54-of-83/btcd/send_update_disable_channel
    test_harness.go:91: Failed: (send update disable channel): exited with error: 
        *errors.errorString did not receive channel update
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/assertions.go:789 (0xf21ed6)
            waitForChannelUpdate: t.Fatalf("did not receive channel update")
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_misc_test.go:1504 (0xf5d85f)
            testSendUpdateDisableChannel: waitForChannelUpdate(
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/test_harness.go:115 (0xf2f34e)
            (*harnessTest).RunTestCase: testCase.test(h.lndHarness, h)
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:247 (0xfd1f8f)
            TestLightningNetworkDaemon.func4: ht.RunTestCase(testCase)
        /home/travis/.gimme/versions/go1.16.3.linux.amd64/src/testing/testing.go:1193 (0x51dd6f)
            tRunner: fn(t)
        /home/travis/.gimme/versions/go1.16.3.linux.amd64/src/runtime/asm_amd64.s:1371 (0x471ca1)
            goexit: BYTE    $0x90   // NOP
```

**Comment by ellemouton** [comment]
> I noticed there's a lock used in updateConnReq. This part I'm not sure either, as there's a lock used above at L3453. Will this create a deadlock?

I dont think it will create a deadlock cause the lock is locked in the goroutine. So the lock will be unlocked when the function returns and then the gouroutine can grab it

**Comment by ellemouton** [comment]
Thanks @yyforyongyu , I have simplified it a bit more as you suggested. The itests also seem to be much happier now :)

File: server.go [hunk 17]
```diff
@@ -3509,6 +3516,12 @@ func (s *server) peerTerminationWatcher(p *peer.Brontide, ready chan struct{}) {
 
 			// The peer doesn't have an advertised address.
 			case err == errNoAdvertisedAddr:
+				// If it is an outbound peer then we fall
+				// back to the existing peer address.
+				if !p.Inbound() {
```
Comment (yyforyongyu) [inline server.go:3521]: Is it possible that an outbound peer gives an `errNoAdvertisedAddr`? If so, we might be iterating the loop too fast, as we `break` here, and then get the same error, then `break`, and forever...

**Comment by yyforyongyu** [comment]
PR looks pretty good to me now, just one final question in the comments.

File: server.go (hunk 17 above)
Comment (ellemouton) [reply server.go:3521]: This breaks out of the switch statement and will result in us using the previously stored address for the peer.. So it will still hit the backoff below.

Comment (ellemouton) [reply server.go:3521]: Im not sure if this check is needed though. Put it here the original switch statement was only run if the peer was inbound and the checks below seem inbound specific

Comment (yyforyongyu) [reply server.go:3521]: yeah me neither, probably not, not sure...the only difference I see is whether we want to keep reconnecting when tor connection is accepted.

**Review by yyforyongyu — APPROVED** [review]
LGTM🎇, just needs a rebase.

**Comment by Roasbeef** [comment]
> What we want to do is to add a second goroutine that checks for the new IP address and asks connMgr to retry with the new one.

Gotcha, I think what's missing here then was removing the old conn reqs (so they all wouldn't stack up).

File: server.go [hunk 18]
```diff
@@ -3910,7 +3988,7 @@ func (s *server) fetchNodeAdvertisedAddr(pub *btcec.PublicKey) (net.Addr, error)
 		return nil, errNoAdvertisedAddr
 	}
 
-	return node.Addresses[0], nil
+	return node.Addresses, nil
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply server.go:3994]: Thanks for the suggestion :) updated!

File: server.go [hunk 19]
```diff
@@ -3520,63 +3533,75 @@ func (s *server) peerTerminationWatcher(p *peer.Brontide, ready chan struct{}) {
...
 
-			srvrLog.Debugf("Attempting to re-establish persistent "+
-				"connection to peer %v", p)
+			// If we have already created a connection request
+			// with the same address, then there is no need to
+			// create a new one.
+			if prevConnReqAddr != nil && connReq.Addr.String() ==
+				prevConnReqAddr.String() {
+
+				continue
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply server.go:3650]: > But not sure if there is a better way? would maybe be fine if the backoff period was reset once the connection was reestablished but at the moment it doesnt do that)

Yeah the purpose of this back off is to ensure that if we connect, then the peer disconnects, we don't try to reconnect to it in a tight loop. The result of this new `for` loop is that we'll do many iterations here until we hit the back off upper limit then start to slow down some.

[the remark this answers is not in the document]
Comment (Roasbeef) [reply server.go:3650]: I think one way to address this would be to layer another back off (local to this method) to clamp down on the cycle speed of this new loop. In practice this should serve to ensure that we don't burn the greater back off (which should only be increased each time we disconnect from the peer, and not each time we try to refresh their address set).

**Comment by hsjoberg** [comment]
Just FYI, I have a situation right now where the IP address of a channel peer has changed.
This patch seems to work as intended.

**Comment by ellemouton** [comment]
Thanks for testing it out @hsjoberg! I'm currently working on a cleaner, event driven solution to this.

**Comment by hsjoberg** [comment]
@ellemouton Sound good, I'll hold on until then.

**Comment by ellemouton** [comment]
@Roasbeef, @yyforyongyu & @bhandras: I have created #5700 as an alternative to this PR. It uses an event driven approach.

**Comment by ellemouton** [comment]
ok, putting #5700 (big refactor) on the back burner again until 0.15 and revamping this PR instead for now.

File: server.go [hunk 20]
```diff
@@ -3493,95 +3493,96 @@ func (s *server) peerTerminationWatcher(p *peer.Brontide, ready chan struct{}) {
...
-			// The peer doesn't have an advertised address.
-			case err == errNoAdvertisedAddr:
-				// Fall back to the existing peer address if
-				// we're not accepting connections over Tor.
-				if s.torController == nil {
-					break
-				}
+	// We'll only need to re-launch a connection request if one
+	// isn't already currently pending.
+	if _, ok := s.persistentConnReqs[pubStr]; ok {
```
Comment (Roasbeef) [inline server.go]: Solid change here, eliminates a bunch of nesting 👍

File: server.go [hunk 21]
```diff
@@ -3583,12 +3596,89 @@ func (s *server) peerTerminationWatcher(p *peer.Brontide, ready chan struct{}) {
...
+// connectToPersistentPeer uses all the stored addresses for a peer to attempt
+// to connect to the peer. It creates connection requests if there are
+// currently none for a given address and it removes old connection requests
+// if the associated address is no longer in the latest address list for the
+// peer.
+func (s *server) connectToPersistentPeer(pubKeyStr string) {
+	s.mu.Lock()
+	defer s.mu.Unlock()
+
+	// Exit if this is not a persistent peer.
```
Comment (Roasbeef) [inline server.go:3704]: Is this necessary given it's checked above?

**Review by Roasbeef — APPROVED** [review]
LGTM 💎

One small comment, but looking really good other than that. Excited to proceed w/ that greater refactor in the next major version, but pleased with how this PR progressed in either case.

**Comment by Roasbeef** [comment]
Needs a rebase!

File: server.go (hunk 21 above)
Comment (ellemouton) [reply server.go]: cool, yeah, removed 👍

**Comment by viaj3ro** [comment]
Has this been thoroughly tested? I had another IP address change on my node and around 25 of my tor peers are still disconnected after 40 hours. The new IP was announced right after the change and 1ml picked it up around 15-30 minutes later.
