### PR TITLE
routing+lnrpc: add missing query routes parameters

### LINKED ISSUE #3150: queryroutes uses unrouteable final_cltv_delta value by default
### Background

The `queryroutes` command uses the `zpay32.DefaultFinalCltvDelta` value to extend to the final hop if none is specified with the request:

https://github.com/lightningnetwork/lnd/blob/4068e78af690f9b4a598de1f3f0b21b5560dd146/routing/router.go#L1398-L1403

However, using `sendtoroute` will fail on the exit hop with `FinalExpiryTooSoon` because of the check here:
https://github.com/lightningnetwork/lnd/blob/4068e78af690f9b4a598de1f3f0b21b5560dd146/invoices/invoiceregistry.go#L534-L540

The `finalCltvRejectDelta` is 13 which is greater than the final cltv default of 9, so this will fail.  Additionally, the default `--bitcoin.timelockdelta` config option is 40, so the final cltv should be _at least_ 40 or else the second check will probably fail given a user's configuration. This isn't a problem with the `addinvoice` command since that uses the `--bitcoin.timelockdelta` value.  This is a quick fix, so I can fix it once we decide on a fix.

### Your environment

* version of `lnd`: master

### PR DESCRIPTION
**Pull request by joostjager**
Over time, several new parameters have been added to the payment RPCs. But `QueryRoutes` hasn't kept up with those. This PR adds what is missing:

* Route hints
* Last hop restriction
* Outgoing channel restriction
* Destination node features

Furthermore an inconsistency with the default final cltv delta is fixed.

Fixes #3150

### CODE REVIEW

**Comment by C-Otto** [comment]
@alexbosworth https://github.com/lightningnetwork/lnd/pull/3926

File: routing/router.go [hunk 1]
```diff
@@ -1402,14 +1402,8 @@ type routingMsg struct {
 func (r *ChannelRouter) FindRoute(source, target route.Vertex,
 	amt lnwire.MilliSatoshi, restrictions *RestrictParams,
```
Comment (Tryiimaggie) [inline routing/router.go:1403]: Auburn at the end of the 4th

Comment (Tryiimaggie) [inline routing/router.go:1403]: 1+4+0+3=8🩵™️

**Review by Tryiimaggie — APPROVED** [review]
