### PR TITLE
[lnwallet] Only Forward Committed Settles and Fails

### LINKED ISSUE #977: Runtime error: invalid memory address or nil pointer dereference
LND stopped. I'm not sure if there's much to do about this or anything but it's certainly unexpected/undesired. I'm hoping the shutdown logs may help to fix an issue. Feel free to close this one if it's not helpful.

Version 0.4, on a Debian 4.9.20-grsec, 25G free RAM, Bitcoin Core RPC client version v0.15.99.0-9cf6393a4

2018-03-29 04:49:24.813 [INF] CRTR: Block 000000000000000000155720ac9c425fc94b9c6343e2da0a4bb43dbb735544e0 (height=515624) clo
sed 0 channels
2018-03-29 04:49:24.867 [INF] NTFN: New block: height=515624, sha=000000000000000000155720ac9c425fc94b9c6343e2da0a4bb43dbb7355
44e0
2018-03-29 04:49:24.867 [INF] UTXN: Attempting to graduate height=515624: num_kids=0, num_babies=0
2018-03-29 04:49:26.692 [INF] CRTR: Updated vertex data for node=0312c02755c6a3475f872be27e71fdb7703a61a25777401a26125e1c772c7e0f6a
2018-03-29 04:49:30.203 [INF] NTFN: Cancelling epoch notification, epoch_id=15092
2018-03-29 04:49:30.203 [INF] HSWC: ChannelLink(393a14959e5e974f2b1af08f50da837baf08a9cd47a78e1c8f91e50dbab8bf13:0) has exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8e8ef7]

goroutine 118602734 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*commitmentChain).tail(...)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1051
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).ReceiveNewCommitment(0xc5bb1ed200, 0x95876f9c07166d0e, 0xf027ee841935e65a, 0xca69236234982f72, 0xea563ca1e51eebb5, 0x56846c853f5fe541, 0xf2b3242d3bd13a74, 0x514c87875ae5ef7b, 0xd600a49189a4583f, 0x0, ...)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3648 +0xb7
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).handleUpstreamMsg(0xc5e688a5a0, 0x15b93c0, 0xc4ba8da300)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1235 +0xf08
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc5e688a5a0)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:921 +0x90e
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:391 +0x150

### LINKED ISSUE #1053: Startup Crash
### Background

Describe your issue here.

Left LND running, came back to it down. Started it back up and I get a start up crash every reboot.

### Your environment

* version of `lnd`  commit hash 13945de8060ad42e077988c1cf69e205dc11e528
* which operating system (`uname -a` on *Nix) . x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: btcd
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

StartLND, get 200 active chans on mainnet run for a while, but probably not too relevant.

### Expected behaviour

Tell us what should happen
No crasherino.

### Actual behaviour

Tell us what happens instead

Get a crash with the error below.
Starting up LND:
https://pastebin.com/QDLTqjcQ

Crash log:
https://pastebin.com/HLNuaTVL

### LINKED ISSUE #1124: lnd crashes while syncing channels with panic: runtime error: invalid memory address or nil pointer dereference (segmentation fault)
### Background

After a clean stop of lnd (via lnrpc stop), and then restarting lnd, the node runs for a few minutes, but then crashes with the message and dump: 

```
2018-04-24 10:12:44.022 [INF] HSWC: ChannelLink(1e49eb55a996b60dde39686e36cdc7e3039bf8b49454093265367b6ba7a28bac:0) has exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8b07ff]

goroutine 40072 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).evaluateHTLCView(0xc420271200, 0xc421ef4030, 0xc42a2fd518, 0xc42a2fd510, 0x43, 0x1, 0xc421dd7f80)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2392 +0x1cf
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).computeView(0xc420271200, 0xc421ef4030, 0x1, 0xc421ef4030, 0xc42403b020, 0xc42a2fde80, 0xc42a2fd5d0, 0x429d69)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3267 +0x179
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).validateCommitmentSanity(0xc420271200, 0x14, 0x20, 0x1, 0x0, 0x40c32e, 0xc420271368)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3357 +0x116
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc420271200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2851 +0x224
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc433670780, 0x3, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1440 +0x9d
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc433670780)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:879 +0x6cf
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:391 +0x14e
```

### Your environment

* lnd 0.4.1-beta
* 4.13.0-1011-azure 14-Ubuntu SMP Thu Feb 15 16:15:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind 0.16.0

### Steps to reproduce

Did not happen more than once (yet)

I had 65 open channels, on restart, received the above message.  
Full log of the session is attached (logging level only at info).

[lndlog.seg.txt](https://github.com/lightningnetwork/lnd/files/1945042/lndlog.seg.txt)

### PR DESCRIPTION
**Pull request by cfromknecht**
This PR fixes an issue that would cause us to forward a settle or fail prematurely, i.e. we would forward a settle or fail before it was fully committed by both commitment transactions. 

Previously, we had such a check for `Add` htlcs, and ensure that neither the `addCommitHeightRemote` and `addCommitHeightLocal` were both non-zero.  Here, we add the same constraints to `removeCommitHeightRemote` and `removeCommitHeightLocal`.

We also change the logic around when an `Fail` or `Settle` should be forwarded by requiring equality between the remote height and `removeCommitHeightRemote`. Currently, we use `>=` to determine when we should forward an HTLC in order to mimic the logic for `Add`s.

This change is more minor, and shouldn't result in any observed difference in behavior, but should provide an additional protection against forwarding the same settle or fail twice. The difference lies in that `Add` updates can persist in the log across multiple commitments after being added, while `Settle`s and `Fail`s are always removed immediately after being locked in.

Fixes #1124. 
Fixes #1053. 
Fixes #977.

### CODE REVIEW

File: lnwallet/channel_test.go [hunk 1]
```diff
@@ -4048,25 +4057,182 @@ func TestLockedInHtlcForwardingSkipAfterRestart(t *testing.T) {
...
+	// that the Fail has been locked in an can be forwarded.
+	fwdPkg, _, _, err = aliceChannel.ReceiveRevocation(bobRevocation)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if len(fwdPkg.Adds) != 0 {
+		t.Fatalf("alice shouldn't forward any HTLC's, instead wants to "+
+			"forward %v htlcs", len(fwdPkg.Adds))
+	}
+	if len(fwdPkg.SettleFails) != 1 {
```
Comment (Roasbeef) [inline lnwallet/channel_test.go]: We can strengthen this check a bit by ensuring the _proper failed HTLC is what's being forwarded.

Comment (cfromknecht) [reply lnwallet/channel_test.go]: Fixed.
