### PR TITLE
multi: replace `LockOutpoint` with `LeaseOutput`

### LINKED ISSUE #8476: [bug]: `locked_balance` in `WalletBalanceResponse` only counts "leased outputs", not "locked outpoints"
### Background

`OpenChannel` and `BatchOpenChannel` (via `FundPsbt`) lock coins differently. `OpenChannel` uses `LockOutpoint` and `FundPsbt` uses `LeaseOutput`.

While outputs reserved by `LeaseOutput` are surfaced in the `ListLeases` walletrpc endpoint and counted as `locked_balance` in the `WalletBalance` result, ones reserved by `LockOutpoint` aren't surfaced anywhere in the gRPC API.

This means that when using `BatchOpenChannel` and constructing a funding transaction, if a potential counterparty delays sending a signed commitment to open the channel, it's possible to see the total amount reserved to the channel opening attempt and which outputs are part of that reservation. However, when using `OpenChannel`, this data is invisible: it doesn't show up in the response to `WalletBalance` or `ListUnspent` or even `ListLeases`. It looks like the balance has disappeared until the attempt times out or succeeds, after which the balance reappears.

In our environment, I've built a temporary workaround by adding a `volatile_locked_balance` field in `WalletBalanceResponse` to count the coins locked by `LockOutpoint` (and therefore by `OpenChannel`). I'm happy to upstream this if desired, or you may want to choose a different approach, like including these in the regular `locked_balance` field.

We are also planning on (soon-ish) adding a workaround `ListLockedOutpoints` RPC endpoint, which I'll also be happy to upstream if you don't choose a different path, such as including these outpoints in `ListLeases` and somehow signaling that they're volatile/have no lazy expiration.

### Your environment

* version of `lnd`: any recent 
* which operating system (`uname -a` on *Nix): any
* version of `btcd`, `bitcoind`, or other backend: any
* any other relevant environment details: none

### Steps to reproduce

An integration test similar to:

```
func testVolatileLockedBalance(ht *lntest.HarnessTest) {
	// Before we start the test, we'll ensure both sides are connected so
	// the funding flow can be properly executed.
	alice := ht.Alice
	bob := ht.Bob
	ht.EnsureConnected(alice, bob)

	// We first make sure Alice has no locked wallet balance.
	balance := alice.RPC.WalletBalance()
	require.Equal(ht, int64(0), balance.LockedBalance)

	// Next, we register a ChannelAcceptor on Bob. This way, we can get
	// Alice's wallet balance after coin selection is done and outpoints
	// are locked.
	stream, cancel := bob.RPC.ChannelAcceptor()
	defer cancel()

	// Then, we request creation of a channel from Alice to Bob. We don't
	// do it synchronously since we want to receive Bob's message in the
	// same goroutine.
	openChannelReq := &lnrpc.OpenChannelRequest{
		NodePubkey:         bob.PubKey[:],
		LocalFundingAmount: int64(funding.MaxBtcFundingAmount),
	}
	_ = alice.RPC.OpenChannel(openChannelReq)

	// After that, we receive the request on Bob's side, get the wallet
	// balance from Alice, and ensure it's non-zero.
	req, err := stream.Recv()
	require.NoError(ht, err)

	balance = alice.RPC.WalletBalance()
	require.NotEqual(ht, int64(0), balance.LockedBalance) // This fails because balance locked by LockOutpoint isn't counted

	// Next, we let Bob deny the request.
	resp := &lnrpc.ChannelAcceptResponse{
		Accept:        false,
		PendingChanId: req.PendingChanId,
	}
	err = stream.Send(resp)
	require.NoError(ht, err)

	// Finally, we check to make sure the balance is unlocked again.
	balance = alice.RPC.WalletBalance()
	require.Equal(ht, int64(0), balance.LockedBalance)
}
```

For our workaround, the `balance.LockedBalance` is replaced by `balance.VolatileLockedBalance` and the test is made to pass by populating that field with data from [`(*Wallet) LockedOutpoints()`](https://github.com/btcsuite/btcwallet/blob/1f3534b00d1440cd6c7f4b68e7dedeeed51d3d84/wallet/wallet.go#L3021).

### Expected behaviour

Test should pass, or there should be another way to access this information

### Actual behaviour

Test fails

### PR DESCRIPTION
**Pull request by aakselrod**
## Change Description
This fixes #8476.

## Steps to Test
The first commit, containing an integration test, is sufficient to test the change. The integration test fails when run prior to merging the subsequent commits which fix the issue, and passes after.

### Testing
- [x] Your PR passes all CI checks.
- [x] Tests covering the positive and negative (error paths) are included.
- [x] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [x] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

## Summary by CodeRabbit

- **New Features**
	- Introduced an enhanced output leasing mechanism for more efficient handling of channel funding processes.

- **Refactor**
	- Updated and unified the output locking mechanism across the system to use the new `OutputLeaser` interface.
	- Removed obsolete locking and unlocking functionalities from various components.

- **Tests**
	- Added new test cases to verify the behavior of locked balance during channel opening processes.

- **Chores**
	- Cleaned up unused import statements and outdated references to improve code maintainability and clarity.

### CODE REVIEW

File: itest/lnd_open_channel_test.go [hunk 1]
```diff
@@ -822,3 +822,53 @@ func testSimpleTaprootChannelActivation(ht *lntest.HarnessTest) {
...
+	}
+	_ = alice.RPC.OpenChannel(openChannelReq)
+
+	// After that, we receive the request on Bob's side, get the wallet
+	// balance from Alice, and ensure it's non-zero.
+	req, err := stream.Recv()
+	require.NoError(ht, err)
+
+	balance = alice.RPC.WalletBalance()
+	require.NotEqual(ht, int64(0), balance.LockedBalance)
```
Comment (aakselrod) [inline itest/lnd_open_channel_test.go:861]: This is where the itest fails before the fix. `LockedBalance` only counts outputs that are locked via `LeaseOutput`, leaving out ones that are locked via `LockOutpoint`. This results in 0 locked balance, though funds are reserved for opening the channel.

**Comment by aakselrod** [comment]
@coderabbitai review

File: sweep/walletsweep.go [hunk 2]
```diff
@@ -134,17 +137,18 @@ type CoinSelectionLocker interface {
...
 	// selection.
-	LockOutpoint(o wire.OutPoint)
+	LeaseOutput(i wtxmgr.LockID, o wire.OutPoint, d time.Duration) (
+		time.Time, []byte, btcutil.Amount, error)
 
-	// UnlockOutpoint unlocks a target outpoint, allowing it to be used for
+	// ReleaseOutput releases a target output, allowing it to be used for
 	// coin selection once again.
-	UnlockOutpoint(o wire.OutPoint)
+	ReleaseOutput(i wtxmgr.LockID, o wire.OutPoint) error
```
[the remark this answers is not in the document]
Comment (aakselrod) [reply sweep/walletsweep.go:151]: The interface is just a small subset of the `lnwallet.WalletController` interface. Maybe a (future?) refactor could move this interface to `chanfunding` or so, and then use the same interface from everywhere it's needed, but I'm not sure just adding more comments here specifically would be any more useful.

File: sweep/walletsweep.go [hunk 3]
```diff
@@ -179,11 +183,11 @@
...
-// outpointLocker as sources for wallet funds.
+// outputLeaser as sources for wallet funds.
 func CraftSweepAllTx(feeRate, maxFeeRate chainfee.SatPerKWeight,
 	blockHeight uint32, deliveryAddrs []DeliveryAddr,
 	changeAddr btcutil.Address, coinSelectLocker CoinSelectionLocker,
-	utxoSource UtxoSource, outpointLocker OutpointLocker,
+	utxoSource UtxoSource, outputLeaser OutputLeaser,
 	signer input.Signer, minConfs int32) (*WalletSweepPackage, error) {
 
 	// TODO(roasbeef): turn off ATPL as well when available?
```
[the remark this answers is not in the document]
Comment (aakselrod) [reply sweep/walletsweep.go:193]: Do we want to log errors here? Might be a good idea...

File: sweep/walletsweep.go [hunk 4]
```diff
@@ -219,7 +227,13 @@
...
 		// crafting out sweep all transaction.
 		for _, utxo := range utxos {
-			outpointLocker.LockOutpoint(utxo.OutPoint)
+			_, _, _, err = outputLeaser.LeaseOutput(
+				chanfunding.LndInternalLockID, utxo.OutPoint,
+				chanfunding.DefaultLockDuration,
+			)
+			if err != nil {
+				return err
+			}
```
[the remark this answers is not in the document]
Comment (aakselrod) [reply sweep/walletsweep.go:236]: I believe this error would be logged by an upstream caller when a lease fails.

**Review by aakselrod — COMMENTED** [review]
Responding to coderabbit comments.

On a higher level, we don't need `volatile_locked_balance` or `ListLockedOutpoints` as mentioned in #8476 since this PR eliminates volatile locks altogether.

File: itest/lnd_open_channel_test.go [hunk 5]
```diff
@@ -822,3 +822,53 @@ func testSimpleTaprootChannelActivation(ht *lntest.HarnessTest) {
...
+
+// testOpenChannelLockedBalance tests that when a funding reservation is
+// made for opening a channel, the balance of the required outputs shows
+// up as locked balance in the WalletBalance response.
+func testOpenChannelLockedBalance(ht *lntest.HarnessTest) {
+	// Before we start the test, we'll ensure both sides are connected so
+	// the funding flow can be properly executed.
+	alice := ht.Alice
+	bob := ht.Bob
+	ht.EnsureConnected(alice, bob)
```
Comment (guggero) [inline itest/lnd_open_channel_test.go:834]: nit: this should have already been asserted by the framework itself.

File: itest/lnd_open_channel_test.go [hunk 6]
```diff
@@ -822,3 +822,53 @@ func testSimpleTaprootChannelActivation(ht *lntest.HarnessTest) {
...
+
+	// We first make sure Alice has no locked wallet balance.
+	balance := alice.RPC.WalletBalance()
+	require.Equal(ht, int64(0), balance.LockedBalance)
```
Comment (guggero) [inline itest/lnd_open_channel_test.go:838]: nit: could use `require.EqualValues()` instead of explicit cast.

File: lnwallet/chanfunding/wallet_assembler.go [hunk 7]
```diff
@@ -488,7 +488,13 @@ func (w *WalletAssembler) ProvisionChannel(r *Request) (Intent, error) {
 		for _, coin := range selectedCoins {
 			outpoint := coin.OutPoint
 
-			w.cfg.CoinLocker.LockOutpoint(outpoint)
+			_, _, _, err = w.cfg.CoinLeaser.LeaseOutput(
+				LndInternalLockID, outpoint,
+				DefaultLockDuration,
```
Comment (guggero) [inline lnwallet/chanfunding/wallet_assembler.go:493]: I wonder: Since before this change the lock would basically exist forever (or until the next restart of the node), should we also use an "infinite" duration here? Or do we kind of rely on the general funding timeout we have in `lnd` that is 10 minutes?

**Review by guggero — COMMENTED** [review]
Very nice cleanup/consolidation of behavior! Code looks good to me, main question is around what timeout to use.

File: lnwallet/chanfunding/wallet_assembler.go (hunk 7 above)
Comment (aakselrod) [reply lnwallet/chanfunding/wallet_assembler.go:493]: I think we have an interplay of several factors:

- the `chanfunding.DefaultLockDuration` (formerly `walletrpc.DefaultLockDuration`) is 10m
- the `lncfg.DefaultReservationTimeout` is 10m
- only the dev config allows changing the reservation timeout from 10m, which is used in itests
- the reservation timeout applies to time since last update to the reservation, rather than time since the reservation was created - this means it can go longer than 10m if the peer is slow enough to respond
- the zombie sweeper iterates through `activeReservations` which I believe is NOT populated on startup from any non-volatile data, so it would miss releasing outputs with infinite expiration and would cause them to need to be released manually in the case that LND restarts with an active reservation

This makes me think that maybe the duration should be the reservation timeout multiplied by a constant factor for the number of state transitions we expect, to allow the peer to idle up to the timeout at each step. Since the timeout is configurable in the dev environment, perhaps we pass that value to lnwallet when initializing it as well?

Comment (guggero) [reply lnwallet/chanfunding/wallet_assembler.go:493]: Ah, right, we have the zombie sweeper that does the cleanup. Maybe we could add a `Cleanup()` method to the reservation that would be called by the zombie sweeper to release the locks immediately? That combined with a multiplication factor of the reservation timeout sounds good to me.

Comment (aakselrod) [reply lnwallet/chanfunding/wallet_assembler.go:493]: - The zombie sweeper calls `failFundingFlow()` on the manager with the channel ID here: https://github.com/lightningnetwork/lnd/blob/72764b14734870d03a1212795e2ec7c02f3b4500/funding/manager.go#L4848
- which calls `cancelReservationCtx()` on the manager with the channel ID here: https://github.com/lightningnetwork/lnd/blob/72764b14734870d03a1212795e2ec7c02f3b4500/funding/manager.go#L912
- which calls `Cancel()` on the `ChannelReservation` here: https://github.com/lightningnetwork/lnd/blob/72764b14734870d03a1212795e2ec7c02f3b4500/funding/manager.go#L4885
- which sends a `fundingReserveCancelMsg` to the wallet's `msgChan` with the reservation ID here: https://github.com/lightningnetwork/lnd/blob/72764b14734870d03a1212795e2ec7c02f3b4500/lnwallet/reservation.go#L795
- which calls `handleFundingCancelRequest()` on the wallet with the message here: https://github.com/lightningnetwork/lnd/blob/72764b14734870d03a1212795e2ec7c02f3b4500/lnwallet/wallet.go#L620
- which calls `UnlockOutpoint()` here: https://github.com/lightningnetwork/lnd/blob/72764b14734870d03a1212795e2ec7c02f3b4500/lnwallet/wallet.go#L1428
- which is replaced in this PR already with a `ReleaseOutput()`

So I think the `Cleanup()` part of this might be redundant, as the zombie sweeper already calls cleanup code that this PR modifies to work with leases instead of locks. I think all I need to do is update this timeout.

Comment (guggero) [reply lnwallet/chanfunding/wallet_assembler.go:493]: Okay cool. Sounds good to me, thanks for confirming!

Comment (aakselrod) [reply lnwallet/chanfunding/wallet_assembler.go:493]: Thanks! I got most of the way there today, will finish it up tomorrow.

Comment (aakselrod) [reply lnwallet/chanfunding/wallet_assembler.go:493]: Looking more closely at the multiplier to use:

- Channel establishment v1 should have a multiplier of 1 (the time between `funding_created` and `funding_signed` messages)
- Channel establishment v2 specifically recommends not locking UTXOs and reusing them between channel open attempts for dual-funded channels, to help [prevent liquidity griefing](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#liquidity-griefing). In addition, since there's a loop that's iterated for each input added (from each side), the multiplier isn't constant.
 
For itests, the reservation timeout is shorter, so using the longer value of the default timeout is safe. I think it's safe to just use `lncfg.DefaultReservationTimeout` in this case.

File: sweep/walletsweep.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (aakselrod) [reply sweep/walletsweep.go:193]: Added error logging.

File: itest/lnd_open_channel_test.go [hunk 8]
```diff
@@ -822,3 +822,53 @@ func testSimpleTaprootChannelActivation(ht *lntest.HarnessTest) {
...
+		Accept:        false,
+		PendingChanId: req.PendingChanId,
+	}
+	err = stream.Send(resp)
+	require.NoError(ht, err)
+
+	// Finally, we check to make sure the balance is unlocked again.
+	balance = alice.RPC.WalletBalance()
+	require.Equal(ht, int64(0), balance.LockedBalance)
+}
```
[the remark this answers is not in the document]
Comment (aakselrod) [reply itest/lnd_open_channel_test.go]: Completed TODO.

File: itest/lnd_open_channel_test.go (hunk 5 above)
Comment (aakselrod) [reply itest/lnd_open_channel_test.go]: Removed this line.

File: itest/lnd_open_channel_test.go (hunk 6 above)
Comment (aakselrod) [reply itest/lnd_open_channel_test.go]: Used `EqualValues` and `NotEqualValues` instead of casts, and checked that the itest fails correctly before the changes, and passes after the changes.

File: lnwallet/chanfunding/wallet_assembler.go (hunk 7 above)
Comment (aakselrod) [reply lnwallet/chanfunding/wallet_assembler.go:529]: Moved `lncfg.DefaultReservationTimeout` to `lnwallet/chanfunding` to avoid import cycles, updated all references to it, and used it explicitly instead of `DefaultLockDuration` for channel reservations.

**Comment by aakselrod** [comment]
Pushed an update:
- Updated release notes
- Fixed nits and comments in itest
- Added error logging (as warnings) to output release loops in `lnwallet/chanfunding` and `sweep` packages
- Moved `DefaultReservationTimeout` to `lnwallet/chanfunding` and used it explicitly in wallet assembler

File: lnwallet/chanfunding/wallet_assembler.go (hunk 7 above)
Comment (aakselrod) [reply lnwallet/chanfunding/wallet_assembler.go]: Ah, forgot to actually use `DefaultReservationTimeout` instead of `DefaultLockDuration`. Fixed.

File: lnwallet/chanfunding/wallet_assembler.go [hunk 9]
```diff
@@ -219,7 +219,13 @@ func (f *FullIntent) Outputs() []*wire.TxOut {
 // NOTE: Part of the chanfunding.Intent interface.
 func (f *FullIntent) Cancel() {
 	for _, coin := range f.InputCoins {
-		f.coinLocker.UnlockOutpoint(coin.OutPoint)
+		err := f.coinLeaser.ReleaseOutput(
+			LndInternalLockID, coin.OutPoint,
+		)
+		if err != nil {
+			log.Warnf("Failed to release UTXO %s (%s))",
```
Comment (guggero) [inline lnwallet/chanfunding/wallet_assembler.go:226]: nit: use `%v` for errors?

**Review by guggero — APPROVED** [review]
Very nice, LGTM :tada:

File: lnwallet/chanfunding/wallet_assembler.go (hunk 9 above)
Comment (aakselrod) [reply lnwallet/chanfunding/wallet_assembler.go]: Done! :heavy_check_mark:

**Comment by aakselrod** [comment]
> @yyforyongyu: review reminder @ziggie1984: review reminder @aakselrod, remember to re-request review from reviewers when ready

Just need one more approval! :pray:

**Review by yyforyongyu — COMMENTED** [review]
Looking good! Just a few comments on the itest then this should be good to go!

File: itest/lnd_open_channel_test.go [hunk 10]
```diff
@@ -822,3 +822,52 @@ func testSimpleTaprootChannelActivation(ht *lntest.HarnessTest) {
 	// Our test is done and Alice closes her channel to Bob.
 	ht.CloseChannel(alice, chanPoint)
 }
+
+// testOpenChannelLockedBalance tests that when a funding reservation is
+// made for opening a channel, the balance of the required outputs shows
+// up as locked balance in the WalletBalance response.
+func testOpenChannelLockedBalance(ht *lntest.HarnessTest) {
+	// Before we start the test, we'll ensure both sides are connected so
```
[the remark this answers is not in the document]
Comment (aakselrod) [reply itest/lnd_open_channel_test.go]: Thanks for the catch! I removed this comment, and rearranged the vars a little bit to support the `wait.NoError` change below.

File: itest/lnd_open_channel_test.go [hunk 11]
```diff
@@ -822,3 +822,52 @@ func testSimpleTaprootChannelActivation(ht *lntest.HarnessTest) {
...
+	// same goroutine.
+	openChannelReq := &lnrpc.OpenChannelRequest{
+		NodePubkey:         bob.PubKey[:],
+		LocalFundingAmount: int64(funding.MaxBtcFundingAmount),
+	}
+	_ = alice.RPC.OpenChannel(openChannelReq)
+
+	// After that, we receive the request on Bob's side, get the wallet
+	// balance from Alice, and ensure the locked balance is non-zero.
+	req, err := stream.Recv()
```
[the remark this answers is not in the document]
Comment (aakselrod) [reply itest/lnd_open_channel_test.go]: Done on both!

**Comment by yyforyongyu** [comment]
This should be good to do, but I'm having trouble understanding why this itest failed,
```
harness_rpc.go:97: 
        	Error Trace:	/home/runner/work/lnd/lnd/lntest/rpc/harness_rpc.go:97
        	            				/home/runner/work/lnd/lnd/lntest/rpc/lnd.go:374
        	            				/home/runner/work/lnd/lnd/itest/lnd_psbt_test.go:1538
        	            				/home/runner/work/lnd/lnd/itest/lnd_psbt_test.go:1019
        	            				/home/runner/work/lnd/lnd/itest/lnd_psbt_test.go:661
        	            				/home/runner/work/lnd/lnd/lntest/harness.go:353
        	            				/home/runner/work/lnd/lnd/itest/lnd_test.go:139
        	Error:      	Received unexpected error:
        	            	rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	Messages:   	Alice: failed to call SendCoins
```

It seems that postgres was really slow, just wanna be sure it wasn't introduced by this PR.

**Comment by aakselrod** [comment]
It looks like it might actually have to do with this PR. The `send_all` option used to use in-memory locks, but now uses leases, which is definitely slower. I wonder if moving the failing test will help until #8529 goes in? I'll try it in a new commit and see what happens.

**Comment by aakselrod** [comment]
That seems to be worse. Going to force-push to remove that commit.

**Comment by aakselrod** [comment]
I'm going to explore more locally and see if I can reproduce/debug the issue in this test.

**Comment by aakselrod** [comment]
Those itests seem to pass locally for me. Curiouser and curiouser...

**Comment by guggero** [comment]
Maybe it's a matter of available resources on the GitHub runner? It seems to me like they are being scaled down somewhat, at least it seems the available disk space is less than before. So maybe CPU is also being throttled?
We could try increasing the DB specific timeout here: https://github.com/lightningnetwork/lnd/blob/d5af76cb2973b92ead1f602baba2f71e8e939cc3/lntest/wait/timeouts_remote_db.go#L23

**Comment by aakselrod** [comment]
Ah, yeah, thus the cross compile check running out of space. I'll increase the timeout and see how the tests do!

**Comment by aakselrod** [comment]
I think the [`unit-race` failures](https://github.com/lightningnetwork/lnd/actions/runs/8300573490/job/22718808474?pr=8496) are unrelated to this PR.

**Comment by aakselrod** [comment]
Looks like the postgres itests passed with a longer timeout.

**Review by yyforyongyu — APPROVED** [review]
LGTM🎉
