### PR TITLE
lnd: use change output index from authoring TX to check reserved value

### LINKED ISSUE #5648: With an anchor-channel open having only a single UTXO cannot be selected for `SendCoins`/`SendMany`
### Background

When using anchor-channels a minimum reserved wallet balance is required (10_000 sats/channel; maximum 100_000 sats).

When the node has some anchor-channel open and only a single UTXO in the wallet, then calling `SendCoins` or `SendMany` to send some on-chain funds out is impossible as it returns the error `reserved wallet balance invalidated`, even though we send out an amount that would leave sufficient funds on the node.

However, it is still possible to call `OpenChannel` to open a channel as long as we fund it with an amount that leaves enough on-chain funds for the reserved wallet balance.

As a work-around it is possible to request a new address on the node and then use `SendCoins` or `SendMany` to actively send an amount equal to (or greater than) the required reserved wallet balance to your own address. This splits the UTXO and makes it possible to now send funds out again. 

It therefore seems that the problem is that the check for reserved wallet balance is done without knowledge of a change output using `SendCoins`/`SendMany`, while this is known when opening a new channel with `OpenChannel`?

### Your environment

* version of `lnd`: 0.13.0/0.13.1
* which operating system (`uname -a` on *Nix): linux

### Steps to reproduce

 1. Create a new node. 
 2. Generate a new address and send funds to this address. 
 3. From the node open an anchor-channel to some remote. Now all of the on-chain funds are in a single UTXO, which are un-spendable using `SendCoins`/`SendMany` when trying to send to an external address (even though the transaction would leave sufficient funds for the wallet reserve on the node).
 4. It is still possible to open channels and to split the UTXO when actively sending funds to your own address requested via `newaddress`.

### Expected behaviour

It should be possible to detect that the change output of a transaction from `SendCoins`/`SendMany` would leave sufficient wallet reserve funds.

### Actual behaviour

The error `reserved wallet balance invalidated` is returned.

### PR DESCRIPTION
**Pull request by bjarnemagnussen**
### Description

Currently a whole UTXO is reserved when anchor-channels is used. This means that if the node has a single UTXO, it cannot be spend even if a change output would leave sufficient funds for the reserve in the wallet.

This PR makes use of the returned `txauthor.AuthoredTx` struct that contains a field for an eventual change index. The reason that this is not automatically detected by the `CheckReservedValueTx` function is because the authored transaction is created in dry-run, meaning it does not add the used change output to the wallet to watch for.

This PR hence assumes that the change index from the authored transaction returned by `WalletController.CreateSimpleTx` will indeed be a change output controlled by the wallet. 

Fixes #5648

### CODE REVIEW

File: lnwallet/wallet.go [hunk 1]
```diff
@@ -1033,20 +1047,53 @@ func (l *LightningWallet) CheckReservedValue(in []wire.OutPoint,
...
 	}
 
 	var inputs []wire.OutPoint
-	for _, txIn := range tx.TxIn {
+	for _, txIn := range req.Tx.TxIn {
 		inputs = append(inputs, txIn.PreviousOutPoint)
 	}
 
-	return l.CheckReservedValue(inputs, tx.TxOut, numAnchors)
+	reservedVal, err := l.CheckReservedValue(inputs, req.Tx.TxOut,
```
Comment (Roasbeef) [inline lnwallet/wallet.go:1063]: Line wrapping should be more like:
```go
reservedVal, err := l.CheckReservedValue(
    inputs, req.Tx.TxOut, numAnchors, 
)
```

File: lnwallet/wallet.go [hunk 2]
```diff
@@ -1033,20 +1047,53 @@ func (l *LightningWallet) CheckReservedValue(in []wire.OutPoint,
...
+		chIdx := *req.ChangeIndex
+		if chIdx < 0 || chIdx >= len(req.Tx.TxOut) ||
+			req.Tx.TxOut[chIdx].Value < int64(reservedVal) {
+
+			return reservedVal, err
+		}
+
+	case err != nil:
+		return reservedVal, err
+
```
Comment (Roasbeef) [inline lnwallet/wallet.go:1093]: Extra new line

**Review by Roasbeef — APPROVED** [review]
LGTM 🍉

Only some small code style nits

**Comment by Roasbeef** [comment]
Also needs a release notes update

**Comment by bjarnemagnussen** [comment]
Thanks @Roasbeef, I have addressed your last issues!

**Comment by Roasbeef** [comment]
Needs a rebase then this should be g2g, thanks for working on this!

**Comment by bjarnemagnussen** [comment]
Rebased

**Review by guggero — APPROVED** [review]
Nice fix, LGTM :100:
