### PR TITLE
itest: neutrino anchor output flake fix

### LINKED ISSUE #5015: flake: neutrino mempool publication
Travis flake, seems to occur mostly with the neutrino backend but I've seen related flakes on other builds. IIRC it may have some relation to double spending anchor outputs, but i'm not positive.
```
   test_harness.go:91: Error outside of test: *errors.errorString failed to find commitment in miner mempool: wanted 2, found 1 txs in mempool: [c4994314ecea4241f4137e268e6105234be21a171503a62956015f709f01ef1f]
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:3745 (0xe8394a)
        	channelForceClosureTest: t.Fatalf("failed to find commitment in miner mempool: %v", err)
        /home/travis/gopath/src/github.com/lightningnetwork/lnd/lntest/itest/lnd_test.go:3522 (0xedb626)
        	testChannelForceClosure.func1: channelForceClosureTest(
        /home/travis/.gimme/versions/go1.15.7.linux.amd64/src/testing/testing.go:1123 (0x51c2ef)
        	tRunner: fn(t)
        /home/travis/.gimme/versions/go1.15.7.linux.amd64/src/runtime/asm_amd64.s:1374 (0x46f821)
        	goexit: BYTE	$0x90	// NOP
```

### LINKED ISSUE #5492: itest-flake: pprof scrape during shutdown triggers test failure
A transient flake that pops up at times: 
```
Error: failed to get profile page (node_id=33, name=Carol): Get "http://localhost:5694/debug/pprof/goroutine?debug=1": dial tcp 127.0.0.1:5694: connect: connection refused
    test_harness.go:88: Failed: (onchain fund recovery): exited with error: 
        *errors.errorString unable to shutdown Carol: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:5692: connect: connection refused"
```

Test appears to flake simply because we fail to fetch the goroutine dump from the `pprof` server. We should either block to make sure we can grab the profile, or not let it impeded the running of the tests assuming the test passes.

### PR DESCRIPTION
**Pull request by guggero**
Fixes #5015.
Fixes #5492 (though indirectly, that never caused the tests to fail in the first place).

Fixes two of our most elusive neutrino itest flakes, both in context of anchor output channels.

I'm not 100% sure I can explain properly _why_ this seems to only happen with Neutrino, but this is what I got so far:
 - for anchor outputs, we always try to sweep our anchor of our local commit TX and our anchor in the remote commit TX (since we possibly don't know who force closed)
 - so if we force close from our end, we always create 1 valid sweep TX (our anchor in the local commitment) and an orphaned one (our anchor in the remote commitment)
- normally the first sweep succeeds and the second sweep fails because we don't have a spare UTXO to anchor it down. so we never actually publish the orphaned TX
 - sometimes (hence the flake), the orphaned sweep (remote commitment anchor) is published first and the UTXO is marked as used (even if it's in an orphaned TX) and then the actual "good" sweep TX can't go through because we don't have a spare UTXO

The easy solution to fix the flakes in the itest is to just add another UTXO. That actually makes all those anchor tests quite stable. But I'm pretty sure this just gets rid of the symptoms of a possible underlying problem.

### CODE REVIEW

File: lntest/harness.go [hunk 1]
```diff
@@ -835,15 +835,16 @@ func (n *NetworkHarness) StopNode(node *HarnessNode) error {
...
+func (n *NetworkHarness) SaveProfilesPages(t *testing.T) {
 	// Only write gorutine dumps if flag is active.
 	if !(*goroutineDump) {
 		return
 	}
 
 	for _, node := range n.activeNodes {
 		if err := saveProfilesPage(node); err != nil {
-			fmt.Printf("Error: %v\n", err)
+			t.Logf("Logging follow-up error only, see rest of "+
```
Comment (Roasbeef) [inline lntest/harness.go:852]: Ah interesting, so the test was actually failing due to some other reason, but this is the error that bubbled up?

File: lntest/harness.go [hunk 2]
```diff
@@ -772,7 +772,13 @@ func (n *NetworkHarness) RestartNode(node *HarnessNode, callback func() error,
...
 	}
 
-	return node.Unlock(context.Background(), unlockReq)
+	if err := node.Unlock(context.Background(), unlockReq); err != nil {
+		return err
+	}
+
+	ctxc, done := context.WithTimeout(context.Background(), DefaultTimeout)
+	defer done()
+	return node.WaitForBlockchainSync(ctxc)
```
Comment (Roasbeef) [inline lntest/harness.go:781]: Ah and this'll ensure that it detects w/e UTXOs were sent to it while it was offline in time?

File: lntest/itest/lnd_test.go [hunk 3]
```diff
@@ -3176,6 +3176,9 @@ func channelForceClosureTest(net *lntest.NetworkHarness, t *harnessTest,
 	ctxt, _ := context.WithTimeout(ctxb, defaultTimeout)
 	net.ConnectNodes(ctxt, t.t, alice, carol)
 
+	// We need one additional UTXO for sweeping the remote anchor.
+	net.SendCoins(ctxt, t.t, btcutil.SatoshiPerBitcoin, alice)
```
Comment (Roasbeef) [inline lntest/itest/lnd_test.go:3180]: Ah yeah, this is something we considered as a short term fix. I think it works for now, but we'll need to gague to see if in practice the current logic w.r.t the sweeper and anchor outputs exclusive groups is problematic or not. I think @wpaulino has a more fundamental solution, but this should give us a bit more breathing room.

File: lntest/itest/lnd_test.go [hunk 4]
```diff
@@ -11002,90 +10986,81 @@ func testAbandonChannel(net *lntest.NetworkHarness, t *harnessTest) {
...
 	// Ensure that the channel can no longer be found in the channel graph.
-	_, err = net.Alice.GetChanInfo(ctxb, &lnrpc.ChanInfoRequest{
-		ChanId: chanID,
-	})
-	if !strings.Contains(err.Error(), "marked as zombie") {
-		t.Fatalf("channel shouldn't be found in the channel " +
-			"graph!")
-	}
+	err = wait.NoError(func() error {
+		_, err := net.Alice.GetChanInfo(ctxb, &lnrpc.ChanInfoRequest{
```
Comment (Roasbeef) [inline lntest/itest/lnd_test.go:11025]: 👍

**Review by Roasbeef — COMMENTED** [review]
In practice, this might also end up eliminating additional flakes, which is promising

File: lntest/itest/lnd_test.go [hunk 5]
```diff
@@ -10951,49 +10948,36 @@ func testAbandonChannel(net *lntest.NetworkHarness, t *harnessTest) {
 		ctxt, t, net, net.Alice, net.Bob, channelParam,
 	)
 	txid, err := lnrpc.GetChanPointFundingTxid(chanPoint)
-	if err != nil {
-		t.Fatalf("unable to get txid: %v", err)
-	}
+	require.NoError(t.t, err, "alice bob get channel funding txid")
```
Comment (yyforyongyu) [inline lntest/itest/lnd_test.go:10950]: 👍

File: lntest/itest/lnd_channel_backup_test.go [hunk 6]
```diff
@@ -847,6 +847,12 @@ func testChanRestoreScenario(t *harnessTest, net *lntest.NetworkHarness,
 	ctxt, _ := context.WithTimeout(ctxb, defaultTimeout)
 	net.SendCoins(ctxt, t.t, btcutil.SatoshiPerBitcoin, carol)
 
+	// For the anchor output case we need two UTXOs for Carol so she can
+	// sweep both the local and remote anchor.
```
Comment (yyforyongyu) [inline lntest/itest/lnd_channel_backup_test.go:851]: 👍

**Comment by yyforyongyu** [comment]
> sometimes (hence the flake), the orphaned sweep (remote commitment anchor) is published first and the UTXO is marked as used (even if it's in an orphaned TX) and then the actual "good" sweep TX can't go through because we don't have a spare UTXO

This is very interesting. Did you get it from observation (the logs?) or from inference? If that's the case then I think we should (not in this PR, just a thought) give each node enough number of UTXO to start with, and add a following test to check that the above case and assert our expectations.

**Review by yyforyongyu — COMMENTED** [review]
And it needs a rebase, sorry bro...

File: lntest/harness.go (hunk 1 above)
Comment (guggero) [reply lntest/harness.go:852]: I think this was just logged first, followed by the actual cause. So we tended to overlook why the node wasn't shutting down properly in the first place.
Wee never actually called `t.Fatalf()` here, so the test couldn't fail because of an error in this loop. We just logged it in the first place. Using the test logger and adding more context will hopefully make us look at the actual cause the next time this happens.

File: lntest/harness.go (hunk 2 above)
Comment (guggero) [reply lntest/harness.go:781]: Yeah, and hopefully make the Neutrino tests a bit more stable in general by giving it time to fully sync to the chain after a restart.

**Comment by guggero** [comment]
> Did you get it from observation (the logs?) or from inference?

I studied the logs for a (way too long) time to find this. It only seems to happen in the case where the sweeper publishes a sweep TX for the remote anchor first. The UTXO is then used/locked up even if the commitment TX confirms and it is now clear which anchor would be the correct one. Apparently Neutrino can't detect that the orphaned TX will never confirm and keeps seeing the UTXO as being locked/used. Just giving the node a second UTXO solves this for the itest at least.

> And it needs a rebase, sorry bro...

No problem! I'm very happy your itest split PR got in first, that huge `lnd_test.go` file was always a bit painful to handle.

File: lntest/itest/assertions.go [hunk 7]
```diff
@@ -1362,7 +1361,7 @@ func assertDLPExecuted(net *lntest.NetworkHarness, t *harnessTest,
 			return fmt.Errorf("unable to get carol's balance: %v", err)
 		}
 
-		carolBalance := carolBalResp.ConfirmedBalance
+		carolBalance := carolBalResp.TotalBalance
```
Comment (yyforyongyu) [inline lntest/itest/assertions.go:1364]: why the change from confirmed to total?

**Review by yyforyongyu — APPROVED** [review]
LGTM👍

File: lntest/itest/log_error_whitelist.txt [hunk 8]
```diff
@@ -18,7 +18,9 @@
 <time> [ERR] CNCT: ChannelArbitrator(<chan_point>): unable to advance state: channel not found
 <time> [ERR] CNCT: ChannelArbitrator(<chan_point>): unable to broadcast close tx: Transaction rejected: output already spent
 <time> [ERR] CNCT: ChannelArbitrator(<chan_point>): unable to force close: channel not found
+<time> [ERR] CNCT: ChannelArbitrator(<chan_point>): unable to mark commitment broadcasted: channel not found
```
[the remark this answers is not in the document]
Comment (guggero) [reply lntest/itest/log_error_whitelist.txt:21]: Yeah, I've asked myself the same thing many times. I think the idea was to eventually look at all the errors and find out if they really should be errors and whether they should be logged in the first place. But it's just making our lives harder as is. Maybe we should start a vote to remove the check for now?

File: lntest/itest/assertions.go (hunk 7 above)
Comment (guggero) [reply lntest/itest/assertions.go:1364]: This is for Neutrino only. There the sweep TX for the (non-existent) remote anchor doesn't get rejected by the backend so the wallet still sees it as being an unconfirmed balance. Maybe I should make it more explicit and add a comment here.

File: lntest/itest/lnd_channel_backup_test.go [hunk 9]
```diff
@@ -847,6 +847,12 @@ func testChanRestoreScenario(t *harnessTest, net *lntest.NetworkHarness,
...
+	if testCase.anchorCommit {
+		net.SendCoins(ctxt, t.t, btcutil.SatoshiPerBitcoin, carol)
```
Comment (carlaKC) [inline lntest/itest/lnd_channel_backup_test.go:853]: Do we need to wait for these to arrive? Or are they confirmed later in the test

**Review by carlaKC — APPROVED** [review]

File: lntest/itest/lnd_channel_backup_test.go (hunk 9 above)
Comment (guggero) [reply lntest/itest/lnd_channel_backup_test.go:853]: `SendCoins` actually mines 6 blocks to confirm them, so no extra wait is necessary.
