### PR TITLE
multi: skip InitRemoteMusigNonces if we've already called it

### LINKED ISSUE #8065: [bug]: Simple taproot channel inactive after 6 confs
### Background

Simple taproot channels stay inactive if the initiator disconnects after the channel opening and reconnects after the channel has reached 6 confirmations. The following error appears in the logs upon reconnection:
```
2023-10-05 11:42:53.684 [WRN] PEER: Peer(03a01da97af71f7859cd1b2b6a70f221ecd49f6eabf0bf1e267bae9570b47232a6): Unable to find our forwarding policy for channel redacted:0, using default values
2023-10-05 11:47:16.999 [WRN] PEER: Peer(03a01da97af71f7859cd1b2b6a70f221ecd49f6eabf0bf1e267bae9570b47232a6): Unable to find our forwarding policy for channel redacted:0, using default values
2023-10-05 15:54:01.694 [WRN] CHBU: Replacing disk backup for ChannelPoint(redacted:0) w/ newer version
2023-10-05 15:54:01.906 [WRN] HSWC: ChannelLink(redacted:0): error when syncing channel states: unable to init remote nonce: pending verification nonce is not set 
2023-10-05 15:54:01.906 [ERR] HSWC: ChannelLink(redacted:0): failing link: unable to synchronize channel states: unable to init remote nonce: pending verification nonce is not set with error: unable to resume channel, recovery required
```

After a `lnd` restart however, the channel turns active.

### Your environment

`v0.17.0-beta`

### Steps to reproduce

This `itest` reproduces the issue: https://github.com/lightningnetwork/lnd/pull/8070

In short:

1. Alice opens a simple taproot chan to Bob
2. Then she disconnects from Bob
3. The channel is confirmed on-chain(6 confs)
4. Alice reconnects but channel stays inactive. 
5. Only after alice restarts does the channel turn active

### Expected behaviour

After Alice reconnects the channel negotiation should continue to activate the channel.

### Actual behaviour

Instead the channel stays inactive.

### PR DESCRIPTION
**Pull request by Roasbeef**
Prior to this commit, taproot channels had a bug:

- If a disconnect happened before `peer.AddNewChannel` was called, then the subsequent reconnect would call `peer.AddNewChannel` and attempt the ChannelReestablish dance.

- `peer.AddNewChannel` would call `NewLightningChannel` with populated nonce ChannelOpts. This in turn would call `InitRemoteMusigNonces` which would create a new musig pair session and set the channel's `pendingVerificationNonce` to nil.

- During the reestablish dance, `ProcessChanSyncMsg` would be called. This would also call `InitRemoteMusigNonces`, except it would fail since `pendingVerificationNonce` was set to nil in the previous invocation.

To fix this, a new function `SkipNonceInit` is exposed on `LightningChannel` that will skip the next call to `InitRemoteMusigNonces` in `ProcessChanSyncMsg`.

Fixes #8065 

Addresses review comments from  https://github.com/lightningnetwork/lnd/pull/8078

### CODE REVIEW

**Review by morehouse — COMMENTED** [review]
Code looks good.  One of the itests is failing; seems potentially related to this change.

File: lnwallet/channel.go [hunk 1]
```diff
@@ -1367,10 +1378,15 @@ func WithRemoteMusigNonces(nonces *musig2.Nonces) ChannelOpt {
 	}
 }
 
-// channelOpts is the set of options used to create a new channel.
-type channelOpts struct {
-	localNonce  *musig2.Nonces
-	remoteNonce *musig2.Nonces
+// WithSkipNonceInit is used to modify the way nonces are handled during
+// channel initialization for taproot channels. If this option is specified,
+// then when we receive the chan reest message from the remote party, we won't
```
Comment (arno01) [inline lnwallet/channel.go:1383]: typo? `s/reest/reset/`

File: itest/lnd_open_channel_test.go [hunk 2]
```diff
@@ -768,3 +768,55 @@ func testFundingExpiryBlocksOnPending(ht *lntest.HarnessTest) {
...
+		OutputIndex: pendingChan.OutputIndex,
+	}
+
+	// We disconnect and reconnect Alice and Bob before the channel is
+	// confirmed. Our expectation is that the channel is active once the
+	// channel is confirmed.
+	ht.DisconnectNodes(alice, bob)
+	ht.EnsureConnected(alice, bob)
+
+	// Mine six blocks to confirm the channel funding transaction.
```
Comment (yyforyongyu) [inline itest/lnd_open_channel_test.go:814]:
```suggestion
	// Mine one block to confirm the channel funding transaction.
```

File: itest/lnd_open_channel_test.go [hunk 3]
```diff
@@ -768,3 +768,55 @@ func testFundingExpiryBlocksOnPending(ht *lntest.HarnessTest) {
...
+	ht.MineBlocks(6)
```
Comment (yyforyongyu) [inline itest/lnd_open_channel_test.go:815]:
```suggestion
	ht.MineBlocksAndAssertNumTxes(1, 1)
```

File: lnwallet/channel.go [hunk 4]
```diff
@@ -1344,13 +1344,24 @@ type LightningChannel struct {
 	// fundingOutput is the funding output (script+value).
 	fundingOutput wire.TxOut
 
+	// opts is the set of options that channel was initialized with.
+	opts *channelOpts
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply lnwallet/channel.go:1348]: yeah think they are not used here and can be removed.

**Review by yyforyongyu — COMMENTED** [review]
Thanks for picking this up! I think we need to make an update to the itest assertion to fix the failing tests.

File: lnwallet/channel.go (hunk 1 above)
Comment (alexbosworth) [inline lnwallet/channel.go:1383]:
```suggestion
// then when we receive the chan reset message from the remote party, we won't
```

File: lnwallet/channel.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply lnwallet/channel.go:1348]: I prefer to keep it, this way the set of options just grows here rather than vertically within the struct def space.

**Comment by Roasbeef** [comment]
> Thanks for picking this up! I think we need to make an update to the itest assertion to fix the failing tests.

Looks like a different test is actually failing, but only on some of the build targets: 
```
=== RUN   TestLightningNetworkDaemon/tranche00/03-of-136/bitcoind/multi_hop_receiver_chain_claim/zeroconf=false/committype=SIMPLE_TAPROOT
    harness_assertion.go:400: 
            Error Trace:    /home/runner/work/lnd/lnd/lntest/harness_assertion.go:400
                                        /home/runner/work/lnd/lnd/lntest/harness_assertion.go:363
                                        /home/runner/work/lnd/lnd/itest/lnd_open_channel_test.go:818
                                        /home/runner/work/lnd/lnd/lntest/harness.go:286
                                        /home/runner/work/lnd/lnd/itest/lnd_test.go:136
            Error:          Received unexpected error:
                            channel not found using funding_txid_bytes:"\xf9\xae\xa2L[\xc7\xfc|\x15-\x9e\x99\xa8\x9b\xcdͰf\xb4\xd6J\xed\x9cM\x14?\x97\xe86\xda\\w"
```

**Review by Crypt-iQ — COMMENTED** [review]
Like yy pointed out offline, I think the failing itest is a timing issue

**Comment by Roasbeef** [comment]
Pushed up a new version where I modified the test to use fresh nodes. The old test used the existing harness nodes, and also used fund max so it would rob them of all their coins, which could mess up future tests.

**Review by yyforyongyu — APPROVED** [review]
LGTM⛵️

**Comment by Roasbeef** [comment]
Nice, looks like that fixed it!
