### PR TITLE
server: fix inbound/outbound peer connection logic

### LINKED ISSUE #997: inbound boolean still reversed
seems we again mistook the variable inbound for actually meaning inbound 
we really should fix this before we make more mistakes
either rename it to "outbound" or correct the logic as i originally suggested

https://github.com/lightningnetwork/lnd/pull/628
https://github.com/lightningnetwork/lnd/pull/627

this is *not* just cosmetics. we currently add outbound peers to inboundPeers and the other way around. 
fix the root cause. it is far easier to just switch true with false in two different places in the code than trying to have every coder remember that inbound means outbound and tidying up the bugs afterwards

```
        if p.inbound {
                // added debugtext to see easier prove my point
                srvrLog.Infof("hello i am inbound %v",p) 
                s.inboundPeers[pubStr] = p
        } else {
                // added debugtext to see easier prove my point
                srvrLog.Infof("hello i am outbound %v",p)
                s.outboundPeers[pubStr] = p
        }
```

```
2018-04-01 15:14:10.479 [INF] SRVR: Established connection to: 18.195.105.234:9735
2018-04-01 15:14:10.583 [INF] SRVR: hello i am inbound 18.195.105.234:9735
...
2018-04-01 15:11:41.823 [INF] SRVR: New inbound connection from 99.43.41.3:40302
2018-04-01 15:11:41.824 [INF] SRVR: hello i am outbound 99.43.41.3:9735
```

### PR DESCRIPTION
**Pull request by wpaulino**
This PR attempts to fix a small bug where inbound peers were being tracked as outbound and outbound as inbound.

I went through the rest of the connection logic and our uses of inbound/outbound connections seem to be consistent with their respective meanings. Inbound connections should be connections initiated by the remote peer, while outbound connections should be initiated locally.

I believe the small patch below should be enough to remedy this issue, although I might have missed something.

Fixes #997.

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -1368,7 +1369,7 @@ func (s *server) peerConnected(conn net.Conn, connReq *connmgr.ConnReq,
 
 	// We'll ensure that we locate the proper port to use within the peer's
 	// address for reconnecting purposes.
-	if tcpAddr, ok := addr.(*net.TCPAddr); ok && !inbound {
+	if tcpAddr, ok := addr.(*net.TCPAddr); ok && inbound {
```
Comment (wpaulino) [inline server.go]: Rebased this to include a recent change that depends on the flipped behavior.

**Comment by cfromknecht** [comment]
Aight, been seeing some errors that may be attributed to this issue, time to revive. Gonna some more testing with this on current master

**Comment by Roasbeef** [comment]
Can you rebase this? Thanks!
