### PR TITLE
Empty commitsig fix

### LINKED ISSUE #1127: lnd sends a `commit_sig` that doesn't include any updates
### Background

Still tracking down occasional issues between `eclair` and `lnd`, I think I was able to isolate this one on `lnd`'s side.

A long-lived channel was closed because, according to `eclair`, `lnd` sent a `commit_sig` that didn't include any changes, which is a protocol violation.

### Your environment

* yalls mainnet nodeid=`03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56`
* channelid=`5002e7b1fe9243c716e6004ee7d9bfcf95b2ec15c1a1ddcfd80ae4b5f06bd29d`
* version of `lnd`: `0.4.1-beta commit=8af80bfc5cdebcd323ed2a50ea0497df6e9bc6e4` (info from @alexbosworth)

### Actual behaviour

```
  lnd                eclair
   |                   |
   |        ...        | 
   |                   | <--- idle (no htlc on either side) 
   |                   |
   |<----- add-1 ------|
   |<------ sig -------|
   |<----- add-2 ------|
   |------- rev ------>| <--- lnd acks add-1
   |------- sig ------>| <--- lnd signs add-1
   |<------ sig -------|
   |------- rev ------>| <--- lnd acks add-2
   |<------ rev -------|
   |------ ful-1 ----->|
   |------- sig ------>| <--- lnd signs add-1 + add-2 + ful-1 = add-2
   |<------ rev -------|
   |<------ sig -------|
   |------ ful-2 ----->|
   |------- sig ------>| <--- lnd signs add-2 + ful-2 = no htlcs
   |------- rev ------>|
   |<------ rev -------| <--- eclair acks that there are no more htlcs
   |<------ sig -------|
   |------- rev ------>| <--- lnd acks that there are no htlcs on eclair's side
   |------- sig ------>| <--- this signature doesn't include anything new
   |<------ err -------| <--- cannot sign without changes!
   |                   |
```

### PR DESCRIPTION
**Pull request by halseth**
This commit removes a faulty check we did to determine if the channel
commitments were fully synced. We assumed that if out local commitment
chain had a height higher than the remote, then we would have state
updates present in our chain but not in theirs, and owed a commitment.
However, there were cases where this wasn't true, and we would send a
new commitment even though we had no new updates to sign. This is a
protocol violation.

Now we don't longer check the heights to determine if we are fully
synced. A consequence of this is that we also need to check if we have
any pending fee updates that are nopt yet signed, as those are
considered non-empty updates.

Fixes #1127

### CODE REVIEW

File: htlcswitch/link_test.go [hunk 1]
```diff
@@ -4287,3 +4287,376 @@ func TestChannelLinkNoMoreUpdates(t *testing.T) {
 	case <-time.After(100 * time.Millisecond):
 	}
 }
+
+// TestChannelLinkWaitForRevocation tests that we will keep accepting updating
```
Comment (Roasbeef) [inline htlcswitch/link_test.go]: updating -> updates 

from the remote -> from the remote node

File: htlcswitch/link_test.go [hunk 2]
```diff
@@ -3913,3 +3913,377 @@ func restartLink(aliceChannel *lnwallet.LightningChannel, aliceSwitch *Switch,
...
+	defer cleanUp()
+
+	var (
+		coreLink  = aliceLink.(*channelLink)
+		aliceMsgs = coreLink.cfg.Peer.(*mockPeer).sentMsgs
+	)
+
+	// Generate a simple payment from Bob to Alice.
+	htlcAmt := lnwire.NewMSatFromSatoshis(1 * btcutil.SatoshiPerBitcoin)
+	hops := []ForwardingInfo{
```
Comment (Roasbeef) [inline htlcswitch/link_test.go]: Any reason why `generateHops` isn't used in both of these new tests?

File: htlcswitch/link_test.go [hunk 3]
```diff
@@ -3913,3 +3913,377 @@ func restartLink(aliceChannel *lnwallet.LightningChannel, aliceSwitch *Switch,
...
+		t.Fatalf("expected RevokeAndAck, got %T", msg)
+	}
+
+	// This will also make Alice ack htlc2.
+	_, _, _, err = bobChannel.ReceiveRevocation(rev)
+	if err != nil {
+		t.Fatalf("bob failed receiving revocation: %v", err)
+	}
+
+	// Bob can now revoke his old commitment in response to the signature
```
Comment (Roasbeef) [inline htlcswitch/link_test.go]: Where did Alice even send a signature here? If Bob does this, he doesn't even have a valid commitment to play...

File: htlcswitch/link_test.go [hunk 4]
```diff
@@ -3913,3 +3913,377 @@ func restartLink(aliceChannel *lnwallet.LightningChannel, aliceSwitch *Switch,
 
 	return aliceLink, t, cleanUp, nil
 }
+
+// TestChannelLinkNoMoreUpdates tests that we won't send a new commitment
+// when there's no new updates to sign.
+func TestChannelLinkNoMoreUpdates(t *testing.T) {
```
Comment (Roasbeef) [inline htlcswitch/link_test.go]: This is a great test! However, I think we can put in a bit of upfront work here to add some helper functions to make the test a bit more readable and reduce a bit of vertical space here.

**Comment by halseth** [comment]
Did rewrite the tests to extract out most of the common code, and tried to reuse PM's diagram from #1127 to explain what is going on during the test. Let me know if it looks okay, or if the lines become too long.

**Comment by halseth** [comment]
Rebased 🍄
