### PR TITLE
lnrpc/invoicesrpc: extend hop hint selection to account for MPP 

### LINKED ISSUE #4514: 0.11.0-beta.rc2 should attach routing hints in any case
### Background

Up until now that made sense, but looks like lnd is not attaching routing hints for private channels if the invoice amount exceeds the largest channels inbound capacity. Now that MPP+Wumbo are available, I think it makes sense to remove these restrictions and attach routing hints in any case since payments can be split and come in via multiple private channels settling the invoice.

### Your environment

* version of `lnd`: 0.11.0-beta.rc2
* which operating system (`uname -a` on *Nix): ubuntu 20.04 amd64
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.20.99 (own build)
* any other relevant environment details

### Steps to reproduce

My example:
1. Set up lnd with 2 private channels with 0.5 BTC inbound capacity each
2. Create invoice of 1 BTC -> no routing hints attached in invoice
3. Create invoice of <0.5 BTC -> routing hints attached in invoice

### Expected behaviour

Routing hints for both private channels should be attached for the 1 btc invoice

### Actual behaviour

No routing hints attached (verified with `decodepayreq`)

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we update the hop hint selection to account for the fact
that with MPP, a single payment may consume multiple channels. As is, if
a user only has two 0.5 BTC channels, and tries to make a 1 BTC channel,
then the current logic won't include any hop hints.

In this commit we fix this with a simple algorithm for selecting hop
hints:

   * randomly shuffle all hop hints
   * add hop hints until we exceed our max, or the set of available
      bandwidth for all hop hints sums to 2x the invoice payment size

This ensures that users don't always get the same set of routing hints
when they go to pay, which may prevent proper payments as users may be
trying to use the same set of channels causing HTLCs to fail. We add 2x
here to give some margin of error if the active channels are used for
other purposes.

Right now we just prand (`math/rand`) to shuffle the channels, using a
new seed for each new invoice. In the future, we may want to use
stronger randomness here just to make the set of chosen channels less
predictable.

The first commit is move-only, while the second implements the heuristic
described above. 

Fixes #4514

### CODE REVIEW

**Comment by Roasbeef** [comment]
Also working on a basic test, but wanted to get the review started, as the changes to the algo aren't too significant.

File: lnrpc/invoicesrpc/addinvoice.go [hunk 1]
```diff
@@ -435,7 +456,11 @@ func selectHopHints(amtMSat lnwire.MilliSatoshi, cfg *AddInvoiceConfig,
 			zpay32.RouteHint([]zpay32.HopHint{hint}),
 		)
 
-		numHints++
+		// As we've just added a new hop hint, we'll accumulate it's
+		// available balance now to update our tally.
+		//
+		// TODO(roasbeef): have a cut off based on min bandwidth?
```
Comment (wpaulino) [inline lnrpc/invoicesrpc/addinvoice.go:462]: We could still include some hints if the minimum isn't reached in the event that balances change between issuing the invoice and it being paid.

Comment (Roasbeef) [reply lnrpc/invoicesrpc/addinvoice.go:462]: I'm considering always adding the largest channel that can satisfy the payment, which should cover the non-mpp senders. This also can be randomized somewhat, but I need to check some details w.r.t ordering across instantiations of a map with the same contents. 

By min cut off, here I mean if we should exclude stuff like channels that only have a few hundred satoshis available as inbound.

File: lnrpc/invoicesrpc/addinvoice.go [hunk 2]
```diff
@@ -423,3 +325,143 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
+	// we've run through all the available channels, or if the sum
+	// of available bandwidth in the routing hints exceeds 2x the
+	// payment amount. We do 2x here to account for a margin of error if
+	// some of the selected channels no longer become operable.
+	var (
+		totalHintBandwidth lnwire.MilliSatoshi
+		hopHintFactor      = lnwire.MilliSatoshi(2)
+
+		hopHints = make([]func(*zpay32.Invoice), 0, numMaxHophints)
+	)
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply lnrpc/invoicesrpc/addinvoice.go:363]: The newline there is actually strategic ;) 

It lets `hopHints` not exceed 80 characters in the column.

File: lnrpc/invoicesrpc/addinvoice.go (hunk 1 above)
Comment (Roasbeef) [reply lnrpc/invoicesrpc/addinvoice.go:540]: Tacked this on in the latests commit.

File: lnrpc/invoicesrpc/addinvoice.go [hunk 3]
```diff
@@ -423,3 +328,218 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
+	if bytes.Equal(remotePub[:], info.NodeKey1Bytes[:]) {
+		remotePolicy = p1
+	} else {
+		remotePolicy = p2
+	}
+
+	return remotePolicy, true
+}
+
+// selectHopHints will selects up to numMaxHophints from the set of passed open
```
Comment (hsjoberg) [inline lnrpc/invoicesrpc/addinvoice.go:399]: Small nit: s/selects/select/

File: lnrpc/invoicesrpc/addinvoice.go [hunk 4]
```diff
@@ -334,34 +335,54 @@ func selectHopHints(amtMSat lnwire.MilliSatoshi, cfg *AddInvoiceConfig,
...
+		totalHintBandwidth lnwire.MilliSatoshi
+		hopHintFactor      = lnwire.MilliSatoshi(2)
+
+		hopHints = make([]func(*zpay32.Invoice), 0, numMaxHophints)
+	)
+	for i := 0; i < len(openChannels); i++ {
+		// If we hit either of our early termination conditions, then
+		// we'll break the loop here.
+		if totalHintBandwidth*hopHintFactor >= amtMSat ||
+			len(hopHints) >= numMaxHophints {
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply lnrpc/invoicesrpc/addinvoice.go:475]: Check out the new logic to see if you still think it needs to be changed. We first add everything that can carry the payment, then attempt to continue to add more channels until we reach 2x the payment sum or hit the 20 hop hint limit.

File: lnrpc/invoicesrpc/addinvoice.go [hunk 5]
```diff
@@ -423,3 +325,143 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
+	randSource.Shuffle(len(openChannels), func(i, j int) {
+		openChannels[i], openChannels[j] = openChannels[j], openChannels[i]
+	})
+
+	// With our channels shuffled, we'll iterate over them in this
+	// now random order to select a set of channels to include as
+	// hop hints. We'll either stop when we have 20 hop hints,
+	// we've run through all the available channels, or if the sum
+	// of available bandwidth in the routing hints exceeds 2x the
+	// payment amount. We do 2x here to account for a margin of error if
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply lnrpc/invoicesrpc/addinvoice.go]: Fixed in the latest diff!

File: lnrpc/invoicesrpc/addinvoice.go [hunk 6]
```diff
@@ -423,3 +325,143 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
+	var (
+		totalHintBandwidth lnwire.MilliSatoshi
+		hopHintFactor      = lnwire.MilliSatoshi(2)
+
+		hopHints = make([]func(*zpay32.Invoice), 0, numMaxHophints)
+	)
+	for i := 0; i < len(openChannels); i++ {
+		// If we hit either of our early termination conditions, then
+		// we'll break the loop here.
+		if totalHintBandwidth*hopHintFactor >= amtMSat ||
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply lnrpc/invoicesrpc/addinvoice.go]: Fixed!

File: lnrpc/invoicesrpc/addinvoice.go [hunk 7]
```diff
@@ -411,23 +412,77 @@ func addHopHint(hopHints []func(*zpay32.Invoice),
...
+		totalHintBandwidth += channel.LocalCommitment.RemoteBalance
+	}
+
+	// If we have enough hop hints at this point, then we'll exit early.
+	// Otherwise, we'll continue to add more that may help out mpp users.
+	if len(hopHints) >= numMaxHophints {
+		return hopHints
+	}
+
+	// In this second pass we'll add channels, and We'll either stop when
```
Comment (cfromknecht) [inline lnrpc/invoicesrpc/addinvoice.go:465]:
```suggestion
	// In this second pass we'll add channels, and we'll either stop when
```

File: lnrpc/invoicesrpc/addinvoice.go [hunk 8]
```diff
@@ -408,42 +427,19 @@ func selectHopHints(amtMSat lnwire.MilliSatoshi, cfg *AddInvoiceConfig,
 			break
 		}
 
-		// If the channel can'tbe a hop hint, then we'll skip it.
+		// If the channel can't a hop hint, then we'll skip it.
```
Comment (carlaKC) [inline lnrpc/invoicesrpc/addinvoice.go]: s/can't/ can't be

File: lnrpc/invoicesrpc/addinvoice.go [hunk 9]
```diff
@@ -341,74 +408,16 @@ func selectHopHints(amtMSat lnwire.MilliSatoshi, cfg *AddInvoiceConfig,
...
-		}
-
-		// Fetch the policies for each end of the channel.
-		chanID := channel.ShortChanID().ToUint64()
-		info, p1, p2, err := graph.FetchChannelEdgesByID(chanID)
-		if err != nil {
-			log.Errorf("Unable to fetch the routing "+
-				"policies for the edges of the channel "+
-				"%v: %v", chanPoint, err)
+		if !canBeHopHint {
```
Comment (carlaKC) [inline lnrpc/invoicesrpc/addinvoice.go]: nit: since we check `remotePolicy !=nil` below anyway, we could skip the bool here and just return a nil policy if it can't be a hint.

File: lnrpc/invoicesrpc/addinvoice.go [hunk 10]
```diff
@@ -423,3 +327,183 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
+	hopHint := zpay32.HopHint{
+		NodeID:      channel.IdentityPub,
+		ChannelID:   channel.ShortChanID().ToUint64(),
+		FeeBaseMSat: uint32(chanPolicy.FeeBaseMSat),
+		FeeProportionalMillionths: uint32(
+			chanPolicy.FeeProportionalMillionths,
+		),
+		CLTVExpiryDelta: chanPolicy.TimeLockDelta,
+	}
+	hopHints = append(
```
Comment (carlaKC) [inline lnrpc/invoicesrpc/addinvoice.go:412]: full credit to the linter for catching this, but this function doesn't actually add to the `hopHints` slice that is passed in?

File: lnrpc/invoicesrpc/addinvoice.go [hunk 11]
```diff
@@ -423,3 +327,183 @@ func AddInvoice(ctx context.Context, cfg *AddInvoiceConfig,
...
+	graph := cfg.ChanDB.ChannelGraph()
+
+	// We'll add our hop hints in two passes, first we'll add all channels
+	// that are eligible to be hop hints, and also have a local balance
+	// above the payment amount.
+	var totalHintBandwidth lnwire.MilliSatoshi
+	hopHintChans := make(map[wire.OutPoint]struct{})
+	hopHints := make([]func(*zpay32.Invoice), 0, numMaxHophints)
+	for _, channel := range openChannels {
+		channel := channel
```
Comment (hsjoberg) [inline lnrpc/invoicesrpc/addinvoice.go:435]: Perhaps I'm missing something, but this looks like an error

**Comment by carlaKC** [comment]
> Most recent version doesn't add any hop hints because addHopHint doesn't append to our hint list.

Resolved with latest push, LGTM!
