### PR TITLE
rpcserver+lnd_test: fixing unassigned UnsettledBalance field

### LINKED ISSUE #2274: [listchannels] fix unsettled_balance
There is a currently-unused field on `listchannels`, named `UnsettledBalance`, which I believe is meant to display the sum of all outstanding pending htlcs. Turns out, the field is actually 2 years old and been hiding in plain sight, but I just noticed it today 🤣

Currently this field will always contain 0, as we don't modify the field in the response message. To make the field accurate, it should include the sum of the [HTLC amounts](https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L2154) contained in the `PendingHTLCs` field.

### PR DESCRIPTION
**Pull request by ccdle12**
fixes #2274

This PR adds a loop that sums the amount of PendingHtlcs to the UnsettledBalance field for Channels. Also adds a test in lnd_test to ensure that the UnsettledBalance field is actually updated.

### CODE REVIEW

**Comment by ccdle12** [comment]
@cfromknecht Thanks for review! appreciate the insights into the  tests, I'll update according to the comments

**Comment by ccdle12** [comment]
@cfromknecht I've updated the PR according to the suggestions but it's strange I'm receiving no test failures when I run `make check` locally but failing in travis?

**Comment by halseth** [comment]
@ccdle12 The Travis failure is unrelated to your change, I'm working on a fix :)

**Comment by ccdle12** [comment]
@halseth thanks! definitely puts my mind at ease a bit :)

File: lnd_test.go [hunk 1]
```diff
@@ -2036,6 +2036,132 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+
+	// Create carol in hodl mode.
+	carol, err := net.NewNode("Carol", []string{"--debughtlc", "--hodl.exit-settle"})
+	if err != nil {
+		t.Fatalf("unable to create new nodes: %v", err)
+	}
+	defer shutdownAndAssert(net, t, carol)
+
+	// Connect Alice to Carol.
+	if err := net.ConnectNodes(ctxb, net.Alice, carol); err != nil {
```
Comment (wpaulino) [inline lnd_test.go]: This and every other use of a context within this test should use a `context.WithTimeout` with the `defaultTimeout` instead.

File: lnd_test.go [hunk 2]
```diff
@@ -2036,6 +2036,132 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+			return nil
+		}
+
+		unsettledErr = assertUnsettledBalance(expectedBalance, carol, net.Alice)
+		if unsettledErr != nil {
+			return false
+		}
+
+		return true
+	}, time.Second*15)
```
Comment (wpaulino) [inline lnd_test.go]: Nit: can use `defaultTimeout` here.

File: lnd_test.go [hunk 3]
```diff
@@ -2036,6 +2036,132 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+		if unsettledErr != nil {
+			return false
+		}
+
+		// Set the amount expected for the Unsettled Balance for
+		// this channel.
+		expectedBalance := numInvoices * payAmt
+
+		// Closure helper to check Unsettled Balance.
+		assertUnsettledBalance := func(expected int,
```
Comment (wpaulino) [inline lnd_test.go]: Any reason this needs to be defined as a closure? Doesn't seem to be used anywhere else.

File: lnd_test.go [hunk 4]
```diff
@@ -2036,6 +2036,134 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+
+		return true
+	}, time.Second*15)
+	if err != nil {
+		t.Fatalf("unsettled balace error: %v", unsettledErr)
+	}
+
+	// Force and assert the channel closure.
+	ctxt, _ = context.WithTimeout(ctxb, channelCloseTimeout)
+	closeChannelAndAssert(ctxt, t, net, net.Alice, chanPointAlice, true)
```
Comment (wpaulino) [inline lnd_test.go]: We should also use `cleanupForceClose` when force closing a channel to mine the sweeping transactions and not pollute the other tests with them, as it can break certain mempool assumptions within them.

**Comment by ccdle12** [comment]
@wpaulino thanks, appreciate the detailed review, I'll get started on the comments

File: lnd_test.go (hunk 1 above)
Comment (ccdle12) [reply lnd_test.go]: fixed

File: lnd_test.go (hunk 2 above)
Comment (ccdle12) [reply lnd_test.go]: fixed

File: lnd_test.go (hunk 3 above)
Comment (ccdle12) [reply lnd_test.go]: fixed

File: lnd_test.go (hunk 4 above)
Comment (ccdle12) [reply lnd_test.go]: fixed

File: lnd_test.go [hunk 5]
```diff
@@ -2073,6 +2073,130 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+		}
+
+		return true
+	}, defaultTimeout)
+	if err != nil {
+		t.Fatalf("unsettled balace error: %v", unsettledErr)
+	}
+
+	// Force and assert the channel closure.
+	ctxt, _ = context.WithTimeout(ctxb, defaultTimeout)
```
Comment (cfromknecht) [inline lnd_test.go]: should use `channelCloseTimeout` instead

File: lnd_test.go [hunk 6]
```diff
@@ -2073,6 +2073,130 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+	defer shutdownAndAssert(net, t, carol)
+
+	// Connect Alice to Carol.
+	ctxt, _ := context.WithTimeout(ctxb, defaultTimeout)
+	if err := net.ConnectNodes(ctxb, net.Alice, carol); err != nil {
+		t.Fatalf("unable to connect alice to carol: %v", err)
+	}
+
+	// Open a channel between Alice and Carol.
+	ctxt, _ = context.WithTimeout(ctxb, defaultTimeout)
```
Comment (cfromknecht) [inline lnd_test.go]: can use `channelOpenTimeout` here

File: lnd_test.go [hunk 7]
```diff
@@ -2073,6 +2073,130 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+
+	// Channel should be ready for payments.
+	const (
+		payAmt      = 100
+		numInvoices = 6
+	)
+
+	// Create a paystream from Alice to Carol to enable Alice to make
+	// a series of payments.
+	alicePayStream, err := net.Alice.SendPayment(ctxb)
```
Comment (cfromknecht) [inline lnd_test.go]: should probably have a `ctxt` with `defaultTimeout`

File: lnd_test.go [hunk 8]
```diff
@@ -2073,6 +2073,130 @@ func testChannelBalance(net *lntest.NetworkHarness, t *harnessTest) {
...
+// is updated according to the number of Pending Htlcs.
+// Alice will send Htlcs to Carol while she is in hodl mode. This will result
+// in a build of pending Htlcs. We expect the channels unsettled balance to
+// equal the sum of all the Pending Htlcs.
+func testChannelUnsettledBalance(net *lntest.NetworkHarness, t *harnessTest) {
+	const chanAmt = btcutil.Amount(1000000)
+	ctxb := context.Background()
+
+	// Create carol in hodl mode.
+	carol, err := net.NewNode("Carol", []string{"--debughtlc", "--hodl.exit-settle"})
```
Comment (cfromknecht) [inline lnd_test.go]: this line looks a little long to me. i'd suggest wrapping the args like:
```golang
carol, err := new.NewNode("Carol", []string{
        "--debughtlc",
        "--hodl.exit-settle",
})
```

**Comment by ccdle12** [comment]
@cfromknecht Thanks! I'll fixup according to the reviews and respond to the comments accordingly.

File: lnd_test.go (hunk 6 above)
Comment (ccdle12) [reply lnd_test.go]: fixed!

File: lnd_test.go (hunk 7 above)
Comment (ccdle12) [reply lnd_test.go]: fixed!

File: lnd_test.go (hunk 5 above)
Comment (ccdle12) [reply lnd_test.go]: fixed!

File: lnd_test.go (hunk 8 above)
Comment (ccdle12) [reply lnd_test.go]: fixed!

**Comment by cfromknecht** [comment]
Awesome thanks @ccdle12! I'm happy with these changes, @wpaulino do you have anything else?

**Comment by wpaulino** [comment]
LGTM after a squash and rebase 🕺🏻

**Comment by ccdle12** [comment]
@cfromknecht, @wpaulino 

Squashed and rebased,

thanks guy, really appreciate all the help and the reviews!
