### PR TITLE
channeldb+rpc: add pagination of listinvoices

### LINKED ISSUE #1514: channeldb+rpc: add pagination of listinvoices
```
$ lncli listinvoices
[lncli] rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (4726702 vs. 4194304)
```

Currently, once we exceed a few thousand invoices, we can no longer return them over the RPC interface in a single go. As a result, we need to add _pagination_ in order to allow callers to iteratively request the entire range, or even seek within the current range. 

# Steps To Completion  

- [ ] Decide on a sane initial value for the chunk size, this can be determined by computing the current serialize size of the `channeldb` struct (as an upper bound), and extrapolating from there towards the max size of `4726702 bytes. 

- [ ] Modify the `ListInvoices` method to instead resemble the [`ForwardingLog.Query`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/forwarding_log.go#L171) API. 

- [ ] Update the RPC response to use this new query interface, and also the RPC interface to accept the new max invoices, invoice seek param, and any other new relevant parameters. 

- [ ] Update `lncli` to set sane default values for these, and also expose the new values to the caller.

### PR DESCRIPTION
**Pull request by valentinewallace**
In this PR, we introduce support for pagination of invoices at the RPC level. We do this by using a cursor on the invoice bucket, seeking until we have enough results as specified by `--max_invoices` or we have no more invoices to iterate through. 

Fixes #1514.
Replaces #1614 and #1720.

### CODE REVIEW

File: rpcserver.go [hunk 1]
```diff
@@ -2873,25 +2873,38 @@ func (r *rpcServer) LookupInvoice(ctx context.Context,
 func (r *rpcServer) ListInvoices(ctx context.Context,
 	req *lnrpc.ListInvoiceRequest) (*lnrpc.ListInvoiceResponse, error) {
 
-	dbInvoices, err := r.server.chanDB.FetchAllInvoices(req.PendingOnly)
-	if err != nil {
-		return nil, err
+	// If the number of invoices was not specified, then we'll default to
+	// returning the latest 100 invoices.
```
Comment (cfromknecht) [inline rpcserver.go]: will this actually return the latest 100? Seems like we scan forward in time

Comment (Roasbeef) [reply rpcserver.go]: Well no latest, but _first_.
