### PR TITLE
walletrpc: add new PSBT creation+signing RPCs

### LINKED ISSUE #3938: lnwallet+rpc: create a set of generic PSBT creation+signing RPC calls in the walletkit sub-server
Related To #3936. These two issue can be began more or less concurrently, as this portion is blocked on support within `btcwallet` itself. Once that implementation is complete, we'd then want to surface this for the end user within `lnd` itself. 

At a higher level, a user should be instruct `lnd` to execute functionality similar to a `fundrawtransaction` call to obtain a complete PSBT packet paying out to the set of specified outputs. We'll also need to insert our change address and perform any needed verification checks. The dual of this call is then _signing_ (to finalize) this PSBT packet, which will then be ready for broadcast by the end user. 

This issue is primary concerned with the design of the RPC interace, as much of the lower level plumbing will be handled by the yet-to-be-written `btcwallet` interface. 

# Steps to Completion 
- [ ] Create to new calls (names just an example) on the `WalletKit` RPC sub-server: `FundPsbtPacket` and `FinalizePsbtPacket`. The names should be self explanatory. 

- [ ] The second portion of this issues deals with the work we'll need to do within `btcwallet` to ensure that we properly lock any relevant inputs (so we don't accidentally create double spends), and also release them if the user wants to abort the protocol. As a result, we'll also need an additional call to _free_ up any inputs allocated to a PSBT. This portion of the issue is related to #2976. 

Once this issue is done, we should be able to use an `lnd` instance to being a funding flow, and provide inputs for this funding flow from another `lnd` instance!

### LINKED ISSUE #4330: lncli openchannel in psbt mode does not accept network serialized tx at final step
When trying open a channel using the CLI in psbt mode, at the last step, after the tx has been signed, lnd [only accepts a finalized PSBT](https://github.com/lightningnetwork/lnd/blob/948fe8cfdbf5b873e55f68e3b4463ff0c1ffff73/cmd/lncli/cmd_open_channel.go#L510).
The [PSBT at this point](https://github.com/lightningnetwork/lnd/blame/32b04b7ac32ba7eabbcda7722cef03b5977acf62/docs/psbt.md#L221) is a complete and signed transaction, as returned by an [Input Finalizer](https://github.com/bitcoin/bips/blob/4fb2c5290e10270c8e4a6df357fe98bfab2ddfe9/bip-0174.mediawiki#Input_Finalizer).

What is the reasoning for not accepting a network serialized raw hex tx at that point, as returned by a [Transaction Extractor](https://github.com/bitcoin/bips/blob/4fb2c5290e10270c8e4a6df357fe98bfab2ddfe9/bip-0174.mediawiki#transaction-extractor)?

I cannot see any technical reason why the finalized PSBT would be needed: the only extra information inside it (compared to the network tx) is potentially the input UTXOs, but even the presence of those is not guaranteed (and if they were there, they have already been seen by lnd in the earlier steps).

Context: Electrum currently does not expose the finalised PSBT to the user; only the network serialized tx. The "Transation Extractor" phase of the PSBT flow happens automatically. This makes the UX significantly simpler.

### LINKED ISSUE #4400: PSBT Funding flow retry, instructions for converting binary PSBT to base64, and accept PSBT from file,
### Background
1. In the PSBT funding flow, if you input the base64 data wrong, it cancels the channel open. This requires you to go back to your hardware devices and resign the PSBT again.

2. I have a PSBT created in Electrum and signed with coldcards, I can only load it back into electrum, I do not know how to convert it to base64.

3. It would also be great to be able to input the PSBT as a file, but that is a little challenging since the PSBT address is only created after the command has run.

### Your environment

* version of `lnd`
    "version": "0.10.99-beta commit=clock/v1.0.0-85-gacc698a6995b35976950282b29c9685c993a0364",
    "commit_hash": "acc698a6995b35976950282b29c9685c993a0364",
* which operating system (`uname -a` on *Nix)
Ubuntu
* version of `btcd`, `bitcoind`, or other backend
bitcoind
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
Generate base64 from electrum psbt file:
base64 testpsbt-signed.psbt -w 0

### Expected behaviour
Channel funding flow complete

### Actual behaviour
[lncli] verifying PSBT by lnd failed: rpc error: code = Unknown desc = error parsing psbt: Invalid PSBT serialization format

### PR DESCRIPTION
**Pull request by guggero**
Fixes #3938.
Fixes #4400.

~Depends on https://github.com/btcsuite/btcutil/pull/178 and https://github.com/btcsuite/btcwallet/pull/711.~

EDIT: Depends on https://github.com/btcsuite/btcwallet/pull/721.

### CODE REVIEW

File: lnrpc/walletrpc/psbt.go [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+				utxo = u
+				break
+			}
+		}
+		if utxo == nil {
+			return fmt.Errorf("input %d not found in list of non-"+
+				"locket UTXO", idx)
+		}
+
+		// Everything's OK, we found the UTXO and can add its
```
Comment (Roasbeef) [inline lnrpc/walletrpc/psbt.go:72]: Isn't this already done within the `btcwallet` methods? If not, then why not?

File: lnrpc/walletrpc/walletkit.proto [hunk 2]
```diff
@@ -454,3 +484,93 @@ message LabelTransactionRequest {
...
+    bytes funded_psbt = 1;
+
+    /*
+    The list of lock leases that were acquired for the inputs in the funded PSBT
+    packet.
+    */
+    repeated UtxoLease locked_utxos = 2;
+}
+
+message TxTemplate {
```
Comment (Roasbeef) [inline lnrpc/walletrpc/walletkit.proto:534]: 👍

File: lnrpc/walletrpc/walletkit_server.go [hunk 3]
```diff
@@ -819,3 +840,226 @@ func (w *WalletKit) LabelTransaction(ctx context.Context,
...
+
+	// In case the user did specify inputs, we need to make sure they are
+	// known to us, still unspent and not yet locked.
+	if len(packet.UnsignedTx.TxIn) > 0 {
+		// Get a list of all unspent witness outputs. We'll acquire the
+		// global coin selection lock to ensure there aren't any other
+		// concurrent processes attempting to lock any UTXOs which may
+		// be shown available to us.
+		var utxos []*lnwallet.Utxo
+		err = w.cfg.CoinSelectionLocker.WithCoinSelectLock(func() error {
```
Comment (Roasbeef) [inline lnrpc/walletrpc/walletkit_server.go:920]: I think nearly this entire method should be wrapped in the main coin selection lock to ensure we have a consistent view of the wallet's current UTXO set.

File: lnrpc/walletrpc/walletkit_server.go [hunk 4]
```diff
@@ -819,3 +840,226 @@ func (w *WalletKit) LabelTransaction(ctx context.Context,
...
+			utxos, err = w.cfg.Wallet.ListUnspentWitness(
+				defaultMinConf, defaultMaxConf,
+			)
+			return err
+		})
+		if err != nil {
+			return nil, err
+		}
+
+		// Validate all inputs against our known list of UTXOs now.
```
Comment (Roasbeef) [inline lnrpc/walletrpc/walletkit_server.go:930]: If inputs in the _PSBT_ were specified, then wouldn't we expect the input info to be populated as well? In this case, we can just do a sanity check that all the inputs are ours (though I think we should also be able to support only a subset of the inputs actually being ours).

File: lnrpc/walletrpc/walletkit_server.go [hunk 5]
```diff
@@ -819,3 +840,226 @@ func (w *WalletKit) LabelTransaction(ctx context.Context,
...
+	default:
+		return nil, fmt.Errorf("fee definition missing, need to " +
+			"specify either target_conf or set_per_vbyte")
+	}
+
+	// We made sure the input from the user is as sane as possible. We can
+	// now ask the wallet to fund the TX. This will not yet lock any coins
+	// but might still change the wallet DB by generating a new change
+	// address.
+	err = w.cfg.Wallet.FundPsbt(packet, feeSatPerKW)
```
Comment (Roasbeef) [inline lnrpc/walletrpc/walletkit_server.go:970]: This should be wrapped in the main coin selection context manager (the mutex).

File: cmd/lncli/walletrpc_active.go [hunk 6]
```diff
@@ -396,3 +401,200 @@ func labelTransaction(ctx *cli.Context) error {
...
+	performed automatically. If the template does contain any inputs, it is
+	assumed that full coin selection happened externally and no additional
+	inputs are added. If the specified inputs aren't enough to fund the
+	outputs with the given fee rate, an error is returned.
+
+	After either selecting or verifying the inputs, all input UTXOs are
+	locked with an internal app ID.
+	`,
+	Flags: []cli.Flag{
+		cli.Uint64Flag{
```
Comment (Roasbeef) [inline cmd/lncli/walletrpc_active.go:431]: What about an ability to specify `(pkScript, value)` tuples like with `sendmany`? This addition would make it easier to use as a replacement for bitcoind when using something like a cold card, unless we intend users to still rely on HWI partially.

File: cmd/lncli/walletrpc_active.go [hunk 7]
```diff
@@ -396,3 +401,200 @@ func labelTransaction(ctx *cli.Context) error {
...
+	// number of arguments/flags.
+	if ctx.NArg() != 1 {
+		return cli.ShowCommandHelp(ctx, "fundpsbt")
+	}
+
+	walletClient, cleanUp := getWalletClient(ctx)
+	defer cleanUp()
+
+	args := ctx.Args()
+	psbtBytes, err := base64.StdEncoding.DecodeString(args.First())
```
Comment (Roasbeef) [inline cmd/lncli/walletrpc_active.go:457]: Not super clear from the help or description that the first value is the raw PSBT template, this should also be a named argument as well IMO.

File: cmd/lncli/walletrpc_active.go [hunk 8]
```diff
@@ -396,3 +401,200 @@ func labelTransaction(ctx *cli.Context) error {
...
+
+	printJSON(&fundPsbtResponse{
+		Psbt:  base64.StdEncoding.EncodeToString(response.FundedPsbt),
+		Locks: response.LockedUtxos,
+	})
+
+	return nil
+}
+
+// finalizePsbtResponse is a struct that contains JSOn annotations for nice
```
Comment (Roasbeef) [inline cmd/lncli/walletrpc_active.go:497]: JSOn -> JSON

File: cmd/lncli/walletrpc_active.go [hunk 9]
```diff
@@ -396,3 +401,200 @@ func labelTransaction(ctx *cli.Context) error {
...
+	// number of arguments/flags.
+	if ctx.NArg() != 1 {
+		return cli.ShowCommandHelp(ctx, "finalizepsbt")
+	}
+
+	walletClient, cleanUp := getWalletClient(ctx)
+	defer cleanUp()
+
+	args := ctx.Args()
+	psbtBytes, err := base64.StdEncoding.DecodeString(args.First())
```
Comment (Roasbeef) [inline cmd/lncli/walletrpc_active.go:535]: Similar comment here re help and the expected arguments.

File: cmd/lncli/walletrpc_active.go [hunk 10]
```diff
@@ -396,3 +401,200 @@ func labelTransaction(ctx *cli.Context) error {
...
+
+	printJSON(&finalizePsbtResponse{
+		Psbt:    base64.StdEncoding.EncodeToString(response.SignedPsbt),
+		FinalTx: hex.EncodeToString(response.RawFinalTx),
+	})
+
+	return nil
+}
+
+var releaseOutputCommand = cli.Command{
```
Comment (Roasbeef) [inline cmd/lncli/walletrpc_active.go:556]: Hmm, alternatively, we could return a unique identifier for the PSBT packet (could just be the full txid) then have the user pass that in to somethign like `cancelpsbt` which looks up the transaction and does all the input unlocking automatically.

File: lntest/itest/psbt.go [hunk 11]
```diff
@@ -73,49 +78,23 @@ func testPsbtChanFunding(net *lntest.NetworkHarness, t *harnessTest) {
...
+		},
+		Fees: &walletrpc.FundPsbtRequest_SatPerVbyte{
+			SatPerVbyte: 2,
+		},
 	}
-
-	// Serialize the PSBT with the faked UTXO information.
-	var buf bytes.Buffer
-	err = unsignedPsbt.Serialize(&buf)
+	fundResp, err := dave.WalletKitClient.FundPsbt(ctxt, fundReq)
```
Comment (Roasbeef) [inline lntest/itest/psbt.go:95]: 👍

File: cmd/lncli/walletrpc_active.go (hunk 10 above)
Comment (guggero) [reply cmd/lncli/walletrpc_active.go:556]: But wouldn't we need to store the PSBT in the wallet then? The way it's currently implemented, the PSBT operations are stateless (except for an eventual change address being added to the wallet DB).

Comment (Roasbeef) [reply cmd/lncli/walletrpc_active.go:556]: Yeah that's true, it's nice that things are stateless as is.

File: lnrpc/walletrpc/psbt.go (hunk 1 above)
Comment (guggero) [reply lnrpc/walletrpc/psbt.go:72]: You're right, most of this is already done by the wallet. The only thing to check here is that the inputs aren't spent or locked yet.

File: lnrpc/walletrpc/walletkit_server.go (hunk 4 above)
Comment (guggero) [reply lnrpc/walletrpc/walletkit_server.go:930]: Optimally, yes. But because the wallet currently only supports adding own inputs, it populates/overwrites the input info anyway. We might change this in the future when adding foreign inputs is supported.

File: lnrpc/walletrpc/walletkit_server.go (hunk 5 above)
Comment (guggero) [reply lnrpc/walletrpc/walletkit_server.go:970]: You mean `WithCoinSelectLock`, right? Wrapped all wallet operations in a closure.

**Comment by guggero** [comment]
Rebased this and depending btcwallet PR.

**Comment by Roasbeef** [comment]
btcwallet PR has been merged! now!

File: lnrpc/walletrpc/psbt.go [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+	outpoint   wire.OutPoint
+	expiration time.Time
+}
+
+// verifyInputsUnspent checks that all inputs are contained in the list of
+// known, non-locked UTXOs given.
+func verifyInputsUnspent(inputs []*wire.TxIn, utxos []*lnwallet.Utxo) error {
+	for idx, txIn := range inputs {
+		found := false
+		for _, u := range utxos {
```
Comment (Roasbeef) [inline lnrpc/walletrpc/psbt.go:34]: Likely won't be a big deal unless "massive" scale, but we should leave a TOOD here to use a map to make things a bit more efficient IMO.

File: lnrpc/walletrpc/psbt.go [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+	locks := make([]*utxoLock, len(packet.UnsignedTx.TxIn))
+	for idx, rawInput := range packet.UnsignedTx.TxIn {
+		lock := &utxoLock{
+			lockID:   LndInternalLockID,
+			outpoint: rawInput.PreviousOutPoint,
+		}
+
+		expiration, err := w.LeaseOutput(lock.lockID, lock.outpoint)
+		if err != nil {
+			return nil, fmt.Errorf("could not lease a lock on "+
```
Comment (Roasbeef) [inline lnrpc/walletrpc/psbt.go:64]: There should be `defer` to unlock the set of inputs that were already leased up until this point. Unless we want the caller to have to handle this responsibility.

File: lntest/itest/lnd_psbt_test.go [hunk 14]
```diff
@@ -89,47 +93,28 @@ func testPsbtChanFunding(net *lntest.NetworkHarness, t *harnessTest) {
...
+		},
+		Fees: &walletrpc.FundPsbtRequest_SatPerVbyte{
+			SatPerVbyte: 2,
+		},
 	}
-
-	// Serialize the PSBT with the faked UTXO information.
-	var buf bytes.Buffer
-	err = unsignedPsbt.Serialize(&buf)
+	fundResp, err := dave.WalletKitClient.FundPsbt(ctxt, fundReq)
```
Comment (Roasbeef) [inline lntest/itest/lnd_psbt_test.go:117]: 👍

**Review by Roasbeef — CHANGES_REQUESTED** [review]
This is super close! Only major comment is re makings sure we unlock the set of leased coins if we can unlock lock some but not all fo them. Gonna give this a spin on the CLI as well to give some feedback on the CLI flow before merging.

File: lnrpc/walletrpc/psbt.go (hunk 13 above)
Comment (guggero) [reply lnrpc/walletrpc/psbt.go:80]: Right, good point! Decided to not go with a `defer` as we only have one error path. So coded it out explicitly there.

**Comment by guggero** [comment]
Rebased after dependend PRs were merged and addressed the comments.

File: lnrpc/walletrpc/walletkit.proto [hunk 15]
```diff
@@ -454,3 +485,92 @@ message LabelTransactionRequest {
...
+    lnrpc.OutPoint outpoint = 2;
+
+    /*
+    The absolute expiration of the output lease represented as a unix timestamp.
+    */
+    uint64 expiration = 3;
+}
+
+message FinalizePsbtRequest {
+    bytes funded_psbt = 1;
```
Comment (wpaulino) [inline lnrpc/walletrpc/walletkit.proto:569]: Nit: missing field docs.

File: lnrpc/walletrpc/psbt.go (hunk 13 above)
Comment (wpaulino) [reply lnrpc/walletrpc/psbt.go:80]: What @Roasbeef was referring to was to defer at the level of the caller of `lockInputs`, as an error can occur in some other method after the fact and the inputs wouldn't be released. There isn't a method that's called after `lockInputs` that returns an error at the moment, but it's probably still worth making the change to prevent any potential bugs in the future.

**Review by wpaulino — COMMENTED** [review]
Looks pretty good! Will begin playing around with it locally and report any issues.

File: lnrpc/walletrpc/psbt.go (hunk 13 above)
Comment (guggero) [reply lnrpc/walletrpc/psbt.go:80]: Ah, I understand now. But the `lockInputs()` is the last thing we do in `FundPsbt()` so nothing can fail after that. But I extended the comment on the function call and also on the RPC description that it's the caller's responsibility to unlock the UTXOs in case of an error on the caller's side.

I don't think we can make this nicer without introducing state to the walletkit server that keeps track of all PSBTs.

File: lnrpc/walletrpc/walletkit_server.go [hunk 16]
```diff
@@ -114,12 +116,32 @@ var (
...
 	// macaroon that we expect to find via a file handle within the main
 	// configuration file in this package.
 	DefaultWalletKitMacFilename = "walletkit.macaroon"
+
+	// LndInternalLockID is the binary representation of the SHA256 hash of
+	// the string "lnd-internal-lock-id" and is used for UTXO lock leases to
+	// identify that we ourselves are locking an UTXO, for example when
+	// giving out a funded PSBT. The ID corresponds to the hex value of
+	// ede19a92ed321a4705f8a1cccc1d4f6182545d4bb4fae08bd5937831b7e38f98.
+	LndInternalLockID = wtxmgr.LockID{
```
Comment (cfromknecht) [inline lnrpc/walletrpc/walletkit_server.go:139]: doesn't look like we exclude locking by this id from external requests?

File: lnrpc/walletrpc/psbt.go (hunk 13 above)
Comment (cfromknecht) [reply lnrpc/walletrpc/psbt.go:80]: another option would be to make a `LeaseOutputs` and `ReleaseOutputs` that lock all of them atomically

File: cmd/lncli/walletrpc_active.go [hunk 17]
```diff
@@ -396,3 +402,329 @@ func labelTransaction(ctx *cli.Context) error {
...
+
+// fundPsbtResponse is a struct that contains JSOn annotations for nice result
+// serialization.
+type fundPsbtResponse struct {
+	Psbt  string                 `json:"psbt"`
+	Locks []*walletrpc.UtxoLease `json:"locks"`
+}
+
+var fundPsbtCommand = cli.Command{
+	Name:     "fundpsbt",
```
Comment (cfromknecht) [inline cmd/lncli/walletrpc_active.go:414]: nit: another option is to name the commands `lncli wallet psbt fund` and `lncli wallet psbt finalize` to enforce better grouping. idk how much nesting our cli lib allows tho...

File: lntest/itest/lnd_psbt_test.go [hunk 18]
```diff
@@ -229,6 +210,12 @@ func testPsbtChanFunding(net *lntest.NetworkHarness, t *harnessTest) {
 
 	// Great, now we can mine a block to get the transaction confirmed, then
 	// wait for the new channel to be propagated through the network.
+	var buf bytes.Buffer
+	finalTx := &wire.MsgTx{}
```
Comment (cfromknecht) [inline lntest/itest/lnd_psbt_test.go:214]: nit: this could also be initialized as `var finalTx wire.MsgTx`

**Review by cfromknecht — COMMENTED** [review]
@guggero nice work! lot of good stuff in here :)

File: cmd/lncli/walletrpc_active.go (hunk 17 above)
Comment (guggero) [reply cmd/lncli/walletrpc_active.go:414]: Good idea, done.

File: lnrpc/walletrpc/psbt.go (hunk 13 above)
Comment (guggero) [reply lnrpc/walletrpc/psbt.go:80]: Yeah, I agree, that would have been the best option. But that would require another `btcwallet` change which I'd rather avoid at this point to move forward with this feature.

Comment (Roasbeef) [reply lnrpc/walletrpc/psbt.go:80]: @guggero ok I think that's reasonable. Worst case someone doesn't have access to all their inputs until the lease expires.

File: cmd/lncli/walletrpc_active.go [hunk 19]
```diff
@@ -14,6 +17,20 @@ import (
 	"github.com/urfave/cli"
 )
 
+var (
+	// psbtCommand is a wallet subcommand that is responsible for PSBT
+	// operations.
+	psbtCommand = cli.Command{
+		Name: "psbt",
```
Comment (Roasbeef) [inline cmd/lncli/walletrpc_active.go:24]: 😎

**Review by Roasbeef — APPROVED** [review]
Only thing I think this is missing is some light doc updates, but that's totally non-blocking, and this PR has been in stasis for quite a while. 

LGTM 🎨

**Comment by guggero** [comment]
DON'T MERGE, just discovered a bug in the fee estimation if more than one input is selected (good thing I started writing the docs for this and coming up with useful examples :sweat_smile: )

**Comment by guggero** [comment]
Added some documentation with examples and fixed the change amount bug.

**Review by wpaulino — APPROVED** [review]
🎉

**Comment by wpaulino** [comment]
@guggero needs a rebase, but it should be good to merge once addressed.
