### PR TITLE
routing: add mission control import rpc

### LINKED ISSUE #4483: rpc: abandonchannel silently "succeeds" for channels not in the pending open state
I opened a channel from Electrum Mobile lightning wallet to my lnd node, but the funding transaction failed to be broadcast.

That left a pending channel in my lnd node that I can't get rid of. I tried force closing, then called 'abandonChannel', but it still is shown as:

```json
➜  lnd git:(master) ✗ ./lncli-debug pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "redacted",
                "channel_point": "redacted:0",
                "capacity": "1000000",
                "local_balance": "0",
                "remote_balance": "redacted",
                "local_chan_reserve_sat": "10000",
                "remote_chan_reserve_sat": "10000",
                "initiator": "INITIATOR_REMOTE",
                "commitment_type": "STATIC_REMOTE_KEY"
            },
            "limbo_balance": "0",
            "commitments": {
                "local_txid": "redacted",
                "remote_txid": "redacted",
                "remote_pending_txid": "",
                "local_commit_fee_sat": "12116",
                "remote_commit_fee_sat": "12116",
                "remote_pending_commit_fee_sat": "0"
            }
        }
    ]
}

``` 

Is there a way to get rid of it?

### LINKED ISSUE #4833: routerrpc+routing: add ability to import mission control weights/data
As is, it's possible for users to export their mission control state which can be useful for debugging, or just trying to reverse engineer how mission control itself works. The format that's exported is more or less an exact snapshot of the memory/desk state that `lnd` will use to guide its path finding endeavors. Mission control is known to be most effective once it has a "hot cache" as it's able to prune down the search space and avoid routes/channels it knows are already bad or ineffective. However, users that attempt to use path finding with a cold cache may waste time attempting to re-build the prior memory (since the channel weights decay) and potentially will run into some timeout by the time that they have "enough" memory built up. 

Consider that most users use a 60 second timeout, if it takes 61 seconds (making an assumption here for simplicity of the example), then users will timeout before they have a chance to actually start using the memory they've built up. Ofc, passive probing can also help to build up this memory/snapshot as well, but that isn't something that most end users or services do unless they have very high outbound volume, in which case they'll already be passively training their mission control instance over time. 

If we give users an option to _import_ mission control state, then they can start with a _hot cache_ for path finding. Going beyond this, state could be passed around between users of a given service to train their mission control state in a manner similar to distributed active learning in ML land. 

# Steps to Completion 

- [ ] Extend the `missionControlState` struct to be able to _batch import_ a series of pair results. 

- [ ] Add a new call to the `routerrpc`, something like `ImportMissionControl` to allow users to take the _direct_ output of the `QueryMissionControl` call. This data format would effectively become a new standardized way of sharing path finding history/memory between `lnd` nodes. 

- [ ] With the above step, we'll need to make a decision if we encounter a new pair result that already exists within the mission control state.
   * There're a few scenarios we need to account for:
       * A success exists, a newer failure exists (according to timestamp) 
       * A failure exists, a newer success exists 
   * To simplify to start with, we could consider just override anything with a newer timestamp compared to the existing state. In the future, we may attempt to combine in more clever ways, but we should likely just make an incremental step first since this change has rather high leverage for the network and many users as a whole.

### PR DESCRIPTION
**Pull request by carlaKC**
This PR adds in-memory mission control import. We take a very simple approach, as outlined in the original issue, where we only import results that are fresher than our current records. 

Fixes #4833

### CODE REVIEW

File: routing/missioncontrol_state.go [hunk 1]
```diff
@@ -209,3 +209,46 @@ func (m *missionControlState) getSnapshot() *MissionControlSnapshot {
...
+			fromNode, toNode,
+		)
+	}
+}
+
+func (m *missionControlState) importResult(currentTs, importedTs time.Time,
+	importedResult pairResult, fromNode, toNode route.Vertex) {
+
+	if currentTs.After(importedTs) {
+		log.Infof("Not setting pair result for %v->%v (%v) "+
```
Comment (cfromknecht) [inline routing/missioncontrol_state.go:245]: maybe move to `Debugf`? could potentially be a lot of entries :)

File: routing/missioncontrol.go [hunk 2]
```diff
@@ -342,6 +342,24 @@ func (m *MissionControl) GetHistorySnapshot() *MissionControlSnapshot {
...
+// restarts.
+func (m *MissionControl) ImportHistory(history *MissionControlSnapshot) error {
+	if history == nil {
+		return errors.New("cannot import nil history")
+	}
+
+	m.Lock()
+	defer m.Unlock()
+
+	log.Debugf("Importing history snapshot to mission control")
```
Comment (cfromknecht) [inline routing/missioncontrol.go:356]: nit: maybe. bump this to `Infof`? would also make a nice addition to log how many were added/ignored! that way info users only see:
```
[CRTR] Importing history snapshot to mission control
[CRTR] Imported XX/YY fresh results from mission control history snapshot.
```

**Review by cfromknecht — COMMENTED** [review]
Nice feature!! Just a few nits on logging

> Fixes #4483

Looks like this might be the wrong issue? Think we want #4833

File: lnrpc/routerrpc/router_server.go [hunk 3]
```diff
@@ -487,6 +492,156 @@ func toRPCPairData(data *routing.TimedPairResult) *PairData {
...
+	if err != nil {
+		return nil, err
+	}
+
+	to, err := route.NewVertexFromBytes(pairResult.NodeTo)
+	if err != nil {
+		return nil, err
+	}
+
+	if bytes.Equal(from[:], to[:]) {
```
Comment (bhandras) [inline lnrpc/routerrpc/router_server.go:541]: nit: could just `if from == to` since these are fixed size arrays.

File: lnrpc/routerrpc/router_server.go [hunk 4]
```diff
@@ -487,6 +492,156 @@ func toRPCPairData(data *routing.TimedPairResult) *PairData {
...
+		return nil, errors.New("peer pubkeys must differ")
```
Comment (bhandras) [inline lnrpc/routerrpc/router_server.go:542]: nit: wdyt about rephrasing the error to something like "node pair source and destination must be different"? Maybe we could even refer to the pubkey itself (like below).

File: lnrpc/routerrpc/router_server.go [hunk 5]
```diff
@@ -487,6 +492,156 @@ func toRPCPairData(data *routing.TimedPairResult) *PairData {
...
+		btcutil.Amount(pairResult.History.SuccessAmtSat),
+		pairResult.History.SuccessTime,
+	)
+	if err != nil {
+		return nil, fmt.Errorf("pair: %v->%v invalid success: %v",
+			from, to, err)
+	}
+
+	if successAmt == 0 && failAmt == 0 {
+		return nil, fmt.Errorf("either success of failure result " +
```
Comment (bhandras) [inline lnrpc/routerrpc/router_server.go:566]: Similarly maybe we could print the from/to nodes to make it easier to debug if there's anything wrong with the dump.

File: routing/missioncontrol_state.go [hunk 6]
```diff
@@ -209,3 +209,46 @@ func (m *missionControlState) getSnapshot() *MissionControlSnapshot {
...
+			lastResult.SuccessTime, pair.SuccessTime, successResult,
+			fromNode, toNode,
+		)
+	}
+}
+
+func (m *missionControlState) importResult(currentTs, importedTs time.Time,
+	importedResult pairResult, fromNode, toNode route.Vertex) {
+
+	if currentTs.After(importedTs) {
```
Comment (bhandras) [inline routing/missioncontrol_state.go:244]: Why wouldn't we want to simply overwrite? I see it perfectly valid to just overwrite with an old dump. WDYT?

File: cmd/lncli/cmd_import_mission_control.go [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+	Action:    actionDecorator(importMissionControl),
+	Flags: []cli.Flag{
+		cli.BoolFlag{
+			Name:  "failure",
+			Usage: "whether the routing history entry was a failure",
+		},
+	},
+}
+
+func importMissionControl(ctx *cli.Context) error {
```
Comment (bhandras) [inline cmd/lncli/cmd_import_mission_control.go:30]: This is very nice, maybe could also add csv import? (Otherwise MC may change if node is busy).

**Review by bhandras — COMMENTED** [review]
Nice feature, mostly nits. :rocket:

File: routing/missioncontrol_state.go (hunk 6 above)
Comment (carlaKC) [reply routing/missioncontrol_state.go:244]: Not sure why would we want to overwrite our existing fresh results with older results? Since the goal in doing this is to get a hotter cache

File: cmd/lncli/cmd_import_mission_control.go (hunk 7 above)
Comment (carlaKC) [reply cmd/lncli/cmd_import_mission_control.go:30]: What do you by MC might change?

I was picturing the main use case for bulk-import to be the rpc? Since you can pass the request from `QueryMissionControl` directly in, adding a csv is an extra step. Could add an option to feed the json output in like we do for `SendToRoute` if we want to do bulk import via cli?

File: lnrpc/routerrpc/router_server.go (hunk 4 above)
Comment (carlaKC) [reply lnrpc/routerrpc/router_server.go]: nice idea! added prefix with from/to to all errors

File: lnrpc/routerrpc/router.proto [hunk 8]
```diff
@@ -334,6 +343,14 @@ message QueryMissionControlResponse {
     repeated PairHistory pairs = 2;
 }
 
+message ImportMissionControlRequest {
+    // Node pair-level mission control state to be imported.
+    repeated PairHistory pairs = 1;
```
Comment (joostjager) [inline lnrpc/routerrpc/router.proto:348]: Mission control's internal state on disk isn't the pair history, but the low level raw payment attempt data with routes and everything. The reason for storing that is that it would allow the mission control logic to be modified without the need for data migration (if possible at all with the derived data).

Another benefit of operating on raw data is that it is possible to change mission control settings and re-derive its state again. In the future, this could even be done runtime. Actually it could be part of the other mission control PR that allows changing the settings runtime. 

But because everything is internal, we could always find a way to deal with an upgrade.

With this PR however, that becomes more troublesome. This RPC freezes the structure of mission control's internal state. Changing it will involve a breaking change or supporting the older RPC. To me that doesn't look ideal.

The alternative is to create an import feature for raw payment data. This import function would reconstruct mission control's state in whatever format is best. Sensitive fields like the payment hash could be stripped out as long as they aren't processed to reconstruct mission control's state.

Comment (Roasbeef) [reply lnrpc/routerrpc/router.proto:348]: > Mission control's internal state on disk isn't the pair history, but the low level raw payment attempt data with routes and everything

The internal state _is_ this currently, but we do indeed derive that data from the raw payment routes. We went in this direction as we're looking at a basic form of distributed mission control where nodes can start to share this information. By updating only the resulting _in-memory_state, we don't need to also store all the route information which is larger, and leaks more information w.r.t the activity of a given node. Also note that this is intended to just be in memory and not propagate to what's stored on disk yet. We could even consider just create a parallel ephemeral mission control where this new data is applied. 

> With this PR however, that becomes more troublesome. This RPC freezes the structure of mission control's internal state.

Eh not really, it's a new experimental call that we're open to breaking at will for the purpose of our experiments. The other advantage of doing something like this in the short term is that the serialized information is _much_ smaller. A hundred individual payment attempts utilizing a total of 1k individual routes can be compressed into a single pair (not likely in reality, just an example). 

> The alternative is to create an import feature for raw payment data. This import function would reconstruct mission control's state in whatever format is best

We considered this but dismissed it in the short term due to the drawbacks I mentioned above. If you want to take a stab at implementing a stripped down version, we'd consider it, but as pointed out above it would leak _a lot_ more information (the payment hash is the least of our concerns).

Comment (Roasbeef) [reply lnrpc/routerrpc/router.proto:348]: We can also leave a path open to the raw data import by making this field a `oneof` w/ the current implementation being a simple in-memory insertion. In the future, if we choose to go with the raw scrubbed data format, we can deprecate the pair history over time. Thoughts @carlaKC ?

Comment (joostjager) [reply lnrpc/routerrpc/router.proto:348]: >The internal state is this currently

I wrote 'Mission control's internal state *on disk*...' I think my statement is correct.

>Eh not really, it's a new experimental call that we're open to breaking at will for the purpose of our experiments.

That wasn't obvious to me from looking at the change set. It is in the router subserver which is now enabled by default iirc. 

>The other advantage of doing something like this in the short term is that the serialized information is much smaller

Question is whether this advantage is relevant in practice for users.

I get the downside of leaking info with raw payment history. But isn't 'distributed mission control' intended to be used by a node operator that runs multiple nodes? In that case nothing is leaked that the operator didn't already know.

If the idea is to dump these exports on the internet, I can understand that some won't do that because of the sensitivity of the information. But it isn't said that the current in-memory state can't be used to derive interesting information from as well. It isn't as rich as the raw data, but could still present a privacy risk.

Comment (carlaKC) [reply lnrpc/routerrpc/router.proto:348]: To me there are two different kinds of imports that one could want for MC:
1. Public import: obtain information from an external source to boost an inactive/new node, privacy concerns for data exporter
2. Personal import: share information between your own nodes, to bootstrap a new node coming online or restore from a previously active node, no privacy concerns

This PR was intended to solve (1), my fault that it wasn't very clear, since newer nodes struggling to route has been a more reported problem than the need to bootstrap your own nodes (2). If we get some feature requests for the latter, I think it would be a great thing to add as well. 

>  But it isn't said that the current in-memory state can't be used to derive interesting information from as well. It isn't as rich as the raw data, but could still present a privacy risk.

This is indeed an open question, but I do think that the aggregation of results does obfuscate routing information to a large degree, especially since one would expect larger nodes to be providing this export. This information is also optionally exported and shared at the discretion of the owner - will add a warning note to the export proto, and be sure to mention this in release notes as well.   

> leave a path open to the raw data import by making this field a `oneof`

As for a one-of in the RPC, I think that we can achieve the same with flat fields in the proto then just logically enforcing that only one of them is set? I've been a bit put off by one-of recently, but that's personal preference so happy to update it.

Comment (Roasbeef) [reply lnrpc/routerrpc/router.proto:348]: Great points @carlaKC, yeah we're only after #1 here, but that doesn't block off a future path doing #2 later. @joostjager  wasn't keyed into the discussions we'd had w.r.t our end goals internally, but hopefully that's now clear. 

Correct the current pair-wise data can leak information, but it's demonstrably less than the set of paths in their totality. 

> As for a one-of in the RPC, I think that we can achieve the same with flat fields in the proto then just logically enforcing that only one of them is set? I've been a bit put off by one-of recently, but that's personal preference so happy to update it.

Up to you really, no strong preference. FWIW, the latest versions of protos have made working w/ oneofs a bit easier with added helper methods. Though the naming of the fields are still rather ugly, at least when manipulating them in Go.

Comment (joostjager) [reply lnrpc/routerrpc/router.proto:348]: Yes, it is clear now. I was on the track of import type 2, 'distributed mission control'. For more public datasets it makes sense to use an aggregated format to obfuscate sensitive data.

File: lnrpc/routerrpc/router.proto [hunk 9]
```diff
@@ -61,6 +61,15 @@ service Router {
     rpc QueryMissionControl (QueryMissionControlRequest)
         returns (QueryMissionControlResponse);
 
+    /*
+    ImportMissionControl imports the state provided to the internal mission
+    control's state, using all results which are more recent than our existing
+    values. These values will only be imported in-memory, and will not be
+    persisted across restarts.
+    */
+    rpc ImportMissionControl (ImportMissionControlRequest)
```
Comment (cfromknecht) [inline lnrpc/routerrpc/router.proto:70]: nit: still need to add the `X` prefix here as well as the Request/Response. that way if we decide to move it out of experimental (or if a different design ultimately emerges) there won't be any naming collisions for the desired names

**Review by cfromknecht — COMMENTED** [review]
looks just about ready! last comment is the addition of the `X` prefix to the rpc method and messages

**Comment by joostjager** [comment]
Getting back to the privacy and space aspects: one option would be to only share successes. I think that priming with just the success amounts for each channel is already very effective. The failures will decay anyway. Users could choose to prune their exports before sharing.

**Review by Roasbeef — APPROVED** [review]
LGTM 🍫

**Comment by Roasbeef** [comment]
> Getting back to the privacy and space aspects: one option would be to only share successes. 

Yeah that may make sense for certain classes of user for this RPC, what's implemented right now doesn't preclude that.
