### PR TITLE
HTLC restoration

### LINKED ISSUE #1124: lnd crashes while syncing channels with panic: runtime error: invalid memory address or nil pointer dereference (segmentation fault)
### Background

After a clean stop of lnd (via lnrpc stop), and then restarting lnd, the node runs for a few minutes, but then crashes with the message and dump: 

```
2018-04-24 10:12:44.022 [INF] HSWC: ChannelLink(1e49eb55a996b60dde39686e36cdc7e3039bf8b49454093265367b6ba7a28bac:0) has exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8b07ff]

goroutine 40072 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).evaluateHTLCView(0xc420271200, 0xc421ef4030, 0xc42a2fd518, 0xc42a2fd510, 0x43, 0x1, 0xc421dd7f80)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2392 +0x1cf
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).computeView(0xc420271200, 0xc421ef4030, 0x1, 0xc421ef4030, 0xc42403b020, 0xc42a2fde80, 0xc42a2fd5d0, 0x429d69)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3267 +0x179
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).validateCommitmentSanity(0xc420271200, 0x14, 0x20, 0x1, 0x0, 0x40c32e, 0xc420271368)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3357 +0x116
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc420271200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2851 +0x224
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc433670780, 0x3, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1440 +0x9d
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc433670780)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:879 +0x6cf
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:391 +0x14e
```

### Your environment

* lnd 0.4.1-beta
* 4.13.0-1011-azure 14-Ubuntu SMP Thu Feb 15 16:15:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind 0.16.0

### Steps to reproduce

Did not happen more than once (yet)

I had 65 open channels, on restart, received the above message.  
Full log of the session is attached (logging level only at info).

[lndlog.seg.txt](https://github.com/lightningnetwork/lnd/files/1945042/lndlog.seg.txt)

### LINKED ISSUE #1247: panic: htlc index mismatch
### Background

crashes at startup with panic

### Your environment

0.4.1-beta commit=28b12116e42c83149b6c6b93b70d669a0702bd2d
Linux instance-1 4.13.0-1013 x86_64 x86_64 x86_64 GNU/Linux
bitcoind 0.16

https://pastebin.com/raw/8ChgyieB
and log
https://pastebin.com/raw/nPgFrk8u

### PR DESCRIPTION
**Pull request by halseth**
This PR attempts to fix a lingering bug within `channel.go` where the log counters would get out of sync with the HTLCs in the index after a restore.

Additionally, we remove some redundant restoration code to simplify the logic.

Fixes #1247 
(potentially also fixes #1124).

### CODE REVIEW

File: lnwallet/channel.go [hunk 1]
```diff
@@ -1340,10 +1340,10 @@ func NewLightningChannel(signer Signer, pCache PreimageCache,
 	// First, initialize the update logs with their current counter values
 	// from the local and remote commitments.
 	localUpdateLog := newUpdateLog(
-		localCommit.LocalLogIndex, localCommit.LocalHtlcIndex,
+		remoteCommit.LocalLogIndex, remoteCommit.LocalHtlcIndex,
```
Comment (Roasbeef) [inline lnwallet/channel.go]: Hmm, I see what you're getting at, but shouldn't this be the _remote pending commitent_? Our pending changes will be committed to that commit diff, not this "locked-in" commitment.

File: lnwallet/channel_test.go [hunk 2]
```diff
@@ -4906,3 +4908,203 @@ func TestNewBreachRetributionSkipsDustHtlcs(t *testing.T) {
...
+	aliceSig, aliceHtlcSigs, err = aliceChannel.SignNextCommitment()
+	if err != nil {
+		t.Fatalf("unable to sign commitment: %v", err)
+	}
+
+	// After Alice has signed this commitment, her local commitment will
+	// contain no HTLCs, her remote commitment will contain an HTLC with
+	// index 0, and the pending remote commitment (a signed remote
+	// commitment which is not AKCed yet) will contain an additional HTLC
+	// with index 1.
```
Comment (Roasbeef) [inline lnwallet/channel_test.go]: Ahh ok, it's clear now: the case where Alice sends another sig before Bob sends a sig to sync up her _local_ commit. In this case, Alice's latest log counter is actually what's on the remote commit.

Need to think a bit w.r.t if there are cases where this is actually _incorrect_...🤔

File: lnwallet/channel.go [hunk 3]
```diff
@@ -1692,27 +1692,17 @@ func (lc *LightningChannel) restoreStateLogs(
 	pendingRemoteCommitDiff *channeldb.CommitDiff,
 	pendingRemoteKeys *CommitmentKeyRing) error {
 
-	// For each HTLC within the local commitment, we add it to the relevant
-	// update logc based on if it's incoming vs outgoing. For any incoming
-	// HTLC's, we also re-add it to the rHashMap so we can quickly look it
-	// up.
+	// For each incoming HTLC within the local commitment, we add it to the
```
Comment (Roasbeef) [inline lnwallet/channel.go]: Makes sense, nice simplification 👍 

This may also have lend to redundant HTLCs being added to the log, which may cause issues when we go to decide which HTLCs are locked in and ready for forwarding.

File: lnwallet/channel.go [hunk 4]
```diff
@@ -1724,22 +1724,6 @@ func (lc *LightningChannel) restoreStateLogs(
 		return nil
 	}
 
-	// If we do have a dangling commitment for the remote party, then we'll
```
Comment (Roasbeef) [inline lnwallet/channel.go]: > The
reason we can safely remove this is to observe that a pending remote
commit is always created from a commitDiff which only contains updates
made by _us_, and thus only taken from the localUpdateLog

I'm not sure that this is _always_ the case, as it's possible to have a situation wherein we commit in coming HTLCs for them for the first time (as a side effect of our commitment).

Comment (Roasbeef) [reply lnwallet/channel.go]: Although, if we're committing these HTLCs to them for the first time, then it should already be in the remote log, as on start up we'll populate the remote log with incoming HTLCs on _our_ commitment.

File: lnwallet/channel.go (hunk 1 above)
Comment (halseth) [reply lnwallet/channel.go]: Using the remote commit should be fine, as all updates on the pending commit will be appended, not restored, and therefore increment the counters.

File: lnwallet/channel.go (hunk 3 above)
Comment (halseth) [reply lnwallet/channel.go]: I _think_ the code I removed would be just noops in all cases. I tried coming up with situations where they would actually add something, but was convinced that they will never by the explanation in the commit message. I might be wrong, but the commit is made by the assumption that it doesn't change behaviour.

File: lnwallet/channel.go (hunk 4 above)
Comment (halseth) [reply lnwallet/channel.go]: Yes, remote updates will be applied to our commit first, which will be used to populate the index. This commit should also not change behaviour.

File: lnwallet/channel.go (hunk 1 above)
Comment (Roasbeef) [reply lnwallet/channel.go]: Yep

File: lnwallet/channel.go (hunk 3 above)
Comment (Roasbeef) [reply lnwallet/channel.go]: Thought about this a bit over the past few days, and my current conclusion is that you are indeed correct. Also that these should have technically been no-ops, but could have times caused redundant elements in the linked list.
