### PR TITLE
invoice: refactor parsing data tagged fields and add unit tests

### LINKED ISSUE #516: listinvoices: can't list (invalid field length)
Doing some testing with ZAP I came across the following bug: https://github.com/LN-Zap/zap-desktop/issues/123

This seems to be an issue on the underlying lnd RPC as well:
```
$ lncli listinvoices
[lncli] rpc error: code = Unknown desc = unable to decode payment request: invalid field length
```

LND Invoice Log:
```
2017-12-24 11:14:13.737 [DBG] LTND: Adding invoice (*channeldb.Invoice)(0xc4200a9a20)({
 Memo: ([]uint8) (len=268 cap=288) {
  00000000  61 62 63 64 65 66 67 68  69 6a 6b 6c 6d 6e 6f 70  |abcdefghijklmnop|
  00000010  71 72 73 74 75 76 77 78  79 7a 61 62 63 64 65 66  |qrstuvwxyzabcdef|
  00000020  67 68 69 6a 6b 6c 6d 6e  6f 70 71 72 73 74 75 76  |ghijklmnopqrstuv|
  00000030  77 78 79 7a 61 62 63 64  65 66 67 68 69 6a 6b 6c  |wxyzabcdefghijkl|
  00000040  6d 6e 6f 70 71 72 73 74  75 76 77 78 79 7a 61 62  |mnopqrstuvwxyzab|
  00000050  63 64 65 66 67 68 69 6a  6b 6c 6d 6e 6f 70 71 72  |cdefghijklmnopqr|
  00000060  73 74 75 76 77 78 79 7a  61 62 63 64 65 66 67 68  |stuvwxyzabcdefgh|
  00000070  69 6a 6b 6c 6d 6e 6f 70  71 72 73 74 75 76 77 78  |ijklmnopqrstuvwx|
  00000080  79 7a 61 62 63 64 65 66  67 68 69 6a 6b 6c 6d 6e  |yzabcdefghijklmn|
  00000090  6f 70 71 72 73 61 62 63  64 65 66 67 68 69 6a 6b  |opqrsabcdefghijk|
  000000a0  6c 6d 6e 6f 70 71 72 73  74 75 76 77 78 79 7a 6b  |lmnopqrstuvwxyzk|
  000000b0  33 34 32 34 61 62 63 64  65 66 67 68 69 6a 6b 6c  |3424abcdefghijkl|
  000000c0  6d 6e 6f 70 71 72 73 74  75 76 77 78 79 7a 61 62  |mnopqrstuvwxyzab|
  000000d0  63 64 65 66 67 68 69 6a  6b 6c 6d 6e 6f 70 71 72  |cdefghijklmnopqr|
  000000e0  73 74 75 76 77 78 79 7a  32 33 33 74 75 76 77 78  |stuvwxyz233tuvwx|
  000000f0  79 7a 61 62 63 64 65 66  67 68 69 6a 6b 6c 6d 6e  |yzabcdefghijklmn|
  00000100  6f 70 71 72 73 74 75 76  77 78 79 7a              |opqrstuvwxyz|
 },
 Receipt: ([]uint8) <nil>,
 PaymentRequest: ([]uint8) (len=623 cap=640) {
  00000000  6c 6e 74 62 34 32 39 34  39 36 37 30 6e 31 70 64  |lntb42949670n1pd|
  00000010  72 6c 6c 79 39 70 70 35  7a 6d 76 70 76 75 35 76  |rlly9pp5zmvpvu5v|
  00000020  77 79 68 78 6a 6c 6c 64  6a 75 79 68 72 37 76 6a  |wyhxjlldjuyhr7vj|
  00000030  6c 35 68 39 76 7a 6d 37  67 77 6c 67 67 30 37 63  |l5h9vzm7gwlgg07c|
  00000040  76 74 6a 38 65 38 67 78  73 6d 71 71 64 64 64 76  |vtj8e8gxsmqqdddv|
  00000050  39 33 78 78 65 72 39 76  65 6e 6b 73 36 74 32 64  |93xxer9venks6t2d|
  00000060  64 6b 78 36 6d 6e 30 77  70 63 68 79 75 6d 35 77  |dkx6mn0wpchyum5w|
  00000070  34 6d 38 77 37 72 65 30  66 73 6b 79 63 6d 79 76  |4m8w7re0fskycmyv|
  00000080  34 6e 78 77 36 72 66 64  66 34 6b 63 6d 74 77 64  |4nxw6rfdf4kcmtwd|
  00000090  61 63 38 7a 75 6e 6e 77  33 36 68 76 61 6d 63 30  |ac8zunnw36hvamc0|
  000000a0  39 61 78 7a 63 6e 72 76  33 6a 6b 76 65 6d 67 64  |9axzcnrv3jkvemgd|
  000000b0  39 34 78 6b 6d 72 64 64  65 68 68 71 75 74 6a 77  |94xkmrddehhqutjw|
  000000c0  64 36 38 32 61 6e 68 30  70 75 68 35 63 74 7a 76  |d682anh0puh5ctzv|
  000000d0  64 6a 78 32 65 6e 38 64  70 35 6b 35 36 6d 76 64  |djx2en8dp5k56mvd|
  000000e0  34 68 78 37 75 72 33 77  66 65 68 67 61 74 6b 77  |4hx7ur3wfehgatkw|
  000000f0  61 75 38 6a 37 6e 70 76  66 33 6b 67 65 74 78 76  |au8j7npvf3kgetxv|
  00000100  61 35 78 6a 36 6e 74 64  33 6b 6b 75 6d 6d 73 77  |a5xj6ntd3kkummsw|
  00000110  39 65 38 78 61 72 34 77  65 6d 68 73 37 74 36 76  |9e8xar4wemhs7t6v|
  00000120  39 33 78 78 65 72 39 76  65 6e 6b 73 36 74 32 64  |93xxer9venks6t2d|
  00000130  64 6b 78 36 6d 6e 30 77  70 63 68 79 75 6d 70 76  |dkx6mn0wpchyumpv|
  00000140  66 33 6b 67 65 74 78 76  61 35 78 6a 36 6e 74 64  |f3kgetxva5xj6ntd|
  00000150  33 6b 6b 75 6d 6d 73 77  39 65 38 78 61 72 34 77  |3kkummsw9e8xar4w|
  00000160  65 6d 68 73 37 74 36 64  76 65 6e 67 76 33 35 76  |emhs7t6dvengv35v|
  00000170  39 33 78 78 65 72 39 76  65 6e 6b 73 36 74 32 64  |93xxer9venks6t2d|
  00000180  64 6b 78 36 6d 6e 30 77  70 63 68 79 75 6d 35 77  |dkx6mn0wpchyum5w|
  00000190  34 6d 38 77 37 72 65 30  66 73 6b 79 63 6d 79 76  |4m8w7re0fskycmyv|
  000001a0  34 6e 78 77 36 72 66 64  66 34 6b 63 6d 74 77 64  |4nxw6rfdf4kcmtwd|
  000001b0  61 63 38 7a 75 6e 6e 77  33 36 68 76 61 6d 63 30  |ac8zunnw36hvamc0|
  000001c0  39 61 72 79 76 65 6e 77  33 36 68 76 61 6d 63 30  |9aryvenw36hvamc0|
  000001d0  39 61 78 7a 63 6e 72 76  33 6a 6b 76 65 6d 67 64  |9axzcnrv3jkvemgd|
  000001e0  39 34 78 6b 6d 72 64 64  65 68 68 71 75 74 6a 77  |94xkmrddehhqutjw|
  000001f0  64 36 38 32 61 6e 68 30  70 75 68 35 63 71 7a 79  |d682anh0puh5cqzy|
  00000200  73 33 75 77 63 6b 78 6e  65 61 77 37 6c 79 6d 6c  |s3uwckxneaw7lyml|
  00000210  35 33 6c 61 71 7a 6c 70  35 36 7a 75 71 34 68 73  |53laqzlp56zuq4hs|
  00000220  37 36 64 64 75 38 67 6a  34 7a 79 39 38 6c 37 66  |76ddu8gj4zy98l7f|
  00000230  6a 63 37 77 73 30 32 6a  70 7a 74 35 33 79 76 35  |jc7ws02jpzt53yv5|
  00000240  77 68 65 65 79 72 6c 6a  6b 34 76 75 64 78 6d 36  |wheeyrljk4vudxm6|
  00000250  73 6a 73 30 63 39 7a 35  73 70 34 71 76 68 74 68  |sjs0c9z5sp4qvhth|
  00000260  32 72 66 36 70 70 79 67  71 38 66 72 6e 66 34     |2rf6ppygq8frnf4|
 },
 CreationDate: (time.Time) 2017-12-24 11:14:13.729410009 -0800 PST,
 SettleDate: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
 Terms: (channeldb.ContractTerm) {
  PaymentPreimage: ([32]uint8) (len=32 cap=32) {
   00000000  81 39 59 4c d7 e7 df a5  60 44 74 bb fd f7 01 b8  |.9YL....`Dt.....|
   00000010  fc 05 3a 1d ec 2d f7 c8  6d 2c a6 d2 c8 58 81 4f  |..:..-..m,...X.O|
  },
  Value: (lnwire.MilliSatoshi) 4294967000 mSAT,
  Settled: (bool) false
 }
})
```

### LINKED ISSUE #553: Validate invoice field lengths before parsing
Currently, not all the lengths of the `BOLT-11` invoice fields are properly sanity checked before attempting to parse them: 

* Fallback address: https://github.com/lightningnetwork/lnd/blob/63517a1eef477cee84a8c9cab036af5a3bd3ee60/zpay32/invoice.go#L712 Could crash if the address field is empty.
* Routing info: https://github.com/lightningnetwork/lnd/blob/63517a1eef477cee84a8c9cab036af5a3bd3ee60/zpay32/invoice.go#L777 Crashes if length is not exactly what we anticipate (multiple of 51 bytes).

### Steps to completion:

- [ ] Create test cases triggering the crashes/failures.
- [ ] Properly validate the lengths, and return error if it does not match what we expect.

### PR DESCRIPTION
**Pull request by wilmerpaulino**
This PR introduces the following changes:

- Refactor parsing each tagged field of an invoice into its own method.
- Remove duplicate code when parsing the timestamp.
- Sanity check parsing each tagged field. In this case, only: empty fallback address field and routing info field length not multiple of 51 bytes. Fixes #553.
- Properly parse the field data length. Fixes #516.
- Add unit tests for each parsed tagged field.

I think I covered all of the possible test input scenarios for parsing each tagged field, but let me know if there are any missing.

There's also a lot of overlap between `invoice_internal_test.go` and `invoice_test.go`. I'm not familiar with how we would go about simplifying that. Maybe someone with more Go knowledge could chime in here :)

### CODE REVIEW

File: zpay32/invoice_internal_test.go [hunk 1]
```diff
@@ -230,13 +296,510 @@ func TestParseTimestamp(t *testing.T) {
...
+		},
+		{
+			// The first byte is <= 3 bits long.
+			data:   []byte{0x1, 0x2},
+			valid:  true,
+			result: 34,
+		},
+		{
+			// The first byte is > 3 bits long.
+			data:   []byte{0xa, 0x0},
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: Awesome! Could you also include cases for the two extremes? (`{0x0, 0x0}` and `{0b11111, 0x11111}` I think)

File: zpay32/invoice_internal_test.go [hunk 2]
```diff
@@ -230,13 +296,510 @@ func TestParseTimestamp(t *testing.T) {
...
+		{
+			data:  []byte{},
+			valid: false, // empty data
+		},
+		{
+			data:  []byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
+			valid: false, // data too short, not 52 bytes
+		},
+		{
+			data:   []byte{0x0, 0x0, 0x0, 0x10, 0x4, 0x0, 0x18, 0x4, 0x0, 0x14, 0x3, 0x0, 0xe, 0x2, 0x0, 0x9, 0x0, 0x0, 0x0, 0x10, 0x4, 0x0, 0x18, 0x4, 0x0, 0x14, 0x3, 0x0, 0xe, 0x2, 0x0, 0x9, 0x0, 0x0, 0x0, 0x10, 0x4, 0x0, 0x18, 0x4, 0x0, 0x14, 0x3, 0x0, 0xe, 0x2, 0x0, 0x9, 0x0, 0x4, 0x1, 0x0},
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: instead of hardcoding the data slice here, could you extract it from the expected result? You should be able to use the `ConvertBits` method on the payment hash to get this data.

File: zpay32/invoice_internal_test.go [hunk 3]
```diff
@@ -230,13 +296,510 @@ func TestParseTimestamp(t *testing.T) {
...
+		valid  bool
+		result *string
+	}{
+		{
+			data:   []byte{},
+			valid:  true,
+			result: &testEmptyString,
+		},
+		{
+			data:   []byte{0xa, 0x1, 0x16, 0x6, 0xa, 0x18, 0xb, 0x13, 0xc, 0x14, 0x10, 0x6, 0x6, 0x1b, 0x1b, 0xe, 0xe, 0xd, 0x14, 0x16, 0x8, 0x19, 0xb, 0x12, 0x4, 0x1, 0x19, 0x17, 0xa, 0x1c, 0x3, 0x10, 0xd, 0x1d, 0x19, 0x7, 0x8, 0x1a, 0xb, 0xe, 0xc, 0x1c, 0x10, 0x7, 0x8, 0x1a, 0x3, 0x9, 0xe, 0xc, 0x10, 0x7, 0x0, 0x1c, 0x13, 0xf, 0xd, 0x9, 0x12, 0x16, 0x6, 0x1d, 0x0},
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: same, use the expected string -> bytes -> convert to base32. 

Or did you get this data slice from somewhere?

File: zpay32/invoice_internal_test.go [hunk 4]
```diff
@@ -230,13 +296,510 @@ func TestParseTimestamp(t *testing.T) {
...
+		{
+			data:  []byte{},
+			valid: false, // empty data
+		},
+		{
+			data:  []byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
+			valid: false, // data too short, not 53 bytes
+		},
+		{
+			data:   []byte{0x0, 0xf, 0x13, 0x11, 0xa, 0x1a, 0x17, 0x3, 0x7, 0xc, 0x5, 0x2, 0x1, 0x3, 0x8, 0x7, 0x8, 0x10, 0xc, 0x19, 0x2, 0x18, 0x18, 0x17, 0xf, 0x1a, 0x8, 0x9, 0x1d, 0x0, 0x0, 0x17, 0xd, 0x19, 0xa, 0x1d, 0x12, 0x1e, 0x11, 0xf, 0x4, 0x8, 0xf, 0xd, 0x1c, 0x3, 0x1c, 0x13, 0x9, 0x17, 0xc, 0x1a, 0x1a},
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: same comment on all these.

File: zpay32/invoice.go [hunk 5]
```diff
@@ -849,6 +853,11 @@ func parseRoutingInfo(data []byte) ([]ExtraRoutingInfo, error) {
 		return nil, err
 	}
 
+	if len(base256Data)%routingInfoLen != 0 {
```
[the remark this answers is not in the document]
Comment (wilmerpaulino) [reply zpay32/invoice.go]: I kept the check up there because we can avoid reading the data if it's not a multiple of the required length. For example, if we're reading two routing infos, but the second one is incomplete, we would avoid reading the first completely.

**Comment by wilmerpaulino** [comment]
Rebased to master and addressed comments.

Let me know if I missed anything!

File: zpay32/invoice_internal_test.go [hunk 6]
```diff
@@ -1,11 +1,83 @@
...
 	"github.com/lightningnetwork/lnd/lnwire"
+	"github.com/lightningnetwork/lnd/zpay32/testutil"
+	"github.com/roasbeef/btcd/btcec"
+	"github.com/roasbeef/btcd/chaincfg"
+	"github.com/roasbeef/btcutil"
+	"github.com/roasbeef/btcutil/bech32"
 )
 
+var (
+	// Placed here and not in testutil to avoid circular dependencies.
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: How does it become a circular dependency?

File: zpay32/invoice_internal_test.go [hunk 7]
```diff
@@ -230,13 +302,504 @@ func TestParseTimestamp(t *testing.T) {
...
+		},
+		{
+			data:   []byte{0x0, 0x0},
+			valid:  true,
+			result: 0,
+		},
+		{
+			data:   []byte{0xf, 0xf},
+			valid:  true,
+			result: 495,
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: max value is `{0x1F, 0x1F} == {0b11111, 0b11111}` since we are using `base32`. This data is actually invalid :P

File: zpay32/invoice_internal_test.go [hunk 8]
```diff
@@ -230,13 +302,504 @@ func TestParseTimestamp(t *testing.T) {
...
+			result: nil, // data too short, not 52 bytes
+		},
+		{
+			data:   testutil.TestPaymentHashData,
+			valid:  true,
+			result: &testutil.TestPaymentHash,
+		},
+		{
+			// This test is the same as above, but we append an
+			// extra byte to the data to cause a failure.
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: update comments to reflect that we are skipping unknown lenghts.

File: zpay32/invoice_internal_test.go [hunk 9]
```diff
@@ -230,13 +302,504 @@ func TestParseTimestamp(t *testing.T) {
...
+	}{
+		{
+			data:   []byte{},
+			valid:  true,
+			result: nil, // empty data
+		},
+		{
+			data:   []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
+			valid:  true,
+			result: nil, // data too short, not 53 bytes
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: update comment

File: zpay32/invoice_internal_test.go [hunk 10]
```diff
@@ -230,13 +302,504 @@ func TestParseTimestamp(t *testing.T) {
...
+		},
+		{
+			data:   testutil.TestPubKeyData,
+			valid:  true,
+			result: testutil.TestPubKey,
+		},
+		{
+			// This test is the same as above, but we append an
+			// extra byte to the data to cause a failure.
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: update comments

File: zpay32/invoice_internal_test.go [hunk 11]
```diff
@@ -230,13 +302,504 @@ func TestParseTimestamp(t *testing.T) {
...
+	}{
+		{
+			data:   []byte{},
+			valid:  true,
+			result: nil, // empty data
+		},
+		{
+			data:   []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
+			valid:  true,
+			result: nil, // data too short, not 52 bytes
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: update comment

File: zpay32/invoice_internal_test.go [hunk 12]
```diff
@@ -230,13 +302,504 @@ func TestParseTimestamp(t *testing.T) {
...
+
+	tests := []struct {
+		data   []byte
+		valid  bool
+		result *[32]byte
+	}{
+		{
+			data:   []byte{},
+			valid:  true,
+			result: nil, // empty data
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: same for all these, update comments

File: zpay32/testutil/testutil.go [hunk 13]
```diff
@@ -0,0 +1,134 @@
+package testutil
```
Comment (halseth) [inline zpay32/testutil/testutil.go]: I think this should have a name that ends with `_test.go` to avoid cluttering the normal API.

File: zpay32/invoice_internal_test.go [hunk 14]
```diff
@@ -1,11 +1,83 @@
...
+			CltvExpDelta:              4,
+		},
+	}
+
+	// Must be initialized in init().
+	testSingleHopData []byte
+	testDoubleHopData []byte
+)
+
+func init() {
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: Can the init be moved to `testutil`?

File: zpay32/testutil/testutil.go (hunk 13 above)
Comment (halseth) [reply zpay32/testutil/testutil.go]: Also, I don't think you need a new folder just for this file.

**Comment by wilmerpaulino** [comment]
Rebased to master and addressed comments.

File: zpay32/invoice_internal_test.go [hunk 15]
```diff
@@ -1,11 +1,149 @@
...
 	"github.com/lightningnetwork/lnd/lnwire"
+	"github.com/ltcsuite/ltcd/chaincfg/chainhash"
+	"github.com/roasbeef/btcd/btcec"
+	"github.com/roasbeef/btcd/chaincfg"
+	"github.com/roasbeef/btcutil"
+	"github.com/roasbeef/btcutil/bech32"
 )
 
+var (
+	testMillisat24BTC    = lnwire.MilliSatoshi(2400000000000)
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: Can you move the test data back to where it was? Since they are in the same package now, it should be accessible from there, and we'll minimize the diff :)

File: zpay32/invoice_test.go [hunk 16]
```diff
@@ -1,68 +1,12 @@
-package zpay32_test
+package zpay32
```
Comment (halseth) [inline zpay32/invoice_test.go]: Add a comment under the package name to explain why it is not `zpay32_test` (to share testdata with `internal–test`)

File: zpay32/invoice_internal_test.go [hunk 17]
```diff
@@ -230,13 +368,572 @@ func TestParseTimestamp(t *testing.T) {
...
 		}
+		if test.valid {
+			if err := compareRoutingInfos(test.result, routingInfo); err != nil {
+				t.Fatalf("test %d failed decoding routing info: %v", i, err)
+			}
+		}
+	}
+}
+
+func compareInvoices(expected, actual *Invoice) error {
```
Comment (halseth) [inline zpay32/invoice_internal_test.go]: these methods can also be moved back.

**Comment by wilmerpaulino** [comment]
Should be good to go now :)
