### PR TITLE
Wire protocol errors

### LINKED ISSUE #661: Channel opening failure may disclose sensitive information about remote host
Trying to open a channel with a remote node whose disk is full returns too much information:

```
$ lncli openchannel 02869ea4a3848c05f9d1d0f145298a24c0e0ce54cce61281e91f362dce130180ce 150000
[lncli] rpc error: code = Code(219) desc = write /var/lib/lnd/bitcoin/testnet/wallet.db: no space left on device
```

lnd.log (local node):

```
2018-01-24 00:35:30.596 [INF] SRVR: Attempting to send msgs 1 to: 02869ea4a3848c05f9d1d0f145298a24c0e0ce54cce61281e91f362dce130180ce
2018-01-24 00:35:30.626 [ERR] FNDG: Received funding error from 02869ea4a3848c05f9d1d0f145298a24c0e0ce54cce61281e91f362dce130180ce: write /var/lib/lnd/bitcoin/testnet/wallet.db: no space left on device
2018-01-24 00:35:30.626 [INF] FNDG: Cancelling funding reservation for node_key=02869ea4a3848c05f9d1d0f145298a24c0e0ce54cce61281e91f362dce130180ce, chan_id=87e4c22e88951e46c001590e6ef12dd344adf24a934c4efc1b0e8610ce754499
2018-01-24 00:35:30.627 [ERR] RPCS: unable to open channel to identityPub(02869ea4a3848c05f9d1d0f145298a24c0e0ce54cce61281e91f362dce130180ce) nor peerID(0): rpc error: code = Code(219) desc = write /var/lib/lnd/bitcoin/testnet/wallet.db: no space left on device
```

### PR DESCRIPTION
**Pull request by halseth**
This PR changes the `failFundingFlow` method to accept an error, which will
only be sent to the remote the peer if it is among the errors found in
`ReservationErrors` or `ErrorCode`. This is done to ensure we don't send
errors that contain information we don't want to leak.

Fixes #661.

### CODE REVIEW

File: lnwallet/errors.go [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+	"github.com/roasbeef/btcd/chaincfg/chainhash"
+	"github.com/roasbeef/btcutil"
+)
+
+// Reservation error wraps certain errors returned during channel reservation
+// that can be sent across the wire to the remote peer. Errors not being
+// ReservationErrors will not be sent to the remote in case of a failed channel
+// reservation, as they may contain private information.
+type ReservationError struct {
+	error
```
Comment (Roasbeef) [inline lnwallet/errors.go]: Why the embedding here? It's an interface, so all we need to do is ensure that the structs implement the `Error() string` method.

Comment (Roasbeef) [reply lnwallet/errors.go]: So this can just be a `string` field minimally. Though in a way this _is_ less code by just embedding an error...

File: fundingmanager.go [hunk 2]
```diff
@@ -689,21 +689,36 @@ func (f *fundingManager) CancelPeerReservations(nodePub [33]byte) {
 }
 
 // failFundingFlow will fail the active funding flow with the target peer,
-// identified by its unique temporary channel ID. This method is send an error
-// to the remote peer, and also remove the reservation from our set of pending
-// reservations.
+// identified by its unique temporary channel ID. This method will send an
+// error to the remote peer, and also remove the reservation from our set of
```
Comment (Roasbeef) [inline fundingmanager.go]: Typo in the commit message: only be senbt -> only be sent

File: fundingmanager.go [hunk 3]
```diff
@@ -689,21 +689,36 @@ func (f *fundingManager) CancelPeerReservations(nodePub [33]byte) {
...
+	var msg lnwire.ErrorData
+	switch fundingErr.(type) {
+
+	// Let the actual error message be sent to the remote.
+	case lnwire.ErrorCode, lnwallet.ReservationError:
+		msg = []byte(fundingErr.Error())
+
+	// We just send a generic error.
+	default:
+		msg = []byte("error")
```
Comment (Roasbeef) [inline fundingmanager.go]: Maybe add a _bit_ more detail, something like: "failing funding flow due to internal error. Possibly we should also log the error in this case, to ease debugging in the future.

**Comment by Roasbeef** [comment]
Updated the PR description to note that this fixes #661.

File: lnwallet/errors.go (hunk 1 above)
Comment (halseth) [reply lnwallet/errors.go]: I embedded the error such that they all can be checked whether they are of the type `ReservationError`, centralizing the list of "acceptable" reservation errors. It also embed the error messages containing non-constant arguments (which as you mention can just as easily be done with a `string` field).

Another way to do this would be to make it more like to the `routing` errors, where the `ReservationError` contains an error code maybe, but not sure if there's an easy way to have the dynamic arguments (minimum amounts etc) this way?

File: fundingmanager.go (hunk 3 above)
Comment (halseth) [reply fundingmanager.go]: Fixed.

The original error is logged below.

File: fundingmanager.go (hunk 2 above)
Comment (halseth) [reply fundingmanager.go]: fixed
