### PR TITLE
multi: update listsweeps to allow sweeps that are not in ListTransactions

### LINKED ISSUE #4748: Sweep listing returns transaction ids that never confirmed
### Background

When performing a `ListSweeps` call in the wallet rpc service, transaction ids that never confirmed are returned in the result due to alternative transaction formations

This also causes errors when attempting to list out transaction details with `lncli wallet listsweeps --verbose` because these not-confirmed transactions are absent from internal records.

### Your environment

* LND 0.11.1

### Steps to reproduce

1. Call `ListSweeps` on a node where a sweep was replaced

### Expected behavior

Only sweeps that were confirmed or potentially will confirm should be returned. An error should not be returned for verbose mode.

### Actual behavior

Ids are returned of missing transactions and errors are returned with the verbose option on the CLI and in the API

### Workaround

Instead of using the verbose option, use the non-verbose mode and cross reference with the chain transactions list

### PR DESCRIPTION
**Pull request by carlaKC**
Fixes #4748

### CODE REVIEW

File: lnrpc/walletrpc/walletkit_server.go [hunk 1]
```diff
@@ -822,16 +825,9 @@ func (w *WalletKit) ListSweeps(ctx context.Context,
...
-	// wallet.
-	if len(sweepTxDetails) != len(txids) {
-		return nil, fmt.Errorf("not all sweeps found by list "+
-			"transactions: %v, %v", len(sweepTxDetails), len(txids))
-	}
-
 	return &ListSweepsResponse{
 		Sweeps: &ListSweepsResponse_TransactionDetails{
-			TransactionDetails: lnrpc.RPCTransactionDetails(transactions),
+			TransactionDetails: lnrpc.RPCTransactionDetails(sweepTxDetails),
```
Comment (bhandras) [inline lnrpc/walletrpc/walletkit_server.go:830]: I think bot verbose and non-verbose response should be filtered, such that they are consistent (returning the same sweeps but with different level of detail). The linked bug seems to recommend the same. WDYT?

Comment (carlaKC) [reply lnrpc/walletrpc/walletkit_server.go:830]: Originally the point of having the non-verbose output was to save us the call to list all of our transactions from the wallet, which was my thinking in still returning the full list (incl rbf). 

I also think there can be a use-case for knowing the txids of sweeps that never made it to chain (eg, the case where you have alerting on every tx your node broadcasts, you'd want to be able to check lnd's sweeps to whitelist the tx).

But I do agree it's confusing to have different output for verbose/not. Could add a `IncludeDropped` option which just returns all the sweeps when verbose is false, and does not work if verbose is true so that you can still get those rbf-ed txids if you need them? Unsure about it tbh.

Comment (bhandras) [reply lnrpc/walletrpc/walletkit_server.go:830]: IMHO simplifying and only including sweeps that made it to the chain would make more sense. Having the `IncludeDropped` smells like something users probably ain't going to need (although a good generalization idea).

Comment (carlaKC) [reply lnrpc/walletrpc/walletkit_server.go:830]: Yeah SGTM, keep it consistent for now and then add the invisible/rbfed sweeps if anybody requires them. Will make a note in the proto that these sweeps aren't listed.

File: lntest/itest/lnd_test.go [hunk 2]
```diff
@@ -4572,32 +4567,56 @@ func assertReports(ctxb context.Context, t *harnessTest,
...
-			Verbose: false,
+			Verbose: verbose,
 		})
-	if err != nil {
-		return fmt.Errorf("list sweeps error: %v", err)
+	require.NoError(t, err)
+
+	var found bool
+	if verbose {
+		found = findSweepInDetails(t, sweep, sweepResp)
```
Comment (bhandras) [inline lntest/itest/lnd_test.go:4583]: You could extend these checks such that:
- if verbose: require that sweep is found in details but not found in txids
- otherwise: require that sweep is found in txids, but not found in details

**Review by bhandras — APPROVED** [review]
LGTM :waffle:

File: lntest/itest/lnd_test.go [hunk 3]
```diff
@@ -4572,32 +4567,56 @@ func assertReports(ctxb context.Context, t *harnessTest,
...
 	// List all sweeps that alice's node had broadcast.
 	ctx, _ = context.WithTimeout(ctx, defaultTimeout)
 	sweepResp, err := node.WalletKitClient.ListSweeps(
 		ctx, &walletrpc.ListSweepsRequest{
-			Verbose: false,
+			Verbose: verbose,
 		})
-	if err != nil {
-		return fmt.Errorf("list sweeps error: %v", err)
+	require.NoError(t, err)
```
Comment (guggero) [inline lntest/itest/lnd_test.go:4579]: micro nit: closing parentheses on new line above (from `ListSweeps`).

File: lntest/itest/lnd_test.go [hunk 4]
```diff
@@ -4572,32 +4567,56 @@ func assertReports(ctxb context.Context, t *harnessTest,
 }
 
 // findSweep looks up a sweep in a nodes list of broadcast sweeps.
-func findSweep(ctx context.Context, node *lntest.HarnessNode,
-	sweep *chainhash.Hash) error {
+func findSweep(ctx context.Context, t *testing.T, node *lntest.HarnessNode,
```
Comment (guggero) [inline lntest/itest/lnd_test.go:4570]: nit: now that it's asserting, should we rename to `assertSweepFound` or something similar?

File: lntest/itest/lnd_test.go [hunk 5]
```diff
@@ -4572,32 +4567,56 @@ func assertReports(ctxb context.Context, t *harnessTest,
...
+		}
+	}
+
+	return false
+}
+
+func findSweepInDetails(t *testing.T, sweepTxid string,
+	sweepResp *walletrpc.ListSweepsResponse) bool {
+
+	sweepDetails, ok := sweepResp.Sweeps.(*walletrpc.ListSweepsResponse_TransactionDetails)
```
Comment (guggero) [inline lntest/itest/lnd_test.go:4610]: nit: can use `sweepResp.GetTransactionIds()` and non-nil assertion to shorten this.

**Review by guggero — APPROVED** [review]
LGTM, only nits :sweat_smile:
