### PR TITLE
Change wallet password

### LINKED ISSUE #607: [Request] Change encryptwallet password
Change encryptwallet password:

1. Ask for "Current password:" then "New Password:" and "Confirm New Password:"
2. If Current password is blank, use the hardcoded password for `--noencryptwallet`
3. If New Password is blank, or it matches the hard coded password for `--noencryptwallet`, fail. (Also I believe under 8 characters fails currently, which is fine)

- This will allow people to encrypt wallets with --noencryptwallet used to generate.
- This will allow people to update compromised passwords.
- This will not allow people to switch from an encryption password to a --noencryptwallet state.

### PR DESCRIPTION
**Pull request by wpaulino**
Fixes #607.

This PR introduces the following changes:

* Updates the `lnwallet.WalletController` interface and `BtcWallet` to handle changing the wallet's private and public passwords.
* Adds RPC call for `ChangePassword`.
* Adds `changepassword` command to `lncli`. The wallet must be unlocked first.

### CODE REVIEW

File: rpcserver.go [hunk 1]
```diff
@@ -1201,6 +1201,46 @@ func (r *rpcServer) ListPeers(ctx context.Context,
...
+			return nil, err
+		}
+	}
+
+	// Check if the current password provided is blank. This most likely
+	// means the wallet came from a --noencryptwallet state and the user
+	// does not know of the default password. In that case, we set it to the
+	// default.
+	if len(in.CurrentPassword) == 0 {
+		in.CurrentPassword = defaultWalletPw
```
Comment (halseth) [inline rpcserver.go]: To avoid the breaking change, you can have one private and one public variable, and set them to "private" and "hello" here.

File: cmd/lncli/commands.go [hunk 2]
```diff
@@ -809,6 +809,55 @@ func unlock(ctx *cli.Context) error {
 	return nil
 }
 
+var changePasswordCommand = cli.Command{
+	Name:   "changepassword",
+	Usage:  "change the encrypted wallet's password",
```
Comment (halseth) [inline cmd/lncli/commands.go]: Add "wallet must be unlocked".

**Comment by wilmerpaulino** [comment]
Rebased to master and addressed comments.

File: lnd.go [hunk 3]
```diff
@@ -191,8 +194,8 @@ func lndMain() error {
 	// We wait until the user provides a password over RPC. In case lnd is
 	// started with the --noencryptwallet flag, we use the default password
 	// "hello" for wallet encryption.
```
Comment (halseth) [inline lnd.go]: Comment can be changed to just somehting like ".... we use default passwords for wallet encyption"

File: rpcserver.go [hunk 4]
```diff
@@ -1120,6 +1121,52 @@ func (r *rpcServer) ListPeers(ctx context.Context,
...
+	}
+
+	privateWalletPw := in.CurrentPassword
+	publicWalletPw := in.CurrentPassword
+
+	// Check if the current password provided is blank or is the default
+	// wallet password. This most likely means the wallet came from a
+	// --noencryptwallet state. In that case, we set the defaults.
+	if len(in.CurrentPassword) == 0 ||
+		bytes.Compare(in.CurrentPassword, defaultPrivateWalletPw) == 0 {
```
Comment (halseth) [inline rpcserver.go]: I don't think we can check against the private password. Let's say we either remove the length requirement, or make the default password longer than 8 characters. Then a user choosing the default password as her password (without using `--noencryptwallet`), will not be able to change it.

File: rpcserver.go [hunk 5]
```diff
@@ -1120,6 +1121,52 @@ func (r *rpcServer) ListPeers(ctx context.Context,
...
+	}
+
+	// Grab the loaded wallet from the server and change its private and
+	// public passwords to the new password provided.
+	w := r.server.cc.wallet
+	err := w.ChangePrivatePassphrase(privateWalletPw, in.NewPassword)
+	if err != nil {
+		return nil, err
+	}
+	err = w.ChangePublicPassphrase(publicWalletPw, in.NewPassword)
```
Comment (halseth) [inline rpcserver.go]: This might be a bit dangerous if changing the private passphrase succeeds, but not the public passphrase. Not sure if there's an easy way to make it atomic though 🤔

**Comment by cfromknecht** [comment]
What's the status of this PR? This is def a useful feature, is now a good time to do more review?

**Comment by wpaulino** [comment]
I can address the nits and rebase, but @halseth's comment regarding atomic passphrase changes is a bit more non-trivial.

One approach would be to backup the wallet before attempting the change and revert if an error occurs. We don't have wallet backups yet though (I think?).

**Comment by Roasbeef** [comment]
The public passphrase is actually just a repeat of the private passphrase. It's only distinct when wallet encryption is turned off.

**Comment by cfromknecht** [comment]
Right, though I think the atomicity thing is still a concern as it could leave the db in a weird state. Easiest solution be to add a method to btcwallet that updates both at the same time. Here is the method that changes the public password https://github.com/Roasbeef/btcwallet/blob/master/wallet/wallet.go#L774
I think this would only require calling `Manager.ChangePassphrase` with both `true` and `false`?

**Comment by halseth** [comment]
Yeh, I think that would work 👍 Any error should then roll back all db changes.

File: rpcserver.go (hunk 5 above)
Comment (wpaulino) [reply rpcserver.go]: Fixed.

File: rpcserver.go (hunk 4 above)
Comment (wpaulino) [reply rpcserver.go]: Fixed.

**Comment by wpaulino** [comment]
Pushed out a new version that also takes into account the macaroon root key store.

File: cmd/lncli/commands.go [hunk 6]
```diff
@@ -1289,6 +1289,61 @@ func unlock(ctx *cli.Context) error {
...
+	}
+	fmt.Println()
+
+	if !bytes.Equal(new, confirm) {
+		return fmt.Errorf("passwords don't match")
+	}
+
+	req := &lnrpc.ChangePasswordRequest{
+		CurrentPassword: current,
+		NewPassword:     new,
```
Comment (cfromknecht) [inline cmd/lncli/commands.go]: nit: use variable name that isn't a keyword

File: macaroons/store.go [hunk 7]
```diff
@@ -118,6 +122,77 @@ func (r *RootKeyStorage) CreateUnlock(password *[]byte) error {
...
+		err := oldEncKey.Unmarshal(dbKey)
+		if err != nil {
+			return err
+		}
+
+		err = oldEncKey.DeriveKey(&old)
+		if err != nil {
+			return err
+		}
+
```
Comment (cfromknecht) [inline macaroons/store.go]: after this method returns, we want to clear this secret key from memory using `defer oldEncKey.Zero()`

File: macaroons/store.go [hunk 8]
```diff
@@ -118,6 +122,77 @@ func (r *RootKeyStorage) CreateUnlock(password *[]byte) error {
...
+		// Finally, we can update our database to store the new
+		// encryption key.
+		err = bucket.Put(encryptedKeyID, newEncKey.Marshal())
+		if err != nil {
+			return err
+		}
+
```
Comment (cfromknecht) [inline macaroons/store.go]: if the previous `encKey` is not-nil, we should zero it immediately before overwriting it with the new one

File: lnwallet/interface.go [hunk 9]
```diff
@@ -211,6 +211,11 @@ type WalletController interface {
 	// which could be e.g. btcd, bitcoind, neutrino, or another consensus
 	// service.
 	BackEnd() string
+
+	// ChangePassphrases modifies the public and private passphrase of the
+	// vallet implementation.
```
Comment (halseth) [inline lnwallet/interface.go]: s/vallet/wallet

File: cmd/lncli/commands.go [hunk 10]
```diff
@@ -1289,6 +1289,61 @@ func unlock(ctx *cli.Context) error {
...
+	fmt.Println()
+
+	fmt.Printf("Confirm new wallet password: ")
+	confirm, err := terminal.ReadPassword(int(syscall.Stdin))
+	if err != nil {
+		return err
+	}
+	fmt.Println()
+
+	if !bytes.Equal(new, confirm) {
```
Comment (halseth) [inline cmd/lncli/commands.go]: Do we enforce minimum 8 chars anywhere?

File: walletunlocker/service.go [hunk 11]
```diff
@@ -56,6 +56,7 @@ func New(authSvc *macaroons.Service, chainDir string,
 		UnlockPasswords: make(chan []byte, 1),
 		chainDir:        chainDir,
 		netParams:       params,
+		authSvc:         authSvc,
```
Comment (halseth) [inline walletunlocker/service.go]: Used for anything?

File: cmd/lncli/commands.go (hunk 6 above)
Comment (wpaulino) [reply cmd/lncli/commands.go]: Fixed.

File: macaroons/store.go (hunk 7 above)
Comment (wpaulino) [reply macaroons/store.go]: Fixed.

File: macaroons/store.go (hunk 8 above)
Comment (wpaulino) [reply macaroons/store.go]: Fixed.

File: lnwallet/interface.go (hunk 9 above)
Comment (wpaulino) [reply lnwallet/interface.go]: Fixed.

File: cmd/lncli/commands.go (hunk 10 above)
Comment (wpaulino) [reply cmd/lncli/commands.go]: The 8 character minimum is enforced at the RPC level.

File: walletunlocker/service.go (hunk 11 above)
Comment (wpaulino) [reply walletunlocker/service.go]: `authSvc` is used in `InitWallet` and `UnlockWallet` to create/unlock the macaroon database. Looks like it was just forgot to be set.

**Comment by wpaulino** [comment]
@cfromknecht Regenerating the macaroon files seemed like a good solution, but I realized that if the encryption key change fails, then the new macaroon files would just be regenerated with the old encryption key.

Also discussed with @halseth the possibility of moving the `ChangePassword` RPC to the `WalletUnlocker`. It would indeed be nice to have all the password related functionality under the `WalletUnlocker` service, but by doing so we'd run into some issues with scoping. We could leave it as is for now as there are future plans to integrate the two different RPC services into one.

File: walletunlocker/service.go (hunk 11 above)
Comment (halseth) [reply walletunlocker/service.go]: So this means the macaroon database was not really encrypted before? 🤔

**Comment by halseth** [comment]
If you delete the macaroons, then they would be regenerated with the new passphrase at next startup, right?

**Comment by wpaulino** [comment]
Yeah, but then we'd have to restart the daemon. If we send any other RPC requests after the passphrase change, authentication would fail.

**Comment by Roasbeef** [comment]
So where are we with this? Seems like we need to extend `btcwallet` to be able to atomically update both passwords at once?

File: lnrpc/rpc.proto [hunk 12]
```diff
@@ -141,7 +141,24 @@ message UnlockWalletRequest {
...
 message UnlockWalletResponse {}
 
+message ChangePasswordRequest {
+    bytes current_password = 1;
+    bytes new_password = 2;
+}
+message ChangePasswordResponse {}
+
 service Lightning {
+    /** lncli: `changepassword`
```
Comment (Roasbeef) [inline lnrpc/rpc.proto]: A bit odd that this new method isn't on the `WalletUnlocker` service itself. This may be a worthy follow up, but would require us to _always_ run the unlocker service as an active RPC server. If we end up doing this, then we can also add an option to actively lock/unlock the wallet. This may be attractive for "box" type nodes that don't frequently forward, and only exist in order to carry out payments sourced from end end user.

File: macaroons/store.go [hunk 13]
```diff
@@ -118,6 +122,77 @@ func (r *RootKeyStorage) CreateUnlock(password *[]byte) error {
...
+			if err != nil {
+				return err
+			}
+
+			encrypted, err := newEncKey.Encrypt(decrypted)
+			if err != nil {
+				return err
+			}
+
+			bucket.Put(k, encrypted)
```
Comment (Roasbeef) [inline macaroons/store.go]: Ignoring the error value here.

File: rpcserver.go [hunk 14]
```diff
@@ -1302,6 +1306,48 @@ func (r *rpcServer) ListPeers(ctx context.Context,
...
+	// wallet. This will be done atomically in order to prevent one
+	// passphrase change from being successful and not the other.
+	err := r.server.cc.wallet.ChangePassphrases(
+		publicPw, in.NewPassword, privatePw, in.NewPassword,
+	)
+	if err != nil {
+		return nil, fmt.Errorf("unable to change password: %v", err)
+	}
+
+	// We'll also need to update the encryption key to our macaroons
```
Comment (Roasbeef) [inline rpcserver.go]: What happens here if we change the password, but then crash? In this case, the macaroons would still be encrypted under the prior password. One way to resolve this would be to mark the macaroon encryption state as "pending change". Upon restart, if we detect in this state, then we can try to decrypt under the new passphrase, and if not, we'd rotate over to the new passphrase.

Comment (wpaulino) [reply rpcserver.go]: I like this idea! This helped me come up with a potential solution:

Rather than changing the macaroon encryption key, we can create an empty file `.regenerate_macaroons` (or something similar) within the `lnddir` and check if it exists while the daemon is starting. If it does, we can delete the previous `macaroon.db` and `*.macaroon` files, which is safe, and recreate the new `macaroon.db` and `*.macaroon` files using the new password.

This would also allow us to move the `ChangePassword` RPC into the `WalletUnlocker` service easily.

Thoughts?

Comment (wpaulino) [reply rpcserver.go]: The above can be simplified to deleting the macaroons whenever a password change happens. We can then move the `ChangePassword` RPC into the `WalletUnlocker` and generate the macaroon database and files with the new password on startup.

File: lnrpc/rpc.proto (hunk 12 above)
Comment (wpaulino) [reply lnrpc/rpc.proto]: Fixed.

File: macaroons/store.go (hunk 13 above)
Comment (wpaulino) [reply macaroons/store.go]: This function was removed since it's no longer needed.

File: rpcserver.go (hunk 14 above)
Comment (wpaulino) [reply rpcserver.go]: Fixed.

File: lnwallet/btcwallet/btcwallet.go [hunk 15]
```diff
@@ -742,3 +742,13 @@ func (b *BtcWallet) IsSynced() (bool, int64, error) {
 	minus24Hours := time.Now().Add(-2 * time.Hour)
 	return !blockHeader.Timestamp.Before(minus24Hours), bestTimestamp, nil
 }
+
+// ChangePassphrases modifies the public and private passphrase of the Bitcoin
+// wallet.
+func (b *BtcWallet) ChangePassphrases(publicOld, publicNew, privateOld,
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply lnwallet/btcwallet/btcwallet.go]: Fixed.

File: walletunlocker/service.go [hunk 16]
```diff
@@ -236,3 +244,82 @@ func (u *UnlockerService) UnlockWallet(ctx context.Context,
...
+
+	// If the current password is blank, we'll assume the user is coming
+	// from a --noencryptwallet state, so we'll use the default passwords.
+	if len(in.CurrentPassword) == 0 {
+		publicPw = lnwallet.DefaultPublicPassphrase
+		privatePw = lnwallet.DefaultPrivatePassphrase
+	}
+
+	// Require the new password to have a minimum length of 8 characters.
+	if len(in.NewPassword) < 8 {
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply walletunlocker/service.go]: Fixed.

File: walletunlocker/service.go [hunk 17]
```diff
@@ -236,3 +244,82 @@ func (u *UnlockerService) UnlockWallet(ctx context.Context,
...
+
+	if !walletExists {
+		return nil, errors.New("wallet not found")
+	}
+
+	publicPw := in.CurrentPassword
+	privatePw := in.CurrentPassword
+
+	// Make sure the new password is not the same as the current.
+	if bytes.Equal(in.CurrentPassword, in.NewPassword) {
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply walletunlocker/service.go]: Fixed.

File: walletunlocker/service.go [hunk 18]
```diff
@@ -236,3 +244,82 @@ func (u *UnlockerService) UnlockWallet(ctx context.Context,
...
+
+	// Require the new password to have a minimum length of 8 characters.
+	if len(in.NewPassword) < 8 {
+		return nil, errors.New("new password must have at least 8 " +
+			"characters")
+	}
+
+	// We default to removing the macaroon files so that they're
+	// re-generated at startup using the new password.
+	for _, file := range u.macaroonFiles {
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply walletunlocker/service.go]: Fixed.

File: lnrpc/rpc.proto [hunk 19]
```diff
@@ -141,6 +152,12 @@ message UnlockWalletRequest {
 }
 message UnlockWalletResponse {}
 
+message ChangePasswordRequest {
+    bytes current_password = 1;
```
Comment (halseth) [inline lnrpc/rpc.proto]: Need comments.

File: walletunlocker/service.go [hunk 20]
```diff
@@ -236,3 +241,88 @@ func (u *UnlockerService) UnlockWallet(ctx context.Context,
...
+	err = w.ChangePassphrases(
+		publicPw, in.NewPassword, privatePw, in.NewPassword,
+	)
+	if err != nil {
+		return nil, fmt.Errorf("unable to change wallet passphrase: "+
+			"%v", err)
+	}
+
+	// Unload the wallet to allow lnd to open it later on.
+	if err := loader.UnloadWallet(); err != nil {
```
Comment (halseth) [inline walletunlocker/service.go]: should make this a `defer` such that it is also done in any error case.

File: walletunlocker/service_test.go [hunk 21]
```diff
@@ -349,3 +349,76 @@ func TestUnlockWallet(t *testing.T) {
...
 	}
 }
+
+// TestChangeWalletPassword tests that we can successfully change the wallet's
+// password needed to unlock it.
+func TestChangeWalletPassword(t *testing.T) {
+	t.Parallel()
+
+	// testDir is empty, meaning wallet was not created from before.
+	testDir, err := ioutil.TempDir("", "testchangepassword")
```
Comment (halseth) [inline walletunlocker/service_test.go]: could add some macaroon files to this dir, to make sure they are deleted :)

File: lnrpc/rpc.proto (hunk 19 above)
Comment (wpaulino) [reply lnrpc/rpc.proto]: Fixed.

File: walletunlocker/service.go (hunk 20 above)
Comment (wpaulino) [reply walletunlocker/service.go]: Fixed.

File: walletunlocker/service_test.go (hunk 21 above)
Comment (wpaulino) [reply walletunlocker/service_test.go]: Fixed.

File: lnrpc/rpc.proto [hunk 22]
```diff
@@ -159,6 +170,21 @@ message UnlockWalletRequest {
 }
 message UnlockWalletResponse {}
 
+message ChangePasswordRequest {
+    /**
+    current_password should be the current valid passphrase used to unlock the
```
Comment (halseth) [inline lnrpc/rpc.proto]: nit: the field name is not usually named like this in the proto comments, as it will not be consistent when the names are translated for `go`. No blocker though.

File: lnd.go [hunk 23]
```diff
@@ -871,8 +871,12 @@ func waitForWalletPassword(grpcEndpoints, restEndpoints []string,
 	if registeredChains.PrimaryChain() == litecoinChain {
 		chainConfig = cfg.Litecoin
 	}
+	macaroonFiles := []string{
```
Comment (halseth) [inline lnd.go]: Add a comment why we are passing the macaroon files to the unlocker service here.

File: walletunlocker/service_test.go [hunk 24]
```diff
@@ -365,3 +365,103 @@ func TestUnlockWallet(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("unable to create temp directory: %v", err)
+	}
+	defer func() {
+		os.RemoveAll(testDir)
```
Comment (halseth) [inline walletunlocker/service_test.go]: nit: can be made `defer os.RemoveAll(testDir)`

File: cmd/lncli/commands.go [hunk 25]
```diff
@@ -1355,6 +1355,63 @@ func unlock(ctx *cli.Context) error {
 	return nil
 }
 
+var changePasswordCommand = cli.Command{
+	Name: "changepassword",
```
Comment (halseth) [inline cmd/lncli/commands.go]: Must be rebased and added to correct command group :)

Comment (wpaulino) [reply cmd/lncli/commands.go]: Fixed.

File: walletunlocker/service_test.go (hunk 24 above)
Comment (wpaulino) [reply walletunlocker/service_test.go]: Fixed.

File: lnd.go (hunk 23 above)
Comment (wpaulino) [reply lnd.go]: Fixed.

File: lnrpc/rpc.proto (hunk 22 above)
Comment (wpaulino) [reply lnrpc/rpc.proto]: Ah, didn't know. I was just going by the style used throughout the other messages.

File: walletunlocker/service.go [hunk 26]
```diff
@@ -277,15 +264,6 @@ func (u *UnlockerService) UnlockWallet(ctx context.Context,
 		return nil, err
 	}
 
-	// Attempt to create a password for the macaroon service.
```
Comment (Roasbeef) [inline walletunlocker/service.go]: Nice, this'll speed up the start time as well, also there's another pending PR to remove the extra invocation of scrypt when we're unlocking the wallet.

**Comment by Roasbeef** [comment]
Tested locally and works as advertised 👌
