### PR TITLE
lnd: fix externalip retention issue

### LINKED ISSUE #10233: [bug]: URIS are not deleted when changed via the externalip config
Regression of (only affects current master): 

https://github.com/lightningnetwork/lnd/pull/8825

When changing the externalIP config (different IP or different Port) the old data is now not deleted anymore and piles up in the node_announement.

cc @Abdulkbk

### PR DESCRIPTION
**Pull request by Abdulkbk**
Fixes #10233

Currently, when a node restarts, persisted addresses are combined with addresses (externalip) set in config, resulting in the retention of addresses that may no longer be valid, in the node announcement. In this PR, we make addresses derived from `--externalip` config take precedence over persisted addresses. However, if `--externalip` is not set and a node restarts, we assume that the persisted addresses are still valid, and therefore we use them for the node announcement.

## Steps to Test
```bash
make build-itest

make itest-only icase="self node announcement persistence"
```

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -5604,13 +5595,10 @@ func (s *server) setSelfNode(ctx context.Context, nodePub route.Vertex,
...
-		for _, addr := range srcNode.Addresses {
-			if _, found := addressMap[addr.String()]; !found {
-				addrs = append(addrs, addr)
-				addressMap[addr.String()] = struct{}{}
-			}
+		// If the `externalip` is not specified in the config, it means 
+		// `addrs` will be empty, we'll use the source node's addresses.
+		if len(s.cfg.ExternalIPs) == 0 {
+			addrs = srcNode.Addresses
 		}
```
[the remark this answers is not in the document]
Comment (Abdulkbk) [reply server.go]: > There appears to be a contradiction between the logic implemented here and the behavior tested in itest/lnd_channel_graph_test.go. The test testSelfNodeAnnouncementPersistence now expects that after an address is set via RPC and the node is restarted without any --externalip config, the previously persisted address is cleared from the node announcement.

@gemini-code-assist, if you look at https://github.com/lightningnetwork/lnd/blob/master/lntest/node/config.go#L300, you'd notice that the method `GenArgs` sets `"--externalip=%v", cfg.P2PAddr())` by default when a node restarts in the tests. That explains why you think this is contradictory.

[the remark this answers is not in the document]
Comment (Abdulkbk) [reply server.go]: @gemini-code-assist thanks for the feedback. The idea is that when a node restarts and `externalip` is not set, we fall back to the persisted addresses, meaning we assume those addresses are still valid and useful. However, when `externalip` is set, we prioritize those addresses. Perhaps I should update the PR description to make this clearer.

File: server.go [hunk 2]
```diff
@@ -5604,13 +5595,10 @@ func (s *server) setSelfNode(ctx context.Context, nodePub route.Vertex,
...
-		// Append unique addresses from the source node to the address
-		// list.
-		for _, addr := range srcNode.Addresses {
-			if _, found := addressMap[addr.String()]; !found {
-				addrs = append(addrs, addr)
-				addressMap[addr.String()] = struct{}{}
-			}
+		// If the `externalip` is not specified in the config, it means
+		// `addrs` will be empty, we'll use the source node's addresses.
+		if len(s.cfg.ExternalIPs) == 0 {
```
Comment (ziggie1984) [inline server.go:5600]: does this mean as soon as I remove all the values from the config it will not mean that entries will disappear, now I need to explicitly create a `Remove` Request ?

Comment (Abdulkbk) [reply server.go:5600]: Yes, I believe that's the tradeoff. The alternative is to treat the values in the config as the only source of truth and never fall back to the retained addresses.

Comment (ziggie1984) [reply server.go:5600]: I am not 100% sure about the feature in the first place retaining values, so I am ok we both as long as the description is verbose enough for users to understand essentially. @alexbosworth what's your opinion regarding new settings which we want to delete ? Right now it seems like removing a value from the config will not remove the value once it was part of the node_annoucement.

Comment (alexbosworth) [reply server.go:5600]: I had the same question before and it was a good while ago but I think the answer was that it would monitor the original state for changes and if there were any changes they'd take priority? Like it remembers the original state of those configuration values and if they change it wipes the API set persisting ones or something?

Comment (ziggie1984) [reply server.go:5600]: personally I favour the approach where we would be able to remove the values by just keeping the config entries empty, when would it make sense to have the information be retained, maybe I still don't understand the full picture of the feature in the first place.

Comment (Abdulkbk) [reply server.go:5600]: Now, the question is what happens when the user never sets the addresses (externalips) in the config but sets them using the `Update` request, and then the node restarts? This means the user will have to set them again.

I favor prioritizing the config, If the values are empty there, we fall back to what we persisted in the previous run. Then make the description verbose enough for users to understand that removing the config means falling back to the addresses last used.

> maybe I still don't understand the full picture of the feature in the first place.

I think the aim was to ensure that users don't have to constantly reconfigure their nodes every time they restart. This can be especially beneficial in situations where the node restarts more frequently.

Comment (ziggie1984) [reply server.go:5600]: > I favor prioritizing the config, If the values are empty there, we fall back to what we persisted in the previous run. Then make the description verbose enough for users to understand that removing the config means falling back to the addresses last used.

Let's do it like this, seems a good approach. So we do this for all values which can be set in the config basically not just externalIP correct ?

Comment (Abdulkbk) [reply server.go:5600]: Yes, for nodeannouncement specifically, we already do this for `alias` and `color`. We haven't found a reliable to address `feature_bits` but a [`TODO`](https://github.com/Abdulkbk/lnd/blob/fbac73011fba9933148c2b74b3207fc8a893abd7/server.go#L5635) was added for that.

Comment (Abdulkbk) [reply server.go:5600]: Added a commit updating the description. Let me know what you think.

File: sample-lnd.conf [hunk 3]
```diff
@@ -212,6 +212,14 @@
 ; advertise your node, this value doesn't need to be set. Unless specified
 ; (with host:port notation), the default port (9735) will be added to the
 ; address.
+;
+; NOTE: If you previously set one or more `externalip` entries and later
+; remove `externalip` from the config, lnd will continue to advertise the
```
Comment (ziggie1984) [inline sample-lnd.conf]: entirely, if they for example remove just one entry it will be removed.

Comment (ziggie1984) [reply sample-lnd.conf]: maybe also add these description to the alias and colour ?

**Review by ziggie1984 — APPROVED** [review]
LGTM

**Review by ellemouton — APPROVED** [review]
Nice fix, thanks! 🙏
