### PR TITLE
Fix FlatMap implementation in Result type

### LINKED ISSUE #10401: [bug]: `FlatMap` implementation in `fn` package is inverted
### Pre-Submission Checklist

- [x] I have searched the existing issues and believe this is a new bug.
- [x] I am not asking a question about how to use lnd, but reporting a bug (otherwise open a discussion).

### LND Version

v0.20.0 and all versions before with the fn package

### LND Configuration

--

### Backend Version

na

### Backend Configuration

na

### OS/Distribution

na

### Bug Details & Steps to Reproduce

The implementation of the `FlatMap` method for the `Result` type is inverted:

https://github.com/lightningnetwork/lnd/blob/85a5bf294c9284706d95d7e44aa7d3ba85633de5/fn/result.go#L148-L156

For a `Result[T]`, `FlatMap` should apply f when the result is `Ok`, and propagate the error unchanged when it’s `Err`. The current code returns `r` on `Ok` and tries to use `r.left` when `Err`, which is wrong.

### Expected Behavior

na

### Debug Information

_No response_

### Environment

_No response_

### PR DESCRIPTION
**Pull request by gijswijs**
The `FlatMap` method for the `Result` type has been corrected to apply the provided function when the result is `Ok` and propagate the error unchanged when it is `Err`. 

Comprehensive unit tests have been added to ensure proper functionality of FlatMap, AndThen, and OrElse methods.

Fixes #10401

### CODE REVIEW

**Comment by gijswijs** [comment]
The coveralls checks failing are a false positive.

Coverage before:
```
go test -cover ./...
ok      github.com/lightningnetwork/lnd/fn/v2   1.030s  coverage: 66.5% of statements
```

After:
```
go test -cover ./...
ok      github.com/lightningnetwork/lnd/fn/v2   1.032s  coverage: 68.0% of statements
```

File: fn/result_test.go [hunk 1]
```diff
@@ -96,3 +96,135 @@ func TestSinkOnOkContinuationCall(t *testing.T) {
...
+			require.Equal(t, tc.expectedA, actual)
+		})
+	}
+}
+
+func TestAndThenMethod(t *testing.T) {
+	// Since AndThen is just an alias for FlatMap, we can reuse the same
+	// test cases.
+	for _, tc := range flatMapTestCases {
+		tc := tc
```
Comment (ziggie1984) [inline fn/result_test.go]: that is not needed anymore in golang > 1.19 I think

Comment (ziggie1984) [reply fn/result_test.go]: can also be removed for all the following lines.

File: docs/release-notes/release-notes-0.20.1.md [hunk 2]
```diff
@@ -32,6 +32,11 @@
   addresses](https://github.com/lightningnetwork/lnd/pull/10341) were added to
   the node announcement and `getinfo` output.
 
+* A bug in the [implementation of
```
Comment (ziggie1984) [inline docs/release-notes/release-notes-0.20.1.md]: not sure if we need release notes, since this function was not used in the LND release anyways, just add a no-changelog label

**Review by ziggie1984 — APPROVED** [review]
some code style minor nits - otherwise LGTM

**Review by yyforyongyu — COMMENTED** [review]
Cool - I think we should address the comments and then merge.

**Comment by litbot-9000** [comment]
@gijswijs, remember to re-request review from reviewers when ready
