### PR TITLE
zmq: remove port checker

### LINKED ISSUE #6333: ZMQ: Can't connect to transaction host if it's mapped to a different port.
### Background

I'm trying to connect a debug version of LND to a bitcoind instance running in a Polar docker container. The Polar bitcoind docker container maps the ZMQ transaction host port (28335) to another local port (29335). LND is unable to connect to the ZMQ transaction host.

### Your environment

* lnd debug build of the current master branch (41b91bd5beb2dcff3b5d7cddb74a319bba18b8e5)
* OS: `21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`
* bitcoind 0.21.1 regtest running in Polar 1.3.0 in default configuration
* Polar connection details:
  - RPC Host | http://127.0.0.1:18443
  - P2P Host | tcp://127.0.0.1:19444
  - ZMQ Block Host | tcp://127.0.0.1:28334
  - ZMQ Transaction Host | tcp://127.0.0.1:29335
* Docker port mapping details
  - 18443/tcp | 0.0.0.0:18443
  - 18444/tcp | 0.0.0.0:19444
  - 28334/tcp | 0.0.0.0:28334
  - 28335/tcp | 0.0.0.0:29335

### Steps to reproduce

- Run bitcoind in Polar, docker ports mapped like above config
- Start LND with `./lnd-debug --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=127.0.0.1:18443 --bitcoind.rpcuser=polaruser --bitcoind.rpcpass=polarpass --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28334 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:29335`
- `lncli-debug unlock`

### Expected behaviour

LND should connect to the ZMQ transaction host over a mapped port in a docker container.

### Actual behaviour

After unlocking the wallet I get this error:
```
2022-03-11 12:47:31.573 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28334
2022-03-11 12:47:31.573 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:29335
2022-03-11 12:47:31.585 [ERR] LTND: unable to create partial chain control: unable to subscribe to zmq tx events on 127.0.0.1:29335 (bitcoind is running on 0.0.0.0:28335)
2022-03-11 12:47:31.586 [ERR] LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to subscribe to zmq tx events on 127.0.0.1:29335 (bitcoind is running on 0.0.0.0:28335)
```

### Remarks
- The same error occurs when connecting to `bitcoind.zmqpubrawtx=tcp://0.0.0.0:29335`, so it must be the port mapping that is the problem.
- Apparently in this case LND _is_ able to connect to the ZMQ block host. Note that the port mapping for the block host in above configuration is 28334:28334. So same port apparently does work.

### PR DESCRIPTION
**Pull request by ErikEk**
Fixes #6333.
This pr reverse the changes in #5710. 
As is, lnd can not connect to a bitcoind node, through zmq, running inside a docker container.
#5710 was added as a safeguard against mixing up the port values of zmqpubrawtx and zmqpubrawblock, which would result in lnd not being notified of new transactions and/or blocks.

### CODE REVIEW

File: chainreg/chainregistry.go [hunk 1]
```diff
@@ -486,92 +485,11 @@ func NewPartialChainControl(cfg *Config) (*PartialChainControl, func(), error) {
...
-					}
-					pubRawBlockActive = true
-				}
-				if zmq[i].Type == "pubrawtx" {
-					url, err := url.Parse(zmq[i].Address)
-					if err != nil {
-						return nil, nil, err
-					}
-					if url.Port() != zmqPubRawTxURL.Port() {
-						return nil, nil, fmt.Errorf(
```
Comment (guggero) [inline chainreg/chainregistry.go:548]: How about we just log a WRN message here? I think this could still be valuable for users that have a mistake in their configuration.

File: chainreg/chainregistry.go [hunk 2]
```diff
@@ -486,92 +485,11 @@ func NewPartialChainControl(cfg *Config) (*PartialChainControl, func(), error) {
...
-						)
-					}
-					pubRawTxActive = true
-				}
-			}
-
-			// Return an error if raw tx or raw block notification over
-			// zmq is inactive.
-			if !pubRawBlockActive {
-				return nil, nil, errors.New(
```
Comment (guggero) [inline chainreg/chainregistry.go:562]: IMO this could still error out to prevent the user from running without ZMQ.

**Review by guggero — COMMENTED** [review]
Thanks for the fix. Though I think instead of removing this check, we could just downgrade the startup error to a log warn message?

File: chainreg/chainregistry.go (hunk 1 above)
Comment (ErikEk) [reply chainreg/chainregistry.go:548]: @guggero Good idea. Code updated.

File: docs/release-notes/release-notes-0.15.0.md [hunk 3]
```diff
@@ -14,7 +14,7 @@ invoices](https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-Septemb
 ## Security
 
 * [Misconfigured ZMQ
-  setup now gets reported](https://github.com/lightningnetwork/lnd/pull/5710).
+  setup now return a warning](https://github.com/lightningnetwork/lnd/pull/5710).
```
Comment (guggero) [inline docs/release-notes/release-notes-0.15.0.md:17]: nit: logs a warning?

**Review by guggero — APPROVED** [review]
LGTM :tada:

File: docs/release-notes/release-notes-0.15.0.md (hunk 3 above)
Comment (ErikEk) [reply docs/release-notes/release-notes-0.15.0.md]: Fixed.

**Review by joostjager — APPROVED** [review]
Fixes the problem 👍
