### PR TITLE
multi: clean up forwarding state from closed channels

### LINKED ISSUE #3052: htlcswitch: clean up forwarding state from closed channels
## Background

In the process of forwarding HTLCs, LND maintains two persistent data structures in order to offer high throughput and crash tolerance.

The first is the [`CircuitMap`](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/circuit_map.go), which maintains a record of incoming (ChannelID, HtlcID) to outgoing (ChannelID, HtlcID). This allows it to determine where a Settle/Fail message should return, and also ensure at most one HTLC is ever sent out for a particular incoming HTLC. The circuit map provides insight at the core of the forwarding process, when LND internally moves an HTLC from the incoming to outgoing channel.

The second is a series of _forwarding packages_ ([FwdPkg](https://github.com/lightningnetwork/lnd/blob/master/channeldb/forwarding_package.go#L195)), which records all HTLCs that are added or removed by a particular commitment transaction. One such record is maintained by each channel for every commitment height. These records are updated atomically when updating channel states, and provide persistent insight into the ingress and egress of HTLCs at the perimeter of the daemon wrt the view of the channel's commitments.

## Issue

Under normal operation, records from both the `CircuitMap` and `FwdPkgs` are removed when they 
become unnecessary. However, this can only be done if the channel is active in the `htlcswitch`. When a channel is closed, LND prevents those channels from ever being loaded back into the switch, to prevent any accidental state updates from occurring and risking any sort of channel breach.

Therefore, the current design leaves some of the forwarding state behind when channels are closed. The total amount of data is small relative to the other data maintained by LND, but it is ideal that we clean up after ourselves and free up the disk space.

## Steps to Completion (`FwdPkg` Cleanup)

- [ ] Create a `Wipe` method on the [`ChannelPackager`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/forwarding_package.go#L411) which deletes the top level bucket for the given channel's forwarding logs
- [ ] When a channel is closed via [`CloseChannel`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/channel.go#L2038), the channel's forwarding packages should be cleaned up by invoking the `Wipe` method on its `ChannelPackager`
 - [ ] Add a migration to clean up any forwarding packages for channels that have been closed prior, yet still have a top-level forwarding package bucket

## Steps to Completion (`CircuitMap` Cleanup)

On startup, when restoring the circuit map state from disk in [NewCircuitMap](https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/circuit_map.go#L185):
 - [ ] Determine the set of channels that have been closed
 - [ ] Remove all _circuits_ from the circuit bucket whose _key_ prefix matches a short channel id in the set of the closed channels
 - [ ] Remove any _keystones_ from the keystone bucket whose _key_ prefix matches a short channel id in the set of closed channels
 - [ ] Ensure _never_ to remove keys whose prefix is the zero-value short channel id, this deletes state for locally initiated payments. We should be defensive by including this check in the `CircuitMap`. It is too risky to assume that the short channel id field is always correct, e.g. some channels may have never confirmed (and never assigned a proper short chan id) but are now closed.

Note: In theory, we can do better than only cleaning the circuit map on restarts, however channel closures aren't very frequent and the amount code required to do so live probably doesn't warrant the complexity unless it becomes an issue in the future.

## WARNING

Please DO NOT test this on a mainnet node until it has undergone sufficient review. This cleanup requires modifying extremely critical code, and minor bugs can lead to completely irrecoverable loss of forwarding state. 

## Notes

This issue could technically be broken up into two, though given the amount of interplay between the the circuit map and forwarding packages I think it'd be best to review the changes as a whole to make sure nothing is missed.

### PR DESCRIPTION
**Pull request by yyforyongyu**
This PR fixes #3052, which contains mainly two parts,

- channeldb: clean forwarding packages for closed channels
The root bucket is “fwd-packages”, and further subdivided based on `ShortChanID` for each channel. When a channel is closed, its `ShortChanID` is used to query the nested bucket in "fwd-packages", and the bucket is deleted. As suggested in #3052, the `Wipe` method in `ChannelContronller` is called inside the CloseChannel method.

- htlcswitch: clean circuits and keystones for closed channels

Fixes https://github.com/lightningnetwork/lnd/issues/4712

### CODE REVIEW

**Comment by Roasbeef** [comment]
>  But fetchOpenChannel also calls the NewChannelPackager. Moreover, fetchOpenChannel calls another method, fetchChanInfo, that also calls the NewChannelPackager. I’m thinking maybe there exists an opportunity for optimization?

IIRC, this is because `RefreshShortChanID` (which is used to sync the in memory state with any possible on-disk updates) exists, which calls `fetchChanInfo`.

File: channeldb/channel_test.go [hunk 1]
```diff
@@ -157,6 +158,25 @@ func remoteHtlcsOption(htlcs []HTLC) testChannelOption {
...
+// particular packager.
+func loadFwdPkgs(t *testing.T, db kvdb.Backend,
+	packager FwdPackager) []*FwdPkg {
+
+	var (
+		fwdPkgs []*FwdPkg
+		err     error
+	)
+
+	err = kvdb.View(db, func(tx kvdb.RTx) error {
```
Comment (Roasbeef) [inline channeldb/channel_test.go:171]: Has been a while since this PR was touched last, but all the calls to `View/Update` will need to be updated w/ the new extra arg to handle transaction retries if `etcd` is being used.

File: channeldb/log.go [hunk 2]
```diff
@@ -35,4 +36,5 @@ func UseLogger(logger btclog.Logger) {
 	migration12.UseLogger(logger)
 	migration13.UseLogger(logger)
 	migration16.UseLogger(logger)
+	migration18.UseLogger(logger)
```
Comment (Roasbeef) [inline channeldb/log.go:39]: Will also need to be updated to be migration #22 (unless something has taken that slot itself already).

File: channeldb/channel.go [hunk 3]
```diff
@@ -2718,6 +2718,12 @@ func (c *OpenChannel) CloseChannel(summary *ChannelCloseSummary,
 			return err
 		}
 
+		// Delete all the forwarding packages stored for this particular
+		// channel.
+		if err = chanState.Packager.Wipe(tx); err != nil {
```
Comment (Roasbeef) [inline channeldb/channel.go:2722]: This should also be done in `MarkChanFullyClosed` so any channels that were fully closed after the migration will also have their forwarding packages cleared.

File: channeldb/migration18/migration_test.go [hunk 4]
```diff
@@ -0,0 +1,294 @@
...
+// TestMigrateFwdPkgCleanup asserts that the migration will delete all the
+// forwarding packages for close channels, and leave the rest untouched.
+func TestMigrateFwdPkgCleanup(t *testing.T) {
+	migrationTests := []struct {
+		name                string
+		beforeMigrationFunc func(kvdb.RwTx) error
+		afterMigrationFunc  func(kvdb.RwTx) error
+	}{
+		{
+			// no closed channels summeries in the db.
```
Comment (Roasbeef) [inline channeldb/migration18/migration_test.go:74]: Style nit: first letter should be capitalized in this commit as well as the ones below.

File: channeldb/migration18/migration_test.go [hunk 5]
```diff
@@ -0,0 +1,294 @@
...
+			),
+			afterMigrationFunc: genAfterMigration(
+				[]int{1}, []int{},
+			),
+		},
+		{
+			// one closed summery with pending status found, and the
+			// forwarding package shares the same channel ID.
+			// This leaves the fwdpkg untouched.
+			name: "no action if closed status is pending",
```
Comment (Roasbeef) [inline channeldb/migration18/migration_test.go:100]: 👍

File: channeldb/migration18/migration.go [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+		// Otherwise, wipe all the forwarding packages.
+		if err := fwdPkgBkt.DeleteNestedBucket(
+			sourceBytes[:]); err != nil {
+
+			return err
+		}
+	}
+
+	log.Infof(
+		"Deletion of forwarding packages of closed channels complete!",
```
Comment (Roasbeef) [inline channeldb/migration18/migration.go:90]: Perhaps we should add a line to encourage the users to compact their DB afterwards? As for very old nodes that have high forwarding activity, this may end up reclaiming a considerable amount of space in theory.

File: htlcswitch/circuit_map.go [hunk 7]
```diff
@@ -224,6 +229,134 @@ func (cm *circuitMap) initBuckets() error {
 	})
 }
 
+// cleanClosedChannels deletes all circuits and keystones related to closed
+// channels. It first reads all the closed channels and cache the ShortChanIDs
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:233]: and cache -> and caches

File: htlcswitch/circuit_map.go [hunk 8]
```diff
@@ -224,6 +229,134 @@ func (cm *circuitMap) initBuckets() error {
...
+// into a map for fast lookup. Then it iterates the circuit bucket and keystone
+// bucket and deletes items whose ChanID matches the ShortChanID.
+//
+// NOTE: this operation can also be built into restoreMemState since the latter
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:237]: 👍

File: htlcswitch/circuit_map.go [hunk 9]
```diff
@@ -224,6 +229,134 @@ func (cm *circuitMap) initBuckets() error {
...
+// already opens and iterates the two root buckets, circuitAddKey and
+// circuitKeystoneKey. Depending on the size of the buckets, this marginal gain
+// may be worth investigating. Atm, for clarity, this operation is wrapped into
+// its own function.
+func (cm *circuitMap) cleanClosedChannels() error {
+	log.Infof("Cleaning circuits from disk for closed channels")
+
+	var (
+		targetChanIDs       = make(map[lnwire.ShortChannelID]int)
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:246]: Any reason this is mapped to an integer rather than just a `bool` or `struct{}`?

File: htlcswitch/circuit_map.go [hunk 10]
```diff
@@ -224,6 +229,134 @@ func (cm *circuitMap) initBuckets() error {
...
+		// If a circuit's incoming key prefix matches the ShortChanID,
+		// it will be deleted. However, if the ShortChanID is zero, the
+		// circuit will be kept as it indicates a locally initiated
+		// payment.
+		if err := circuitBkt.ForEach(func(_, v []byte) error {
+			circuit, err := cm.decodeCircuit(v)
+			if err != nil {
+				return err
+			}
+
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:286]: Don't we want to clean these up to if the _outgoing_ channel ID is now a closed channel?

File: htlcswitch/circuit_map.go [hunk 11]
```diff
@@ -224,6 +229,134 @@ func (cm *circuitMap) initBuckets() error {
...
+			// Check if the incoming channel ID can be found in the
+			// map. Skip if no matches found.
+			_, found := targetChanIDs[circuit.Incoming.ChanID]
+			if !found {
+				return nil
+			}
+
+			// Delete the ciruit.
+			inKey := circuit.InKey()
+			if err := circuitBkt.Delete(inKey.Bytes()); err != nil {
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:301]: It isn't safe to delete from underneath a bucket while one is iterating over it. So we'll need to do this in two passes: first gather all the keys we _would_ delete, then make another transaction to delete them all at once.

File: htlcswitch/circuit_map.go [hunk 12]
```diff
@@ -224,6 +229,134 @@ func (cm *circuitMap) initBuckets() error {
...
+
+			// Check if the circuit key channel ID can be found in
+			// the map. Skip if no matches found.
+			_, found := targetChanIDs[inKey.ChanID]
+			if !found {
+				return nil
+			}
+
+			// Delete the keystone using the outgoing key.
+			if err := keystoneBkt.Delete(k); err != nil {
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:335]: Similar comment here re not deleting while iterating over a bucket.

**Review by Roasbeef — CHANGES_REQUESTED** [review]
This was buried at the bottom of some notifications, let's see if we can revive it!

One things I'm curious of about is how much state we can clean up for old very active nodes with this PR. To gather a ball park number, we could recruit some testers to run the migration in dry run mode, flagging that it won't commit anything to disk, so it should be safe.

File: channeldb/channel.go (hunk 3 above)
Comment (yyforyongyu) [reply channeldb/channel.go:2866]: `MarkChanFullyClosed` is called in two places.

First when we `ResolveContract` in `ChainArbitrator`, which is attached to `arbCfg.MarkChannelResolved`. This function is only invoked when [we reach `StateFullyResolved`](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/channel_arbitrator.go#L1069). Now, to reach `StateFullyResolved`, we must use one of the following triggers, `remoteCloseTrigger`, `localCloseTrigger`, `coopCloseTrigger` or`breachCloseTrigger`.

The formal three triggers will all invoke the method `MarkChannelClosed`, which calls `channel.CloseChannel` that will wipe the fwd packages. As for the trigger `breachCloseTrigger`, when received, we will also [close the channel via `markClosed`](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/chain_watcher.go#L1161) in `dispatchContractBreach` before we handle the case in our state machine. The call stack is somewhat deep and jumpy, as `markClosed` is again wrapped in [`processACK` in server.go](https://github.com/lightningnetwork/lnd/blob/master/server.go#L968) and passed to `ContractBreachEvent`, where this is the second place we would use `MarkChanFullyClosed`. However, before that happens, we would call [`ProcessACK`](https://github.com/lightningnetwork/lnd/blob/master/breacharbiter.go#L882) which calls `CloseChannel` that wipes the packages.

File: channeldb/channel_test.go (hunk 1 above)
Comment (yyforyongyu) [reply channeldb/channel_test.go:143]: Fixed!

File: htlcswitch/circuit_map.go (hunk 10 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go:343]: Yes. Since `decodeCircuit` will not give the circuit an `Outgoing` circuit key, this is done when we clean the keystones.

File: channeldb/log.go (hunk 2 above)
Comment (yyforyongyu) [reply channeldb/log.go]: Fixed! Changed to 23.

File: channeldb/migration18/migration_test.go (hunk 4 above)
Comment (yyforyongyu) [reply channeldb/migration18/migration_test.go]: Fixed!

File: channeldb/migration18/migration.go (hunk 6 above)
Comment (yyforyongyu) [reply channeldb/migration18/migration.go]: Added.

File: htlcswitch/circuit_map.go (hunk 7 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go]: Fixed.

File: htlcswitch/circuit_map.go (hunk 9 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go]: Guess I wasn't aware of using empty struct back then🤓

File: htlcswitch/circuit_map.go (hunk 11 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go]: Fixed!

File: htlcswitch/circuit_map.go (hunk 12 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go]: Fixed!

File: channeldb/forwarding_package.go [hunk 13]
```diff
@@ -39,6 +39,38 @@ var (
 	// fwdPackagesKey is the root-level bucket that all forwarding packages
 	// are written. This bucket is further subdivided based on the short
 	// channel ID of each channel.
+	//
```
Comment (Roasbeef) [inline channeldb/forwarding_package.go:42]: 👍

File: channeldb/forwarding_package.go [hunk 14]
```diff
@@ -944,6 +947,28 @@ func (p *ChannelPackager) RemovePkg(tx kvdb.RwTx, height uint64) error {
...
+	}
+
+	sourceBytes := makeLogKey(p.source.ToUint64())
+
+	// If the nested bucket doesn't exist, there's no need to delete.
+	if fwdPkgBkt.NestedReadWriteBucket(sourceBytes[:]) == nil {
+		return nil
+	}
+
+	if err := fwdPkgBkt.DeleteNestedBucket(sourceBytes[:]); err != nil {
```
Comment (Roasbeef) [inline channeldb/forwarding_package.go:965]: Can be simplified to just:
```go
return fwdPkgBkt.DeleteNestedBucket(sourceBytes[:])
```

File: contractcourt/briefcase.go [hunk 15]
```diff
@@ -125,6 +125,59 @@ type ArbitratorLog interface {
...
 
 const (
+	// While some state transition is allowed, certain transitions are not
+	// possible. Listed below is the full state transition map which
+	// contains all possible paths. We start at StateDefault and end at
+	// StateFullyResolved, or StateError(not listed as its a possible state
+	// in every path). The format is,
+	// 	-> state: conditions we switch to this state.
+	//
+	// StateDefault
```
Comment (Roasbeef) [inline contractcourt/briefcase.go:135]: Very cool state transition diagram! Would be cool to eventually use something to render this out using a traditional state-machine like structure. This is a big improvement on what we have for now though imo.

File: channeldb/channel.go (hunk 3 above)
Comment (Roasbeef) [reply channeldb/channel.go:2866]: Thanks for the through answer! One way to verify this from the PoV of an integration test would be to supplement the `PendingChannels` response w/ some information about the set of active forwarding packages. Each time we call a normal `CloseChannel` (or have a resulting closed channel and a pending channels call), we would then verify that the set of forwarding packages is 100% empty.

File: channeldb/migration23/migration.go [hunk 16]
```diff
@@ -0,0 +1,119 @@
...
+	closeBucket := tx.ReadBucket(closedChannelBucket)
+	if closeBucket == nil {
+		return nil
+	}
+
+	var chanSummaries []*mig.ChannelCloseSummary
+
+	// appendSummary is a function closure to help put deserialized close
+	// summeries into chanSummaries.
+	appendSummary := func(_ []byte, summaryBytes []byte) error {
```
Comment (Roasbeef) [inline channeldb/migration23/migration.go:41]: Nice closure usage here to make this section more readable!

File: htlcswitch/circuit_map.go [hunk 17]
```diff
@@ -219,6 +219,11 @@ func NewCircuitMap(cfg *CircuitMapConfig) (CircuitMap, error) {
 		return nil, err
 	}
 
+	// Delete old circuits and keystones of closed channels
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:222]: Hmm, so we'll do this at start up rather than on an _ongoing_ basis? I guess in the end, at least with bolt, we only really shrink disk space no compaction, which (atm) itself requires a restart....

Also style nit: missing a period here.

File: htlcswitch/circuit_map.go [hunk 18]
```diff
@@ -250,6 +255,214 @@ func (cm *circuitMap) initBuckets() error {
...
+			return false
+		}
+
+		_, ok := closedChanIDSet[chanID]
+		return ok
+	}
+
+	// Find closed channels and cache their ShortChannelIDs into a map.
+	// This map will be used for looking up relative circuits and keystones.
+	closedChannels, err := cm.cfg.DB.FetchClosedChannels(false)
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:299]: Don't consider it a blocker, but since we only need the _short chan ID_ of each of the closed channels, we could add a _new_ method here that just scans the buckets to fetch the keys themselves. This would let us not have to decode the values, and potentially not send the values at all for certain classes of replicated databases.

File: htlcswitch/circuit_map.go [hunk 19]
```diff
@@ -250,6 +255,214 @@ func (cm *circuitMap) initBuckets() error {
...
+			err := keystoneBkt.Delete(outKey.Bytes())
+			if err != nil {
+				return err
+			}
+
+			numKeystonesDeleted++
+		}
+
+		return nil
+	}, func() {}); err != nil {
```
Comment (Roasbeef) [inline htlcswitch/circuit_map.go:454]: The closure counter variables (`numKeystonesDeleted`, etc) should also be reset each time to avoid logging some possibly incorrect values.

**Review by Roasbeef — CHANGES_REQUESTED** [review]
Great work on this PR! 

I think think the only remaining item I need to properly re-grok is our usage of the zero short chan ID to indicate an outgoing payment (no incoming circuit) and how we go about handling the deletion of them in practice w/ and w/o this PR. 

As mentioned in the original issue, we'll need to ensure we properly test this PR before and after the 0.14 cycle as the worst case here is we erroneously delete a circuit that results in an on-chain one-sided redemption (remote party pulls the pre-image and we don't know which incoming channel it belongs to).

File: channeldb/channel.go (hunk 3 above)
Comment (yyforyongyu) [reply channeldb/channel.go:2866]: Good idea. A new itest case is added!

File: htlcswitch/circuit_map.go (hunk 17 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go:222]: Period added.

I thinking on an ongoing basis, there is `DeleteCircuits` being called multiple times to clean up circuits. Haven't dug into all those call sites yet while I think most of the circuits are cleaned before the channel being closed?

File: htlcswitch/circuit_map.go (hunk 19 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go:454]: Done!

File: htlcswitch/circuit_map.go (hunk 18 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map.go:299]: I think the bucket keys are channel outpoints right? I think we'd still load the value bytes and encode the short channel ID. But yeah, this is a good way to optimize the CRUD in our db, and, we could def write more granular methods for specific cases.

File: htlcswitch/circuit_map.go [hunk 20]
```diff
@@ -250,6 +255,216 @@ func (cm *circuitMap) initBuckets() error {
...
+				circuitKeySet[inKey] = struct{}{}
+			}
+
+			return nil
+		})
+		return err
+
+	}, func() {
+		// Reset the sets.
+		circuitKeySet = make(map[CircuitKey]struct{})
```
Comment (bhandras) [inline htlcswitch/circuit_map.go:410]: :+1:

File: htlcswitch/circuit_map_test.go [hunk 21]
```diff
@@ -0,0 +1,403 @@
...
+	if cs.RemoteCurrentRevocation == nil {
+		return channeldb.WriteElements(w, false)
+	}
+
+	return nil
+}
+
+// writeOutpoint writes an outpoint to the passed writer using the minimal
+// amount of bytes possible.
+func writeOutpoint(w io.Writer, o *wire.OutPoint) error {
```
Comment (bhandras) [inline htlcswitch/circuit_map_test.go:394]: nit: could we just use the function to write to a buffer from `lnwire` instead?

**Review by bhandras — COMMENTED** [review]
Super clean code in this PR! Great work!
My only real comment before approval is to rebase as we already have migration23.

File: channeldb/channel_test.go [hunk 22]
```diff
@@ -130,6 +130,25 @@ func remoteHtlcsOption(htlcs []HTLC) testChannelOption {
...
+		fwdPkgs, err = packager.LoadFwdPkgs(tx)
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply channeldb/channel_test.go:144]: Fixed！

File: channeldb/channel_test.go [hunk 23]
```diff
@@ -822,6 +841,10 @@ func TestChannelStateTransition(t *testing.T) {
 		t.Fatalf("revocation state was not synced")
 	}
 
+	// At this point, we should have 2 forwarding packages added.
+	fwdPkgs := loadFwdPkgs(t, cdb, channel.Packager)
+	require.Equal(t, 2, len(fwdPkgs), "wrong number of forwarding packages")
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply channeldb/channel_test.go:846]: nice tip, changed!

File: channeldb/migration23/migration.go [hunk 24]
```diff
@@ -0,0 +1,119 @@
+package migration23
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply channeldb/migration23/migration.go:1]: Done!

File: channeldb/migration23/migration_test.go [hunk 25]
```diff
@@ -0,0 +1,297 @@
...
+				tx, isPending, chanID,
+			); err != nil {
+				return err
+			}
+		}
+
+		// Create fwdPkg nested buckets
+		for _, id := range fwdPkgChanIDs {
+			chanID := lnwire.NewShortChanIDFromInt(uint64(id))
+			if err := createTestFwdPkgBucket(tx,
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply channeldb/migration23/migration_test.go:170]: Changed.

File: lntest/itest/lnd_wipe_fwdpkgs_test.go [hunk 26]
```diff
@@ -0,0 +1,227 @@
...
+	require.NoError(t.t, err, "unable to mine blocks")
+
+	// Now that the closing transaction is confirmed, the above waiting
+	// close channel should now become pending force closed channel.
+	pendingChan = assertPendingForceClosedChannel(t.t, net.Bob)
+
+	// Check the forwarding pacakges are deleted.
+	require.Zero(t.t, pendingChan.NumForwardingPackages)
+
+	// For Alice, the forwarding packages should have been wipe too.
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply lntest/itest/lnd_wipe_fwdpkgs_test.go:58]: Fixed!

File: htlcswitch/circuit_map_test.go (hunk 21 above)
Comment (yyforyongyu) [reply htlcswitch/circuit_map_test.go]: good thought! I think there are some works left in terms of putting this circuit map db operations into `channeldb` package and, there are overlaps of writers/encoders between `lnwire` and `channeldb`, which we could fix later.

File: channeldb/forwarding_package_test.go [hunk 27]
```diff
@@ -729,6 +730,49 @@ func TestPackagerSettleFailsThenAdds(t *testing.T) {
...
 
+// TestPackagerWipeAll checks that when the method is called, all the related
+// forwarding packages will be removed.
+func TestPackagerWipeAll(t *testing.T) {
+	t.Parallel()
+
+	db := makeFwdPkgDB(t, "")
+
+	shortChanID := lnwire.NewShortChanIDFromInt(1)
+	packager := channeldb.NewChannelPackager(shortChanID)
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply channeldb/forwarding_package_test.go:741]: That's indeed a good test case, while I don't think it belongs here as a unit test. Maybe there should be some unit tests to ensure we always enforce the scope of a given packager is limited to its channel, with that promise, we could then test all the add/delete/wipe methods of the packager. Otherwise we'd have at least 2x more states to be tested.

**Comment by bhandras** [comment]
Let me know when ready for another round @yyforyongyu

**Comment by yyforyongyu** [comment]
> Let me know when ready for another round @yyforyongyu

It's ready! PTAL.

File: channeldb/forwarding_package_test.go (hunk 27 above)
[the remark this answers is not in the document]
Comment (bhandras) [reply channeldb/forwarding_package_test.go:741]: Yes indeed, I agree it's not a normal unit test scenario, but in this case we're operating on a shared resource, meaning that accidental bug in the way we create the bucket keys may mean unexpected deletes. I'm ok with the test as is and this is more of an bonus we could add.

**Review by bhandras — APPROVED** [review]
LGTM :1st_place_medal:

**Review by Roasbeef — APPROVED** [review]
LGTM ⚒
