### PR TITLE
[rpcServer]: add time_lock_delta overflow check for UpdateChannelPolicy

### LINKED ISSUE #7320: [bug]: high values for time_lock_delta can result in unexpected setting of 0
Hello,

updatechanpolicy's time_lock_delta can roll over when very high values are used, which might result in a setting of 0.
I noticed this in a happy accident, where I used the channel_id instead of the channel_point and also forgot to actually
set time_lock_delta. So my channel_id got parsed as --time_lock_delta.

`lncli --network testnet updatechanpolicy --fee_rate 0 --base_fee_msat 0 844393044316848128`

resulted in time_lock_delta getting set to 0 for all my channels...

This shouldn't even be possible, because normally it complains that the  minimum value is 18.


### Your environment

tlv/v1.1.0-130-g143eba82e (0.15.99-beta current git master)
Linux lnd-test2 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
bitcoin-core 23.0


### Steps to reproduce

`lncli --network testnet updatechanpolicy --fee_rate 0 --base_fee_msat 0 844393044316848128`

### Expected behaviour

Failure or time_lock_delta set to a high value

### Actual behaviour

time_lock_delta got set to 0 for all my channels

> $ lncli --network testnet getchaninfo 2610605642201169921
{
    [...]
    "node1_policy": {
        "time_lock_delta": 0,
        "min_htlc": "1000",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "0",
        "disabled": false,
        "max_htlc_msat": "1458270000",
        "last_update": 1673657439,
        "custom_records": {
        }
    },
    [...]
$ lncli --network testnet getchaninfo 2610596846108147712
{
    [...]
    "node1_policy": {
        "time_lock_delta": 0,
        "min_htlc": "1000",
        "fee_base_msat": "0",
        "fee_rate_milli_msat": "0",
        "disabled": false,
        "max_htlc_msat": "990000000",
        "last_update": 1673657439,
        "custom_records": {
        }
    },
   [...]                                                                                                                                                                                                                                                                           
                

### Additional Info
This might be caused by a 32bit roll over, as this still works as expected:
`lncli --network testnet updatechanpolicy --fee_rate 0 --base_fee_msat 0 --time_lock_delta 2147483647`
results in time_lock_delta 65535
while this results in setting it to zero again:
`lncli --network testnet updatechanpolicy --fee_rate 0 --base_fee_msat 0 --time_lock_delta 2147483648`

### PR DESCRIPTION
**Pull request by eval-exec**
Signed-off-by: Eval EXEC <execvy@gmail.com>

## Change Description
This PR want to add time_lock_delta overflow check in rpcServer, the maximum time_lock_delta should be `max(uint16)`, fix #7320
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

File: cmd/lncli/commands.go [hunk 1]
```diff
@@ -2117,13 +2118,26 @@ func updateChannelPolicy(ctx *cli.Context) error {
 
 	switch {
 	case ctx.IsSet("time_lock_delta"):
-		timeLockDelta = ctx.Int64("time_lock_delta")
+		timeLockDeltaUnCheck := ctx.Int64("time_lock_delta")
```
Comment (MStreet3) [inline cmd/lncli/commands.go:2121]: What happens in the case that the initial value overflows an int64?

Comment (eval-exec) [reply cmd/lncli/commands.go:2121]: If initial value overflows an int64, `ctx.Int64("time_lock_delta")` will return 0. I think I need use `ctx.String()` instead of `ctx.Int64()`.

**Comment by MStreet3** [comment]
Would be ideal to add unit tests showing the overflow would now error

File: config.go [hunk 2]
```diff
@@ -98,6 +98,9 @@ const (
 	// HTLCs on our channels.
 	minTimeLockDelta = routing.MinCLTVDelta
 
+	// MaxTimeLockDelta is the maximum timelock.
+	MaxTimeLockDelta = ^uint16(0)
```
Comment (MStreet3) [inline config.go:102]: Prefer to just write `math.MaxUint16` instead of using caret operator.

**Review by MStreet3 — APPROVED** [review]

File: config.go (hunk 2 above)
Comment (MStreet3) [reply config.go:102]: meant to comment not approve

**Comment by eval-exec** [comment]
This PR failed at `make lint`, it trigger the [missing parallel test method](https://github.com/kunwardeep/paralleltest#missing-tparallel-in-the-test-method).

I wonder there are many unit tests in history commits didn't trigger the paralleltest error.

File: cmd/lncli/commands.go [hunk 3]
```diff
@@ -2070,6 +2071,22 @@ func parseChanPoint(s string) (*lnrpc.ChannelPoint, error) {
 	}, nil
 }
 
+func parseTimeLockDelta(timeLockDeltaStr string) (uint16, error) {
+	timeLockDeltaUnCheck, err :=
```
Comment (guggero) [inline cmd/lncli/commands.go:2075]: nit: wrap at function call, for example:
```
timeLockDeltaUnCheck, err := strconv.ParseUint(
        timeLockDeltaStr, 10, 64,
)
```

File: cmd/lncli/commands.go [hunk 4]
```diff
@@ -2070,6 +2071,22 @@ func parseChanPoint(s string) (*lnrpc.ChannelPoint, error) {
...
+		strconv.ParseUint(timeLockDeltaStr, 10, 64)
+	if err != nil {
+		return 0, fmt.Errorf("fail to parse time_lock_delta: %s "+
+			"to uint64, err: %s", timeLockDeltaStr, err)
```
Comment (guggero) [inline cmd/lncli/commands.go:2079]: nit: we usually use `%v` for errors in format strings.

File: config.go [hunk 5]
```diff
@@ -98,6 +99,9 @@ const (
 	// HTLCs on our channels.
 	minTimeLockDelta = routing.MinCLTVDelta
 
+	// MaxTimeLockDelta is the maximum timelock.
```
Comment (guggero) [inline config.go:102]: nit: more precise comment? Perhaps something along the lines of "... is the maximum CLTV delta that can be applied to forwarded HTLCs"?

File: rpcserver.go [hunk 6]
```diff
@@ -6815,6 +6815,12 @@ func (r *rpcServer) UpdateChannelPolicy(ctx context.Context,
 			minTimeLockDelta)
 	}
 
+	if req.TimeLockDelta > uint32(MaxTimeLockDelta) {
+		return nil, fmt.Errorf("time lock delta of %v is too big, "+
```
Comment (guggero) [inline rpcserver.go:6819]: nit: use `%d` for numeric types in format strings.

**Review by guggero — COMMENTED** [review]
Looks pretty good, thanks.

> I wonder why there are many unit tests in history commits didn't trigger the paralleltest error.

We added a couple of new linters and are still fine-tuning them (to find out which ones we actually want to have active and which ones are too strict). But we added them in a way that they only apply to new code, that's why they don't trigger on existing lines.

File: rpcserver.go (hunk 6 above)
Comment (eval-exec) [reply rpcserver.go:6819]: > nit: use `%d` for numeric types in format strings.

I found many occurence of code like this:https://github.com/lightningnetwork/lnd/blob/628fc017324daf57b822a2c2b7c5c763f3131736/rpcserver.go#L6788-L6822

All of them are using `%v` for numeric types in error format, I think `%v` is better than `%d` in error message, because `%v` contains variable type.

**Comment by eval-exec** [comment]
I added `[skip ci]` in commit message.

File: cmd/lncli/commands.go [hunk 7]
```diff
@@ -2070,6 +2071,23 @@ func parseChanPoint(s string) (*lnrpc.ChannelPoint, error) {
 	}, nil
 }
 
+func parseTimeLockDelta(timeLockDeltaStr string) (uint16, error) {
```
Comment (GeorgeTsagk) [inline cmd/lncli/commands.go:2074]: Perhaps a short godoc here would be useful? In order to easily provide info on what the behavior is going to be e.g. with regards to `MaxTimeLockDelta`

File: cmd/lncli/commands.go [hunk 8]
```diff
@@ -2070,6 +2071,23 @@ func parseChanPoint(s string) (*lnrpc.ChannelPoint, error) {
...
+	timeLockDeltaUnCheck, err := strconv.ParseUint(
+		timeLockDeltaStr, 10, 64,
+	)
+	if err != nil {
+		return 0, fmt.Errorf("fail to parse time_lock_delta: %s "+
```
Comment (GeorgeTsagk) [inline cmd/lncli/commands.go:2079]: nit:  "fail" -> "failed" ?

File: cmd/lncli/commands_test.go [hunk 9]
```diff
@@ -68,3 +71,64 @@ func TestParseChanPoint(t *testing.T) {
...
+		},
+		{
+			"3",
+			3,
+			false,
+			"",
+		},
+		{
+			"65535",
+			65535,
```
Comment (GeorgeTsagk) [inline cmd/lncli/commands_test.go:106]: Why not re-use `math.MaxUint16` here?

File: cmd/lncli/commands_test.go [hunk 10]
```diff
@@ -68,3 +71,64 @@ func TestParseChanPoint(t *testing.T) {
...
+			0,
+			true,
+			fmt.Sprintf("time_lock_delta is too big, "+
+				"max value is %d", lnd.MaxTimeLockDelta),
+		},
+		{
+			"18446744073709551616",
+			0,
+			true,
+			fmt.Sprint("fail to parse time_lock_delta:" +
```
Comment (GeorgeTsagk) [inline cmd/lncli/commands_test.go:121]: nit: no space between `+` and string, also can add the string space on this line for consistency

**Review by GeorgeTsagk — COMMENTED** [review]
Hey! Cool changes, sneaky bug 🐞

File: cmd/lncli/commands_test.go (hunk 9 above)
Comment (GeorgeTsagk) [reply cmd/lncli/commands_test.go:106]: Also for uint64, you can use something like this
```
strconv.FormatUint(math.MaxUint64, 10)
```

this way it's more clear that one case checks the uint64 limits

File: cmd/lncli/commands_test.go (hunk 10 above)
Comment (eval-exec) [reply cmd/lncli/commands_test.go:121]: This value: `18446744073709551616` is bigger than `math.MaxUint64`, so I just write a string here.

**Comment by eval-exec** [comment]
@guggero Hello, could you please trigger the CI action. Thank you. :heart:

**Comment by ellemouton** [comment]
@eval-exec , you need to remove the `[skip-ci]` directives in your commit titles for the CI to run

File: cmd/lncli/commands_test.go [hunk 11]
```diff
@@ -68,3 +73,64 @@ func TestParseChanPoint(t *testing.T) {
...
+func TestParseTimeLockDelta(t *testing.T) {
+	t.Parallel()
+	testCases := []struct {
+		timeLockDeltaStr      string
+		expectedTimeLockDelta uint16
+		expectErr             bool
+		expectedErrContent    string
+	}{
+		{
+			"-1",
```
Comment (ellemouton) [inline cmd/lncli/commands_test.go:88]: please use named variables. You then also dont need to set default values :)

Comment (eval-exec) [reply cmd/lncli/commands_test.go:88]: Thank you. :heart:

**Comment by eval-exec** [comment]
https://github.com/lightningnetwork/lnd/actions/runs/3996088114/jobs/6855758636
https://github.com/lightningnetwork/lnd/actions/runs/3996088114/jobs/6855758779
These CI actions are failed.

**Comment by ellemouton** [comment]
the coverage one is expected to fail at the moment (pending https://github.com/lightningnetwork/lnd/pull/7252)

The other one I have just re-run to see if it fails consistently or if it is just a flake.

The linter one needs to be fixed too though and you also need to add a note to the release notes

**Comment by ellemouton** [comment]
Looking good @eval-exec ! Just needs a merge conflict fix now :)

**Comment by eval-exec** [comment]
> Looking good @eval-exec ! Just needs a merge conflict fix now :)

Hello, merge conflict has fixed now. :smile:

**Review by GeorgeTsagk — APPROVED** [review]
LGTM :100: 

Some CI failures are probably flakes, overall looking good :)

File: config.go [hunk 12]
```diff
@@ -98,6 +99,10 @@ const (
 	// HTLCs on our channels.
 	minTimeLockDelta = routing.MinCLTVDelta
 
+	// MaxTimeLockDelta is the maximum CLTV delta that can be applied to
+	// forwarded HTLCs.
+	MaxTimeLockDelta = math.MaxUint16
```
Comment (ellemouton) [inline config.go:104]: i think this should be a constant in the `routing` package where `MinCLTVDelta` is also currently defined. 

Then we can replace [this](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/addinvoice.go#L351) check with that constant too.

File: rpcserver.go [hunk 13]
```diff
@@ -6815,6 +6815,12 @@ func (r *rpcServer) UpdateChannelPolicy(ctx context.Context,
 			minTimeLockDelta)
 	}
 
+	if req.TimeLockDelta > uint32(MaxTimeLockDelta) {
```
Comment (ellemouton) [inline rpcserver.go:6818]: nit: can use `if {} else {}` since both of these will never be true at the same time

File: cmd/lncli/commands.go [hunk 14]
```diff
@@ -2070,6 +2071,25 @@ func parseChanPoint(s string) (*lnrpc.ChannelPoint, error) {
...
+	)
+	if err != nil {
+		return 0, fmt.Errorf("failed to parse time_lock_delta: %s "+
+			"to uint64, err: %v", timeLockDeltaStr, err)
+	}
+
+	if timeLockDeltaUnCheck > uint64(lnd.MaxTimeLockDelta) {
+		return 0, fmt.Errorf("time_lock_delta is too big, "+
+			"max value is %d", lnd.MaxTimeLockDelta)
+	}
```
Comment (ellemouton) [inline cmd/lncli/commands.go:2088]: dont think we need this check on this side if it will already be checked on the server side.

File: cmd/lncli/commands.go [hunk 15]
```diff
@@ -2117,12 +2137,15 @@ func updateChannelPolicy(ctx *cli.Context) error {
 
 	switch {
 	case ctx.IsSet("time_lock_delta"):
-		timeLockDelta = ctx.Int64("time_lock_delta")
+		timeLockDeltaStr := ctx.String("time_lock_delta")
```
Comment (ellemouton) [inline cmd/lncli/commands.go:2140]: why are we parsing a `Uint64` flag as a string?

**Review by ellemouton — COMMENTED** [review]
tAck! Just a few questions around implementation

File: cmd/lncli/commands.go (hunk 15 above)
Comment (eval-exec) [reply cmd/lncli/commands.go:2140]: when `"time_lock_delta"` is bigger than `max(int64)`, `ctx.Int64()` will return `0`:

```go
// Int64 looks up the value of a local Int64Flag, returns
// 0 if not found
func (c *Context) Int64(name string) int64 {
	return lookupInt64(name, c.flagSet)
}

func lookupInt64(name string, set *flag.FlagSet) int64 {
	f := set.Lookup(name)
	if f != nil {
		parsed, err := strconv.ParseInt(f.Value.String(), 0, 64)
		if err != nil {
			return 0
		}
		return parsed
	}
	return 0
}

```

Comment (ellemouton) [reply cmd/lncli/commands.go:2140]: but then why bother with making the flat Uint64 at all? Why not string? and also , does this issue not just apply to all our Uint flags?

Comment (eval-exec) [reply cmd/lncli/commands.go:2140]: > 

make the flag to `Uint64` to hint user the `time_lock_delta` is an unsigned integer.

File: cmd/lncli/commands.go (hunk 14 above)
Comment (eval-exec) [reply cmd/lncli/commands.go:2088]: Perhaps it is better to keep this check, because the code on the server side may not be updated in time.

File: cmd/lncli/commands.go (hunk 15 above)
Comment (eval-exec) [reply cmd/lncli/commands.go:2140]: >  does this issue not just apply to all our Uint flags

yes, same for `ctx.Bool()` and `ctx.Float64()`, all of them have this issue.

Comment (ellemouton) [reply cmd/lncli/commands.go:2140]: gotcha

File: cmd/lncli/commands.go (hunk 14 above)
Comment (ellemouton) [reply cmd/lncli/commands.go:2088]: I think it is usually expected that the server updates before the client does? In my mind, "business logic" checks like this should be left to the server. 

The other reason for removing it would be to make this function more generic so that it can be used to check overflows of other parameters.

**Review by ellemouton — APPROVED** [review]
tACK. Thanks for the fix @eval-exec 👍 

Im approving this PR as it does fix the linked issue. But think it is worth just making a note of the wider issue: 
This only fixes the overflow for one parameter. We should either consider switching the CLI over to a lib that does not silently fail when these overflows happen (something like [cobra](https://cobra.dev/) _or_ we should consider switching all our parameters to strings so that we can do the check our selves. But this is outside the scope of this PR.

File: cmd/lncli/commands.go (hunk 14 above)
Comment (eval-exec) [reply cmd/lncli/commands.go:2088]: Agree with you. Will remove it.

**Comment by ellemouton** [comment]
> The CI failed, don't know why.

that failure was unrelated to your PR :) it should be fixed in master now so should work now

**Review by ellemouton — APPROVED** [review]
looks good! perhaps just tweak your first commit title to be more aligned with our guidelines? I think a commit message would also be nice. 

(ps: no need to re-request review once already approved)

File: cmd/lncli/commands_test.go [hunk 16]
```diff
@@ -68,3 +72,53 @@ func TestParseChanPoint(t *testing.T) {
...
+			expectedErrContent: fmt.Sprint(
+				"failed to parse time_lock_delta:" +
+					" 18446744073709551616 to uint64"),
+		},
+	}
+	for _, tc := range testCases {
+		timeLockDelta, err := parseTimeLockDelta(tc.timeLockDeltaStr)
+		require.Equal(t, tc.expectedTimeLockDelta, timeLockDelta)
+		if tc.expectErr {
+			assert.ErrorContains(t, err, tc.expectedErrContent)
```
Comment (ellemouton) [inline cmd/lncli/commands_test.go:119]: please use `require` instead of `assert` 🙏

**Comment by eval-exec** [comment]
> 

Thank you. I added `rpcserver: ` to first commit title.

File: cmd/lncli/commands_test.go (hunk 16 above)
Comment (eval-exec) [reply cmd/lncli/commands_test.go]: Done. :heart:

**Comment by ellemouton** [comment]
>  I added rpcserver:  to first commit title

I dont see this change?

**Comment by eval-exec** [comment]
> > I added rpcserver:  to first commit title
> 
> I dont see this change?

Sorry, I updated now.

**Comment by ellemouton** [comment]
@eval-exec - can you change the base of this to the `0-16-1-staging` branch please (see the `edit` button top right) and then rebase?

**Comment by eval-exec** [comment]
> @eval-exec - can you change the base of this to the `0-16-1-staging` branch please (see the `edit` button top right) and then rebase?

Done  :heart:

File: cmd/lncli/commands.go [hunk 17]
```diff
@@ -2080,6 +2080,20 @@ func parseChanPoint(s string) (*lnrpc.ChannelPoint, error) {
...
+func parseTimeLockDelta(timeLockDeltaStr string) (uint16, error) {
+	timeLockDeltaUnCheck, err := strconv.ParseUint(
+		timeLockDeltaStr, 10, 64,
+	)
+	if err != nil {
+		return 0, fmt.Errorf("failed to parse time_lock_delta: %s "+
+			"to uint64, err: %v", timeLockDeltaStr, err)
+	}
+
+	return uint16(timeLockDeltaUnCheck), nil
```
Comment (guggero) [inline cmd/lncli/commands.go:2094]: I think we should check that the value isn't greater than `uint64(routing.MaxCLTVDelta)` before we cast to `uint16`. Otherwise a value greater than `uint16` won't result in an error but a possibly unexpected high/truncated `uint16` value.

File: config.go [hunk 18]
```diff
@@ -98,6 +98,10 @@ const (
 	// HTLCs on our channels.
 	minTimeLockDelta = routing.MinCLTVDelta
 
+	// MaxTimeLockDelta is the maximum CLTV delta that can be applied to
+	// forwarded HTLCs.
+	MaxTimeLockDelta = routing.MaxCLTVDelta
```
Comment (guggero) [inline config.go:103]: Do we need an extra alias here? Can't we just use `routing.MaxCLTVDelta` in the `rpcserver.go`?

File: docs/release-notes/release-notes-0.16.0.md [hunk 19]
```diff
@@ -369,6 +369,9 @@ in the lnwire package](https://github.com/lightningnetwork/lnd/pull/7303)
 * [Allow `--stateless_init` mode to be used for watch-only
   wallets](https://github.com/lightningnetwork/lnd/pull/7462).
 
+* [Add time_lock_delta overflow check for UpdateChannelPolicy](https://github.com/lightningnetwork/lnd/pull/7350)
```
Comment (guggero) [inline docs/release-notes/release-notes-0.16.0.md:372]: Can you move this to the `release-notes-0.16.1.md` file please?

**Review by guggero — COMMENTED** [review]
Almost there, just a few more requests.

File: config.go (hunk 18 above)
Comment (eval-exec) [reply config.go:103]: I just want to keep the style of `minTimeLockDelta`, because there is a line `minTimeLockDelta = routing.MinCLTVDelta` above in line `99`.

File: cmd/lncli/commands.go (hunk 17 above)
Comment (eval-exec) [reply cmd/lncli/commands.go:2100]: I followed @ellemouton 's review comment: https://github.com/lightningnetwork/lnd/pull/7350#discussion_r1090295163

How about add a condition check : `if timeLockDeltaUnCheck > math.MaxUint16 {` here?

Comment (guggero) [reply cmd/lncli/commands.go:2100]: Yes, that comment wasn't wrong per se. But the cast to `uint16` actually suppresses any errors on the server side, as the value can never be larger than the maximum. This would lead to silent but unexpected behavior.

The current version looks better. But given we now have two constants for this, we should use `routing.MaxCLTVDelata` here instead of `math.MaxUint16`.

Comment (eval-exec) [reply cmd/lncli/commands.go:2100]: Agree, I will update this to use `routing.MaxCLTVDelata`

File: cmd/lncli/commands.go (hunk 14 above)
Comment (guggero) [reply cmd/lncli/commands.go]: I would've agreed with this, **if** the return value of this function was `uint32`. But given it's `uint16` that can never be larger than the allowed maximum value. Instead a too large value would silently be converted/truncated to an `uint16` value, which might lead to very unexpected behavior.

File: cmd/lncli/commands.go (hunk 17 above)
Comment (eval-exec) [reply cmd/lncli/commands.go:2100]: Updated.

**Comment by eval-exec** [comment]
I think this PR is ready to merge.

**Comment by ellemouton** [comment]
@eval-exec   - it will only be merged once all the CI checks have completed.
