### PR TITLE
invoicesrpc: limit first pass of hop hint selection

### LINKED ISSUE #6225: lncli addholdinvoice --> invoice is too large
### Background

Adding a hold invoice on a node with many private channels (hundreds) leads to invoice is too large

### Your environment

* version of `lnd` 0.14.1-beta
* which operating system (`uname -a` on *Nix) 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend bitcoin-22.0
* any other relevant environment details: I have around 400 private channels

### Steps to reproduce

$ lncli addholdinvoice --amt 100 --memo test1 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
[lncli] rpc error: code = Unknown desc = invoice is too large

### Expected behaviour

Get a hold invoice ;)

### Actual behaviour

Get `invoice is too large` notification

image

### PR DESCRIPTION
**Pull request by carlaKC**
## Change Description
This PR adds limits to our first pass of adding hop hints to invoices. 
- Previously: if we had 100 channels where `remoteBalance > invoice amount` , we would add 100 hints
- Now: we will add up to 20 channels, or enough hints to each incoming bandwidth 2 * invoice amount

The first commit also updates one of our existing itests to ensure we have hop hint coverage, where previously we said that we were adding coverage but did not check that our invoice actually had hints. 

Fixes #6225.

## Steps to Test
There is an itest reproducing this issue on [this branch](https://github.com/carlaKC/lnd/tree/6225-invoicetoolarge). 
- Run the itest against master -> fails with "invoice too large"
- Run the itest against this branch -> only adds 20 hop hints + passes

Note: the itest takes quite long because it creates many channels. It can be decreased to create > 20 channels to demonstrate that we just create too many hints.

### CODE REVIEW

File: lnrpc/invoicesrpc/addinvoice.go [hunk 1]
```diff
@@ -664,18 +705,23 @@ func SelectHopHints(amtMSat lnwire.MilliSatoshi, cfg *SelectHopHintsCfg,
...
+			len(hopHints), numMaxHophints, hopHintFactor, amtMSat,
+			totalHintBandwidth,
+		)
+		if enoughHopHints {
+			log.Debugf("Second pass of hop selection has " +
+				"sufficient hints")
+
+			return hopHints
+		}
+
```
Comment (Crypt-iQ) [inline lnrpc/invoicesrpc/addinvoice.go:724]: nit: seems like the below if statement can be removed now. would be better than omitting the call to sufficienthints since its better to house the logic in the same place. not really necessary for this pull though

File: lnrpc/invoicesrpc/addinvoice_test.go [hunk 2]
```diff
@@ -577,3 +569,57 @@ func TestSelectHopHints(t *testing.T) {
...
+			name:       "enough hints",
+			numHints:   3,
+			maxHints:   3,
+			sufficient: true,
+		},
+		{
+			name:     "not enough hints, insufficient bandwidth",
+			numHints: 1,
+			maxHints: 3,
+			// We want at least 600, and we have enough.
```
Comment (Crypt-iQ) [inline lnrpc/invoicesrpc/addinvoice_test.go:608]: s/600/200

**Review by Crypt-iQ — COMMENTED** [review]
LGTM 🎧 
leaving this here in case somebody else decides to work on this in the future:
- if we were to clamp down on heap allocations during decoding, theoretically we wouldn't need such low limits. there is the qr code limit but not all zpay32 invoices need to follow that

File: lnrpc/invoicesrpc/addinvoice.go (hunk 1 above)
Comment (carlaKC) [reply lnrpc/invoicesrpc/addinvoice.go:724]: yeah, can be! forgot to delete.

**Review by Crypt-iQ — APPROVED** [review]

**Review by bhandras — APPROVED** [review]
Nice catch! LGTM :tada:
