### PR TITLE
routing: add chans rejected due to failed chain validation to zombie index

### LINKED ISSUE #5191: High CPU spikes with v0.12.1-beta
### Background

We have high CPU spikes on the exact 30 minute mark of most hours throughout the day. Seems like some cron/batch process?

### Your environment

* version of `lnd`

v0.12.1-beta

* which operating system (`uname -a` on *Nix)

ubuntu 20.04

* version of `btcd`, `bitcoind`, or other backend

bitcoind (zmq) 0.21.0

* any other relevant environment details

LND is the cause of the CPU spikes verified by running `htop` during one of the spikes.
Logs don't show anything that constitutes a pattern with the spikes. 
Running an EC2 ubuntu instance t3.medium. (2 CPU, 4 GB RAM)

### Steps to reproduce
run 0.12.1-beta - using docker image

### Expected behaviour

Maybe CPU spikes every week? for auto db compaction, but not every hour.

________________
Any chance you know why this is happening?, or would you be able to instruct on how to get more information to help debug this?

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we start to add any channels that fail the normal chain
validation to the zombie index. With this change, we'll ensure that we
won't continue to re-process the same set of spent channels over and
over again.

Fixes #5191.

### CODE REVIEW

File: routing/router.go [hunk 1]
```diff
@@ -1261,7 +1261,7 @@ func (r *ChannelRouter) processUpdate(msg interface{},
 				"existence: %v", err)
 		}
 		if isZombie {
-			return newErrf(ErrIgnored, "ignoring msg for zombie "+
+			return newErrf(ErrZombie, "ignoring msg for zombie "+
```
Comment (Roasbeef) [inline routing/router.go:1264]: I don't _think_ this should cause any issues...

Can remove it if wanted though, just felt like we should start to distinguish outdated channel updates from zombies. I think it's the case though that a zombie shouldn't even get this far down as the gossiper filters it out at an earlier step.

File: channeldb/graph.go [hunk 2]
```diff
@@ -3347,6 +3347,37 @@ func (c *ChannelGraph) NewChannelEdgePolicy() *ChannelEdgePolicy {
...
+	err := kvdb.Batch(c.db, func(tx kvdb.RwTx) error {
+		edges := tx.ReadWriteBucket(edgeBucket)
+		if edges == nil {
+			return ErrGraphNoEdgesFound
+		}
+		zombieIndex := edges.NestedReadWriteBucket(zombieBucket)
+
+		// If there's no zombie index, then we couldn't have marked an
+		// edge as a zombie in the first place.
+		if zombieIndex == nil {
```
Comment (wpaulino) [inline channeldb/graph.go:3365]: I don't think this applies here? We should use `CreateIfNotExists` in case an edge has never been marked as a zombie before this.

File: routing/router.go (hunk 1 above)
Comment (wpaulino) [reply routing/router.go:1264]: Nothing stops an implementation from just sending arbitrary gossip to us, so we should look for any places that depend on `ErrIgnored` just to be safe (gossiper and router come to mind) and see if `ErrZombie` applies there as well.

File: routing/router.go [hunk 3]
```diff
@@ -1292,6 +1292,21 @@ func (r *ChannelRouter) processUpdate(msg interface{},
...
 		fundingTx, err := r.fetchFundingTx(&channelID)
 		if err != nil {
+			// If the funding transaction isn't found at all, then
+			// we'll mark the edge itself as a zombie so we don't
+			// continue to request it.
+			//
+			// TODO(roasbeef): mark as zero if strict?
+			zErr := r.cfg.Graph.MarkEdgeZombie(
+				msg.ChannelID, msg.NodeKey1Bytes,
+				msg.NodeKey2Bytes,
```
Comment (wpaulino) [inline routing/router.go:1302]: Is it safe to mark zero pubkeys here even without running in strict mode? The channel doesn't have a valid UTXO backing it, so it could never be resurrected anyway.

File: routing/router_test.go [hunk 4]
```diff
@@ -3109,3 +3109,114 @@ func TestBuildRoute(t *testing.T) {
...
+	_, _, _, isZombie, err := ctx.graph.HasChannelEdge(
+		edge.ChannelID,
+	)
+	require.True(t, isZombie, "edge should be marked as zombie")
+}
+
+// TestChannelOnChainRejectionZombie tests that if we fail validating a channel
+// due to some sort of on-chain rejection (no funding transaction, or invalid
+// UTXO), then we'll mark the channel as a zombie.
+func TestChannelOnChainRejectionZombie(t *testing.T) {
```
Comment (wpaulino) [inline routing/router_test.go:3195]: :+1:

**Review by wpaulino — COMMENTED** [review]
Linter failures:
>routing/router_test.go:3186:21: SA4006: this value of `err` is never used (staticcheck)
	_, _, _, isZombie, err := ctx.graph.HasChannelEdge(
>
>routing/router_test.go:3219:39: `teh` is a misspelling of `the` (misspell)
	// Instead now, we'll remove it from teh set of UTXOs which should

File: routing/router.go (hunk 3 above)
Comment (Roasbeef) [reply routing/router.go:1302]: What strict mode started to do was modify the values stored here to enforce that the non-blank pubkey was used here for resurrection: https://github.com/lightningnetwork/lnd/pull/5138/commits/f5cf6a0b70965de82c5d9947e0d075cdfefdc03b. So this should be fine IIUC

File: routing/router.go (hunk 1 above)
Comment (Roasbeef) [reply routing/router.go:1264]: I think I'll just remove it to isolate the set of changes in this diff.

File: channeldb/graph.go (hunk 2 above)
Comment (Roasbeef) [reply channeldb/graph.go]: Fixed.

File: routing/router.go (hunk 3 above)
Comment (wpaulino) [reply routing/router.go:1302]: Let's mark both keys as zero then? Saves space (66 bytes per entry) and makes sure we never resurrect them.

Comment (Roasbeef) [reply routing/router.go]: We'll still end up writing a `[33]byte{}` so no bytes, saved, but moved to using blank keys so they can't be resurrected.

Comment (Roasbeef) [reply routing/router.go]: Actually, what about the rare case where for w/e reason the RPCs in the pipeline to fetch the funding transaction or UTXO return an error, which means we'll never be able to properly re-validate the channel (assuming it isn't actually spent)?

Comment (Roasbeef) [reply routing/router.go]: Gonna add some new error types so we can isolate the failures.

Comment (Roasbeef) [reply routing/router.go]: If someone ends a like bad block hash (by way of an invalid short channel ID), it'll still be added to the reject cache so we'll only process it a single time within that restart cycle.

Comment (Roasbeef) [reply routing/router.go]: Dug a bit and it'll really only fail when there's something wrong on the node side, added another error case to catch failed funding validation.

**Comment by Roasbeef** [comment]
Added another case to catch an invalid funding transaction, should be ready for review now.

File: channeldb/graph.go [hunk 5]
```diff
@@ -3397,6 +3397,35 @@ func (c *ChannelGraph) NewChannelEdgePolicy() *ChannelEdgePolicy {
...
+				"bucket: %w", err)
+		}
+
+		return markEdgeZombie(zombieIndex, chanID, pubKey1, pubKey2)
+	})
+	if err != nil {
+		return err
+	}
+
+	c.rejectCache.remove(chanID)
```
Comment (wpaulino) [inline channeldb/graph.go:3423]: Why are we removing from the cache here instead of adding? It could be used within the gossiper when receiving channel announcements/updates for this channel after it being marked as a zombie to fail early. I guess it somewhat overlaps with the gossiper's reject cache?

File: routing/router.go [hunk 6]
```diff
@@ -1369,19 +1386,8 @@ func (r *ChannelRouter) processUpdate(msg interface{},
...
-			// resurrected.
-			var zeroKey [33]byte
-			zErr := r.cfg.Graph.MarkEdgeZombie(
-				msg.ChannelID, zeroKey, zeroKey,
-			)
-			if zErr != nil {
-				return fmt.Errorf("unable to mark spent "+
-					"chan(id=%v) as a zombie: %w", msg.ChannelID,
-					zErr)
+			if err := r.addZombieEdge(msg.ChannelID); err != nil {
```
Comment (wpaulino) [inline routing/router.go:1389]: Looks like we should only do this if we get a utxo not found error or something along those lines? Same applies for `GetBlockHash` and `GetBlock` in `fetchFundingTx`. This would prevent marking a valid edge as a non-resurrectable zombie if the RPC connection closes for whatever reason.

File: channeldb/graph.go (hunk 5 above)
Comment (Roasbeef) [reply channeldb/graph.go:3423]: Mainly copying the existing logic that removes items from the cache once they're deleted, modified. AFAICT, rn the cache is only read in `ChanUpdatesInHorizon`, but we won't ever iterate over these new zombie channels as they weren't ever added to the channel graph.

File: routing/router.go (hunk 6 above)
Comment (Roasbeef) [reply routing/router.go]: Ah yeh I dug into this a bit, but then forgot that we return a specific error on the `lnd` side if the UTXO is indeed unspent, fixed!

File: routing/router.go [hunk 7]
```diff
@@ -1309,8 +1326,17 @@ func (r *ChannelRouter) processUpdate(msg interface{},
 		channelID := lnwire.NewShortChanIDFromInt(msg.ChannelID)
 		fundingTx, err := r.fetchFundingTx(&channelID)
 		if err != nil {
-			return errors.Errorf("unable to fetch funding tx for "+
-				"chan_id=%v: %v", msg.ChannelID, err)
+			// If the funding transaction isn't found at all, then
+			// we'll mark the edge itself as a zombie so we don't
+			// continue to request it. We use the "zero key" for
+			// both node pubkeys so this edge can't be resurrected.
+			zErr := r.addZombieEdge(msg.ChannelID)
```
Comment (wpaulino) [inline routing/router.go:1333]: Similar to the error handling for `GetUtxo`, what about `GetBlockHash` and `GetBlock`? Unlikely to fail in most cases, but there's a slight gap where if the backend becomes unavailable, the health check hasn't fired yet, and a wave of new gossip arrives, then we'll never be able to process/resurrect those channels. We don't have a consistent error for `block not found` across all backends, so might be a bit more involved.

Comment (Roasbeef) [reply routing/router.go:1333]: I think we can account for this by specifying the pubkeys as normal, this way we'll eventually hear about the channels again causing them to be resurrected.

Comment (Roasbeef) [reply routing/router.go]: Pushed up a new commit to pattern match on errors based on commonalities between `btcd` the `bitcoind` errors.

File: routing/router.go [hunk 8]
```diff
@@ -1326,25 +1342,21 @@ func (r *ChannelRouter) processUpdate(msg interface{},
...
 			case strings.Contains(err.Error(), "out of range"):
-				// If the funding transaction isn't found at all, then
-				// we'll mark the edge itself as a zombie so we don't
-				// continue to request it. We use the "zero key" for
-				// both node pubkeys so this edge can't be resurrected.
-				var zeroKey [33]byte
-				zErr := r.cfg.Graph.MarkEdgeZombie(
-					msg.ChannelID, zeroKey, zeroKey,
-				)
+				// If the funding transaction isn't found at
```
Comment (wpaulino) [inline routing/router.go:1345]: Should also add here the case where the transaction index is greater than the number of transactions in the block.

Comment (Roasbeef) [reply routing/router.go:1345]: This is caught as is, since the "out of range" sub-string will match this case.

**Review by wpaulino — APPROVED** [review]

**Comment by Roasbeef** [comment]
Ping @cfromknecht

File: routing/router_test.go [hunk 9]
```diff
@@ -3136,3 +3136,115 @@ func TestBuildRoute(t *testing.T) {
 		t.Fatalf("unexpected no channel error node")
 	}
 }
+
+// edgeCreationModifier is an enum-like type used to modify steps that are
+// skipped when creating a channel in the test context.
+type edgeCreationModifier uint8
```
Comment (cfromknecht) [inline routing/router_test.go:3142]: nice test harness 😎

File: routing/router.go [hunk 10]
```diff
@@ -1309,6 +1311,37 @@ func (r *ChannelRouter) processUpdate(msg interface{},
...
+			// match for the relevant errors.
+			//
+			// * btcd:
+			//    * https://github.com/btcsuite/btcd/blob/master/rpcserver.go#L1316
+			//    * https://github.com/btcsuite/btcd/blob/master/rpcserver.go#L1086
+			// * bitcoind:
+			//    * https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/rpc/blockchain.cpp#L770
+			//     * https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/rpc/blockchain.cpp#L954
+			switch {
+			case strings.Contains(err.Error(), "not found"):
```
Comment (cfromknecht) [inline routing/router.go:1341]: i'm a little hesitant to introduce string parsing on errors as we've been bitten in the past, but i think that's okay here since it is mostly an optimization 👍

File: channeldb/graph.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply channeldb/graph.go:3423]: Added the locking at the top, I don't think this'll be an issue from a contention perspective (other non `ChannelGraph` update transactions can be batched) as ideally once users update the process these zombies once, then never do again.

File: routing/router.go (hunk 10 above)
Comment (Roasbeef) [reply routing/router.go:1341]: Yeah I feel the same, but in this case it's relatively contained. What we _really_ need to do is do all this error code massaging at the `rpcclient` level, so we can have it apply to both `bitcoind` and `btcd`, and the other projects that leverage the library can help maintain the set of error codes.
