### PR TITLE
channeldb: add new migration to finalize invoice migration for outgoi…

### LINKED ISSUE #1538: lnd crashes after a gRPC client made an InvoiceSubscription call.
### Background

I'm using LND with various thin/web wrappers. After updating to latest code in master it crashes every time a client is connected and tries to subscribe to invoices.

### Your environment

lnd version 0.4.2-beta commit=93207608b5a433ddfc15cfe56bb060e1c720166e
Linux 4.4.0-124-generic x86_64 x86_64 x86_64 GNU/Linux
Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255

### Steps to reproduce

1) Update lnd to 93207608b5a433ddfc15cfe56bb060e1c720166e
2) make gRPC InvoiceSubscription request

### Expected behaviour

not crashing :)

### Actual behaviour

fatal error: runtime: out of memory

### LINKED ISSUE #1546: panic: runtime error: makeslice: len out of range
### Background
after running for a few minutes, lnd crashes with panic
panic after updating to latest commt

`panic:` runtime error: makeslice: len out of range
goroutine 53983 [running]:
github.com/lightningnetwork/lnd/channeldb.deserializeOutgoingPayment(0xb90910, 0x13ca5bc0, 0x8, 0xa637a088, 0x9d)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:192 +0x1a8
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchAllPayments.func1.1(0xa637a080, 0x8, 0x8, 0xa637a088, 0x9d, 0x9d, 0x9d, 0x115e8e0c)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:103 +0x84
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).ForEach(0x13ca5ba0, 0x1322fad8, 0x8, 0x8)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:388 +0xec
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchAllPayments.func1(0x115e8e00, 0xae1668, 0x115e8e00)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:95 +0x74
github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).View(0x1153a000, 0x1322fb18, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:699 +0x80
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchAllPayments(0x1143c050, 0x97b709, 0xe, 0x0, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/channeldb/payments.go:89 +0x4c
main.(*rpcServer).ListPayments(0x114dff40, 0xb962c8, 0x13c24740, 0x10a4624, 0x114dff40, 0x124ecb10, 0x114aa000)
	/home/admin/go/src/github.com/lightningnetwork/lnd/rpcserver.go:3572 +0x74
github.com/lightningnetwork/lnd/lnrpc._Lightning_ListPayments_Handler.func1(0xb962c8, 0x13c24740, 0x8ec508, 0x10a4624, 0x1, 0x1, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6684 +0x68
github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0xb962c8, 0x13c24740, 0x8ec508, 0x10a4624, 0x124ecb00, 0x124ecb10, 0x13a39970, 0x5a7078, 0x13a39970, 0x13ca5960)
	/home/admin/go/src/github.com/lightningnetwork/lnd/macaroons/service.go:117 +0x108
github.com/lightningnetwork/lnd/lnrpc._Lightning_ListPayments_Handler(0x9676c8, 0x114dff40, 0xb962c8, 0x13c24740, 0x13a39950, 0x1162d810, 0x0, 0x0, 0xe1a92aa3, 0x65251098)
	/home/admin/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6686 +0x124
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0x113b4000, 0xb98fb0, 0x113a04b0, 0x1574c2d0, 0x115be2e0, 0x10779dc, 0x13ca5960, 0x0, 0x0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x7c0
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0x113b4000, 0xb98fb0, 0x113a04b0, 0x1574c2d0, 0x13ca5960)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1054
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0x11328f00, 0x113b4000, 0xb98fb0, 0x113a04b0, 0x1574c2d0)
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x7c
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/admin/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0x7c
`

### Your environment
MAINNET
Version 0.4.2-beta commit=93207608b5a433ddfc15cfe56bb060e1c720166e
4.15.0-20-genericx86_64 GNU/Linux
bitcoind 0.16

[LOGS](https://www.dropbox.com/s/xs78iz9laaczney/lnd.log?dl=0)

### PR DESCRIPTION
**Pull request by Roasbeef**
…ng payments

In this commit, we migrate the database away from a partially migrated
state. In a prior commit, we migrated the database in order to update
the Invoice struct with three new fields: add index, settle index, paid
amt.  However, it was overlooked that the OutgoingPayment struct also
embedded an Invoice within it. As a result, nodes that upgraded to the
first migration found themselves unable to start up, or call
listpayments, as the internal invoice within the OutgoignPayment hadn't
yet been updated.  This would result in an OOM typically as we went to
allocate a slice with a integer that should have been small, but may
have ended up actually being a set of random bytes, so a very large
number.

In this commit, we finish the DB migration by also migrating the
internal invoice within each OutgoingPayment.

Fixes #1538.
Fixes #1546.

### CODE REVIEW

File: channeldb/migrations.go [hunk 1]
```diff
@@ -231,3 +231,69 @@ func migrateInvoiceTimeSeries(tx *bolt.Tx) error {
...
+
+		paymentCopy = append(
+			paymentCopy, paymentBytes[endOfInvoiceIndex:]...,
+		)
+
+		// At this point, we now have the new format of the outgoing
+		// payments, we'll attempt to deseirliaze it to ensure the
+		// bytes are properly formatted.
+		paymentReader := bytes.NewReader(paymentCopy)
+		_, err := deserializeOutgoingPayment(paymentReader)
```
Comment (cfromknecht) [inline channeldb/migrations.go]: Assuming this call is just to double check that our reconstructed invoice satisfies the new format?

Comment (Roasbeef) [reply channeldb/migrations.go]: Yep! Helped me find some bugs during testing.

**Comment by cfromknecht** [comment]
Was able to recreate the issue, and can confirm that this fixes the issue on the node which originally OOM'd after migration 2.

File: channeldb/migrations.go [hunk 2]
```diff
@@ -231,3 +231,69 @@ func migrateInvoiceTimeSeries(tx *bolt.Tx) error {
...
 }
+
+// migrateInvoiceTimeSeriesOutgoingPayments is a follow up to the
+// migrateInvoiceTimeSeries migration. As at the time of writing, the
+// OutgoingPayment struct embeddeds an instance of the Invoice struct. As a
+// result, we also need to migrate the internal invoice to the new format.
+func migrateInvoiceTimeSeriesOutgoingPayments(tx *bolt.Tx) error {
+	payBucket := tx.Bucket(paymentBucket)
+	if payBucket == nil {
+		return ErrNoPaymentsCreated
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply channeldb/migrations.go]: Fixed!

File: channeldb/migrations.go [hunk 3]
```diff
@@ -231,3 +231,73 @@ func migrateInvoiceTimeSeries(tx *bolt.Tx) error {
...
+		// With the prefix extracted, we'll copy over the invoice, and
+		// also add padding for the new 24 bytes of fields, and finally
+		// append the remainder of the outoing payment.
+		paymentCopy := make([]byte, len(invoiceBytes))
+		copy(paymentCopy[:], invoiceBytes)
+
+		padding := bytes.Repeat([]byte{0}, 24)
+		paymentCopy = append(paymentCopy, padding...)
+
+		paymentCopy = append(
```
Comment (halseth) [inline channeldb/migrations.go]: style nit: might be easier to read if written as
```go
var paymentCopy []byte
paymentCopy = append(paymentCopy, paymentBytes[:endOfInvoiceIndex]...)
paymentCopy = append(paymentCopy, padding...)
paymentCopy = append(paymentCopy, paymentBytes[endOfInvoiceIndex:]...)
```

File: channeldb/migrations.go [hunk 4]
```diff
@@ -231,3 +231,73 @@ func migrateInvoiceTimeSeries(tx *bolt.Tx) error {
...
+			paymentCopy, paymentBytes[endOfInvoiceIndex:]...,
+		)
+
+		// At this point, we now have the new format of the outgoing
+		// payments, we'll attempt to deseirliaze it to ensure the
+		// bytes are properly formatted.
+		paymentReader := bytes.NewReader(paymentCopy)
+		_, err := deserializeOutgoingPayment(paymentReader)
+		if err != nil {
+			return fmt.Errorf("unable to desrialize payment: %v", err)
```
Comment (halseth) [inline channeldb/migrations.go]: nit: deserialize

**Comment by Roasbeef** [comment]
PTAL!
