### PR TITLE
contractcourt: fix potential panic during startup

### LINKED ISSUE #7935: [bug]: invalid memory address or nil pointer dereference
### Background

After upgrading my lnd node to `v0.17.0-beta.rc1`, my node fails to startup with a segmentation violation.

### Your environment

* version of `lnd`: `v0.17.0-beta.rc1`
* which operating system (`uname -a` on *Nix): `Linux 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend: `bitcoind`
* any other relevant environment details

### Steps to reproduce

```sh
lnd --accept-keysend --profile 6061 --tor.active --tor.v3 --protocol.wumbo-channels --db.prune-revocation
...
lncli unlock
```

### Expected behaviour

I expect lnd to startup without a segmentation violation.

### Actual behaviour

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcf7a9e]

goroutine 1 [running]:
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).relaunchResolvers(0xc000598580, 0x0, 0x0?)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:739 +0x6fe
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).Start(0x146e4a0?, 0xc001406e40)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:560 +0x665
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).Start(0xc002771e80?)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:707 +0x11fe
github.com/lightningnetwork/lnd.(*server).Start.func1()
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:1987 +0x19ff
sync.(*Once).doSlow(0x3?, 0x16d9432?)
        /usr/lib/go-1.19/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/lib/go-1.19/src/sync/once.go:65
github.com/lightningnetwork/lnd.(*server).Start(0xc4998?)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:1862 +0x76
github.com/lightningnetwork/lnd.Main(0xc0003fa580, {{0x0?, 0xc000006340?, 0xc000066738?}}, 0xc000120fc0, {0xc0000906c0, 0xc000100720, 0xc000100780, 0xc0001007e0, {0x0}})
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/lnd.go:676 +0x3df4
main.main()
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x205
```

### PR DESCRIPTION
**Pull request by yyforyongyu**
Related to this fix https://github.com/lightningnetwork/lnd/commit/5a285827194f85af10c138da735b35a1faee97aa, we may not have the historical data for old channels so we skip it here too.

Fixes #7935

### CODE REVIEW

**Review by guggero — APPROVED** [review]
LGTM :tada:

File: contractcourt/chain_arbitrator.go [hunk 1]
```diff
@@ -262,6 +262,13 @@ type arbChannel struct {
 	c *ChainArbitrator
 }
 
+// ChanType returns the channel commitment type.
+//
+// NOTE: Part of the ArbChannel interface.
+func (a *arbChannel) ChanType() channeldb.ChannelType {
+	return a.channel.ChanType
```
Comment (GeorgeTsagk) [inline contractcourt/chain_arbitrator.go:269]: Could `a.channel` ever be nil?

Comment (yyforyongyu) [reply contractcourt/chain_arbitrator.go:269]: Shouldn't be since `arbChannel` is created via `getArbChannel` in `newActiveChannelArbitrator`.

**Review by guggero — APPROVED** [review]
Code looks good to me. Though I would like to hear from the user who reported this that the startup is fixed.

**Review by Roasbeef — APPROVED** [review]
LGTM 🦜
