### PR TITLE
routing: report invalid channels in updatechanpolicy call

### LINKED ISSUE #4846: Add more detailed info from updatechanpolicy
### Background
When trying to update the fee rate of a channel using updatechanpolicy, there are often cases where you send an api/cli call, and when you then check the fee rates, for some nodes the policy changed, and other nodes it didnt.

All calls to updatechanpolicy return:
`{}`

### Your environment

* version of `lnd`
'version': '0.11.99-beta commit=v0.11.0-beta-534-g7e298f143425337448f95019234b22849d64aca3', 'commit_hash': '7e298f143425337448f95019234b22849d64aca3'
* which operating system (`uname -a` on *Nix)
linux
* version of `btcd`, `bitcoind`, or other backend
bitcoind
* any other relevant environment details
using 

### Steps to reproduce

Gotchas that I have found:

- min_htlc=1, where remote node only allows min_htlc=1000

- When passing in a bad txid using the rest API

- When the channel is unconfirmed

- When the channel is currently in-active.

### Expected behaviour

It should at least return an error message in cases where it cannot update the channel, and if not show why.

It seems that it might require streaming for something like this to actually return a response though.

### Actual behaviour

Most api calls to updatechanpolicy only return:
`{}`

### PR DESCRIPTION
**Pull request by ErikEk**
Fixes #4846. Detects invalid and pending channels in the updatechanpolicy call.
Returns a failed update policy report if any of following situations occur:
* **When passing in a bad channel point**
* **When channels are unconfirmed**
* **min_htlc < remote min_htlc**
* **local max_htlc > remote max_htlc**
* **max_htlc < min_htlc**

Edit: Expanded the test to include missing channels and policy updates.

Fixes https://github.com/lightningnetwork/lnd/issues/4702

### CODE REVIEW

File: routing/localchans/manager.go [hunk 1]
```diff
@@ -106,6 +110,17 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+	// were not found.
+	if len(chansToUpdate) > 0 {
+		errStr := "can not find channel(s):"
+		for _, chanPoint := range chanPoints {
+			errStr += fmt.Sprintf(" %s:%d",
+				chanPoint.Hash.String(), chanPoint.Index)
+		}
+		return fmt.Errorf(errStr)
+	}
+
```
Comment (ellemouton) [inline routing/localchans/manager.go:123]: would be cool to make the returned error a bit more informative. We can at this point tell if the channel is not found at all or if it is just unconfirmed or inactive. So can do something like this perhaps:

```
if len(chansToUpdate) > 0 {
		var errStr string
		for _, chanPoint := range chanPoints {
			channel, err := r.FetchChannel(chanPoint)
			if errors.Is(err, channeldb.ErrChannelNotFound) {
				errStr += fmt.Sprintf(
					"channel %s:%d not found; ",
					chanPoint.Hash.String(), chanPoint.Index,
				)
				continue
			}
			if err != nil {
				errStr += fmt.Sprintf(
					"error fetching channel %s:%d; ",
					chanPoint.Hash.String(), chanPoint.Index,
				)
				continue
			}
			if channel.IsPending {
				errStr += fmt.Sprintf("channel %s:%d is "+
					"not yet confirmed; ",
					chanPoint.Hash.String(), chanPoint.Index)
				continue
			}
			// ...
			// channel inactive perhaps?	
		}
		return fmt.Errorf(errStr)
	}
```

File: routing/localchans/manager.go [hunk 2]
```diff
@@ -76,6 +76,10 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
 			return nil
 		}
 
+		// Mark this channel as found by removing it. chansToUpdate
+		// will be used to report absent channels later on.
+		delete(chansToUpdate, info.ChannelPoint)
+
```
Comment (ellemouton) [inline routing/localchans/manager.go:82]: maybe move this to below the `r.updateEdge()` line so that we can also report back to the user if a channel update could not happen at all (even if the channel was found)

**Review by ellemouton — CHANGES_REQUESTED** [review]
Works as advertised: returns an error message to user if they request channel policy update on a channel that does not exist (bad txid perhaps) or if channel is unconfirmed.

I think the error messages could be a bit more descriptive. The user might panic if we return "channel not found" for a channel that is perhaps just not confirmed. See my suggestions in the commit.

Some nits:  I think your commit message title is a bit long (its gotta be 50 chars or less) and then just add a commit body with a more detailed description (see [contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#model-git-commit-messages)

**Comment by ErikEk** [comment]
@ellemouton Thanks for the review! I like your ideas. Will update the pr this weekend.

File: routing/localchans/manager.go (hunk 1 above)
Comment (ErikEk) [reply routing/localchans/manager.go:123]: We do not loop through any pending channels with `ForAllOutgoingChannels` so it isn't an issue at the moment.

Comment (ErikEk) [reply routing/localchans/manager.go:123]: Great idea. I like it.

File: routing/localchans/manager.go [hunk 3]
```diff
@@ -106,6 +111,36 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
 		return err
 	}
 
+	// Return an error if any of the channels in chansToUpdate
+	// were not found.
+	if len(chansToUpdate) > 0 {
+		var errStr string
+		for _, chanPoint := range chanPoints {
```
Comment (ellemouton) [inline routing/localchans/manager.go:118]: `for chanPoint := range chansToUpdate {...}`

- Then you dont need to do the length check above
- also removes some unnecessary queries

File: routing/localchans/manager.go [hunk 4]
```diff
@@ -106,6 +111,36 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+					chanPoint.Hash.String(), chanPoint.Index,
+				)
+				continue
+			}
+			if channel.IsPending {
+				errStr += fmt.Sprintf("channel %s:%d is "+
+					"not yet confirmed; ",
+					chanPoint.Hash.String(), chanPoint.Index)
+				continue
+			}
```
Comment (ellemouton) [inline routing/localchans/manager.go:139]: What about the rest of the channels that were not updated but dont fall into the category above? Maybe add a generic error message here for those

**Review by ellemouton — COMMENTED** [review]
Thanks for the updates :) a few more comments from me. Also pls see my comments on commit message in my previous review :)

File: routing/localchans/manager.go (hunk 3 above)
Comment (ErikEk) [reply routing/localchans/manager.go:118]: @ellemouton You're right. Should have seen this myself. Thx.

**Comment by ErikEk** [comment]
Updated the code. Now it also detects inactive channels. See pr description.

File: routing/localchans/manager.go [hunk 5]
```diff
@@ -106,6 +125,40 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+		}
+		errStr += fmt.Sprintf("channel %s:%d could "+
+			"not update its policies; ",
+			chanPoint.Hash.String(), chanPoint.Index)
+	}
+	if errStr != "" {
+		// Report error msg for both invalid and inactive channels.
+		return fmt.Errorf(errStr + errInactiveChans)
+	}
+
```
Comment (ellemouton) [inline routing/localchans/manager.go:161]: Hmmm so the problem here is that if there were also some successful channel updates (`err := r.updateEdge(info.ChannelPoint, edge, newSchema)` above) then we still return here and then dont call `r.UpdateForwardingPolicies(policiesToUpdate)` below. (I think a test for this would be a good idea).

An idea would be to _first_ loop through all the channels-to-update and determine if there are any errors (wrong txid, inactive, pending) and just return an error and include in the error message that no updates were made to _any_ channels . Only if there are no bad apple channels then we go on to `err := r.ForAllOutgoingChannels(func(...`. So then it is an all-or-nothing situation (less ambiguity). Either that or keep track of all the problem channels, let the others update and then return an error naming the problem channels plus a message saying that all other channels were updated successfully. I lean toward the second option since if the user just wants to update all their channels but then a few are inactive then we dont want them to go type out the whole list of channels manually.

**Review by ellemouton — CHANGES_REQUESTED** [review]
Thanks for the updates :)

I have tested all the cases and they work as advertised. 

I have left some nit comments. Also, when making changes remember to run `make lint` and `make unit` to ensure that no tests are broken. This latest change broke `TestManager` since you added a new member to the `Manager` struct but did not init that member in the test. Might also be worth it add tests for your changes (one of my comments includes an idea for a test).

File: routing/localchans/manager.go (hunk 5 above)
Comment (ErikEk) [reply routing/localchans/manager.go:161]: Thanks for the review! I'll remember to run the tests before my next commit + fix the test model.
I agree, the second option is the way to go. I'll edit the error message to clarify what is happening in the background.

File: routing/localchans/manager_test.go [hunk 6]
```diff
@@ -91,13 +96,23 @@ func TestManager(t *testing.T) {
 	forAllOutgoingChannels := func(cb func(*channeldb.ChannelEdgeInfo,
 		*channeldb.ChannelEdgePolicy) error) error {
 
-		return cb(
+		err := cb(
```
Comment (ErikEk) [inline routing/localchans/manager_test.go:99]: Not happy with this. Is there a better way?

File: routing/localchans/manager_test.go [hunk 7]
```diff
@@ -91,13 +96,23 @@ func TestManager(t *testing.T) {
...
+		if err != nil {
+			return err
+		}
+		return cb(
+			&channeldb.ChannelEdgeInfo{
+				Capacity:     chanCapInactive,
+				ChannelPoint: chanPointInactive,
+			},
+			&currentPolicy,
+		)
```
Comment (ErikEk) [inline routing/localchans/manager_test.go:115]: Not happy with this bit. Is there a more elegant solution?

File: routing/localchans/manager.go [hunk 8]
```diff
@@ -106,6 +127,38 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+		}
+		errStr += fmt.Sprintf("channel %s:%d could "+
+			"not update its policies; ",
+			chanPoint.Hash.String(), chanPoint.Index)
+	}
+	if errStr != "" {
+		return fmt.Errorf("policy update failed: %s %s",
+			errStr, errInactiveChans)
+	}
+
```
Comment (ellemouton) [inline routing/localchans/manager.go:161]: there is still the issue here that if some channels were updated successfully and some were invalid then it will return here and not call `r.UpdateForwardingPolicies(policiesToUpdate)` below. I think you can get rid of `errStr` and just rather append these all to `errInvalidChans`.

File: routing/localchans/manager_test.go (hunk 7 above)
Comment (ellemouton) [reply routing/localchans/manager_test.go:115]: How about something like this rather?

```
func TestManager(t *testing.T) {
	t.Parallel()
	
	var (
		chanPointValid    = wire.OutPoint{Hash: chainhash.Hash{1}, Index: 2}
		chanCap           = btcutil.Amount(1000)
		chanPointInactive = wire.OutPoint{Hash: chainhash.Hash{2}, Index: 2}
		chanPointMissing  = wire.OutPoint{Hash: chainhash.Hash{3}, Index: 2}
		maxPendingAmount  = lnwire.MilliSatoshi(999000)
		minHTLC           = lnwire.MilliSatoshi(2000)
	)

	newPolicy := routing.ChannelPolicy{
		FeeSchema: routing.FeeSchema{
			BaseFee: 100,
			FeeRate: 200,
		},
		TimeLockDelta: 80,
		MaxHTLC:       5000,
	}

	currentPolicy := channeldb.ChannelEdgePolicy{
		MinHTLC:      minHTLC,
		MessageFlags: lnwire.ChanUpdateOptionMaxHtlc,
	}

	updateForwardingPolicies := func(
		chanPolicies map[wire.OutPoint]htlcswitch.ForwardingPolicy) {

		if len(chanPolicies) == 0 {
			return
		}

		if len(chanPolicies) != 1 {
			t.Fatal("unexpected number of policies to apply")
		}

		policy := chanPolicies[chanPointValid]
		if policy.TimeLockDelta != newPolicy.TimeLockDelta {
			t.Fatal("unexpected time lock delta")
		}
		if policy.BaseFee != newPolicy.BaseFee {
			t.Fatal("unexpected base fee")
		}
		if uint32(policy.FeeRate) != newPolicy.FeeRate {
			t.Fatal("unexpected base fee")
		}
		if policy.MaxHTLC != newPolicy.MaxHTLC {
			t.Fatal("unexpected max htlc")
		}
	}

	var expectedNumUpdates int
	propagateChanPolicyUpdate := func(
		edgesToUpdate []discovery.EdgeWithInfo) error {

		if len(edgesToUpdate) != expectedNumUpdates {
			t.Fatalf("unexpected number of updates,"+
				" expected %d got %d", expectedNumUpdates,
				len(edgesToUpdate))
		}

		for _, edge := range edgesToUpdate {
			policy := edge.Edge
			if !policy.MessageFlags.HasMaxHtlc() {
				t.Fatal("expected max htlc flag")
			}
			if policy.TimeLockDelta != uint16(newPolicy.TimeLockDelta) {
				t.Fatal("unexpected time lock delta")
			}
			if policy.FeeBaseMSat != newPolicy.BaseFee {
				t.Fatal("unexpected base fee")
			}
			if uint32(policy.FeeProportionalMillionths) != newPolicy.FeeRate {
				t.Fatal("unexpected base fee")
			}
			if policy.MaxHTLC != newPolicy.MaxHTLC {
				t.Fatal("unexpected max htlc")
			}
		}

		return nil
	}

	type channel struct {
		active   bool
		edgeInfo *channeldb.ChannelEdgeInfo
	}

	var channelSet []channel

	forAllOutgoingChannels := func(cb func(*channeldb.ChannelEdgeInfo,
		*channeldb.ChannelEdgePolicy) error) error {

		for _, c := range channelSet {
			if err := cb(c.edgeInfo, &currentPolicy); err != nil {
				return err
			}
		}
		return nil
	}

	fetchChannel := func(chanPoint wire.OutPoint) (*channeldb.OpenChannel,
		error) {

		constraints := channeldb.ChannelConstraints{
			MaxPendingAmount: maxPendingAmount,
			MinHTLC:          minHTLC,
		}

		return &channeldb.OpenChannel{
			LocalChanCfg: channeldb.ChannelConfig{
				ChannelConstraints: constraints,
			},
		}, nil
	}

	hasActiveLink := func(chanID lnwire.ChannelID) bool {
		for _, c := range channelSet {
			if !chanID.IsChanPoint(&c.edgeInfo.ChannelPoint) {
				continue
			}

			return c.active
		}
		return false
	}

	manager := Manager{
		UpdateForwardingPolicies:  updateForwardingPolicies,
		PropagateChanPolicyUpdate: propagateChanPolicyUpdate,
		ForAllOutgoingChannels:    forAllOutgoingChannels,
		FetchChannel:              fetchChannel,
		HasActiveLink:             hasActiveLink,
	}

	// Policy with no max htlc value.
	MaxHTLCPolicy := currentPolicy
	MaxHTLCPolicy.MaxHTLC = newPolicy.MaxHTLC
	noMaxHtlcPolicy := newPolicy
	noMaxHtlcPolicy.MaxHTLC = 0

	tests := []struct {
		name                string
		currentPolicy       channeldb.ChannelEdgePolicy
		newPolicy           routing.ChannelPolicy
		channelSet          []channel
		specifiedChanPoints []wire.OutPoint
		expectedNumUpdates  int
		expectErr           bool
	}{
		{
			name:          "valid channel",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{chanPointValid},
			expectedNumUpdates:  1,
		},
		{
			name:          "one active and one inactive channel",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointInactive,
					},
					active: false,
				},
			},
			specifiedChanPoints: []wire.OutPoint{
				chanPointValid,
				chanPointInactive,
			},
			expectErr:          true,
			expectedNumUpdates: 1,
		},
		{
			name:          "all channels",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{},
			expectedNumUpdates:  1,
		},
		{
			name:          "missing channel",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{chanPointMissing},
			expectErr:           true,
			expectedNumUpdates:  0,
		},
		{
			// Here, no max htlc is specified, the max htlc value
			// should be kept unchanged.
			name:          "no mac htlc specified",
			currentPolicy: MaxHTLCPolicy,
			newPolicy:     noMaxHtlcPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{chanPointValid},
			expectedNumUpdates:  1,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			currentPolicy = test.currentPolicy
			channelSet = test.channelSet
			expectedNumUpdates = test.expectedNumUpdates

			err := manager.UpdatePolicy(test.newPolicy, test.specifiedChanPoints...)
			if err != nil && test.expectErr {
				return
			}
			if err != nil {
				t.Fatalf(err.Error())
			}
			if test.expectErr {
				t.Fatalf("expected error")
			}
		})
	}
}
```

**Review by ellemouton — COMMENTED** [review]
Left some more comments and an idea for the test

File: routing/localchans/manager.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (ErikEk) [reply routing/localchans/manager.go:161]: Sounds good.

File: routing/localchans/manager_test.go (hunk 7 above)
Comment (ErikEk) [reply routing/localchans/manager_test.go:115]: @ellemouton Is there a reason you removed the testing code you posted two days ago? I did copy it and are running tests right now.

Comment (ErikEk) [reply routing/localchans/manager_test.go:115]: @ellemouton It is better than what I initially wrote btw. Impressed.

Comment (ellemouton) [reply routing/localchans/manager_test.go]: oops sorry! for some reason it looked like i had commented it twice so i removed one 🙈  
will post again for reference:
```
func TestManager(t *testing.T) {
	t.Parallel()
	
	var (
		chanPointValid    = wire.OutPoint{Hash: chainhash.Hash{1}, Index: 2}
		chanCap           = btcutil.Amount(1000)
		chanPointInactive = wire.OutPoint{Hash: chainhash.Hash{2}, Index: 2}
		chanPointMissing  = wire.OutPoint{Hash: chainhash.Hash{3}, Index: 2}
		maxPendingAmount  = lnwire.MilliSatoshi(999000)
		minHTLC           = lnwire.MilliSatoshi(2000)
	)

	newPolicy := routing.ChannelPolicy{
		FeeSchema: routing.FeeSchema{
			BaseFee: 100,
			FeeRate: 200,
		},
		TimeLockDelta: 80,
		MaxHTLC:       5000,
	}

	currentPolicy := channeldb.ChannelEdgePolicy{
		MinHTLC:      minHTLC,
		MessageFlags: lnwire.ChanUpdateOptionMaxHtlc,
	}

	updateForwardingPolicies := func(
		chanPolicies map[wire.OutPoint]htlcswitch.ForwardingPolicy) {

		if len(chanPolicies) == 0 {
			return
		}

		if len(chanPolicies) != 1 {
			t.Fatal("unexpected number of policies to apply")
		}

		policy := chanPolicies[chanPointValid]
		if policy.TimeLockDelta != newPolicy.TimeLockDelta {
			t.Fatal("unexpected time lock delta")
		}
		if policy.BaseFee != newPolicy.BaseFee {
			t.Fatal("unexpected base fee")
		}
		if uint32(policy.FeeRate) != newPolicy.FeeRate {
			t.Fatal("unexpected base fee")
		}
		if policy.MaxHTLC != newPolicy.MaxHTLC {
			t.Fatal("unexpected max htlc")
		}
	}

	var expectedNumUpdates int
	propagateChanPolicyUpdate := func(
		edgesToUpdate []discovery.EdgeWithInfo) error {

		if len(edgesToUpdate) != expectedNumUpdates {
			t.Fatalf("unexpected number of updates,"+
				" expected %d got %d", expectedNumUpdates,
				len(edgesToUpdate))
		}

		for _, edge := range edgesToUpdate {
			policy := edge.Edge
			if !policy.MessageFlags.HasMaxHtlc() {
				t.Fatal("expected max htlc flag")
			}
			if policy.TimeLockDelta != uint16(newPolicy.TimeLockDelta) {
				t.Fatal("unexpected time lock delta")
			}
			if policy.FeeBaseMSat != newPolicy.BaseFee {
				t.Fatal("unexpected base fee")
			}
			if uint32(policy.FeeProportionalMillionths) != newPolicy.FeeRate {
				t.Fatal("unexpected base fee")
			}
			if policy.MaxHTLC != newPolicy.MaxHTLC {
				t.Fatal("unexpected max htlc")
			}
		}

		return nil
	}

	type channel struct {
		active   bool
		edgeInfo *channeldb.ChannelEdgeInfo
	}

	var channelSet []channel

	forAllOutgoingChannels := func(cb func(*channeldb.ChannelEdgeInfo,
		*channeldb.ChannelEdgePolicy) error) error {

		for _, c := range channelSet {
			if err := cb(c.edgeInfo, &currentPolicy); err != nil {
				return err
			}
		}
		return nil
	}

	fetchChannel := func(chanPoint wire.OutPoint) (*channeldb.OpenChannel,
		error) {

		constraints := channeldb.ChannelConstraints{
			MaxPendingAmount: maxPendingAmount,
			MinHTLC:          minHTLC,
		}

		return &channeldb.OpenChannel{
			LocalChanCfg: channeldb.ChannelConfig{
				ChannelConstraints: constraints,
			},
		}, nil
	}

	hasActiveLink := func(chanID lnwire.ChannelID) bool {
		for _, c := range channelSet {
			if !chanID.IsChanPoint(&c.edgeInfo.ChannelPoint) {
				continue
			}

			return c.active
		}
		return false
	}

	manager := Manager{
		UpdateForwardingPolicies:  updateForwardingPolicies,
		PropagateChanPolicyUpdate: propagateChanPolicyUpdate,
		ForAllOutgoingChannels:    forAllOutgoingChannels,
		FetchChannel:              fetchChannel,
		HasActiveLink:             hasActiveLink,
	}

	// Policy with no max htlc value.
	MaxHTLCPolicy := currentPolicy
	MaxHTLCPolicy.MaxHTLC = newPolicy.MaxHTLC
	noMaxHtlcPolicy := newPolicy
	noMaxHtlcPolicy.MaxHTLC = 0

	tests := []struct {
		name                string
		currentPolicy       channeldb.ChannelEdgePolicy
		newPolicy           routing.ChannelPolicy
		channelSet          []channel
		specifiedChanPoints []wire.OutPoint
		expectedNumUpdates  int
		expectErr           bool
	}{
		{
			name:          "valid channel",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{chanPointValid},
			expectedNumUpdates:  1,
		},
		{
			name:          "one active and one inactive channel",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointInactive,
					},
					active: false,
				},
			},
			specifiedChanPoints: []wire.OutPoint{
				chanPointValid,
				chanPointInactive,
			},
			expectErr:          true,
			expectedNumUpdates: 1,
		},
		{
			name:          "all channels",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{},
			expectedNumUpdates:  1,
		},
		{
			name:          "missing channel",
			currentPolicy: currentPolicy,
			newPolicy:     newPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{chanPointMissing},
			expectErr:           true,
			expectedNumUpdates:  0,
		},
		{
			// Here, no max htlc is specified, the max htlc value
			// should be kept unchanged.
			name:          "no mac htlc specified",
			currentPolicy: MaxHTLCPolicy,
			newPolicy:     noMaxHtlcPolicy,
			channelSet: []channel{
				{
					edgeInfo: &channeldb.ChannelEdgeInfo{
						Capacity:     chanCap,
						ChannelPoint: chanPointValid,
					},
					active: true,
				},
			},
			specifiedChanPoints: []wire.OutPoint{chanPointValid},
			expectedNumUpdates:  1,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			currentPolicy = test.currentPolicy
			channelSet = test.channelSet
			expectedNumUpdates = test.expectedNumUpdates

			err := manager.UpdatePolicy(test.newPolicy, test.specifiedChanPoints...)
			if err != nil && test.expectErr {
				return
			}
			if err != nil {
				t.Fatalf(err.Error())
			}
			if test.expectErr {
				t.Fatalf("expected error")
			}
		})
	}
}
```

File: routing/localchans/manager.go [hunk 9]
```diff
@@ -106,6 +127,33 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
 		return err
 	}
 
+	// Return an error if any of the channels in chansToUpdate
+	// were invalid.
+	for chanPoint := range chansToUpdate {
+		channel, err := r.FetchChannel(chanPoint)
+		if errors.Is(err, channeldb.ErrChannelNotFound) {
+			errInvalidChans += fmt.Sprintf(
```
Comment (ellemouton) [inline routing/localchans/manager.go:135]: nit: for all these `fmt.Sprint(...` statements, see contribution guidelines [here](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#additional-style-constraints-on-top-of-gofmt) basically, if all the arguments cant fit on 1 line, then the open and close brackets should also be on their own lines. so:
```
fmt.Sprintf(
<args here>,
)
```

**Review by ellemouton — COMMENTED** [review]
Cool, thanks for the update @ErikEk 🚀  I think it is really useful to show users these errors.

I have tested all the cases and they all work as advertised 💪 
(also left a few more nit comments) (also just remember to add an entry in the release notes)

Before I approve this, I just want to get someone else's opinion about the all-or-nothing  strategy vs trying them all and reporting back which ones failed. There is something nice and clean about all-or-nothing but that might also just be a bit of a mission for users since if they wanted to update all their channels and then 1 fails then they would need to go update the rest one by one. But then on the other hand, maybe they only want the updates to succeed if the policy updates can be applied to all their channels. Let me hunt for some opinions quickly 👍

**Review by ellemouton — APPROVED** [review]
Cool, got some opinions and looks like people agree with the way you have gone about it here 🚀  so LGTM! Just see my nit comments from before :)

File: routing/localchans/manager.go (hunk 9 above)
Comment (ErikEk) [reply routing/localchans/manager.go:136]: Fixing it.

**Comment by ErikEk** [comment]
@ellemouton Well, you did a lot of the heavy lifting on this one. Thank you. I'll remember it.

**Comment by ellemouton** [comment]
@ErikEk , the second commit should not be a merge from master. Rather rebase your original commit and then add the change to the release notes.

File: routing/localchans/manager.go [hunk 10]
```diff
@@ -106,6 +125,40 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+			)
+			continue
+		}
+		if err != nil {
+			errStr += fmt.Sprintf(
+				"error fetching channel %s:%d; ",
+				chanPoint.Hash.String(), chanPoint.Index,
+			)
+			continue
+		}
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply routing/localchans/manager.go:148]: (new line after line 148)

File: routing/localchans/manager.go (hunk 9 above)
Comment (ellemouton) [reply routing/localchans/manager.go:136]: still need new line after the last argument before the `)`

File: docs/release-notes/release-notes-0.14.0.md [hunk 11]
```diff
@@ -0,0 +1,33 @@
...
+
+## Database
+
+* [Ensure single writer for legacy
+  code](https://github.com/lightningnetwork/lnd/pull/5547) when using etcd
+  backend.
+
+# Contributors (Alphabetical Order)
+* ErikEk
+* Zero-1729
```
Comment (ellemouton) [inline docs/release-notes/release-notes-0.14.0.md]: First rebase your original commit onto latest master. Then add your changes to release notes

**Review by ellemouton — CHANGES_REQUESTED** [review]
Hey :) your latest push added a merge commit. So just address that and then we are good to go. (also there are a feeew unaddressed (but non-blocking) nits still)

**Comment by ErikEk** [comment]
Just a moment... Having some issues rebasing.

**Comment by ErikEk** [comment]
This looks better.

File: routing/localchans/manager.go [hunk 12]
```diff
@@ -34,6 +35,9 @@ type Manager struct {
 	FetchChannel func(chanPoint wire.OutPoint) (*channeldb.OpenChannel,
 		error)
 
+	// HasActiveLike is used to check whether a channel is active or not.
```
Comment (carlaKC) [inline routing/localchans/manager.go:38]: s/HasActiveLike/HasActiveLink

File: routing/localchans/manager.go [hunk 13]
```diff
@@ -34,6 +35,9 @@ type Manager struct {
...
+	HasActiveLink func(chanID lnwire.ChannelID) bool
```
Comment (carlaKC) [inline routing/localchans/manager.go:39]: nit: would `IsActive` be a better name?

File: routing/localchans/manager.go [hunk 14]
```diff
@@ -59,6 +63,8 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
 
 	haveChanFilter := len(chansToUpdate) != 0
 
+	var errInvalidChans string
```
Comment (carlaKC) [inline routing/localchans/manager.go:66]: nit: this could also be `[]string` and then we use `strings.Join` rather than trying to smartly append below

File: routing/localchans/manager.go [hunk 15]
```diff
@@ -85,6 +91,22 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
 			return nil
 		}
 
+		// Mark this channel as found by removing it. chansToUpdate
+		// will be used to report invalid channels later on.
+		// Note: This must be executed before we look for inactive
+		// channels.
+		delete(chansToUpdate, info.ChannelPoint)
```
Comment (carlaKC) [inline routing/localchans/manager.go:98]: The name on `chansToUpdate` seems a bit unintuitive it's actually the list of channels that we didn't update?

**Review by carlaKC — COMMENTED** [review]
Thanks for the PR @ErikEk! This API has been a source of frustration for a while, so it's great to have some UX improvements on the go :D 

One thing that's tricky here is that we can hit these kind on "error-not-error" states where we update some channels, and fail out on others. To me, it doesn't quite feel right for the rpc call to error out when it has actually taken some actions successfully. 

The detailed errors you've added here are great, but I would suggest that we go one step further and add the outcomes of our updates to the rpc. Strings are nice for people to read, but don't give machines very good feedback. 

I would suggest adding a report of the actions we've actually taken in the response (which can be printed out nicely in `lncli`)
```
message PolicyUpdateResponse {
  repeated updateSummary updates = 1;
}
```

With an update summary which tells us what happened:
```
message updateSummary struct{
  uint64 channel ID = 1;
  bool success = 2; 
  
  // The below are, as far as possible, specific reasons for the update failing. Falling back on a string if we can't enumerate it.
  bool channel_not_found = 1;
  bool is_pending = 2;
  bool inactive = 3;
  string update_err = 4;
}
```

That way, we can provide a clear report on what updated and what failed, and address some of the annoying silent failures very explicitly. @alexbosworth does this look reasonable to you?

**Comment by alexbosworth** [comment]
> That way, we can provide a clear report on what updated and what failed, and address some of the annoying silent failures very explicitly. @alexbosworth does this look reasonable to you?

sure it looks ok to me, I don't think there is really a standard way to represent structured errors so putting them in the regular response seems as good as anything else

I'd always populate update_err even if a failure boolean is set, that way if a future boolean is added that fails but the client software doesn't know about that boolean, it will still show a reasonable error

**Comment by carlaKC** [comment]
> I don't think there is really a standard way to represent structured errors so putting them in the regular response seems as good as anything else

yeah def a shortcoming of grpc that errors aren't particularly easy to handle. This case is particularly difficult because we have a lot of different "entities" that can each have their own error. 

> I'd always populate update_err even if a failure boolean is set

Agreed, the string is probably always good to have as a fallback. 

Only issue with this approach is that the grpc call will still fail without an error (for older clients that don't know about the new fields), because the "error" would be returned in the response, but I think it's a happy inbetween because upgraded client will have much better information.

File: routing/localchans/manager.go (hunk 15 above)
Comment (ErikEk) [reply routing/localchans/manager.go:98]: The name is not intuitive, hence the comment above `delete`. I can create a separate list with a more appropriate name and copy all the necessary channel properties into it if you want? The rationale behind it was optimizing for memory usage.

File: routing/localchans/manager.go (hunk 12 above)
Comment (ErikEk) [reply routing/localchans/manager.go:38]: Nice

File: routing/localchans/manager.go (hunk 13 above)
Comment (ErikEk) [reply routing/localchans/manager.go:39]: Since I'm referencing https://github.com/lightningnetwork/lnd/blob/ebabda671786486d37a76718961672eabfa7b368/htlcswitch/switch.go#L2061 I though I might as well use the same name.

File: routing/localchans/manager.go (hunk 14 above)
Comment (ErikEk) [reply routing/localchans/manager.go:66]: I'll do that, thank you!

File: routing/localchans/manager.go (hunk 15 above)
Comment (ErikEk) [reply routing/localchans/manager.go:98]: Hopefully I can find something more intuitive.

File: routing/localchans/manager.go (hunk 13 above)
Comment (ErikEk) [reply routing/localchans/manager.go:39]: I think HasActiveLink is good name because it returns true if there is a link in the link index *AND* the link is eligible to forward. Not to be confused by the active status of the channel.

**Comment by ErikEk** [comment]
@carlaKC Thanks for the review. I liked your suggestions. 
For the response, I suggest we do not return a list of the channels that were successfully updated... IMO it becomes excessive if a user has many channels. I would suggest just returning a list of the failed policy updates and a message. Something like this...

```
{
    "message": "not all channels were updated",
    "failed_policy_updates": [
        {
            "chan_id": "2236772788274528256",
            "channel_point": "asdasdasd4a0asdasdasdde2a9bacd01d05e40d7cc34668053fb6f3c49729:0",
            "update_status": "INACTIVE",
            "update_err": "channel is not active"
        },
        {
            "chan_id": "223758312312326384",
            "channel_point": "asdasdasd22sadb9166214133529bc05c0d7268ec2c480b187e3939683c0aa:0",
            "update_status": "INVALID",
            "update_err": "channel is invalid"
        },
        {
            "chan_id": "223841231314141696",
            "channel_point": "2f12sadsasadsasd11w1115217c4fbcf903b2807c089eb914a624f59e321d83:0",
            "update_status": "NOTFOUND",
            "update_err": "channel is missing"
        },
    ]
}
```

**Comment by carlaKC** [comment]
Thanks for all the iterations on this one @ErikEk! I think we're converging on a great solution.

> I suggest we do not return the channels that were successfully updated

Good point! Happy to only return failed channel updates, then you can assume that your update went through if it's not in the failures list. 

>  "message": "not all channels were updated",

I think we can cut this message? The length of the `failed_policy_updates` array will tell you what the outcome of the batch update was. For a nice user experience on the cli, we could perhaps just print this message based on array length? I don't see much use for it on the rpc.

>     "failed_policy_updates": [
>         {
>             "chan_id": "2237584227850256384",
>             "channel_point": "asdasdasd4a0asdasdasdde2a9bacd01d05e40d7cc34668053fb6f3c49729:0",
>             "channel_status": "INACTIVE",
>             "update_err": "channel is not active"
>         },
>         {
>             "chan_id": "553444444440256384",
>             "channel_point": "asdasdasd22sadb9166214133529bc05c0d7268ec2c480b187e3939683c0aa:0",
>             "channel_status": "PENDING",
>             "update_err": "channel is pending"
>         },
>         {
>             "chan_id": "123334227850256384",
>             "channel_point": "2f12sadsasadsasd11w1115217c4fbcf903b2807c089eb914a624f59e321d83:0",
>             "channel_status": "NOTFOUND",
>             "update_err": "channel is missing"
>         },

Looks good! Would the `channel_status` be an enum of possible reasons we failed? Since we don't currently have any state that represents `NOTFOUND`? If so, I'd suggest `update_failure_reason`? Then we can just enumerate all the known failure reasons, and have a 0 value for unknown: 

```
enum UpdateFailureReason{
  UpdateFailureReasonUnknown = 0;
  UpdateFailureReasonInactive = 1;
  ...
  UpdateFailureReasonPending = 3;
}
```

> {
>    "message": "channel policies were successfully updated",
>    "failed_policy_updates": []
>}

As noted above, an empty `failed_policy_updates` will be sufficient to inform end user that we've succeeded completely.

File: lnrpc/lightning.proto [hunk 16]
```diff
@@ -3506,7 +3506,30 @@ message PolicyUpdateRequest {
...
+
+message FailedUpdates {
+    enum Reason {
+        UNKNOWN = 0;
+        PENDING = 1;
+        INACTIVE = 2;
+        NOTFOUND = 3;
+        INVALID = 4;
+        INVALID_PARAMETER = 5;
+    }
```
Comment (ErikEk) [inline lnrpc/lightning.proto:3518]: @carlaKC If you are not satisfied with the naming of these I'll change them.

**Comment by ErikEk** [comment]
The new update returns a failure report if min_htlc is smaller then the remote min_htlc.

File: routing/localchans/manager.go (hunk 13 above)
Comment (ErikEk) [reply routing/localchans/manager.go:40]: @carlaKC I'm changing my mind... changing it to IsChannelActive, just like we call it in the invoice sub-server. Thanks for mentioning it.

**Comment by ErikEk** [comment]
Ready to be reviewed.

File: docs/release-notes/release-notes-0.14.0.md [hunk 17]
```diff
@@ -119,6 +123,7 @@ currnet DNS seeds when in SigNet
 mode](https://github.com/lightningnetwork/lnd/pull/5564).
 
 # Contributors (Alphabetical Order)
+
```
Comment (carlaKC) [inline docs/release-notes/release-notes-0.14.0.md:126]: nit: don't need newline here?

File: lnrpc/lightning.proto (hunk 16 above)
Comment (carlaKC) [reply lnrpc/lightning.proto:3518]: These look good! 

One comment I'd make is to move the enum out of the message and have it sit by itself, just makes things easier if we ever want to re-use the enum (if we move it later, it's a compile time break). 

Grpc has also been complaining about duplicate names recently (logging warnings etc), so I'd go with: 
```
enum UpdateFailure{
  UPDATE_FAILURE_UNKNOWN = 0;
  ...
  UPDATE_FAILURE_INVALID ...
```

File: lnrpc/lightning.proto [hunk 18]
```diff
@@ -3506,7 +3506,30 @@ message PolicyUpdateRequest {
...
+
+    // The channel that the policy update report belongs to.
+    string channel_point = 1;
```
Comment (carlaKC) [inline lnrpc/lightning.proto:3521]: I think that we have a dedicated type for outpoints?

File: routing/localchans/manager.go [hunk 19]
```diff
@@ -42,23 +47,24 @@ type Manager struct {
...
 
 	r.policyUpdateLock.Lock()
 	defer r.policyUpdateLock.Unlock()
 
-	// First, we'll construct a set of all the channels that need to be
-	// updated.
-	chansToUpdate := make(map[wire.OutPoint]struct{})
+	// First, we'll construct a set of all the channels that we are
+	// trying to update.
+	unprocessedChans := make(map[wire.OutPoint]struct{})
```
Comment (carlaKC) [inline routing/localchans/manager.go:60]: nice!

File: routing/localchans/manager.go [hunk 20]
```diff
@@ -103,7 +129,45 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+					ChannelPoint: chanPoint.String(),
+					Reason:       lnrpc.FailedUpdate_NOTFOUND,
+					UpdateError:  "not found",
+				})
+
+		case err != nil:
+			failedUpdates = append(failedUpdates,
+				&lnrpc.FailedUpdate{
+					ChannelPoint: chanPoint.String(),
+					Reason:       lnrpc.FailedUpdate_INVALID,
```
Comment (carlaKC) [inline routing/localchans/manager.go:151]: What do we mean by `INVALID` here? Would `INTERNAL_ERR` be a better name? Since we're failed for an unexpected reason?

**Review by carlaKC — COMMENTED** [review]
Looking great! Would just like to move around the enum + clarify what we're conveying in the `INVALID` case then we're good to go. Really wonderful improvement 💪

File: routing/localchans/manager.go (hunk 20 above)
Comment (ErikEk) [reply routing/localchans/manager.go]: I think INTERNAL_ERR is great.

File: lnrpc/lightning.proto (hunk 18 above)
Comment (ErikEk) [reply lnrpc/lightning.proto]: We have. Just applied it on the new update. If you think it becomes to bloated I'll change it back to a string.

**Comment by ErikEk** [comment]
@carlaKC Rebased and ready for review. Haven't changed the test function in this update.

**Comment by carlaKC** [comment]
> Wait with the review.

👍 

For future iterations, you can use the "request review" button on GH to let us know when a PR is ready for a look. That puts it in the reviewers queue, and they're more likely to remember to take a look :)

File: cmd/lncli/commands.go [hunk 21]
```diff
@@ -2311,7 +2311,22 @@ func updateChannelPolicy(ctx *cli.Context) error {
 		return err
 	}
 
-	printRespJSON(resp)
+	// Parse the response into the final json object that will be printed
+	// to stdout. At the moment, this filters out the raw txid bytes from
+	// each failed update's outpoint and only prints the txid string.
+	var listFailedUpdateResp = struct {
```
Comment (carlaKC) [inline cmd/lncli/commands.go:2317]: Would be nice to have a `if len(resp.FailedUpdates)==0` print "all channels updated successfully", but not a blocking comment since you've done the hard yards on this PR!

File: routing/localchans/manager.go [hunk 22]
```diff
@@ -71,17 +77,39 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+		// Mark this channel as found by removing it. unprocessedChans
+		// will be used to report invalid channels later on.
+		delete(unprocessedChans, info.ChannelPoint)
+
 		// Apply the new policy to the edge.
 		err := r.updateEdge(info.ChannelPoint, edge, newSchema)
 		if err != nil {
-			log.Warnf("Cannot update policy for %v: %v\n",
-				info.ChannelPoint, err,
+			appendUpdateFailureItem(
```
Comment (carlaKC) [inline routing/localchans/manager.go:92]: I've got a slight preference for having an `makeFailureItem` helper function then just going `failureUpdates = append(...` inline, I don't think it makes it less readable.

File: routing/localchans/manager_test.go [hunk 23]
```diff
@@ -115,34 +133,162 @@ func TestManager(t *testing.T) {
...
-	if err != nil {
-		t.Fatal(err)
+	tests := []struct {
+		name                     string
+		currentPolicy            channeldb.ChannelEdgePolicy
+		newPolicy                routing.ChannelPolicy
+		channelSet               []channel
+		specifiedChanPoints      []wire.OutPoint
+		expectedNumUpdates       int
+		expectedNumFailedUpdates int
```
Comment (carlaKC) [inline routing/localchans/manager_test.go:168]: Can we match these to an exact set of failure updates we expect?

**Review by carlaKC — COMMENTED** [review]
tACK, what a great ux improvement! Just some last nits then we're good to go :D
```
{                                                                                                                                                             
        "failed_updates": [                                                                                                                                   
                {                                                                                                                                             
                        "outpoint": "15170061db558201dfd758ccda218340e1c557c547a93051c25b4ab0a5e05d9a:0",                                                    
                        "reason": "UPDATE_FAILURE_INACTIVE",                                                                                                  
                        "update_error": "channel is inactive"                                                                                                 
                }                                                                                                                                             
        ]                                                                                                                                                     
} 
```

File: routing/localchans/manager.go (hunk 22 above)
Comment (ErikEk) [reply routing/localchans/manager.go:92]: Sounds good

File: routing/localchans/manager_test.go (hunk 23 above)
Comment (ErikEk) [reply routing/localchans/manager_test.go:168]: Sure thing. Np.

File: cmd/lncli/commands.go (hunk 21 above)
Comment (ErikEk) [reply cmd/lncli/commands.go:2317]: I'm not sure what you mean but I added a print command in rpcserver.go.

```
if len(failedUpdates) == 0 {
	rpcsLog.Info("All channels updated successfully")
}
```

Comment (carlaKC) [reply cmd/lncli/commands.go:2317]: Sorry, was unclear here, I meant print it just on the CLI rather than printing an empty list. But it's just a little bit of UX-sugar so not vital!

Comment (ErikEk) [reply cmd/lncli/commands.go:2317]: Alright, I'll leave it as is then. Thx for your review.

File: routing/localchans/manager_test.go [hunk 24]
```diff
@@ -115,34 +138,173 @@ func TestManager(t *testing.T) {
...
-		t.Fatal(err)
+			if err != nil && test.expectErr {
+				return
+			}
+			if err != nil {
+				t.Fatalf(err.Error())
+			}
+			if test.expectErr {
+				t.Fatalf("expected error")
+			}
```
Comment (carlaKC) [inline routing/localchans/manager_test.go:307]: Could flatten all this into having an expected error `expectedErr error` in each case and just `require.Equal(t, test.ExpectedErr, err)`.

**Review by carlaKC — APPROVED** [review]
Thank you for all the iterations on this, really a great improvement to a previously quite opaque api failure! 

Tested the following cases, and goods are as advertized: 
* Multiple channel successful update
* Single channel fails, others succeed
* Channel inactive
* Channel not found
* Channel pending

🥇

File: routing/localchans/manager_test.go (hunk 24 above)
Comment (ErikEk) [reply routing/localchans/manager_test.go:307]: Awesome.

**Comment by ErikEk** [comment]
@carlaKC Grateful for your support on this one! The error check is now commited and codebase rebased.

**Review by ellemouton — APPROVED** [review]
Great PR @ErikEk! tACK for all the listed cases 🚀

**Comment by ErikEk** [comment]
@ellemouton great. And again, the table driven test you provided really elevated this pr.

**Comment by ErikEk** [comment]
Had to do a rebase because of changes in a proto file from last commit.

File: routing/localchans/manager.go [hunk 25]
```diff
@@ -75,17 +81,37 @@ func (r *Manager) UpdatePolicy(newSchema routing.ChannelPolicy,
...
+					err.Error(),
+				))
+
+			return nil
+		}
+
+		// Check whether the channel is inactive, if so, we add an item
+		// to the failed policy update list.
+		channelID := lnwire.NewChanIDFromOutPoint(&info.ChannelPoint)
+		if !r.IsChannelActive(channelID) {
```
Comment (Roasbeef) [inline routing/localchans/manager.go:108]: Why should we care if a channel is inactive or not? The link existing doesn't mean that we can't update the channel on the gossip layer. 

This change would likely also negatively interact with an attempt to disable a link (manually) when a channle is inactive.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: routing/localchans/manager.go (hunk 25 above)
Comment (Roasbeef) [reply routing/localchans/manager.go:108]: > Edit: As is, the policy update command silently fails to update a channel policy if it the channel is inactive. The latest update fixes this by skipping the policy update and returns a policy update report.

Ah I see this now, can you point to where it would fail before?

Comment (ErikEk) [reply routing/localchans/manager.go:108]: @Roasbeef I ran some tests and it looks like the policy update command **does not** silently fails when a channel is inactive on the latest master build. I tried to track down where this issue would have occurred (as described in the comment section of issue #4846), all the way back to 0.12.0-beta, but could not figure it out. 

If you want me to include inactive channels in the policy update process I'll update the pr right away.

Comment (ErikEk) [reply routing/localchans/manager.go]: I ran some tests and it looks like the policy update command works as it should on inactive channels. I tried to track down where this issue would have occurred (as described in the comment section of issue #4846), all the way back to 0.12.0-beta, but could not figure it out. I didn't realize the gossip layer would take care of it. My bad.
Anyway, the latest commit leaves inactive channels alone and they will be treated the same way as in master.

**Comment by Roasbeef** [comment]
Needs a rebase!

**Comment by ErikEk** [comment]
Rebased!

**Comment by guggero** [comment]
Sorry, another merge got in first, your PR requires yet another rebase. Will try to get this PR in next!
@Roasbeef I assume your comment above was answered? Or is there still something to be checked/changed?

**Comment by ErikEk** [comment]
@guggero Rebased

**Comment by ErikEk** [comment]
Inactive channel updates still silently fails but this can be fixed in a separate pr. I'll create an issue later this week. Imo this pr should not address that issue.

File: routing/localchans/manager.go (hunk 25 above)
Comment (ErikEk) [reply routing/localchans/manager.go]: @Roasbeef Don't have any answers right now. I'll try to address the issue in a separate pr.

**Comment by sako0938** [comment]
AWESOME!

**Comment by sako0938** [comment]
I may be mistaken, but it still silently fails if you pass in a channel point that looks valid, but isnt among your list of channels?

I tried getting one of my channels channel_points, adjusted a few characters in it, then ran update_chan_policy and it didnt provide any errors.

It did provide errors if the channel points was malformed is a bigger way, like missing characters.

**Comment by ErikEk** [comment]
@sako0938 Let me look into that.

**Comment by ErikEk** [comment]
@sako0938 I can not reproduce the error, just getting UPDATE_FAILURE_NOT_FOUND every time. Pls send over your channel_point string and the adjusted one if that is possible.
You probably already know this, but updatechannelpolicy only allows to update all channels globally, or a particular channel, not an array of channels.

**Comment by sako0938** [comment]
lnd version 0.13.99-beta commit=kvdb/v1.0.2-6-g6be472eb

You are right, we get updated error using the CLI
```
user@user:/srv/lnd$ lncli updatechanpolicy --chan_point=a61c7e14d1444b0045240447bbd2281f60800585c375e40b3ef2594dd6034e85:0 --base_fee_msat=1 --fee_rate=0.000010 --time_lock_delta=25
{
	"failed_updates": []
}
user@user:/srv/lnd$ lncli updatechanpolicy --chan_point=b61c7e14d1444b0045240447bbd2281f60800585c375e40b3ef2594dd6034e85:0 --base_fee_msat=1 --fee_rate=0.000010 --time_lock_delta=25
{
	"failed_updates": [
		{
			"outpoint": "b61c7e14d1444b0045240447bbd2281f60800585c375e40b3ef2594dd6034e85:0",
			"reason": "UPDATE_FAILURE_NOT_FOUND",
			"update_error": "not found"
		}
	]
}
```

But in my Python code which uses gRPC I am not getting any return values regardless of good or bad
```
# good channel point
lnd.update_channel_policy(
    base_fee_msat=1,
    fee_rate=0.000001 * 100,
    time_lock_delta=25,
    chan_point='a61c7e14d1444b0045240447bbd2281f60800585c375e40b3ef2594dd6034e85:0'
)

# bad channel point
r = lnd.update_channel_policy(
    base_fee_msat=1,
    fee_rate=0.000001 * 100,
    time_lock_delta=25,
    chan_point='b61c7e14d1444b0045240447bbd2281f60800585c375e40b3ef2594dd6034e85:0'
)
```

Here is the Python implementation of that function, for reference:
```
    @handle_rpc_errors
    def update_channel_policy(self, base_fee_msat=None, fee_rate=None, time_lock_delta=None,
                              chan_point=None, all_channels=False):
        """Update the channel policy for all channels, or a single channel"""
        kwargs = {
            'global': all_channels
        }
        if base_fee_msat:
            kwargs['base_fee_msat'] = base_fee_msat
        if fee_rate:
            kwargs['fee_rate'] = fee_rate
        if chan_point:
            txid, out_index = chan_point.split(":")
            txid_reversed = bytearray(bytes.fromhex(txid))
            txid_reversed.reverse()
            cp = ln.ChannelPoint(funding_txid_bytes=bytes(txid_reversed), output_index=int(out_index))
            kwargs['chan_point'] = cp
        if time_lock_delta:
            kwargs['time_lock_delta'] = time_lock_delta

        request = ln.PolicyUpdateRequest(**kwargs)
        response = self._ln_stub.UpdateChannelPolicy(request)
        return response
```

**Comment by guggero** [comment]
You probably need to re-generate your protobuf definitions.

**Comment by ErikEk** [comment]
@sako0938 Still having problems?

**Comment by sako0938** [comment]
@ErikEk No I got it this morning! I dont regenerate the protos that often, so it always takes me a bit to get to it!

```
>>> lnd.update_channel_policy(
...     chan_point="678927d0c032f81cc6021baea0e2f9a018be9d949ee7739cd52604a165750aef:2",
...     base_fee_msat=100,
...     fee_rate=0.0100,
...     time_lock_delta=25
... )
failed_updates {
  outpoint {
    txid_bytes: "\357\nue\241\004&\325\234s\347\236\224\235\276\030\240\371\342\240\256\033\002\306\034\3702\300\320\'\211g"
    txid_str: "678927d0c032f81cc6021baea0e2f9a018be9d949ee7739cd52604a165750aef"
    output_index: 2
  }
  reason: UPDATE_FAILURE_NOT_FOUND
  update_error: "not found"
}

```
