### PR TITLE
[mobile] Set walletunlocker TLS credentials

### LINKED ISSUE #3905: [mobile] grpc: no transport security set
### Background

I have launched LND on iOS via `gomobile` and all your instructions (using falafel). I am able to start LND node and see all logs. But I cannot make any gRPC requests because of the following error:

`Error Domain=go Code=1 "grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)" UserInfo={NSLocalizedDescription=grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)}`

### Your environment

Also please note that I am using new `nio` branch of `grpc-swift` as they recommend.

* version of `lnd`:  lnd v0.9.0-beta-rc1
* which operating system (`uname -a` on *Nix): OSX
* version of `btcd`, `bitcoind`, or other backend: Neutrino
* any other relevant environment details

### Steps to reproduce

`LndmobileStart` succeeds and I see all the logs. But any gRPC request (`LndmobileInitWallet` or `LndmobileGenSeed`) does fail with the error above.

### PR DESCRIPTION
**Pull request by halseth**
This PR fixes a regression from #3783, where TLS support was added on mobile, but we forgot to add the TLS credentials also to the wallet unlocker client.

Fixes #3905

### CODE REVIEW

File: lnd.go [hunk 1]
```diff
@@ -60,6 +60,25 @@ var (
 	networkDir string
 )
 
+// WalletUnlockerAuthOptions returns a list of DialOptions that can be used to
+// authenticate with the wallet unlocker service.
+//
+// NOTE: This should only be called after the WalletUnlocker listerner has
```
Comment (guggero) [inline lnd.go]: nit: s/listerner/listener/

Comment (halseth) [reply lnd.go]: Fixed
