### PR TITLE
Switch duplicate links

### LINKED ISSUE #1342: Remote uncooperative close when trying to send a first HTLC
### Background

When connected to remote https://1ml.com/node/03295d2e292565743a40bd44da227a820f8730877bc3dfadebade8785bcf355258 peer using BLW the very first payment attempt directly to that node results in a remote uncooperative closing.

Messages sent from BLW:

> --> UpdateAddHtlc(0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b6470,0,100000,18ec2624601f2cf15b25a0600bb092e94e9b514954a151263a658c6dcbf08242,526571,000237d723d2bd755d0c63e8ee94d5dde32a280e08085653d5945a56f7f36a69c86dca9460c154f20428e60f41bb6b3d2c2173c62e216c333f47c5342345734d5b9e4f1de45f4f22901df86fe5e88191c70a44bc5f919651309d1b26e4b9b77b93d2e39e81a200c01afb60534a381d204275f4b0a3f1dae1c938d575b684449726acedc440c0227f01c0c38a09c1a269a28b6e4005b078893dfc96ca24e954da3ce582e5c8d5d6101b987cae620fe52be8e93ad0e84018a4f3e2df15eddea786302b5ac1de35eae97409061c43a8413ebe5f676d8c503d738847107c7c0370028d2368a5e4aeea0bef7e240752ba71eabe37d5dd132dd6ecdfe150b96d619f5a40bb886ef72d0864ce8ed0e32984b6f9023c44b089c7dc2b7fc5153043419ca45b7e27284a0795989e3a6ab9d882c92c9cdf62be9947417b703cec134e70caecdac5d51976b017d280959cbc8324209dad6067b1249bc145102d155e810308127530b7a7127e5962044ba69bfb505002c6d35cb5c36a36d48093bfc15d39a7c70de2bf1a8fde65fc8da2f6c5c574759dab1f26161d15c9cc0afa10d3a1dd4cbfc926add70084eb675c325b9725b4b5af838265ead80c6ab40e6b0dee95772f622bb9ca4ba2b17ae1c47d5d3f04d5a604e5caee01f0c5567c52955e4ccf4649452e5fa494931f0e5dfe8e7cd04496e2a8d18a37580d3d6d618f56b753b4ac7b4bf1d035bd913c0dd64dff8bb78e23397a11af8291a82c9d1aa225ba490f778968d12585e42978a4838ed456474ec8b5a8231b674ec4a4123a9cd758b41fb3128e158ea583fc2b3480c5dddff0cbe1e7c2669e056c8daab1ee62f8b9942e92504f0b8810d0dcefcd178af7d14d0652b199fcce5edb09c9fc1ef34d5dc768caa101d32ea0b30273c8c4c04710a2f4e67faca83925fe3d051a5c4610801eeab3e55f75d1167a9678aea3c1b5325a53570ef93d24674107c111e7a50e751a450aee6cad892536d6e09cc242971aaef3e15ec650ce426300b4cd84d08455799ceb876494977779a9895d82725129af30cf7aeb889220e0c66efa61d1fcfc720c47147c564241ee1bf00c54f6c1a89b024d17299024ef0b0d78bf5010c3ba5a51a3c8b81ea2f427e500332f293f5faafa968e5c3778a83b427d9632f634ccc7e768e9ed6daa9189f55972dac3136e4b3b9d4fe1ec9fde6e64a744d98ff3e771e7697efea96991795f81682c23f9411776b272f349344e7054edb61815f30615198d0fbdbf56687690c580758dfe3de27bd08900a0b83021519934cb710170d44138a69d4dd50150e7bc990acef8e3748202c2e62be038589170f422a3b9b00e2fc50edfec075c3aec79255fb048d7499ee2cfe1b816478c01c65a6f63093dc07963f465be1313e016d76d3391f888967e57df3b1ed373c90c92ad79fb8349724e546abaf18a79583e44a19421fc6ea07690485f3409b6e49a05eba64db7bbec0da9ac00587027b1fae5c75a753af7e78e44503f71be6e363c86e89c835c5b6b7dfbbcb77e3913f4ec00c6543ffa77812da163c69153d507f78362012c603eab6c3e513d5ff25137541cef00b8454078ebc24784d366986986337efde3218a46e998e183893ba09ae9ca90f4f2a8ae80bdcfb802bd97343bfceda9942b31cb11f818411e960da3888fdb867b252211a25c8f76b8aebf35ab9908e692a54093cf22406f392dd5515d27f44890dcec0d77070368e386a6ca9cd1f730b6dc27d177ceef5ad29a2610715ebab6910ddecc15bcb2cbe9a67ff5898bb509183d2ad464dd0c441d28b44d0a07c02e1f3e503a628187e64cdd57b0c29f00311f63f57a77acfe4ee870eca8eefab1e4a21d8e692ed52a5ecee1929fc9d629fe9bd6e1b9c669c3cc08a531e851ed1ecfbc056d3c24170eb55637b70702009e)
> 
> --> CommitSig(0155be75e94162b8b9ae30ceb5fe2621f204891132289e58eac64386c79b6470,304402202259c4d0500d129c8efbb16daf9aba48a292365fd48d8672a7470d1140bbae8502205fdd2b4fff1e1311f61b491e4f8fb81f783e92f640481f9c791e5342e895710601,List())

Remote peer LND log: http://paste.ubuntu.com/p/BD3kFqvxqh/
Full local BLW channel state: https://paste.ubuntu.com/p/Gn9CMWxhhy/

### Your environment

lnd version 0.4.2-beta commit=4bde4c1c262ddae5171240d47fcbd0b5ea1f1eae

### Steps to reproduce

Open a channel with https://1ml.com/node/03295d2e292565743a40bd44da227a820f8730877bc3dfadebade8785bcf355258, try to send a payment.

### Expected behaviour

No remote uncooperative closing.

### Actual behaviour

Remote uncooperative closing.

### LINKED ISSUE #1348: lnd-lnd force-closing due to invalid_commit_sig
two lnd trying to send 1 sat invoices to eachother. one froze in mutex-land. restarted both. channel got closed after restarts.

lnd version 0.4.2-beta commit=4bde4c1c262ddae5171240d47fcbd0b5ea1f1eae

might be closely related to #1340 

```2018-06-08 14:44:22.767 [ERR] HSWC: ChannelLink(522968:666:1) Failing link: ChannelPoint(9d3f4868ec2d1c4c8c7da14d4e60adb08a57ee9f73743066d9f9e0a31ecf9acd:1): unable to accept new commitment: rejected commitment: commit_height=594, invalid_commit_sig=3044022026ed0d5ac10ca73cd7358aeb30abfdaadc8cbd8f173f8b84b20e61d55ccc6d04022045b7363a5e1295d20a39b008be240c39a4f0a232982b3a75beed28eb8037d235, commit_tx=0200000001cd9acf1ea3e0f9d9663074739fee578ab0ad604e4da17d8c4c1c2dec68483f9d0100000000a1b71280023d0a020000000000220020a4d327d89eee074a20bbe25f5d0c5955a7ab50d1566a45ea1621222b71696a3577340d000000000016001409a2344fd318ff0478b2f5663cdcbf4ff70b6028fc55d720, sig_hash=2389fc4abd70c5c97696513bfd73f0393ee9b70f515403ee117f387d65f903ed```

### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### PR DESCRIPTION
**Pull request by cfromknecht**
Alters the htlcswitch to reject duplicate links and purge all link indexes upon removal. Previously we would only purge either the live or pending indexes.

Fixes #1348. 
Fixes #1342.

### CODE REVIEW

File: htlcswitch/switch.go [hunk 1]
```diff
@@ -1772,24 +1779,18 @@ func (s *Switch) addLiveLink(link ChannelLink) {
...
 // request will be propagated/handled to/in the main goroutine.
 func (s *Switch) GetLink(chanID lnwire.ChannelID) (ChannelLink, error) {
 	s.indexMtx.RLock()
 	defer s.indexMtx.RUnlock()
 
+	return s.getLink(chanID)
+}
+
+// getLink returns the link stored in either the pending index or the live
+// lindex.
```
Comment (halseth) [inline htlcswitch/switch.go]: nit: index

**Comment by halseth** [comment]
One integration test failing, not sure if related to the change.

**Comment by Roasbeef** [comment]
Failure possibly related to the ping pong peer issue? Once we get this, and the combined set of fixes for the server concurrent connections selection algorithm, then we can have a new base line to evaluate bug reports and fixes from.

**Comment by offerm** [comment]
@halseth @Roasbeef Integration tests seem to fail consistently, at the same point,  after this merge, No problem before the merge. 

Can you have a look please

File: htlcswitch/switch.go [hunk 2]
```diff
@@ -1829,23 +1830,23 @@ func (s *Switch) RemoveLink(chanID lnwire.ChannelID) error {
...
-		delete(s.pendingLinkIndex, chanID)
-		link.Stop()
+	// Remove the channel from live link indexes.
+	delete(s.pendingLinkIndex, link.ChanID())
+	delete(s.linkIndex, link.ChanID())
+	delete(s.forwardingIndex, link.ShortChanID())
+
+	// Remove the channel from channel index.
+	peerPub := link.Peer().PubKey()
+	delete(s.interfaceIndex, peerPub)
```
Comment (Roasbeef) [inline htlcswitch/switch.go]: As is, this'll remove all the links for a peer, rather than just remove this particular link. Also just now realizing that `removeLinkLink` did the same thing as well.

Comment (cfromknecht) [reply htlcswitch/switch.go]: so disconneting one peer removes forwarding over all channels w/ that peer?

**Comment by Roasbeef** [comment]
As is, yes would seem that's the case

**Comment by Roasbeef** [comment]
Thanks for the report we're looking into it
