### PR TITLE
REST saga 3/3: REST API for subservers, websocket for streaming responses

### LINKED ISSUE #2344: REST API CORS headers
### Background

If a web application wanted to use an LND node, requests would be blocked even if the REST API were exposed due to the lack of a `Access-Control-Allow-Origin` header. I don't know that there's much harm in setting it to `*` by default, since you'd need macaroons for the node to do pretty much anything anyway.

This is somewhat of a duplicate of #1405, however that issue went a little off-topic with a fork of LND.

### Your environment

* version of `lnd` - 0.5.1
* which operating system (`uname -a` on *Nix) - Ubuntu Server 16.04
* version of `btcd`, `bitcoind`, or other backend - bitcoind

### LINKED ISSUE #2730: rpc: REST endpoint for CloseChannel hangs
### Background

When sending an HTTP request to `DELETE /v1/channels/{channel_point.funding_txid_str}/{channel_point.output_index}`, the response hangs until the next block is mined. When the response is returned it contains two JSON objects instead of a single one. 

```
{"result":{"close_pending":{"txid":"3F8yolDdkh8OEVmdnK8lHlQaNG7a+qtHbw3WLHITGeU="}}}
{"result":{"chan_close":{"closing_txid":"3F8yolDdkh8OEVmdnK8lHlQaNG7a+qtHbw3WLHITGeU="}}}
```

i skimmed through the [rpc.proto](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L412) file and noticed that the `SendPayment` and `OpenChannel` have *Sync versions for the REST proxy but `CloseChannel` does not. It returns a `stream` instead of a response object, which I believe may be the reason why it hangs until the async operation completes.

There is also no way to pass in the `--force` parameter via the REST API. Currently the two parameters for `funding_txid` and `output_index` are supplied in the URL. The endpoint does not have a way to provide the additional options, such as `force`, `time_limit`, `block`, `conf_target`, `sat_per_byte`.

### Your environment

* version of `lnd`: tested 0.5.2-beta and master branch as of [2a65245](https://github.com/lightningnetwork/lnd/commit/2a652455aaea661b147b6adca0ff51edcd268508)
* which operating system (`uname -a` on *Nix): Ubuntu 16.04.5 LTS and Windows 10 Pro 1803
* version of `btcd`, `bitcoind`, or other backend: btcd version 0.12.0-beta (using --simnet)

### Steps to reproduce

Try to close a channel via the REST API using Postman or curl
```
curl -X DELETE \ 
 https://localhost:8001/v1/channels/1c1cc3d7fb9c5a94628186a376d0c832dced9951968733db745c66aa9ba4cd2d/1 \
  -H 'Content-Type: application/json' \
  -H 'grpc-metadata-macaroon: 0201036c6e6402cf01030a10cd26e692e9db0389751f18280815c0b71201301a160a0761646472657373120472656164120577726974651a130a04696e666f120472656164120577726974651a170a08696e766f69636573120472656164120577726974651a160a076d657373616765120472656164120577726974651a170a086f6666636861696e120472656164120577726974651a160a076f6e636861696e120472656164120577726974651a140a057065657273120472656164120577726974651a120a067369676e6572120867656e657261746500000620c1dab9cfeacb111ece9e9e49d98bc552ceec7dd4bacbde42f875ba2eb3e0bc4b'
```

Here's a screen cap of the issue in action on simnet
https://imgur.com/a/kGc3mzy

### Expected behaviour

The HTTP response should return synchronously with the `closing_txid`

### Actual behaviour

The HTTP response hangs until the next block is mined, which will be in minutes on mainnet/testnet

### LINKED ISSUE #3430: LND Rest API Estimate Fee Endpoint incorrect?
### Background

When using the estimate fee endpoint in the REST API aka
https://api.lightning.community/rest/#get-v1-transactions-fee

it does not require the AddrToAmount parameter like this GRPC version requires, furthermore when making a request it returns the error "no outputs"

### Your environment

* version of `lnd`
0.7
* which operating system (`uname -a` on *Nix)
Mac OS 10.14.6
* version of `btcd`, `bitcoind`, or other backend
bitcoind 18.1
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
I made a request to the REST api over TOR like so
http://vmsgj6t6t2l542rt3hqacpyqtt5upimhxfefiejkkrjiylblwzmys4id.onion/lnd-rest/btc/v1/transactions/fee?target_conf=2

### Expected behaviour

The API should require the AddrToAmount parameter but this is not stated in the documentation

Tell us what should happen

### Actual behaviour

AddrToAmount is not required according to the documentation and a "no outputs" error is returned

### LINKED ISSUE #3622: Consider phasing out *Sync methods for REST in favor of websockets
Having to develop off of the REST API for Joule, it's clear that it's a bit of a brittle thing, and the endpoints often either diverge a bit due to the duplicated code between the async and sync methods, or the endpoints get hooked up with async methods and simply don't work (See `DELETE /v1/channels` and `GET /v1/invoices/subscribe`)

Ideally instead of making separate methods, the async methods could just be exposed as websockets instead of http requests. It looks like there's a library for this that wraps around `grpc-gateway` called [`grpc-websocket-proxy`](https://github.com/tmc/grpc-websocket-proxy) that would hopefully work out of the box, but it doesn't look like it's super active so I can't be sure.

The main difficulty with this would be the lack of customizable headers for websocket requests. It'd either have to be appended as a query parameter, or make an HTTP request to get a one time use URL ala this suggestion: https://devcenter.heroku.com/articles/websocket-security#authentication-authorization

### LINKED ISSUE #4100: Add buildroute functionality to REST API
### Background

I am looking to create a custom route in the REST API. Especially when creating routes that dont originate at your own node, the queryroute API does not help.

### Your environment

* version of `lnd`
LND master
* which operating system (`uname -a` on *Nix)
ubuntu
* version of `btcd`, `bitcoind`, or other backend
btcd
* any other relevant environment details

Unrelated, but what is the format LND is expecting for arrays in query parameters? queryroute uses an array for 'ignored_nodes', and I cannot get it to work.

### LINKED ISSUE #4222: Add lncli version capability to REST API
### Background
I am looking to be able to use the new ```lncli version``` command in the REST environment.

### LINKED ISSUE #4229: No REST endpoint for checking the status of a single outgoing payment
Why isn't there an equivalent of /v1/invoice for outgoing payments?
I have to retrieve a massive blob of payments and parse to find whether a transaction has cleared :(

### PR DESCRIPTION
**Pull request by guggero**
This is part 3 of 3 of the REST improvement saga which will ultimately replace #4141:

- [x] Part 1/3 (#4250): Cleanup proto files, split `WalletUnlocker` into own file, generate Swagger docs for all RPCs, fix comment styles (replace `///` with `//` and `/**` with `/*`).
- [x] Part 2/3 (#4251): Add REST endpoints and `grpc-gateway` code to all subservers and update `grpc-gateway` library.
- [x] Part 3/3 (this PR): Add a WebSocket proxy to the REST listener to support streaming responses.

Depends on #4251, only the last 4 commits are new.

Updated API docs for unified gRPC/REST APIs [can be previewed here](https://www.guggero.org/lightning-api/).

Fixes #3622
Fixes #4222
Fixes #2344
Fixes #2730
Fixes #4100
Fixes #4229
Fixes #3430

### CODE REVIEW

File: rpcserver.go [hunk 1]
```diff
@@ -875,6 +895,15 @@ func addrPairsToOutputs(addrPairs map[string]int64) ([]*wire.TxOut, error) {
 	return outputs, nil
 }
 
+// allowCORS wraps the given http.Handler with a function that adds the
+// Access-Control-Allow-Origin header to the response.
+func allowCORS(handler http.Handler, origin string) http.Handler {
+	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		w.Header().Set("Access-Control-Allow-Origin", origin)
```
Comment (AnthonyRonning) [inline rpcserver.go:902]: Hey @guggero, I'm coming in from https://github.com/lightningnetwork/lnd/pull/3281. 

Just wanted to ask about your use case for CORS and whether or not this will suffice. I had started with this in my PR but ended up having to expand on it with preflight request options once I deployed something on a live domain. Simple requests don't need to worry about preflight requests but if you're passing in certain headers, for instance `grpc-metadata-macaroon`, or using PUT/DELETE requests, I think you might find that you have to handle preflights: https://github.com/lightningnetwork/lnd/pull/3281/files#diff-01ada5680aaa18fc79cbf78b2d55a37bR725

It's been awhile and I stopped doing it, just providing my experience when I first went through this from soup to nuts.

Comment (guggero) [reply rpcserver.go:902]: Hey Anthony. Thanks for the input. You are correct, this might not be enough. I'll add it to the TODO list.

Comment (AnthonyRonning) [reply rpcserver.go]: Thanks a lot @guggero! Great work on this, very happy to see it get introduced.

**Comment by sako0938** [comment]
Hey Guggero, I started trying out some of the endpoints tonight. I may have found some quirks that can help with the process.

POST /v2/wallet/address/next
Cannot send empty string data in POST body
My code has an empty string in the POST body, and that has worked so far for v1 endpoints, though I'm not sure if its really a good or bad thing. Doing it for this endpoint gave Go unmarshalling errors.

This next endpoint is the big one everyone is probably eager to use
POST /v2/router/send
It seems like it is returning data for each attempt. It is returning multiple dictionaries with {"result":} keys, when I think it should only return one. At its current state, I cannot do json.loads({}).

I was splitting along the newline to watch as it tried the attempts:
```for i in range(0,19): len(json.loads(r.text.split('\n')[i])['result']['htlcs'])```

I also tried out: GET /v2/router/htlcevents
And it seemed to work, but you saidwebsockets weren't working yet, and think these streaming ones will work better with websockets instead of the python "for loop" syntax, so I might play around with that more later.

POST /v2/router/send return data:
> '{"result":{"payment_hash":"5eb8b650f4708209bf39e14f09d05690991dc9ad949f60d4b8df1bad326819fe","value":"1000000","creation_date":"1591321010","fee":"0","payment_preimage":"0000000000000000000000000000000000000000000000000000000000000000","value_sat":"1000000","value_msat":"1000000000","payment_request":"lnbc10m1p0dngdfpp5t6utv585wzpqn0eeu98sn5zkjzv3mjddjj0kp49cmud66vngr8lqdq2w3jhxapqxgcqzpgsp52tnfp5dzv7w50pg42dd0lz6tgp5fpdn3c3ythpverj0hw2zkc4ks9qy9qsqv7d3qwkpz32dlhqrpf5nsv9f76xfd8yz6m5fw8lakc3z9f8l03usxcvzgyyh753elyds7ckdrw2rdc9ue46p4aevhsh9a9z5u78ufwcqe5myaz","status":"IN_FLIGHT","fee_sat":"0","fee_msat":"0","creation_time_ns":"1591321010843009472","htlcs":[],"payment_index":"3856","failure_reason":"FAILURE_REASON_NONE"}}\n{"result":{"payment_hash":"5eb8b650f4708209bf39e14f09d05690991dc9ad949f60d4b8df1bad326819fe","value":"1000000","creation_date":"1591321010","fee":"0","payment_preimage":"0000000000000000000000000000000000000000000000000000000000000000","value_sat":"1000000","value_msat":"1000000000","payment_request":"lnbc10m1p0dngdfpp5t6utv585wzpqn0eeu98sn5zkjzv3mjddjj0kp49cmud66vngr8lqdq2w3jhxapqxgcqzpgsp52tnfp5dzv7w50pg42dd0lz6tgp5fpdn3c3ythpverj0hw2zkc4ks9qy9qsqv7d3qwkpz32dlhqrpf5nsv9f76xfd8yz6m5fw8lakc3z9f8l03usxcvzgyyh753elyds7ckdrw2rdc9ue46p4aevhsh9a9z5u78ufwcqe5myaz","status":"IN_FLIGHT","fee_sat":"0","fee_msat":"0","creation_time_ns":"1591321010843009472","htlcs":[{"status":"IN_FLIGHT","route":{"total_time_lock":633190,"total_fees":"2","total_amt":"1000002","hops":[{"chan_id":"694210751119753216","chan_capacity":"4388592","amt_to_forward":"1000000","fee":"2","expiry":633150,"amt_to_forward_msat":"1000000000","fee_msat":"2000","pub_key":"0292052c3ab594f7b5e997099f66e8ed51b4342126dcb5c3caa76b38adb725dcdb","tlv_payload":true,"mpp_record":null,"custom_records":{}},{"chan_id":"694210751119753216","chan_capacity":"4388592","amt_to_forward":"1000000","fee":"0","expiry":633150,"amt_to_forward_msat":"1000000000","fee_msat":"0","pub_key":"0360a41eb8c3fe09782ef6c984acbb003b0e1ebc4fe10ae01bab0e80d76618c8f4","tlv_payload":true,"mpp_record":{"payment_addr":"UuaQ0aJnnUeFFVNa/4tLQGiQtnHESLuFmRyfdyhWxW0=","total_amt_msat":"1000000000"},"custom_records":{}}],"total_fees_msat":"2000","total_amt_msat":"1000002000"},"attempt_time_ns":"1591321010865159252","resolve_time_ns":"0","failure":null,"preimage":null}],"payment_index":"3856","failure_reason":"FAILURE_REASON_NONE"}}\n{"result":{"payment_hash":"5eb8b650f4708209bf39e14f09d05690991dc9ad949f60d4b8df1bad326819fe","value":"1000000","creation_date":"1591321010","fee":"2","payment_preimage":"7f2fc0cca0ecc486929e8b9cbf9659902748d483327c95d373956f3f556dcd05","value_sat":"1000000","value_msat":"1000000000","payment_request":"lnbc10m1p0dngdfpp5t6utv585wzpqn0eeu98sn5zkjzv3mjddjj0kp49cmud66vngr8lqdq2w3jhxapqxgcqzpgsp52tnfp5dzv7w50pg42dd0lz6tgp5fpdn3c3ythpverj0hw2zkc4ks9qy9qsqv7d3qwkpz32dlhqrpf5nsv9f76xfd8yz6m5fw8lakc3z9f8l03usxcvzgyyh753elyds7ckdrw2rdc9ue46p4aevhsh9a9z5u78ufwcqe5myaz","status":"SUCCEEDED","fee_sat":"2","fee_msat":"2000","creation_time_ns":"1591321010843009472","htlcs":[{"status":"SUCCEEDED","route":{"total_time_lock":633190,"total_fees":"2","total_amt":"1000002","hops":[{"chan_id":"694210751119753216","chan_capacity":"4388592","amt_to_forward":"1000000","fee":"2","expiry":633150,"amt_to_forward_msat":"1000000000","fee_msat":"2000","pub_key":"0292052c3ab594f7b5e997099f66e8ed51b4342126dcb5c3caa76b38adb725dcdb","tlv_payload":true,"mpp_record":null,"custom_records":{}},{"chan_id":"694210751119753216","chan_capacity":"4388592","amt_to_forward":"1000000","fee":"0","expiry":633150,"amt_to_forward_msat":"1000000000","fee_msat":"0","pub_key":"0360a41eb8c3fe09782ef6c984acbb003b0e1ebc4fe10ae01bab0e80d76618c8f4","tlv_payload":true,"mpp_record":{"payment_addr":"UuaQ0aJnnUeFFVNa/4tLQGiQtnHESLuFmRyfdyhWxW0=","total_amt_msat":"1000000000"},"custom_records":{}}],"total_fees_msat":"2000","total_amt_msat":"1000002000"},"attempt_time_ns":"1591321010865159252","resolve_time_ns":"1591321011235110235","failure":null,"preimage":"fy/AzKDsxIaSnoucv5ZZkCdI1IMyfJXTc5VvP1VtzQU="}],"payment_index":"3856","failure_reason":"FAILURE_REASON_NONE"}}\n'

File: lntest/itest/rest_api.go [hunk 2]
```diff
@@ -0,0 +1,352 @@
...
+	}
+	urlEnc          = base64.URLEncoding
+	webSocketDialer = &websocket.Dialer{
+		HandshakeTimeout: 45 * time.Second,
+		TLSClientConfig:  insecureTransport.TLSClientConfig,
+	}
+	resultPattern = regexp.MustCompile("{\"result\":(.*)}")
+)
+
+// testRestApi tests that the most important features of the REST API work
```
Comment (Roasbeef) [inline lntest/itest/rest_api.go:54]: Nice! I wonder if we should start to run these as a distinct job on Github. Maybe somethign to revisit later if we think we need to add a significant amount of new test cases. With this as is, we at least now have some basic sanity checks to ensure we don'[t break the RESt behavior silently for our users.

File: lntest/itest/rest_api.go [hunk 3]
```diff
@@ -0,0 +1,352 @@
...
+			ctxb := context.Background()
+			newAddrReq := &lnrpc.NewAddressRequest{
+				Type: lnrpc.AddressType_WITNESS_PUBKEY_HASH,
+			}
+			addrRes, err := a.NewAddress(ctxb, newAddrReq)
+			require.Nil(t, err, "get address")
+
+			// Create the full URL with the map query param.
+			url := "/v1/transactions/fee?target_conf=%d&" +
+				"AddrToAmount[%s]=%d"
```
Comment (Roasbeef) [inline lntest/itest/rest_api.go:123]: Oh wow, totally didn't know this was how you specified map params :p

**Comment by guggero** [comment]
@sako0938 thank you very much for testing!

> Cannot send empty string data in POST body

I don't think sending an empty POST worked before that PR. Or maybe it changed because of the library update. But in any case, a POST body _always_ has to be set. If there's no content to send, just send a `"{}"`.

> It seems like it is returning data for each attempt. It is returning multiple dictionaries with {"result":} keys, when I think it should only return one. At its current state, I cannot do json.loads({}).

That's exactly why WebSockets are needed, because there are multiple messages being returned that are valid JSON each on its own. Adding WebSocket support is the whole point of this PR (while adding the REST endpoints was done in PR 2/3). So please test again with a WS library (code examples can be found in the preview of the API doc: https://www.guggero.org/lightning-api/#v2-router-send)

> but you saidwebsockets weren't working yet

Was I referring to this PR specifically? Maybe there was a misunderstanding. They should work now :)

File: lnrpc/websocket_proxy.go [hunk 4]
```diff
@@ -0,0 +1,221 @@
...
+					p.logger.Tracef("WS: socket "+
+						"closed: %v", err)
+					return
+				}
+				p.logger.Errorf("error reading message: %v",
+					err)
+				return
+			}
+			_, err = requestBodyW.Write(append(payload, '\n'))
+			if err != nil {
```
[the remark this answers is not in the document]
Comment (guggero) [reply lnrpc/websocket_proxy.go:148]: Right, this could be inefficient. Fixed it and also made the code a bit easier to understand in general by creating a dedicated `requestForwardingReader` and `responseForwardingWriter`.

File: lntest/itest/rest_api.go (hunk 2 above)
Comment (guggero) [reply lntest/itest/rest_api.go:54]: They run pretty fast as all of these calls are pretty light-weight.
These tests should greatly increase our confidence when updating the `grpc-web` library or changing other things like JSON serializer or similar.
Added a test for CORS as well and fixed a few errors in the process.

File: lntest/itest/rest_api.go (hunk 3 above)
Comment (guggero) [reply lntest/itest/rest_api.go:125]: Yeah, that's really un-intuitive. We should avoid using GET for any messages that contain map types. I added an explicit comment to the only two RPCs where this syntax is needed.
