### PR TITLE
chanbackup: update on-disk backup file with unconfirmed channels

### LINKED ISSUE #3816: unconfirmed channels are not included in channel backup when using gRPC
### Background

Unable to recover after a hardware failure

### Your environment

* LND version 0.8.1
* Linux 5.3.12-1-default #1 SMP Thu Nov 21 07:21:43 UTC 2019 (a6f6081) x86_64 x86_64 x86_64 GNU/Linux
* bitcoin 0.18.1 running on a remote host on the LAN
* LND was originally installed on another computer which has had a hardware failure.
* channel.backup file was downloaded from RTL client. However I believe it uses LND's backup files

### Steps to reproduce and actual behaviour

Channel opened last night. channel.backup file taken and saved away from computer hosting LND. 24 word seed kept safe. The channel.backup file was taken before the channel was confirmed on-chain, but after I initiated the channel opening process.

At some point overnight, the hardware failed.

Set up LND on my desktop computer. Ran command to restore wallet: ./lncli create --multi_file=channel.backup. Enter in 24 word recovery seed. Allow LND to do its thing.

See the following in the log:

> 2019-12-10 20:17:35.689 [INF] LNWL: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=2500
2019-12-10 20:17:36.340 [INF] LNWL: Seed birthday surpassed, starting recovery of wallet from height=607115 hash=00000000000000000006de43c6f3ef4761652f2ab4b72e99cacf3958dfd82f95 with recovery-window=2500
2019-12-10 20:18:21.234 [INF] LNWL: Scanning 446 blocks for recoverable addresses
2019-12-10 20:19:55.940 [INF] LNWL: Recovered 1 external addrs at height=607437 hash=00000000000000000006fc1ff25bdefa30bf14f06f768d4f88f3323152f69de6
2019-12-10 20:19:55.940 [INF] LNWL: Found 1 spends from watched outpoints at height=607437 hash=00000000000000000006fc1ff25bdefa30bf14f06f768d4f88f3323152f69de6
2019-12-10 20:20:22.169 [INF] LNWL: Recovered addresses from blocks 607115-607560
2019-12-10 20:20:22.481 [INF] LNWL: Started rescan from block 0000000000000000000fa8e058b44e7b61b613eb961bb5a9a0fbd07df5d4a567 (height 607560) for 1 address
2019-12-10 20:20:23.450 [INF] LNWL: Catching up block hashes to height 607561, this might take a while
2019-12-10 20:20:23.453 [INF] LNWL: Done catching up block hashes
2019-12-10 20:20:23.453 [INF] LNWL: Finished rescan for 1 address (synced to block 00000000000000000008fd994b5f8310177b40c2e8cd3b997ad81e35dab0dd4b, height 607561)
2019-12-10 20:20:24.017 [INF] LTND: Chain backend is fully synced (end_height=607561)!

Which I assume is on-chain scanning. However, it doesn't appear that LND is making any attempt to recover channel balance.

Verifying channel backup gives blank response:

./lncli verifychanbackup --multi_file="channel.backup"
> {
> 
> }

Asking to manually run the restore again produces no output at all and no response from LND.
./lncli restorechanbackup --multi_file=channel.backup

Are funds safu?

### PR DESCRIPTION
**Pull request by guggero**
Fixes #3816.

Currently there is a discrepancy between the backups obtained through the gRPC call and the content of the automatically created `channel.backup` file. The RPC backups do contain pending channels while the backup file does not.
This PR aims to fix that discrepancy.

### CODE REVIEW

File: fundingmanager.go [hunk 1]
```diff
@@ -1697,7 +1697,7 @@ func (f *fundingManager) handleFundingCreated(fmsg *fundingCreatedMsg) {
 
 	// Inform the ChannelNotifier that the channel has entered
 	// pending open state.
-	f.cfg.NotifyPendingOpenChannelEvent(fundingOut)
+	f.cfg.NotifyPendingOpenChannelEvent(fundingOut, completeChan)
```
Comment (halseth) [inline fundingmanager.go]: so at this point the notification will trigger an update of the SCB on the gRPC API. When is the file backup triggered?

Comment (guggero) [reply fundingmanager.go]: The `chanbackup.SubSwapper` gets this notification and then updates the file backup. But you are right, I forgot the `SubscribeChannelBackups`, that should also be updated with pending channels. The synchronous RPC `ExportAllChannelBackups` always contained the unconfirmed channels because the backups were assembled on-the-fly.

File: fundingmanager_test.go [hunk 2]
```diff
@@ -867,6 +915,18 @@ func assertMarkedOpen(t *testing.T, alice, bob *testNode,
...
+	// Make sure the notification about the pending channel was sent out.
+	select {
+	case <-alice.mockChanEvent.openEvent:
+	case <-time.After(time.Second * 5):
+		t.Fatalf("alice did not send open channel event")
+	}
+	select {
+	case <-bob.mockChanEvent.openEvent:
+	case <-time.After(time.Second * 5):
+		t.Fatalf("alice did not send open channel event")
```
Comment (cfromknecht) [inline fundingmanager_test.go]:
```suggestion
		t.Fatalf("bob did not send open channel event")
```

File: fundingmanager_test.go [hunk 3]
```diff
@@ -685,6 +721,18 @@ func fundChannel(t *testing.T, alice, bob *testNode, localFundingAmt,
...
+	// Make sure the notification about the pending channel was sent out.
+	select {
+	case <-alice.mockChanEvent.pendingOpenEvent:
+	case <-time.After(time.Second * 5):
+		t.Fatalf("alice did not send pending channel event")
+	}
+	select {
+	case <-bob.mockChanEvent.pendingOpenEvent:
+	case <-time.After(time.Second * 5):
+		t.Fatalf("alice did not send pending channel event")
```
Comment (cfromknecht) [inline fundingmanager_test.go]:
```suggestion
		t.Fatalf("bob did not send pending channel event")
```

File: lntest/itest/lnd_test.go [hunk 4]
```diff
@@ -14367,10 +14382,48 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
 			},
 		},
 
-		// Create a backup from an unconfirmed channel and make sure
-		// recovery works as well.
+		// Use the channel backup file that contains an unconfirmed
+		// channel and make sure recovery works as well.
+		{
+			name:            "restore unconfirmed channel file",
```
Comment (cfromknecht) [inline lntest/itest/lnd_test.go]: nice, simple test :)

**Comment by guggero** [comment]
> are these pending channels ever cleaned up if the channels never confirm?

Good question. What happens with them in the channel DB? Are they detected and removed after a certain time? Or would you need to call `abandonchannel` on them? If the latter is true then we can just add the close notification to `AbandonChannel`.
But still, you might want to keep the backup in case it ever confirms for whatever reason. It's a few hundred bytes per channel and their number should be very limited so I'm not too worried about the size of the backup file.

File: fundingmanager_test.go [hunk 5]
```diff
@@ -274,6 +298,17 @@ func createTestFundingManager(t *testing.T, privKey *btcec.PrivateKey,
 		bestHeight: fundingBroadcastHeight,
 	}
 
+	// The mock channel event notifier will receive events for each pending
```
Comment (halseth) [inline fundingmanager_test.go]: Solid test addition 👍

File: channel_notifier.go [hunk 6]
```diff
@@ -75,8 +75,39 @@ func (c *channelNotifier) SubscribeChans(startingChans map[wire.OutPoint]struct{
...
 				switch event := e.(type) {
 
-				// A new channel has been opened, we'll obtain
-				// the node address, then send to the
+				// A new channel has been opened and is still
+				// pending. We can still create a backup, even
+				// if the final channel ID is not yet available.
+				case channelnotifier.PendingOpenChannelEvent:
+					pendingChan := event.PendingChannel
+					nodeAddrs, err := c.addrs.AddrsForNode(
```
Comment (halseth) [inline channel_notifier.go]: Possible to reuse the logic below from `OpenChanEvent`?

**Comment by halseth** [comment]
> > are these pending channels ever cleaned up if the channels never confirm?
> 
> Good question. What happens with them in the channel DB? Are they detected and removed after a certain time? Or would you need to call `abandonchannel` on them? If the latter is true then we can just add the close notification to `AbandonChannel`.
> But still, you might want to keep the backup in case it ever confirms for whatever reason. It's a few hundred bytes per channel and their number should be very limited so I'm not too worried about the size of the backup file.

Yes, currently they will stay around (only if you're the initiator) until `abandonchannel` is called. There is an existing issue/PR to address this: #1755, for now I think it is okay the backup stays around until abandon channel is called.

**Comment by guggero** [comment]
I added a commit to remove the channel from the backup file if `abaondonchannel` is called.
