### PR TITLE
routerrpc+lntest: add nil check for failure detail and add itest coverage

### LINKED ISSUE #4233: Rendezvous of RPC that terminate in new SubscribeHtlcEvents
### Background
Hi, I've used this new https://api.lightning.community/?python#subscribehtlcevents call, (after fixing a bug in the documentation... ) 
This is the code that I used
```python
import codecs, grpc, os
import router_pb2 as lnd, router_pb2_grpc as routerrpc
import time
import pickle


macaroon = codecs.encode(open('/home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon', 'rb').read(), 'hex')
os.environ['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA'
cert = open('/home/admin/.lnd/tls.cert', 'rb').read()
ssl_creds = grpc.ssl_channel_credentials(cert)
channel = grpc.secure_channel('localhost:10009', ssl_creds)
stub = routerrpc.RouterStub(channel)
request = lnd.SubscribeHtlcEventsRequest()
print("Running")                                                                                                                                                                                               
responses = []                                                                                                                                                                                                 
response_id = 0                                                                                                                                                                                                
for response in stub.SubscribeHtlcEvents(request, metadata=[('macaroon', macaroon)]):                                                                                                                          
    print('res_id = ' + str(response_id))                                                                                                                                                                      
    print(response)

```

But after a while (at res_id 19) I got this error:
```
_Rendezvous: <_Rendezvous of RPC that terminated with:                                                                                                                                      
        status = StatusCode.UNKNOWN           
        details = "unknown failure detail type: <nil>"                                                                                                                                       
        debug_error_string = "{"created":"@1588220504.572403636","description":"Error received from peer ipv4:127.0.0.1:10009","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_m
essage":"unknown failure detail type: <nil>","grpc_status":2}"
```

### Your environment

lnd version 0.10.0-beta commit=v0.10.0-beta
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux

Thanks

### PR DESCRIPTION
**Pull request by carlaKC**
Add a nil check for `LinkEvent` failure details so that the stream succeeds for link failures that do not have a  `FailureDetail`. 

Add coverage in itests for successful and failure cases for event streams, including a case where the failure detail is nil. 

Fixes #4233

### CODE REVIEW

File: lntest/itest/lnd_test.go [hunk 1]
```diff
@@ -4671,6 +4671,40 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
 		lnd.DefaultBitcoinTimeLockDelta, maxHtlc, carol,
 	)
 
+	// Before we start sending payments, subscribe to htlc events for each
+	// node.
+	ctxt, _ = context.WithTimeout(ctxb, defaultTimeout)
+	aliceEvents, err := net.Alice.RouterClient.SubscribeHtlcEvents(
+		ctxb, &routerrpc.SubscribeHtlcEventsRequest{},
```
Comment (guggero) [inline lntest/itest/lnd_test.go:4678]: This needs to be `ctxt`. Also you could use the same instance of `ctxt` for all events as they are expected to live for the same duration.

File: lntest/itest/lnd_test.go [hunk 2]
```diff
@@ -4779,6 +4835,48 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
...
+			t.Fatalf("expected: %v, got: %v", expectedType,
+				event.EventType)
+		}
+
+		switch event.Event.(type) {
+		case *routerrpc.HtlcEvent_ForwardEvent:
+			forwards++
+
+		case *routerrpc.HtlcEvent_SettleEvent:
+			settles++
```
Comment (guggero) [inline lntest/itest/lnd_test.go:4865]: nit: add newline after.

File: lntest/itest/lnd_test.go [hunk 3]
```diff
@@ -9610,6 +9610,32 @@ out:
 		t.Fatalf("channel not seen by alice before timeout: %v", err)
 	}
 
+	// Before we start sending payments, subscribe to htlc events for each
+	// node.
+	ctxt, _ = context.WithTimeout(ctxb, defaultTimeout)
+	aliceEvents, err := net.Alice.RouterClient.SubscribeHtlcEvents(
+		ctxb, &routerrpc.SubscribeHtlcEventsRequest{},
```
Comment (guggero) [inline lntest/itest/lnd_test.go:9617]: Same here concerning `ctxt` and reuse of it.

File: lntest/itest/lnd_test.go [hunk 4]
```diff
@@ -9805,6 +9865,83 @@ out:
 	cleanupForceClose(t, net, net.Bob, chanPointBob)
 }
 
+func assertEventAndType(t *harnessTest,
+	eventType routerrpc.HtlcEvent_EventType,
+	client routerrpc.Router_SubscribeHtlcEventsClient) *routerrpc.HtlcEvent {
+	event, err := client.Recv()
```
Comment (guggero) [inline lntest/itest/lnd_test.go:9871]: nit: add newline before.

File: lntest/itest/lnd_test.go [hunk 5]
```diff
@@ -9805,6 +9865,83 @@ out:
 	cleanupForceClose(t, net, net.Bob, chanPointBob)
 }
 
+func assertEventAndType(t *harnessTest,
```
Comment (guggero) [inline lntest/itest/lnd_test.go:9868]: Could this also be used in the `assertHtlcEvents` from the previous commit?

File: lntest/itest/lnd_test.go [hunk 6]
```diff
@@ -4779,6 +4832,57 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
...
+	if forwards != fwdCount {
+		t.Fatalf("expected: %v forwards, got: %v", fwdCount, forwards)
+	}
+
+	if settles != settleCount {
+		t.Fatalf("expected: %v settles, got: %v", settleCount, settles)
+	}
+}
+
+func assertEventAndType(t *harnessTest,
```
Comment (joostjager) [inline lntest/itest/lnd_test.go:4870]: go doc missing

File: lntest/itest/lnd_test.go [hunk 7]
```diff
@@ -4779,6 +4832,57 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
...
+	expectedType routerrpc.HtlcEvent_EventType,
+	client routerrpc.Router_SubscribeHtlcEventsClient) {
+
+	var forwards, settles int
+
+	numEvents := fwdCount + settleCount
+	for i := 0; i < numEvents; i++ {
+		event := assertEventAndType(t, expectedType, client)
+
+		switch event.Event.(type) {
```
Comment (joostjager) [inline lntest/itest/lnd_test.go:4849]: At this point, it is already know that the event is of the given fixed type `expectedType`. Is it still necessary to do this switch? I would think that it is sufficient to have just a single counter, that counts the number of events of that given type.

File: lntest/itest/lnd_test.go [hunk 8]
```diff
@@ -4671,6 +4671,37 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
 		lnd.DefaultBitcoinTimeLockDelta, maxHtlc, carol,
 	)
 
+	// Before we start sending payments, subscribe to htlc events for each
+	// node.
+	ctxt, _ = context.WithTimeout(ctxb, defaultTimeout)
+	aliceEvents, err := net.Alice.RouterClient.SubscribeHtlcEvents(
+		ctxt, &routerrpc.SubscribeHtlcEventsRequest{},
+	)
```
Comment (joostjager) [inline lntest/itest/lnd_test.go:4679]: Is there an unsubscribe needed?

File: lntest/itest/lnd_test.go [hunk 9]
```diff
@@ -4671,6 +4671,37 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
...
+	if err != nil {
+		t.Fatalf("could not subscribe events: %v", err)
+	}
+
+	daveEvents, err := dave.RouterClient.SubscribeHtlcEvents(
+		ctxt, &routerrpc.SubscribeHtlcEventsRequest{},
+	)
+	if err != nil {
+		t.Fatalf("could not subscribe events: %v", err)
+	}
```
Comment (joostjager) [inline lntest/itest/lnd_test.go:4703]: Maybe it is possible to start with a `map[node]expectation`. Then subscribe in a loop to all map keys (the nodes) and later on assert on the events also in a loop. (brainstorming to see if the event assertions can be structured more)

File: lntest/itest/lnd_test.go [hunk 10]
```diff
@@ -9811,6 +9869,67 @@ out:
...
+	// Get the follow up settle or fail event.
+	resolution := assertEventAndType(t, eventType, client)
+
+	// Check for a settle if we expect a successful forward, otherwise check
+	// for a failure.
+	if success {
+		_, ok = resolution.Event.(*routerrpc.HtlcEvent_SettleEvent)
+	} else {
+		_, ok = resolution.Event.(*routerrpc.HtlcEvent_ForwardFailEvent)
+	}
```
Comment (joostjager) [inline lntest/itest/lnd_test.go:9893]: This assert function uses a somewhat different style compared to the one in the previous commit. Wouldn't it be possible to unify this? Perhaps define an enum with everything that we can expect and then do: `assert(alice, FORWARD, SETTLE)`

A helper function likes `assertForward` is nice, but it also makes it a little less explicit what the raw expectation is.

File: lntest/itest/lnd_test.go [hunk 11]
```diff
@@ -4671,6 +4671,37 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
 		lnd.DefaultBitcoinTimeLockDelta, maxHtlc, carol,
 	)
 
+	// Before we start sending payments, subscribe to htlc events for each
```
Comment (joostjager) [inline lntest/itest/lnd_test.go:4674]: We are in the process of splitting lnd itests into their own files when we touch a file. You could also do that for this PR (non blocking).

File: lntest/itest/lnd_test.go (hunk 7 above)
Comment (carlaKC) [reply lntest/itest/lnd_test.go:4849]: We have two different types we're checking here 
- `assertEventAndType`: check that the htlc event is labelled as a send/receive/forward as expected
- This switch, where we check whether the event is a settle or forward

For example a sending node has a forward of type send, and a settle of type send because those are the two htlc events associated with their single send.

File: lntest/itest/lnd_test.go (hunk 10 above)
Comment (carlaKC) [reply lntest/itest/lnd_test.go:9893]: Flattened this to just use the event count. Only `assertLinkFailure` remains separate because we check additional information on the event.

File: lntest/itest/lnd_multi-hop-payments.go [hunk 12]
```diff
@@ -280,10 +314,94 @@ func testMultiHopPayments(net *lntest.NetworkHarness, t *harnessTest) {
...
 	closeChannelAndAssert(ctxt, t, net, dave, chanPointDave, false)
 	ctxt, _ = context.WithTimeout(ctxb, channelCloseTimeout)
 	closeChannelAndAssert(ctxt, t, net, carol, chanPointCarol, false)
 }
+
+// assertHtlcEvents consumes events from a client and ensures that they are of
+// the expected type and contain the expected number of forwards, forward
+// failures and settles.
+func assertHtlcEvents(t *harnessTest, fwdCount, fwdFailCount, settleCount int,
+	userType routerrpc.HtlcEvent_EventType,
```
Comment (joostjager) [inline lntest/itest/lnd_multi-hop-payments.go:352]: For test readability, a struct containing `fwdCount`, `fwdFailCount`, `settleCount` and `userType` would have been nice (non blocking)

File: lntest/itest/lnd_multi-hop-payments.go [hunk 13]
```diff
@@ -0,0 +1,407 @@
...
+	}
+}
+
+// assertEventAndType reads an event from the stream provided and ensures that
+// it is associated with the correct user related type - a user initiated send,
+// a receive to our node or a forward through our node. Note that this event
+// type is different from the htlc event type (forward, link failure etc).
+func assertEventAndType(t *harnessTest, eventType routerrpc.HtlcEvent_EventType,
+	client routerrpc.Router_SubscribeHtlcEventsClient) *routerrpc.HtlcEvent {
+	event, err := client.Recv()
```
Comment (guggero) [inline lntest/itest/lnd_multi-hop-payments.go:396]: nit: insert newline above
