### PR TITLE
bimodal pathfinding probability improvements

### LINKED ISSUE #7553: Forgetting learnt uncertainty reduction of liquidity in case of contradictions
While doing the information theoretic payment delivery you keep track of two values for each channel in each direction 

1. `failAmount`  is the amount that in your last observation the channel was not able to forward
2. `successAmount` is the amount that in your last observation the channel was able to forward

In the follwoing line you make a sanity check:

https://github.com/lightningnetwork/lnd/blob/51df3e5b1ea2f1f749652cecf26e7471d35aa629/routing/probability_bimodal.go#L511

if the check triggers you return a `0` probability. However I think it might make sense to just reset the learnt knowledge as it is clearly outdated to `successAmount = 0` and `failAmount = capacity` and compute the probability from there and relearn knowledge by potentially attempting a payment (depending on the result of the probability result). Of course instead of resetting both variables one could only reset the one variable for which the information is older.

btw I didn't say that before but I like the naming `failAmount` and `successAmount` better than eclairs naming `high` and `low` or my own naming `maxLiquidity` and `minLiquidity`.

### LINKED ISSUE #8263: [bug]: logs heavily spammed by `[ERR] CRTR: error computing probability to node:`
### Background

Found out I had a FC 2 hours before, went searching the logs but couldn't find anything useful, realized I had 204MB of logs for the last 1.5hrs and nothing more. Debuglevel is `info`, I do have a very aggressive rebalancer, but every file is made 99% of very long lines starting with
`[ERR] CRTR: error computing probability to node:`
followed by what appears to me to be a list of past "scores" for previous payments.
I don't really care for that data and would expect it to be in `debug` rather than `info`, this way I am forced to increase to the sky the size of the log rotation just to accomodate for data I do not really care for

### Your environment

* version of `lnd` 0.17.0
* which operating system (`uname -a` on *Nix) //
* version of `btcd`, `bitcoind`, or other backend //
* any other relevant environment details //

### Steps to reproduce

Have up to 30 rebalance threads going, with my secret routerRPC sauce

### Expected behaviour

Sane log amount

### Actual behaviour

Logs spammed into oblivion by non-required data

### PR DESCRIPTION
**Pull request by bitromortac**
## Change Description
Fixes normalization bugs with respect to large channels and situations where the channel doesn't obey a bimodal distribution (fixes #8263 and #9085). 

The probability calculation is avoided for amounts smaller than the last success amount in order to speed things up. This also fixes a case where mission control has outdated values (fixes #7553).

### CODE REVIEW

File: routing/probability_bimodal_test.go [hunk 1]
```diff
@@ -309,6 +309,20 @@ func TestIntegral(t *testing.T) {
 	}
 }
 
+// TestSpecialCase tests a value combination found by fuzz tests.
+func TestSpecialCase(t *testing.T) {
```
Comment (yyforyongyu) [inline routing/probability_bimodal_test.go:369]: This name is too generic and gives very little info about what's being tested here...maybe add a link to https://github.com/lightningnetwork/lnd/issues/9085?

**Review by yyforyongyu — COMMENTED** [review]
Looking good. Will do a second round to reload the bimodal to understand the implications. Meanwhile left some questions, also think this is missing a rebase (checked out locally and ignored files popped up).

File: routing/probability_bimodal_test.go [hunk 2]
```diff
@@ -11,10 +11,10 @@ import (
 )
 
 const (
-	smallAmount = lnwire.MilliSatoshi(400_000)
-	largeAmount = lnwire.MilliSatoshi(5_000_000)
-	capacity    = lnwire.MilliSatoshi(10_000_000)
-	scale       = lnwire.MilliSatoshi(400_000)
+	smallAmount = lnwire.MilliSatoshi(400_000_000)
```
[the remark this answers is not in the document]
Comment (bitromortac) [reply routing/probability_bimodal_test.go:14]: Not entirely different values, one should be able to multiply those values by any same number (here by 1000) and the tests should stay invariant, because that number cancels out if you look at `primitive`.

File: routing/probability_bimodal_test.go (hunk 1 above)
Comment (bitromortac) [reply routing/probability_bimodal_test.go]: Totally, I changed it and added some description.

File: docs/release-notes/release-notes-0.19.0.md [hunk 3]
```diff
@@ -40,6 +40,12 @@
   a graceful shutdown of LND during the main chain backend sync check in certain
   cases.
 
+* [Bimodal pathfinding probability
```
[the remark this answers is not in the document]
Comment (bitromortac) [reply docs/release-notes/release-notes-0.19.0.md]: I changed it to target 20, but I think it could be included earlier since it's basically a bug fix PR.

File: routing/probability_bimodal.go [hunk 4]
```diff
@@ -423,27 +423,31 @@ func cannotSend(failAmount, capacity lnwire.MilliSatoshi, now,
 // unbalanced channels, a very high scale assumes a random distribution. More
 // details can be found in
 // https://github.com/lightningnetwork/lnd/issues/5988#issuecomment-1131234858.
+// Additionally, we add a constant term 1/c to the distribution to avoid
```
Comment (yyforyongyu) [inline routing/probability_bimodal.go:426]: should we also update `P(x) ~ exp(-x/s) + exp((x-c)/s)` above to have this new constant?

File: routing/probability_bimodal.go [hunk 5]
```diff
@@ -423,27 +423,31 @@ func cannotSend(failAmount, capacity lnwire.MilliSatoshi, now,
...
+// previous success and fail amounts contradict a bimodal distribution.
 func (p *BimodalEstimator) primitive(c, x float64) float64 {
 	s := float64(p.BimodalScaleMsat)
 
 	// The indefinite integral of P(x) is given by
-	// Int P(x) dx = H(x) = s * (-e(-x/s) + e((x-c)/s)),
+	// Int P(x) dx = H(x) = s * (-e(-x/s) + e((x-c)/s) + x/(c*s)),
 	// and its norm from 0 to c can be computed from it,
-	// norm = [H(x)]_0^c = s * (-e(-c/s) + 1 -(1 + e(-c/s))).
+	// norm = [H(x)]_0^c = s * (-e(-c/s) + 1 + 1/s -(1 + e(-c/s))) =
```
Comment (yyforyongyu) [inline routing/probability_bimodal.go:435]:
```suggestion
	// norm = [H(x)]_0^c = s * (-e(-c/s) + 1 + 1/s -(-1 + e(-c/s))) =
```

File: routing/probability_bimodal.go [hunk 6]
```diff
@@ -423,27 +423,31 @@ func cannotSend(failAmount, capacity lnwire.MilliSatoshi, now,
...
 	excs := math.Exp((x - c) / s)
-
-	// norm can only become zero, if c is zero, which we sorted out before
-	// calling this method.
-	norm := -2*ecs + 2
+	exs := math.Exp(-x / s)
 
 	// We end up with the primitive function of the normalized P(x).
-	return (-exs + excs) / norm
+	return (-exs + excs + x/(c*s)) / norm
```
Comment (yyforyongyu) [inline routing/probability_bimodal.go:450]: This is a very interesting mix of bimodal and uniform distribution - can `c` here ever be 1? just thinking about edge cases here.

File: routing/probability_bimodal.go (hunk 5 above)
Comment (bitromortac) [reply routing/probability_bimodal.go]: Thanks a lot, fortunately only a typo in the comment.

File: routing/probability_bimodal.go [hunk 7]
```diff
@@ -508,16 +508,17 @@ func (p *BimodalEstimator) probabilityFormula(capacityMsat, successAmountMsat,
...
+	// We discard the knowledge for the channel in that case. Note that
+	// this condition should only happen due to the two corrections above,
+	// as mission control already enforces successAmount < failAmount.
 	if failAmount <= successAmount {
 		log.Tracef("fail amount (%v) is smaller than or equal the "+
 			"success amount (%v) for capacity (%v)",
 			failAmountMsat, successAmountMsat, capacityMsat)
 
-		return 0.0, nil
+		successAmount = 0
```
[the remark this answers is not in the document]
Comment (bitromortac) [reply routing/probability_bimodal.go]: Thanks for your detailed review here, right this is all coupled. I decided to move the sanity check up in order to see the original input to the method if this code gets executed. I also altered the rescaling slightly and hope that it makes sense.

File: routing/probability_bimodal.go [hunk 8]
```diff
@@ -484,43 +488,57 @@ func (p *BimodalEstimator) probabilityFormula(capacityMsat, successAmountMsat,
...
 		failAmount = capacity
 	}
 
-	// successAmount should be capacity at max.
-	if successAmount > capacity {
-		log.Debugf("Correcting successAmount %v to capacity %v",
-			successAmount, capacity)
-
-		successAmount = capacity
+	// Mission control may have some outdated values with regard to the
```
Comment (yyforyongyu) [inline routing/probability_bimodal.go:503]: nice doc💯

File: routing/probability_bimodal.go [hunk 9]
```diff
@@ -484,43 +488,57 @@ func (p *BimodalEstimator) probabilityFormula(capacityMsat, successAmountMsat,
...
+	// In case we have a large success we need to correct it to be in the
+	// valid range. We set the success amount close to the capacity, because
+	// we assume to still be able to send. Any possible failure (that must
+	// in this case be larger than the capacity) is corrected as well.
+	if successAmount >= capacity {
+		log.Debugf("Correcting success amount %s and failure amount "+
+			"%s to capacity %s", successAmountMsat,
+			failAmount, capacityMsat)
+
+		successAmount = capacity - 1
```
Comment (yyforyongyu) [inline routing/probability_bimodal.go:519]: hmm what's the reason for minus 1?

File: routing/probability_bimodal.go [hunk 10]
```diff
@@ -484,43 +488,57 @@ func (p *BimodalEstimator) probabilityFormula(capacityMsat, successAmountMsat,
...
-			failAmount, capacity)
+	// The next statement is a safety check against an illogical condition.
+	// We discard the knowledge for the channel in that case since we have
+	// inconsistent data.
+	if failAmount <= successAmount {
+		log.Warnf("Fail amount (%s) is smaller than or equal to the "+
+			"success amount (%s) for capacity (%s)",
+			failAmountMsat, successAmountMsat, capacityMsat)
 
+		successAmount = 0
```
Comment (yyforyongyu) [inline routing/probability_bimodal.go:499]: In this case should we keep the `failAmount` the same and only let it be changed under `if failAmount > capacity {`?

File: routing/probability_bimodal.go (hunk 6 above)
Comment (yyforyongyu) [reply routing/probability_bimodal.go:450]: Still curious about the `c`, what happens if it is 1?

**Review by yyforyongyu — COMMENTED** [review]
For the itest failures, the neutrino one is a known issue, the other [one](https://github.com/lightningnetwork/lnd/actions/runs/14597515788/job/40947103655?pr=8330) is weird and looks like it's related to the `listunspent` bug, could you rebase to the latest master to include the fix?

File: routing/probability_bimodal.go (hunk 6 above)
Comment (bitromortac) [reply routing/probability_bimodal.go:450]: I think my comment got lost here. In practice that would mean that the combined distribution would be dominated by a uniform one. We could use a small constant as well here, but I wanted to avoid adding that. The 1/c term just represents a number that should be small with respect to the capacity.

File: routing/probability_bimodal.go (hunk 10 above)
Comment (bitromortac) [reply routing/probability_bimodal.go:499]: This expresses that we don't know which of the fail/success amounts has the true info and overriding both expresses that we are unsure about both, which is why I prefer to have it in a symmetric way. An idea here is that we could only override the more outdated observation with the bounds (but I think that we should not encounter that line anyhow because of mission control enforcing the condition, so that would be over-engineered).

File: routing/probability_bimodal_test.go [hunk 11]
```diff
@@ -242,6 +242,39 @@ func TestSuccessProbability(t *testing.T) {
...
+		BimodalConfig: BimodalConfig{BimodalScaleMsat: scale},
+	}
+
+	// An amount that's close to the success amount should have a very high
+	// probability.
+	amtCloseSuccess := successAmount + 1
+	_, err := estimator.probabilityFormula(
+		capacity, successAmount, failAmount, amtCloseSuccess,
+	)
+	require.ErrorContains(t, err, "normalization factor is zero")
```
Comment (ziggie1984) [inline routing/probability_bimodal_test.go]: Interesting that in only fails in the reNorm calculation not already when calculating the prob:

```
	prob := p.integral(capacity, amount, failAmount)

```

File: routing/probability_bimodal_test.go [hunk 12]
```diff
@@ -269,10 +269,30 @@ func TestSmallScale(t *testing.T) {
...
+	// An amount that's close to the fail amount should have a very low
+	// probability.
+	amtCloseFail := failAmount - 1
+	p, err = estimator.probabilityFormula(
+		capacity, successAmount, failAmount, amtCloseFail,
+	)
+	require.NoError(t, err)
+	require.InDelta(t, 0.0, p, defaultTolerance)
+
+	// In the region where the bimodal model doesn't give good forecasts, we
```
Comment (ziggie1984) [inline routing/probability_bimodal_test.go:310]: Q: could you describe where the region is here where the bimodal is not good, I mean it is very dependant on the constants we use of the capacity and scale or ?  I wonder why it scales linearly I thought it's more uniform now where the bimodal does fall of to sharply ?

File: routing/probability_bimodal.go (hunk 9 above)
Comment (ziggie1984) [reply routing/probability_bimodal.go:522]: so the successAmt needs to be -1 smaller for the reNorm calculation to not be 0 basically ?

**Review by ziggie1984 — COMMENTED** [review]
Very nice documentation of the problem. Had some minor comments, if they are resolved it's good to go.

File: routing/probability_bimodal_test.go (hunk 12 above)
Comment (bitromortac) [reply routing/probability_bimodal_test.go:310]: right, it depends on the parameter combination, if you choose a huge `s`, every bimodal distribution will be a uniform one, since it doesn't matter how large the capacity is and this smears out the bimodal peaks.

If `s` is (very) small compared to `c`, the probability will drop quickly. If we then learn that the balance range is within the success/fail amounts range where the non-normalized probability is ~zero, we would still be able to retain the bimodal distribution within the newly learned range, but now starting at the success/fail amounts, if we had full numerical precision.

Because the numerical values of the exponential drop to zero if the scale is very small, at `amounts >> s`, we get the renormalization error. I think uncovering this error was nice, because I think keeping the bimodal distribution for the learned amounts isn't great and falling back to uniform distribution is better (since we it demonstrated that a bimodal model doesn't hold).

File: routing/probability_bimodal_test.go (hunk 11 above)
Comment (bitromortac) [reply routing/probability_bimodal_test.go]: I think both calculations for `prob` and `reNorm` don't really "fail", but they return float64(0), not some non-zero small amount, because
```
	ecs := math.Exp(-c / s)
	exs := math.Exp(-x / s)
```
both give `float64(0)`, because `c/s` and `x/s` being very large. So in that sense both calculations are almost correct, but due to the division by plain zero we fail.

File: routing/probability_bimodal_test.go [hunk 13]
```diff
@@ -78,7 +81,6 @@ func TestSuccessProbability(t *testing.T) {
 			failAmount:          capacity,
 			amount:              smallAmount,
 			expectedProbability: 0.684,
```
[the remark this answers is not in the document]
Comment (bitromortac) [reply routing/probability_bimodal_test.go:83]: Yeah not too great I didn't calculate the number independently, but it serves more like a way to pin the behavior and to spot changes. The number itself is a sanity check however, since it's larger than the 0.5 in "no info, large amount". This is expected because for an amount that is similar to the scale you expect to find some leftovers, increasing the success probability.

File: routing/probability_bimodal_test.go [hunk 14]
```diff
@@ -311,6 +311,25 @@ func TestIntegral(t *testing.T) {
 	}
 }
 
+// TestBimodalFuzz9085 tests a value combination found by fuzz tests reported in
+// https://github.com/lightningnetwork/lnd/issues/9085. This test found a case
+// where we could not compute a normalization factor because we learned that the
+// balance lies somewhere in the middle of the channel, a surprising result for
+// the bimodal model, which predicts two distinct modes at the edges and
+// therefore has numerical issues in the middle.
+func TestBimodalFuzz9085(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (bitromortac) [reply routing/probability_bimodal_test.go:396]: Nice suggestion, TIL :tada:. I have added the seed. We also don't lose coverage since the other test I introduced tests the same.

File: routing/probability_bimodal.go (hunk 9 above)
Comment (bitromortac) [reply routing/probability_bimodal.go:522]: > so the successAmt needs to be -1 smaller for the reNorm calculation to not be 0 basically ?

right, I think that's another way to say that there would be a logical contradiction to say that you can send the same amount as you fail to send

**Review by ziggie1984 — APPROVED** [review]
LGTM

**Comment by bitromortac** [comment]
I'm done testing, this is ready.

**Comment by bitromortac** [comment]
Updated to address the 0.19 release notes.
