### PR TITLE
lnwallet/chancloser: properly compute initial fee of cop close txn

### LINKED ISSUE #6953: coop close does not work with agreed fees (may be due to Taproot)
### Background

A peer tried to coop close with my node. The negotiation ended with 183 fees but than broadcast transaction failed. The channel got stuck in closing with no txn in mempool. It had to be force closed later.

closing negotiation

```
2022-09-28 07:47:12.286 [INF] HSWC: ChannelLink(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0): exited
2022-09-28 07:47:12.286 [INF] HSWC: ChannelLink(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0): stopping
2022-09-28 07:47:12.287 [INF] HSWC: Removing channel link with ChannelID(c0376aea6113eb4070f0c94bf8162cfd367a552d8f78ec939926f3192269f237)
2022-09-28 07:47:12.300 [INF] PEER: Peer(032e65c456441da55db4c9b3ea863e60a154afc4bac2bdc96dbb25336779257b38): Delivery addr for channel close: bc1pxxxxxxxx -> taproot address
2022-09-28 07:47:12.313 [INF] CHCL: Ideal fee for closure of ChannelPoint(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0) is: 183 sat
2022-09-28 07:47:12.313 [INF] NANN: Announcing channel(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0) disabled [requested]
2022-09-28 07:47:12.336 [INF] CHCL: ChannelPoint(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0): sending shutdown message
2022-09-28 07:47:12.336 [INF] CHCL: ChannelPoint(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0): responding to shutdown
2022-09-28 07:47:12.720 [INF] CHCL: ChannelPoint(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0): computing fee compromise, ideal=183, last_sent=0, remote_offer=183
2022-09-28 07:47:12.723 [INF] CHCL: ChannelPoint(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0): proposing fee of 183 sat to close chan
2022-09-28 07:47:12.723 [INF] CHCL: ChannelPoint(37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0) fee of 0.00000183 BTC accepted, ending negotiation
2022-09-28 07:47:12.731 [INF] CHCL: Broadcasting cooperative close tx: (*wire.MsgTx)(0x4020869180)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=15) {
  (*wire.TxIn)(0x407d6954a0)({
   PreviousOutPoint: (wire.OutPoint) 37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=4 cap=4) {
    ([]uint8) <nil>,
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 1f 02 46 27  89 62 99 6b 68 df 36 c2  |0D. ..F'.b.kh.6.|
```
however failure to broadcast as expected fees was 193 (may be due to taproot)

```
2022-09-28 07:47:12.740 [ERR] LNWL: Notifying unmined tx notification (ad702fc910e166ca03f60c7f04cb69319eb5f22af144bed8b52a5b1c2401940a) while creating notification for blocks
2022-09-28 07:47:12.804 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0x4020869180)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=15) {
  (*wire.TxIn)(0x407d6954a0)({
   PreviousOutPoint: (wire.OutPoint) 37f2692219f3269993ec788f2d557a36fd2c16f84bc9f07040eb1361ea6a37c0:0,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=4 cap=4) {
    ([]uint8) <nil>,
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 1f 02 46 27  89 62 99 6b 68 df 36 c2  |0D. ..F'.b.kh.6.|
--
  })
 },
 LockTime: (uint32) 0
})

2022-09-28 07:47:12.806 [ERR] PEER: Peer(032e65c456441da55db4c9b3ea863e60a154afc4bac2bdc96dbb25336779257b38): unable to process close msg: unmatched backend error: -26: min relay fee not met, 184 < 193
```

### Your environment

* version of `lnd`
```
lncli getinfo
{
    "version": "0.15.1-beta commit=v0.15.1-beta",
    "commit_hash": "fd1a95bf322cdd1c743a1554f8e470fbf9a5e564",
    "identity_pubkey": "03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1",
    "alias": "⚡G-Spot-21_69_420⚡",


```
* which operating system (`uname -a` on *Nix)
`Linux umbrel 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
```
umbrel@umbrel:~/umbrel/bin $ ./bitcoin-cli -getinfo
Chain: main
Blocks: 756058
Headers: 756058
Verification progress: 99.9999%
Difficulty: 31360548173144.85

Network: in 1, out 10, total 11
Version: 230000
Time offset (s): -1
Proxies: 10.21.21.11:9050 (ipv4, ipv6, onion, cjdns)
Min tx relay fee rate (BTC/kvB): 0.00001000
```
* any other relevant environment details

### Steps to reproduce

May be try coop closing channel with ECONOMICAL fees.

### Expected behaviour

If minimum relay fees is 193 then 193 should have been proposed.

### Actual behaviour

Channel did not close and had to be force closed later.

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we modify the way we compute the starting ideal fee for the co-op close transaction. Before this commit, channel.CalcFee was used, which'll compute the fee based on the commitment transaction itself, rathern than the co-op close transaction. As the co-op close transaction is potentailly bigger (two P2TR outputs) than the commitment transaction, this can cause us to under estimate the fee, which can result in the fee rate being too low to propagate.

To remedy this, we now compute a fee estimate from scratch, based on the delivery fees of the two parties.

Fixes #6953

### CODE REVIEW

**Comment by Roasbeef** [comment]
The current solution has a gap in it: one of the co-op close outputs might be trimmed if they are dust. However, we can only compute if an output is dust _after_ we compute our desired starting fee (the initiator's output might be trimmed). Therefore we have a circular dependnacy here: we can only know if an output is dust after we know the fee, but we can only compute the fee _accurately_ if we know if an output is dust. 

At a glance, we can either live with the current solution (will over estimate by a bit if one of the outputs is dust), or just worry about the remote party's output (they don't pay the fee).

**Comment by Roasbeef** [comment]
Marking this as ready for review, worst case we end up over paying slightly when one of the parties doesn't have an output (it was dusted).

**Comment by Roasbeef** [comment]
Seeing this in the itests, seems unrelated, but investigating: 
```
        	Error:      	Received unexpected error:
        	            	expected confirmed balance 16668165, got 16667565
        	Test:       	TestLightningNetworkDaemon/tranche03/92-of-110/btcd/wallet_import_account
```

**Comment by guggero** [comment]
> Seeing this in the itests, seems unrelated, but investigating:
> 
> ```
>         	Error:      	Received unexpected error:
>         	            	expected confirmed balance 16668165, got 16667565
>         	Test:       	TestLightningNetworkDaemon/tranche03/92-of-110/btcd/wallet_import_account
> ```

No, we're actually coop-closing channels in that test. And it looks like the fee needs to be increased by 600 sats to 9650 here: https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_wallet_import_test.go#L564
I guess we should start using appropriate fee estimators in that test instead of hard coding things. But some times hard coded fees can help detect changes in the fee estimators too, which might be useful as well in certain cases...

File: lnwallet/chancloser/chancloser.go [hunk 1]
```diff
@@ -261,14 +306,45 @@ func NewChanCloser(cfg ChanCloseCfg, deliveryScript []byte,
...
+	c.idealFeeSat = c.cfg.FeeEstimator.EstimateFee(
+		0, localTxOut, remoteTxOut, c.idealFeeRate,
+	)
+
+	// When we're the initiator, we'll want to also factor in the highest
+	// fee we want to pay. This'll either be 3x the ideal fee, or the
+	// specified explicit max fee.
+	c.maxFee = c.idealFeeSat * defaultMaxFeeMultiplier
+	if c.cfg.MaxFee > 0 {
+		c.maxFee = c.cfg.FeeEstimator.EstimateFee(
```
Comment (guggero) [inline lnwallet/chancloser/chancloser.go:339]: Won't this basically clamp the max fee rate down to the ideal fee rate? Or where does the `c.cfg.MaxFee` value come in?

**Review by guggero — COMMENTED** [review]
Looks good, but I have a question about the max fee rate.

Needs a rebase too. And the unit test flake seems to be something we haven't reported before, created an issue here: https://github.com/lightningnetwork/lnd/issues/6985

**Comment by Roasbeef** [comment]
>  But some times hard coded fees can help detect changes in the fee estimators too, which might be useful as well in certain cases...

Yep indeed, in this case I think I need to add some additional logic to ignore the possibly dusted output of the remote party (since we know that ahead of time).

File: lnwallet/channel.go [hunk 2]
```diff
@@ -7214,8 +7214,48 @@ func CreateCooperativeCloseTx(fundingTxIn wire.TxIn,
...
+	remoteBalance := chanState.RemoteCommitment.RemoteBalance.ToSatoshis()
+
+	// If this is an anchor channel, and they're the initiator, then we'll
+	// regain the stats allocated to the anchor outputs with the co-op
+	// close transaction.
+	if chanState.ChanType.HasAnchors() && !chanState.IsInitiator {
+		remoteBalance += 2 * anchorSize
+	}
+
+	return remoteBalance <= chanState.RemoteChanCfg.DustLimit
```
Comment (Crypt-iQ) [inline lnwallet/channel.go:7254]: If one side has dust, this can lead to coop close not working. One side should be able to broadcast in these scenarios, but the spec doesn't say what to do if you receive a `fee_satoshis` that makes the transaction non-standard. I only included the relevant scenarios, there are more that do not matter:

Scenario 1 :
| Commit | Our Output | Their Output |
| ------------- | ------------- | ------------- |
|  Local | dust  | not  |
|  Remote  | not  | not  |

Our output is dust on our commitment, so we will not include it as weight and will send a fee that may be too low to the counterparty. The counterparty does not see this output as dust. If the fee is low enough, it may be non-standard for the counterparty. 

Scenario 2:
| Commit | Our Output | Their Output |
| ------------- | ------------- | ------------- |
|  Local | not  | dust  |
|  Remote  | not  | not  |

Their output is dust on our commitment. We will still use the weight of the trimmed output and send them a fee that will be standard for their commitment transaction. This is ok.

Scenario 3: 
| Commit | Our Output | Their Output |
| ------------- | ------------- | ------------- |
|  Local | not  | not  |
|  Remote  | not  | dust  |

Their output is dust on their commitment, so we will not use their weight. We will propose a fee that is non-standard for us, but not for them. This isn't ok because if they accept it, we will not be able to broadcast the closing txn.

Scenario 4:
| Commit | Our Output | Their Output |
| ------------- | ------------- | ------------- |
|  Local | not  | not  |
|  Remote  | dust  | not  |

This is not dust on ours, but is on theirs. So we will include the weight when proposing the fee. This is fine.

It seems like the best way would be to not trim outputs if they are dust. Then you slightly overpay, but never underpay.

File: lnwallet/chancloser/chancloser_test.go [hunk 3]
```diff
@@ -250,8 +275,10 @@ func TestMaxFeeBailOut(t *testing.T) {
 			// instantiate our channel closer.
 			closeCfg := ChanCloseCfg{
 				Channel: &mockChannel{
-					absoluteFee: absoluteFee,
```
Comment (Crypt-iQ) [inline lnwallet/chancloser/chancloser_test.go:253]: there is shadowing in this test with `isInitiator`. it's possible that both tests run with it set to `false`

File: lnwallet/channel.go (hunk 2 above)
Comment (Roasbeef) [reply lnwallet/channel.go:7254]: > It seems like the best way would be to not trim outputs if they are dust. Then you slightly overpay, but never underpay.

You mean trim during fee estimation (here), or when we actually construct the co-op transaction? If we don't trim when making the co-op close transaction, and the other party does, then we'll get an invalid sig (diff sighash) and the fee divergence won't matter. 

I originally didn't do any trimming at all (for fee estimation) but then switched it in an attempt to "optimize" fees a bit more. However, just removing that logic does ensure we'll only ever slightly overpay and don't need to worry about the underway case (lack of mempool propagation).

Comment (Crypt-iQ) [reply lnwallet/channel.go:7254]: I meant not trimming for fee estimation, we'd have to trim the outputs according to spec to not get invalid sig

File: lnwallet/chancloser/chancloser_test.go (hunk 3 above)
Comment (Roasbeef) [reply lnwallet/chancloser/chancloser_test.go:253]: Nice catch, fixed!

File: lnwallet/chancloser/chancloser.go [hunk 4]
```diff
@@ -231,28 +258,52 @@ type ChanCloser struct {
 	locallyInitiated bool
 }
 
+// calcCoopCloseFee computes an "ideal" co-op absolute co-op close fee given
```
Comment (guggero) [inline lnwallet/chancloser/chancloser.go:261]: nit: co-op appears twice.

File: lnwallet/chancloser/chancloser.go [hunk 5]
```diff
@@ -261,14 +312,52 @@ func NewChanCloser(cfg ChanCloseCfg, deliveryScript []byte,
...
+	// fee we want to pay. This'll either be 3x the ideal fee, or the
+	// specified explicit max fee.
+	c.maxFee = c.idealFeeSat * defaultMaxFeeMultiplier
+	if c.cfg.MaxFee > 0 {
+		c.maxFee = c.cfg.FeeEstimator.EstimateFee(
+			0, localTxOut, remoteTxOut, c.cfg.MaxFee,
+		)
+	}
+
+	chancloserLog.Infof("Ideal fee for closure of ChannelPoint(%v) "+
```
Comment (guggero) [inline lnwallet/chancloser/chancloser.go:357]: If we're logging things here, should we also include the max fee? Might be interesting in debugging further co-op close fee negotiations between implementations in the future.

**Review by guggero — APPROVED** [review]
I can't really contribute to the dust calculation discussion as I'm not familiar enough with the nuances there. But the code and test fixes look good to me :tada:
