### PR TITLE
peer: catch write timeouts, retry with backoff

### LINKED ISSUE #2784: Peer connections flapping
### Background

Updated to 0.5.2-99-beta commit=queue/v1.0.1-23-g36cc1da8ea0eec6be4559c673bc07bd0ae9be66a

And started back up.  It can't seem to sync, and keeps disconnecting 10-20 peers every few minutes while 'applying gossip update'

### Your environment

* version of `lnd` : 0.5.2-99-beta commit=queue/v1.0.1-23-g36cc1da8ea0eec6be4559c673bc07bd0ae9be66a

* which operating system (`uname -a` on *Nix) Rasbian
* version of `btcd`, `bitcoind`, or other backend

### Steps to reproduce

Start node

### Expected behaviour
Runs normally

### Actual behaviour
"Applying update" stalls for 10+ seconds... then spam of peer connections failing.  
All of these peers were working find before the upgrade.  There seems to be an endless loop of trying to get the gossip... causes peers to disconnect... when reconnect tries to get gossip... which causes peers to disconnect.
It's like the gossiper is causing peers to time out... which is causing the gossiper to start over when the channel comes up and rinse/repeat.

2019-03-15 23:27:41.020 [INF] DISC: gossipSyncer(03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e): applying new update horizon: start=2019-03-15 22:26:59 +0700 +07, end=2155-04-22 04:55:14 +0700 +07, backlog_size=21999
2019-03-15 23:27:55.228 [INF] DISC: Broadcasting batch of 905 new announcements
2019-03-15 23:27:55.336 [INF] PEER: Disconnecting 213.174.156.76:9735, reason: unable to write message: write tcp 10.34.0.85:43314->213.174.156.76:9735: write: connection reset by peer
2019-03-15 23:27:55.348 [INF] PEER: Disconnecting 46.229.165.138:9735, reason: unable to write message: write tcp 10.34.0.85:55744->46.229.165.138:9735: write: connection reset by peer
2019-03-15 23:27:55.360 [INF] PEER: Disconnecting 46.229.165.133:9735, reason: unable to write message: write tcp 10.34.0.85:39280->46.229.165.133:9735: write: connection reset by peer
2019-03-15 23:27:55.430 [INF] PEER: Disconnecting 46.229.165.154:9735, reason: unable to write message: write tcp 10.34.0.85:49280->46.229.165.154:9735: write: connection reset by peer

### PR DESCRIPTION
**Pull request by cfromknecht**
Fixes #2784.

### CODE REVIEW

File: peer.go [hunk 1]
```diff
@@ -1005,7 +1005,9 @@ func (p *peer) readHandler() {
 out:
 	for atomic.LoadInt32(&p.disconnect) == 0 {
 		nextMsg, err := p.readNextMessage()
-		idleTimer.Stop()
+		if !idleTimer.Stop() {
```
Comment (Roasbeef) [inline peer.go]: 👍

File: peer.go [hunk 2]
```diff
@@ -1427,29 +1429,97 @@ func (p *peer) writeMessage(msg lnwire.Message) error {
...
+				if retryDelay == 0 {
+					retryDelay = minRetryDelay
+				} else {
+					retryDelay *= 2
+					if retryDelay > maxRetryDelay {
+						retryDelay = maxRetryDelay
+					}
+				}
+
+				peerLog.Infof("Write timeout detected for "+
```
Comment (Roasbeef) [inline peer.go]: Should probably demote this to debug logging level. It can be spammy with the current set of network peers.

Comment (cfromknecht) [reply peer.go]: tbh peer debug logs are useless for just viewing, they're only useful when grepping because there's 1000s of logs/s. what if we also demote gossip send/recv logs to trace? stilling keeping important ones like htlc forwards in debug?

Comment (wpaulino) [reply peer.go]: Also log peer public key?

File: peer.go [hunk 3]
```diff
@@ -1429,27 +1431,72 @@ func (p *peer) writeMessage(msg lnwire.Message) error {
...
+			// Initialize a retry delay of zero, which will be
+			// increased if we encounter a write timeout on the
+			// send.
+			var retryDelay time.Duration
+		retryWithDelay:
+			if retryDelay > 0 {
+				select {
+				case <-time.After(retryDelay):
+				case <-p.quit:
+					exitErr = ErrPeerExiting
```
Comment (wpaulino) [inline peer.go]: Shouldn't we be sending this error back to the caller as well if they asked for a synchronized send?

Comment (wpaulino) [reply peer.go]: Ah never mind, I see it in the follow up commit.

File: peer.go [hunk 4]
```diff
@@ -1429,6 +1429,14 @@ func (p *peer) writeMessage(msg lnwire.Message) error {
 //
 // NOTE: This method MUST be run as a goroutine.
 func (p *peer) writeHandler() {
+	// We'll stop the timer after a new messages is received, and also
```
Comment (wpaulino) [inline peer.go]: Nit: s/received/sent/

File: peer.go (hunk 2 above)
Comment (cfromknecht) [reply peer.go]: Fixed and fixed

File: peer.go [hunk 5]
```diff
@@ -1429,27 +1429,80 @@ func (p *peer) writeMessage(msg lnwire.Message) error {
 func (p *peer) writeHandler() {
 	var exitErr error
 
+	const (
+		minRetryDelay = 5 * time.Second
```
Comment (Roasbeef) [inline peer.go]: I think we can remove this in favor of just using `writeMessageTimeout` here since it's added in the next commit and don't need to rack the value in two places in the same file.

Comment (cfromknecht) [reply peer.go]: they're different values really, just coincidence that they were chosen to be the same value. in my mind it's not clear that they should always assume the same?
