### PR TITLE
Auto regenerate TLS cert

### LINKED ISSUE #2758: Auto regeneration of SSL Cert
### Background
When lnd is first started, and no tls.cert is found, the necessary tls.key & tls.cert file are generated.
It is easy to regenerate them: stop lnd. Delete the files. Start lnd.

My Current Cert shows:
```Validity
            Not Before: Apr 24 04:53:56 2018 GMT
            Not After : Jun 19 04:53:56 2019 GMT
        Subject: O = lnd autogenerated cert, CN = RaspiBolt
```

### The Issue
After the SSL cert expires, various remote queries will fail.
### Your environment
* version of `lnd`: 0.5.2

### Steps to reproduce
None.

### Requested Behaviour
1) Would help if the certs were created with a much longer validity period from the start. 
2) And auto-regeneration needs to be implemented

### Question
Do macaroons also have expiry dates? If so ... same issue applies.

### PR DESCRIPTION
**Pull request by orbitalturtle**
Auto-regenerates TLS files once expired.

Fixes #2758

### CODE REVIEW

**Comment by redstorm1** [comment]
I'm suffering from this issue. the auto generated cert has expired and connections now fail. cannot even unlock the  wallet.

Organization: lnd autogenerated cert
Valid From: March 18, 2018
Valid To: May 13, 2019


[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid"

File: lnd_test.go [hunk 1]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
 	}
 }
 
+// testTLSAutoRegeneration creates an expired TLS certificate, testing that a new TLS certificate pair is regenerated when the old pair expires
+func testTLSAutoRegeneration(lnNet *lntest.NetworkHarness, t *harnessTest) {
+	certPath := lnNet.Alice.Cfg.TLSCertPath
```
Comment (cfromknecht) [inline lnd_test.go]: instead of making `cfg` public by naming it `Cfg`, perhaps we can instead define getters for `TLSCertPath` and `TLSKeyPath`? Then we would no longer require the prior commit

File: lnd_test.go [hunk 2]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
...
+		t.Fatalf("Expired certificate was not replaced successfully")
+	}
+
+	if !newCert.NotAfter.After(expiredCert.NotAfter) {
+		t.Fatalf("New certificate expiration is too old")
+	}
+}
+
+// genExpiredCertPair generates an expired key/cert pair to the paths provided to test that expired certificates are being regenerated correctly
+func genExpiredCertPair(t *harnessTest, lnNet *lntest.NetworkHarness, certPath string, keyPath string, expiredTime time.Time) *x509.Certificate {
```
Comment (cfromknecht) [inline lnd_test.go]: a couple things here:
 - `expiredTime` is not used anywhere
 - function signature should be wrapped to 80 chars
 - since `certPath` and `keyPath` are of the same type `string`, they can be defined as `certPath, keyPath string` to save space

File: lnd_test.go [hunk 3]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
...
+	if expiredCert == newCert {
+		t.Fatalf("Expired certificate was not replaced successfully")
+	}
+
+	if !newCert.NotAfter.After(expiredCert.NotAfter) {
+		t.Fatalf("New certificate expiration is too old")
+	}
+}
+
+// genExpiredCertPair generates an expired key/cert pair to the paths provided to test that expired certificates are being regenerated correctly
```
Comment (cfromknecht) [inline lnd_test.go]: godoc should also be wrapped to 80 chars

File: lnd_test.go [hunk 4]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
...
+	if err != nil {
+		t.Fatalf("failed to create certificate: %v", err)
+	}
+
+	expiredCert, err := x509.ParseCertificate(derBytes)
+	if err != nil {
+		t.Fatalf("failed to parse certificate: %v", err)
+	}
+
+	if err != nil {
```
Comment (cfromknecht) [inline lnd_test.go]: stray error check?

File: lnd_test.go [hunk 5]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
...
+		t.Fatalf("failed to encode certificate: %v", err)
+	}
+
+	keybytes, err := x509.MarshalECPrivateKey(priv)
+	if err != nil {
+		t.Fatalf("unable to encode privkey: %v", err)
+	}
+	keyBuf := &bytes.Buffer{}
+	err = pem.Encode(keyBuf, &pem.Block{Type: "EC PRIVATE KEY",
```
Comment (cfromknecht) [inline lnd_test.go]: i'd suggest wrapping like this to follow the style guidelines:
```golang
        err = pem.Encode(
                certBuf, &pem.Block{
                        Type: "EC PRIVATE KEY",
                        Bytes: keyBytes,
               },
       )
```
similarly for encoding the certificate

File: lnd_test.go [hunk 6]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
...
+		Bytes: derBytes})
+	if err != nil {
+		t.Fatalf("failed to encode certificate: %v", err)
+	}
+
+	keybytes, err := x509.MarshalECPrivateKey(priv)
+	if err != nil {
+		t.Fatalf("unable to encode privkey: %v", err)
+	}
+	keyBuf := &bytes.Buffer{}
```
Comment (cfromknecht) [inline lnd_test.go]: nit: `certBuf` and `keyBuf` can be defined as 
```golang
        var certBuf bytes.Buffer
        ...
        var keyBuf bytes.Buffer
```
then each can be passed in using `&keyBuf` and `&certPath` to obtain a reference

File: lnd_test.go [hunk 7]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
...
+		IPAddresses: ipAddresses,
+	}
+
+	// Generate a private key for the certificate.
+	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
+	if err != nil {
+		t.Fatalf("Failed to generate a private key")
+	}
+
+	derBytes, err := x509.CreateCertificate(rand.Reader, &template,
```
Comment (cfromknecht) [inline lnd_test.go]: suggested wrapping:
```golang
	derBytes, err := x509.CreateCertificate(
                rand.Reader, &template, &template, &priv.PublicKey, priv,
       )
```

File: lnd_test.go [hunk 8]
```diff
@@ -13852,6 +13852,124 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
 	}
 }
 
+// testTLSAutoRegeneration creates an expired TLS certificate, testing that a new TLS certificate pair is regenerated when the old pair expires
```
Comment (cfromknecht) [inline lnd_test.go]: nit: godoc should be wrapped to 80 chars, and some of the comments in this file should be made to be complete sentences with proper punctuation :)

**Comment by cfromknecht** [comment]
@redstorm1 in the meantime you can try deleting the `tls.cert` and `tls.key` and restarting lnd

**Comment by cfromknecht** [comment]
@orbitalturtle any progress on this front? should we keep this slated for 0.7?

**Comment by orbitalturtle** [comment]
Hey @cfromknecht - sure that all sounds good, I'll push up my revisions tomorrow. :)

**Comment by cfromknecht** [comment]
@orbitalturtle excellent, thanks!

**Comment by orbitalturtle** [comment]
@cfromknecht Ok finally revised that! Lmk if I can be of any more assistance. Less busy now, so will be more responsive.

File: lntest/node.go [hunk 9]
```diff
@@ -290,6 +290,15 @@ func (hn *HarnessNode) Name() string {
 	return hn.cfg.Name
 }
 
+func (hn *HarnessNode) TLSCertStr() string {
```
Comment (cfromknecht) [inline lntest/node.go]: nit: missing godoc comment here and below :)

File: lnd_test.go [hunk 10]
```diff
@@ -13852,6 +13859,134 @@ func testChannelBackupRestore(net *lntest.NetworkHarness, t *harnessTest) {
...
+		t.Fatalf("couldn't grab new certificate")
+	}
+
+	newCert, err := x509.ParseCertificate(newCertData.Certificate[0])
+	if err != nil {
+		t.Fatalf("couldn't parse new certificate")
+	}
+
+	// Test that the expired certificate was deleted and a new certificate was generated.
+	if expiredCert == newCert {
```
Comment (cfromknecht) [inline lnd_test.go]: is it possible for the two certs to share the same pointer? o/w i think just the last check is sufficient

Comment (orbitalturtle) [reply lnd_test.go]: Good point... just tweaked those two things :)

**Comment by cfromknecht** [comment]
@orbitalturtle this probably needs a rebase, since the main `lnd_test.go` file has been recently moved to `lntest/itest/lnd_test.go`

**Comment by cfromknecht** [comment]
@orbitalturtle be sure to run `make lint`, the current build is failing with `lntest/node.go:1::warning: file is not gofmted with -s (gofmt)`

also recommend not using the github "merge w/ master" button, typically better to rebase over master and force push :)

**Comment by orbitalturtle** [comment]
@cfromknecht Ahhhh my bad, fixed that

File: lnd.go [hunk 11]
```diff
@@ -437,13 +437,39 @@ func getTLSConfig(cfg *config) (*tls.Config, *credentials.TransportCredentials,
...
 	if err != nil {
 		return nil, nil, "", err
 	}
 
+	cert, err := x509.ParseCertificate(certData.Certificate[0])
+	if err != nil {
+		return nil, nil, "", err
+	}
+
+	// If the certificate expired, delete it and the TLS key and generate a new pair
```
Comment (halseth) [inline lnd.go]: nit: missing period end of sentence.

**Comment by orbitalturtle** [comment]
@halseth Sure thing, I can take a stab at that tonight. Just a bit confused about how to approach that if you can elaborate a bit! Like which file do you see the unit test being in?

**Comment by halseth** [comment]
@orbitalturtle You can put the test in `server_test.go`. Just a simple test to make sure the `getTLSConfig` method creates the files as expected (you can perhaps make it take the file path directly instead of the full config to simplify).

**Comment by cfromknecht** [comment]
@halseth should we consider doing that as a follow up given that the PR is complete as is?

**Comment by cfromknecht** [comment]
@orbitalturtle if you can rebase on latest master and leave the itest, we can get this merged in time for the release candidate. If not we may need to push off to 0.8

**Comment by orbitalturtle** [comment]
Sure thing, just rebased as is

Almost done with the new test in server_test.go I think, but I suppose that would require more review. So if this is merged as is, I’ll just add another PR updating the tests?

**Comment by cfromknecht** [comment]
@orbitalturtle awesome thanks! yeah since it doesn't affect the operational behavior, i'm fine with moving it to a unit test in a separate PR
