### PR TITLE
lnwallet: enforce fee floor and dust-reserve adherence

### LINKED ISSUE #1030: lnd can create transaction below min fee rate
### Background

Trying to open channel using all funds available.

### Your environment

* lnd version 0.4.1-beta
* Linux 2.6.32-042stab127.2 #1 SMP
* Bitcoin Core Daemon version v0.16.99.0-2fc9437
* go version go1.10 linux/amd64

### Steps to reproduce
Tried to send all funds, daemon tell me that not enough funds, so I calculate difference and use "proper" amount. Well, that not work.

```
rav3n@node1:~$ lncli walletbalance
{
    "total_balance": "998955",
    "confirmed_balance": "998955",
    "unconfirmed_balance": "0"
}
rav3n@node1:~$ lncli openchannel xxxx 998955
[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.00999176 BTC only have 0.00998955 BTC  available
rav3n@node1:~$ lncli openchannel  xxxx 998734
[lncli] rpc error: code = Unknown desc = -26: mempool min fee not met, 221 < 1081 (code 66)
rav3n@node1:~$ lncli openchannel  xxxx 998955
[lncli] rpc error: code = Unknown desc = not enough witness outputs to create funding transaction, need 0.00998955 BTC only have 0 BTC  available
rav3n@node1:~$ lncli walletbalance
{
    "total_balance": "0",
    "confirmed_balance": "0",
    "unconfirmed_balance": "0"
}
```

### Expected behaviour

Open channel

### Actual behaviour

Channel not open, funds gone?

### PR DESCRIPTION
**Pull request by wpaulino**
In this PR, we fix an issue where sometimes transactions wouldn't provide enough of a fee to be relayed by the backend node. This was caused due to `bitcoind` no longer using the minimum relay fee when estimating fees (see https://github.com/bitcoin/bitcoin/commit/fd29d3df299bd06c0e6bb218863e0c855b3b91af). This would especially cause issues when sweeping outputs after a contract breach, etc. Now, we'll fetch the minimum relay fee from the backend node and ensure it is set as a lower bound if the estimated fee ends up dipping below it.

We also enforce that the channel reserve is above the dust limit. The minimum channel size has also been modified to reflect this change. This allows us to avoid dust outputs from being created in the commitment transactions. This fixes some incompatibility issues between `c-lightning` and `lnd`, due to`lnd` not fully being BOLT-2 compliant.

Fixes #1030.

### CODE REVIEW

File: lnwallet/fee_estimator.go [hunk 1]
```diff
@@ -180,6 +180,21 @@ func (b *BtcdFeeEstimator) fetchEstimatePerVSize(
...
+	// Before proceeding, we'll make sure that this fee rate respects the
+	// minimum relay fee set on the backend node.
+	info, err := b.btcdConn.GetInfo()
+	if err != nil {
+		return 0, err
+	}
+
+	// If the estimated fee rate is lower than the minimum relay fee rate,
+	// then we'll use that.
+	if minFeeRate, err := btcutil.NewAmount(info.RelayFee); err == nil {
```
Comment (Roasbeef) [inline lnwallet/fee_estimator.go]: When would this fail?

File: lnwallet/fee_estimator.go [hunk 2]
```diff
@@ -301,6 +316,21 @@ func (b *BitcoindFeeEstimator) fetchEstimatePerVSize(
...
+	// minimum relay fee set on the backend node.
+	info, err := b.bitcoindConn.GetInfo()
+	if err != nil {
+		return 0, err
+	}
+
+	// If the estimated fee rate is lower than the minimum relay fee rate,
+	// then we'll use that.
+	if minFeeRate, err := btcutil.NewAmount(info.RelayFee); err == nil {
+		if satPerKB < minFeeRate {
```
Comment (Roasbeef) [inline lnwallet/fee_estimator.go]: May be worth adding a debug logging statement here for future diagnostic purposes.

File: lnwallet/reservation.go [hunk 3]
```diff
@@ -296,6 +296,15 @@ func (r *ChannelReservation) CommitConstraints(csvDelay, maxHtlcs uint16,
...
 	}
 
+	// The channel reserve should always be greater or equal to our dust
+	// limit. The reservation request should be denied if otherwise.
+	//
+	// TODO: change this if we allow to manually specify the dust limit.
+	dustLimit := DefaultDustLimit()
+	if chanReserve < dustLimit {
+		return ErrChanReserveTooSmall(chanReserve, dustLimit)
+	}
```
Comment (Roasbeef) [inline lnwallet/reservation.go]: We also need to ensure that the reserve we propose is above the dust limit. If it is, then we should increase the reserve until it's safely above the dust limit.

File: fundingmanager.go [hunk 4]
```diff
@@ -60,10 +60,13 @@ const (
...
 	maxWaitNumBlocksFundingConf = 288
+)
 
+var (
 	// minChanFundingSize is the smallest channel that we'll allow to be
-	// created over the RPC interface.
-	minChanFundingSize = btcutil.Amount(20000)
+	// created over the RPC interface. The dust limit is used in order to
+	// avoid dust outputs.
+	minChanFundingSize = lnwallet.DefaultDustLimit() * 100
```
Comment (Roasbeef) [inline fundingmanager.go]: What's the rational for this change?

Comment (wpaulino) [reply fundingmanager.go]: Removed.

File: lnwallet/reservation.go (hunk 3 above)
Comment (wpaulino) [reply lnwallet/reservation.go]: Fixed.

File: lnwallet/fee_estimator.go (hunk 2 above)
Comment (wpaulino) [reply lnwallet/fee_estimator.go]: Fixed.

File: lnwallet/fee_estimator.go (hunk 1 above)
Comment (wpaulino) [reply lnwallet/fee_estimator.go]: It *shouldn't*, but it doesn't hurt to check the error.

[the remark this answers is not in the document]
Comment (wpaulino) [reply lnwallet/fee_estimator.go]: Fixed.

File: lnwallet/fee_estimator.go [hunk 5]
```diff
@@ -301,6 +316,21 @@ func (b *BitcoindFeeEstimator) fetchEstimatePerVSize(
...
+	// Before proceeding, we'll make sure that this fee rate respects the
+	// minimum relay fee set on the backend node.
+	info, err := b.bitcoindConn.GetInfo()
+	if err != nil {
+		return 0, err
+	}
+
+	// If the estimated fee rate is lower than the minimum relay fee rate,
+	// then we'll use that.
+	if minFeeRate, err := btcutil.NewAmount(info.RelayFee); err == nil {
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply lnwallet/fee_estimator.go]: Fixed.

File: lnwallet/reservation.go [hunk 6]
```diff
@@ -296,6 +296,15 @@ func (r *ChannelReservation) CommitConstraints(csvDelay, maxHtlcs uint16,
 		return ErrCsvDelayTooLarge(csvDelay, maxDelay)
 	}
 
+	// The channel reserve should always be greater or equal to our dust
+	// limit. The reservation request should be denied if otherwise.
+	//
+	// TODO: change this if we allow to manually specify the dust limit.
+	dustLimit := DefaultDustLimit()
```
[the remark this answers is not in the document]
Comment (wpaulino) [reply lnwallet/reservation.go]: I believe this should be good to go now.
