### PR TITLE
config: sync-freelist being ignored

### LINKED ISSUE #5519: [bbolt] sync-freelist=false setting ignored
### Background

[bbolt] sync-freelist=false setting ignored

### Your environment

* lnd version 0.13.0-beta commit=v0.13.0-beta
* Linux 5.10.x, armhf
* bitcoind

### Steps to reproduce

```lnd.conf
[Application Options]
sync-freelist=false

[bolt]
db.bolt.nofreelistsync=true
```

### Expected behaviour

```
[INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
```

### Actual behaviour

```
[INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
```

### PR DESCRIPTION
**Pull request by ErikEk**
Fixes #5519. This pr adds the `isSet` function to `ValidateConfig` which makes it possible to check whether a option has been set by the config file or by a flag. It does this by forwarding both parsing objects to ValidateConfig. isSet is then used to override `cfg.DB.Bolt.NoFreelistSync` in case `sync-freelist` is set.
I believe `isSet` can be used as a safety measure and improve further validation of the config settings.
Also, renamed the variable name of `cfg.DB.Bolt.SyncFreelist` to `cfg.DB.Bolt.NoFreelistSync` which makes it less confusing.

Edit: Apparently, `lnd --db.bolt.nofreelistsync` do not work either. As is, it gives the opposite of what is expected. This pr addresses this. Sad thing is that the `go-flags` package does not support an argument on a bool flag, so it can not be set to `false`, this forces the user to use `sync-freelist` instead.

### CODE REVIEW

**Comment by ErikEk** [comment]
Wait before reviewing this. Found an small error.

File: config.go [hunk 1]
```diff
@@ -603,7 +604,9 @@ func LoadConfig(interceptor signal.Interceptor) (*Config, error) {
 	// Next, load any additional configuration options from the file.
 	var configFileError error
 	cfg := preCfg
-	if err := flags.IniParse(configFilePath, &cfg); err != nil {
+	fileParser := flags.NewParser(&cfg, flags.Default)
+	err := flags.NewIniParser(fileParser).ParseFile(configFilePath)
```
Comment (Roasbeef) [inline config.go:608]: Is this qualitatively different than the existing `IniParse` or just a long form way of executing the same logic?

File: kvdb/config.go [hunk 2]
```diff
@@ -25,7 +25,7 @@ const (
 
 // BoltConfig holds bolt configuration.
 type BoltConfig struct {
-	SyncFreelist bool `long:"nofreelistsync" description:"Whether the databases used within lnd should sync their freelist to disk. This is disabled by default resulting in improved memory performance during operation, but with an increase in startup time."`
+	NoFreelistSync bool `long:"nofreelistsync" description:"Whether the databases used within lnd should sync their freelist to disk. This is disabled by default resulting in improved memory performance during operation, but with an increase in startup time."`
```
Comment (Roasbeef) [inline kvdb/config.go:28]: We don't want to break the existing config options, the prefix may be a bit weird here, but the idea is that _not_ syncing the free list is actually the default. If users want to sync the free list (which means faster start up time, but more performance degradation with larger databases), then they need to set this flag manually.

Comment (Roasbeef) [reply kvdb/config.go:28]: Ah ok, I think the issue here is actually the divergence between the command line flag itself, and how the flag is to be interpreted. So arguably, we want to do the reverse operation here: change the command line flag to match the other one.

File: config.go [hunk 3]
```diff
@@ -686,6 +692,26 @@ func ValidateConfig(cfg Config, usageMessage string,
 		return nil
 	}
 
+	// IsSet returns true if an option has been set in either the config
+	// file or by a flag.
```
Comment (Roasbeef) [inline config.go:696]: Hmm, shouldn't this already be handled by our current behavior, where we read the command line options, then attempt to merge/override them with what we read from the config itself?

File: config.go (hunk 1 above)
Comment (ErikEk) [reply config.go:608]: It is executing the same logic as IniParse

Comment (ErikEk) [reply config.go:608]: It is executing the same logic as `IniParse` and we get a handle to the parse object.
```
func IniParse(filename string, data interface{}) error {
	p := NewParser(data, Default)

	return NewIniParser(p).ParseFile(filename)
}
```

File: config.go (hunk 3 above)
Comment (ErikEk) [reply config.go:696]: It should, but right now we can not distinguish between set and not set boolean parameters. There is no way to find out if 
 `sync-freelist` has been explicitly set, except through the go-flag parsing object. Therefore we don't know if we should override the value of `db.bolt.nofreelistsync` or not. This is the reason the issue occurs (as stated in #5519).

Comment (ErikEk) [reply config.go:696]: I tried my hardest to find a way around it without invoking the parsing objects `IsSet` function but I couldn't.

File: kvdb/config.go (hunk 2 above)
Comment (ErikEk) [reply kvdb/config.go:28]: As is, `lnd --db.bolt.nofreelistsync`, without anything explicitly set in the config file, gives us the opposite of what is expected, namely `Opening bbolt database, sync_freelist=true, auto_compact=false`. The `--db.bolt.nofreelistsync` flag does not serve any purpose if we can not set a boolean flag to false.

_Not_ syncing is set as the default state in Incfg/db.go:
```
func DefaultDB() *DB {
	return &DB{
		Backend:             BoltBackend,
		BatchCommitInterval: DefaultBatchCommitInterval,
		Bolt: &kvdb.BoltConfig{
			NoFreelistSync:    true,
			AutoCompactMinAge: kvdb.DefaultBoltAutoCompactMinAge,
			DBTimeout:         kvdb.DefaultDBTimeout,
		},
	}
}
```

Comment (bhandras) [reply kvdb/config.go:28]: I think it's worth changing the description too while we're here, since it's a bit confusing. "This is disabled by default" meaning `NoFreelistSync=true`. I think we could rephrase to somehting like "This is set to true by default, meaning we don't sync the free-list resulting in imporved...". WDYT?

File: config.go (hunk 3 above)
Comment (bhandras) [reply config.go:696]: I think this is not needed?
If `SyncFreeList` is not set then value is `false` so we get the same as the `Bolt.NoFreeListSync` default so overriding has no effect.
If `SyncFreeList` is set then the value is true we want to override.

File: kvdb/config.go (hunk 2 above)
Comment (ErikEk) [reply kvdb/config.go:28]: @bhandras Good idea. Will add a short description.

File: config.go (hunk 3 above)
Comment (ErikEk) [reply config.go:696]: @bhandras Problem is right here:
https://github.com/lightningnetwork/lnd/blob/4487acc5d9ae3c0074bfc407825b15c6e0da1c24/config.go#L1443
If we have (in lnd.conf)...
```
[Application Options]
sync-freelist=false

[bolt]
db.bolt.nofreelistsync=true
```
...it will ignore `sync-freelist=false` since `sync-freelist` is superordinate `db.bolt.nofreelistsync`. I agree, I would rather do this without the new function `IsSet`, but could not find a way around it with go-flags.

Comment (bhandras) [reply config.go:696]: Indeed, missed the precedence aspect. Thanks for the thorough explanation @ErikEk

**Review by bhandras — APPROVED** [review]
LGTM thanks @ErikEk :1st_place_medal:

**Comment by ErikEk** [comment]
@bhandras Cool. I'll pull from upstream and make sure everything works.

**Comment by ErikEk** [comment]
Rebased.

**Comment by bhandras** [comment]
Ping @Roasbeef

**Review by Roasbeef — APPROVED** [review]
LGTM 🎬

File: config.go [hunk 4]
```diff
@@ -688,6 +693,26 @@ func ValidateConfig(cfg Config, usageMessage string,
...
+		}
+
+		long, ok := fieldname.Tag.Lookup("long")
+		if !ok {
+			fmt.Fprintf(os.Stderr,
+				"field %s does not have a long tag\n", field)
+			return false
+		}
+
+		return fileParser.FindOptionByLongName(long).IsSet() ||
```
Comment (Roasbeef) [inline config.go:712]: This can cause a panic if this `lnd` config is actually embedded in _another_ config. So we need something more generalized here...
