### PR TITLE
rpcserver: add remote balance for pending force close

### LINKED ISSUE #5924: Pending channels output incorrectly reports remote balance as zero
### Background

While investigating a forced closure from Breez, the outputs of the closing on-chain transaction didn't align with what we expected. `lncli pendingchannels` shows `remote_balance: 0` and a single pending htlc, however, the closing transaction has a third output for a remote balance. When looking at the logs for the construction of the closing transaction, it does include a remote balance:
```
 ourBalance: (lnwire.MilliSatoshi) 15781743297 mSAT,
 theirBalance: (lnwire.MilliSatoshi) 163085529 mSAT,
```

### Your environment

LND: v0.13.1-beta
OS: Ubuntu 18.04
Backend: btcd 0.21

### Expected behaviour

Pending channels output should have `remote_balance: 163085` for the closing channel in question.

### PR DESCRIPTION
**Pull request by yyforyongyu**
Add the missing field `RemoteBalance`. Fixes #5924.

Not sure if this balance is accurate?

### CODE REVIEW

File: rpcserver.go [hunk 1]
```diff
@@ -3296,6 +3296,10 @@ func (r *rpcServer) PendingChannels(ctx context.Context,
 			}
 			channel.NumForwardingPackages = int64(len(fwdPkgs))
 
+			channel.RemoteBalance = int64(
+				historical.LocalCommitment.RemoteBalance.ToSatoshis(),
```
Comment (Crypt-iQ) [inline rpcserver.go:3300]: Balance should be correct as this would be an unconfirmed force close, and only the force-closer would have awareness of an unconfirmed force close. We don't persist pending commitment updates as the recipient so `LocalCommitment` is correct here

Comment (guggero) [reply rpcserver.go:3300]: I tested this with both incoming and outgoing HTLCs and the balance seems to be as expected.

**Review by guggero — APPROVED** [review]
tACK, LGTM

File: docs/release-notes/release-notes-0.14.0.md [hunk 2]
```diff
@@ -195,6 +195,11 @@ the custom records (or other details) of the prior payment attempts.
   cleaned up) properly. An example script was added to the [PSBT
   documentation](../psbt.md) to show the simplified process.
 
+* [Add value to the field
+  `remote_balance`](https://github.com/lightningnetwork/lnd/pull/5931) in
+`pending_force_closing_channels` under `pendingchannels` whereas was
```
Comment (Crypt-iQ) [inline docs/release-notes/release-notes-0.14.0.md:200]: nit: `whereas was` -> `whereas before was` ?

**Review by Crypt-iQ — APPROVED** [review]

**Comment by guggero** [comment]
Release notes need to be updated to 0.15.0.

File: docs/release-notes/release-notes-0.14.0.md (hunk 2 above)
Comment (yyforyongyu) [reply docs/release-notes/release-notes-0.14.0.md]: changed

**Comment by yyforyongyu** [comment]
> Release notes need to be updated to 0.15.0.

Done!
