### PR TITLE
lnd: add interrupt handler to handle shutdown requests while syncing chain backend

### LINKED ISSUE #1265: LND RPC API Issues with StopDaemon command
### Background

LND Refuses to respond to StopDaemon() API unless chain is fully synched. It also doesn't reply whether it was successful or not in either case when a stop is requested.

### Your environment

* version of `lnd` Version 0.4.1-beta commit=9f6af3a2c1b036fb224949753054afc684e30644
* which operating system (`uname -a` on *Nix)  Linux Ubuntu 16
* version of `btcd`, `bitcoind`, or other backend btcd Version 0.12.0-beta
* any other relevant environment details Using nodejs grpc-node to access LND API

### Steps to reproduce

1. Start a new LND node accessible remotely its IP and TLS Cert, Macaroon
2. Using Javascript API Setup a lightning connection to the node and issue:

call = lightning.stopDaemon({}, function(err, response) {
     console.log('StopDaemon: ' + JSON.stringify(response));
 })

### Expected behaviour

The callback function should output IDEALLY something like {status: 'stopped} or similar and shut down the node at the earliest in a graceful manner.

### Actual behaviour

If the node is fully synched, it will shutdown as expected but return empty response {}. If the node is not yet synched the callback function will timeout and do nothing.

### PR DESCRIPTION
**Pull request by wpaulino**
Fixes #1265.

### CODE REVIEW

File: signal.go [hunk 1]
```diff
@@ -48,10 +48,8 @@ func mainInterruptHandler() {
 		isShutdown = true
 		ltndLog.Infof("Shutting down...")
 
-		// Run handlers in LIFO order.
-		for i := range interruptCallbacks {
-			idx := len(interruptCallbacks) - 1 - i
-			callback := interruptCallbacks[idx]
+		// Execute the interrupt callbacks in FIFO order.
+		for _, callback := range interruptCallbacks {
```
Comment (Roasbeef) [inline signal.go]: What's the rationale behind the change to FIFO order from LIFO?

Comment (wpaulino) [reply signal.go]: So that we can add and execute interrupt handlers as we go, making it work sort of like a `defer`.

Comment (halseth) [reply signal.go]: FWIW defers are executed in LIFO order.
