### PR TITLE
htlcswitch: add linkStopIndex to cleanly shutdown ChannelLink

### LINKED ISSUE #6593: Channel ERROR: "failing link: unable to resolve fwd pkgs: bucket not found with error: internal error"
## Background

I run a CLN node and have experienced quite a couple of instances where my node force-closed a channel, due to the LND peer sending an `internal error` message. 

I finally had this error with a peer that was able to provide the relevant logs (@ZoltanAB)

## LND environment

* LND: `0.14.2-beta`
* OS: `Linux ipayblue-1 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`
* Using @C-Otto's `rebalance-lnd` script  
(if that's relevant)

## Steps to reproduce

Have a channel between LND / CLN that forwards HTLCs.

## Expected behaviour

LND should not send an error.

## Actual behaviour

LND sends an error.

### LND Logs (peer A)

```
2022-05-29 21:46:19.294 [ERR] HSWC: ChannelLink(297f43e0ac9a7307f334dc2a38eac05a86943f77e912dba679bc9cda52284a55:0): unable to remove fwd pkg for height=421027: bucket not found
2022-05-29 21:46:19.294 [ERR] HSWC: ChannelLink(297f43e0ac9a7307f334dc2a38eac05a86943f77e912dba679bc9cda52284a55:0): failing link: unable to resolve fwd pkgs: bucket not found with error: internal error
```

### CLN logs (peer B)

```
2022-05-29T21:46:12.082Z UNUSUAL 032fe854a231aeb2357523ee6ca263ae04ce53eee8a13767ecbb911b69fefd8ace-channeld-chan#7100: Adding HTLC 2358 too slow: killing connection
2022-05-29T21:46:12.084Z INFO    032fe854a231aeb2357523ee6ca263ae04ce53eee8a13767ecbb911b69fefd8ace-chan#7100: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (9)
2022-05-29T21:46:20.650Z UNUSUAL 032fe854a231aeb2357523ee6ca263ae04ce53eee8a13767ecbb911b69fefd8ace-chan#7100: Peer permanent failure in CHANNELD_NORMAL: channeld: received ERROR error channel 554a2852da9cbc79a6db12e9773f94865ac0ea382adc34f307739aace0437f29: internal error
2022-05-29T21:46:20.651Z INFO    032fe854a231aeb2357523ee6ca263ae04ce53eee8a13767ecbb911b69fefd8ace-chan#7100: State changed from CHANNELD_NORMAL to AWAITING_UNILATERAL
```
## Additional info

The LND node was heavily rebalancing and thus running into memory issues about 7 minutes before the event (no log entries up to `2022-05-29 21:40:02.124`).

index

As you can tell from the graph, they stopped their rebalancing script a couple of hours after the crash.

### PR DESCRIPTION
**Pull request by Crypt-iQ**
With this, extra calls to RemoveLink will wait for the link to
fully stop. This is accomplished by a map that stores a single stop
channel that callers to RemoveLink will listen on. This map is not
consulted when the Switch is shutting down and calls Stop on each
individual link. Though that could be added in the future, it is
not necessary.

Fixes #6593

### CODE REVIEW

**Comment by yyforyongyu** [comment]
I did see several repetitive calls to `RemoveLink` to the same link, and I guess the issue is that other callers need to wait until it's fully stopped? It looks like the error in #6593 came from `l.resolveFwdPkgs()`, and I guess the packages were somehow removed by another link removal? What I don't understand here is, shouldn't `l.resolveFwdPkgs` only happens when the htlc manager is started? If so, it means there's another goroutine trying to stop in at the same time?

**Comment by Crypt-iQ** [comment]
Related to, but not fixed by, https://github.com/lightningnetwork/lnd/pull/6655

- This is because if a goroutine that is not the `peerTerminationWatcher` calls `RemoveLink`, it will call `link.Stop`. 
- If the connection then dies, the `RemoveLink` call in `peerTerminationWatcher` won't call `link.Stop` as the link won't exist in the Switch's index. 
- If a reconnect occurs, two links may be up at the same time.

Granted the existing cases where this can occur are _all_ force close cases, I think it would still be possible to trigger from `rpcserver.go`, even if we are already force closing. I think this is more than anything a defensive measure to ensure new callsites of `RemoveLink` don't cause a force close.

File: htlcswitch/switch.go [hunk 1]
```diff
@@ -2269,12 +2279,48 @@ func (s *Switch) HasActiveLink(chanID lnwire.ChannelID) bool {
 // returns after the link has been completely shutdown.
 func (s *Switch) RemoveLink(chanID lnwire.ChannelID) {
 	s.indexMtx.Lock()
-	link := s.removeLink(chanID)
+	link, _ := s.getLink(chanID)
```
Comment (yyforyongyu) [inline htlcswitch/switch.go:2282]: nit: can check `if link == nil` here to exit early then we won't need to check `link != nil` below.

Comment (yyforyongyu) [reply htlcswitch/switch.go:2282]: also log the error here so it's easier for debugging?

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
Thanks for the detailed explanation! Pending a release note, otherwise good to go.

File: htlcswitch/switch.go (hunk 1 above)
Comment (Crypt-iQ) [reply htlcswitch/switch.go:2282]: `RemoveLink` is called on link startup always so if it's not found an error will always be returned. Maybe a trace log just so users don't have logs that look like errors?

Comment (yyforyongyu) [reply htlcswitch/switch.go:2282]: Yap, as long as we can debug it, anything would be fine.

> RemoveLink is called on link startup always so if it's not found an error will always be returned. 

I do see several other places calling `RemoveLink` tho.

Comment (Crypt-iQ) [reply htlcswitch/switch.go:2282]: Right but most of the time it's going to log an error just because of a reconnect

**Comment by Roasbeef** [comment]
Needs a release notes entry.

**Comment by Crypt-iQ** [comment]
added note

File: htlcswitch/switch.go (hunk 1 above)
Comment (Crypt-iQ) [reply htlcswitch/switch.go]: added trace log

**Review by Roasbeef — APPROVED** [review]
LGTM 💸
