### PR TITLE
Fix the ability to disable p2p listening

### LINKED ISSUE #1488: Cannot disable Listening on the p2p interface
### Background

lnd is listening for p2p connections even if nolisten=1 is put in lnd.conf

### Your environment

* lnd from commit hash 9205720bea931d73e55a886f94d21a759180ff2b
* Linux 4.16.0-2-amd64 #1 SMP Debian 4.16.12-1 (2018-05-27) x86_64 GNU/Linux

### Steps to reproduce

Add nolisten=1 in lnd.conf

### Expected behaviour

lnd doesn't listen to p2p.

### Actual behaviour

lnd listen to *:9735

### Proposed patch to fix the problem
```
diff --git a/config.go b/config.go
index 949f2503..ba5ada38 100644
--- a/config.go
+++ b/config.go
@@ -812,13 +812,6 @@ func loadConfig() (*config, error) {
                return nil, err
        }
 
-       // Remove the listening addresses specified if listening is disabled.
-       if cfg.DisableListen {
-               ltndLog.Infof("Listening on the p2p interface is disabled!")
-               cfg.Listeners = nil
-               cfg.ExternalIPs = nil
-       }
-
        // Add default port to all RPC listener addresses if needed and remove
        // duplicate addresses.
        cfg.RPCListeners, err = lncfg.NormalizeAddresses(
@@ -839,6 +832,13 @@ func loadConfig() (*config, error) {
                return nil, err
        }
 
+       // Remove the listening addresses specified if listening is disabled.
+       if cfg.DisableListen {
+               ltndLog.Infof("Listening on the p2p interface is disabled!")
+               cfg.Listeners = nil
+               cfg.ExternalIPs = nil
+       } else {
+
                // Add default port to all listener addresses if needed and remove
                // duplicate addresses.
                cfg.Listeners, err = lncfg.NormalizeAddresses(
@@ -870,6 +870,7 @@ func loadConfig() (*config, error) {
                                return nil, err
                        }
                }
+       }
 
        // Finally, ensure that we are only listening on localhost if Tor
        // inbound support is enabled.
```

### PR DESCRIPTION
**Pull request by yaslama**
Fix #1488

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -839,36 +832,44 @@ func loadConfig() (*config, error) {
...
-		cfg.net.ResolveTCPAddr,
-	)
-	if err != nil {
-		return nil, err
-	}
+	// Remove the listening addresses specified if listening is disabled.
+	if cfg.DisableListen {
+		ltndLog.Infof("Listening on the p2p interface is disabled!")
+		cfg.Listeners = nil
+		cfg.ExternalIPs = nil
```
Comment (wpaulino) [inline config.go]: nit: no need to nil these out as they haven't been initialized yet.
