### PR TITLE
chanbackup: always combine with on-disk state when swapping, refuse to start w/ invalid files

### LINKED ISSUE #4377: channels.backup can be overwritten as empty if a corrupted channel.db is removed
### Background

I lost a channels.db due to a power event, and nuked it so that I was able to get back into LND and attempt recovery... 

Being stupid, I did not make a copy of the channels.backup before doing so. I then found the channels.backup was overwritten as empty, presumably due to the node now running an empty channels.db

A check to prevent this overwrite may spare others from this same mistake.

(With the kind assistance of @guggero @alexbosworth I was still able to recover funds with `channtools` but this is a non-trivial affair for most)

### Your environment

* 0.9.2
* Ubuntu 20.04 x64
* neutrino (static btcd peer)

### Steps to reproduce

Have channels and verify a good channels.backup exists
Stop node and delete channels.db
Start node and note how channels.backup is updated

### Expected behaviour

Suggest forking channels.backup when a corrupted channels.db is detected on start, or preventing the write of backups if channel count is 0

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we fix a bug that could possibly cause a user's on disk
back up file to be wiped out, if they ever started _another_ lnd node
with different channel state. To remedy this, before we swap out the
channel state with what's on disk, we'll first read out the contents of
the on-disk SCB file and _combine_ that with what we have in memory.

We also add an additional defense against starting up with an
invalid SCB state. With this commit, we'll now fail to start up if we're
unable to update or read the existing SCB state from disk. This will
prevent an lnd node from starting up with an invalid SCB file, an SCB
file it can't decrypt, or an SCB left over from another node.

Fixes #4377

### CODE REVIEW

File: chanbackup/pubsub.go [hunk 1]
```diff
@@ -155,12 +155,44 @@ func (s *SubSwapper) Stop() error {
...
+	// structure will replace what we read from disk.
+	combinedBackup := make(map[wire.OutPoint]Single)
+	if diskMulti != nil {
+		for _, diskChannel := range diskMulti.StaticBackups {
+			chanPoint := diskChannel.FundingOutpoint
+			combinedBackup[chanPoint] = diskChannel
+		}
+	}
+	for _, memChannel := range s.backupState {
+		combinedBackup[memChannel.FundingOutpoint] = memChannel
```
Comment (cfromknecht) [inline chanbackup/pubsub.go:200]: perhaps we should check that if we find a collision we are setting it with the same value? just as a sanity check

Comment (Roasbeef) [reply chanbackup/pubsub.go:200]: What would the behavior be if the value is different? I think it's better to _replace_ the existing, as the new one might have a new field, or be using a new SCB version. If we want to replace, then this logic implements that as is.

Comment (Roasbeef) [reply chanbackup/pubsub.go:200]: It's also possible to just leave the duplicate there too.

Comment (cfromknecht) [reply chanbackup/pubsub.go:200]: that's true, i was thinking even a warning would be nice to see. you're right though the newer one is probably more correct

Comment (Roasbeef) [reply chanbackup/pubsub.go]: log warning added

Comment (Roasbeef) [reply chanbackup/pubsub.go]: Realize now, that the way it is, it'll always print that log statement in the typical case...
