### PR TITLE
Fix Benchmark Test (BenchmarkReadMessage/Funding_Locked) in the lnwire  package

### LINKED ISSUE #7152: BenchmarkReadMessage/FundingLocked failure
I don't think we run the benchmarks in the test framework or this would have been caught. This happens since there is now a scid alias in funding_locked and `createExtraData` is called which populates the extra bytes with random data and can produce a non-canonical tlv stream:
```
--- FAIL: BenchmarkReadMessage/FundingLocked
    message_test.go:244: 
        	Error Trace:	message_test.go:244
        	            				benchmark.go:193
        	            				benchmark.go:233
        	            				asm_amd64.s:1571
        	Error:      	Received unexpected error:
        	            	tlv stream is not canonical
        	Test:       	BenchmarkReadMessage/FundingLocked
        	Messages:   	unable to read msg
```

### PR DESCRIPTION
**Pull request by ziggie1984**
## Change Description

This PR fixes #7152

The benchmark tests failed as described in the issue. Currently the tests produce random data for the `ExtraOpaqueData` field of most of the message types. This can be dangerous as soon as new data is added to a msg type via a tlv record. In this case other tests will fail too, if they use the random data generator for the tlv part.  
The benchmark tests failed now, because the `funding_locked` msg type is the first message in the code base which has an tlv record nested in the overall message type therefore this behaviour was not observed before. Except the `Open_channel` msg but this is a special kind of message because the `upfront_script` has to be always in the tlv_data therefore the tests swap the `ExtraOpaqueData` and encode the relevant `upfront_script` record in the tlv stream

My approach was to narrow down the funding_locked message, discarding the random part of the `ExtraOpaqueData` data and including the new `AliasScid` tlv record, this way the tests will test the encode and decode method of the `funding_locked` msg more throughly. 

Though as soon as another msg type introduces a new nested tlv field the tests will fail again. So maybe we should get rid of the random message generation part for the `ExtraOpaqueData` field for all msg types, or restrict its size to 0, and add additional tests which really try to push the max size of the whole message to its boundaries to actually test the size limits of the payload etc.

Moreover I added the Benchmark tests to the CI which which only runs the benchmark tests, explicitly avoiding all the other unit tests with the `test.run=NONE` option.

## Steps to Test

In the lnwire directory run: `go test -v  -bench=BenchmarkReadMessage`

or more general:

`make unit-bench` which runs all benchmark tests of all packages

### Testing
- [x] Your PR passes all CI checks.
- [x] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by morehouse** [comment]
> The benchmark tests failed now, because the `funding_locked` msg type is the first message in the code base which has an tlv record nested in the overall message type therefore this behaviour was not observed before.

Don't we do something similar for `UpfrontShutdownScript` in `OpenChannel` and `AcceptChannel`?  Why do the benchmarks pass for them?

> Moreover should we also include the Benchmark tests in the overall testrun sothat we capture future failure more reliably?

Yes, I think this is the best way to avoid bit rot.  Then when a new TLV is introduced, the test will fail and alert us that we need to update the benchmarks.

**Comment by ziggie1984** [comment]
Thanks for your review, appreciate it :)

Good point, thats because the upfrontscript needs to be in the tlv-data, thats a hard requirement according to the bolts: 
```
if both nodes advertised the option_upfront_shutdown_script feature:
MUST include upfront_shutdown_script with either a valid shutdown_scriptpubkey as required by shutdown scriptpubkey, or a zero-length shutdown_scriptpubkey (ie. 0x0000).

```
https://github.com/lightning/bolts/blob/master/02-peer-protocol.md

therefore the  compelete random string of `ExtraOpaqueData` gets swapped for the new 0x0000 byte tlv record. Thats why when ready this tlv record everything is fine and no random data is in the Opaque field. For the `funding_locked` there is no mandatory field in the tlv record therefore the random stream is written to the `ExtraOpaqueData`

The swapping happens [here](https://github.com/lightningnetwork/lnd/blob/33a0cbe63440d5ae50cf6fc81855acc5b90b2622/lnwire/extra_bytes.go#L75)

File: Makefile [hunk 1]
```diff
@@ -196,6 +196,10 @@ unit-race:
 	@$(call print, "Running unit race tests.")
 	env CGO_ENABLED=1 GORACE="history_size=7 halt_on_errors=1" $(UNIT_RACE)
 
+unit-bench: $(BTCD_BIN)
+	@$(call print, "Running benchmark tests.")
+	$(UNIT_BENCH)
```
Comment (morehouse) [inline Makefile:201]: I think it would also be good to run `make unit-bench` in CI.

I think the file we need to modify for that is `.github/workflows/main.yml`

Comment (ziggie1984) [reply Makefile:201]: thanks for the reminder, I added it.

File: lnwire/message_test.go [hunk 2]
```diff
@@ -453,7 +454,24 @@ func newMsgFundingLocked(t testing.TB, r io.Reader) *lnwire.FundingLocked {
...
+	// When testing the WriteMessage function we need to populate
+	// the alias to test the encoding of the tlv_stream in the
+	// funding_locked message (now called channel_ready in the bolt spec).
+	_, err = r.Read(c[:8])
+	require.NoError(t, err, "unable to generate channel alias")
+	aliasScid := lnwire.NewShortChanIDFromInt(
+		binary.BigEndian.Uint64(c[:8]),
+	)
+
+	msg.AliasScid = &aliasScid
```
Comment (morehouse) [inline lnwire/message_test.go:467]: I think we could simplify this code a bit.  Something like:

```go
msg := lnwire.FundingLocked{
  ChanID: lnwire.ChannelID(c),
  NextPerCommitmentPoint: pubkey,
  AliasScid: lnwire.NewShortChanIDFromInt(r.Int63()),
  ExtraData: make([]byte, 0),
}
```

The `RecordProducer` stuff below to populate `ExtraData` could stay the same.

**Review by morehouse — APPROVED** [review]
Thanks for the fix!

One suggestion below on simplifying the new code.

File: lnwire/message_test.go (hunk 2 above)
Comment (ziggie1984) [reply lnwire/message_test.go]: Done, Though I had to keep the aliasScid separate because the `AliasScid` is a pointer but the `NewShortChanIDFromInt` returns a value type

**Review by morehouse — APPROVED** [review]
LGTM

File: lnwire/message_test.go [hunk 3]
```diff
@@ -452,8 +453,24 @@ func newMsgFundingLocked(t testing.TB, r io.Reader) *lnwire.FundingLocked {
...
+		ExtraData:              make([]byte, 0),
+	}
+
+	// When testing the funding_locked msg type in the ReadMessage function
+	// we need to populate the ExtraData field here with a valid TLV stream
+	// and cannot use random data.
+	recordProducers := []tlv.RecordProducer{&aliasScid}
+	err = lnwire.EncodeMessageExtraData(&msg.ExtraData, recordProducers...)
+	require.NoError(t, err, "unable to encode channel alias into "+
+		"tlv stream")
```
Comment (morehouse) [inline lnwire/message_test.go:473]: IIUC, we don't need to call `EncodeMessageExtraData` here, since it will also be done inside `Encode`.

File: Makefile (hunk 1 above)
Comment (guggero) [reply Makefile:201]: I don't see what the benefit of running the benchmark tests in CI is? This takes up another slot of our already pretty scarce action runner slots. And as long as we don't manually compare the results with previous runs, this wouldn't show any performance degradation.

File: make/testing_flags.mk [hunk 4]
```diff
@@ -101,12 +101,14 @@ ifeq ($(UNIT_TARGETED), yes)
 UNIT := $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" $(TEST_FLAGS) $(UNITPKG)
 UNIT_DEBUG := $(GOTEST) -v -tags="$(DEV_TAGS) $(LOG_TAGS)" $(TEST_FLAGS) $(UNITPKG)
 UNIT_RACE := $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS) lowscrypt" $(TEST_FLAGS) -race $(UNITPKG)
+UNIT_BENCH :=  $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" -test.bench=. -test.run=XXX $(UNITPKG)
```
Comment (guggero) [inline make/testing_flags.mk:104]: What's the `test.run=XXX` here? Is the intent to only run very short benchmark tests to make sure they work in general but finish quickly?

File: lnwire/message_test.go (hunk 3 above)
Comment (ziggie1984) [reply lnwire/message_test.go:473]: Thanks you are right, its now part because we write it before 👍

Comment (ziggie1984) [reply lnwire/message_test.go:473]: Though I think also including it in the extradata is the correct way of doing it, because normally when calling `newMsgFundingLocked` I would expect a correctly filled message of this type without having to know that I need to `encode` it first so the TLV data is included in the right place ?

Comment (ziggie1984) [reply lnwire/message_test.go:473]: but I am good with both ways

**Comment by ziggie1984** [comment]
Hmm I understand your points regarding adding it to the CI tests, so the initial issue of this PR was, because it was not on anyone's radar that the Benchmark tests were failing. But adding them to the CI is also maybe not the right approach. Maybe only execute them for specific releases so that we make sure they do not fail and pass at least ?

**Comment by guggero** [comment]
> Hmm I understand your points regarding adding it to the CI tests, so the initial issue of this PR was, because it was not on anyone's radar that the Benchmark tests were failing. But adding them to the CI is also maybe not the right approach. Maybe only execute them for specific releases so that we make sure they do not fail and pass at least ?

Perhaps we can just run the benchmark tests on `master` branch? So they would be run after each merged PR but at least not for each update of each PR, which already saves some cycles but would still be noticed when they break (when we actually have fully green CI which is hopefully very soon).
What I mean is: `if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}` in the `unit-bench` job.

**Comment by ziggie1984** [comment]
I like your idea so I changed the CI workflow for Benchmark tests.

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
Thanks for the PR! I like that we are considering putting benchmarks into our CI, but the current approach may not add many benefits.

At the moment, for a particular PR, we run benchmarks twice, one before and one after, to assess the performance improvement brought by the PR. Running benchmarks alone, however, doesn't provide us with any useful info.

I thought about adding a new workflow [here](https://github.com/lightningnetwork/lnd/actions) to run benchmarks periodically. Or run them per release to see the performance change between releases, or run them for particular PRs, with the help of a github bot to report the results.

So I'd say we should remove it from CI because it doesn't give us useful info. And similar bugs can get fixed whenever the benchmarks are run. Not ideal, until we can properly figure out how to run them automatically.

**Comment by ziggie1984** [comment]
> At the moment, for a particular PR, we run benchmarks twice, one before and one after, to assess the performance improvement brought by the PR. Running benchmarks alone, however, doesn't provide us with any useful info.

What do you mean by "run twice" here, are the benchmarks already included in some kind of test-script or "should" a developer run the benchmark tests twice?

Anyways I agree maybe just put them out of the CI for now as you said and look in a separate PR how we can integrate the benchmarks properly.

File: make/testing_flags.mk [hunk 5]
```diff
@@ -101,12 +101,16 @@ ifeq ($(UNIT_TARGETED), yes)
 UNIT := $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" $(TEST_FLAGS) $(UNITPKG)
 UNIT_DEBUG := $(GOTEST) -v -tags="$(DEV_TAGS) $(LOG_TAGS)" $(TEST_FLAGS) $(UNITPKG)
 UNIT_RACE := $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS) lowscrypt" $(TEST_FLAGS) -race $(UNITPKG)
+# NONE is a special value which selects no other tests but only executes the benchmark tests here.
+UNIT_BENCH :=  $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" -test.bench=. -test.run=NONE $(UNITPKG)
```
Comment (yyforyongyu) [inline make/testing_flags.mk:105]:
```suggestion
UNIT_BENCH := $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" -test.bench=. -test.run=NONE $(UNITPKG)
```

File: make/testing_flags.mk [hunk 6]
```diff
@@ -101,12 +101,16 @@ ifeq ($(UNIT_TARGETED), yes)
...
 endif
 
 ifeq ($(UNIT_TARGETED), no)
 UNIT := $(GOLIST) | $(XARGS) env $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" $(TEST_FLAGS)
 UNIT_DEBUG := $(GOLIST) | $(XARGS) env $(GOTEST) -v -tags="$(DEV_TAGS) $(LOG_TAGS)" $(TEST_FLAGS)
 UNIT_RACE := $(UNIT) -race
+# NONE is a special value which selects no other tests but only executes the benchmark tests here.
+UNIT_BENCH :=  $(GOLIST) | $(XARGS) env $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" -test.bench=. -test.run=NONE
```
Comment (yyforyongyu) [inline make/testing_flags.mk:113]:
```suggestion
UNIT_BENCH := $(GOLIST) | $(XARGS) env $(GOTEST) -tags="$(DEV_TAGS) $(LOG_TAGS)" -test.bench=. -test.run=NONE
```

**Review by yyforyongyu — APPROVED** [review]
LGTM👍

> What do you mean by "run twice" here, are the benchmarks already included in some kind of test-script or "should" a developer run the benchmark tests twice?

I meant the developer should run it twice to understand the performance change. An example would be #4884, which used the bench results to guide the code change.

**Comment by yyforyongyu** [comment]
Maybe this can be rebased and merged🧐

File: Makefile (hunk 1 above)
Comment (ziggie1984) [reply Makefile:201]: Removed it from the CI

**Comment by ziggie1984** [comment]
> Maybe this can be rebased and merged🧐

Rebased and ready to be merged I think.

**Review by guggero — APPROVED** [review]
LGTM :tada:
