### PR TITLE
htlcswitch: properly apply the fee constraints of the *outgoing* link when accepting HTLC's

### LINKED ISSUE #922: FeeInsufficient error paying invoice to routed (not directly connected) c-lightning node
I'm trying to pay an invoice generated by the Blockstream c-lightning store (buying stickers!)
My lnd node is configured, funded, well connected and has 3 channels open to other well funded and connected nodes. 

If I use queryroutes, I see 5-6 routes with 0-2 SAT total fees and plenty of capacity. The invoice is for 81009 SAT payment. When I try to "payinvoice", I get this error:

"payment_error": "FeeInsufficient(fee=81009343 mSAT...

That fee is actually the entire invoice amount, not the fee. The payment amount is 81009, and lnd seems to add 0.343 SAT to the end of it.

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we fix an existing bug in the forwarding logic in the link. Before this commit, we would actually apply the fee policies of the _incoming_ link when accepting new HTLC's. This was incorrect as we should actually be applying the fees of the _outgoing_ link, as we'll be using that link's payment bandwidth to support the HTLC. This bug cause a ton of issues when routing on mainnet, as we would reject an HTLC for violating the policy of the incoming link, then send the policy of the incoming link. The router would them prune the _outgoing_ link, as that is the proper policy that _should_ have been applied. This process would then at times repeat tens of times, until we gave up with a timeout error. 

To fix this issue, we've added a series of new methods to the link and switch to allow the incoming link to validate an HTLC against the fee policy of the outgoing link. Along the way, we've simplified some logic (`linkControl`) within the link and the switch. 

Finally, we also fix an existing deadlock bug in the gossiper that would manifest due to attempting to create a `bolt` write transaction, while we already have an active read transaction open. 

Fixes #922.

### CODE REVIEW

File: discovery/gossiper.go [hunk 1]
```diff
@@ -1161,20 +1167,37 @@ func (d *AuthenticatedGossiper) processChanPolicyUpdate(
...
+	}
+
+	// With the set of edges we need to update retrieved, we'll now re-sign
+	// them, and insert them into the database.
+	var chanUpdates []networkMsg
+	for _, edgeInfo := range edgesToUpdate {
+		// Now that we've collected all the channels we need to update,
+		// we'll Re-sign and update the backing ChannelGraphSource, and
 		// retrieve our ChannelUpdate to broadcast.
-		_, chanUpdate, err := d.updateChannel(info, edge)
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply discovery/gossiper.go]: I think it worked in the old set of integration tests as that was the _only_ thing going on, so it was able to upgrade a read transaction to a write transaction. When there are other transactions in flight, the deadlock occurs as it tries to grab the write lock while it has the readlock, but is unable to do so as a result of the other active transactions.

**Comment by Roasbeef** [comment]
> 2) the switch before it decides to hand the packet to the outgoing link.

Modifying the PR to handle the fee and min HTLC related policies at the link instead.

File: htlcswitch/switch.go [hunk 2]
```diff
@@ -892,14 +874,37 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
...
 		var destination ChannelLink
 		for _, link := range interfaceLinks {
 			// We'll skip any links that aren't yet eligible for
 			// forwarding.
-			if !link.EligibleToForward() {
+			switch {
+			case !link.EligibleToForward():
+				fallthrough
+
+			case link.ShortChanID().ToUint64() == 0:
```
Comment (cfromknecht) [inline htlcswitch/switch.go]: Should add comment to explain that this should never happen, but protects against invalid circuit map states, i.e. that we should never be forwarding an HTLC _out_ to the source hop.
Maybe replace with `case link.ShortChanID() == sourceHop:` to match comment?

File: htlcswitch/switch.go [hunk 3]
```diff
@@ -892,14 +874,37 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
...
 		// Try to find destination channel link with appropriate
 		// bandwidth.
 		var destination ChannelLink
 		for _, link := range interfaceLinks {
 			// We'll skip any links that aren't yet eligible for
 			// forwarding.
-			if !link.EligibleToForward() {
+			switch {
+			case !link.EligibleToForward():
+				fallthrough
```
Comment (cfromknecht) [inline htlcswitch/switch.go]: should this be `continue`?

File: htlcswitch/switch.go [hunk 4]
```diff
@@ -892,14 +874,37 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
 			return s.failAddPacket(packet, failure, addErr)
 		}
 		interfaceLinks, _ := s.getLinks(targetLink.Peer().PubKey())
+		s.indexMtx.Unlock()
+
+		// We'll keep track of any HTLC failures during the link
+		// selection process. This way we can return the error for
+		// precise link that the sender selected, while optimistically
+		// trying all inks to utilize out available bandwidth.
```
Comment (cfromknecht) [inline htlcswitch/switch.go]: inks -> links, out -> our

File: htlcswitch/switch.go (hunk 3 above)
Comment (Roasbeef) [reply htlcswitch/switch.go]: Same as below, it'll go into the continue.

File: htlcswitch/switch.go [hunk 5]
```diff
@@ -1891,28 +1781,8 @@ type updateForwardingIndexCmd struct {
 func (s *Switch) UpdateShortChanID(chanID lnwire.ChannelID,
 	shortChanID lnwire.ShortChannelID) error {
 
-	command := &updateForwardingIndexCmd{
```
Comment (halseth) [inline htlcswitch/switch.go]: `updateForwardingIndexCmd` can now be removed.

File: htlcswitch/switch.go [hunk 6]
```diff
@@ -1891,28 +1781,8 @@ type updateForwardingIndexCmd struct {
...
-	}
-
-	return errors.New("unable to update short chan id htlc switch was stopped")
-}
-
-// updateShortChanID updates the short chan ID of an existing link.
-func (s *Switch) updateShortChanID(chanID lnwire.ChannelID,
-	shortChanID lnwire.ShortChannelID) error {
+	s.indexMtx.Lock()
+	defer s.indexMtx.Unlock()
```
Comment (halseth) [inline htlcswitch/switch.go]: same, feels safer to release lock before calling into the link.

File: htlcswitch/switch.go [hunk 7]
```diff
@@ -1946,36 +1816,16 @@ type getLinksCmd struct {
 // GetLinksByInterface fetches all the links connected to a particular node
 // identified by the serialized compressed form of its public key.
 func (s *Switch) GetLinksByInterface(hop [33]byte) ([]ChannelLink, error) {
-	command := &getLinksCmd{
```
Comment (halseth) [inline htlcswitch/switch.go]: All these `cmd` structs can be deleted.

File: lnd_test.go [hunk 8]
```diff
@@ -7919,7 +7946,7 @@ var testsCases = []*testCase{
 		name: "update channel policy",
 		test: testUpdateChannelPolicy,
 	},
-	{
+	/*{
```
Comment (halseth) [inline lnd_test.go]: not intentional?

File: discovery/gossiper.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (halseth) [reply discovery/gossiper.go]: Makes sense! Didn't know `boltdb` could upgrade transactions like that!

File: htlcswitch/switch.go [hunk 9]
```diff
@@ -892,14 +874,39 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
...
 
 		// Try to find destination channel link with appropriate
 		// bandwidth.
 		var destination ChannelLink
 		for _, link := range interfaceLinks {
 			// We'll skip any links that aren't yet eligible for
 			// forwarding.
-			if !link.EligibleToForward() {
+			switch {
+			case !link.EligibleToForward():
```
Comment (halseth) [inline htlcswitch/switch.go]: I would prefer a plain `if` statement instead of `switch` here.

Comment (Roasbeef) [reply htlcswitch/switch.go]: Stylistically I generally prefer switch statements to if/else.

File: lnd_test.go (hunk 8 above)
Comment (Roasbeef) [reply lnd_test.go]: Heh yeh, had isolated that test in order to debug it.

File: htlcswitch/switch.go (hunk 7 above)
Comment (Roasbeef) [reply htlcswitch/switch.go]: Fixed.

File: htlcswitch/switch.go (hunk 6 above)
Comment (Roasbeef) [reply htlcswitch/switch.go]: Fixed.

File: htlcswitch/switch.go [hunk 10]
```diff
@@ -880,8 +857,11 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
 			return s.handleLocalDispatch(packet)
 		}
 
+		s.indexMtx.Lock()
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply htlcswitch/switch.go]: Fixed.

File: htlcswitch/switch.go [hunk 11]
```diff
@@ -715,14 +688,18 @@ func (s *Switch) handleLocalDispatch(pkt *htlcPacket) error {
 	// appropriate channel link and send the payment over this link.
 	case *lnwire.UpdateAddHTLC:
 		// Try to find links by node destination.
+		s.indexMtx.Lock()
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply htlcswitch/switch.go]: Fixed.

File: htlcswitch/switch.go [hunk 12]
```diff
@@ -386,63 +389,33 @@ func (s *Switch) SendHTLC(nextNode [33]byte, htlc *lnwire.UpdateAddHTLC,
...
+		// If we can't locate a link by its converted channel ID, then
+		// we'll return an error back to the caller.
 		link, ok := s.linkIndex[cid]
 		if !ok {
 			return fmt.Errorf("unable to find ChannelPoint(%v) to "+
 				"update link policy", targetLink)
 		}
 
-		link.UpdateForwardingPolicy(c.newPolicy)
+		link.UpdateForwardingPolicy(newPolicy)
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply htlcswitch/switch.go]: At this point, there's no circular call back to the switch. Updating anyway as it'll result in us holding the index mutex for less time.

File: htlcswitch/switch.go [hunk 13]
```diff
@@ -923,6 +949,29 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
...
+		case destination == nil && len(linkErrs) != 0:
+			// At this point, some or all of the links rejected the
+			// HTLC so we couldn't forward it. So we'll try to look
+			// up the error that can from the source.
+			linkErr, ok := linkErrs[packet.outgoingChanID]
+			if !ok {
+				// If we can't find the error of the source,
+				// then we'll return an unknown next peer,
+				// though this should never happen.
+				linkErr = &lnwire.FailUnknownNextPeer{}
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply htlcswitch/switch.go]: Done.

File: htlcswitch/switch.go [hunk 14]
```diff
@@ -923,6 +949,29 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
...
 			return s.failAddPacket(packet, failure, addErr)
+
+		// If we had a forwarding failure due to the HTLC not
+		// satisfying the current policy, then we'll send back an
+		// error, but ensure we send back the error sourced at the
+		// *target* link.
+		case destination == nil && len(linkErrs) != 0:
+			// At this point, some or all of the links rejected the
+			// HTLC so we couldn't forward it. So we'll try to look
+			// up the error that can from the source.
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply htlcswitch/switch.go]: Fixed.

**Comment by Roasbeef** [comment]
PTAL.
