### PR TITLE
routing: local balance check before path finding

### LINKED ISSUE #1680: Incorrect payment error message
### Background

I have an open channel with "local_balance": "0", and I try to pay an Invoice to the node I'm direcly connected by the channel

### Your environment

* lnd version 0.4.2-beta commit=f0f5e11b826e020c11c37343bcbaf9725627378b
* Linux wepa 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* btcd version 0.12.0-beta

### Steps to reproduce
```
$ lncli payinvoice lnsb10u....cqde6eyq
```
### Expected behaviour

I'm a sender with not enough funds for this invoice, I should get an error message that indicates to me that I don't have enough funds

```
{
	"payment_error": "not enough funds",
	"payment_preimage": "",
	"payment_route": null
}
```

### Actual behaviour

I receive this error message

```
{
	"payment_error": "unable to find a path to destination",
	"payment_preimage": "",
	"payment_route": null
}
```

### PR DESCRIPTION
**Pull request by joostjager**
Fixes #1680

### CODE REVIEW

File: routing/pathfind.go [hunk 1]
```diff
@@ -8,6 +8,7 @@ import (
 
 	"github.com/btcsuite/btcd/btcec"
 	"github.com/coreos/bbolt"
+	"github.com/go-errors/errors"
```
Comment (cfromknecht) [inline routing/pathfind.go]: wrong import

File: routing/payment_session.go [hunk 2]
```diff
@@ -1,8 +1,7 @@
 package routing
 
 import (
-	"fmt"
-
+	"github.com/go-errors/errors"
```
Comment (cfromknecht) [inline routing/payment_session.go]: import

File: routing/payment_lifecycle.go [hunk 3]
```diff
@@ -186,6 +186,19 @@ func (p *paymentLifecycle) resumePayment() ([32]byte, *route.Route, error) {
 
 }
 
+// errorToPaymentFailure takes a path finding error and converts it into a
+// payment-level failure.
+func errorToPaymentFailure(err error) channeldb.FailureReason {
+	switch err {
+	case errNoTlvPayload, errNoPathFound, errMaxHopsExceeded,
```
Comment (cfromknecht) [inline routing/payment_lifecycle.go]: `errNoTlvPayload` isn't necessarily a path issue, but maybe that should be addressed in a different pr?

Comment (joostjager) [reply routing/payment_lifecycle.go]: Yes, I left that part unchanged. Just made it more obvious that that is the current logic. But agree that we should differentiate more. Another failure that we could expose is not having any info on the node at all (not in graph, not in the hints).

File: channeldb/payments.go [hunk 4]
```diff
@@ -105,6 +105,10 @@ const (
 	// or the final cltv delta or amount is incorrect.
 	FailureReasonPaymentDetails FailureReason = 3
 
+	// FailureReasonInsufficientBalance indicates that we didn't have enough
+	// balance to complete the payment.
+	FailureReasonInsufficientBalance = 4
```
Comment (joostjager) [inline channeldb/payments.go]: Do we need a db version bump? I am not completely convinced that we should add this protection against downgrading on nodes running master.

**Comment by joostjager** [comment]
Todo: add test

File: channeldb/payments.go (hunk 4 above)
Comment (joostjager) [reply channeldb/payments.go]: Discussed with @Roasbeef offline. Up to now we generally don't give this level of support to users on master.

Comment (guggero) [inline channeldb/payments.go]: Should add explicit `FailureReason` type.

File: routing/pathfind.go [hunk 5]
```diff
@@ -305,6 +309,50 @@ type PathFindingConfig struct {
...
+		if outgoingChan != nil && chanID != *outgoingChan {
+			return nil
+		}
+
+		bandwidth, ok := g.bandwidthHints[chanID]
+
+		// If the bandwidth is not available for whatever reason, don't
+		// fail the pathfinding early.
+		if !ok {
+			max = lnwire.MaxMilliSatoshi
```
Comment (guggero) [inline routing/pathfind.go]: If there is no bandwidth hint for just one of the channels, this causes the `getMaxOutgoingAmt` to always return `lnwire.MaxMilliSatoshi` because no other channel can overwrite the max with a "real" value. Should this maybe just be ignored? I guess it depends on what the causes for the hints being empty could be and if it's likely that the hint for just one channel is missing or that the hints for all of them are missing.

File: routing/pathfind_test.go [hunk 6]
```diff
@@ -2299,16 +2299,13 @@ func newPathFindingTestContext(t *testing.T, testChannels []*testChannel,
 		t:                 t,
 		testGraphInstance: testGraphInstance,
 		source:            route.Vertex(sourceNode.PubKeyBytes),
+		pathFindingConfig: *testPathFindingConfig,
```
[the remark this answers is not in the document]
Comment (joostjager) [reply routing/pathfind_test.go]: Yes, it somehow disappeared. I didn't find out what I did wrong, maybe a rebase mistake

File: routing/errors.go [hunk 7]
```diff
@@ -11,16 +11,6 @@ const (
 	// does not exist in the graph.
```
[the remark this answers is not in the document]
Comment (joostjager) [reply routing/errors.go]: Removed

File: channeldb/payments.go (hunk 4 above)
Comment (joostjager) [reply channeldb/payments.go]: Added

File: routing/pathfind.go (hunk 5 above)
Comment (joostjager) [reply routing/pathfind.go]: There may be a race condition. A channel becoming available right after the bandwidth hints are queried. It is an edge case and it felt safer to do it like this. Not to fail the routing while there is a channel available that just doesn't have a bandwidth hint.

File: routing/errors.go [hunk 8]
```diff
@@ -7,18 +7,10 @@ import "github.com/go-errors/errors"
...
-
-	// ErrMaxHopsExceeded is returned when a candidate path is found, but
-	// the length of that path exceeds HopLimit.
-	ErrMaxHopsExceeded
-
 	// ErrTargetNotInNetwork is returned when the target of a path-finding
 	// or payment attempt isn't known to be within the current version of
 	// the channel graph.
-	ErrTargetNotInNetwork
+	ErrTargetNotInNetwork errorCode = iota
```
Comment (cfromknecht) [inline routing/errors.go]: preexisting, but `errorCode` should be exported if `ErrTargetNotInNetwork` is also exported for godocs

Comment (cfromknecht) [reply routing/errors.go]: could be made into a trivial follow up

**Comment by cfromknecht** [comment]
two of the async benchmarks failed, perhaps an indicator that this introduces a performance regression?

**Comment by joostjager** [comment]
> two of the async benchmarks failed, perhaps an indicator that this introduces a performance regression?

Manually checked the timing of a queryroutes call on testnet, didn't see a difference with master. Restarted itests

**Comment by joostjager** [comment]
Yes, does seem to be failing consistently. Will check it out.

**Comment by joostjager** [comment]
Turned out to be a deadlock with getting the source node. Fixed now
