### PR TITLE
channeldb: don't reject duplicate waiting proofs

### LINKED ISSUE #1315: Crashing after failing to "find node"
### Background

Node was offline for a few weeks because bitcoind crashed, and i had no time to resolve it.  I resolved the bitcoind issue, but when i got to bringing lnd back up it wouldnt stay.  after the initial catching up to the chain etc I get this
```
2018-06-02 15:13:06.804 [INF] LNWL: Started listening for blocks via ZMQ on tcp://127.0.0.1:28332
2018-06-02 15:13:06.808 [ERR] DISC: unable to rebroadcast stale channels: error while retrieving outgoing channels: unable to find node
2018-06-02 15:13:06.808 [INF] DISC: Received new local channel announcement: (*lnwire.AnnounceSignatures)(0xc4206560b0)({
 ChannelID: (lnwire.ChannelID) (len=32 cap=32) 819e596633d706091d84970d162b5469ebd97233ee22deba48cab591decff8ff,
 ShortChannelID: (lnwire.ShortChannelID) 515042:1815:0,
 NodeSignature: (lnwire.Sig) (len=64 cap=64) {
  00000000  b6 8f 73 75 e4 c8 f7 3a  f6 fd 2b b7 e6 ba 10 d0  |..su...:..+.....|
  00000010  21 30 fe 26 33 f2 e8 ea  d8 02 ed 13 00 13 14 f6  |!0.&3...........|
  00000020  2e 30 c6 ee 12 3e 46 27  34 c8 38 2a 5d cc e2 5f  |.0...>F'4.8*].._|
  00000030  f3 7f c7 55 9e 85 5c 4d  47 70 f9 3e d0 b6 05 a7  |...U..\MGp.>....|
 },
 BitcoinSignature: (lnwire.Sig) (len=64 cap=64) {
  00000000  08 0c c5 6d b2 14 63 1d  fe de e3 43 39 28 5c ec  |...m..c....C9(\.|
  00000010  93 27 0e aa 01 e4 92 a0  f4 e9 c2 5c 3e db 18 34  |.'.........\>..4|
  00000020  0c 15 49 78 e1 fc ea 24  08 2b 08 23 3b 77 ba fb  |..Ix...$.+.#;w..|
  00000030  ce 7f b5 26 d0 55 e9 e8  0e f1 5f 86 bd d7 52 08  |...&.U...._...R.|
 }
})

2018-06-02 15:13:06.812 [ERR] DISC: unable to store the proof for short_chan_id=566294667911954432: waiting proof with such key already exist
2018-06-02 15:13:06.812 [ERR] FNDG: Unable to send channel proof: unable to store the proof for short_chan_id=566294667911954432: waiting proof with such key already exist
2018-06-02 15:13:06.812 [ERR] FNDG: error sending channel announcement: channel announcement failed: unable to store the proof for short_chan_id=566294667911954432: waiting proof with such key already exist
2018-06-02 15:13:06.908 [ERR] SRVR: unable to start server: unexpected EOF

unexpected EOF
```

### Your environment

lnd version 0.4.1-beta commit=6fa93a78c18180a3bc77116b749b3c5e279d5a33(tried going forward and it caused bigger issues so i rolled back)
ubuntu 17.10 
bitcoind on .16

### Steps to reproduce
not sure how to reproduce, i keep getting that error above.  I clear out all data and macaroons and the node starts up fine(with no channels obv).  I recover from seed and also fine but again no channels.  I have funds tied up in channels.  not particularly concerned with the funds directly, more of how this could negatively impact others.

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we modify the waiting proof slightly to acept dupliacte
waiting proofs, rather than reject them. Otherwise, it's possible that
the remote node first sends us their half of the waiting proof (before
we do), we write that to disk, then upon restart, we'll try to add it
again, but be rejected by the system.

Fixes #1315.

### CODE REVIEW

File: channeldb/waitingproof.go [hunk 1]
```diff
@@ -56,10 +56,6 @@ func NewWaitingProofStore(db *DB) (*WaitingProofStore, error) {
 
 // Add adds new waiting proof in the storage.
 func (s *WaitingProofStore) Add(proof *WaitingProof) error {
-	if _, ok := s.cache[proof.Key()]; ok {
-		return ErrWaitingProofAlreadyExist
```
Comment (halseth) [inline channeldb/waitingproof.go]: nit: definition of `ErrWaitingProofAlreadyExist` can now be removed
