### PR TITLE
sweep: account for all script types in craftSweepTx

### LINKED ISSUE #6747: LND Creating onchain transaction that will never broadcast (too low fee)
### Background

We've had several customers report LND is creating transactions that never show up in the mempool. They are trying to just send bitcoin onchain (no channel openings/closings) and the transactions never show up in the mempool. We initially thought that it was just neutrino failing to broadcast but I couldn't get them to broadcast manually against a bitcoin node because of too low of fees. After investigating we found that the fee rates being set at less than 1 sat/vbyte. This is preventing the transactions from working and LND is stuck with a Limbo balance.

I think most of the people I've talked to were using the send_all method in Send Coins.
https://api.lightning.community/#sendcoins

It seems like this is only happening with a Neutrino backend. I haven't heard any reports of this on a bitcoin backed node. 

_Example_

*Output from `listchaintxns`

```
        {
            "tx_hash": "f1bd7ed69fcd89ce3f1ad985db321dfe9d71a5933ec6973cfedc3781bffb07c0",
            "amount": "-1098823",
            "num_confirmations": 0,
            "block_hash": "",
            "block_height": 0,
            "time_stamp": "1657288860",
            "total_fees": "318",
            "dest_addresses": [
                "bc1q7k09jufpjwmln8tpnqkh5fre4kngvgk6xtttfh7ppv4edgrc8rxqw0gm46"
            ],
            "output_details": [
                {
                    "output_type": "SCRIPT_TYPE_WITNESS_V0_SCRIPT_HASH",
                    "address": "bc1q7k09jufpjwmln8tpnqkh5fre4kngvgk6xtttfh7ppv4edgrc8rxqw0gm46",
                    "pk_script": "0020f59e59712193b7f99d61982d7a2479ada68622da32d6b4dfc10b2b96a07838cc",
                    "output_index": "0",
                    "amount": "1098505",
                    "is_our_address": false
                }
            ],
            "raw_tx_hex": "02000000000104105f21b83e812986c01cbdfc080aca298dcafaaa02ccbbb2a4d53734cb680a33000000000000000000baa2157b8f608d5a15c85022be60507e604cd8c4e07587aa46af376509d8ac0100000000000000000062d1bc55fd0551ac68543cdd3790569ff11a41a5dc8ffef5a3a31dc38d629613000000000000000000daca91d45c7ca9f49d140bf9de1e420c901924cffb2cd2c147c1eeab11b3ba580000000000000000000109c3100000000000220020f59e59712193b7f99d61982d7a2479ada68622da32d6b4dfc10b2b96a07838cc02483045022100a16bb8b2c55e155e888cc2eaaf6adaa702e8b418f29c2f483106858bc84651f50220549d1d5c1303bd411b21ec14919f454c00f54e7b146126b094fa37964aae78d1012102c62066c28e75c11e16ec6ee829ab22ce9885d7df888b0e59a9aa10da2699630c02473044022030df4b89dcc79f236c377e82f39fbd5825a87c83ca01f63025c002d73bb3a64e0220548d85ad5ccd062cfcf4a2cd0a673030ce7f7582d6d3888cdd75edc677f02025012103aa31e5fd95be848be0b43021b4437cd35b612a092720907978e4fc43a679d85d02473044022079319cd5add22c77352fed20eaed99a722aa3f159831447285dc646c262911de0220314dc29ff24def696251998bffd2da490aaa08b7e3b7e83a9554746d69e50f8b012102cf4164ab4b84f0900742b3ff51fc1c34ae9b8ad6fa8b30ea5724d72840674b0d02483045022100df50d4cdf8db42d6cb709c5ed981357b150ad148790493e67eaa00fbcaac0c930220356d619a85d67b11bfba5a09041df69bad13a96a36be199635af5c67efd002d201210377de2bbf02661b43b2417b90f216cea7edf85fe2401b679fba8fa9183c60691ed65a0b00",
            "label": "external"
        },
```

When decoding that `raw_tx`

```
{
    "addresses": [
        "bc1qt0t88kp2npndl5hgynl0n0rtqknztaz0p67ngh",
        "bc1qumq7nw9ssugmlp33uwdaakzqpw6jx8pu324u9m",
        "bc1qk73cnxk745amrtjny50zmlzxqrmwpws2ldg60y",
        "bc1qdfqyh2fzrhz2gqf3ygrz3j5g8vrha4ds6dvzkc",
        "bc1q7k09jufpjwmln8tpnqkh5fre4kngvgk6xtttfh7ppv4edgrc8rxqw0gm46"
    ],
    "block_height": -1,
    "block_index": -1,
    "confirmations": 0,
    "double_spend": false,
    "fees": 318,
    "hash": "f1bd7ed69fcd89ce3f1ad985db321dfe9d71a5933ec6973cfedc3781bffb07c0",
    "inputs": [
        {
            "addresses": [
                "bc1qt0t88kp2npndl5hgynl0n0rtqknztaz0p67ngh"
            ],
            "age": 744137,
            "output_index": 0,
            "output_value": 18864,
            "prev_hash": "330a68cb3437d5a4b2bbcc02aafaca8d29ca0a08fcbd1cc08629813eb8215f10",
            "script_type": "pay-to-witness-pubkey-hash",
            "sequence": 0,
            "witness": [
                "3045022100a16bb8b2c55e155e888cc2eaaf6adaa702e8b418f29c2f483106858bc84651f50220549d1d5c1303bd411b21ec14919f454c00f54e7b146126b094fa37964aae78d101",
                "02c62066c28e75c11e16ec6ee829ab22ce9885d7df888b0e59a9aa10da2699630c"
            ]
        },
        {
            "addresses": [
                "bc1qumq7nw9ssugmlp33uwdaakzqpw6jx8pu324u9m"
            ],
            "age": 744136,
            "output_index": 0,
            "output_value": 979636,
            "prev_hash": "01acd8096537af46aa8775e0c4d84c607e5060be2250c8155a8d608f7b15a2ba",
            "script_type": "pay-to-witness-pubkey-hash",
            "sequence": 0,
            "witness": [
                "3044022030df4b89dcc79f236c377e82f39fbd5825a87c83ca01f63025c002d73bb3a64e0220548d85ad5ccd062cfcf4a2cd0a673030ce7f7582d6d3888cdd75edc677f0202501",
                "03aa31e5fd95be848be0b43021b4437cd35b612a092720907978e4fc43a679d85d"
            ]
        },
        {
            "addresses": [
                "bc1qk73cnxk745amrtjny50zmlzxqrmwpws2ldg60y"
            ],
            "age": 744017,
            "output_index": 0,
            "output_value": 477,
            "prev_hash": "1396628dc31da3a3f5fe8fdca5411af19f569037dd3c5468ac5105fd55bcd162",
            "script_type": "pay-to-witness-pubkey-hash",
            "sequence": 0,
            "witness": [
                "3044022079319cd5add22c77352fed20eaed99a722aa3f159831447285dc646c262911de0220314dc29ff24def696251998bffd2da490aaa08b7e3b7e83a9554746d69e50f8b01",
                "02cf4164ab4b84f0900742b3ff51fc1c34ae9b8ad6fa8b30ea5724d72840674b0d"
            ]
        },
        {
            "addresses": [
                "bc1qdfqyh2fzrhz2gqf3ygrz3j5g8vrha4ds6dvzkc"
            ],
            "age": 742822,
            "output_index": 0,
            "output_value": 99846,
            "prev_hash": "58bab311abeec147c1d22cfbcf2419900c421edef90b149df4a97c5cd491cada",
            "script_type": "pay-to-witness-pubkey-hash",
            "sequence": 0,
            "witness": [
                "3045022100df50d4cdf8db42d6cb709c5ed981357b150ad148790493e67eaa00fbcaac0c930220356d619a85d67b11bfba5a09041df69bad13a96a36be199635af5c67efd002d201",
                "0377de2bbf02661b43b2417b90f216cea7edf85fe2401b679fba8fa9183c60691e"
            ]
        }
    ],
    "lock_time": 744150,
    "opt_in_rbf": true,
    "outputs": [
        {
            "addresses": [
                "bc1q7k09jufpjwmln8tpnqkh5fre4kngvgk6xtttfh7ppv4edgrc8rxqw0gm46"
            ],
            "script": "0020f59e59712193b7f99d61982d7a2479ada68622da32d6b4dfc10b2b96a07838cc",
            "script_type": "pay-to-witness-script-hash",
            "value": 1098505
        }
    ],
    "preference": "low",
    "received": "2022-07-18T10:04:18.021737922Z",
    "relayed_by": "3.84.254.53",
    "size": 649,
    "total": 1098505,
    "ver": 2,
    "vin_sz": 4,
    "vout_sz": 1,
    "vsize": 325
}
```

### Your environment

* LND 0.15.0 (and I believe some were on 0.14.3)
* Linux
* btcd backend

### Steps to reproduce

I can't find an exact reproduction case besides running a neutrino node and trying to Send All. 

### Expected behaviour

The transaction is created with a 1 sat/vbyte or greater fee limit and the transaction broadcasts ok.

### Actual behaviour

Transaction is created with less than 1 sat/vbyte and never gets sent.

### PR DESCRIPTION
**Pull request by Crypt-iQ**
With this change, transactions created via craftSweepTx will be
standard. Previously, p2wsh scripts passed in via SendCoins would
be weighted as p2wpkh scripts. With a feerate of 1 sat/vbyte,
transactions returned would be non-standard. Luckily, the critical
sweeper subsystem only used p2wpkh scripts so this only affected
callers from the rpcserver.

Fixes #6747

### CODE REVIEW

File: sweep/weight_estimator.go [hunk 1]
```diff
@@ -83,6 +83,12 @@ func (w *weightEstimator) addP2TROutput() {
 	w.estimator.AddP2TROutput()
 }
 
+// addP2WSHOutput updates the weight estimate to account for an additional
+// segwit v0 P2WSH output.
+func (w *weightEstimator) addP2WSHOutput() {
+	w.estimator.AddP2WSHOutput()
```
Comment (Roasbeef) [inline sweep/weight_estimator.go:89]: Can we easily extend the `weight_estimator_test.go` tests to account for this new case? 

Alternatively, can we reproduce that sweep all txn coming in at less than 1 sat/byte scenario in the itest? One way would possibly to use a neutrino node and feed it a low estimate to trigger the case.

Comment (Crypt-iQ) [reply sweep/weight_estimator.go:89]: Yes, but if we broadcast it in a test, btcd won't pick it up on regtest due to some config params

File: sweep/txgenerator.go [hunk 2]
```diff
@@ -339,6 +339,8 @@ func getWeightEstimate(inputs []input.Input, outputs []*wire.TxOut,
 	// trimmed.
```
Comment (ellemouton) [inline sweep/txgenerator.go:339]: would be cool if we could have some way to make sure that this if-else chain (which could be a switch) checks the same cases that are checked in [CraftSweepAllTx](https://github.com/lightningnetwork/lnd/blob/fec8fd9c63dc672dc3ea1b9be47bd1d6c4a0a54d/sweep/walletsweep.go#L246) so that this bug is prevented in future if any new script types are added.

**Review by ellemouton — COMMENTED** [review]
lgtm 🔥  left a non-pressing comment. Also agree that a test would be cool if it's not too tricky to add.

File: sweep/txgenerator.go (hunk 2 above)
Comment (Crypt-iQ) [reply sweep/txgenerator.go:339]: I think logic unification would be good, but not sure how to do it here. The cases here need to check more cases than the `CraftSweepAllTx` cases (since those are only wallet UTXOs -- fewer possible script types). Also the `CraftSweepAllTx` case needs to check for taproot pubkey rather than the general v1 witness script

**Review by Crypt-iQ — COMMENTED** [review]
I think the issue still exists if a user passes in a `P2PKH` or `P2SH` script when sweeping all -- need to account for that as well

**Comment by Crypt-iQ** [comment]
> I think the issue still exists if a user passes in a `P2PKH` or `P2SH` script when sweeping all -- need to account for that as well

P2SH scripts luckily won't cause an issue due to lnd overestimating the DER sig weight, but P2PKH outputs can result in a non-std tx. I've added an integration test that will fail with a non-std transaction error if this patch isn't applied. The `getWeightEstimate` function will also fail if `outputPkScript` is an unknown script which requires new scripts to update this function.

File: sweep/txgenerator.go [hunk 3]
```diff
@@ -337,10 +342,25 @@ func getWeightEstimate(inputs []input.Input, outputs []*wire.TxOut,
 	// change output to the weight estimate regardless, since the estimated
 	// fee will just be subtracted from this already dust output, and
 	// trimmed.
-	if txscript.IsPayToTaproot(outputPkScript) {
+	switch {
```
Comment (Roasbeef) [inline sweep/txgenerator.go:345]: 👍

File: lntest/itest/lnd_nonstd_sweep_test.go [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+	txid, err := waitForTxInMempool(net.Miner.Client, minerMempoolTimeout)
+	require.NoError(t.t, err)
+
+	tx, err := net.Miner.Client.GetRawTransaction(txid)
+	require.NoError(t.t, err)
+
+	msgTx := tx.MsgTx()
+
+	// Fetch the weight of the transaction.
+	weight := msgTx.SerializeSizeStripped()*3 + msgTx.SerializeSize()
```
Comment (Roasbeef) [inline lntest/itest/lnd_nonstd_sweep_test.go:117]: Can use https://pkg.go.dev/github.com/btcsuite/btcd@v0.23.1/blockchain#GetTransactionWeight here

Or you can use `GetRawTransactionVerbose`: https://pkg.go.dev/github.com/btcsuite/btcd@v0.23.1/btcjson#TxRawResult -- this one already has both weight and vsize computed for you.

File: lntest/itest/lnd_nonstd_sweep_test.go [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+
+	// Calculate the virtual size, rounding up.
+	vbytes := (weight + 3) / 4
+
+	// Fetch the fee of the transaction.
+	inputVal := 0
```
Comment (Roasbeef) [inline lntest/itest/lnd_nonstd_sweep_test.go:123]: Initialize w/ a single `var` statement?

File: lntest/itest/lnd_nonstd_sweep_test.go [hunk 6]
```diff
@@ -0,0 +1,146 @@
...
+	}
+
+	for _, outp := range msgTx.TxOut {
+		outputVal += int(outp.Value)
+	}
+
+	fee = inputVal - outputVal
+
+	// Require fee >= vbytes.
+	require.True(t.t, fee >= vbytes)
```
Comment (Roasbeef) [inline lntest/itest/lnd_nonstd_sweep_test.go:145]: Not sure I follow this comparison.... 

Isn't it that we want to:
  * Ensure the transactions are getting into the mempool 
  * have a fee rate of > 1 sat/byte?

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: lntest/itest/lnd_nonstd_sweep_test.go (hunk 6 above)
Comment (Crypt-iQ) [reply lntest/itest/lnd_nonstd_sweep_test.go:145]: - `SendCoins` ensures txn's get into mempool, otherwise it errors
- 1sat/vbyte is fine, but less than that isn't. In a local test I did, btcd did accept < 1sat/vbyte so the test just asserts that this isn't happening in the itest

**Comment by Roasbeef** [comment]
PR is looking good now, though I see this race on CI:
```
WARNING: DATA RACE
Read at 0x00c0000296af by goroutine 28:
  github.com/lightningnetwork/lnd/sweep.createSweeperTestContext.func2()
      /home/runner/work/lnd/lnd/sweep/sweeper_test.go:142 +0x6c
  github.com/lightningnetwork/lnd/sweep.(*UtxoSweeper).sweep()
      /home/runner/work/lnd/lnd/sweep/sweeper.go:1296 +0xd8
  github.com/lightningnetwork/lnd/sweep.(*UtxoSweeper).sweepCluster.func1()
      /home/runner/work/lnd/lnd/sweep/sweeper.go:8[68](https://github.com/lightningnetwork/lnd/runs/7679184688?check_suite_focus=true#step:6:69) +0x1ab
  github.com/lightningnetwork/lnd/sweep.(*mockBackend).WithCoinSelectLock()
      /home/runner/work/lnd/lnd/sweep/backend_mock_test.go:108 +0x2e
  github.com/lightningnetwork/lnd/sweep.(*UtxoSweeper).sweepCluster()
      /home/runner/work/lnd/lnd/sweep/sweeper.go:858 +0x15c
  github.com/lightningnetwork/lnd/sweep.(*UtxoSweeper).collector()
      /home/runner/work/lnd/lnd/sweep/sweeper.go:797 +0x1b05
  github.com/lightningnetwork/lnd/sweep.(*UtxoSweeper).Start.func1()
      /home/runner/work/lnd/lnd/sweep/sweeper.go:385 +0xfe

Previous write at 0x00c0000296af by goroutine 29:
  github.com/lightningnetwork/lnd/sweep.createSweeperTestContext.func2()
      /home/runner/work/lnd/lnd/sweep/sweeper_test.go:142 +0x7d
  github.com/lightningnetwork/lnd/sweep.TestDifferentFeePreferences()
      /home/runner/work/lnd/lnd/sweep/sweeper_test.go:1101 +0x4c8
  testing.tRunner()
      /opt/hostedtoolcache/go/1.18.2/x64/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.18.2/x64/src/testing/testing.go:14[86](https://github.com/lightningnetwork/lnd/runs/7679184688?check_suite_focus=true#step:6:87) +0x47
```

File: sweep/sweeper_test.go [hunk 7]
```diff
@@ -137,7 +137,8 @@ func createSweeperTestContext(t *testing.T) *sweeperTestContext {
 		Signer: &mock.DummySigner{},
 		GenSweepScript: func() ([]byte, error) {
 			script := make([]byte, input.P2WPKHSize)
-			script[0] = outputScriptCount
+			script[0] = 0
+			script[1] = 20
```
Comment (Roasbeef) [inline sweep/sweeper_test.go:141]: What's this variable below even used for? Looks to be triggering some race race condition (see my comment below in the main body)

Comment (Roasbeef) [reply sweep/sweeper_test.go:141]: Ah I think it's that two goroutine are calling this function and they both increment this variable? It seems we can either remove it, make it an atomic, or slap a defer mutex here.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: sweep/sweeper_test.go (hunk 7 above)
Comment (Crypt-iQ) [reply sweep/sweeper_test.go:140]: removed
