### PR TITLE
chanfunding: extend PSBT witness input check

### LINKED ISSUE #5287: Exception when opening channel from external wallet: error verifying PSBT: not all inputs are segwit spends
### Background

Potentially irrelevant background: I reinstalled lnd from the AUR lnd-git while trying to get the debug build working to use abandonchannel (#5265). I ended up having to hack the PKGBUILD to get it to build.
I also attempted to open a channel from a non-segwit wallet to see if it would work, that's when I saw the error for the first time.

After transferring the funds to the Electrum wallet I previously used for channel opens I still got the error. After restarting LND the error continues to persist.

### Your environment

* version of `lnd`
Updated via AUR package lnd-git on May 10, 2021
```
$ lnd --version
lnd version 0.12.99-beta commit=
```

* which operating system (`uname -a` on *Nix)
`Linux 4.19.187-1-MANJARO`
* version of `btcd`, `bitcoind`, or other backend
```
$ bitcoind --version
Bitcoin Core version v0.21.0.0-g95ea54ba089610019a74c1176a2c7c0dba144b1c
```
* any other relevant environment details
Electrum 4.1.2

### Reproduction
I'm not sure if I gave myself a weird version of LND or if the PSBT is broken. I can't go back to 12.1, and I can't open channels from LND's wallet either right now (#5265).

The base64 PSBT I created
```
cHNidP8BAH0CAAAAAQeYr3I5MHphjxj1bPQunMDzEkgelnMO5GCMmbDlxG5SAQAAAAD9////AsDGLQAAAAAAIgAg9fp4qrX9SaD2yimizd/iXaQGzn6L/Zw76gOwOptuxI5EBj0AAAAAABYAFONc59ZQL6q0zFUM0/q42rcQJfZiZmwKAAABAN4CAAAAAAEBMPm+cpKW6ErZunBiEagbxsTbqIjPk4IafKXcF22KaU8BAAAAAP3///8CzFoVAAAAAAAWABRWhifnP2EA8DBR7o/XvZ973jM/K8DPagAAAAAAFgAUkaSLivW2msAxEEs6XzgyHpWQ+rkCRzBEAiB+6VK+lMY+rlZ9QoHZRFWWFP5Pi/zMP/RparPY75mmlgIgLtLvsw/ZMaTow22vB46ERCVlk2WMIXZZQI4P5lgtENYBIQP2/DeH61A5AdKmyPH/3E4x+yAwEfe0v3TK+YTGVbpGIhRsCgAiBgImroxoUMLdqZNKgnBilRbwCjAWGhV+aPU0UHS5Xyj5AxC5tKcTAAAAgAAAAAAJAAAAAAAiAgLAoq4c393kznYb0SZHM2G0HSgOEHI8cDsLvhyRTfpKFxC5tKcTAAAAgAEAAAAIAAAAAA==
```

### Expected behaviour
The channel open proceeds to the next step

### Actual behaviour

An error is produced
```sh
$ lncli openchannel 026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2 3000000 --psbt
...
[lncli] verifying PSBT by lnd failed: rpc error: code = Unknown desc = error verifying PSBT: not all inputs are segwit spends
```

### PR DESCRIPTION
**Pull request by guggero**
Fixes #5287.

The PSBT spec is a bit vague when it comes to the WitnessUtxo field of
an input as it's not strictly required for witness inputs. Therefore
Electrum for example does not include the field.
We need to make the SegWit input check a bit more elaborate by looking
at the output script of the UTXO and also the redeem script in case it's
a nested SegWit spend.

### CODE REVIEW

**Comment by Crypt-iQ** [comment]
Thanks for doing this, will review

File: lnwallet/chanfunding/psbt_assembler.go [hunk 1]
```diff
@@ -543,3 +544,55 @@ func verifyInputsSigned(ins []*wire.TxIn) error {
...
+// need to look at it and make sure it's either a witness pkScript or a nested
+// SegWit spend.
+func verifyAllInputsSegWit(txIns []*wire.TxIn, ins []psbt.PInput) error {
+	for idx, in := range ins {
+		switch {
+		// The optimal case is that the witness UTXO is set explicitly.
+		case in.WitnessUtxo != nil:
+
+		// Only the non witness UTXO field is set, we need to inspect it
+		// to make sure it's not P2PKH or bare P2WH.
```
Comment (wpaulino) [inline lnwallet/chanfunding/psbt_assembler.go:560]: Nit: P2WSH*

**Review by wpaulino — APPROVED** [review]

**Review by Crypt-iQ — COMMENTED** [review]
Nit and a question

File: lnwallet/chanfunding/psbt_assembler.go (hunk 1 above)
Comment (guggero) [reply lnwallet/chanfunding/psbt_assembler.go]: Ah yes, it's supposed to say P2WH. Fixed.

File: lnwallet/chanfunding/psbt_assembler.go [hunk 2]
```diff
@@ -543,3 +544,55 @@ func verifyInputsSigned(ins []*wire.TxIn) error {
...
+		case in.NonWitnessUtxo != nil:
+			utxo := in.NonWitnessUtxo
+			txIn := txIns[idx]
+			txOut := utxo.TxOut[txIn.PreviousOutPoint.Index]
+
+			if !isSegWitScript(txOut.PkScript) &&
+				!isSegWitScript(in.RedeemScript) {
```
[the remark this answers is not in the document]
Comment (guggero) [reply lnwallet/chanfunding/psbt_assembler.go:567]: Everything but the witnesses needs to be set during the `Verify` step. This ensures that the channel output(s) are present as required but also serves as a check to make sure the signing wallets have all the information they need. So a PSBT must basically be fully ready to be signed.

[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply lnwallet/chanfunding/psbt_assembler.go:567]: Got it, good to know

File: lnwallet/chanfunding/psbt_assembler.go [hunk 3]
```diff
@@ -543,3 +544,55 @@ func verifyInputsSigned(ins []*wire.TxIn) error {
...
+		switch {
+		// The optimal case is that the witness UTXO is set explicitly.
+		case in.WitnessUtxo != nil:
+
+		// Only the non witness UTXO field is set, we need to inspect it
+		// to make sure it's not P2PKH or bare P2SH.
+		case in.NonWitnessUtxo != nil:
+			utxo := in.NonWitnessUtxo
+			txIn := txIns[idx]
+			txOut := utxo.TxOut[txIn.PreviousOutPoint.Index]
```
Comment (Crypt-iQ) [inline lnwallet/chanfunding/psbt_assembler.go:564]: This won't panic which is good, but `psbt.SumUtxoInputValues` has the same indexing and will panic on malformed PSBTs.  Could be fixed in a followup and version-bumped?  It's irrelevant to this PR but I found it while reviewing this one.  I could also patch it instead.

**Review by Crypt-iQ — APPROVED** [review]
Change set looks good! 🦖 

Just a comment about the indexing.

File: lnwallet/chanfunding/psbt_assembler.go (hunk 3 above)
Comment (Roasbeef) [reply lnwallet/chanfunding/psbt_assembler.go:564]: A follow up for the next rc sounds good IMO.
