### PR TITLE
chainfee: return floor fee rate when a given target is not found

### LINKED ISSUE #6056: unable to start server: unable to query fee estimator: web API does not include a fee estimation for block target of 1
### Background

One of my client node was unable to start because it requested a fee estimation for block target 1. See the [incident report](https://severinalexb.github.io/personal-blog/2021/12/05/Indicent-Report.html) for more background information.

Logs:
```
[ERR] CNCT: ChannelArbitrator(*****): unable to advance state: unable to query fee estimator
: web API does not include a fee estimation for block target of 1
unable to start server: unable to query fee estimator: web API does not include a fee estimation for block target of 1
```

### Your environment

* version of `lnd`: 0.13.4
* which operating system (`uname -a` on *Nix): Linux Nuc9 5.11.0-41-generic~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend : Neutrino

### Steps to reproduce

The node was down for some time and needed to react quickly to channel force-closes. See related incident report.

### Expected behaviour

Only request estimations for block >= 2 or provide estimations for block 1.

### Actual behaviour

Node didnt start anymore.

### PR DESCRIPTION
**Pull request by yyforyongyu**
Instead of returning an error, we now log the error and return a default fee rate when a given conf target cannot be found from the web fee estimator.

Fixes #6056.

### CODE REVIEW

File: lnwallet/chainfee/estimator.go [hunk 1]
```diff
@@ -593,8 +600,12 @@ func (w *WebAPIEstimator) EstimateFeePerKW(numBlocks uint32) (SatPerKWeight, err
 	}
 
 	feePerKb, err := w.getCachedFee(numBlocks)
+
+	// If the estimator doesn't have enough data, or returns an error, then
+	// to return a proper value, then we'll return the default fall back
```
Comment (bhandras) [inline lnwallet/chainfee/estimator.go:605]: nit: I believe the "then to return a proper value" part is just leftover from a previous comment version.

**Review by bhandras — APPROVED** [review]
LGTM :ice_cream:

File: lnwallet/chainfee/estimator.go (hunk 1 above)
Comment (yyforyongyu) [reply lnwallet/chainfee/estimator.go:605]: Fixed!

File: lnwallet/chainfee/estimator.go [hunk 2]
```diff
@@ -593,8 +600,12 @@ func (w *WebAPIEstimator) EstimateFeePerKW(numBlocks uint32) (SatPerKWeight, err
 	}
 
 	feePerKb, err := w.getCachedFee(numBlocks)
+
+	// If the estimator returns an error, a zero value fee rate will be
+	// returned. We will log the error and return the fall back fee rate
+	// instead.
 	if err != nil {
-		return 0, err
+		log.Errorf("unable to query estimator: %v", err)
```
Comment (guggero) [inline lnwallet/chainfee/estimator.go:608]: I'm not sure returning the default value (fee floor!) is a good idea here. The problem is that the code that generates the https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json file is never going to include a fee estimate for a 1 block confirmation target (it's using https://github.com/lightningnetwork/lnd/blob/master/lnrpc/walletrpc/walletkit_server.go#L636).
And since a 1 block target is the "most urgent fee" setting, returning the _minimum_ fee is probably the worst thing we can do. Should we try to return the fee value for the _next_ higher confirmation target? In this case for 2 blocks? And only if there is no value at all return the fee floor?

Comment (Roasbeef) [reply lnwallet/chainfee/estimator.go:608]: IIRC bitcoind (on the RPC interface) never allows a 1 conf query, and instead only allows 2 blocks as a minimum

Comment (guggero) [reply lnwallet/chainfee/estimator.go:608]: IMO we should just add a special case for conf target of 1 here. And simply try to return the value for conf target of 2.

Comment (yyforyongyu) [reply lnwallet/chainfee/estimator.go:608]: > IIRC bitcoind (on the RPC interface) never allows a 1 conf query, and instead only allows 2 blocks as a minimum

Tested with `bitcoin-cli estimatesmartfee 1` and did pass. However I think it falled back to conf target of 2.

Comment (guggero) [reply lnwallet/chainfee/estimator.go:608]: Hmm, maybe the issue is that we don't use the `estimatesmartfee` call yet, but an older one?

Comment (yyforyongyu) [reply lnwallet/chainfee/estimator.go:608]: > IMO we should just add a special case for conf target of 1 here.

Will take this approach. So split it into three cases, when a conf target cannot be found,
a) try search a lower conf, which will give a more expensive fee rate and we will log a warning there
b) if the above fails, try search a larger conf, which will give a cheaper fee rate and we will log an error, hopefully users will catch it
c) if all the above fail, return the floor fee rate and log an error, this is a very unlikely case unless the web API has nothing in it

**Review by guggero — APPROVED** [review]
Nice fix, LGTM :tada:

**Comment by alexbosworth** [comment]
A fee estimate of 1 is not included in the fee estimates on purpose, it doesn't make sense given the way that Bitcoin core estimates fees
