### PR TITLE
config: allow independent rpccookie config

### LINKED ISSUE #6613: rpccookie does not work when .bitcoin directory is not accessable
### Background

[bitcoind.rpccookie](https://github.com/lightningnetwork/lnd/blob/7106ea59db9ade78d65bb46605f94637900c0e3f/lncfg/bitcoind.go#L10) parameter is used to point to a file that bitcoind generates for letting clients have a [more secure](https://github.com/Kixunil/security_writings/blob/master/cookie_files.md) way to authenticate with it.

bitcoind is configurable such file can be written to a custom location. This is useful for limiting access to only one or two accounts on the system that need the cookie and don't need to read the rest of `.bitcoin` directory.

Yet, looks like LND cannot be configured to access a particular `bitcoind.zmqpubrawblock`, `bitcoind.zmqpubrawtx` with a cookie. It only works with the cookie file if LND is configured to access the whole `.bitcoin` directory, from where it will read bitcoin's config for `zmqpubrawblock` and `zmqpubrawtx`: 
```
failed to load config: ValidateConfig: unable to load RPC credentials for bitcoind: please set all or none of bitcoind.rpcuser, bitcoind.rpc
pass, bitcoind.zmqpubrawblock, bitcoind.zmqpubrawtx
```
Why can't I just configure  `bitcoind.zmqpubrawblock` and `bitcoind.zmqpubrawtx` like I did with user+password auth?

### Your environment

* `lnd version 0.15.0-beta.rc3 commit=tor/v1.0.1-6-g199f9d113`
* `Linux bl5 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux`
* `Bitcoin Core version v23.0`

### Steps to reproduce

1. Run lnd and bitcoind on separate OS accounts.
2. Try to configure bitcoind to write it's cookie file to a particular directory and LND to read just that cookie file (e.g. by setting up group permissions)
3. Deny LND account from read access to `.bitcoin` directory.

### Expected behaviour

LND  should let me configure `bitcoind.zmqpubrawblock` and `bitcoind.zmqpubrawtx` 

without the need for LND to access `bitcoind.dir`

### PR DESCRIPTION
**Pull request by bitromortac**
## Change Description
Fixes #6613. The bitcoind `.cookie` file contains an auto generated user (`__cookie__`) and password (random string), which can be used instead of the rpc user name and password. This commit allows for running against bitcoind without having to access `bitcoin.conf` like in the case for pure user/password/zmq configuration.

Note that here we check explicitly that rpc password/user is not set at the same time with the cookie path (could break some malconfigured setups, previously that was allowed because one took precedence over the other).

## Steps to Test
The path for the bitcoind cookie file can be specified with `rpccookiefile` (see #6613).

### Testing
- [ ] Your PR passes all CI checks.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -1794,6 +1794,48 @@ func parseRPCParams(cConfig *lncfg.Chain, nodeConfig interface{},
...
 		}
 
+		// Get the daemon name for displaying proper errors.
+		switch net {
+		case chainreg.BitcoinChain:
+			daemonName = "bitcoind"
+			confDir = conf.Dir
+			confFile = conf.ConfigPath
+			confFileBase = "bitcoin"
+		case chainreg.LitecoinChain:
```
Comment (positiveblue) [inline config.go:1804]: I think that we can already delete litecoin-related code? @guggero

File: config.go [hunk 2]
```diff
@@ -1794,6 +1794,48 @@ func parseRPCParams(cConfig *lncfg.Chain, nodeConfig interface{},
...
+		if (conf.RPCUser != "" || conf.RPCPass != "") &&
+			conf.RPCCookie != "" {
+
+			return fmt.Errorf("please only provide either "+
+				"%[1]v.rpccookie or %[1]v.rpcuser and "+
+				"%[1]v.rpcpass", daemonName)
+		}
+
+		// We convert the cookie into a user name and password.
+		if conf.RPCCookie != "" {
```
Comment (positiveblue) [inline config.go:1822]: Same logic than bitcoin core :+1:

https://github.com/bitcoin/bitcoin/blob/33aaf434af2740d33abc0f45f613a666092630c3/contrib/linearize/linearize-hashes.py#L90

File: config.go [hunk 3]
```diff
@@ -1794,6 +1794,48 @@ func parseRPCParams(cConfig *lncfg.Chain, nodeConfig interface{},
...
+			confFileBase = "bitcoin"
+		case chainreg.LitecoinChain:
+			daemonName = "litecoind"
+			confDir = conf.Dir
+			confFile = conf.ConfigPath
+			confFileBase = "litecoin"
+		}
+
+		// Check that cookie and credentials don't contradict each
+		// other.
```
Comment (positiveblue) [inline config.go:1812]: :+1:

**Review by positiveblue — APPROVED** [review]
LGTM :rocket: 

I am not sure about litecoin though. I don't know if it uses the same cookie param or even if we need to keep supporting it.

File: config.go (hunk 1 above)
Comment (Roasbeef) [reply config.go:1804]: I think it's something we should do for 0.16, since it's basically already broken, but can't hurt to just live it in for now ;)

**Review by Roasbeef — APPROVED** [review]
LGTM 🐜

**Comment by Roasbeef** [comment]
Needs a rebase, then this is g2g!

File: config.go [hunk 4]
```diff
@@ -1794,6 +1794,48 @@ func parseRPCParams(cConfig *lncfg.Chain, nodeConfig interface{},
...
+		// We convert the cookie into a user name and password.
+		if conf.RPCCookie != "" {
+			cookie, err := ioutil.ReadFile(conf.RPCCookie)
+			if err != nil {
+				return fmt.Errorf("cannot read cookie file: %w",
+					err)
+			}
+
+			splitCookie := strings.Split(string(cookie), ":")
+			if len(splitCookie) == 2 {
```
Comment (guggero) [inline config.go:1830]: code style nit: whenever `else` is `return error`, consider inverting the condition and returning early, then the success flow can continue un-indented.

**Review by guggero — APPROVED** [review]
utACK, LGTM :tada: 

Will hit the merge button as soon as it's rebased.

File: config.go (hunk 4 above)
Comment (bitromortac) [reply config.go]: thank you, changed it and rebased

File: docs/release-notes/release-notes-0.15.1.md [hunk 5]
```diff
@@ -115,6 +115,9 @@
 * [Re-initialise registered middleware index lookup map after removal of a 
   registered middleware](https://github.com/lightningnetwork/lnd/pull/6739)
 
+* [Bitcoind cookie file path can be specified with zmq
+  options](https://github.com/lightningnetwork/lnd/pull/6735)
```
Comment (guggero) [inline docs/release-notes/release-notes-0.15.1.md:119]: PR number is wrong in link!

Comment (bitromortac) [reply docs/release-notes/release-notes-0.15.1.md]: ah sorry, another point on the checklist
