### PR TITLE
lnwallet: apply BIP69+CLTV tie-break to HTLC signature order

### LINKED ISSUE #4118: CLTV tie-breaking doesn't seem to be working
I've been doing compatibility tests on https://github.com/lightningnetwork/lightning-rfc/pull/491 (since we're very late to the party and never merged support for that in eclair :fearful:)

C-lightning correctly orders duplicates by cltv, but lnd-0.9.2-beta doesn't (I think it should, since https://github.com/lightningnetwork/lnd/pull/3142 appears to add that feature).

It's easy to repro. In an Alice -> Bob setting, have Alice send the following two HTLCs:

- HTLC 1: amount1, paymentHash1, cltv1
- HTLC 2: amount1, paymentHash1, cltv1 - 1

Bob will send the htlc signatures in the wrong order: (sig for HTLC 1, sig for HTLC 2).
It should send (sig for HTLC 2, sig for HTLC 1).

### PR DESCRIPTION
**Pull request by cfromknecht**
Fixes #4118 

This PR fixes an issue in which HTLC signatures sent to the remote peer could be improperly ordered. This can occur when multiple HTLCs share the identical payment hashes and amounts, but have differing CLTV values. In particular, if these HTLCs are added in such a way that subsequence has descending CLTVs, the HTLC signatures would not reflect the HTLC tie-breaker used to sort the commitment.

#3412 partially fixed the issue, by ensuring that we properly sort the actual commitment and second-level transaction refer to the proper txid in their previous outpoint, however it failed to apply this sorting when generating the signing jobs and hence the final ordering that is sent on the wire.

### CODE REVIEW

File: lnwallet/channel_test.go [hunk 1]
```diff
@@ -450,6 +450,107 @@ func TestCheckCommitTxSize(t *testing.T) {
 	}
 }
 
+// TestCommitHTLCSigTieBreak asserts that HTLC signatures are sent the proper
+// BIP69+CLTV sorting expected by BOLT 3 when multiple HTLCs have identical
+// payment hashes and amounts, but differing CLTVs. This is exercised by adding
+// the HTLCs in the descending order of their CLTVs, and asserting that their
+// order is reversed when signing.
+func TestCommitHTLCSigTieBreak(t *testing.T) {
```
Comment (wpaulino) [inline lnwallet/channel_test.go]: :+1:

File: lnwallet/channel.go [hunk 2]
```diff
@@ -811,6 +812,24 @@ func (lc *LightningChannel) diskHtlcToPayDesc(feeRate chainfee.SatPerKWeight,
...
+	// other party's policy.
+	var (
+		localOutputIndex  int32
+		remoteOutputIndex int32
+	)
+	switch {
+	case isLocal && isDustLocal:
+		localOutputIndex = -1
+	case !isLocal && isDustRemote:
+		remoteOutputIndex = -1
```
Comment (halseth) [inline lnwallet/channel.go]: Do we need to explicitly set this, won't `htlc.OutputIndex` already be written as `-1` in the DB?

File: lnwallet/commitment.go [hunk 3]
```diff
@@ -371,11 +371,16 @@ type unsignedCommitmentTx struct {
 	// fee is the total fee of the commitment transaction.
 	fee btcutil.Amount
 
-	// ourBalance|theirBalance are the balances of this commitment *after*
-	// subtracting commitment fees and anchor outputs. This can be
-	// different than the balances before creating the commitment
-	// transaction as one party must pay the commitment fee.
-	ourBalance   lnwire.MilliSatoshi
+	// ourBalance is our balance on this commitment *after* subtracting
```
Comment (halseth) [inline lnwallet/commitment.go]: 👍

File: lnwallet/channel_test.go (hunk 1 above)
Comment (halseth) [inline lnwallet/channel_test.go]: Ideally (IMO) the test commit should be added after the fix to ensure a bisectable commit hiistory.

File: lnwallet/channel.go (hunk 2 above)
Comment (cfromknecht) [reply lnwallet/channel.go]: good point! will update

File: lnwallet/channel_test.go (hunk 1 above)
Comment (cfromknecht) [reply lnwallet/channel_test.go]: done

**Comment by cfromknecht** [comment]
> One small nit regarding d2fa2b5 commit's message: the test addition is no longer in the prior commit.

Fixed

File: lnwallet/channel.go [hunk 4]
```diff
@@ -934,13 +953,6 @@ func (lc *LightningChannel) diskCommitToMemCommit(isLocal bool,
 		commit.dustLimit = lc.channelState.RemoteChanCfg.DustLimit
 	}
 
-	// Finally, we'll re-populate the HTLC index for this state so we can
-	// properly locate each HTLC within the commitment transaction.
-	err = commit.populateHtlcIndexes(lc.channelState.ChanType)
```
Comment (Roasbeef) [inline lnwallet/channel.go:939]: Why was this removed?

Comment (Roasbeef) [reply lnwallet/channel.go:939]: We still needs this when we go to write a commitment to disk, as we need the `outputIndex` value.

Comment (Roasbeef) [reply lnwallet/channel.go:939]: Or is this this is unnecessary, since we have already signed this commitment, and won't need to write it to disk _again_?

File: lnwallet/channel.go [hunk 5]
```diff
@@ -811,6 +812,19 @@ func (lc *LightningChannel) diskHtlcToPayDesc(feeRate chainfee.SatPerKWeight,
...
 
+	// Reconstruct the proper local/remote output indexes from the HTLC's
+	// persisted output index depending on whose commitment we are
+	// generating.
+	var (
+		localOutputIndex  int32
+		remoteOutputIndex int32
+	)
+	if isLocal {
+		localOutputIndex = htlc.OutputIndex
```
Comment (Roasbeef) [inline lnwallet/channel.go:828]: Do we actually need these values _after_ signing? Assuming that we never need to re-write a commitment to disk that is.

File: lnwallet/channel.go (hunk 4 above)
Comment (cfromknecht) [reply lnwallet/channel.go:939]: > since we have already signed this commitment, and won't need to write it to disk again?

correct, we've already written the diff at this point, plus we don't have the information available to repopulate them properly w/o access to the sorted cltvs anyway.

however, this doesn't repopulate the `outgoingHTLCIndex` and `incomingHTLCIndex` maps, perhaps those _should_ be repopulated in case we don't receive the remote party's signatures before the link is restarted?

File: lnwallet/channel.go (hunk 5 above)
Comment (cfromknecht) [reply lnwallet/channel.go:828]: i couldn't find anywhere where we use them after signing, but i think it's safer to reconstruct the in-memory state as accurately as possible to reduce the chance of introducing new bugs.

File: lnwallet/channel.go (hunk 4 above)
Comment (cfromknecht) [reply lnwallet/channel.go:939]: test case with restart added, doesn't appear that we need to repopulate
