### PR TITLE
Fix warning messages

### LINKED ISSUE #6801: lnd force-closes in response to warning messages
A while back we added warning messages to the spec with the purpose of having a way to signal to nodes that something has gone wrong but that we do not want to force close any channels.

We started using warning messages to tell peers when we ignored a gossip message because it was bogus, with the message "Unreadable/bogus gossip message".

However, it looks like lnd interprets warning messages as critical errors and responds by force-closing channels - ignoring the entire purpose of warning messages?

A peer of mine pulled this from their log:

2022-08-06 12:14:48.864 [ERR] HSWC: ChannelLink(0db90ff58728d7698dbf9e478eca33109b9777898acf28b08bd9352a75a7a74c:0): failing link: ChannelPoint(0db90ff58728d7698dbf9e478eca33109b9777898acf28b08bd9352a75a7a74c:0): received error from peer: chan_id=0000000000000000000000000000000000000000000000000000000000000000, err=Unreadable/bogus gossip message with error: remote error

On my end I just received an error message that said "remote error".

### PR DESCRIPTION
**Pull request by positiveblue**
Stop casting warnings to errors before passing it to the service handling the message. BOLT1 talks about [error and warning messages]( #6801) so I created a new interface called `ErrorLike`.

Warning messages for pending channels are now handled by the funding manager. Until now they were simply ignored.

Currently, the only action triggered by a warning messages sent by our peers  is logging.

Fixes #6801

### CODE REVIEW

File: lnwire/error.go [hunk 1]
```diff
@@ -47,6 +47,25 @@ func (e FundingError) Error() string {
 	return e.String()
 }
 
+// ErrorLike is an interface implemented by Error and Warning messages as
+// described in BOLT1.
+type ErrorLike interface {
```
Comment (Crypt-iQ) [inline lnwire/error.go:52]: I don't really see the benefit of this - I dislike changing the peer/brontide code more than it has to be changed. I think it is better if `Warning` does not embed `Error` and either:
- `handleError` is duplicated with a `handleWarning` function
- `handleError` handles both a `Warning` or an `Error` without an interface, and is renamed to `handleErrorOrWarning` or something similar

**Review by Crypt-iQ — CHANGES_REQUESTED** [review]

**Comment by saubyk** [comment]
Cleared the milestone for the pr as the issue (https://github.com/lightningnetwork/lnd/issues/6801) is tagged now

File: lnwire/error.go (hunk 1 above)
Comment (positiveblue) [reply lnwire/error.go]: I chose option A :+1:

File: peer/brontide.go [hunk 2]
```diff
@@ -1675,6 +1675,38 @@ func (p *Brontide) storeError(err error) {
 	)
 }
 
+// handleWarning processes a warning message read from the remote peer. The
+// boolean return indicates whether the message should be delivered to a
+// targeted peer or not.
+// The message gets stored in memory as an error if we have open channels with
```
Comment (Crypt-iQ) [inline peer/brontide.go:1681]: nit: no newline above

File: peer/brontide.go [hunk 3]
```diff
@@ -1675,6 +1675,38 @@ func (p *Brontide) storeError(err error) {
...
+// the peer we received it from.
+//
+// NOTE: This method should only be called from within the readHandler.
+func (p *Brontide) handleWarning(msg *lnwire.Warning) bool {
+	switch {
+	// Connection wide messages should be forward the error to all the
```
Comment (Crypt-iQ) [inline peer/brontide.go:1687]: s/error/warning

File: funding/manager.go [hunk 4]
```diff
@@ -4077,12 +4085,16 @@ func (f *Manager) handleInitFundingMsg(msg *InitFundingMsg) {
 	}
 }
 
+// handleWarningMsg processes the warning which was received from remote peer.
+func (f *Manager) handleWarningMsg(peer lnpeer.Peer, msg *lnwire.Warning) {
```
Comment (Crypt-iQ) [inline funding/manager.go:4089]: i think this should come with a test

File: lnwire/lnwire.go [hunk 5]
```diff
@@ -194,6 +208,18 @@ func WriteElement(w *bytes.Buffer, element interface{}) error {
 		if _, err := w.Write(e[:]); err != nil {
 			return err
 		}
+
+	case WarningData:
```
Comment (Crypt-iQ) [inline lnwire/lnwire.go:212]: is this called anywhere?

**Review by Crypt-iQ — COMMENTED** [review]
i think the link test should be added back and that a fundingmanager test should be added

File: lnwire/lnwire.go (hunk 5 above)
Comment (Roasbeef) [reply lnwire/lnwire.go:212]: I think we can actually also just fall through to the case below.

File: peer/brontide.go [hunk 6]
```diff
@@ -1775,7 +1807,7 @@ func messageSummary(msg lnwire.Message) string {
 			msg.ChanID, msg.ID, msg.FailureCode)
 
 	case *lnwire.Warning:
-		return fmt.Sprintf("%v", msg.Error.Error())
+		return fmt.Sprintf("%v", msg.Warning())
```
Comment (Roasbeef) [inline peer/brontide.go:1810]: If we keep the existing `Error` method, then we can pass it around as a normal `error`. Not sure if we 100% want that behavior though...

**Review by Roasbeef — COMMENTED** [review]
IIRC, you had a test that you used to repro the behavior in the first place? If we modified `SendCustomMessage` to allow sending messages below the custom message range w/ a build tag (for itests) then we can test this out in the wild to ensure that sending a warning doesn't lead to a force close. This should help catch any future regressions in the future.

File: lnwire/lnwire.go [hunk 7]
```diff
@@ -589,6 +633,19 @@ func ReadElement(r io.Reader, element interface{}) error {
 		if _, err := io.ReadFull(r, *e); err != nil {
 			return err
 		}
+
+	case *WarningData:
```
[the remark this answers is not in the document]
Comment (positiveblue) [reply lnwire/lnwire.go:637]: It would be nicer but we cannot because the `switch` statement is casting to the data type. Even if the underlying struct looks the same we cannot access to its properties until we cast it again. Same case as `ShortChanIDEncoding` and `uint8`

File: peer/brontide.go (hunk 6 above)
Comment (positiveblue) [reply peer/brontide.go:1809]: I would leave it like this so we do not have any error in the future using the `Error` interface for warnings.

File: lnwire/lnwire.go (hunk 5 above)
Comment (positiveblue) [reply lnwire/lnwire.go:212]: No, and the method will be removed soon* (YY comment). However, I added in case someone is using `lnwire.WriteElement` outside the lnd code base for completeness.

File: funding/manager.go (hunk 4 above)
Comment (positiveblue) [reply funding/manager.go:4178]: Added `don't fail the channel if we receive a warning message` to `TestChannelLinkFail`

**Review by Crypt-iQ — APPROVED** [review]
needs rebase

**Review by Roasbeef — APPROVED** [review]
LGTM ❄️

**Comment by guggero** [comment]
@positiveblue the new linter rules seem to cause a few new complaints.
