### PR TITLE
[funding+autopilot] Make the funding manager and autopilot fee aware

### LINKED ISSUE #986: Autopilot can create impossible channel requests, which fail due to occupying funds without room for transaction fees
### Background

If you configure autopilot to control the entire wallet, it will attempt to open channels with all available funds, which will result in destined-to-fail openChannel directives due to the need to pay fees on opening

### Your environment

* lnd 0.4.0, but also present in master
* mac os
* bitcoind

### Steps to reproduce

Set `autopilot.allocation=1`
Have enough funds for < `autopilot.maxchannels` channels in the wallet.

### Expected behaviour

Autopilot should be able to control the full wallet and account for fees in the final channel opening directive

### Actual behaviour

```
2018-03-31 04:04:09.657 [INF] ATPL: Triggering attachment directive dispatch, total_funds=0.02493046 BTC
2018-03-31 04:04:10.729 [INF] ATPL: Attempting to execute channel attachment directives: ([]autopilot.AttachmentDirective) (len=1 cap=1) {
 (autopilot.AttachmentDirective) {
  PeerKey: (*btcec.PublicKey)(0xXXXX)({
   Curve: (elliptic.Curve) <nil>,
   X: (*big.Int)(0x)(XXXXX),
   Y: (*big.Int)(0x)(YYYYY)
  }),
  ChanAmt: (btcutil.Amount) 0.02493046 BTC,
  Addrs: ([]net.Addr) (len=1 cap=1) {
   (*net.TCPAddr)(0x)(X.X.X.X)
  }
 }
}

2018-03-31 04:04:11.856 [INF] FNDG: Initiating fundingRequest(localAmt=0.02493046 BTC, remoteAmt=0 mSAT, capacity=0.02493046 BTC, chainhash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, addr=X.X.X.X, dustLimit=0.00000573 BTC)
2018-03-31 04:04:11.858 [INF] LNWL: Performing funding tx coin selection using 4 sat/vbyte as fee rate
2018-03-31 04:04:11.858 [WRN] ATPL: Unable to open channel to XXX of 0.02493046 BTC: not enough witness outputs to create funding transaction, need 0.02493658 BTC only have 0.02493046 BTC  available
```

### PR DESCRIPTION
**Pull request by halseth**
This is an alternative to #3017.

Since the funding manager and wallet can't know up front the how much it will cost us in fees to fund a channel, it will always cost us more than `chanSize` in total. This makes it hard to spend all the funds remaining in the wallet into a channel, since we won't have enough to cover the additional fee.

This PR attempts to fix this by letting one specify a "spend amount" instead of a "channel size" when opening a channel. This makes the wallet do coin selection that results in a decrease in balance equal to this spend amount, instead of spending `chanSize+fees`.

We make the autopilot use this new option, making it better at staying within its budget, and also able to open channels that utilizes the whole wallet balance.

Fixes #986

### CODE REVIEW

File: fundingmanager_test.go [hunk 1]
```diff
@@ -467,20 +475,19 @@ func recreateAliceFundingManager(t *testing.T, alice *testNode) {
...
-func setupFundingManagers(t *testing.T, maxPendingChannels int) (*testNode, *testNode) {
-	// We need to set the global config, as fundingManager uses
-	// MaxPendingChannels, and it is usually set in lndMain().
-	cfg = &config{
-		MaxPendingChannels: maxPendingChannels,
-	}
+type cfgOption func(*fundingConfig)
+
+func setupFundingManagers(t *testing.T, maxPendingChannels int,
+	options ...cfgOption) (*testNode, *testNode) {
```
Comment (wpaulino) [inline fundingmanager_test.go]: If we're going this route, why not also make `maxPendingChannels` a `cfgOption`?

File: lnwallet/reservation.go [hunk 2]
```diff
@@ -163,7 +163,7 @@ func NewChannelReservation(capacity, fundingAmt btcutil.Amount,
 		// TODO(roasbeef): need to rework fee structure in general and
 		// also when we "unlock" dual funder within the daemon
 
-		if capacity == fundingAmt {
+		if capacity == localFundingAmt {
```
Comment (wpaulino) [inline lnwallet/reservation.go]: Unrelated to this diff (https://github.com/lightningnetwork/lnd/pull/3165/commits/949783387a3b8f170e362c1edef45a45bb1578e6) but noticed while reviewing the whole method: there's a dust check below and above for 0 when it should really be `2 * DefaultDustLimit()`?

File: lnwallet/wallet.go [hunk 3]
```diff
@@ -484,15 +484,16 @@ func (l *LightningWallet) handleFundingReserveRequest(req *InitFundingReserveMsg
...
 			req.FundingFeePerKw, req.LocalFundingAmt, req.MinConfs,
-			reservation.ourContribution,
 		)
 		if err != nil {
 			req.err <- err
 			req.resp <- nil
 			return
 		}
+		reservation.ourContribution.Inputs = coins
+		reservation.ourContribution.ChangeOutputs = change
```
Comment (wpaulino) [inline lnwallet/wallet.go]: Unrelated: any reason this is a slice rather than just one?

File: lnwallet/wallet.go [hunk 4]
```diff
@@ -1302,52 +1304,64 @@ func (l *LightningWallet) selectCoinsAndChange(feeRate SatPerKWeight,
...
-		contribution.ChangeOutputs[0] = &wire.TxOut{
+		changeOutputs = make([]*wire.TxOut, 1)
+		changeOutputs[0] = &wire.TxOut{
 			Value:    int64(changeAmt),
 			PkScript: changeScript,
 		}
 	}
 
-	return nil
+	unlock := func() {
```
Comment (wpaulino) [inline lnwallet/wallet.go]: Seems like we'd want to call this in the error cases above after the inputs are locked.

File: lnwallet/wallet.go [hunk 5]
```diff
@@ -457,8 +457,36 @@ func (l *LightningWallet) handleFundingReserveRequest(req *InitFundingReserveMsg
...
+
+	// If we're on the receiving end of a single funder channel then we
+	// don't need to perform any coin selection, and the remote contributes
+	// all funds.
+	capacity := req.RemoteFundingAmt
+	localFundingAmt := btcutil.Amount(0)
+
+	// Otherwise, attempt to obtain enough coins to meet the required
+	// funding amount.
+	if req.LocalFundingAmt != 0 {
```
Comment (wpaulino) [inline lnwallet/wallet.go]: Add TODO to handle dual funder case?

File: lnwallet/wallet.go [hunk 6]
```diff
@@ -494,66 +495,88 @@ func (l *LightningWallet) handleFundingReserveRequest(req *InitFundingReserveMsg
 		req.PushMSat, l.Cfg.NetParams.GenesisHash, req.Flags,
 	)
 	if err != nil {
+		unlock()
 		req.err <- err
 		req.resp <- nil
 		return
 	}
 
+	err = l.initOurContribution(
```
Comment (wpaulino) [inline lnwallet/wallet.go]: :+1:

File: lnwallet/wallet.go [hunk 7]
```diff
@@ -432,13 +439,21 @@ func (l *LightningWallet) InitChannelReservation(
...
-	if req.LocalFundingAmt+req.RemoteFundingAmt == 0 {
+	if req.LocalFundingAmt+req.RemoteFundingAmt+req.LocalSpendAmt == 0 {
 		err := ErrZeroCapacity()
 		req.err <- err
 		req.resp <- nil
 		return
 	}
 
+	if req.LocalFundingAmt+req.RemoteFundingAmt > 0 && req.LocalSpendAmt > 0 {
+		err := fmt.Errorf("Local and remote fund amt must be zero " +
```
Comment (wpaulino) [inline lnwallet/wallet.go]: Nit: errors returned should begin lowercase.

There are some other cases as well.

File: lnwallet/wallet.go [hunk 8]
```diff
@@ -69,6 +69,13 @@ type InitFundingReserveMsg struct {
 	// workflow.
 	NodeAddr net.Addr
 
+	// LocalSpendAmt should be set to the amount we intend to spend when
+	// opening the channel. This can be used for instance to use all our
+	// remaining funds to open the channel, since it will take fees into
+	// account. Can currently only be used when LocalFundingAmt and
+	// RemoteFundingAmt are set to 0.
+	LocalSpendAmt btcutil.Amount
```
Comment (wpaulino) [inline lnwallet/wallet.go]: WTB enum structs. An alternative to make it clear only one of these can be specified would be something similar to what's shown in https://play.golang.org/p/jfgsCBxb9q.

File: lnwallet/wallet.go [hunk 9]
```diff
@@ -1303,6 +1336,10 @@ func (l *LightningWallet) WithCoinSelectLock(f func() error) error {
 // successful/possible, then the selected coins and change outputs are
 // returned. This method locks the selected outputs, and a function closure to
 // unlock them in case of an error is returned.
+//
+// NOTE: This method is different from selectCoinsToSpend in the way that it is
+// targetting a specific funding output size, instead of spending a given
```
Comment (wpaulino) [inline lnwallet/wallet.go]: Nit: s/targetting/targeting/

There are some other cases as well.

File: lnwallet/wallet.go [hunk 10]
```diff
@@ -1380,6 +1417,119 @@ func (l *LightningWallet) selectCoinsAndChange(feeRate SatPerKWeight,
...
+// 'toSpend' creating the funding tx. If necessary, a change address will also
+// be generated. If coin selection is successful/possible, then the selected
+// coins and change outputs are returned, and the value of the resulting
+// funding output. This method locks the selected outputs, and a function
+// closure to unlock them in case of an error is returned.
+//
+// NOTE: This method is different from selectCoinsAndChange in the way that it
+// spends the given amount when selecting coins, instead of targetting a
+// specific funding output size.
+func (l *LightningWallet) selectCoinsToSpend(feeRate SatPerKWeight,
```
Comment (wpaulino) [inline lnwallet/wallet.go]: There's a good bit of duplication here with `coinSelect` and `selectCoinsAndChange`. Seems like it'd be possible to refactor some things around.

File: lnwallet/wallet.go (hunk 8 above)
Comment (wpaulino) [reply lnwallet/wallet.go]: Another approach would be to make this a `SubtractFees bool` and keep `LocalFundingAmt` the same. Then we can just thread the boolean down to coin selection.

File: fundingmanager_test.go [hunk 11]
```diff
@@ -2724,3 +2724,95 @@ func TestFundingManagerMaxConfs(t *testing.T) {
...
+		}
+
+		if !test.change && len(fundingTx.TxOut) != 1 {
+			t.Fatalf("expected 1 output, had %v",
+				len(fundingTx.TxOut))
+		}
+
+		// Inputs should be all funds in the wallet.
+		if len(fundingTx.TxIn) != len(allCoins) {
+			t.Fatalf("Fad %d inputs, expected %d",
```
Comment (wpaulino) [inline fundingmanager_test.go]: Nit: s/fad/had/

File: lnwallet/reservation.go (hunk 2 above)
Comment (halseth) [reply lnwallet/reservation.go]: I think that is covered by the dustcheck online 198?

File: lnwallet/wallet.go (hunk 3 above)
Comment (halseth) [reply lnwallet/wallet.go]: Not sure. Legacy reasons I guess

File: lnwallet/wallet.go (hunk 5 above)
Comment (halseth) [reply lnwallet/wallet.go]: I think dual funder is a known TODO tbh :p

File: fundingmanager_test.go (hunk 1 above)
Comment (halseth) [reply fundingmanager_test.go]: Yes, good idea! Done.

File: lnwallet/wallet.go (hunk 4 above)
Comment (halseth) [reply lnwallet/wallet.go]: Good catch! Fixed by moving locking to below the error cases.

File: lnwallet/wallet.go (hunk 7 above)
Comment (halseth) [reply lnwallet/wallet.go]: Fixed.

File: fundingmanager_test.go (hunk 11 above)
Comment (halseth) [reply fundingmanager_test.go]: Fixed.

File: lnwallet/wallet.go (hunk 10 above)
Comment (halseth) [reply lnwallet/wallet.go]: Done.

File: lnwallet/wallet.go (hunk 9 above)
Comment (halseth) [reply lnwallet/wallet.go]: Fixed

File: lnwallet/wallet.go (hunk 8 above)
Comment (halseth) [reply lnwallet/wallet.go]: Yeah, a enum/union holding the amount and the type of amount would be ideal here. Defining a new type seemed a bit overkill.

Using the bool would work, would you prefer it over the current approach? (code wise it would be more or less the same).

**Comment by halseth** [comment]
PTAL @wpaulino

File: lnwallet/wallet.go [hunk 12]
```diff
@@ -449,9 +457,12 @@ func (l *LightningWallet) handleFundingReserveRequest(req *InitFundingReserveMsg
 		return
 	}
 
+	capacity := req.LocalFundingAmt + req.RemoteFundingAmt
+	localFundingAmt := req.LocalFundingAmt
+
 	id := atomic.AddUint64(&l.nextFundingID, 1)
 	reservation, err := NewChannelReservation(
-		req.Capacity, req.FundingAmount, req.CommitFeePerKw, l, id,
+		capacity, localFundingAmt, req.CommitFeePerKw, l, id,
```
Comment (wpaulino) [inline lnwallet/wallet.go]: Nit: could also make `NewChannelReservation` take the remote funding amount as well.

File: lnwallet/reservation.go (hunk 2 above)
Comment (wpaulino) [reply lnwallet/reservation.go]: That check doesn't cover the remote case. It does cover the initiator case though, so one of those checks is redundant.

File: lnwallet/wallet.go [hunk 13]
```diff
@@ -1320,48 +1320,76 @@ func (l *LightningWallet) selectCoinsAndChange(feeRate SatPerKWeight,
...
+	return &wire.TxOut{
+		Value:    int64(changeAmt),
+		PkScript: changeScript,
+	}, nil
+}
+
+// lockCoins locks the given UTXOs such that they will be reserved and
+// ineglible for use by other transactions. A function closure to unlock them
+// is returned.
+func (l *LightningWallet) lockCoins(coins []*Utxo) (func(), error) {
```
Comment (wpaulino) [inline lnwallet/wallet.go]: Add a note that this requires the `coinSelectMtx` lock to be held.

Comment (wpaulino) [reply lnwallet/wallet.go]: Also seems like this method doesn't need to return an error.

File: lnwallet/wallet.go (hunk 8 above)
Comment (wpaulino) [reply lnwallet/wallet.go]: Yeah I think the bool approach is cleaner.

File: lnwallet/wallet.go (hunk 10 above)
Comment (wpaulino) [reply lnwallet/wallet.go]: Hmm I was thinking of actually reusing the existing `selectCoins` method. We'd pass a `subtractFees bool` to it and, if set, run the special case logic.

Comment (halseth) [reply lnwallet/wallet.go]: Done.

**Comment by halseth** [comment]
Pushed a new version using the `subtractFees` bool. Also increased the test covereage of `coinSelect`,  it should be handling more edge cases now.

PTAL @wpaulino

File: lnwallet/wallet.go [hunk 14]
```diff
@@ -1392,19 +1436,27 @@ func selectInputs(amt btcutil.Amount, coins []*Utxo) (btcutil.Amount, []*Utxo, e
...
+// returns the size of the created funding ouput, as well as the size of the
+// change output if any. The specified fee rate should be expressed in sat/kw
+// for coin selection to function properly, and the passed dustLimit is used to
+// clamp the outputs created.
+//
+// If subtractFees is true, then the estimated fee will be taken from the
+// output amount, meaning that the resuling funding output might be smaller
+// than the passed amt. The resulting funding output value will be returned,
+// along with the change amount if any.
+func coinSelect(feeRate SatPerKWeight, amt, dustLimit btcutil.Amount,
```
Comment (wpaulino) [inline lnwallet/wallet.go]: It might just be me, but I find this method a bit difficult to follow in its final form due to all of the different variables involved, though avoiding the code duplication is certainly nice.

Comment (halseth) [reply lnwallet/wallet.go]: Yeah, I agree. In the process of trying to share the code between the two cases, it kinda got out of hand. The two cases (`subtractFee=true/false`) are different enough to make it tricky to handle edge cases between them.

Code harder to reason about is more prone for errors than a little bit of code duplication.

Comment (halseth) [reply lnwallet/wallet.go]: I created a version where the two cases are separated, lmk what you think: https://github.com/lightningnetwork/lnd/compare/master...halseth:autopilot-spend-coins-subtract-fees-distinct-coinselect?expand=1

Comment (wpaulino) [reply lnwallet/wallet.go]: Separating them LGTM. Would also be nice to get someone else's opinion.

File: lnwallet/wallet_test.go [hunk 15]
```diff
@@ -0,0 +1,152 @@
...
+		// Optionally count a change output.
+		if change {
+			weightEstimate.AddP2WKHOutput()
+		}
+
+		totalWeight := int64(weightEstimate.Weight())
+		return feeRate.FeeForWeight(totalWeight)
+	}
+
+	type testCase struct {
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet_test.go]: Done.

File: lnwallet/wallet.go [hunk 16]
```diff
@@ -1290,11 +1301,12 @@ func (l *LightningWallet) WithCoinSelectLock(f func() error) error {
 // outputs which sum to at least 'amt' amount of satoshis. If necessary,
 // a change address will also be generated. If coin selection is
 // successful/possible, then the selected coins and change outputs are
-// returned. This method locks the selected outputs, and a function closure to
-// unlock them in case of an error is returned.
+// returned, and the value of the resulting funding output. This method locks
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet.go]: It will always select coins targetting a multisig output, so I think it is safe to assume it is only used for funding txs for now.

File: lnwallet/wallet.go [hunk 17]
```diff
@@ -1453,6 +1466,9 @@ func coinSelect(feeRate SatPerKWeight, amt, dustLimit btcutil.Amount,
 		// selected inputs. We'll remember the resulting values for
 		// now, while we try to add a change output.
 		changeAmt := btcutil.Amount(0)
+		if subtractFees {
+			outputAmt += rem
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet.go]: Should be better now after the split.

File: fundingmanager_test.go [hunk 18]
```diff
@@ -2727,3 +2727,94 @@ func TestFundingManagerMaxConfs(t *testing.T) {
...
+			t.Fatalf("expected 2 outputs, had %v",
+				len(fundingTx.TxOut))
+		}
+
+		if !test.change && len(fundingTx.TxOut) != 1 {
+			t.Fatalf("expected 1 output, had %v",
+				len(fundingTx.TxOut))
+		}
+
+		// Inputs should be all funds in the wallet.
```
[the remark this answers is not in the document]
Comment (halseth) [reply fundingmanager_test.go]: Done.

File: lnwallet/reservation.go (hunk 2 above)
Comment (halseth) [reply lnwallet/reservation.go]: You're right, the below check covers the case were we are the initiator, but not when the remote gets a dust balance. I think it is okay for now though, since the remote is the one that should reject it because of the dust (it doesn't hurt us).

File: lnwallet/wallet.go (hunk 12 above)
Comment (halseth) [reply lnwallet/wallet.go]: Agreed, but seemed like a change too big to be done in this PR. Added a TODO.

**Comment by halseth** [comment]
Coin select separated to make logic more straightforward and comments addressed. PTAL @wpaulino

File: lnwallet/wallet.go [hunk 19]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+	// wil go to change.
+	newChange := totalSat - amt
+	newOutput := amt - requiredFee
+
+	// If adding a change output lead to both outputs being above
+	// the dust limit, we'll add the change ouput. Otherwise we'll
+	// go with the no change tx we originally found.
+	if newChange > dustLimit && newOutput > dustLimit {
+		outputAmt = newOutput
+		changeAmt = newChange
```
Comment (wpaulino) [inline lnwallet/wallet.go]: If we can proceed with the change output, wouldn't we want to subtract the fee from the change output instead if possible? The current logic subtracts it from the non-change output.

File: fundingmanager.go [hunk 20]
```diff
@@ -2756,10 +2755,11 @@ func (f *fundingManager) handleInitFundingMsg(msg *initFundingMsg) {
 		ourDustLimit = defaultLitecoinDustLimit
 	}
 
-	fndgLog.Infof("Initiating fundingRequest(localAmt=%v, remoteAmt=%v, "+
-		"capacity=%v, chainhash=%v, peer=%x, dustLimit=%v, min_confs=%v)",
-		localAmt, msg.pushAmt, capacity, msg.chainHash,
-		peerKey.SerializeCompressed(), ourDustLimit, msg.minConfs)
+	fndgLog.Infof("Initiating fundingRequest(localAmt=%v "+
+		"(subtractFees=%v), pushAmt=%v, chainhash=%v, peer=%x, "+
+		"dustLimit=%v, min_confs=%v)", localAmt, msg.subtractFees,
```
Comment (wpaulino) [inline fundingmanager.go]: Style nit: make `min_confs` camelCase for consistency?

**Comment by Roasbeef** [comment]
Will this result in 1-in-1-out channels if using the entire wallet balance? I bring this up as ideally we can still support CPFP'ing these channels for confirmation purposes even if we're using _most_ of the balance of the wallet. However, in that case, we'd need to start leaving a "fee purse" on-chain at all times. In the future, once we move to pure CPFP or sighash single fees for channel force closes, then such a coin tranche will be required for operation.

File: fundingmanager_test.go [hunk 21]
```diff
@@ -2391,6 +2420,8 @@ func TestFundingManagerCustomChannelParameters(t *testing.T) {
 // TestFundingManagerMaxPendingChannels checks that trying to open another
 // channel with the same peer when MaxPending channels are pending fails.
 func TestFundingManagerMaxPendingChannels(t *testing.T) {
+	t.Parallel()
```
Comment (Roasbeef) [inline fundingmanager_test.go]: IIRC there's some lingering global variable race condition that prevented us from doing this in the past?

File: lnwallet/wallet_test.go [hunk 22]
```diff
@@ -0,0 +1,176 @@
...
+	// Optionally count a change output.
+	if change {
+		weightEstimate.AddP2WKHOutput()
+	}
+
+	totalWeight := int64(weightEstimate.Weight())
+	return feeRate.FeeForWeight(totalWeight)
+}
+
+// TestCoinSelect tests that we pick coins adding up to the expected amount
```
Comment (Roasbeef) [inline lnwallet/wallet_test.go]: 👌

File: lnwallet/wallet_test.go [hunk 23]
```diff
@@ -0,0 +1,176 @@
...
+// when creating a funding transaction, and that the calculated change is the
+// expected amount.
+// NOTE: coinSelect will always attempt to add a change output, so we must
```
Comment (Roasbeef) [inline lnwallet/wallet_test.go]: Style nit: missing newline above.

File: lnwallet/wallet_test.go [hunk 24]
```diff
@@ -0,0 +1,176 @@
...
+			// We have just enough left to pay the fee, so there is
+			// nothing left for change.
+			// TODO(halseth): currently coinselect estimates fees
+			// assuming a change output.
+			expectedChange: 0,
+		},
+	}
+
+	for _, test := range testCases {
+		t.Run(test.name, func(t *testing.T) {
```
Comment (Roasbeef) [inline lnwallet/wallet_test.go]: Can bind the loop variable `test := test`, then use `t.Paralle()` within the `Run` closure.

File: lnwallet/wallet.go [hunk 25]
```diff
@@ -1274,13 +1275,14 @@ func (l *LightningWallet) WithCoinSelectLock(f func() error) error {
...
-// also be generated.
+// outputs which sum to at least 'amt' amount of satoshis. If necessary,
+// a change address will also be generated. If coin selection is
+// successful/possible, then the selected coins and change outputs are
+// returned. This method locks the selected outputs, and a function closure to
+// unlock them in case of an error is returned.
 func (l *LightningWallet) selectCoinsAndChange(feeRate SatPerKWeight,
-	amt btcutil.Amount, minConfs int32,
-	contribution *ChannelContribution) error {
+	amt btcutil.Amount, minConfs int32) ([]*wire.TxIn, []*wire.TxOut,
```
Comment (Roasbeef) [inline lnwallet/wallet.go]: Would be more readable if the return parameters were lifted into a struct that looks something like: 
```go
type selectedCoins struct {
    Coins []*wire.TxIn
    Change []*wire.TxOut
    ReleaseCoins func() 
}
```

File: lnwallet/interface_test.go [hunk 26]
```diff
@@ -772,7 +772,7 @@ func testReservationInitiatorBalanceBelowDustCancel(miner *rpctest.Harness,
 		LocalFundingAmt:  fundingAmount,
 		RemoteFundingAmt: 0,
 		CommitFeePerKw:   feePerKw,
-		FundingFeePerKw:  feePerKw,
+		FundingFeePerKw:  1000,
```
Comment (Roasbeef) [inline lnwallet/interface_test.go]: Why was this needed?

File: lnwallet/wallet.go [hunk 27]
```diff
@@ -483,66 +484,88 @@ func (l *LightningWallet) handleFundingReserveRequest(req *InitFundingReserveMsg
...
-		req.err <- err
-		req.resp <- nil
-		return
+		return err
 	}
 	reservation.ourContribution.DelayBasePoint, err = l.DeriveNextKey(
 		keychain.KeyFamilyDelayBase,
 	)
 	if err != nil {
-		req.err <- err
```
Comment (Roasbeef) [inline lnwallet/wallet.go]: Nice to get rid of all these error sends as well!

File: lnwallet/wallet.go [hunk 28]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
 		return selectedUtxos, changeAmt, nil
 	}
 }
+
+// coinSelectSubtractFees attempts to select coins such that we'll spend up to
```
Comment (Roasbeef) [inline lnwallet/wallet.go]: we'll -> will ?

File: lnwallet/wallet.go [hunk 29]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+		return nil, 0, 0, fmt.Errorf("output amount(%v) after "+
+			"subtracting fees(%v) below dust limit(%v)", outputAmt,
+			requiredFee, dustLimit)
+	}
+
+	// We were able to create a transaction with no change from the
+	// selected inputs. We'll remember the resulting values for
+	// now, while we try to add a change output. Assume that change output
+	// is a P2WKH output.
+	weightEstimate.AddP2WKHOutput()
```
Comment (Roasbeef) [inline lnwallet/wallet.go]: Don't see an area where this is ever undone, if we don't need a change output. So we'll still factor this output into the fees we pay, resulting in us over paying.

File: lnwallet/wallet.go [hunk 30]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+		changeAmt = newChange
+	}
+
+	// Sanity check the resulting ouput values to make sure we
+	// don't burn a great part to fees.
+	totalOut := outputAmt + changeAmt
+	fee := totalSat - totalOut
+
+	// Fail if more than 20% goes to fees.
+	if fee > totalOut/5 {
```
Comment (Roasbeef) [inline lnwallet/wallet.go]: Possibly make this 20% value a config parameter? In certain situations like testnet or simnet, the user may not care.

File: lnwallet/wallet.go [hunk 31]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+
+	// If adding a change output lead to both outputs being above
+	// the dust limit, we'll add the change ouput. Otherwise we'll
+	// go with the no change tx we originally found.
+	if newChange > dustLimit && newOutput > dustLimit {
+		outputAmt = newOutput
+		changeAmt = newChange
+	}
+
+	// Sanity check the resulting ouput values to make sure we
```
Comment (Roasbeef) [inline lnwallet/wallet.go]: ouput -> output

File: lnwallet/wallet_test.go [hunk 32]
```diff
@@ -174,3 +174,173 @@ func TestCoinSelect(t *testing.T) {
 		})
 	}
 }
+
+// TestCoinSelectSubtractFees tests that we pick coins adding up to the expected amount
```
Comment (Roasbeef) [inline lnwallet/wallet_test.go]: Funky line wrapping?

File: fundingmanager.go (hunk 20 above)
Comment (Roasbeef) [reply fundingmanager.go]: We kinda use both in the codebase for logging atm. Personally, I prefer snake case for stuff like this, and camel case when referring to a sub-system within the codebase, similar to Python naming conventions.

File: autopilot/agent.go [hunk 33]
```diff
@@ -584,6 +584,7 @@ func (a *Agent) openChans(availableFunds btcutil.Amount, numChans uint32,
 
 	// Use the heuristic to calculate a score for each node in the
 	// graph.
+	log.Debugf("Scoring %d nodes for chansize=%v", len(nodes), chanSize)
```
Comment (Roasbeef) [inline autopilot/agent.go]: `chan_size`?

File: fundingmanager_test.go (hunk 21 above)
Comment (wpaulino) [reply fundingmanager_test.go]: I believe that was addressed by https://github.com/lightningnetwork/lnd/pull/3165/commits/fe7d9143d8e15bfa5f57793e52c7110a643faf04.

**Comment by wpaulino** [comment]
> Will this result in 1-in-1-out channels if using the entire wallet balance? I bring this up as ideally we can still support CPFP'ing these channels for confirmation purposes even if we're using most of the balance of the wallet. However, in that case, we'd need to start leaving a "fee purse" on-chain at all times. In the future, once we move to pure CPFP or sighash single fees for channel force closes, then such a coin tranche will be required for operation.

Seems like we can work around this with the autopilot allocation setting?

File: fundingmanager_test.go (hunk 21 above)
Comment (halseth) [reply fundingmanager_test.go]: Yep exactly :)

File: lnwallet/interface_test.go (hunk 26 above)
Comment (halseth) [reply lnwallet/interface_test.go]: The test is attempting to test that an insane commit fee is pushing our balance into the negative, but without this change it would fail even to select coins for the funding tx (this was not a problem before since we first selected coins after making the reservation).

File: lnwallet/wallet.go (hunk 28 above)
Comment (halseth) [reply lnwallet/wallet.go]: we'll is correct

File: lnwallet/wallet.go (hunk 29 above)
Comment (halseth) [reply lnwallet/wallet.go]: The `weightEstimate` is only used again on the line below, so no reason to undo. 

At this point we have found a valid coin selection (`outputAmt` and `changeAmt=0`), so we just check if adding a change output still is valid (if not we return the first valid selection we found).

File: lnwallet/wallet_test.go (hunk 23 above)
Comment (halseth) [reply lnwallet/wallet_test.go]: fixed: https://github.com/lightningnetwork/lnd/pull/3165/commits/53f5e10b856323356115c9ac8df9792b869f4c4a

File: lnwallet/wallet_test.go (hunk 24 above)
Comment (halseth) [reply lnwallet/wallet_test.go]: fixed: https://github.com/lightningnetwork/lnd/pull/3165/commits/53f5e10b856323356115c9ac8df9792b869f4c4a

File: lnwallet/wallet.go (hunk 25 above)
Comment (halseth) [reply lnwallet/wallet.go]: Good idea! Done: https://github.com/lightningnetwork/lnd/pull/3165/commits/b136a27562cfa91d569f8a7588d1c42dbaca09d6

File: lnwallet/wallet.go [hunk 34]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+
+	var weightEstimate input.TxWeightEstimator
+	for _, utxo := range selectedUtxos {
+		switch utxo.AddressType {
+		case WitnessPubKey:
+			weightEstimate.AddP2WKHInput()
+		case NestedWitnessPubKey:
+			weightEstimate.AddNestedP2WKHInput()
+		default:
+			return nil, 0, 0, fmt.Errorf("Unsupported "+
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet.go]: done: https://github.com/lightningnetwork/lnd/pull/3165/commits/a01182ae51fa85b5c9b3be8e64ad4e2e203fa243

File: lnwallet/wallet.go [hunk 35]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+	// is a P2WKH output.
+	weightEstimate.AddP2WKHOutput()
+
+	// Now that we have added the change output, redo the fee
+	// estimate.
+	totalWeight = int64(weightEstimate.Weight())
+	requiredFee = feeRate.FeeForWeight(totalWeight)
+
+	// For a transaction with a change output, everything we don't spend
+	// wil go to change.
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet.go]: Fixed

File: lnwallet/wallet.go [hunk 36]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+	newChange := totalSat - amt
+	newOutput := amt - requiredFee
+
+	// If adding a change output lead to both outputs being above
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet.go]: Fixed

File: lnwallet/wallet.go [hunk 37]
```diff
@@ -1485,3 +1485,93 @@ func coinSelect(feeRate SatPerKWeight, amt btcutil.Amount,
...
+	// the dust limit, we'll add the change ouput. Otherwise we'll
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet.go]: fixed

File: lnwallet/wallet.go (hunk 31 above)
Comment (halseth) [reply lnwallet/wallet.go]: fixed.

File: lnwallet/wallet_test.go (hunk 32 above)
Comment (halseth) [reply lnwallet/wallet_test.go]: Fixed: https://github.com/lightningnetwork/lnd/pull/3165/commits/bb47413e52538b1ddffe9bec133e247824537dd7

File: lnwallet/wallet.go (hunk 19 above)
Comment (halseth) [reply lnwallet/wallet.go]: Since this method is meant to target an exact _spend amount_, we want to ensure that the total we spend is `fundingAmt+fee`. Subtracting it from the change would cause us to spend a bit more than intended.

File: fundingmanager.go (hunk 20 above)
Comment (halseth) [reply fundingmanager.go]: Made them all snake case 🐍

File: lnwallet/wallet.go (hunk 30 above)
Comment (halseth) [reply lnwallet/wallet.go]: Are you thinking a user configurable setting? 

Since the user can already control fees for manually opened channels, maybe it makes sense to make it an `autopilot` setting?

**Comment by halseth** [comment]
> > Will this result in 1-in-1-out channels if using the entire wallet balance? I bring this up as ideally we can still support CPFP'ing these channels for confirmation purposes even if we're using most of the balance of the wallet. However, in that case, we'd need to start leaving a "fee purse" on-chain at all times. In the future, once we move to pure CPFP or sighash single fees for channel force closes, then such a coin tranche will be required for operation.
> 
> Seems like we can work around this with the autopilot allocation setting?

Decided to go with the 1-output funding txes for now, as this mostly only targetting the "fund all" case, where it makes sense to not leave any tiny change output.

PTAL @wpaulino @Roasbeef

**Comment by wpaulino** [comment]
>>> Will this result in 1-in-1-out channels if using the entire wallet balance? I bring this up as ideally we can still support CPFP'ing these channels for confirmation purposes even if we're using most of the balance of the wallet. However, in that case, we'd need to start leaving a "fee purse" on-chain at all times. In the future, once we move to pure CPFP or sighash single fees for channel force closes, then such a coin tranche will be required for operation.

>> Seems like we can work around this with the autopilot allocation setting?

> Decided to go with the 1-output funding txes for now, as this mostly only targetting the "fund all" case, where it makes sense to not leave any tiny change output.

Another approach we could take it to keep things as is in this PR and introduce a new autopilot flag that ensures a tiny anchor output is created for the purpose of bumping fees. We'd then tune the autopilot allocation to leave X% for the "fee purse" and use that when bumping.

**Comment by halseth** [comment]
Squashed.

File: fundingmanager.go [hunk 38]
```diff
@@ -2801,6 +2802,12 @@ func (f *fundingManager) handleInitFundingMsg(msg *initFundingMsg) {
 		return
 	}
 
+	// Now that we have successfully reserved funds for this channel in the
+	// wallet, we can fetch the final channel capacity. This is done at
+	// this point since the final capacity might change in case of
+	// fundAll=true.
```
Comment (cfromknecht) [inline fundingmanager.go]: fundAll -> subtractFees?

File: lnwallet/wallet.go (hunk 30 above)
Comment (cfromknecht) [reply lnwallet/wallet.go]: agree on making this check configurable! however i don't think a percentage makes much sense here, since the fees paid are independent of the amount being sent. 20% might make sense for $1 channel, but not a $100 or $1000. perhaps this is better expressed as a max fee rate?

File: lnwallet/wallet.go [hunk 39]
```diff
@@ -1291,52 +1330,93 @@ func (l *LightningWallet) selectCoinsAndChange(feeRate SatPerKWeight,
...
-	for i, coin := range selectedCoins {
-		outpoint := &coin.OutPoint
-		l.lockedOutPoints[*outpoint] = struct{}{}
-		l.LockOutpoint(*outpoint)
+	switch {
+	// In case this request want the fees subtracted from the local amount,
+	// we'll call the specialized method for that. This ensures that we
+	// won't deduct more that the specified balance from our wallet.
+	case subtractFees:
+		dustLimit := DefaultDustLimit()
```
Comment (cfromknecht) [inline lnwallet/wallet.go]: will this be accurate on ltc?

File: lnwallet/wallet.go [hunk 40]
```diff
@@ -1291,52 +1330,93 @@ func (l *LightningWallet) selectCoinsAndChange(feeRate SatPerKWeight,
...
+			feeRate, amt, dustLimit, coins,
+		)
+		if err != nil {
+			return nil, err
+		}
 
-		// Empty sig script, we'll actually sign if this reservation is
-		// queued up to be completed (the other side accepts).
-		contribution.Inputs[i] = wire.NewTxIn(outpoint, nil, nil)
+	// Ótherwise to a normal coin selection where we target a given funding
```
Comment (cfromknecht) [inline lnwallet/wallet.go]: to -> do

File: lnwallet/wallet.go [hunk 41]
```diff
@@ -1291,52 +1330,93 @@ func (l *LightningWallet) selectCoinsAndChange(feeRate SatPerKWeight,
...
 
-	return nil
+	// Lock the selected coins. These coins are now "reserved", this
+	// prevents concurrent funding requests from referring to and this
+	// double-spending the same set of coins.
+	inputs := make([]*wire.TxIn, len(selectedCoins))
+	for i, coin := range selectedCoins {
+		outpoint := &coin.OutPoint
+		l.lockedOutPoints[*outpoint] = struct{}{}
+		l.LockOutpoint(*outpoint)
```
Comment (cfromknecht) [inline lnwallet/wallet.go]: isn't this a little racey since two calls to this method can get the same utxos before locking them?

Comment (wpaulino) [reply lnwallet/wallet.go]: The `coinSelectMtx` being acquired throughout this method should prevent that, no?

Comment (cfromknecht) [reply lnwallet/wallet.go]: ahh cool missed that

File: lnwallet/wallet.go (hunk 30 above)
Comment (halseth) [reply lnwallet/wallet.go]: I added the check in the first place to avoid cases where a user would deposit say $5 into the wallet, and autopilot opened a channel where $3 went to fees. Setting a max fee rate in that scenario wouldn't help, since $3 fee might be okay if you are opening large channels.

We are targeting app users primarily here, so maybe we should discuss it in that context.

Comment (cfromknecht) [reply lnwallet/wallet.go]: > Setting a max fee rate in that scenario wouldn't help, since $3 fee might be okay if you are opening large channels.

Why doesn't it help? To me it seems more effective than setting a percentage, since we're directly limiting how much we allocate to fees rather than assuming people are okay paying higher fees simply because they have more money.

> We are targeting app users primarily here, so maybe we should discuss it in that context.

We should still be cognizant of non-app users of autopilot or developers using lnd+autopilot in their own applications, of which there are many on mainnet.

Comment (Roasbeef) [reply lnwallet/wallet.go]: > Why doesn't it help?

Because it's absolute. In that "deposit $5, but get $3" scenario, what max fee should be set there? As this example is denominated in fiat, one would also need to factor in the current exchange rate as well. Alternatively, we could have "fee bands", kinda like a piece-wise function to decide what the proper % limit should be given the channel size. So for a 30k satoshi channel, 10k satoshis may be unacceptable as a total fee, while for a 300k satoshi channel 10k satoshis isn't so bad.

Comment (cfromknecht) [reply lnwallet/wallet.go]: > Because it's absolute.

Not sure I follow, aren't both absolute? One is don't go above this %, the other is don't go above this sat/byte.

In that "deposit $5, but get $3" scenario, what max fee should be set there? As this example is denominated in fiat, one would also need to factor in the current exchange rate as well.

Was thinking that a user would just tell autopilot to never use more than, e.g., 5 sat/byte for funding. Exchange rates wouldn't come into play at all

> Alternatively, we could have "fee bands", kinda like a piece-wise function to decide what the proper % limit should be given the channel size. So for a 30k satoshi channel, 10k satoshis may be unacceptable as a total fee, while for a 300k satoshi channel 10k satoshis isn't so bad.

To me it'd be less intuitive to specify a number of satoshis, because then you have to convert into dollar amounts. When people see a fee rate, they now roughly know the difference between a good and a bad sat/byte value. Perhaps fee rate bands? :)

Comment (halseth) [reply lnwallet/wallet.go]: I don't think this question has a "right" answer, and should be getting more discussion, at least before we start implementing a more complex heuristic.

I'm okay just removing this sanity check for now, even though app users might end up paying high percentage wise fees for opening channels (earlier we had this capped as a result of targeting 95% autopilot allocation in the app, which would leave only 5% to fees). Or just set it at 50% or something, with a TODO of improving it.

File: lnwallet/wallet_test.go [hunk 42]
```diff
@@ -0,0 +1,180 @@
...
+	"testing"
+
+	"github.com/btcsuite/btcutil"
+	"github.com/lightningnetwork/lnd/input"
+)
+
+// fee is a helper method that returns the fee estimate used for a tx with the
+// given number of inputs and the optional change output. This matches the
+// estimate done by the wallet.
+func fee(feeRate SatPerKWeight, numInput int, change bool) btcutil.Amount {
```
[the remark this answers is not in the document]
Comment (halseth) [reply lnwallet/wallet_test.go]: fixed: 9d1404bfb1ad02dcb72d4e65af514283dae7d05a

File: lnwallet/wallet.go (hunk 40 above)
Comment (halseth) [reply lnwallet/wallet.go]: Fixed: https://github.com/lightningnetwork/lnd/pull/3165/commits/e74c13c935052638fff291b4e60c779e05935a36

File: lnwallet/wallet.go (hunk 39 above)
Comment (halseth) [reply lnwallet/wallet.go]: No. Changed to using `DefaultConstraints.DustLimit` instead, which is properly set also for LTC: :https://github.com/lightningnetwork/lnd/pull/3165/commits/a1e826d721bcf799d52490bc7633e775ead073dd

It is a bit hacky since the constraints are really meant for commitment outputs, but I guess we can assume that dustlimit and the regular tx dustlimit is the same (they are currently)-

File: fundingmanager.go (hunk 38 above)
Comment (halseth) [reply fundingmanager.go]: Fixed: https://github.com/lightningnetwork/lnd/pull/3165/commits/c04ce8727f5c2a4ddaf42fca89db31fd374b5c2b

File: lnwallet/wallet.go (hunk 30 above)
Comment (cfromknecht) [reply lnwallet/wallet.go]: @halseth sounds good to me, in that case i'd just leave the 20% heuristic with a todo

Comment (halseth) [reply lnwallet/wallet.go]: TODO added
