### PR TITLE
rpcserver: prevent overflow in channel count

### LINKED ISSUE #2552: lncli getinfo showing 4294967295 num_inactive_channels
### Background

Closing some channels, opening some. Force close 15+. Was doing maintenance! Then I ran getinfo and saw something weird.

### Your environment

* version of `lnd`: `0.5.1-beta commit=v0.5.1-beta-256-089d461552ffc05d7b1c22d603af0fa82e788e85`
* which operating system (`uname -a` on *Nix): `3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64`
* version of `btcd`, `bitcoind`, or other backend - `bitcoind 0.17.1`
* any other relevant environment details

### Steps to reproduce

Run lncli getinfo...

### Expected behaviour

0 inactive channels, as I closed all inactive (which was not what I wanted to do but happened any way). **In listchannels there were 0 inactive channels**.

### Actual behaviour
```{
       "version": "0.5.1-beta commit=v0.5.1-beta-256-g089d461552ffc05d7b1c22d603af0fa82e788e85",
       "identity_pubkey": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
       "alias": "MiltonPusser.lightningnode.eu",
       "num_pending_channels": 2,
       "num_active_channels": 109,
       "num_inactive_channels": 4294967295,
       "num_peers": 132,
       "block_height": 560488,
       "block_hash": "00000000000000000016bd943367e0941bf42605145c89ca031bb32e6ae10dae",
       "best_header_timestamp": 1548685935,
       "synced_to_chain": true,
       "testnet": false,
       "chains": [
               "bitcoin"
       ],
       "uris": [
               "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b@82.197.218.97:9735"
       ]
```

### PR DESCRIPTION
**Pull request by MDrollette**
This fixes #2552 using the solution suggested by @cfromknecht here https://github.com/lightningnetwork/lnd/issues/2552#issuecomment-459597592

### CODE REVIEW

File: rpcserver.go [hunk 1]
```diff
@@ -1779,17 +1779,22 @@ func (r *rpcServer) fetchActiveChannel(chanPoint wire.OutPoint) (
...
-	}
 
-	openChannels, err := r.server.chanDB.FetchAllOpenChannels()
+	channels, err := r.server.chanDB.FetchAllOpenChannels()
 	if err != nil {
 		return nil, err
 	}
-	inactiveChannels := uint32(len(openChannels)) - activeChannels
+
+	var nActiveChannels uint32
```
Comment (Roasbeef) [inline rpcserver.go]: No need to prefix any of the variable names. We don't use any sort of prefix/suffix naming conventions within the codebase.
