### PR TITLE
multi: share the same bitcoind connection between multiple rescan clients

### LINKED ISSUE #1174: Possibly missing updates from Bitcoind backend
### Background

I have 9 lnd's sharing a single Bitcoind backend on a single server.  I didn't open a channel with any of them in order to see this issue.  I funded the first address generated from each lnd's wallet with some satoshis(which confirmed), and destroyed each lnd.  Then, I restored each using the seed phrase, with multiple re-synchronizing from Bitcoind at once.  Some of them (it seems the first ones to get a connection to Bitcoind) restored fine, with funds in their wallet.  Others (the later ones to connect) seemed to miss their funding transactions.  The address look-ahead window should have caught the funding transactions, as the addresses I sent to were the first generated addresses for each seed.

### Your environment

* version of `lnd` = `0.4.1-beta commit=09c997983127bb1e575d97c69aa364a82cfb1df7`
* which operating system (`uname -a` on *Nix) = `Linux provingapoint 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend = `Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255`
* any other relevant environment details = `All running in Docker containers, which probably exacerbated the connectivity issues.`

I've confirmed the wallet starts recovery without issue:
```
2018-05-03 05:18:07.589 [WRN] LTND: open /root/.lnd/lnd.conf: no such file or directory
2018-05-03 05:18:07.589 [INF] LTND: Version 0.4.1-beta commit=09c997983127bb1e575d97c69aa364a82cfb1df7
2018-05-03 05:18:07.589 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-05-03 05:18:07.592 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2018-05-03 05:18:07.593 [INF] RPCS: Generating TLS certificates...
2018-05-03 05:18:07.616 [INF] RPCS: Done generating TLS certificates
2018-05-03 05:18:07.623 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-05-03 05:18:07.624 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2018-05-03 05:18:07.624 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create wallet, or `lncli unlock` to unlock already created wallet.
2018-05-03 05:18:50.518 [INF] LNWL: Opened wallet
2018-05-03 05:18:50.519 [INF] LTND: Wallet recovery mode enabled with address lookahead of 250 addresses
2018-05-03 05:18:50.614 [INF] LTND: Primary chain is set to: bitcoin
2018-05-03 05:18:50.614 [INF] LTND: Initializing bitcoind backed fee estimator
2018-05-03 05:18:51.939 [INF] LNWL: Opened wallet
2018-05-03 05:18:51.944 [INF] LNWL: Started listening for blocks via ZMQ on tcp://bitcoind:29000
2018-05-03 05:18:53.281 [INF] LNWL: The wallet has been unlocked without a time limit
2018-05-03 05:18:53.283 [INF] LNWL: Catching up block hashes to height 520983, this will take a while...
2018-05-03 05:18:53.285 [INF] LTND: LightningWallet opened
2018-05-03 05:18:53.286 [INF] LNWL: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=250
2018-05-03 05:18:53.292 [INF] LNWL: Caught up to height 0
```

### Steps to reproduce

Connect multiple lnds to a single Bitcoind backend+ZMQ, and restore them from some seeds with confirmed funds to an address derived from the seed.

Alternatively, I think if you drop some crucial packets on ZMQ you'll see similar results.

### Expected behaviour

LND is aware when it's missing crucial information from its backend, and it recovers from data connectivity issues gracefully.

### Actual behaviour

Connectivity issues with the Bitcoind backend appear to "trick" LND into the wrong state with regards to funding and possibly seeing crucial transactions.

### PR DESCRIPTION
**Pull request by wpaulino**
In this PR, we introduce a nice optimization with regards to `lnd`'s interaction with a `bitcoind` backend. Within `lnd`, we currently have three different subsystems responsible for watching the chain: `chainntnfs`, `lnwallet`, and `routing/chainview`. Each of these subsystems has an active RPC and ZMQ connection to the underlying `bitcoind` node. This would incur a toll on the underlying `bitcoind` node and would cause us to miss ZMQ events, which are crucial to `lnd`. We remedy this issue by sharing the same connection to a `bitcoind` node between the different clients within `lnd`.

We now also require the backing `bitcoind` node to use different hosts to provide its ZMQ raw block and raw transaction notifications (`zmqpubrawblock` and `zmqpubrawtx`). This was needed as the notification queue maintained by the `bitcoind` node would sometimes overflow with transactions and would cause block notifications to be dropped/missed.

Depends on https://github.com/btcsuite/btcwallet/pull/511.
Fixes #1174.

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -133,11 +133,12 @@ type btcdConfig struct {
...
-	RPCHost string `long:"rpchost" description:"The daemon's rpc listening address. If a port is omitted, then the default port for the selected chain parameters will be used."`
-	RPCUser string `long:"rpcuser" description:"Username for RPC connections"`
-	RPCPass string `long:"rpcpass" default-mask:"-" description:"Password for RPC connections"`
-	ZMQPath string `long:"zmqpath" description:"The path to the ZMQ socket providing at least raw blocks. Raw transactions can be handled as well."`
+	Dir          string `long:"dir" description:"The base directory that contains the node's data, logs, configuration file, etc."`
+	RPCHost      string `long:"rpchost" description:"The daemon's rpc listening address. If a port is omitted, then the default port for the selected chain parameters will be used."`
+	RPCUser      string `long:"rpcuser" description:"Username for RPC connections"`
+	RPCPass      string `long:"rpcpass" default-mask:"-" description:"Password for RPC connections"`
+	ZMQBlockHost string `long:"zmqblockhost" description:"The ZMQ host providing raw block notifications"`
+	ZMQTxHost    string `long:"zmqtxhost" description:"The ZMQ host providing raw transaction notifications"`
```
Comment (halseth) [inline config.go]: Does it make sense to call these `zmqpubrawtx` and `zmqpubrawblock`?

File: routing/chainview/interface_test.go [hunk 2]
```diff
@@ -20,11 +20,12 @@ import (
...
 	"github.com/btcsuite/btcutil"
-	"github.com/lightninglabs/neutrino"
-	"github.com/ltcsuite/ltcd/btcjson"
-
+	"github.com/btcsuite/btcwallet/chain"
 	"github.com/btcsuite/btcwallet/walletdb"
 	_ "github.com/btcsuite/btcwallet/walletdb/bdb" // Required to register the boltdb walletdb implementation.
+
+	"github.com/lightninglabs/neutrino"
+	"github.com/ltcsuite/ltcd/btcjson"
```
Comment (halseth) [inline routing/chainview/interface_test.go]: guess this should be `btcd`, really

**Comment by Roasbeef** [comment]
The dependent `btcwallet` PR has been merged now, so this needs a rebase! You may want to wait until after #1579 is in however.

File: lnwallet/interface_test.go [hunk 3]
```diff
@@ -2173,21 +2171,27 @@ func runTests(t *testing.T, walletDriver *lnwallet.WalletDriver,
...
 			defer bitcoind.Process.Kill()
 
-			// Start an Alice btcwallet bitcoind back end instance.
-			aliceClient, err = chain.NewBitcoindClient(netParams,
-				fmt.Sprintf("127.0.0.1:%d", rpcPort), "weks",
-				"weks", zmqPath, 100*time.Millisecond)
-			if err != nil {
-				t.Fatalf("couldn't start alice client: %v", err)
-			}
+			time.Sleep(time.Second)
```
Comment (Roasbeef) [inline lnwallet/interface_test.go]: Why's this sleep necessary now?

Comment (wpaulino) [reply lnwallet/interface_test.go]: To ensure bitcoind has started before we attempt to connect to it.

**Comment by Roasbeef** [comment]
Needs rebase.

**Comment by githorray** [comment]
Typo in the docs?

`lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=REPLACEME --bitcoind.rpcpass=REPLACEME --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28333 --externalip=X.X.X.X`

Results in:

`unable to load RPC credentials for bitcoind: please set all or none of bitcoind.rpcuser, bitcoind.rpcpass, bitcoind.zmqpubrawblock, bitcoind.zmqpubrawtx`

**Comment by wpaulino** [comment]
Whoops, yeah the second should be `--bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333 `.

**Comment by githorray** [comment]
Also, `[INF] LNWL: Started listening for blocks via ZMQ on` never appears in the log after the update and LND keeps losing chain sync. I am still trying to track that one down.

**Comment by bretton** [comment]
So now bitcoin.conf must set different ports for zmq as follows
```
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
```

lnd.conf used to have

```
bitcoind.zmqpath=tcp://127.0.0.1:28332
```

however now it must have

```
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
```
??? 

but the sample lnd.conf file is incorrect?

https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf

; bitcoind.zmqblockhost=tcp://127.0.0.1:28332
; bitcoind.zmqtxhost=tcp://127.0.0.1:28333

can submit PR if needed?

**Comment by wpaulino** [comment]
See #1717.
