### PR TITLE
contractcourt: fix off-by-one error in closeObserver

### LINKED ISSUE #2764: possible off-by-one error in chain watcher DLP detection
### Background

I am running an LND node which I periodically backup by copying the data directory. I am aware that running a node with such backup may cause problems and indeed in cases the backup was executed in the middle of a payment I am experiencing data loss on channel re-establishment.
From my experience these "data loss" detections ended up in force close by remote peer and my node was able to sweep the funds to its wallet.
Last time I had a different behavior when the channel was forced closed by remote node and my local node wasn't able to sweep the funds.

**The line in the log that indicates the dataloss is this:**

2019-03-05 12:47:03.936 [ERR] LNWL: ChannelPoint(23c663b0503bef526b4fe5e8725bfd60cb423335155bc0b8330db046abe4ddb4:1), sync failed with local data loss: remote believes our tail height is 112, while we have 111!

**I also see that the spent was detected by these lines:**

2019-03-13 00:17:31.918 [DBG] BTCN: UTXO 23c663b0503bef526b4fe5e8725bfd60cb423335155bc0b8330db046abe4ddb4:1 spent by txn 6bd85de02091aafe54a905be8965b25f02b2f6757fe5ebfe9219afdb23496e14
2019-03-13 00:17:31.918 [DBG] BTCN: Fetching filter for height=565766, hash=000000000000000000235ecc744a68e15d20ce4121a76305c3d8fa88620bf426
2019-03-13 00:17:31.919 [DBG] BTCN: Sending getcfilters to 91.134.145.202:8333 (outbound)
2019-03-13 00:17:31.930 [INF] NTFN: Dispatching spend notification for outpoint=23c663b0503bef526b4fe5e8725bfd60cb423335155bc0b8330db046abe4ddb4:1 at height=566801
2019-03-13 00:17:31.930 [INF] CNCT: Close observer for ChannelPoint(23c663b0503bef526b4fe5e8725bfd60cb423335155bc0b8330db046abe4ddb4:1) active
2019-03-13 00:17:31.930 [INF] CNCT: ChannelArbitrator(c210c29c1feb5fa9d22a9df33d085900de714888aa3b597878471e3986a93627:1): starting state=StateDefault
2019-03-13 00:17:31.930 [INF] CNCT: ChannelArbitrator(23c663b0503bef526b4fe5e8725bfd60cb423335155bc0b8330db046abe4ddb4:1): starting state=StateDefault
2019-03-13 00:17:31.930 [WRN] CNCT: Unprompted commitment broadcast for ChannelPoint(23c663b0503bef526b4fe5e8725bfd60cb423335155bc0b8330db046abe4ddb4:1) 

Made some research and saw that, even though the spend is detected, there is no handling in the code for my case.
More specific in the closeObserver the program reaches this line: https://github.com/lightningnetwork/lnd/blob/master/contractcourt/chain_watcher.go#L369

The relevant local variables in my case are set to the following:
broadcastStateNum = 112
remoteStateNum = 111
remoteChainTip = nil

As you can see there is no "case" that matches this state therefore the switch block ends up with doing nothing and doesn't dispatch any close transaction.
 
I wonder if in my case the code should run this block: https://github.com/lightningnetwork/lnd/blob/master/contractcourt/chain_watcher.go#L409

Hope the info above will help to improve this case.

### Your environment

* LND 0.5.2

### Expected behavior
I would expect that in the case of data loss an attempt to sweep the funds will be done.
I am opening this issue  because I see that for some cases this attempt is done and since this specific case is somehow skipped maybe observing it will help improve this flow.

### Actual behavior
Channel stays pending forever, funds are not swept.

### PR DESCRIPTION
**Pull request by Roasbeef**
In this PR, we fix an off-by-one error when handling force closes from the remote party. Before this commit, if the remote party broadcasts state 2, and we were on state 1, then we wouldn't act at all. This is due to an extraneous +1 in the comparison, causing us to only detect this DLP case if the remote party's state is two beyond what we know atm. A test that fails when run on master has been added to demonstrate the bug, and confirm that it has been fixed. 

Fixes #2764.

### CODE REVIEW

File: contractcourt/chain_watcher.go [hunk 1]
```diff
@@ -410,7 +410,7 @@ func (c *chainWatcher) closeObserver(spendNtfn *chainntnfs.SpendEvent) {
 		// actually greater than even one beyond our best known state
 		// number. This should ONLY happen in case we experienced some
 		// sort of data loss.
-		case broadcastStateNum > remoteStateNum+1:
+		case broadcastStateNum > remoteStateNum:
```
Comment (halseth) [inline contractcourt/chain_watcher.go]: Comments here and for the above case should be updated to reflect and describe the change. Would also be beneficial to comment on why the `+1` is not caught by the above case.

File: contractcourt/chain_watcher_test.go [hunk 2]
```diff
@@ -213,3 +223,154 @@ func TestChainWatcherRemoteUnilateralClosePendingCommit(t *testing.T) {
 		t.Fatalf("unable to find alice's commit resolution")
 	}
 }
+
+// TestChainWatcherDataLossProtect tests that if we've lost data (and are
+// behind the remote node), then we'll properly detect this case and dispatch a
+// remote force close using the obtained data loss commitment point.
+func TestChainWatcherDataLossProtect(t *testing.T) {
```
Comment (halseth) [inline contractcourt/chain_watcher_test.go]: nit: test case commit should be added after fix commit, to strive for commit history build passing.

File: contractcourt/chain_watcher_test.go [hunk 3]
```diff
@@ -213,3 +223,154 @@ func TestChainWatcherRemoteUnilateralClosePendingCommit(t *testing.T) {
...
+		// Otherwise, we'll feed in this new state number as a response
+		// to the query, and insert the expected DLP commit point.
+		dlpPoint := aliceChannel.State().IdentityPub
+		err = aliceChannel.State().MarkDataLoss(dlpPoint)
+		if err != nil {
+			t.Errorf("unable to insert dlp point: %v", err)
+			return false
+		}
+
+		// Now we'll trigger the channel close even to trigger the
```
Comment (halseth) [inline contractcourt/chain_watcher_test.go]: s/even/event

File: contractcourt/chain_watcher_test.go [hunk 4]
```diff
@@ -213,3 +223,154 @@ func TestChainWatcherRemoteUnilateralClosePendingCommit(t *testing.T) {
...
+	// DLP protocol on our end.
+	//
+	// broadcastStateNum is the number that we'll trick Alice into thinking
+	// was broadcast, while numUpdates is the actual number of updates
+	// we'll execute. Both of these will be random 8-bit values generated
+	// by testing/quick.
+	dlpScenario := func(broadcastStateNum, numUpdates uint8) bool {
+		// If the random state num is less than our current state num,
+		// then this case will pass as we only care about the DLP case.
+		if broadcastStateNum <= numUpdates {
```
Comment (halseth) [inline contractcourt/chain_watcher_test.go]: What we could instead to is to define a new `type dlp struct { broadcastStateNum, numUpdates uint8}`, then define a `Generate` method that ensures `broadcastStateNum > numUpdates`. I think that way we get more out of our limited number of test iterations :)

File: contractcourt/chain_watcher_test.go [hunk 5]
```diff
@@ -213,3 +223,154 @@ func TestChainWatcherRemoteUnilateralClosePendingCommit(t *testing.T) {
...
+		}
+
+		// We'll request a new channel event subscription from Alice's
+		// chain watcher so we can be notified of our fake close below.
+		chanEvents := aliceChainWatcher.SubscribeChannelEvents()
+
+		// Now that we have our updates in place, we'll feed Alice a
+		// random state number. If this is beyond her best known state
+		// for Bob, then she should enter the DLP protocol.
+		stateNumChan <- uint64(broadcastStateNum)
```
Comment (halseth) [inline contractcourt/chain_watcher_test.go]: Why does this have to be sent on a channel? Can't we just make `extractStateNumHint` return `broadcastStateNum`?

File: contractcourt/chain_watcher_test.go [hunk 6]
```diff
@@ -213,3 +223,154 @@ func TestChainWatcherRemoteUnilateralClosePendingCommit(t *testing.T) {
...
+		// We should get a new uni close resolution that indicates we
+		// processed the DLP scenario.
+		var uniClose *lnwallet.UnilateralCloseSummary
+		select {
+		case uniClose = <-chanEvents.RemoteUnilateralClosure:
+			// If we processed this as a DLP case, then the remote
+			// party's commitment should be blank, as we don't have
+			// this up to date state.
+			blankCommit := channeldb.ChannelCommitment{}
+			if uniClose.RemoteCommit.FeePerKw != blankCommit.FeePerKw {
```
Comment (halseth) [inline contractcourt/chain_watcher_test.go]: also check that the commitPoint/contractResolution is properly populated to sweep our output

**Comment by roeierez** [comment]
@Roasbeef following conversation in slack, I applied this fix to my node that had this issue (funds were not swept) and I **confirm** that now after restarting the funds were swept correctly.
Will wait for this to be merged but regardless of that the fast response and quick solution are very appreciated here.

File: contractcourt/chain_watcher_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (Roasbeef) [reply contractcourt/chain_watcher_test.go]: We test the equal case in another test in this file, and the less than case is covered by the existing breach tests.

**Comment by Roasbeef** [comment]
PTAL @halseth @cfromknecht

File: contractcourt/chain_watcher_test.go (hunk 6 above)
Comment (Roasbeef) [reply contractcourt/chain_watcher_test.go]: Proper population of the entire uni close resolution is already tested within the `lnwallet` package. Added a clause here to ensure that it uses the fake commit point we passed in to derive their final sweeping keys.

File: contractcourt/chain_watcher_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (cfromknecht) [reply contractcourt/chain_watcher_test.go]: sgtm

**Comment by MykelSIlver** [comment]
I am not very common with github. Are there any binaries available for this fix branch? Or is the only solution to build this fix from source? Thank you

**Comment by halseth** [comment]
@MykelSIlver currently only from source. But the v0.6 release is just around the corner 🤞

**Comment by MykelSIlver** [comment]
updated to version: lnd version 0.6.0-beta commit=v0.6-beta-rc4
Unfortunately channels still pending at version?
Should a new issue report be made?

after starting the lnd daemon and finishing its startup pending channels gives still:

```
{
    "total_limbo_balance": "44948535",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
        {
            "channel": {
                "remote_node_pub": "03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601",
                "channel_point": "cf91a4e77e81cdec69eb2fa94f8d15a4235cf60de06380a2aec4b743abd99091:1",
                "capacity": "250000",
                "local_balance": "2803",
                "remote_balance": "0"
            },
            "closing_txid": "5a4d2eb780c0c4d3b07d9de57ed47411eed7bd9bfc65abc2fd59e747075a5a89",
            "limbo_balance": "2803",
            "maturity_height": 566904,
            "blocks_til_maturity": -4391,
            "recovered_balance": "0",
            "pending_htlcs": [
            ]
        }
    ],
    "waiting_close_channels": [
        {
            "channel": {
                "remote_node_pub": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266",
                "channel_point": "b8e7a58656a00b85280a97a87e7f5455392dedefc7bb3089813d90b971ff9473:1",
                "capacity": "10000000",
                "local_balance": "9994349",
                "remote_balance": "0"
            },
            "limbo_balance": "9994349"
        },
        {
            "channel": {
                "remote_node_pub": "023f61eb4abd39ee37190fcaf6343050b0b70da647960f9a95e9974cebc4fffd47",
                "channel_point": "b06ad896e955ab3fd92a870eafdac61ab300226492edcc800be2c27626778211:0",
                "capacity": "16777215",
                "local_balance": "16770786",
                "remote_balance": "0"
            },
            "limbo_balance": "16770786"
        },
        {
            "channel": {
                "remote_node_pub": "02a35e94b403dead4d08a00e3df3577682e34f5c4ba39476497be838dc76d15a09",
                "channel_point": "a9c6512546094d3615587d1375459b516a43fa6f40aefb8d5e94211a1b998496:0",
                "capacity": "50000",
                "local_balance": "0",
                "remote_balance": "0"
            },
            "limbo_balance": "0"
        },
        {
            "channel": {
                "remote_node_pub": "0317d6b11e81729192aab651174991a32e566786a7abb45b88898ed27e218a15e6",
                "channel_point": "f3665b0c3c07cc0946f0eb37cf40e595f3deaac34c4bd7c6f1f4b1929880db08:0",
                "capacity": "1500000",
                "local_balance": "1319575",
                "remote_balance": "0"
            },
            "limbo_balance": "1319575"
        },
        {
            "channel": {
                "remote_node_pub": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
                "channel_point": "4be8b1fd780739f20901d6bb0a6f3e17510026efbcf6b62f051463fa32dcb312:0",
                "capacity": "100000",
                "local_balance": "89777",
                "remote_balance": "0"
            },
            "limbo_balance": "89777"
        },
        {
            "channel": {
                "remote_node_pub": "03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56",
                "channel_point": "ca59f20c8a371678c4e2abaab4fbc0123e864cb2d39c0391c12afb120174b9b3:0",
                "capacity": "16777215",
                "local_balance": "16771245",
                "remote_balance": "0"
            },
            "limbo_balance": "16771245"
        }
    ]
}

```

Studying the lnd.log filtered for the pending channels gives:
```
2019-04-12 08:26:20.194 [INF] LTND: Version: 0.6.0-beta commit=v0.6-beta-rc4, build=production, logging=default
2019-04-12 08:26:20.194 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-04-12 08:26:20.208 [INF] CHDB: Checking for schema update: latest_version=8, db_version=7
2019-04-12 08:26:20.209 [INF] CHDB: Performing database schema migration
2019-04-12 08:26:20.209 [INF] CHDB: Applying migration #8
2019-04-12 08:26:20.209 [INF] CHDB: Migrating to the gossip message store new key format
2019-04-12 08:26:20.209 [INF] CHDB: Migration to the gossip message store new key format complete!

2019-04-12 08:26:53.918 [INF] SWPR: Candidate sweep set of size=1, has yield=0.09988237 BTC
2019-04-12 08:26:53.918 [INF] SWPR: Sweep candidates at height=571294, yield 1 distinct txns
2019-04-12 08:26:53.929 [INF] CNCT: Creating ChannelArbitrators for 1 closing channels
2019-04-12 08:26:53.929 [INF] NTFN: New block epoch subscription
2019-04-12 08:26:53.930 [INF] NTFN: New spend subscription: spend_id=8, outpoint=b06ad896e955ab3fd92a870eafdac61ab300226492edcc800be2c27626778211:0, height_hint=566232
2019-04-12 08:26:53.930 [INF] NTFN: New spend subscription: spend_id=5, outpoint=b8e7a58656a00b85280a97a87e7f5455392dedefc7bb3089813d90b971ff9473:1, height_hint=566232
2019-04-12 08:26:53.930 [INF] NTFN: New spend subscription: spend_id=6, outpoint=4be8b1fd780739f20901d6bb0a6f3e17510026efbcf6b62f051463fa32dcb312:0, height_hint=566233
2019-04-12 08:26:53.930 [INF] NTFN: New spend subscription: spend_id=4, outpoint=f3665b0c3c07cc0946f0eb37cf40e595f3deaac34c4bd7c6f1f4b1929880db08:0, height_hint=566232
2019-04-12 08:26:53.930 [INF] NTFN: New spend subscription: spend_id=7, outpoint=ca59f20c8a371678c4e2abaab4fbc0123e864cb2d39c0391c12afb120174b9b3:0, height_hint=566232
2019-04-12 08:26:53.930 [INF] NTFN: New spend subscription: spend_id=3, outpoint=a9c6512546094d3615587d1375459b516a43fa6f40aefb8d5e94211a1b998496:0, height_hint=566572
2019-04-12 08:26:54.084 [INF] CNCT: Close observer for ChannelPoint(b06ad896e955ab3fd92a870eafdac61ab300226492edcc800be2c27626778211:0) active
2019-04-12 08:26:54.192 [INF] CNCT: Close observer for ChannelPoint(b8e7a58656a00b85280a97a87e7f5455392dedefc7bb3089813d90b971ff9473:1) active
2019-04-12 08:26:54.303 [INF] CNCT: Close observer for ChannelPoint(4be8b1fd780739f20901d6bb0a6f3e17510026efbcf6b62f051463fa32dcb312:0) active
2019-04-12 08:26:54.412 [INF] CNCT: Close observer for ChannelPoint(f3665b0c3c07cc0946f0eb37cf40e595f3deaac34c4bd7c6f1f4b1929880db08:0) active
2019-04-12 08:26:54.521 [INF] CNCT: Close observer for ChannelPoint(ca59f20c8a371678c4e2abaab4fbc0123e864cb2d39c0391c12afb120174b9b3:0) active
2019-04-12 08:26:54.635 [INF] CNCT: Close observer for ChannelPoint(a9c6512546094d3615587d1375459b516a43fa6f40aefb8d5e94211a1b998496:0) active
2019-04-12 08:26:54.636 [INF] CNCT: ChannelArbitrator(ca59f20c8a371678c4e2abaab4fbc0123e864cb2d39c0391c12afb120174b9b3:0): starting state=StateCommitmentBroadcasted
2019-04-12 08:26:54.924 [INF] CNCT: ChannelArbitrator(ca59f20c8a371678c4e2abaab4fbc0123e864cb2d39c0391c12afb120174b9b3:0): noop trigger chainTrigger
2019-04-12 08:26:54.926 [INF] CNCT: ChannelArbitrator(cf91a4e77e81cdec69eb2fa94f8d15a4235cf60de06380a2aec4b743abd99091:1): starting state=StateWaitingFullResolution
2019-04-12 08:26:54.972 [INF] CNCT: ChannelArbitrator(cf91a4e77e81cdec69eb2fa94f8d15a4235cf60de06380a2aec4b743abd99091:1): still awaiting contract resolution
2019-04-12 08:26:54.972 [INF] CNCT: ChannelArbitrator(cf91a4e77e81cdec69eb2fa94f8d15a4235cf60de06380a2aec4b743abd99091:1): relaunching 1 contract resolvers
2019-04-12 08:26:54.972 [INF] NTFN: New confirmation subscription: txid=5a4d2eb780c0c4d3b07d9de57ed47411eed7bd9bfc65abc2fd59e747075a5a89, num_confs=1
2019-04-12 08:26:54.972 [INF] CNCT: ChannelArbitrator(b8e7a58656a00b85280a97a87e7f5455392dedefc7bb3089813d90b971ff9473:1): starting state=StateCommitmentBroadcasted
2019-04-12 08:26:54.972 [INF] NTFN: New confirmation subscription: conf_id=1, txid=5a4d2eb780c0c4d3b07d9de57ed47411eed7bd9bfc65abc2fd59e747075a5a89, height_hint=566760
2019-04-12 08:26:55.285 [INF] CNCT: ChannelArbitrator(b8e7a58656a00b85280a97a87e7f5455392dedefc7bb3089813d90b971ff9473:1): noop trigger chainTrigger
2019-04-12 08:26:55.287 [INF] CNCT: ChannelArbitrator(b06ad896e955ab3fd92a870eafdac61ab300226492edcc800be2c27626778211:0): starting state=StateCommitmentBroadcasted
2019-04-12 08:26:55.300 [INF] CNCT: ChannelArbitrator(b06ad896e955ab3fd92a870eafdac61ab300226492edcc800be2c27626778211:0): noop trigger chainTrigger
2019-04-12 08:26:55.300 [INF] CNCT: ChannelArbitrator(a9c6512546094d3615587d1375459b516a43fa6f40aefb8d5e94211a1b998496:0): starting state=StateCommitmentBroadcasted
2019-04-12 08:26:55.338 [INF] NTFN: Dispatching 1 confirmation notification for txid=5a4d2eb780c0c4d3b07d9de57ed47411eed7bd9bfc65abc2fd59e747075a5a89
2019-04-12 08:26:55.338 [INF] NTFN: New spend subscription: spend_id=9, outpoint=5a4d2eb780c0c4d3b07d9de57ed47411eed7bd9bfc65abc2fd59e747075a5a89:0, height_hint=571294
2019-04-12 08:26:55.338 [INF] CNCT: *contractcourt.commitSweepResolver(cf91a4e77e81cdec69eb2fa94f8d15a4235cf60de06380a2aec4b743abd99091:1): waiting for commit output to be swept
2019-04-12 08:26:55.576 [INF] CNCT: ChannelArbitrator(a9c6512546094d3615587d1375459b516a43fa6f40aefb8d5e94211a1b998496:0): noop trigger chainTrigger
2019-04-12 08:26:55.578 [INF] CNCT: ChannelArbitrator(f3665b0c3c07cc0946f0eb37cf40e595f3deaac34c4bd7c6f1f4b1929880db08:0): starting state=StateCommitmentBroadcasted
2019-04-12 08:26:55.856 [INF] CNCT: ChannelArbitrator(f3665b0c3c07cc0946f0eb37cf40e595f3deaac34c4bd7c6f1f4b1929880db08:0): noop trigger chainTrigger
2019-04-12 08:26:55.858 [INF] CNCT: ChannelArbitrator(4be8b1fd780739f20901d6bb0a6f3e17510026efbcf6b62f051463fa32dcb312:0): starting state=StateCommitmentBroadcasted
2019-04-12 08:26:56.102 [INF] CNCT: ChannelArbitrator(4be8b1fd780739f20901d6bb0a6f3e17510026efbcf6b62f051463fa32dcb312:0): noop trigger chainTrigger

```

**Comment by MykelSIlver** [comment]
> @MykelSIlver currently only from source. But the v0.6 release is just around the corner
lnd version 0.6.0-beta commit=v0.6-beta-rc4 did indeed solve the problem :+1:
