### PR TITLE
multi: allow min-depth of zero for non-zero conf channels

### LINKED ISSUE #8783: [bug]: Channels without zero-conf feature but `minimum_depth` 0 are rejected
### Background

As per BOLT 2, a node receiving `open_channel` can communicate the number of confirmations of the funding transaction it deems reasonable via [`accept_channel`](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#the-accept_channel-message)'s `minimum_depth` field:

```
if channel_type includes option_zeroconf:

    MUST set minimum_depth to zero.

otherwise:

    SHOULD set minimum_depth to a number of blocks it considers reasonable to avoid double-spending of the funding transaction.
```

However, LND currently does not only check that `minimum_depth` is `0` if the zero conf. feature is set, but also *that `minimum_depth` is non-zero otherwise*.

In particular, it rejects any channel without the feature that sets `minimum_depth` to 0:

https://github.com/lightningnetwork/lnd/blob/bc6292f8bd37ddcb4283e79418861be37a36a618/funding/manager.go#L2023-L2030

Unfortunately, this means LND is currently unnecessarily failing channel opens *on a more permissive counterparty limit*.

LDK currently does *not* set the optional zero-conf feature bit, but just sets `minimum_depth` to zero in `accept_channel` via a specific [API method](https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelManager.html#method.accept_inbound_channel_from_trusted_peer_0conf) via which users can opt into trusting the counterparty for 0conf. However, if we now do this on a per-peer basis and the LND counterparty tries to open a *non-zero conf* channel to us, it will always be rejected due to `non-zero-conf channel has min depth zero`. 

That is, due to this arbitrary restriction, users will have to know beforehand whether the LND counterparty will open a zero-conf or non-zero-conf channel.

### Steps to reproduce

Try to open a non-zero-conf channel from LND to a LDK node that trusts its LND counterparty for zero-conf channels.

### Expected behaviour

The channel should be opened.

### Actual behaviour

The channel is unnecessarily rejected.

### PR DESCRIPTION
**Pull request by ellemouton**
~If our peer indicates to us that they are OK with a zero conf channel (ie, they trust us) by setting min-depth to 0 in accept_channel, then as long as they support SCID aliases, we should just upgrade the channel to ZeroConf and continue the funding flow.~

EDIT: updated to just allow the peer to set min-depth to 0. We dont upgrade the channel type.

Fixes #8783 

NOTE: we already allow ourselves to do this when our peer sends us an OpenChannel without a zero-conf channel type: https://github.com/lightningnetwork/lnd/blob/fed760913ff98a89c73414acde6cf29f8728321a/funding/manager.go#L1570-L1583

So all this PR does is allow our peer to do this too :)

### CODE REVIEW

File: channeldb/channel.go [hunk 1]
```diff
@@ -1346,6 +1346,41 @@ func (c *OpenChannel) MarkScidAliasNegotiated() error {
 	return nil
 }
 
+// MarkZeroConfNegotiated adds ZeroConfBit to ChanType in-memory and in the
+// database. If the channel does not yet exist in the database then only the
+// in-memory version is updated.
+func (c *OpenChannel) MarkZeroConfNegotiated() error {
```
Comment (ellemouton) [inline channeldb/channel.go:1352]: might not need the DB part... cause I think we would never persist before completing the processing of AcceptChannel right?

File: funding/manager.go [hunk 2]
```diff
@@ -2020,13 +2020,51 @@ func (f *Manager) funderProcessAcceptChannel(peer lnpeer.Peer,
...
+				"type to zero-conf: %w", err)
+			log.Warn(flowErr)
+			f.failFundingFlow(peer, cid, flowErr)
+
+			return
+		}
+
+		// Zero conf channels will require an SCID alias, so request one
+		// now and add it to the reservation.
+		aliasScid, err := f.cfg.AliasManager.RequestAlias()
```
Comment (Crypt-iQ) [inline funding/manager.go:2061]: 👍

**Comment by ellemouton** [comment]
hmmm ok from [this comment](https://github.com/lightningnetwork/lnd/issues/8783#issuecomment-2150840687) on the original issue, it sounds like we dont actually need to go and change this to a zero conf channel. We can just _allow_ them to send a min-depth of 0 (even though this is not a zero conf channel) and then we just continue as normal (and only send channel_ready when we see fit). 

so the diff can actually be way smaller 

cc @Crypt-iQ  - wdyt?

**Comment by Crypt-iQ** [comment]
> hmmm ok from [this comment](https://github.com/lightningnetwork/lnd/issues/8783#issuecomment-2150840687) on the original issue, it sounds like we dont actually need to go and change this to a zero conf channel. We can just _allow_ them to send a min-depth of 0 (even though this is not a zero conf channel) and then we just continue as normal (and only send channel_ready when we see fit).
> 
> so the diff can actually be way smaller
> 
> cc @Crypt-iQ - wdyt?

yup that seems fine

**Comment by ellemouton** [comment]
Ok I've made the update discussed above. 

It's hard to write a test for this case cause we dont really support this between two LND nodes opening a non-zero conf channel cause we want to register for confirmations and this is not allowed with a depth of 0. 

So to test this you can apply [this patch](https://github.com/user-attachments/files/15827109/testMinDepthZero.patch) which allows our channel acceptor to set a MinDepth of 0 & also makes sure we still register for 1 conf if we are on the receiver side of this operation. Then to actually test the flow, you can run the `scid_alias_channel_update/public_no-chan-type_update` test which uses the channel acceptor to open a _non_ zero conf channel

**Review by yyforyongyu — APPROVED** [review]
Needs a rebase, otherwise LGTM🌊

**Review by Crypt-iQ — APPROVED** [review]
