### PR TITLE
lnwallet: add commitment transaction sorting with CLTV tie breaker

### LINKED ISSUE #2234: Invalid commit sig
### Background

This is a continuation of https://github.com/lightningnetwork/lnd/issues/2232, once reconnected LND sends `update_add_htlc` and then a `commit_sig` which fails a check.

When looking at incoming messages BLW gets this:

```
<-- ChannelReestablish(64e13aeff81da767ab480c47af20bdde33e04e6598ee39ae6a853993fef561fb,69,43,Some(24e63bf3e8767bad763ecc2400597c2e0679f2f696176754b7b076051392a526),Some(02d0049cd3995412b622b976407fb7b5a7cfbe91ff068cbdc69d5abca54a9a2dda))

<-- UpdateAddHtlc(64e13aeff81da767ab480c47af20bdde33e04e6598ee39ae6a853993fef561fb,1,351308789,836cc3987b415bcf9a52053d125ecaa92fe4810787fdd2846dcdca7e68110344,551710,000338376fe16de2f0bd7dd04fc19898cfcafc38654726a372b284c7bfb3e3829e78b2071f6a4cfdf8563ae1e356ebd67ee76c910402b7b81ab9f4a25266621b899fce16f2bbcebc7152543a04940d324066448e814292e4d39f2eb80574381ff92016d8b2a0e9bd7c1d9acdcc92adeeac96f312e003a469232f0410844889e94b3e103cc3202684c65ad3f269e76259b797708bff1e3d004377ed2ca8c17b72c897ca9af5872bb6554abf4af5ab195122ff93435eadd7f20331b49f0773fe6b6df9c69bcb99fa46ce35c673c110e7a800439d8d73ca9aaddeda49a24ace034b9d20c142bb3a06600dcfaf775df867f9c276e598b2ed03bab5762510bdd9d13580deb0197dbf8ee13bcba625d3bf0decf6735718322183f4ef56dfda9e2d4a616402497e1cb79624a69d37958de1784eec83658e0f93d5dd48c1f84ec6bd76c62c440bcf1ce6d5a9eed3736254a51b664a54d92a4b4d5524ff6fcf6b42f6b9e2db4749f859944fa31abe4e8ab2289088dce94507db75f22c25814190c47b53d9a47393e64bef525257c8ddaf5b403b069a709318daafb54e38cc8190ce16aaa623c134a21b12d6015a8eab18722f3dd211f3474e0c9dba74aebf1950ba5a661ee7db9b7d745159eefb637f592b9ad0bf18244c32df0987e7226d2857eded6878800c8f66f948862734feca4755b9c9e0f987ce6fd0ba8bfca6e80f472b98619f5ef798c4f70ad6df914f1a29051a7d52998ee912557a31dd320962cb45a2dc8124e0a45e732de85714dc651f84c7fb3e7020c68be9bc351bc6bc5892359dc6009d1156c9a91cb995c1e222d0d031c2224d64ed1b6e0d6d0f4638e529ad242c3c195fd4e84511b8e1a2c68c7ee82a687273a54c9735b736094a2882e858d88cb3e211f5914f7094a652ca930606f76ae5a4a3f2fa2647e98def048322ac9ff2e2cd2a179298e46b24b514527602bce0535f7fcc4b0b8d59d6a0b08d00138f6423589aee2ee00bd00d913ff0ebf2a6689bfae891508ed6105ceeb2976b7487222bb97189ce5211d433e967086d1e3def8c182b5a709546d4c4081a7347aa6cb2008288ae4f78740f44b7892ef760cc7e85ba0c3702950ac9c6d97686a54ad334e6f19cd8cf59be166c0ced127f17c88b4b366f10f48262bc144213f8fb306ed937e3d5629349f9625f15937cb8a8cdf157556233d8e3bad01aaa859a0d6d2f8caf8bf7d8d9bbe7f9db24a0a17cd9c0b3fa4a46dc6924de785f00e4846cdf4d7c5bd6e393acef07e4a0d9e50289e45d742e129739a9603c7b2682df8addd293dd854626f919c3ce9692652618920ceb1fd0ed64647e3ce21736f56a73b74798edcf03b4edf70cff6fceaf77304a0ea73fbab3a3ec689e263b113405bc73a0ab1d310fb4adb52ec43a65e0ff765b728f3f6560406a3507ba78509235b470f4fe70d8b739ff10fdcb3f0ce3c9c2d4bf3642fb7c079fbb86644534320b211e8628bfcf082ce69ae9f2cc25c60b1341dadfff3cd18fc6deb623800bf118793b82f9a59f40d1e6e0bb474153472d8a2bacc8870cdfd24627c66fa12e85b094ce981d753c3e388c69c35210d1e0442edd92cd2f086f1d5e041bc2d73e1d2dfdc03dcfaaa4a50b642010e6886fbc42c6699f8b905c31f79f3e1127f9175b360a9e3ef244fb113f6d8acdcde9a91cb40bf4e394b26eb4d818f0fef5c2cad192faca87ef2c72212a0b5c4b847dd02a27f84d2ce2f3f65acc7df6ed6e8a039cf9da6aa999e239842427767a4488a2909520548646973dfc4e7d3e517275bd3ebca9048e7d3925c55fcb4b3d8485d848db49df45e0e34a6cb2e3e794666dfd0df32e762e4f5ee25daa61bb71e4e7fb37290d1dc0a11039dfe09abfafd64a0d90f67aad7e33d9eabe9f9436d135767fb76615eae70554af048cdf2c5cad)

<-- CommitSig(64e13aeff81da767ab480c47af20bdde33e04e6598ee39ae6a853993fef561fb,30450221009b611f8a13a75061238a0966e2f8ef794d0653db51baf8c5593fc10e858bd4bf022034a29ce6bb044c8ffff8e5faecb0374cf8ff9eecad1460abbd7a105b2132615c01,List(304402203d3e1cb14608386af22ea11a630b050a033df321cb297b3e5387c40d100d9aa502205033c8b16286bf9bfc729bc7f3dcb25a6e2a98c6f9c797adaaf8bf7fec46e1db01, 3044022018869744c26829b8b1062ca8e40d41d5cec4452b9afbdd5b6284c703d5eacac502204961cc21d449fdbc4c30212da4cfe8324e4b4fc1b0aaaf30c2199ae50b12455601, 3045022100d995ec7b85c706cc522b1a036d8881ec0683465323050f47a689d71f669f901c02206e8a31840d9a5baa891327cc3a5383072be4e2030440a7ac48e0206f58faa48201, 3045022100a2b21b89f8f306341292884750325671affdace223b735615d1b6e547c41fe0102202333708f2094ce73529fdce4c31b20278c679e5e08d0151611e9076f65e274b801, 304402202aa220604895620b42e98376074dcae3464b79f8094dcd45f67451a7c86c7b2d02204de1b1301261f61f51d1f7e513f300ff7b276199bb035ce4aec99d94089c0c8f01, 304402207dbce5aaf34f1a1eee5c11e338945a03d00783256befe1e66e9be78f3a050026022072cbec78ac35f45b32d99a6905de0ef82d45d662c47181882814272f2912189701, 3044022026b06dd7ef073d4cc8e90900fe14603204c6947d3e83945b46e839f3aadc82820220568c1029e6340662a3cd6060aa41a26d9b00a1372ae4c62015b80465510a439201, 3045022100ab95914e2c3906c910d9ec8171d11ed18b649f0a4eb4ddf8fb0c2798ea9a6bd8022051d72d4c7267fbefc91fa8774ed8383559aa0e28465e3f7e38bf9e11edb5a54101))

<signature check fails here>

<-- UpdateAddHtlc(64e13aeff81da767ab480c47af20bdde33e04e6598ee39ae6a853993fef561fb,2,348754582,3c9493f44abb69c17a3a96af0ca4ed38828a484019c05ab0584fbc58425367b5,551716,0003e0c3a95bd312ad39dcf733b22559e16eecee9530c081aeb1a96d1ccb768c8a80147d37b7a5f66086488f4d67f286ee39626444b7ce431fe504163c1e45e0736586351fb833bd24dfc9e96190a2e0514fe39f57cb5c5964baf2887838fe1a15c884dcfea8d6594842f502f22cac92c814626dbc20b7e21164c00722187d56a98a3fdc6f3fefbe4d56647787f1e603908ec9c971f52f530b8d3fdf74bd14dbf60815b113e9069ba10544059b152db66f4f0437108f02d1d47c1211bcbd40fa1e7214b33de9e79724599f13de8f397286bf315b7d99f2b6571c822cf8141ad3807da8567d12153936c4d09bb6465329bc091475e3ba0bd774bb3eecac1d03238e1a2667ec26545730a69fc33e8bf788f0b5cad467cf5b3d4bee62246cb1f5450973e385ecf0942cc5651d9902d88e365094c46844ed4c719e92d98eef27db9ed9cc2a104ed16807de20a068f2e830f35c4eed4df5f7b488dad7e65cd7fc0e81bcc6bbcd9a0fbbd21796cf776a35afc21a629434dd426955c2ba8a7c54853ff4e44dffd83b265fbcec77c77066098744ae396a99fe59deb51341366e051c3d86b9a9e56a39b81f93f78e57e3bfceb4b73d9a148cba612e50f2dd1fc890a6c8583ac981ce82ab2d54713a281493a690d7bd7ad5f895c36cae581ea52d290b54e6669d2ff769f506fe9ead57324289574ec4b08530361e7bdab21ff637c6a449f9b1992e11b1bfdc52f0571a51d35272d2b010cf9853723a1568de8f3c8f8c6ade19e465f0a230d1657976afdf6c7288197083c62b1edf0c2463197416f79acf7aa214d5bf1d4a798fe1ce631938f48eb8a8954a1f4fad2e9e05662ca0192de711f570e5f490d1cb30ce5ef9cc5d61707986d32956d872607981f5681f59dded93b642a1926de426a5ee22994a589b38461646d2d3b2cae6f3db856a39040402666a9786321b271c6d774c6dc2584d478920ab2f172f68262aa9bdf8138a573ddd3272369b70cad2a9c6e54e9f580a107d9a3b7ef0e5e4e0e8b8cfc30ecb2a637f436c64bcc44ab32d823061e9353db387aedea2040d6dcb45c27c0cca39a7e0cfbd4d76ff247812b2eea0bccc111c8bb4452b6767b7cef91d4565745fe610d79ebb1e8f079e84caf4e5d5b4f8803a4b796324ccf004bf5398a281147b122cf700c3137bd2ba6680ea269d1dc61939e7efb229dae405dce7a4b1bbea503e3da12ff1bc8bb8255a99e2d59b52f78a6156a18802b4863c8a2ee2618be7f59aeabbbf125c33171f83189a0f6708de940d3667dd1da732b5f5010b7de4900b6b2d029000d8f5f8d9186e75f51044ddfc089306fef93f9899dbae7b6ce6501c338bbfa72c30e2bb14610d35acc7d11ee774d76df228777054e18a46a04725af6d150bd62f48a5b4b0362244933d7a929fbd0c468212b11e6e99a18d956b7ccf2206969b530cdd239c1cd23a29edd12de6b595b4e5fce59d43b040fc7cc22f3848ec59514184e02b990f05be5f4e4eaa90a583aa8e57be0c9223f31961836b5df5b25a1671534b6e54d0de9a377e8db3ea4330acf0be3ac5a44cc308df6040410d20feb4799a3b928f757a3eaa34cf3dd88bff1ef0afb552eaf3fad3cc4665a4ffd09071778c50d82beebdfc37cafd00b8c3735c92c197d54bcd547356410b99aa2a96462396dc085197d8eb094742b6b40209b9dd0657b73ba7613be141a96f2490e047d3e9ebc6081b885eb17ae4dd9fbf65ab3e56372df197cfe5a36fa45ed595a267da452556961b78dd4f742c8e5e30458371abd74bfd5500d667615fdf560a7aa602bb2ae84e9cfdbb8f250a5e84a5f5355522297eb8a30931d358c1f628450786ac9b11319a9ee391cb6a111f35ec542693ceae2974895eee83735764e668e72a92f73abce3fb93ed85ca8cb47db0beb23c32d9b823b0)

<-- UpdateAddHtlc(64e13aeff81da767ab480c47af20bdde33e04e6598ee39ae6a853993fef561fb,3,348754582,3c9493f44abb69c17a3a96af0ca4ed38828a484019c05ab0584fbc58425367b5,551717,00025efd72f743642834d2506bb64c02ca5069223def3294ec35d59cc01962722eb0e570c29e1066bb0e3f13a002c86a4855621be22c0407a07c6af4d963b61ec5ab10107de9d8c1cf99f8514642bda6cbdd609f66556413a1dbf43f30ce463f2d2d82ecbaa0e3e340d8b3cdf4b0c9d57e68db513b78dd8e5880a05197a99fcdc92ebeced601c694a9b5a575affae74e771e908450092cd3a69771c4a354f9b3c48a15c35d1986212eacf0d27fc75bc4a7099e9a1e14275e3ef6e2d4e10717892315d1b560db50b4dcd9d020db5a6abff5e5a7ce6b9b443adfe3bc88a14cdb941b02afe070facad73f717748a6fc698fb8fcfec77f02734c8bc4a4e6eeed1c496ef9a9744b13f78697e8fb67c02f172c81ea91e5b573756c99e34d76169291b381fbf903243d3f24f2ddc9d4a478ddb062fcbaec3fb46b365b73e1963526b99b8ac9db6dbdafabb88f746d9a6409a120833e9f87e4f02f831cdb8796a3bb761572e64f06c3ab5e2f654b35027400d2bcd5b63548717bf4b402ede149c5f148aa05fff63d29a40c75584368ff45cee3fe67ab7d9563599fa45b9fc112978265804e9f152868a77543e3dd5dfd3c0fd1e7e6ddf133020a66f8b3a2a29b1a4a87ee60db5c09747fe08ffd5966b9db748ea7adfdc5e6a09ad9f9161a518abf95657c070d1403605ffa6a03bdc1a6dbb380829ed3f3abb8a088029cde4391dc73685273c4831539fe339fa18c8a9b8c05296e6feba8c4d1ee84f471d76ae5c3ab32c0304f4a747db54aea8120d1a4cc4aad02c73d589ad4f6bd1550b8f321d109a56c31f11281f200ac3cce6ee70654f55282455dddc16ffb4a2b180f3d7fcaf15a67593f0f85158f09d2b1b607c0e3af9a41d406b0b262fadca18539ce638f5cda6b75041006f161e39861e2ea9de2b8c4ed99d5d5cb078fe289eb21529252fffa4e6670cf51d39e6fb9a5c7ca4ef32ff60104215c72e53acaf1f3c103eb7e6d86e22dbe34864ef2b74bb039188b938093819542bea10e62814ce486cafe6f547ad3f1b82774980d95291e9312fcdc9c4f940d4f166f05744b4c33b278603905819d39a7b00e9582d12d04588205ca5e5ddf348e197332dd7cb97249ece0bb40b27c20203d06a006d3e71068ff0a08ef9ed76bf81072feb5bb7c8c6cd87d8aaa9e6478cb869d85cba8b2bbde4bc56fc61871955992461c80f1e61d16c0176ea59cc91efa72aeec1756553a0504cfd860d74591f3d598e8cd1fb47bb33b2091b7f6a969a846dfd6da4694bf02e8bb298edfdb2711086a6c484cda22c7bc331e0c0568b75000c4d9f042ae7826ce0d05402000ba11db10380556f8ff2a229a0b59deb46a358a57b4b61af823c0952cd59547de591d2844d046656b05ed8a3dcb8608a273e98027ba035cc94264ac9cd333eb68761cf5cce52b11d6fb1bdc0853acb866987633d18aac455364f97716c0f6225c6293a6f0955d09d40175821aeff92d16f795a7a573ac93c6ef71d1b74e4da68f0fdfe3dbb6279f94bf11fc8a9caf2df7176ffcedafa1edd166e8c556ac48d402407827917d71adeddb5fdcb2c86c05bc01a94640833a9190b51b9873092df5c69f7e1632ea90c540e252f0933fad25ff55080fa6797ade864b9ab6a1854048cd45558fb530b17673c8fa9407d7e5440524f8bd8fae322a247ab7022b5b3b4dd336fc177dcd7b23b528922cec215e28f0b4053a53036596d5123ce99cee7cbe993e983458acefbb5d407b59fad22c3b37e3677bb6e1142b1822949c63c43f311fb8e6e19a3d0842a4d41ae3bab988ded2c0c3022c516721de612c1ed386856dddb2884e3ad8c699cd66e10f33ca3fd01e204d9cfc89f805c43116d6ca293863fe3bccd15b73a4d09aac6ece06432cd237b0432367c7fc84bacdce7dea5c548262f355d31475cb)
```

Is seems strange that LND sends two HTLCs with identical amount and hash but different expiry.

I'm in contact with remote LND operator, what can I ask them to do in order to get more useful info?

### Your environment

0.5.1-beta commit=v0.5.1-beta-rc4

### PR DESCRIPTION
**Pull request by cfromknecht**
Updates commitment transaction sorting to be consistent with https://github.com/lightningnetwork/lightning-rfc/pull/491

Fixes #2234

### CODE REVIEW

File: lnwallet/channel.go [hunk 1]
```diff
@@ -2411,7 +2411,13 @@ func (lc *LightningChannel) createCommitmentTx(c *commitment,
...
 	// Each output includes an off-chain 2-of-2 covenant clause, so we'll
 	// need the objective local/remote keys for this particular commitment
-	// as well.
+	// as well. For any non-dust HTLCs that are manifested on the commitment
+	// transaction, we'll also record its CLTV which is required to sort the
+	// commitment transaction below. The slice is initially sized to the
+	// number of existing outputs, since any outputs already added are
+	// commitment outputs and should correspond to zero values for the
+	// purposes of sorting.
+	cltvs := make([]uint32, len(commitTx.TxOut))
```
Comment (Roasbeef) [inline lnwallet/channel.go]: I think this needs to first add up to two zero valued CLTV values for the commitment outputs (if present). Otherwise, `len(cltvs) != len(commitTx.TxOut)`. Also since we use append below, this should be: 
```go
cltvs := make([]uint32, 0, len(commitTx.TxOut))
```

Comment (cfromknecht) [reply lnwallet/channel.go]: that's what this does?

Comment (cfromknecht) [reply lnwallet/channel.go]: > The slice is initially sized to the number of existing outputs, since any outputs already added are commitment outputs and should correspond to zero values for the purposes of sorting.
