### PR TITLE
invoices: add height based expiry watcher

### LINKED ISSUE #4587: Expired hodl invoice can still be settled
### Background

Hodl invoices have an expiry height just like regular invoices. However, the responsibility to settle the invoice after an htlc is accepted lies with the user. When the user doesn't cancel or settle an invoice before it expires, the accepted htlc expires and leads to channel force-close.

The force-close is still somewhat acceptable. Hodl invoice is an advanced feature and applications need to tend to the hodl invoices that they manage.

This issue is about what happens after the force-close. Even after the channel is fully resolved, it is still possible to mark an accepted hodl invoice as `settled` using the `SettleInvoice` rpc. No error is returned and it will look as if we've actually received the money. Not good for accounting.

### Your environment

lnd master - 6055b00dbbcedf45cd60f12e57dc5c1a7b97746f

### Steps to reproduce

* Bob creates hodl invoice
* Alice pays hodl invoice
* Generate blocks until channel force-closes
* Generate more blocks until channel is fully resolved
* Bob calls `SettleInvoice` with the preimage
-> Invoice settled.

### Expected behaviour

When there is no reasonable chance to claim the htlc anymore, the invoice should transition to the `canceled` state. A subsequent `SettleInvoice` call will then also return an error. By canceling the invoice in time, the force-close will also be prevented.

### Actual behaviour

Invoice is marked settled even though no money has been received.

### LINKED ISSUE #4987: Invoice HTLC shards should not remain in ACCEPTED state after cancelation
### Background

As currently designed in the invoices RPC: invoices enter an ACCEPTED state when HTLCs are held but not yet settled with the preimage. This is designed to allow a caller to know when HTLCs are safely held and that they can settle with a preimage.

However if the preimage is never provided, the HTLCs will never leave this ACCEPTED state even though after a timeout they will no longer be able to be claimed

Ideally the surfaced state of the HTLC would indicate a different state to the RPC caller to disambiguate between "able to be settled" and "no longer able to be settled"

### Your environment

* LND 0.12.0-beta

### PR DESCRIPTION
**Pull request by carlaKC**
This PR adds a height-based expiry watcher for hodl invoices which will cancel these invoices back before they expire. This prevents lnd from force-closing when an invoice is not released by its creator. Resolving these htlcs properly addresses two state machine issues we run into when a hodl invoice expires: 
- Fixes #4587 : clients can still settle hodl invoices which have expired (and can't be claimed)
- Fixes #4987: when a hodl invoice with active htlcs expires and goes to chain, its htlcs remain in accepted state

An alternative approach was explored in #5136, however there are multiple race issues that arise when the invoice registry does not drive changes in invoice state, so instead an expiry watcher which keeps control in the invoice registry was chosen.

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -483,11 +478,21 @@ func newServer(cfg *Config, listenAddrs []net.Addr,
...
-	_, currentHeight, err := s.cc.ChainIO.GetBestBlock()
+	currentHash, currentHeight, err := s.cc.ChainIO.GetBestBlock()
 	if err != nil {
 		return nil, err
 	}
 
+	// Create an invoice expiry watcher that will expire our own invoices
+	// once block before they trigger a force close.
+	expiryWatcher := invoices.NewInvoiceExpiryWatcher(
+		clock.NewDefaultClock(), lncfg.DefaultIncomingBroadcastDelta+1,
```
Comment (carlaKC) [inline server.go:489]: Using `lncfg.DefaultIncomingBroadcastDelta+1` here so that we don't go to chain for our hodl invoices.

Wondering whether this should be exposed in config? We don't expose our broadcast deltas, so I wasn't sure whether it was necessary.

File: invoices/invoice_expiry_watcher_test.go [hunk 2]
```diff
@@ -203,3 +204,102 @@ func TestInvoiceExpiryWhenAddingMultipleInvoices(t *testing.T) {
...
+
+	creationDate := testTime
+	expiry := time.Hour
+
+	test := setupHodlExpiry(
+		t, creationDate, expiry, 0, channeldb.ContractAccepted, nil,
+	)
+	defer test.watcher.Stop()
+
+	test.mockClock.SetTime(testTime.Add(expiry + 1))
```
Comment (bhandras) [inline invoices/invoice_expiry_watcher_test.go:237]: didn't you mean to add an assertion after the `SetTime`?

**Review by bhandras — COMMENTED** [review]
Nicely structured commits and very readable solution. Apart from a few nits changes lgtm.

File: config.go [hunk 3]
```diff
@@ -1355,6 +1360,16 @@ func ValidateConfig(cfg Config, usageMessage string,
 		return nil, err
 	}
 
+	// Log a warning if our expiry delta is not greater than our incoming
+	// broadcast delta. We do not fail here because this value may be set
+	// to zero to intentionally keep lnd's behavior unchanged from when we
+	// didn't auto-cancel these invoices.
+	if cfg.Invoices.HoldExpiryDelta <= lncfg.DefaultIncomingBroadcastDelta {
+		ltndLog.Warnf("Invoice hold expiry delta: %v <= incoming " +
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply config.go:1368]: Auto-expire does change some assumptions around hold invoices. 
- Previously: You have until the htlc's expiry to go to chain, even if that means a channel is force closed
- Now: The invoice will be canceled before it goes to chain, so you won't be able to settle after `expiry - HoldExpiryDelta`

I thought that it would be good to allow the option to opt-out of this behaviour change by allowing a 0 value delta. This still lets you settle up until `expiry`, and the invoice registry state will be handled properly because we will cancel any un-settled invoices at their expiry height even after they've gone to chain. 

For 99.99% of people I don't think this value will be updated, and for the rest it's nice to have the option? We could come back to this later once it's been well communicated and enforce? Since there isn't really much use-case for allowing your channels to be force closed IMO 😅

File: invoices/invoice_expiry_watcher.go [hunk 4]
```diff
@@ -115,6 +176,31 @@ func makeInvoiceExpiry(paymentHash lntypes.Hash,
...
+		var expiryHeights []uint32
+
+		for _, htlc := range invoice.Htlcs {
+			// We only care about accepted htlcs, since they will
+			// trigger force-closes.
+			if htlc.State != channeldb.HtlcStateAccepted {
+				continue
+			}
+
+			expiryHeights = append(expiryHeights, htlc.Expiry)
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoice_expiry_watcher.go:209]: We do call `makeHeightExpiry` twice (`makeInvoiceExpiry`/`addHtlcs`) and the `addHtlcs` is called from outside of the context of the expiry watcher, so I thought it would be better to leave that logic in the watcher. Opinion not tightly held, so happy to do either :)

[the remark this answers is not in the document]
Comment (bhandras) [reply invoices/invoice_expiry_watcher.go:209]: IMHO reducing the number of allocations is worth it. Finding the minimum and passing it to `makeHeightExpiry` is probably the best solution since pre-allocating `expiryHeights` would allocate more than needed.

File: config.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (bhandras) [reply config.go:1368]: Fair enough. The warning is probably scary enough to make users think twice. Maybe worth thinking through why a 0 delta would add to the overall (power)user experience.

**Review by bhandras — APPROVED** [review]
LGTM :ocean:

File: server.go [hunk 5]
```diff
@@ -483,11 +478,21 @@ func newServer(cfg *Config, listenAddrs []net.Addr,
...
 	}
 
-	_, currentHeight, err := s.cc.ChainIO.GetBestBlock()
+	currentHash, currentHeight, err := s.cc.ChainIO.GetBestBlock()
 	if err != nil {
 		return nil, err
 	}
 
+	// Create an invoice expiry watcher that will expire our own invoices
+	// once block before they trigger a force close.
```
Comment (yyforyongyu) [inline server.go:487]: typo: could rm "once block"

File: invoices/invoice_expiry_watcher_test.go [hunk 6]
```diff
@@ -203,3 +204,114 @@ func TestInvoiceExpiryWhenAddingMultipleInvoices(t *testing.T) {
...
+	// this invoice to be canceled because it has been accepted.
+	test.mockClock.SetTime(creationDate.Add(expiry))
+
+	// Tick our mock block subscription with the next block, we don't
+	// expect anything to happen.
+	test.announceBlock(t, uint32(testCurrentHeight+1))
+
+	// Now, we add another htlc to the invoice. This one has a lower expiry
+	// height than our current ones.
+	htlc3 := uint32(testCurrentHeight + 5)
```
Comment (yyforyongyu) [inline invoices/invoice_expiry_watcher_test.go:310]: 👍

File: invoices/test_utils_test.go [hunk 7]
```diff
@@ -365,3 +367,111 @@ func checkFailResolution(t *testing.T, res HtlcResolution,
...
+	select {
+	case actual := <-h.cancelChan:
+		require.Equal(t, expected, actual)
+
+	case <-time.After(testTimeout):
+		t.Fatalf("invoice: %v not canceled", h.hash)
+	}
+}
+
+// setupHodlExpiry creates up a hodl invoice in our expiry watcher and runs an
```
Comment (yyforyongyu) [inline invoices/test_utils_test.go:409]: typo
setupHodlExpiry creates up a hodl invoice in our expiry watcher and runs an
setupHodlExpiry creates ~up~ a hodl invoice in our expiry watcher and runs an

File: invoices/invoice_expiry_watcher_test.go [hunk 8]
```diff
@@ -203,3 +204,114 @@ func TestInvoiceExpiryWhenAddingMultipleInvoices(t *testing.T) {
...
+	test := setupHodlExpiry(
+		t, creationDate, expiry, 0, channeldb.ContractOpen, nil,
+	)
+
+	test.assertCanceled(t, test.hash)
+	test.watcher.Stop()
+}
+
+// TestAcceptedHodlNotExpired tests that hodl invoices which are in an accepted
+// state are not expired once their time-based expiry elapses.
```
Comment (yyforyongyu) [inline invoices/invoice_expiry_watcher_test.go:225]: Looks like the description is a bit off.

File: lntest/itest/lnd_hold_invoice_force_test.go [hunk 9]
```diff
@@ -88,25 +87,25 @@ func testHoldInvoiceForceClose(net *lntest.NetworkHarness, t *harnessTest) {
...
+		RHash: payHash[:],
+	})
 	require.NoError(t.t, err)
+	require.Equal(t.t, lnrpc.Invoice_CANCELED, inv.State)
 
-	// Cleanup Alice's force close.
-	cleanupForceClose(t, net, net.Alice, chanPoint)
+	// Clean up the channel.
+	ctxt, _ = context.WithTimeout(ctxb, channelCloseTimeout)
+	closeChannelAndAssert(ctxt, t, net, net.Alice, chanPoint, false)
```
Comment (yyforyongyu) [inline lntest/itest/lnd_hold_invoice_force_test.go:110]: 👍

File: invoices/invoice_expiry_watcher.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply invoices/invoice_expiry_watcher.go:209]: Or we could pass `invoice` to `makeHeightExpiry` to avoid going through the slice a second time.

**Review by yyforyongyu — COMMENTED** [review]
cACK. Again very nice commits! Need to go over the invoice's cancellation flow to understand the issue a bit more🤓

File: config.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (carlaKC) [reply config.go:1368]: It's more about giving the option to not change behaviour. Eg, I was thinking about loop, with a 12 block delta, we won't be able to settle our invoices 12 blocks before expiry, because they will be auto-cancelled which changes assumptions a bit. I think it's nice to give services like loop the option to disable this change while they update to accommodate it, then we can enforce it in the next major release?

File: invoices/invoice_expiry_watcher.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoice_expiry_watcher.go:209]: We don't always have the `invoice` struct when we call `makeHeightExpiry`, so moving to just pass in minimum expiry height.

File: invoices/invoice_expiry_watcher.go [hunk 10]
```diff
@@ -151,18 +240,67 @@ func makeTimestampExpiry(paymentHash lntypes.Hash,
...
+
+	for _, height := range expiryHeights {
+		if height < minHeight || minHeight == 0 {
+			minHeight = height
+		}
+	}
+
+	// If we don't have any htlcs that are going to expire, we
+	// don't need to add this invoice to the expiry watcher yet.
+	if minHeight == 0 {
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoice_expiry_watcher.go:258]: I think we have serious bugs elsewhere if a htlc has a 0 min-height. Added a warning log in this case, and moved to pass in minimum height rather than `[]uint32`.

File: invoices/invoice_expiry_watcher_test.go (hunk 8 above)
Comment (carlaKC) [reply invoices/invoice_expiry_watcher_test.go:225]: I think it is? `setupHodlExpiry` adds an accepted invoice with now+1h expiry, and then we tick the test clock to that time. I've added another invoice as a control to check that we're actually expiry invoices at now+1h, updated the comment to reflect that 👍

File: invoices/test_utils_test.go [hunk 11]
```diff
@@ -367,3 +369,111 @@ func checkFailResolution(t *testing.T, res HtlcResolution,
...
+		require.Equal(t, expected, actual)
+
+	case <-time.After(testTimeout):
+		t.Fatalf("invoice: %v not canceled", h.hash)
+	}
+}
+
+// setupHodlExpiry creates a hodl invoice in our expiry watcher and runs an
+// arbitrary update function which advances the invoices's state.
+func setupHodlExpiry(t *testing.T, creationDate time.Time,
```
Comment (yyforyongyu) [inline invoices/test_utils_test.go:413]: 👍

File: invoices/invoice_expiry_watcher_test.go [hunk 12]
```diff
@@ -203,3 +204,113 @@ func TestInvoiceExpiryWhenAddingMultipleInvoices(t *testing.T) {
...
+	test := setupHodlExpiry(
+		t, creationDate, expiry, 0, channeldb.ContractAccepted, nil,
+	)
+	defer test.watcher.Stop()
+
+	// Add another invoice that will expire at our expiry time as a control
+	// value.
+	tsExpires := &invoiceExpiryTs{
+		PaymentHash: lntypes.Hash{1, 2, 3},
+		Expiry:      testTime.Add(expiry),
```
Comment (yyforyongyu) [inline invoices/invoice_expiry_watcher_test.go:243]: nit: use `creationDate.Add`

File: invoices/invoice_expiry_watcher_test.go [hunk 13]
```diff
@@ -203,3 +204,113 @@ func TestInvoiceExpiryWhenAddingMultipleInvoices(t *testing.T) {
...
+		Keysend:     true,
+	}
+	test.watcher.AddInvoices(tsExpires)
+
+	test.mockClock.SetTime(testTime.Add(expiry + 1))
```
Comment (yyforyongyu) [inline invoices/invoice_expiry_watcher_test.go:248]: nit: use `creationDate.Add`

File: invoices/invoice_expiry_watcher_test.go [hunk 14]
```diff
@@ -203,3 +204,113 @@ func TestInvoiceExpiryWhenAddingMultipleInvoices(t *testing.T) {
...
+
+	// Assert that only the ts expiry invoice is expired.
+	test.assertCanceled(t, tsExpires.PaymentHash)
```
Comment (yyforyongyu) [inline invoices/invoice_expiry_watcher_test.go:251]: Is there a way we can assert the invoice is not canceled? Or is it implicitly asserted in this `assertCanceled`?

**Review by yyforyongyu — COMMENTED** [review]
LGTM🤓 Just a few questions.

File: invoices/invoice_expiry_watcher.go [hunk 15]
```diff
@@ -151,18 +241,59 @@ func makeTimestampExpiry(paymentHash lntypes.Hash,
...
+
+	// Select on quit too so that callers won't get blocked in case
+	// of concurrent shutdown.
+	case <-ew.quit:
+	}
+}
+
+// addHtlcs adds a height-based expiry entry for an invoice, using the lowest
+// htlc height available to expire the invoice. This should be used to update
+// the expiry watcher to include height-based expiry watcher for  htlcs as they
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoice_expiry_watcher.go:279]: 🦅 👀

File: invoices/invoice_expiry_watcher.go [hunk 16]
```diff
@@ -122,6 +186,32 @@ func makeInvoiceExpiry(paymentHash lntypes.Hash,
...
+	case channeldb.ContractAccepted:
+		if !invoice.HodlInvoice {
+			log.Debugf("Invoice in accepted state not added to "+
+				"expiry watcher: %v", paymentHash)
+
+			return nil
+		}
+
+		var minHeight uint32
+		for _, htlc := range invoice.Htlcs {
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoice_expiry_watcher.go:201]: Everytime we add htlcs to the invoice, we're calling `addHtlcs` which will add the new expiry heights to the watcher. This does mean that we'll have multiple entries for one invoice in the queue, but that's pretty cheap, and we'll just skip them if the invoice was canceled in a previous run. Can come back to optimize this if we want, but would rather leave that to a follow up, since it's not too critical imo.

File: invoices/invoice_expiry_watcher_test.go (hunk 14 above)
Comment (carlaKC) [reply invoices/invoice_expiry_watcher_test.go:251]: Yeah, just implicitly asserted. Couldn't think of a better way to test it.

File: invoices/invoice_expiry_watcher.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply invoices/invoice_expiry_watcher.go:201]: Yeah I would say atm it's not a concern performance-wise. And it's not related to the newly added HTLCs but the HTLCs which are already added to the invoice. For an HTLC we have three states,
- HtlcStateAccepted
- HtlcStateSettled
- HtlcStateCanceled

Since [an HTLC with `HtlcStateSettled` can only be found in an invoice that has `ContractSettled`](https://github.com/lightningnetwork/lnd/blob/master/channeldb/invoices.go#L2185), the question is what happens when one of the `invoice.Htlcs` changes from `HtlcStateAccepted` to `HtlcStateCanceled`? Do we still use its expiry to cancel our invoice or should we update our expiry height?

**Review by yyforyongyu — COMMENTED** [review]
One final question is, what happens when one of the `invoice.Htlcs` changes from `HtlcStateAccepted` to `HtlcStateCanceled`? Do we still use its expiry to cancel our invoice or should we update our expiry height?

File: invoices/invoice_expiry_watcher.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoice_expiry_watcher.go:201]: Hm yeah, if a htlc is canceled then we shouldn't be using its expiry height to cancel it. I _think_ that can only happen when we [release mpp htlcs](https://github.com/lightningnetwork/lnd/blob/41c089fbf4feb3217b1e6a651142f192cbdcc8b9/invoices/invoiceregistry.go#L370) due to timeout, and then another attempt is made with a new set of htlcs which have higher expiry heights. But we should def account for that.

**Comment by carlaKC** [comment]
> One final question is, what happens when one of the `invoice.Htlcs` changes from `HtlcStateAccepted` to `HtlcStateCanceled`? Do we still use its expiry to cancel our invoice or should we update our expiry height?

So what could go wrong here, for example, is: 
- We add a htlc with height 100 to the expiry watcher for invoice `x`
- We add another htlc with height 105 for invoice `x`
- The htlc with expiry height 100 is canceled
- When we reach height 100, we incorrectly expire the invoice because we think the htlc is still active, when we should only cancel at height 105

I looked into whether this can happen with our current htlc handling, and it turns out the only time that we release a single htlc is when we [release](https://github.com/lightningnetwork/lnd/blob/41c089fbf4feb3217b1e6a651142f192cbdcc8b9/invoices/invoiceregistry.go#L370) due to MPP timeout. In this case, the invoice is still in an open state, so it won't have been added to the expiry watcher. Once all htlcs arrive for the invoice, it's moved into the `accepted` state, and the htlc set is finalized (we won't add a new set of htlcs with different expiry heights after this point, so we don't need to worry about our cancel height changing).

I've pushed a small update to only add to the height expiry watcher when we get a `resultAccepted` ([1](https://github.com/lightningnetwork/lnd/blob/41c089fbf4feb3217b1e6a651142f192cbdcc8b9/invoices/update.go#L229) /[2](https://github.com/lightningnetwork/lnd/blob/41c089fbf4feb3217b1e6a651142f192cbdcc8b9/invoices/update.go#L424)) our invoice update, which indicates that we have accepted all htlcs for the invoice. This way we only add the expiry height to the queue once, and we can be certain that it is the correct expiry height for the invoice. 

While we can update the expiry watcher to allow updating minimum height for an invoice, I don't think we need it right now. If our htlc handing changes, then we can come back and add invoice-awareness to the queue (also spent some time on this before I realized we don't really need it - it would look something like: track known invoices in `map[paymentHash]expiryHeight`, when we add a new htlc, remove previous entry from queue and re-add it).

File: invoices/invoiceregistry_test.go [hunk 17]
```diff
@@ -1118,6 +1119,222 @@ func TestOldInvoiceRemovalOnStart(t *testing.T) {
...
+	t.Run("single shot expires", func(t *testing.T) {
+		testHeightExpiryWithRegistry(t, 1, false)
+	})
+
+	t.Run("mpp settled before expiry", func(t *testing.T) {
+		testHeightExpiryWithRegistry(t, 2, true)
+	})
+
+	t.Run("mpp expires", func(t *testing.T) {
+		testHeightExpiryWithRegistry(t, 2, false)
```
Comment (yyforyongyu) [inline invoices/invoiceregistry_test.go:1140]: nit: seems like these can be fit into a perfect table test.

File: invoices/invoiceregistry_test.go [hunk 18]
```diff
@@ -1118,6 +1119,222 @@ func TestOldInvoiceRemovalOnStart(t *testing.T) {
...
+		resolution, err := ctx.registry.NotifyExitHopHtlc(
+			testInvoicePaymentHash, htlcAmt, expiry,
+			testCurrentHeight, getCircuitKey(uint64(i)), hodlChan,
+			payLoad,
+		)
+		require.NoError(t, err)
+		require.Nil(t, resolution, "did not expect direct resolution")
+	}
+
+	require.Eventually(t, func() bool {
```
Comment (yyforyongyu) [inline invoices/invoiceregistry_test.go:1185]: Fancy!

File: invoices/invoiceregistry_test.go [hunk 19]
```diff
@@ -1118,6 +1119,222 @@ func TestOldInvoiceRemovalOnStart(t *testing.T) {
...
+	// Send htlc 3.
+	hodlChan3 := make(chan interface{}, 1)
+	resolution, err = ctx.registry.NotifyExitHopHtlc(
+		testInvoicePaymentHash, invoice.Terms.Value/2, expiry,
+		testCurrentHeight, getCircuitKey(12), hodlChan3, mppPayload,
+	)
+	require.NoError(t, err)
+	require.Nil(t, resolution, "did not expect direct resolution")
+
+	// Check that settled amount is equal to the sum of values of the htlcs
```
Comment (yyforyongyu) [inline invoices/invoiceregistry_test.go:1317]: Looks like the amount is not checked.

**Review by yyforyongyu — COMMENTED** [review]
The newly added tests are so great! Just a few more questions🤓

File: invoices/invoiceregistry.go [hunk 20]
```diff
@@ -1101,6 +1114,16 @@ func (i *InvoiceRegistry) notifyExitHopHtlcLocked(
 
 		}
 
+		// If we have fully accepted the set of htlcs for this invoice,
+		// we can now add it to our invoice expiry watcher. We do not
+		// add invoices before they are fully accepted, because it is
+		// possible that we MppTimeout the htlcs, and then our relevant
+		// expiry height could change.
+		if res.outcome == resultAccepted {
+			expiry := makeInvoiceExpiry(ctx.hash, invoice)
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoiceregistry.go:1123]: > So here the invoice might still be in ContractOpen and we are adding ts expiry every time a new HTLC comes in?

If we get a `resultAccepted` outcome, then we're definitely in `ContractAccepted`. So in  the case where we're accepting mpp htlcs, we'll just no add it to the expiry watcher until all the htlcs are accepted. Once we reach this state, that's the final set of htlcs for this invoice so our min expiry height won't change.

File: invoices/invoice_expiry_watcher_test.go [hunk 21]
```diff
@@ -203,3 +204,115 @@ func TestInvoiceExpiryWhenAddingMultipleInvoices(t *testing.T) {
...
+	currentHeight := uint32(testCurrentHeight + 1)
+	test.announceBlock(t, currentHeight)
+
+	// Now, we add another htlc to the invoice. This one has a lower expiry
+	// height than our current ones.
+	htlc2 := currentHeight + 5
+	expiry2 := makeHeightExpiry(test.hash, htlc2)
+	test.watcher.AddInvoices(expiry2)
+
+	// Announce our lowest htlc expiry block less our delta, the invoice
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply invoices/invoice_expiry_watcher_test.go:314]: yeah, changed to minus ➖

File: invoices/invoiceregistry_test.go (hunk 19 above)
Comment (carlaKC) [reply invoices/invoiceregistry_test.go:1317]: 🙈 copied another test, will remove since it's already covered elsewhere.

**Comment by yyforyongyu** [comment]
Let me know if this is ready for a final round🤓

**Comment by carlaKC** [comment]
> Let me know if this is ready for a final round🤓

Ready for another look, travis failures unrelated flakes so far as I can tell.

File: invoices/invoiceregistry_test.go [hunk 22]
```diff
@@ -1118,6 +1119,222 @@ func TestOldInvoiceRemovalOnStart(t *testing.T) {
 	require.Equal(t, expected, response.Invoices)
 }
 
+// TestHeightExpiryWithRegistry tests our height-based invoice expiry for
+// invoices paid with singe and multiple htlcs, testing the case where the
```
Comment (yyforyongyu) [inline invoices/invoiceregistry_test.go:1123]: typo: singe -> single

**Review by yyforyongyu — APPROVED** [review]
LGTM👍 Very nice tests added! Found one typo and the rest is looking great!
