### PR TITLE
cmd: fix incorrect error code

### LINKED ISSUE #9648: [bug]: 0.19.0rc1 on testnet4:  `lncli` reports all errors as "wallet is encrypted"
### Background

Any lnd error returns the same message to lncli

### Your environment

* version of `lnd` 0.19.0-beta.rc1 commit=v0.19.0-beta.rc1
* which operating system (`uname -a` on *Nix) macos/docker
* version of `btcd`, `bitcoind`, or other backend bitcoind 28.1
* any other relevant environment details fresh install of testnet4

### Steps to reproduce
 ```
% lncli openchannel --node_key 030f289f0f931cd33cc3435dc5f5fc2a6a65bb0297327d43e82562aded10df74a7 --fee_rate_ppm 1 --local_amt 15000000
[lncli] wallet is encrypted - please unlock using 'lncli unlock', or set password using 'lncli create' if this is the first time starting lnd
```

while in the log:
```
2025-03-26 13:24:03.150 [INF] CHFD: Performing funding tx coin selection using 8626 sat/kw as fee rate
2025-03-26 13:24:03.150 [ERR] RPCS: unable to open channel to NodeKey(030f289f0f931cd33cc3435dc5f5fc2a6a65bb0297327d43e82562aded10df74a7): not enough witness outputs to create funding transaction, need 0.15000000 BTC only have 0 BTC available
2025-03-26 13:24:03.151 [ERR] RPCS: [/lnrpc.Lightning/OpenChannel]: not enough witness outputs to create funding transaction, need 0.15000000 BTC only have 0 BTC available
```

### PR DESCRIPTION
**Pull request by guggero**
Fixes a bug introduced by #9605, fixes #9648.
We need to use the "Unimplemented" code to detect whether the wallet is already unlocked. Otherwise we'll always get the wrong error message. But because the Unimplemented code can also occur if there is a mismatch between the build tags used for lncli and lnd, we also need to include that possibility in the erorr message to make sure the user can fix the problem.

### CODE REVIEW

File: cmd/commands/commands.go [hunk 1]
```diff
@@ -270,7 +270,7 @@ func actionDecorator(f func(*cli.Context) error) func(*cli.Context) error {
 		// 'unlock') but the wallet is already unlocked, then these
 		// methods aren't recognized any more because this service is
 		// shut down after successful unlock.
-		if s.Code() == codes.Unknown &&
+		if s.Code() == codes.Unimplemented &&
```
Comment (yyforyongyu) [inline cmd/commands/commands.go:273]: I think we need to check for both `Unimplemented` and `Unknown`?

File: cmd/commands/commands.go [hunk 2]
```diff
@@ -284,11 +284,14 @@ func actionDecorator(f func(*cli.Context) error) func(*cli.Context) error {
 		// means that lnd is running, but the RPC server is not active
 		// yet (only WalletUnlocker server active) and most likely this
 		// is because of an encrypted wallet.
-		if s.Code() == codes.Unknown {
-			return errors.New("wallet is encrypted - please " +
-				"unlock using 'lncli unlock', or set " +
-				"password using 'lncli create' if this is " +
-				"the first time starting lnd")
+		if s.Code() == codes.Unimplemented {
```
Comment (yyforyongyu) [inline cmd/commands/commands.go:287]: Same here - it will return `Unknown` in the edge case found in #9605

**Review by yyforyongyu — COMMENTED** [review]
You are quick! I actually also created a fix here https://github.com/lightningnetwork/lnd/compare/master...yyforyongyu:lnd:fix-cli Think we can pick that?

File: cmd/commands/commands.go [hunk 3]
```diff
@@ -284,11 +284,14 @@ func actionDecorator(f func(*cli.Context) error) func(*cli.Context) error {
 		// means that lnd is running, but the RPC server is not active
```
Comment (MPins) [inline cmd/commands/commands.go:284]: nit: On line 283, the comment refers to `Unknown` code, but it seems the correct code is `Unimplemented`. Consider updating the comment to reflect that.

File: cmd/commands/commands.go (hunk 1 above)
Comment (guggero) [reply cmd/commands/commands.go:273]: No, `Unknown` is the default code that we return everywhere (basically if you don't use `status.Error()` and just return an error, the `Unknown` status is always used). Only `Unimplemented` tells us that we're trying to call into a method that doesn't exist.
We also don't get an error saying "wallet locked" back. If only the wallet unlocker is active, any other gRPC method will return `Unimplemented`.
So unfortunately we can't really tell the difference between the wallet being locked and a gRPC method that's not enabled because of build tags. That's why I updated the error message instead.

**Comment by guggero** [comment]
> You are quick! I actually also created a fix here [master...yyforyongyu:lnd:fix-cli](https://github.com/lightningnetwork/lnd/compare/master...yyforyongyu:lnd:fix-cli) Think we can pick that?

I don't think that version is correct. Try it out with any method that returns an error (e.g. `lncli sendcoins` when no balance available).

File: cmd/commands/commands.go [hunk 4]
```diff
@@ -280,15 +280,20 @@ func actionDecorator(f func(*cli.Context) error) func(*cli.Context) error {
...
-				"password using 'lncli create' if this is " +
-				"the first time starting lnd")
+		// the wallet is encrypted. If we get error code Unimplemented,
+		// it means that lnd is running, but the RPC server is not
+		// active yet (only WalletUnlocker server active) and most
+		// likely this is because of an encrypted wallet. The only other
+		// case where we get Unimplemented is if there is a mismatch
+		// between the build tags used to build lncli vs. lnd.
+		if s.Code() == codes.Unimplemented {
+			return errors.New("RPC method is not implemented - " +
```
Comment (yyforyongyu) [inline cmd/commands/commands.go:290]: nit: think we might as well just return `s.Err`, but no strong opinion here

**Review by yyforyongyu — APPROVED** [review]
> > You are quick! I actually also created a fix here [master...yyforyongyu:lnd:fix-cli](https://github.com/lightningnetwork/lnd/compare/master...yyforyongyu:lnd:fix-cli) Think we can pick that?
> 
> I don't think that version is correct. Try it out with any method that returns an error (e.g. `lncli sendcoins` when no balance available).

hmmm think it did go through
```
./lncli-debug sendcoins bc1qkst39hl5muh7g52nx9rde3emmtytgzghzrh8y8 --amt=1000
Amount: 1000
Destination address: bc1qkst39hl5muh7g52nx9rde3emmtytgzghzrh8y8
Confirm payment (yes/no): yes
[lncli] rpc error: code = Unknown desc = insufficient funds available to construct transaction
```

Anyway thanks for the quick fix!

**Review by MPins — APPROVED** [review]
No further comments.

**Comment by guggero** [comment]
@yyforyongyu hmm, of course you're wrong... I had a very old model in my head :sweat_smile: 
I totally forgot we added this mechanism: https://github.com/lightningnetwork/lnd/blob/23602e017e30c2f2810a17a62a174d8858b6077c/rpcperms/interceptor.go#L739, so the `Unimplemented` message doesn't make it through correctly...

Gonna manually test all the cases now with the updated code, to make sure we don't break anything new...

**Comment by guggero** [comment]
Tested all cases manually, seems to work now.

**Review by yyforyongyu — APPROVED** [review]
tACK, thanks again!
