### PR TITLE
config.go: check for RPCUser AND RPCPass (AND ZMQPath for bitcoind)

### LINKED ISSUE #621: Runtime error with bitcoind backend
I've been trying out the new `bitcoind` backend mode, and I've been having some issues. 

After starting `bitcoind` (and ensuring it syncs completely before doing anything else), `lnd` gives me this errror:

```
2018-01-18 11:02:01.643 [INF] LTND: Version 0.3.0-alpha
2018-01-18 11:02:01.643 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2018-01-18 11:02:01.643 [INF] LTND: Primary chain is set to: bitcoin
2018-01-18 11:02:01.643 [INF] LTND: Initializing bitcoind backed fee estimator
2018-01-18 11:02:02.337 [INF] LNWL: Opened wallet
panic: runtime error: index out of range

goroutine 10 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.connFromAddr(0x0, 0x0, 0x0, 0x0, 0x3, 0xc4201fc780)
        /home/torkel/goprojects/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:286 +0x467
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq.Subscribe(0x0, 0x0, 0xc4201bbeb0, 0x2, 0x2, 0x5f5e100, 0x0, 0x0, 0xc420066700)
        /home/torkel/goprojects/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/gozmq/zmq.go:312 +0x4d
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcwallet/chain.(*BitcoindClient).socketHandler(0xc4201da540)
        /home/torkel/goprojects/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcwallet/chain/bitcoind.go:515 +0xf3
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcwallet/chain.(*BitcoindClient).Start
        /home/torkel/goprojects/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcwallet/chain/bitcoind.go:368 +0x160
```

My `lnd.conf` looks like this:
```
[Application Options]
no-macaroons=true
noencryptwallet=true

[Bitcoin]
bitcoin.active=true
bitcoin.testnet=true
bitcoin.node=bitcoind

[bitcoind]
bitcoind.rpcuser=xxx
bitcoind.rpcpass=xxx
```

My `bitcoin.conf` looks like this:
```
testnet=1
rpcuser=xxx
rpcpassword=xxx
server=1
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
````

I'm running Ubuntu 17.10, with Go version 1.9.2.

### PR DESCRIPTION
**Pull request by aakselrod**
This fixes config parsing such that:

* In the case of `btcd`, `lnd.conf` or command line options MUST specify BOTH `btcd.rpcuser` and `btcd.rpcpass` in order to avoid attempting to get authentication parameters from `btcd.conf` or NEITHER to get the parameters from `btcd.conf`; otherwise an error is returned asking the user to specify both or neither.
* In the case of `bitcoind`, `lnd.conf` or command line options MUST specify ALL OF `bitcoind.rpcuser`, `bitcoind.rpcpass`, and `bitcoind.zmqpath` in order to avoid attempting to get authentication parameters and the ZMQ path from `bitcoin.conf` or NONE to get the parameters from `bitcoin.conf`; otherwise an error is returned asking the user to specify all or none.

This should fix #621 when merged; however, in order to fix the underlying panic, glide should also be updated to the latest `gozmq` and (after the `btcwallet` glide is updated) `btcwallet`.

### CODE REVIEW

**Comment by halseth** [comment]
Looks like if not all is set, then those that are will be overridden by what's in the `conf` file? Is that intentional, or should we return an error?

**Comment by aakselrod** [comment]
That's intentional but I'm conflicted about it. I don't like the idea of returning an error if we can get the information from the config file, but maybe it would be better to consider the RPCUser AND RPCPass separately from the ZMQPath?

**Comment by halseth** [comment]
I just think it might be confusing that the config would override something you specified on the command line. Why not require either all or none to be set, and return an error otherwise?

**Comment by aakselrod** [comment]
That's definitely simpler, and I'm ok with that idea. I'll change it.

**Comment by aakselrod** [comment]
I've updated the code to return an error when only some, but not all or none, of the parameters are specified.

**Comment by mecampbellsoup** [comment]
As of ~0.12 Bitcoin Core, RPC username/password auth was deprecated in favor of auto-generated cookie auth file (auto generated by the daemon on initialization IIRC). As long as the OS user that initializes the `bitcoind` process is the same one querying the RPC interface, no manual configuration is necessary (i.e your user is authenticated by providing the cookie auth file to the RPC server).

My point is that perhaps we should start moving away from telling people in LND docs to configure their RPC username/password unless they will be querying the RPC interface from a remote process or from a different user on the same system. This would make setup/wiring `bitcoind` with `lnd` easier.

Note: not sure if `btcd` adopted this pattern as well or not.

cc @sansari

**Comment by aakselrod** [comment]
When auth parameters aren't specified, the configuration checks for a cookie file. This PR only ensures that, if RPC user and password ARE specified, the ZMQ socket path is also specified so that there's no attempt to get the configuration from `bitcoin.conf`.

File: config.go [hunk 1]
```diff
@@ -576,13 +576,30 @@ func parseRPCParams(cConfig *chainConfig, nodeConfig interface{}, net chainCode,
...
+		// user did that unintentionally.
+		if conf.RPCUser != "" || conf.RPCPass != "" {
+			return fmt.Errorf("please set both or neither of " +
+				"btcd.rpcuser and btcd.rpcpass")
+		}
 	case *bitcoindConfig:
-		if conf.RPCUser != "" || conf.RPCPass != "" || conf.ZMQPath != "" {
+		// If all of RPCUser, RPCPass, and ZMQPath are set, we assume
+		// those parameters are good to use.
+		if conf.RPCUser != "" && conf.RPCPass != "" && conf.ZMQPath != "" {
```
Comment (mecampbellsoup) [inline config.go]: Why if they are `nil`?

Comment (mecampbellsoup) [reply config.go]: Looks like what you have here is idiomatic: https://stackoverflow.com/a/18595217

**Comment by aakselrod** [comment]
Rebased and added `glide` update.

**Comment by aakselrod** [comment]
Sorry, just rebased again to master.

**Comment by aakselrod** [comment]
Removed glide update, as @Roasbeef has merged it separately, and rebased on top of the already-merged glide update.

**Comment by mecampbellsoup** [comment]
Hey guys, recently seems like configuration protocol has changed as my long-time-functional `bitcoind` conf now fails to start the daemon.

```
[Bitcoind]
; lnd should auto-discover the .cookie and bitcoin.conf files
bitcoind.zmqpath='tcp://127.0.0.1:18501'
```
And in `lnd.conf`:
```
[Bitcoin]
bitcoin.mainnet=1
bitcoin.active=1
bitcoin.node=bitcoind

[Bitcoind]
; lnd should auto-discover the .cookie and bitcoin.conf files
bitcoind.zmqpath='tcp://127.0.0.1:18501'
```
Any way to use something like e.g. `git bisect` to find which commit made it impossible to launch `lnd` with these configurations? Thanks guys, appreciate the continuous work on this FWIW :)

**Comment by mecampbellsoup** [comment]
P.S. Left out the failure message from `lnd`:
```
λ MEC-MBP lnd → λ git master* → lnd
Attempting automatic RPC configuration to bitcoind
unable to load RPC credentials for bitcoind: unable to extract RPC credentials: zmqpubrawblock and zmqpubrawtx must be different, cannot start w/o RPC connection
```
@halseth this seems like a regression...?

**Comment by halseth** [comment]
@mecampbellsoup This is a recent change, take a look here: https://github.com/lightningnetwork/lnd/pull/1566
