### PR TITLE
Fix race between `channel_ready` and link update

### LINKED ISSUE #7401: [bug]: race with `funding_locked` and `update_fee`/`update_add_htlc`
We have an electrum user who opened [a channel](https://blockstream.info/tx/5312520f35070e7c353377ac84483ffac5fe9d08a006fb2d40d73e64e594f203?output:1) with [`bfx-lnd1`](https://1ml.com/node/03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6).
The channel is using static_remotekey, no anchors.
Immediately after the channel gets opened, the following message exchange happens (electrum logs - `feb12`):
```
20230212T211915.199453Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | >> Sending FUNDING_LOCKED
20230212T211915.200725Z |    DEBUG | lnchannel.Channel.[03f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f521252] | Setting channel state: FUNDED -> OPEN
20230212T211915.228150Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | CHANNEL OPENING COMPLETED (776238x1553x1)
20230212T211915.242947Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | updating fee to bump remote ctn
20230212T211915.243083Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | (chan: 776238x1553x1) current pending feerate 3755. new feerate 3756
20230212T211915.246767Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | >> Sending UPDATE_FEE
20230212T211915.247150Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | send_commitment. chan 776238x1553x1. ctn: 1.
20230212T211915.250417Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | >> Sending COMMITMENT_SIGNED
20230212T211915.907661Z |    DEBUG | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | << Received ERROR
20230212T211915.907861Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | remote peer sent error [DO NOT TRUST THIS MESSAGE]: rejected commitment: commit_height=1, invalid_commit_sig=304402205ffed5b844d11c1b8f5e4be6dfb17287265eef80ffd975195c76ee6a9ff424250220173cd11940a49db06fe524d24fbf7eb9180f93b8117536c78eb7db8904823304, commit_tx=020000000103f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f52125301000000007268e7800161f5ff0000000000160014aec8d8fd4e9bcb41de8f241c4eef3d2a9811e5ece6fa9d20, sig_hash=ff310d4f9219d30ff57064b885d4792314d012fd2c8e6bc5f7d3873ae412b425. chan_id=03f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f521252
```
Based on the error message (and the node alias?), the remote (`bfx-lnd1`) [is likely running lnd](https://github.com/lightningnetwork/lnd/blob/48c8c1bf48ed9be7a014803ea4c3b4624407dcc3/lnwallet/channel.go#L4449), no idea what version though.

Note that electrum is the opener/funder of the channel, and it sends an `update_fee` msg (3755 sat/kw -> 3756 sat/kw) right after `funding_locked`:
```
20230212T211915.243083Z |     INFO | lnpeer.Peer.[LNWallet, 03cde60a63-b218bbf7] | (chan: 776238x1553x1) current pending feerate 3755. new feerate 3756
```
This is supposed to update the absolute fee for the commitment tx (msat), from `2718 sat` to `2719 sat`:
```py
>>> 3755 * 724 // 1000 * 1000
2718000
>>> 3756 * 724 // 1000 * 1000
2719000
```

The `commit_tx` lnd sends it is checking our sig against:
`commit_tx=020000000103f294e5643ed7402dfb06a0089dfec5fa3f4884ac7733357c0e07350f52125301000000007268e7800161f5ff0000000000160014aec8d8fd4e9bcb41de8f241c4eef3d2a9811e5ece6fa9d20`
From that, the fee lnd expects to be paid:
```py
>>> fee=16777215-16774497
>>> fee
2718
```
It looks like lnd is incorrectly still calculating with the old feerate.

The issue seems to be similar to https://github.com/ElementsProject/lightning/issues/3341,
which by the looks of it was worked around in c-lightning in https://github.com/ElementsProject/lightning/pull/3634 - not sure if there was any follow-up to fix the bug in lnd there...
Note that in either case, unlike in many seemingly related issues, there is no disconnection of bolt8 transport, no channel_reestablish is involved.

-----

ref: https://github.com/spesmilo/electrum/issues/8191#issuecomment-1427158299
@ondra-novak

### PR DESCRIPTION
**Pull request by yyforyongyu**
Depends on 
- #7517 
- https://github.com/lightninglabs/neutrino/pull/279
- #7794 

This PR starts tracking pending open channels in `peer.Brontide`. Suppose a message is received for this pending channel, it will be cached and processed once this channel becomes active.

Fixes #7401

### CODE REVIEW

File: peer/brontide.go [hunk 1]
```diff
@@ -3878,3 +3865,33 @@ func (p *Brontide) handleNewPendingChannel(req *newChannelMsg) {
...
+
+// sendLinkUpdateMsg sends a message that updates the channel to the
+// channel's message stream.
+func (p *Brontide) sendLinkUpdateMsg(msg lnwire.Message) {
+	linkUpdateMsg, ok := msg.(LinkUpdater)
+	if !ok {
+		return
+	}
+
+	targetChan := linkUpdateMsg.TargetChanID()
```
Comment (morehouse) [inline peer/brontide.go:3896]: Since we now determine `targetChan` here, I think we can remove the associated variable in `readHandler`.

File: peer/brontide.go [hunk 2]
```diff
@@ -3895,3 +3914,101 @@ func (p *Brontide) sendLinkUpdateMsg(msg lnwire.Message) {
...
+// handleLinkUpdateMsg returns a boolean to indicate whether the given message
+// can be sent to the channel's message stream. If this message's channel is
+// still pending, it will be cached.
+func (p *Brontide) handleLinkUpdateMsg(msg lnwire.Message,
+	chanID lnwire.ChannelID) bool {
+
+	p.activeChanMtx.RLock()
+	defer p.activeChanMtx.RUnlock()
+
+	channel, ok := p.activeChannels[chanID]
```
Comment (morehouse) [inline peer/brontide.go:3927]: Can we reuse `isActiveChannel` and `isPendingChannel` for clarity here?

File: peer/brontide.go [hunk 3]
```diff
@@ -3895,3 +3914,101 @@ func (p *Brontide) sendLinkUpdateMsg(msg lnwire.Message) {
...
+		p.log.Errorf("Failed to cache msg %s for pending channel: %v, "+
+			"error: %v", msg.MsgType(), chanID, err)
+	}
+
+	return false
+}
+
+// processEarlyMsgs takes a block height, resends all the future messages
+// found below and equal to that height and deletes those messages found in the
+// gossiper's futureMsgs.
```
Comment (morehouse) [inline peer/brontide.go:3967]: This function comment seems incorrect.  I don't see any block heights used or deleting of messages.

File: peer/brontide.go [hunk 4]
```diff
@@ -1664,9 +1664,15 @@ func (p *Brontide) handleCustomMessage(msg *lnwire.Custom) error {
...
-	_, ok := p.activeChannels[chanID]
-	p.activeChanMtx.RUnlock()
-	return ok
+	defer p.activeChanMtx.RUnlock()
+
+	// The channel would be nil if,
+	// - the channel doesn't exist, or,
+	// - the channel exists, but is pending. In this case, we don't
+	//   consider this channel active.
+	channel := p.activeChannels[chanID]
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:1704]: Good call. For `channel_reestablish` we allow pending channels, added this check.

File: peer/brontide.go [hunk 5]
```diff
@@ -1660,6 +1660,29 @@ func (p *Brontide) handleCustomMessage(msg *lnwire.Custom) error {
...
+// disk.
+func (p *Brontide) isLoadedFromDisk(chanID lnwire.ChannelID) bool {
+	p.activeChanMtx.RLock()
+	defer p.activeChanMtx.RUnlock()
+
+	// If this is a newly added channel, no need to reestablish.
+	_, added := p.addedChannels[chanID]
+	if added {
+		return false
+	}
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:1681]: previously we use `nil` value to indicate it's a pending channel. And because we only ever have pending channels in the `activeChannels` map during startup, it also implicitly means it's loaded from disk. With the following commits this implication is not correct anymore.

On the other hand, the loaded channels won't appear in `addedChannels` map, so we perform an explicit check here.

File: peer/brontide.go [hunk 6]
```diff
@@ -3733,3 +3639,143 @@ func (p *Brontide) attachChannelEventSubscription() error {
 
 	return nil
 }
+
+// handleExistingChannel updates the existing channel's next revocation if it's
+// nil.
+func (p *Brontide) handleExistingChannel(c *channeldb.OpenChannel) {
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3710]: yeah i like it, changed.

File: peer/brontide.go (hunk 1 above)
Comment (yyforyongyu) [reply peer/brontide.go:3896]: not sure I follow, what do you mean by "the associated variable"?

File: peer/brontide.go (hunk 3 above)
Comment (yyforyongyu) [reply peer/brontide.go:3967]: yikes, it was copied, now fixed.

File: peer/brontide.go (hunk 2 above)
Comment (yyforyongyu) [reply peer/brontide.go:3927]: wanted this too but couldn't as they were in two separate locks, which complicated things. but now it's changed to sync maps, so yeah switched.

File: funding/manager.go [hunk 7]
```diff
@@ -2336,6 +2336,15 @@ func (f *Manager) handleFundingCreated(peer lnpeer.Peer,
 	// and canceling the wait for the funding confirmation.
 	f.wg.Add(1)
 	go f.advanceFundingState(completeChan, pendingChanID, nil)
+
+	// With FundingSigned sent, we can now notify Brontide to keep track of
+	// this pending open channel.
+	if err := peer.AddPendingChannel(completeChan, f.quit); err != nil {
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply funding/manager.go:2342]: yeah we need to send it earlier, moved to before sending `funding_signed`.

File: peer/brontide.go (hunk 1 above)
Comment (morehouse) [reply peer/brontide.go]: I'm not sure anymore -- it looks like the code I was referring to has changed, but the force push makes it hard to figure out what's different.

File: lnutils/sync_map.go [hunk 8]
```diff
@@ -45,9 +45,40 @@ func (m *SyncMap[K, V]) LoadAndDelete(key K) (V, bool) {
...
 func (m *SyncMap[K, V]) Range(visitor func(K, V) bool) {
 	m.Map.Range(func(k any, v any) bool {
 		return visitor(k.(K), v.(V))
 	})
 }
+
+// ForEach iterates the map and applies the `visitor` function. Unlike the
+// `Range` method, the `visitor` function will be applied to all the items
+// unless there's an error.
+func (m *SyncMap[K, V]) ForEach(visitor func(K, V) error) {
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply lnutils/sync_map.go:59]: `ForEach` uses `Range` under the hood, so ofc you can just replace it. This is added to differentiate the two use cases.

File: funding/manager.go [hunk 9]
```diff
@@ -3417,30 +3399,19 @@ func (f *Manager) handleChannelReady(peer lnpeer.Peer,
...
-	defer func() {
-		f.handleChannelReadyMtx.Lock()
-		delete(f.handleChannelReadyBarriers, msg.ChanID)
-		f.handleChannelReadyMtx.Unlock()
-	}()
-
-	f.localDiscoveryMtx.Lock()
-	localDiscoverySignal, ok := f.localDiscoverySignals[msg.ChanID]
-	f.localDiscoveryMtx.Unlock()
+	f.handleChannelReadyBarriers.Store(msg.ChanID, struct{}{})
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply funding/manager.go:3428]: > since we no longer do an atomic load-compare-store.

can you elaborate?

[the remark this answers is not in the document]
Comment (yyforyongyu) [reply funding/manager.go:3428]: Godd point! We actually need to use load or store here, updated.

File: peer/brontide.go [hunk 10]
```diff
@@ -403,10 +404,6 @@ type Brontide struct {
 	// objects to queue messages to be sent out on the wire.
 	outgoingQueue chan outgoingMsg
 
-	// activeChanMtx protects access to the activeChannels and
-	// addedChannels maps.
-	activeChanMtx sync.RWMutex
```
[the remark this answers is not in the document]
Comment (Roasbeef) [reply peer/brontide.go:408]: IIRC, the active channels map was originally only ever accessed in the main event loop. Once we added `filterChannelsToEnable` to handle channel enable/disable, then we created that other `addedChannels` map to track the _new_ channels since the peer session was created. 

These maps are also only ever modified right after each other in the main event loop `channelManager`.

[the remark this answers is not in the document]
Comment (Roasbeef) [reply peer/brontide.go:408]: If we wanted to, we could get rid of _both_ these mutexes if we funnel all the state requests through the main `channelManager` goroutine (req+resp over channels).

File: peer/brontide.go [hunk 11]
```diff
@@ -1663,8 +1664,25 @@ func (p *Brontide) handleCustomMessage(msg *lnwire.Custom) error {
...
 func (p *Brontide) isActiveChannel(chanID lnwire.ChannelID) bool {
-	_, ok := p.activeChannels.Load(chanID)
-	return ok
+	// The channel would be nil if,
+	// - the channel doesn't exist, or,
+	// - the channel exists, but is pending. In this case, we don't
+	//   consider this channel active.
+	channel, _ := p.activeChannels.Load(chanID)
+
+	return channel != nil
```
Comment (Roasbeef) [inline peer/brontide.go:1713]: We do we care about nil-ness here? We should just check the second arg to see if it exists or not. 

I know we use the `ok && nil` trick in a few other places, but IMO we should shy away from that in favor of _not_ storing `nil` values in a map to mean a certain state. 

Alternatively, we can make a very simple wrapper struct around the channel itself to be able to thread through another state to fill this new perceived gap.

File: peer/brontide.go [hunk 12]
```diff
@@ -1661,6 +1661,26 @@ func (p *Brontide) handleCustomMessage(msg *lnwire.Custom) error {
...
+
+	// Return false if the channel is unknown.
+	channel, ok := p.activeChannels.Load(chanID)
+	if !ok {
+		return false
+	}
+
+	// During startup, we will use a nil value to mark a pending channel
+	// that's loaded from disk.
+	return channel == nil
```
Comment (Roasbeef) [inline peer/brontide.go:1701]: Ah yeah, this is already in place (`nil values in the map`) and is indeed the first location we started to use that trick...

Comment (Roasbeef) [inline peer/brontide.go:1701]: Ah yeah, this is already in place (nil values in the map) and is indeed the first location we started to use that trick...

File: peer/brontide.go [hunk 13]
```diff
@@ -423,9 +423,9 @@ type Brontide struct {
 	// waited a shorter duration.
 	addedChannels *lnutils.SyncMap[lnwire.ChannelID, struct{}]
 
-	// newChannels is used by the fundingManager to send fully opened
+	// newActiveChannel is used by the fundingManager to send fully opened
```
Comment (Roasbeef) [inline peer/brontide.go:440]: Could use some rationale in the commit body.

File: peer/brontide.go [hunk 14]
```diff
@@ -88,8 +88,13 @@ type outgoingMsg struct {
 // the receiver of the request to report when the channel creation process has
 // completed.
 type newChannelMsg struct {
+	// channel is used when the pending channel becomes active.
 	channel *channeldb.OpenChannel
-	err     chan error
+
+	// channelID is used when there's a new pending channel.
+	channelID lnwire.ChannelID
```
Comment (Roasbeef) [inline peer/brontide.go:104]: Isn't this channel ID already known for _all_ channels? Should it be nil/zero in certain cases?

File: peer/brontide.go [hunk 15]
```diff
@@ -3793,3 +3844,37 @@ func (p *Brontide) handleNewActiveChannel(req *newChannelMsg) {
...
+	// If we already have this channel, something is wrong with the funding
+	// flow as it will only be marked as active after `ChannelReady` is
+	// handled. In this case, we will do nothing but log an error, just in
+	// case this is a legit channel.
+	if p.isActiveChannel(chanID) {
+		p.log.Errorf("Channel(%v) is already active, ignoring "+
+			"pending channel request", chanID)
+
+		return
+	}
```
Comment (Roasbeef) [inline peer/brontide.go:3878]: So we won't load these into the link? If not, then we won't immediately start to send chan reest to mark the new session as active/eligible.

File: funding/manager.go [hunk 16]
```diff
@@ -2162,6 +2162,15 @@ func (f *Manager) continueFundingAccept(resCtx *reservationWithCtx,
 		f.failFundingFlow(resCtx.peer, pendingChanID, err)
 		return
 	}
+
+	// With FundingCreated sent, we can now notify Brontide to keep track
+	// of this pending open channel.
+	err = resCtx.peer.AddPendingChannel(channelID, f.quit)
```
Comment (Roasbeef) [inline funding/manager.go:2168]: Ah ok, makes sense, this is just an active funding attempt that _may_ become a channel in the future. I think we could update some of the `godoc` comments to make that a bit more clear (basically this is where we stage things).

**Review by Roasbeef — CHANGES_REQUESTED** [review]
Nice work! This is pretty much what I had in mind when I left this comment: https://github.com/lightningnetwork/lnd/issues/7401#issuecomment-1435396952. Will be great to finally fix this very long standing bug. 

My main questions surround the new maps added, and if we can get by with _not_ storing `nil` in maps with a pointer value (and rely on just `ok` or a wrapper struct to thread through some new state).

File: peer/brontide.go (hunk 11 above)
Comment (yyforyongyu) [reply peer/brontide.go:1713]: Agree we should avoid the implicit usage of `nil` in map as well. Added a commit before this one to remove it.

File: peer/brontide.go (hunk 12 above)
Comment (yyforyongyu) [reply peer/brontide.go:1701]: Added a new map to handle this specific case.

File: peer/brontide.go (hunk 15 above)
Comment (yyforyongyu) [reply peer/brontide.go:3878]: Updated the docs in `handleNewPendingChannel`.

File: peer/brontide.go (hunk 12 above)
Comment (yyforyongyu) [reply peer/brontide.go:1701]: Tried to implement here, a commit [here](https://github.com/yyforyongyu/lnd/commit/4f033c6a4f4abf2eb6031d0b99e96f4595b18c9a) in a different branch, 

To remove the nil usage, we need three maps,
- `activeChannels` to store active channels only
- `pendingChannels` to store pending channels only
- `reestablishChannels` to store pending channels loaded from disk

I think that's quite some maps...meanwhile I noticed the channel store already have method `lnChan.IsPending()` to decide whether it's pending or not. This leads me to think we should manage the channel state inside funding manager only, and access it from brontide, instead of maintaining yet another state of the channel.

This means we should expand `lnChan` to have methods so the brontide can know its state, like whether it's marked open or channel ready sent. Then inside brontide, we can decide what to do based on the state of the channel saved in `activeChannels`, wdyt?

**Review by Crypt-iQ — COMMENTED** [review]
verrrrry close 🦖 

can you test this with a hacky test (add a sleep somewhere in `handleFundingLocked` and have a peer send `UpdateFee`) to confirm this works?

File: funding/manager.go [hunk 17]
```diff
@@ -2171,6 +2171,15 @@ func (f *Manager) continueFundingAccept(resCtx *reservationWithCtx,
...
```
Comment (morehouse) [inline funding/manager.go:2177]: To fully avoid race conditions for zeroconf, I think we actually need to call `AddPendingChannel` *before* we send `funding_created`.

Otherwise the following sequence of events is possible:

1. We send `funding_created` and then immediately this thread is descheduled (before calling `AddPendingChannel`)
2. Peer sends `funding_signed`
3. Peer immediately sends `channel_ready` and `update_fee` since this is a zeroconf channel
4. Our channel manager processes the `update_fee` and force closes
5. Our `funding_created` thread gets scheduled again and we call `AddPendingChannel`

Comment (Crypt-iQ) [reply funding/manager.go:2177]: great catch

File: peer/brontide.go (hunk 12 above)
Comment (yyforyongyu) [reply peer/brontide.go:1701]: > Can defer convo to a refactor PR, but I don't like using lnChan because it's in-memory.

Agree here. I think we wanna slowly move the subsystems to deal with the db directly, treating the disk records as the single source of truth. Atm we can already do this in `brontide` as it has access to the db instance, maybe in another PR.

File: peer/brontide.go [hunk 18]
```diff
@@ -3743,3 +3650,146 @@ func (p *Brontide) attachChannelEventSubscription() error {
...
+// nil.
+func (p *Brontide) updateNextRevocation(c *channeldb.OpenChannel) {
+	chanPoint := &c.FundingOutpoint
+	chanID := lnwire.NewChanIDFromOutPoint(chanPoint)
+
+	// Read the current channel.
+	currentChan, loaded := p.activeChannels.Load(chanID)
+
+	// currentChan should exist, but we perform a check anyway to avoid nil
+	// pointer reference.
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3726]: fixed

File: peer/brontide.go [hunk 19]
```diff
@@ -3743,3 +3650,146 @@ func (p *Brontide) attachChannelEventSubscription() error {
...
+	}
+
+	// If we've reached this point, there are two possible scenarios.  If
+	// the channel was in the active channels map as nil, then it was
+	// loaded from disk and we need to send reestablish. Else, it was not
+	// loaded from disk and we don't need to send reestablish as this is a
+	// fresh channel.
+	shouldReestablish := p.isLoadedFromDisk(chanID)
+
+	// This refreshes the activeChannels entry if the link was not in the
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3780]: updated.

File: peer/brontide.go [hunk 20]
```diff
@@ -3743,3 +3650,146 @@ func (p *Brontide) attachChannelEventSubscription() error {
...
+	// Only update RemoteNextRevocation if the channel is in the
+	// activeChannels map and if we added the link to the switch. Only
+	// active channels will be added to the switch.
+	if p.isActiveChannel(chanID) {
+		p.log.Infof("Already have ChannelPoint(%v), ignoring",
+			chanPoint)
+
+		// Handle it and close the err chan on the request.
+		p.updateNextRevocation(newChan)
+		close(req.err)
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3840]: Good catch, reverted.

File: peer/brontide.go [hunk 21]
```diff
@@ -3743,3 +3650,146 @@ func (p *Brontide) attachChannelEventSubscription() error {
...
 }
+
+// updateNextRevocation updates the existing channel's next revocation if it's
+// nil.
+func (p *Brontide) updateNextRevocation(c *channeldb.OpenChannel) {
+	chanPoint := &c.FundingOutpoint
+	chanID := lnwire.NewChanIDFromOutPoint(chanPoint)
+
+	// Read the current channel.
+	currentChan, loaded := p.activeChannels.Load(chanID)
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3723]: not sure if I follow. I think using a mutex map will need to read the object first to make sure it exists?

File: funding/manager.go (hunk 17 above)
Comment (yyforyongyu) [reply funding/manager.go:2177]: Nice catch!

File: peer/brontide.go [hunk 22]
```diff
@@ -3891,3 +3917,108 @@ func (p *Brontide) sendLinkUpdateMsg(cid lnwire.ChannelID, msg lnwire.Message) {
...
+	chanID lnwire.ChannelID) bool {
+
+	// Return true if the channel is active.
+	if p.isActiveChannel(chanID) {
+		return true
+	}
+
+	// If the channel is not active, it must be pending, otherwise this
+	// indicates an error.
+	if p.isPendingChannel(chanID) {
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3934]: fixed.

File: funding/manager.go (hunk 17 above)
Comment (yyforyongyu) [reply funding/manager.go:2177]: This leads me to think, we'd need a new method, `CancelPendingChannel` on `brontide` to cancel the channel if the funding flow fails?

File: funding/manager.go [hunk 23]
```diff
@@ -2182,16 +2182,37 @@ func (f *Manager) continueFundingAccept(resCtx *reservationWithCtx,
...
+		f.failFundingFlowAndRemoveChannel(
+			resCtx.peer, channelID, pendingChanID, err,
+		)
 		return
 	}
 }
 
+// failFundingFlowAndRemoveChannel removes the pending channel from Brontide
+// and fails the funding flow.
+func (f *Manager) failFundingFlowAndRemoveChannel(peer lnpeer.Peer,
```
Comment (morehouse) [inline funding/manager.go:2201]: I think there are other cases where we also need to remove the pending channel.  For example, the `fundingTimeout` case.

WDYT about putting the `RemovePendingChannel` directly into `failFundingFlow` and then checking for the pending channel on the brontide side (and doing nothing if it doesn't exist)?

Comment (yyforyongyu) [reply funding/manager.go:2201]: Good catch on the `fundingTimeout` case! Do you think there are more cases? 

> WDYT about putting the RemovePendingChannel directly into failFundingFlow and then checking for the pending channel on the brontide side (and doing nothing if it doesn't exist)?

That's actually my initial approach. It's ditched because I wanna finer control over the communication between the funding manager and the brontide. Plus there are way more `failFundingFlow` calls that use a temp ID, and the current approach seems like a more minor change.

File: peer/brontide.go [hunk 24]
```diff
@@ -2286,25 +2283,30 @@ func (p *Brontide) queue(priority bool, msg lnwire.Message,
 // ChannelSnapshots returns a slice of channel snapshots detailing all
 // currently active channels maintained with the remote peer.
 func (p *Brontide) ChannelSnapshots() []*channeldb.ChannelSnapshot {
-	p.activeChanMtx.RLock()
-	defer p.activeChanMtx.RUnlock()
+	snapshots := make(
+		[]*channeldb.ChannelSnapshot, 0, p.activeChannels.Len(),
+	)
+
+	p.activeChannels.ForEach(func(_ lnwire.ChannelID,
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:2352]: Yeah tbh I'm not too satisfied with the interface of the `syncmap`. It's confusing to use `Range` to decide when to return false or true. That's why I added `ForEach` to explicitly state that this method will go through every item in the list unless you return an error to abort the iteration. Open to change it if others feel the same way too.

File: funding/manager.go (hunk 23 above)
Comment (morehouse) [reply funding/manager.go:2201]: Any failure in `handleFundingSigned`.  I think also some failures in `pruneZombieReservations` may happen when a channel is pending.

File: peer/brontide.go [hunk 25]
```diff
@@ -3898,6 +3935,32 @@ func (p *Brontide) handleNewPendingChannel(req *newChannelMsg) {
...
+// from `activeChannels` map.
+func (p *Brontide) handleRemovePendingChannel(req *newChannelMsg) {
+	defer close(req.err)
+
+	chanID := req.channelID
+
+	// If we already have this channel, something is wrong with the funding
+	// flow as it will only be marked as active after `ChannelReady` is
+	// handled. In this case, we will log an error and remove it.
+	if p.isActiveChannel(chanID) {
```
Comment (Crypt-iQ) [inline peer/brontide.go:3948]: I don't think we should ever remove from `activeChannels` here

File: funding/manager.go (hunk 23 above)
Comment (Crypt-iQ) [reply funding/manager.go:2201]: Basically any calls to `failFundingFlow` after `AddPendingChannel`. We have to be careful with `handleFundingSigned` though and validate that the `msg.ChanID` is actually _from_ the peer in question. This might also be a good time to improve `signedReservations`. There's not an issue there afaict, but the design is wrong and the map should also be keyed by peer id

**Comment by morehouse** [comment]
I haven't looked at the latest update, but I wanted to ask -- can we add a regression test?

There's multiple significant changes in this PR, and many ways it could break in the future.  It would be good to at least make sure we don't reintroduce https://github.com/lightningnetwork/lnd/issues/7401.

**Comment by Roasbeef** [comment]
> I haven't looked at the latest update, but I wanted to ask -- can we add a regression test?

One way to make this a bit easier to test, would be adding in some build flag level attributes, similar to the `hodl` switch tags we use to test some on chain interaction: https://github.com/lightningnetwork/lnd/blob/0005adaac8031625bde0e181dfa24d13acceb081/htlcswitch/hodl/config_dev.go#L1-L29

File: peer/brontide.go [hunk 26]
```diff
@@ -2347,133 +2413,24 @@ func (p *Brontide) channelManager() {
...
-
-			// If we've reached this point, there are two possible scenarios.
-			// If the channel was in the active channels map as nil, then it
-			// was loaded from disk and we need to send reestablish. Else,
-			// it was not loaded from disk and we don't need to send
-			// reestablish as this is a fresh channel.
-			shouldReestablish := ok
-
-			// Create the link and add it to the switch.
-			err = p.addLink(
```
Comment (yyforyongyu) [inline peer/brontide.go:2463]: @Crypt-iQ Have a question re the [analysis made here](https://github.com/lightningnetwork/lnd/issues/7401#issuecomment-1428217893), since these happens in the same goroutine,
1. add the active channel in `peer.Brontide.activeChannels`
2. add the link via `peer.Brontide.addLink`, which asks the switch to eventually call `switch.AddLink`.

This means while the channel is still pending open, there is no link for handle `update_fee` or `update_add_htlc`?

And for `update_add_htlc`, for lnd nodes, I don't think this race could happen because while the channel is still pending, it won't be used for the pathfinding?

**Review by yyforyongyu — COMMENTED** [review]
Added some unit tests, and still trying to work out an itest.

**Comment by yyforyongyu** [comment]
Updated PR with tests, and depends on this PR https://github.com/lightninglabs/neutrino/pull/279 to have the in-order range method now.

**Comment by morehouse** [comment]
This PR is getting quite big and tedious to re-review on force push.  If we could separate out some of the early commits to a separate PR, I think it would help everyone review this better and faster.  It would also allow us to do a smaller revert if something breaks.

I'd be happy to quickly review/approve everything up to [402df14](https://github.com/lightningnetwork/lnd/pull/7518/commits/402df14b3fdd713ba96c172f67b37a46e1139502) in a separate PR.  There's probably other things we could also pull out and quickly approve+submit.

It would be nice to get this PR distilled down to what's needed to fix https://github.com/lightningnetwork/lnd/issues/7401.

**Comment by Roasbeef** [comment]
@morehouse still need to catch up with the PR, but we've been starting to integrate Reviewable into certain PR workflows. I think you're familiar with Critique (Google's internal code review tool), this is essentially that but publicly available. In particular, it lets you review each _revision_ rather than the entire PR set or all commits once again with each force push. I find this very helpful for long lived PRs, as it helps one maintain relative context with each revision. Here's a handy link: https://reviewable.io/reviews/lightningnetwork/lnd/7518

**Comment by yyforyongyu** [comment]
@morehouse added a new PR as suggested as I also prefer small PRs. In the future we can rely on the reviewable to focus on new diff as suggested by @Roasbeef, but ofc we'll limit the PR size first.

File: peer/brontide.go [hunk 27]
```diff
@@ -3742,3 +3761,339 @@ func (p *Brontide) attachChannelEventSubscription() error {
...
+	})
+	if err != nil {
+		p.log.Errorf("Failed to cache msg %s for pending channel: %v, "+
+			"error: %v", msg.MsgType(), chanID, err)
+	}
+
+	p.log.Debugf("Cached early msg %s for pending channel: %v",
+		msg.MsgType(), chanID)
+
+	return false
```
Comment (morehouse) [inline peer/brontide.go:4057]: What happens if we remove all this caching code and just return true?

To me it looks like messages would automatically start queuing until the link becomes active.  If so, we could probably greatly simplify this PR.

**Comment by Roasbeef** [comment]
Can be rebased now!

File: peer/brontide.go (hunk 27 above)
Comment (yyforyongyu) [reply peer/brontide.go:4057]: hmm so you mean we don't need to cache any messages here? Then what if this channel is still pending and we receive an `update_fee` from the remote?

Comment (morehouse) [reply peer/brontide.go:4057]: From what I can tell, if we return `true` from `handleLinkUpdateMsg` for pending channels, then `sendLinkUpdateMsg` will get called.  That will create a `chanStream` to queue messages until the link becomes active.

So we might not need to add all this caching stuff.

Comment (yyforyongyu) [reply peer/brontide.go:4057]: yeah I think you are right! These messages are already saved in the queue in `chanStream` so the early cache here is unnecessary, will remove!

File: peer/brontide.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3890]: ok reverted it again

File: funding/manager.go [hunk 28]
```diff
@@ -859,6 +859,58 @@ func (f *Manager) CancelPeerReservations(nodePub [33]byte) {
...
+	var (
+		cid   lnwire.ChannelID
+		found bool
+	)
+
+	// visitor finds the channel ID based on the tempChanID.
+	visitor := func(chanID lnwire.ChannelID, sig *tempChannelSignal) bool {
+		// Found the matching tempChanID, return false to exit the
+		// iteration.
+		if sig.tempChanID == tempChanID {
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply funding/manager.go:888]: what do you mean "reuse"? Like a repeated pending channel ID after restart? In that case the pending channel is not sent to `brontide` tho.

**Comment by Roasbeef** [comment]
Needs a rebase!

File: funding/manager.go [hunk 29]
```diff
@@ -842,21 +854,47 @@ func (f *Manager) CancelPeerReservations(nodePub [33]byte) {
...
 
 	log.Debugf("Failing funding flow for pending_id=%x: %v",
-		tempChanID, fundingErr)
+		cid.tempChanID, fundingErr)
+
+	// First, notify Brontide to remove the pending channel.
+	//
+	// NOTE: depending on where we fail the flow, we may not have the
+	// active channel ID yet.
+	if !cid.chanID.IsEmpty() {
```
Comment (Crypt-iQ) [inline funding/manager.go:888]: Maybe just have a bool in `chanIdentifier` instead? What if somebody decides to use an all-zero ChannelID for a zero-conf channel?

File: funding/manager.go [hunk 30]
```diff
@@ -887,7 +925,7 @@ func (f *Manager) failFundingFlow(peer lnpeer.Peer, tempChanID [32]byte,
 	}
 
 	errMsg := &lnwire.Error{
-		ChanID: tempChanID,
+		ChanID: cid.tempChanID,
```
Comment (Crypt-iQ) [inline funding/manager.go:928]: I think there's at least one call-site where the _real_ ChannelID is used here, so it wouldn't use the tempChanID

**Review by Crypt-iQ — COMMENTED** [review]
super close, just two comments

File: funding/manager.go (hunk 29 above)
Comment (Crypt-iQ) [reply funding/manager.go:888]: We send to brontide for zero-conf channels. I think it might just be better to have a bool that each caller sets if we should call `RemovePendingChannel` since that seems a lot harder to mess up / no hidden gotchas

Comment (yyforyongyu) [reply funding/manager.go:888]: cool yeah i like the idea. Change to be more explicit!

**Review by morehouse — APPROVED** [review]
Looking pretty clean.

Tested before and after 818dbe0b0966dc48cb5ed8e521d81532b633ae2a:
```bash
$ git checkout pr/7518
$ git checkout 12a41f301b32b0d36181389e6ce0cb6f5cb3cfcf
$ make itest icase=update_pending_open_channels
...
--- FAIL: TestLightningNetworkDaemon (81.04s)
    --- FAIL: TestLightningNetworkDaemon/tranche00/135-of-135/btcd/update_pending_open_channels (76.17s)
        --- FAIL: TestLightningNetworkDaemon/tranche00/135-of-135/btcd/update_pending_open_channels/pending_on_funder_side (68.25s)
        --- FAIL: TestLightningNetworkDaemon/tranche00/135-of-135/btcd/update_pending_open_channels/pending_on_fundee_side (4.58s)

$ git checkout 818dbe0b0966dc48cb5ed8e521d81532b633ae2a
$ make itest icase=update_pending_open_channels
...
--- PASS: TestLightningNetworkDaemon (45.95s)
    --- PASS: TestLightningNetworkDaemon/tranche00/135-of-135/btcd/update_pending_open_channels (40.20s)
        --- PASS: TestLightningNetworkDaemon/tranche00/135-of-135/btcd/update_pending_open_channels/pending_on_funder_side (18.42s)
        --- PASS: TestLightningNetworkDaemon/tranche00/135-of-135/btcd/update_pending_open_channels/pending_on_fundee_side (18.45s)
```

File: peer/brontide.go [hunk 31]
```diff
@@ -3744,32 +3744,30 @@ func (p *Brontide) updateNextRevocation(c *channeldb.OpenChannel) {
...
 	p.log.Infof("Processing retransmitted ChannelReady for "+
 		"ChannelPoint(%v)", chanPoint)
 
 	nextRevoke := c.RemoteNextRevocation
-	err := currentChan.InitNextRevocation(nextRevoke)
-	if err != nil {
-		p.log.Errorf("unable to init chan revocation: %v", err)
-	}
+
+	return currentChan.InitNextRevocation(nextRevoke)
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3789]: make sense, updated.

File: peer/brontide.go [hunk 32]
```diff
@@ -3855,7 +3853,12 @@ func (p *Brontide) handleNewActiveChannel(req *newChannelMsg) {
 
 		// Handle it and close the err chan on the request.
 		close(req.err)
-		p.updateNextRevocation(newChan)
+
+		// Update the next revocation point.
+		if err := p.updateNextRevocation(newChan); err != nil {
+			p.log.Errorf(err.Error())
+			return
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3879]: fixed!

File: peer/brontide.go [hunk 33]
```diff
@@ -3871,6 +3908,34 @@ func (p *Brontide) handleNewPendingChannel(req *newChannelMsg) {
...
+// from `activeChannels` map. The request will be ignored if the channel is
+// considered active by Brontide. Noop if the channel ID cannot be found.
+func (p *Brontide) handleRemovePendingChannel(req *newChannelMsg) {
+	defer close(req.err)
+
+	chanID := req.channelID
+
+	// If we already have this channel, something is wrong with the funding
+	// flow as it will only be marked as active after `ChannelReady` is
+	// handled. In this case, we will log an error and remove it.
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide.go:3943]: fixed!

File: peer/brontide_test.go [hunk 34]
```diff
@@ -1118,3 +1118,56 @@ func TestPeerCustomMessage(t *testing.T) {
 	require.Equal(t, remoteKey, receivedCustom.peer)
 	require.Equal(t, receivedCustomMsg, &receivedCustom.msg)
 }
+
+// TestUpdateNextRevocation checks that the method `updateNextRevocation` is
+// behave as expected.
+func TestUpdateNextRevocation(t *testing.T) {
+	t.Parallel()
+
+	require := require.New(t)
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply peer/brontide_test.go:1128]: just a new trick I learnt from gpt😂 With this initialization, I can write `require.NoError(err)` instead of `require.NoError(t, err)`.

File: funding/manager.go [hunk 35]
```diff
@@ -2382,11 +2429,25 @@ func (f *Manager) handleFundingSigned(peer lnpeer.Peer,
...
+	cid := newChanIdentifier(pendingChanID)
+	cid.setChanID(msg.ChanID)
+
+	// If the pending channel ID is not found, fail the funding flow.
 	if !ok {
 		err := fmt.Errorf("unable to find signed reservation for "+
 			"chan_id=%x", msg.ChanID)
 		log.Warnf(err.Error())
-		f.failFundingFlow(peer, msg.ChanID, err)
+		f.failFundingFlow(peer, cid, err, true)
```
[the remark this answers is not in the document]
Comment (yyforyongyu) [reply funding/manager.go:2474]: Very clever, I like it!

File: funding/manager.go (hunk 30 above)
Comment (yyforyongyu) [reply funding/manager.go:956]: With the latest push this is now fixed.

**Review by morehouse — APPROVED** [review]
LGTM with a couple nits.

**Review by Crypt-iQ — APPROVED** [review]

File: funding/manager.go [hunk 36]
```diff
@@ -2365,11 +2437,30 @@ func (f *Manager) handleFundingSigned(peer lnpeer.Peer,
...
+	//
+	// TODO(yy): refactor the funding flow to fix this case.
+	cid := newChanIdentifier(pendingChanID)
+	cid.setChanID(msg.ChanID)
+
+	// If the pending channel ID is not found, fail the funding flow.
 	if !ok {
+		// NOTE: we directly overwrite the pending channel ID here for
+		// this rare case, which can be removed once we can make sure
+		// the pending channel ID is always found here.
```
[the remark this answers is not in the document]
Comment (morehouse) [reply funding/manager.go:2456]: We *could* check the channel ID in `peer/brontide.go` and handle it there if there's no pending channel for that ID.  Then we could guarantee that only real channel IDs end up in `handleFundingSigned`.  But please don't do that -- funding manager is a better place for this.

I think we should replace the second part of the comment:
```suggestion
		// this rare case since we don't have a valid pending channel ID.
```

[the remark this answers is not in the document]
Comment (yyforyongyu) [reply funding/manager.go:2456]: yeah that's not what brontide is for. Updated the comments.

**Review by morehouse — APPROVED** [review]
ACK f9d4212eccc1760a29ef8f1bb8c350428147bec9
