### PR TITLE
contractcourt/contract_resolvers: correct off-by-one HTLC expiry

### LINKED ISSUE #1632: [Test flake] htlc mismatch: predicate not satisfied after time out
The integration test suite currently fails sometimes with the error 
```
    --- PASS: TestLightningNetworkDaemon/test_multi-hop_htlc_local_chain_claim (7.50s)
    --- PASS: TestLightningNetworkDaemon/test_multi-hop_htlc_remote_chain_claim (7.45s)
    --- FAIL: TestLightningNetworkDaemon/switch_circuit_persistence (37.02s)
    	lnd_test.go:74: Failed: (switch circuit persistence): exited with error: 
    		*errors.errorString htlc mismatch: predicate not satisfied after time out
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:9428 (0xc089ce)
    			testSwitchCircuitPersistence: t.Fatalf("htlc mismatch: %v", err)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:99 (0xbcaccb)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:11258 (0xc236ba)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 (0x4f6aa0)
    			tRunner: fn(t)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337 (0x45ecf1)
    			goexit: BYTE	$0x90	// NOP
```
See for instance: https://travis-ci.org/lightningnetwork/lnd/jobs/407553324

This is the line where it fails: https://github.com/lightningnetwork/lnd/blob/5299472fad9e67d2875892f304641f80fb7ce325/lnd_test.go#L9428

It most often happen on Travis, which indicates this is more likely to happen on slow boxes.

### Steps
- [ ] (easy) Correct the error logging for this error. `assertNumActiveHtlcs` should be changed to return an error indicating how many HTLCs were active when failure happened.
- [ ] Get rid of the test failure.

### PR DESCRIPTION
**Pull request by halseth**
This commit attempts to fix an inconsistency in when we consider an HTLC
to expire. When we first launched the resolver we would compare the
current block height agains the expiry, while for new incoming blocks
we would compare against expiry-1.

This lead to a flake during integration tests, during a call to
RestartNode after _exactly_ enough blocks for the HTLC to expire. In
some cases the resolver would see the new blocks and consider the HTLC
to be expired (because of the -1), while in some cases resolver would
shut down before seeing the new blocks, and upon restart wouldn't act on
the new height because we did not compare against -1.

This commit fixes this by doing the same comparison in both cases.

Fixes #1632

### CODE REVIEW

**Comment by cfromknecht** [comment]
nice, looks correct to me! i would guess that the contest resolver should also do the same thing, can't think of why not atm

**Comment by Roasbeef** [comment]
Repeating the convo here: it's minus one atm as we want to ensure that the HTLC is already present in the nursery by the time its actually eligible to be included in a block. When this was written, we didn't have the concept of "late graduation" in the nursery yet.

File: contractcourt/contract_resolvers.go [hunk 1]
```diff
@@ -822,7 +822,7 @@ func (h *htlcOutgoingContestResolver) Resolve() (ContractResolver, error) {
 	if err != nil {
 		return nil, err
 	}
-	if uint32(currentHeight) >= h.htlcResolution.Expiry {
+	if uint32(currentHeight) >= h.htlcResolution.Expiry-1 {
```
Comment (wpaulino) [inline contractcourt/contract_resolvers.go]: We should update the comment to note that we now mine a block earlier and the reason for doing so.

**Comment by cfromknecht** [comment]
Is this PR ready?

**Comment by halseth** [comment]
Ready.
