### PR TITLE
Filter out bitcoind mempool spends

### LINKED ISSUE #1341: Force closing channel looking for txid different than one actually mined. Funds in limbo.
### Background

I was using autopilot to open a new channel, but my node was shut down before the transaction was mined. When I was syncing up my node a few hours later, starting LND while bitcoind was scanning the 6 previous blocks, I received an error about the block height being less than previous and LND crashed.

I restarted LND, and everything synced back up and the channel was shown as opened. I tried to pay an invoice, but the payment never completed. That was when I noticed that the channel was being forced closed. I never saw an actual error message about that payment.

The closing_txid does not match the actual closing transaction on chain and as such, LND is unable to detect that the close has finished.

Opening transaction: https://www.smartbit.com.au/tx/0932213005e5023d5acc5a66ef40be7e4fbf08b52b88c55598643036288e3380

lncli pendingchannels | jq ".pending_force_closing_channels[0]"                                                                                  

```json
{
  "channel": {
    "remote_node_pub": "024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed",
    "channel_point": "0932213005e5023d5acc5a66ef40be7e4fbf08b52b88c55598643036288e3380:1",
    "capacity": "1600000",
    "local_balance": "1599819",
    "remote_balance": "0"
  },
  "closing_txid": "3428ff4021fb0e75233506442d1f19d416a7eb06c8e1d38bd6a47b00618c90c2",
  "limbo_balance": "1599819",
  "maturity_height": 0,
  "blocks_til_maturity": 0,
  "recovered_balance": "0",
  "pending_htlcs": []
}
```

Actual closing transaction: https://www.smartbit.com.au/tx/65e0596a71c671136a62b9530231ed84ec3bef4a02aac6349ec3448e237262e3

Additional details can be found in the slack thread: https://lightningcommunity.slack.com/archives/C6BKD3RKR/p1528316418000738

A copy of logs collected with an additional log line dumping resolver information can be found at: https://duck1123.keybase.pub/lnd-patched.log.gz

Unfortunately, all logs from the time this error occurred have already been rotated out. 

### Your environment

* LND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
  * Compiled from source: go version go1.10 linux/amd64
* Linux cybertronix 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255

### Steps to reproduce

Begin to open channel but shut down node before funding transaction can confirm. After transaction confirms, have remote party force close the channel.

Start bitcoind, and while it is rewinding the last 6 blocks start lnd and after it crashes, start it again.

### Expected behaviour

Channel should be closed once closing transaction is complete. Locked funds should be returned to wallet.

### Actual behaviour

Channel still listed under "pending_force_closing_channels" despite closing transaction having 370+ confirmations. Funds in limbo.

### PR DESCRIPTION
**Pull request by halseth**
This commit fix a bug within the bitcoind notifier logic, which would
ignore the passed mempool argument, and notify spentness whether the
spending transaction was confirmed or not. The logic used to fix this is
similar to what is already done for the btcd backend.

NOTE: mempool spends will be removed entirely in the near future. 

Fixes #1341.

### CODE REVIEW

File: chainntnfs/interface_test.go [hunk 1]
```diff
@@ -425,14 +425,30 @@ func testSpendNotification(miner *rpctest.Harness,
...
+	mempoolSpendTimeout := 10 * time.Second
+	mempoolSpends := make(chan *chainntnfs.SpendDetail, numClients)
 	for _, c := range spendClients {
-		select {
-		case <-c.Spend:
-			t.Fatalf("did not expect to get notification before " +
-				"block was mined")
-		case <-time.After(50 * time.Millisecond):
-		}
+		go func(client *chainntnfs.SpendEvent) {
```
Comment (wpaulino) [inline chainntnfs/interface_test.go]: :+1:

**Comment by halseth** [comment]
Good question! Turns out `bitcoind` doesn't notify correctly on spends already existing in the mempool when the spend client is registered, so I decided not to debug this further as it is all gonna be removed in #1531.
