### PR TITLE
aliasmgr+channeldb: stop deleting zero-conf edges from graph if reorg occurs

### LINKED ISSUE #7229: [bug]: GetChanInfo returns an error for zero-conf channels
### Background

To update channel fees, you can use the UpdateChannelPolicy and then use GetChanInfo to confirm the fee rate update was applied, but for zero-conf channels the latter API call returns an error

So when looking up such a channel with GetChanInfo, it should return the channel info

### Your environment

- LND 0.15.5-beta

### Steps to reproduce

- Create a zero-conf channel
- Update the fee rate
- Check that the fee rate was applied

### Expected behavior

- The fee rate should be returned

### Actual behavior

- Error is returned

### PR DESCRIPTION
**Pull request by Crypt-iQ**
Fixes #7229 

Description of issue:

When a block is disconnected due to a reorg, DisconnectBlockAtHeight is called for the block height. Prior to this patch, it would delete every SCID in the graph with a block height greater than the disconnected height. This meant that a reorg would delete every zero-conf channel edge from the graph. The fix simply iterates up until the StartingAlias and deletes every SCID between the disconnected height and the StartingAlias height.

An integration test is included that asserts that the fix works.

### CODE REVIEW

File: channeldb/graph.go [hunk 1]
```diff
@@ -1525,12 +1526,10 @@ func (c *ChannelGraph) DisconnectBlockAtHeight(height uint32) ([]*ChannelEdgeInf
...
 
-	// Delete everything after this height from the db.
-	endShortChanID := lnwire.ShortChannelID{
-		BlockHeight: math.MaxUint32 & 0x00ffffff,
-		TxIndex:     math.MaxUint32 & 0x00ffffff,
-		TxPosition:  math.MaxUint16,
-	}
+	// Delete everything after this height from the db up until the
+	// SCID alias range.
+	endShortChanID := aliasmgr.StartingAlias
```
Comment (Roasbeef) [inline channeldb/graph.go:1531]: What about permitting access to the actual scid range and existing set? Otherwise seems like this would be lossy and end up _not_ deleting some items that it actually should.

Comment (Crypt-iQ) [reply channeldb/graph.go:1531]: Since these are zero-conf channels, I don't think they ever need to be removed from the graph in case of a reorg

Comment (Crypt-iQ) [reply channeldb/graph.go:1531]: In the normal non-zero-conf case, I'm not sure how our code will handle a reorg removing the edge from the graph. I don't think another `ChannelAnnouncement` will be sent to the gossiper from the funding manager. If I'm right that means that the edge will just stay deleted similar to this case

Comment (Crypt-iQ) [reply channeldb/graph.go:1531]: > In the normal non-zero-conf case, I'm not sure how our code will handle a reorg removing the edge from the graph. I don't think another `ChannelAnnouncement` will be sent to the gossiper from the funding manager. If I'm right that means that the edge will just stay deleted similar to this case

Apparently this is what the `testOpenChannelAfterReorg` does. I guess there's nothing we can do about it since the spec doesn't prescribe what to do if the funding tx is reorged out

File: lntest/itest/lnd_zero_conf_test.go [hunk 2]
```diff
@@ -1068,3 +1070,209 @@ func testOptionScidUpgrade(net *lntest.NetworkHarness, t *harnessTest) {
...
+	_ = sendAndAssertSuccess(
+		t, carol, &routerrpc.SendPaymentRequest{
+			PaymentRequest: daveInvoiceResp.PaymentRequest,
+			TimeoutSeconds: 60,
+			FeeLimitMsat:   noFeeLimitMsat,
+		},
+	)
+
+	// We will now attempt to query for the alias SCID in Carol's graph.
+	// The starting alias is 16_000_000:0:0 so that is the SCID we will
```
Comment (GeorgeTsagk) [inline lntest/itest/lnd_zero_conf_test.go:1153]: How do we know that this is the starting alias?

**Review by GeorgeTsagk — APPROVED** [review]
LGTM :chains:

File: channeldb/graph.go (hunk 1 above)
Comment (morehouse) [reply channeldb/graph.go:1531]: > Apparently this is what the testOpenChannelAfterReorg does. I guess there's nothing we can do about it since the spec doesn't prescribe what to do if the funding tx is reorged out

If we have an alias SCID for a non-zero-conf channel, I think we would still want the channel to be pruned from the graph on reorg (existing behavior).  Otherwise we might try to route payments through the non-existent channel.

Comment (Crypt-iQ) [reply channeldb/graph.go:1531]: Non-zero-conf channels are not stored in the graph by their alias SCID. They still have an alias, but it is not stored in the graph this way. Only public zero-conf channels before 6 confirmations and private zero-conf channels will be stored in the graph via their alias SCID.

File: lntest/itest/lnd_zero_conf_test.go (hunk 2 above)
Comment (Crypt-iQ) [reply lntest/itest/lnd_zero_conf_test.go:1153]: It's what's defined in the aliasmgr. Though I think we can just import it instead

**Review by jerry47738 — APPROVED** [review]
7229

File: aliasmgr/aliasmgr.go [hunk 3]
```diff
@@ -53,10 +53,10 @@ var (
 	// endBlockHeight is the ending block height of the alias range.
 	endBlockHeight = 16_250_000
 
-	// startingAlias is the first alias ShortChannelID that will get
+	// StartingAlias is the first alias ShortChannelID that will get
```
Comment (positiveblue) [inline aliasmgr/aliasmgr.go:56]: I was checking the Bolts but I do not see the `startingBlockHeight`. 

Is this standardized or each implementation will set their own start block?  I expected to find it in [BOLT2](https://github.com/lightning/bolts/blob/b38156b9510c0562cf50f8758a64602cc0315c19/02-peer-protocol.md)

File: lntest/itest/lnd_zero_conf_test.go [hunk 4]
```diff
@@ -1068,3 +1070,209 @@ func testOptionScidUpgrade(net *lntest.NetworkHarness, t *harnessTest) {
 		},
 	)
 }
+
+// testZeroConfReorg tests that a reorg does not cause a zero-conf channel to
+// be deleted from the channel graph. This was previously the case due to logic
+// in the function DisconnectBlockAtHeight.
+func testZeroConfReorg(net *lntest.NetworkHarness, t *harnessTest) {
+
```
Comment (positiveblue) [inline lntest/itest/lnd_zero_conf_test.go:1078]: nit: extra line not needed.

**Review by positiveblue — APPROVED** [review]
tACK :+1:

File: aliasmgr/aliasmgr.go (hunk 3 above)
Comment (Crypt-iQ) [reply aliasmgr/aliasmgr.go:56]: We define this in the `aliasmgr` package - it's implementation-defined

**Comment by guggero** [comment]
Needs a rebase and fix for the linter.

File: lntest/itest/temp_lnd_test.go [hunk 5]
```diff
@@ -55,9 +55,9 @@ var (
 // TestLightningNetworkDaemonTemp performs a series of integration tests
 // amongst a programmatically driven network of lnd nodes.
 func TestLightningNetworkDaemonTemp(t *testing.T) {
-	if !*tempTest {
-		t.Skip("Running old tests, new tests are skipped")
-	}
+	// if !*tempTest {
```
Comment (guggero) [inline lntest/itest/temp_lnd_test.go:58]: If you comment this out, all tests are run in the "old" tests. You can run a specific test case of the new tests with `make itest icase=xyz temptest=true`.

**Review by guggero — CHANGES_REQUESTED** [review]

File: lntest/itest/temp_lnd_test.go (hunk 5 above)
Comment (Crypt-iQ) [reply lntest/itest/temp_lnd_test.go]: I accidentally committed this

**Review by guggero — APPROVED** [review]
