### PR TITLE
lnd: only set payment address if not empty in PaymentRequest

### LINKED ISSUE #5413: Keysend using gRPC lnrpc.Lightning.SendPayment fails if PaymentAddr is empty
### Background

Using the `lnrpc.Lightning.SendPayment` gRPC fails with the error `incorrect_payment_details` if `PaymentAddr` in the `SendRequest` is empty using keysend.

### Your environment

* version of `lnd`: 0.13.0

### Steps to reproduce

Calling `lnrpc.Lightning.SendPayment` with e.g. the `SendRequest` used for a keysend:

```
{
  "dest": DestPubKey,
  "amt": Amount,
  "payment_hash": PayHash,
  "final_cltv_delta": 40,
  "dest_custom_records": {
    "5482373484": Preimage
  }
}
```

### Expected behaviour

Keysend should be successful.

### Actual behaviour

It seems that 46c9140ac0c6401ba682b319abfae880ea6fe600 which fixed a nil-panic regarding not defining the `PaymentAddr` did not address the case that when it is _not_ specified an empty bytearray is used instead of its nil value.

Hence https://github.com/lightningnetwork/lnd/blob/f9a51882c469e5ea35c21074d20fa6d333f24b25/rpcserver.go#L4353 copies per default the empty bytearray, which will later down in the function call cause an incorrect_payment_details as a correct Payment Address is expected.

### PR DESCRIPTION
**Pull request by bjarnemagnussen**
## Background

This PR addresses an issue where not defining a payment address with the `SendPaymentRequest` results in a `payment_incorrect_details` error for:
* keysend payments, and 
* in LND versions <=0.11 when defining the payment directly using the pubkey in `Dest` and `PaymentHash` instead of using an invoice with `PaymentRequest`.

The error occurs as not defining a payment address with the `SendPaymentRequest` results in an _empty_ payment address byte array in the `paymentIntent` instead of a nil-value.

fixes #5413

### CODE REVIEW

File: rpcserver.go [hunk 1]
```diff
@@ -4347,10 +4347,14 @@ func (r *rpcServer) extractPaymentIntent(rpcPayReq *rpcPaymentRequest) (rpcPayme
...
-	if payIntent.paymentAddr == nil {
+	// Set the payment address if it was explicitly defined with the
+	// rpcPaymentRequest.
+	// Note that the payment address for the payIntent should be nil if none
+	// was provided with the rpcPaymentRequest.
+	if len(rpcPayReq.PaymentAddr) != 0 {
 		payIntent.paymentAddr = &[32]byte{}
+		copy(payIntent.paymentAddr[:], rpcPayReq.PaymentAddr)
 	}
-	copy(payIntent.paymentAddr[:], rpcPayReq.PaymentAddr)
```
Comment (Roasbeef) [inline rpcserver.go:4353]: Ahh, so this ended up copying a _zero valued_ payment address, which was rejected as it's used as a shibboleth elsewhere in the codebase.

**Review by Roasbeef — CHANGES_REQUESTED** [review]
Solid fix! IMO the only thing missing here is updating the itests (`testSingleHopInvoice`) to account for this change. Looking at the [existing test case for keysend we have](https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_single_hop_invoice_test.go#L147) I don't see how this _wasn't_ already covered, given the request is identical to the proto sample you posted in the original issue.

**Comment by Roasbeef** [comment]
> I don't see how this wasn't already covered, given the request is identical to the proto sample you posted in the original issue.

Ah I think the difference here is all our itests [use `SendPaymentV2` and not the deprecated](https://github.com/lightningnetwork/lnd/blob/1287328678c2c6c31792287bb413d46714af0c9c/lntest/itest/lnd_test.go#L13656) variant on the main Lightning service.

**Comment by bjarnemagnussen** [comment]
Right, I was also wondering why the itest hadn't picked this up but just as you mention it is not tested for this `SendPayment` (probably due to deprecation?).

**Comment by Roasbeef** [comment]
NP, it all makes sense now, and also explains why we didn't catch this when testing on the CLI as the CLI uses all the v2 calls. Given that we worked to move all the integration tests over to using the v2 APIs, I think this can land as is.

**Review by Roasbeef — APPROVED** [review]
LGTM 🛰

Ran the itests locally, it's hitting some failures due to a regression (after 0.13) that #5429 should fix.
