### PR TITLE
htlcswitch: log fixes

### LINKED ISSUE #3656: Unfounded [ERR] HSWC: Unable to find target channel for HTLC settle/fail
### Background

This following ERR shows up in the log when there is no error situation.

```
2019-10-31 15:56:26.196 [ERR] HSWC: Unable to find target channel for HTLC settle/fail: channel ID = 13073:1:0, HTLC ID = 1
2019-10-31 15:56:26.196 [ERR] HSWC: ChannelLink(13073:1:0): unhandled error while forwarding htlc packet over htlcswitch: Unable to find target channel for HTLC settle/fail: channel ID = 13073:1:0, HTLC ID = 1
```

This seems to have been introduced in https://github.com/lightningnetwork/lnd/pull/3143

### Your environment

* `lnd 0.8`

### Steps to reproduce

Send a payment

### Expected behaviour

No errors expected

### Actual behaviour

Error above shows up

### PR DESCRIPTION
**Pull request by Crypt-iQ**
This PR fixes the error log intro'd in #3143 when pipelining settles to the switch, and makes logging less spammy and more informative.  The PR breakdown is as follows:

- First commit changes the fallback in `NextLocalHtlcIndex` to `RemoteCommitment` since `LocalCommitment` lags behind for the `LocalHtlcIndex` field. Without this bug fix, open circuits could get prematurely trimmed, resulting in more error logs. A test case is included to check that the fix works.
- Second commit returns `ErrLinkShuttingDown` so that the link logs when it's getting shut down. Also changes the order of the `ackDownStreamPackets` and check-if-link-quit call for consistency since the packets should be ACKed before going down.
- Final commit changes the switch to only log an error if a `update_fail_htlc` comes in and `closeCircuit` returns `ErrUnknownCircuit`. Rationale being that only settles should hit this code path, anything else is a result of a link flap.

Closes #3656

### CODE REVIEW

File: htlcswitch/link_test.go [hunk 1]
```diff
@@ -3158,6 +3158,161 @@ func TestChannelLinkTrimCircuitsNoCommit(t *testing.T) {
...
+
+		err := bobChan.ReceiveNewCommitment(sig.CommitSig, sig.HtlcSigs)
+		if err != nil {
+			t.Fatalf("unable to receive new commitment: %v", err)
+		}
+	case <-time.After(time.Second):
+	}
+
+	// Next, revoke Bob's current commitment and send it to Alice so that we
+	// can test that Alice's circuits aren't trimmed.
```
Comment (cfromknecht) [inline htlcswitch/link_test.go]: ah got it, can see how this would lead to those pesky error logs!

File: htlcswitch/link.go [hunk 2]
```diff
@@ -2069,11 +2073,7 @@ func (l *channelLink) updateCommitTx() error {
 		Htlcs:   pendingHTLCs,
 	}:
 	case <-l.quit:
-		return nil
-	}
-
-	if err := l.ackDownStreamPackets(); err != nil {
-		return err
+		return ErrLinkShuttingDown
```
Comment (cfromknecht) [inline htlcswitch/link.go]: 👍

File: htlcswitch/switch.go [hunk 3]
```diff
@@ -1164,6 +1164,10 @@ func (s *Switch) handlePacketForward(packet *htlcPacket) error {
 			return err
 		}
 
+		if circuit == nil {
```
Comment (cfromknecht) [inline htlcswitch/switch.go]: could use a comment here explaining when we expect the circuit to be nil

Comment (Crypt-iQ) [reply htlcswitch/switch.go]: done, could you check out my comment and see if it's all good

File: htlcswitch/link_test.go (hunk 1 above)
Comment (Crypt-iQ) [reply htlcswitch/link_test.go]: 👍

File: htlcswitch/link_test.go [hunk 4]
```diff
@@ -3158,6 +3158,161 @@ func TestChannelLinkTrimCircuitsNoCommit(t *testing.T) {
...
+	// Both of these circuits should have successfully added, as this is the
+	// first attempt to send them.
+	if len(fwdActions.Adds) != numHtlcs {
+		t.Fatalf("expected %d circuits to be added", numHtlcs)
+	}
+	alice.assertNumPendingNumOpenCircuits(2, 0)
+
+	// Since both were committed successfully, we will now deliver them to
+	// Alice's link.
+	for _, addPkt := range addPkts[:numHtlcs] {
```
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply htlcswitch/link_test.go]: 👍

File: htlcswitch/link_test.go [hunk 5]
```diff
@@ -3158,6 +3158,161 @@ func TestChannelLinkTrimCircuitsNoCommit(t *testing.T) {
...
+		numHtlcs = 2
+	)
+
+	// We'll start by creating a new link with our chanAmt (5 BTC).
+	aliceLink, bobChan, batchTicker, start, cleanUp, restore, err :=
+		newSingleLinkTestHarness(chanAmt, 0)
+	if err != nil {
+		t.Fatalf("unable to create link: %v", err)
+	}
+	defer cleanUp()
```
[the remark this answers is not in the document]
Comment (Crypt-iQ) [reply htlcswitch/link_test.go]: yup good catch

File: channeldb/channel.go [hunk 6]
```diff
@@ -2079,7 +2079,7 @@ func (c *OpenChannel) AdvanceCommitChainTail(fwdPkg *FwdPkg) error {
 // NextLocalHtlcIndex returns the next unallocated local htlc index. To ensure
 // this always returns the next index that has been not been allocated, this
 // will first try to examine any pending commitments, before falling back to the
-// last locked-in local commitment.
+// last locked-in remote commitment.
```
Comment (Roasbeef) [inline channeldb/channel.go]: Commit message should include that fragment in the body message of this PR.

File: htlcswitch/link.go [hunk 7]
```diff
@@ -2060,6 +2060,10 @@ func (l *channelLink) updateCommitTx() error {
 		return err
 	}
 
+	if err := l.ackDownStreamPackets(); err != nil {
```
Comment (Roasbeef) [inline htlcswitch/link.go]: Same comment here re having the commit body populated with the fragment related to this commit from the main PR body.

File: htlcswitch/switch.go (hunk 3 above)
Comment (cfromknecht) [reply htlcswitch/switch.go]: looks good to me 👍
